angular/angular-cli

- .circleci/config.yml
- package.json
- scripts/saucelabs/start-tunnel.sh
- scripts/saucelabs/stop-tunnel.sh
- scripts/saucelabs/wait-for-tunnel.sh
- tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js
- tests/legacy-cli/e2e/tests/misc/browsers.ts
- yarn.lock
The following browsers are being tested against a production build of the CLI (includes differential loading, AOT, and optimization):
- Chrome: 41, 75
- Safari: 9.0, ~~10.1~~**, 11.1, 12.1
- Firefox: 48, 60, 68
- IE: 10, 11
- Edge: 14, 17, 18
** This browser is currently failing and disabled pending additional investigation.   Safari 10.1 has a javascript execution error and may be a legitimate failure.  See comments in code for some further details.
> test: integrate browser testing for differential loading

- packages/schematics/angular/application/files/tsconfig.spec.json.template
If a project is generated with `enableIvy`, this commit adds the necessary configuration to `tsconfig.spec.json` to then run the tests with Ivy. Note that the CLI already does the correct work (runs `ngcc` and then runs the tests).
cc @filipesilva as we talked about it on Slack
> feat(@schematic/angular): enable ivy in tests

- packages/angular/cli/commands/analytics-long.md
- packages/angular/cli/commands/analytics.json
The possible values are in the JSON (and an error message) but are not mentioned in the doc.
This is probably true of all enum values - in the standard API doc, value types are automatically extracted into the doc, but since these are always strings, we don't do that. We should have a way to automatically include enumerated value descriptions, that would go into the arg description. 
For now, I've put them into a long-description for the command.
> Document possible values of analytics command

- etc/api/angular_devkit/schematics/tools/index.d.ts
- packages/angular/cli/models/schematic-command.ts
- packages/angular_devkit/schematics/tools/description.ts
- packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
- packages/angular_devkit/schematics/tools/workflow/node-workflow_spec.ts
- packages/angular_devkit/schematics_cli/bin/schematics.ts
Fix #14986
This PR includes some refactoring to simplify the interaction of the `NodeWorkflow` and the `BaseWorkflow` with the registry.
We were registering redundant `addPostTransform`s. Some of them in the constructor of the `BaseWorkflow`, which did not allow us to intercept `addUndefinedDefaults`.
Additionally, we were setting the `validateOptionsWithSchema` transform multiple times unnecessarily.
An issue left to fix is support for the `--project` option in schematic commands. Currently, `getProjectName` does not know about this option, since `createWorkflow` does not know how to parse the command line arguments. The parsing logic is implemented partially by the concrete implementation of the `SchematicCommand` template method.
> fix(@angular/cli): use correct schematic defaults considering workspace

- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html_spec.ts
- packages/angular_devkit/build_angular/test/browser/cross-origin_spec_large.ts
- packages/angular_devkit/build_angular/test/browser/index_spec_large.ts
- packages/angular_devkit/build_angular/test/browser/scripts-array_spec_large.ts
- packages/angular_devkit/build_angular/test/browser/service-worker_spec_large.ts
- packages/angular_devkit/build_angular/test/browser/styles_spec_large.ts
- packages/angular_devkit/build_angular/test/dev-server/index_spec_large.ts
- tests/legacy-cli/e2e/tests/basic/scripts-array.ts
- tests/legacy-cli/e2e/tests/basic/styles-array.ts
- tests/legacy-cli/e2e/tests/build/polyfills.ts
- tests/legacy-cli/e2e/tests/build/styles/extract-css.ts
- tests/legacy-cli/e2e/tests/misc/support-ie.ts
- tests/legacy-cli/e2e/tests/misc/support-safari-10.1.ts
- tests/legacy-cli/e2e/tests/third-party/bootstrap.ts
This change synchronizes the behavior of classic scripts and module scripts (`type="module"`).  Module scripts are deferred by default.  Also, certain injected scripts are not considered module scripts even in a ES2015+ build due to the strict mode behavior of module scripts.  Deferring such scripts also ensures consistent execution in those scenarios.
> feat(@angular-devkit/build-angular): add defer attributes to classic scripts

- packages/schematics/angular/universal/files/root/__tsconfigFileName__.json.template
- packages/schematics/angular/universal/index_spec.ts
The universal tsconfig extends the application tsconfig which by default it's module format is ES2015. While NodeJS 12 does support this, older versions of Node don't
> fix(@schematics/angular): add commonjs module to universal tsconfig

- packages/angular_devkit/build_angular/test/browser/errors_spec_large.ts
- packages/angular_devkit/build_angular/test/browser/lazy-module_spec_large.ts
- packages/angular_devkit/build_angular/test/browser/output-hashing_spec_large.ts
- packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
- packages/schematics/angular/application/files/tsconfig.app.json.template
- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/universal/files/root/__tsconfigFileName__.json.template
- packages/schematics/angular/universal/index_spec.ts
- tests/angular_devkit/build_angular/hello-world-app-ivy/src/tsconfig.app.json
- tests/angular_devkit/build_angular/hello-world-app-ivy/src/tsconfig.server.json
- tests/angular_devkit/build_angular/hello-world-app/src/tsconfig.app.json
- tests/angular_devkit/build_angular/hello-world-app/src/tsconfig.server.json
- tests/legacy-cli/e2e/tests/basic/rebuild.ts
- tests/legacy-cli/e2e/tests/build/build-app-shell.ts
- tests/legacy-cli/e2e/tests/build/build-errors.ts
- tests/legacy-cli/e2e/tests/build/dynamic-import.ts
- tests/legacy-cli/e2e/tests/build/lazy-load-syntax.ts
- tests/legacy-cli/e2e/tests/build/platform-server.ts
- tests/legacy-cli/e2e/tests/misc/lazy-module.ts
With the omission of `includes` or `files` in tsconfig files tsc will pick up all the files under the rootDir and make them as part of the compilation. In certain cases, redundant files will be picked up which will cause a slower compilations.
Related to: TOOL-949
> fix(@schematics/angular): exclusively list the files in tsconfigs

- packages/schematics/angular/application/other-files/app.component.ts.template
When you generate an application with `--minimal` flag, the image in the
HTML template of the root component doesn't have the 'alt' attribute
> fix(@schematics/angular): the required 'alt' attribute is missing

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
Webpack and its development server assume the presence of two node builtins (`events` & `querystring`).  Due to package hoisting, npm/yarn will usually place the shims for those two builtins at locations that webpack can find them.  This is however not guaranteed nor will it work with pnpm which strictly follows the prescribed dependency tree.
To remedy this, the specific node shims are enabled only for the specific internal webpack files that are used within the development server.  This ensures that the requirements of these files does not pollute the entire application.
Fixes #13680
> fix(@angular-devkit/build-angular): support pnpm with ng serve

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/bundle-budget.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator.ts
- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/test/browser/aot_spec_large.ts
- packages/angular_devkit/build_angular/test/browser/bundle-budgets_spec_large.ts
- packages/ngtools/webpack/src/resource_loader.ts
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/migrations/update-9/update-workspace-config.ts
- packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
- packages/schematics/angular/utility/config.ts
- packages/schematics/angular/utility/json-utils.ts
- packages/schematics/angular/utility/workspace-models.ts
It’s very easy to inadvertently import toplevel css in component styles. Since component css is standalone and self-contained, it will never be shared between components and remains as a single large bundle for each component. This in turn adds a large amount of code that must be processed and increases bundle size.
Note: this will only work for AOT compilations
Related to: TOOL-949
> feat(@angular-devkit/build-angular): add bundle budget for component styles

- packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
- packages/ngtools/webpack/src/compiler_host.ts
> fix(@ngtools/webpack): delete all virtual files for styles on change

- tests/legacy-cli/e2e/utils/project.ts
Fixes issues when `ng-snapshots` option is used.  Otherwise an older version of the CLI packages could potentially be used. Some minor import statement re-ordering included as well to remove numerous lint errors.
> test: ensure E2E locally published packages are used

- packages/angular_devkit/build_angular/package.json
- yarn.lock
sass version `1.22.8` was rolled back and is no longer available on NPM
Supersedes https://github.com/angular/angular-cli/pull/15162
> fix(@angular-devkit/build-angular): rollback sass to version `1.22.7`

- packages/angular/cli/models/parser.ts
At the moment we are adding leftover args to `--` even when it's an empty array, this causes schematics without arguments to fail silently, because of https://github.com/angular/angular-cli/blob/07780b9272d985606d318da16d732dd28a41d592/packages/angular/cli/models/schematic-command.ts#L463
Fixes: #15156
> fix(@angular/cli): don't add leftovers when there are none

- .circleci/config.yml
snapshots builds are required to be run when the PR is created by renovate. This is because we have renovate jobs that update the snapshots commit SHA and we want to verify that these are green prior to merging them.
Related to: https://github.com/angular/angular-cli/pull/14687
> ci: enable snapshot e2e for renovate PRs

- packages/ngtools/webpack/src/transformers/import_factory.ts
- packages/ngtools/webpack/src/transformers/import_factory_spec.ts
> fix(@ngtools/webpack): find aliased lazy route factories

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
>  fix(@angular-devkit/build-angular): escape dot in js extensions to match literally

- packages/angular/cli/BUILD
- packages/angular/cli/commands.json
- packages/angular/cli/commands/deploy-impl.ts
- packages/angular/cli/commands/deploy-long.md
- packages/angular/cli/commands/deploy.json
- packages/angular/cli/models/architect-command.ts
- packages/angular/cli/models/command-runner.ts
Implementation of the `ng deploy` command. Find the design document [here](https://docs.google.com/document/d/1qyVJUjoZEB3QHGBe82ogwUsnAKBv2lqWRbe8BafaGtQ/edit?usp=sharing).
// cc @vikerman @StephenFluin @clydin @alan-agius4 @filipesilva
> feat(@angular/cli): implement deploy command

- packages/angular_devkit/architect/src/api.ts
- packages/angular_devkit/architect/src/create-builder.ts
A custom builder can call `context.scheduleBuilder` to call another builder.
However, the following call will fail with `Must either have a target from
the context or a default project.` exception because `scheduleBuilder` does
not pass `target` to the called builder.
```typescript
import { JsonObject } from '@angular-devkit/core'
import { BuilderContext, BuilderOutput, BuilderRun, createBuilder } from '@angular-devkit/architect';
import { Observable, from } from 'rxjs';
import { concatMap, map } from 'rxjs/operators';
export default createBuilder(_customBuilder);
function _customBuilder(options: JsonObject, context: BuilderContext): Observable<BuilderOutput> {
const builder = '@angular-devkit/build-angular:browser';
return from(context.scheduleBuilder(builder, options)).pipe( …
```
> Pass target to a builder called through `context.scheduleBuilder`

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/ng-new/schema.json
>  fix(@schematics/angular): the `ng-new` schematic should not prompt for style nor for routing

- packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
- packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
> Clean up Build Optimizer whitelists

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/utils.ts
With this change we address 2 main issues related to unbound breakpoints:
1) in VS code when having a `baseHref` set.
2) Visual Studio when using an SPA inside a ASP.NET project
For the latter, it seems that there is no way to set a `webRoot`. However, `webpack:///` seems to be handled internally and will be mapped to the `SpaRoot` ie `ClientApp` folder.
Fixes: #15211
> fix(@angular-devkit/build-angular): various breakpoints issues

- tests/legacy-cli/e2e/tests/build/prod-build.ts
The output of a prod build contains now:
```
bootstrapModuleFactory($l).catch(e=>console.error(e))}
```
Which is not being matched with the previously defined RegExp
> test: fix failing prod build snapshots

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/library/index.ts
Defaults in code are no longer required as the root issue was solved by https://github.com/angular/angular-cli/pull/15222
> refactor(@schematics/angular): remove hardcoded default values

- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html.ts
- tests/legacy-cli/e2e/tests/misc/support-safari-10.1.ts
The polyfill will not function properly if the defer attribute is present.
> fix(@angular-devkit/build-angular): avoid defer attribute for Safari nomodule polyfill

- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/src/resource_loader.ts
- packages/ngtools/webpack/src/transformers/replace_resources.ts
- packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
- yarn.lock
With this change we add support for raw-loader 1, 2 and 3.
In version 2 raw-loader released a breaking change https://github.com/webpack-contrib/raw-loader/releases/tag/v2.0.0 and now they use ES Module export instead of CommonJS.
Closes #15286 and closes #15149
> feat(@ngtools/webpack): add support for raw-loader 2 and 3

- packages/angular_devkit/build_optimizer/BUILD
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
- packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts
- packages/angular_devkit/build_optimizer/src/transforms/import-tslib.ts
- packages/angular_devkit/build_optimizer/src/transforms/prefix-functions.ts
- packages/angular_devkit/build_optimizer/src/transforms/prefix-functions_spec.ts
>  fix(@angular-devkit/build-optimizer): don't add pure comments to tslib helpers

- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/dev-server/schema.json
- packages/angular_devkit/build_angular/test/dev-server/works_spec_large.ts
We have a number of browser options that we allow the dev-server to merge. However, this only happens when such as options are undefined from the dev-server builder. At the moment these option have defaults inside their schema which results in them never being `undefined`, and hence the overridden logic is bypassed.
See: https://github.com/angular/angular-cli/blob/6dd5b186d4dc0ed750cc195d9ebe1aaa282bb640/packages/angular_devkit/build_angular/src/dev-server/index.ts#L49-L63 and https://github.com/angular/angular-cli/blob/6dd5b186d4dc0ed750cc195d9ebe1aaa282bb640/packages/angular_devkit/build_angular/src/dev-server/index.ts#L107-L115
Fixes #15273 and fixes #15064
> fix(@angular-devkit/build-angular): serve option merging is being overridden by defaults in schema

- etc/api/angular_devkit/schematics/src/_golden-api.d.ts
- packages/angular_devkit/schematics/src/tree/host-tree.ts
Remove unused optimize method marked for removal in version 7.0
> refactor(@angular-devkit/schematics): remove optimize from host-tree

- docs/design/analytics.md
- packages/schematics/angular/application/files/tsconfig.app.json.template
- packages/schematics/angular/application/files/tsconfig.spec.json.template
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/application/schema.json
- packages/schematics/angular/library/files/tsconfig.lib.json.template
- packages/schematics/angular/library/files/tsconfig.lib.prod.json.template
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/index_spec.ts
- packages/schematics/angular/ng-new/index.ts
- packages/schematics/angular/ng-new/schema.json
- packages/schematics/angular/web-worker/index_spec.ts
- packages/schematics/angular/workspace/files/tsconfig.json.template
- tests/angular_devkit/build_angular/hello-world-app-ivy/src/tsconfig.app.json
- tests/angular_devkit/build_angular/hello-world-app-ivy/src/tsconfig.server.json
- tests/angular_devkit/build_angular/hello-world-app-ivy/src/tsconfig.spec.json
- tests/angular_devkit/build_angular/hello-world-app-ivy/tsconfig.json
- tests/angular_devkit/build_angular/hello-world-app/tsconfig.json
- tests/angular_devkit/build_ng_packagr/ng-packaged-ivy/tsconfig.json
- tests/angular_devkit/build_ng_packagr/ng-packaged/tsconfig.json
- tests/legacy-cli/e2e/setup/500-create-project.ts
- tests/legacy-cli/e2e/tests/build/lazy-load-syntax.ts
- tests/legacy-cli/e2e/tests/generate/library/library-consumption.ts
- tests/legacy-cli/e2e/tests/ivy/ivy-opt-out.ts
- tests/legacy-cli/e2e/tests/ivy/ivy.ts
- tests/legacy-cli/e2e/tests/ivy/ngcc-es2015-only.ts
- tests/legacy-cli/e2e/utils/project.ts
**feat(@schematics/angular): introduce Ivy libraries for development**  
Since `NGCC` is non incremental and in library projects we have the original TS sources
we don't need to build a library using the `VE` and transform it using `NGCC`. Instead we can build the library using `NGTSC` (Ivy) directly
as this enables faster incremental compilations and a better development experience.
Libraries now have a `production` configuration, which enabled `VE` compilations. As it is not recommended to publish NGTSC (Ivy)
built libraries to NPM repositories, since Ivy libraries are not backwards compatible with the legacy View Engine.
**feat(@schematics/angular): remove enableIvy option** 
With this change we remove the enableIvy option as now we only support generating Ivy application. Users who …
> Ivy workspaces

- packages/schematics/angular/migrations/update-9/index.ts
- packages/schematics/angular/migrations/update-9/ivy-libraries.ts
- packages/schematics/angular/migrations/update-9/ivy-libraries_spec.ts
- packages/schematics/angular/migrations/update-9/update-workspace-config.ts
- packages/schematics/angular/migrations/update-9/utils.ts
Add a migration to migrate existing libraries to the new library layout considering it will be the default in version
>  feat(@schematics/angular): ivy library migration

- packages/schematics/angular/guard/index.ts
- packages/schematics/angular/guard/index_spec.ts
- packages/schematics/angular/guard/schema.json
Currently, if the user hits `<Enter>` before selecting an interface to implement, the CLI will generate a broken guard that implements no interface. With this commit, the CLI generates a `CanActivate` guard by default.
> fix(@schematics/angular): default interface for guard

- packages/schematics/angular/collection.json
- tests/legacy-cli/e2e/tests/build/platform-server.ts
The universal schematic by itself doesn't get you a working server application.
BREAKING CHANGE: universal schematic is now hidden and cannot be used with the `ng generate` command.
Users who want a working universal application should use `ng add @nguniversal/express-engine` or `ng add @nguniversal/hapi-engine`
Closes: #15166
//cc @vikerman
> feat(@schematics/angular): hide universal schematic

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
When testing React with Karma in a monorepo managed with [Nx](https://nx.dev/) (built on top of the Angular CLI), I
found that TSX files were not showing up in test coverage reports. This change seems to fix that issue.
> feat(@angular-devkit/build-angular): collect test coverage from JSX/TSX files

- packages/angular/cli/commands/add.md
Updates doc for `ng add` as requested in Issue https://github.com/angular/angular-cli/issues/15348
Closes #15348
> docs: ng add configures project in cwd

- packages/angular/cli/commands/deploy-long.md
- packages/angular/cli/commands/deploy.json
Adding some more detail to the API doc for the new `ng deploy` command.
> Add deploy command doc

- packages/ngtools/webpack/src/transformers/ctor-parameters.ts
- packages/ngtools/webpack/src/transformers/ctor-parameters_spec.ts
This mimics the behavior of TypeScript's `emitDecoratorMetadata` option.
> fix(@ngtools/webpack): only add ctor params to decorated classes

- packages/angular_devkit/build_optimizer/src/transforms/import-tslib.ts
- packages/angular_devkit/build_optimizer/src/transforms/import-tslib_spec.ts
Inlined tslib helpers can be suffixed with `$` and a number when having multiple helpers in the same file.
With this change we will replace all tslib inline helpers to imports from `tslib`
> fix(@angular-devkit/build-optimizer): replace multiple tslib helpers

- packages/schematics/angular/guard/schema.json
- tests/legacy-cli/e2e/tests/generate/guard/guard-basic.ts
- tests/legacy-cli/e2e/tests/generate/guard/guard-implements.ts
Fixes the type of the items in the `schema.json` for `implements`, as `enum` is not picked up by the CLI.
Also migrates the existing e2e test to `async/await` and adds another one with `implements` to avoid regressions.
My previous PR #15313 fixed an issue in the guard schematic but introduced a regression (sorry!) as:
```json
"items": {
"enum": [
"CanActivate",
"CanActivateChild",
"CanLoad"
]
},
```
is not picked up by the CLI, so `--implements` ends up not being recognized when running:
ng g guard foo --implements=CanActivate
The regression was released in CLI v8.3.0 stable (not in the next or rc releases).
If the issue is encountered, it can be easily worked around by using `--defaults` or manually picking the interface wanted in the prompt.
> fix(@schematics/angular): implements items type for guard schematic

- etc/api/angular_devkit/core/src/_golden-api.d.ts
- packages/angular_devkit/core/src/workspace/definitions.ts
- packages/angular_devkit/core/src/workspace/json/reader.ts
- packages/angular_devkit/core/src/workspace/json/reader_spec.ts
> fix(@angular-devkit/core): track workspace targets with no original collection

- packages/angular_devkit/build_angular/src/utils/normalize-builder-schema.ts
`--poll` is a valid command line option (vs. `--poll 1000`).  This however will result in a value of 0 which causes polling to be disabled rather than enabled which is completely non-obvious.  This change sets a default value of 500 when the commandline flag is used.
> fix(@angular-devkit/build-angular): default poll value when not present

- packages/angular/cli/utilities/package-metadata.ts
According to [the npm config docs](https://docs.npmjs.com/misc/config#npmrc-files), a user can specify the path to their
`npmrc` file using the environment variable `NPM_CONFIG_USERCONFIG`.
I ran into this issue on my system because I have my `npmrc` file in a custom location. I noticed it when running `ng
update @angular/cli` because there were 404 errors on a few internal packages, which indicated that my `npmrc` was not
being honored.
I'm not sure if this fix is sufficient, but wanted to at least start a conversation about the issue.
> feat(@angular/cli): add support for custom npmrc path

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/migrations/update-9/update-workspace-config.ts
- packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
- packages/schematics/angular/migrations/update-9/utils.ts
- packages/schematics/angular/migrations/update-9/utils_spec.ts
- tests/legacy-cli/e2e/setup/500-create-project.ts
With this change we enable the AOT option for the browser builder when an application will use Ivy as rendering engine.
> feat(@schematics/angular): add migration to enable AOT by default

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
I missed this in #15381.
Workaround is to use `codeCoverageExclude` in `angular.json`:
```json
"codeCoverageExclude": ["**/*.spec.tsx"],
```
> feat(@angular-devkit/build-angular): exclude TSX test files from test coverage

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/utils/mangle-options.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
A debugging and troubleshooting aid to easily control name mangling independently of other optimizations without modifying code inside node modules.
`NG_BUILD_MANGLE=0 ng build --prod`
> refactor(@angular-devkit/build-angular): add debug no mangle environment variable

- .circleci/config.yml
This is by default set to xlarge in the test-executor which is not needed for flake-jail.
> ci: change resource_class for flake jail to medium

- packages/schematics/angular/application/other-files/app.component.html.template
Let’s increase the discoverability of Angular’s PWA support by featuring the `ng add @angular/pwa` command in the new CLI app.
> feat(@schematics/angular): feature PWA in CLI app

- packages/schematics/angular/migrations/update-9/index.ts
- packages/schematics/angular/migrations/update-9/ivy-libraries.ts
- packages/schematics/angular/migrations/update-9/ngsw-config.ts
- packages/schematics/angular/migrations/update-9/update-app-tsconfigs.ts
- packages/schematics/angular/migrations/update-9/update-app-tsconfigs_spec.ts
- packages/schematics/angular/migrations/update-9/update-workspace-config.ts
- packages/schematics/angular/migrations/update-9/utils.ts
This migration updates the current tsconfig for the applications in two ways.
1) removes `enableIvy: true` option since it's by default true.
2) Amends the files/exclude/include options to only include files that are needed in the compilation.
Closes #15491
> feat(@schematics/angular): add migration for applications tsconfigs

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/dev-server/schema.json
- packages/angular_devkit/build_angular/test/dev-server/allowed-hosts_spec_large.ts
This PR adds `allowedHosts` as option and passes it along to the dev server. Issue #13656 describes a use-case for this. My use-case is slightly different, as I'm working on a multi-tenant application that derives the tenant from the host name. Having access to `allowedHosts` makes it possible to define multiple hosts pointing to 127.0.0.1 and using them to access the dev server (during development).
A test was added, but I'm not entirely happy with the end result. The `beforeEach` and `afterEach` are duplicate with `public-host_spec_large.ts` (although more spec files have the exact same code). It might also be better to combine it with the public-host spec file, as some test cases in there (no options specified, or with `disableHostCheck`) also apply to the `allowedHosts` option.
> feat(@angular-devkit/build-angular): expose webpack-dev-server's allowedHosts option

- packages/schematics/angular/application/index.ts
Before this commit:
`--minimal=true` create project without any testing frameworks and disable e2e, lint, test targets. Thereafter, if in this minimal project we try command `ng generate class|component|directive|guard|module|pipe|service`, it will always create `*_spec.ts` files.
After this commit:
`--minimal=true` override `@schematics/angular` in `angular.json` to not create `*_spec.ts` files when using `ng generate *` commands.
> feat(@schematics/angular): minimal=true should not create tests files when using `ng generate` command

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
terser-webpack-plugin 2.0.0+ enables the extract comments option by default which is not used by the CLI.
terser-webpack plugin update PR: #15538
> fix(@angular-devkit/build-angular): disable extract comments for webpack terser plugin

- packages/angular_devkit/build_angular/src/app-shell/index.ts
- packages/angular_devkit/build_angular/src/server/schema.json
- packages/angular_devkit/build_angular/test/app-shell/app-shell_spec_large.ts
- packages/angular_devkit/build_angular/test/server/base_spec_large.ts
- packages/schematics/angular/migrations/update-9/index.ts
- packages/schematics/angular/migrations/update-9/update-server-main-file.ts
- packages/schematics/angular/migrations/update-9/update-server-main-file_spec.ts
- packages/schematics/angular/universal/files/src/__main@stripTsExtension__.ts.template
- scripts/test.ts
- tests/angular_devkit/build_angular/hello-world-app-ve/src/main.server.ts
- tests/angular_devkit/build_angular/hello-world-app/src/app/app.module.ts
- tests/angular_devkit/build_angular/hello-world-app/src/app/app.server.module.ts
- tests/angular_devkit/build_angular/hello-world-app/src/main.server.ts
- tests/legacy-cli/e2e/tests/build/build-app-shell-with-schematic.ts
- tests/legacy-cli/e2e/tests/build/build-app-shell.ts
- tests/legacy-cli/e2e/tests/build/platform-server.ts
- tests/legacy-cli/e2e_runner.ts
**feat(@angular-devkit/build-angular): enable bundleDependencies by default for server builder**
BREAKING CHANGE: bundleDependencies default value has been changed from none to all. This will result in all of node_modules to be bundled in the final server bundle.
Under Ivy, if users choose to opt-out from bundling dependencies they will need to run NGCC binary manually to make non-bundled node_modules compatible with Ivy.
**feat(@schematics/angular): add export to `renderModule` in server main file**
This will be used by universal and app-shell to render the server module
**fix(@angular-devkit/build-angular): make app-shell work with Ivy**
Fixes #15383
**feat(@schematics/angular): add export to `renderModuleFactory`  in server main file**
**feat(@schematics/angular): add migration to add …
> Ivy app shell

- tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js
Our combined CI usage is often hitting the max number of concurrent sessions on saucelabs.  Currentl the saucelabs job takes 12 sessions at once because the tests run in parallel, instead we should run these in series to only use 1 session.  
It should not have a large impact on overall CI run time as each of the tests take ~10 seconds so we are moving from the Saucelabs steps taking ~1:45 to ~3:00 each.  Based on previous CI runs it looks like this change will still cause the saucelabs test runs to complete ~15 minutes before other jobs in the sequence.
> ci: update saucelabs protractor config to run e2e tests in series rather than parallel

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Script bundles were not being subject to the terser mangle optimizations when using bundle down leveling.
This change also allows terser to perform ECMA 6 level compress and output optimizations on the actual application bundles (non-script bundles) which can provide for further size improvements.  Also limits the parsing for optimizations of the script bundles to one step.
Fixes #15489
Supersedes #15507
> fix(@angular-devkit/build-angular): fully optimize script bundles with bundle downleveling

- lib/packages.ts
The `peerDependenciesMeta` package.json field is becoming increasingly prevalent.  The minimum versions in this change provide support for the field and mitigate incorrect peer dependency warnings for end users.
npm: https://github.com/npm/cli/blob/fc5fc76182c0746433c84a7208877fb70ef62352/CHANGELOG.md#v6110-2019-08-20
yarn: https://github.com/yarnpkg/yarn/blob/53d8004229f543f342833310d5af63a4b6e59c8a/CHANGELOG.md#1130
pnpm:
https://github.com/pnpm/pnpm/releases/tag/v3.2.0
> build: update minimum npm/yarn engine versions for built packages

- etc/api/angular_devkit/core/src/_golden-api.d.ts
- packages/angular_devkit/core/src/json/schema/interface.ts
- packages/angular_devkit/core/src/json/schema/prompt_spec.ts
- packages/angular_devkit/core/src/json/schema/registry.ts
- packages/schematics/angular/guard/schema.json
If a prompt is present on a schema property and the type is an array with a set of enum values, then the prompt type is a list with multiselect capabilites.  This eliminates the need to specify the longhand form for typical multiselect prompts.
> feat(@angular-devkit/core): auto discover multiselect schema prompt types

- packages/schematics/angular/module/schema.json
Add more detail to the API doc for `ng g m --route xx --module xx`
> docs: expand doc for new -route flag in generate module

- .github/workflows/lock-closed.yml
Closes #15532 
Now that we have worked through the backlog of inactive closed issues. We will move to automatically locking issues once per day.
> ci: update schedule for locking inactive issues

- packages/schematics/angular/universal/files/root/__tsconfigFileName__.json.template
- packages/schematics/angular/universal/index_spec.ts
By default we disable types inclusion in tsconfig.app.json which this tsconfig extends from
> feat(@schematics/angular): add node types to universal tsconfig

- packages/angular/cli/bin/postinstall/analytics-prompt.js
This can potentially execute on very old versions of Node.js and can crash otherwise.  The `ng` command itself has an initial Node.js version check that will then inform the user of the required minimum.
> fix(@angular/cli): ensure analytics postinstall script is ES5

- packages/schematics/angular/library/files/tsconfig.lib.json.template
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/migrations/update-8/update-dependencies.ts
- packages/schematics/angular/migrations/update-9/index.ts
- packages/schematics/angular/migrations/update-9/remove-tsickle.ts
- packages/schematics/angular/migrations/update-9/remove-tsickle_spec.ts
- packages/schematics/angular/migrations/update-9/update-dependencies.ts
- packages/schematics/angular/utility/latest-versions.ts
With this change we remove the requirement to add tsickle as a dependency when having a workspace library.
Since the CTOR downlevel transformer which was previously provided via tsickle  is now in ng-packagr version 5.5.1+ We migrate existing libraries to remove the need for tsickle.
//FYI @alexeagle
> feat(schematics/angular): remove dependency on tsickle

- packages/schematics/angular/workspace/files/tsconfig.json.template
- packages/schematics/angular/workspace/index_spec.ts
- packages/schematics/angular/workspace/schema.json
- tests/legacy-cli/e2e/tests/build/platform-server.ts
- tests/legacy-cli/e2e/tests/misc/browsers.ts
Add "stricter" compiler option to workspace tsconfig
Closes #14694
> feat(@schematics/angular): add `strict` compiler option to workspace tsconfig

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
There appears to be defects related to terser's ECMA 6 options.  The optimizations present a minimal size improvement in general and was the default for differential loading prior to #15566.  Further investigation is required to determine the underlying cause within terser.
Fixes #15580
> fix(@angular-devkit/build-angular): always use ECMA 5 optimizations with terser

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
> fix(@angular-devkit/build-angular): use manual sourcemap processing for large sourcemaps

- packages/schematics/angular/migrations/update-9/ivy-libraries_spec.ts
- packages/schematics/angular/migrations/update-9/update-workspace-config.ts
- packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
- packages/schematics/angular/universal/index.ts
- tests/legacy-cli/e2e/tests/build/platform-server.ts
The optimizations are suggested to;
1) disables ngDevMode via terser
2) helps with cold server starts the same way as client by lowering JS parse times
//cc @vikerman
> feat(@schematics/angular): enable scripts optimization for server bundle  

- package.json
- packages/angular_devkit/architect/package.json
- packages/angular_devkit/architect_cli/package.json
- packages/angular_devkit/benchmark/package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/delete-output-dir.ts
- packages/angular_devkit/build_ng_packagr/package.json
- packages/angular_devkit/build_webpack/package.json
- packages/angular_devkit/core/package.json
- packages/angular_devkit/schematics/package.json
- packages/angular_devkit/schematics_cli/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/utility/latest-versions.ts
- packages/schematics/update/package.json
- yarn.lock
> fix(@angular-devkit/build-angular): remove pure_getters

- etc/api/angular_devkit/architect/src/index.d.ts
- etc/api/angular_devkit/architect/testing/index.d.ts
- packages/angular_devkit/architect/node/node-modules-architect-host.ts
- packages/angular_devkit/architect/src/api.ts
- packages/angular_devkit/architect/src/architect.ts
- packages/angular_devkit/architect/src/create-builder.ts
- packages/angular_devkit/architect/src/internal.ts
- packages/angular_devkit/architect/testing/testing-architect-host.ts
- packages/angular_devkit/build_angular/src/app-shell/index.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/karma/index.ts
- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
This eliminates the need to manually read a workspace file and removes the use of the experimental workspace API from the `@angular-devkit/build-angular` package.
The `BuilderContext` now provides a `getProjectMetadata` function that provides the `root`, `sourceRoot`, `prefix`, and any custom extension fields from the project definition within `angular.json`.
> feat(@angular-devkit/architect): support accessing project metadata

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/collection.json
- packages/schematics/angular/interceptor/files/__name@dasherize@if-flat__/__name@dasherize__.interceptor.spec.ts.template
- packages/schematics/angular/interceptor/files/__name@dasherize@if-flat__/__name@dasherize__.interceptor.ts.template
- packages/schematics/angular/interceptor/index.ts
- packages/schematics/angular/interceptor/index_spec.ts
- packages/schematics/angular/interceptor/schema.json
- tests/legacy-cli/e2e/tests/generate/interceptor/interceptor-basic.ts
It is now possible to generate interceptors using the angular-cli (see #6937):
`$ ng g interceptor(ic) test`
Result:
```
CREATE src/app/test.interceptor.spec.ts (417 bytes)
CREATE src/app/test.interceptor.ts (419 bytes)
```
Is master the correct one to merge into? The documentation says devkit:master but there's no such branch. devkit is too far behind I guess.
> feat(@schematics/angular): add generator for interceptor

- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/package-chunk-sort.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- packages/angular_devkit/build_webpack/src/utils.ts
- packages/angular_devkit/build_webpack/src/webpack-dev-server/index_spec_large.ts
- packages/angular_devkit/build_webpack/src/webpack/index.ts
- packages/angular_devkit/build_webpack/src/webpack/index_spec_large.ts
- packages/angular_devkit/core/src/json/schema/visitor.ts
- tests/legacy-cli/e2e/tests/basic/scripts-array.ts
- tests/legacy-cli/e2e/tests/basic/styles-array.ts
- tests/legacy-cli/e2e/tests/misc/support-safari-10.1.ts
This corrects SRI value injection into the runtime bundle as well as accurately displaying file sizes following a differential loading build.
Fixes #15468
Fixes #15425
Fixes #15625
> Several fixes for differential loading bundle downleveling

- packages/schematics/angular/workspace/files/tslint.json.template
>no-use-before-declare is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
> fix(@schematics/angular): drop deprecated tslint rule

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- yarn.lock
This helps to ensure that the ES5 bundles operate consistently with the ES2015+ bundles.
Fixes #15673
> fix(@angular-devkit/build-angular): downlevel with non-loose ECMA compliance

- packages/schematics/angular/universal/index.ts
- packages/schematics/angular/universal/index_spec.ts
- tests/legacy-cli/e2e/tests/build/build-app-shell-with-schematic.ts
Currently, in the CLI universal schematic we are setting the server output path to `dist/project-server` and not amending the build outputPath
Ex:
```
dist/project
dist/project-server
```
However, the above paths are being update when adding `nguniversal` to the below:
```
dist/project/browser
dist/project/server
```
With this change it is proposed to move that logic to upstream.
Related PR to clean up nguniversal schematics https://github.com/angular/universal/pull/1265
> feat(@schematics/angular): update browser output path when adding universal

- BUILD
- packages/angular_devkit/core/BUILD
- packages/angular_devkit/core/node/host.ts
- packages/angular_devkit/core/src/json/schema/visitor.ts
- packages/angular_devkit/schematics/BUILD
- packages/angular_devkit/schematics_cli/BUILD
Fix all build errors for packages under `angular_devkit` in g3
> build: g3 sync for angular_devkit

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/augment-index-html_spec.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/index-file/write-index-html.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- tests/legacy-cli/e2e/tests/i18n/build-locale.ts
When using i18n (`i18nLocale`), set the document locale in `index.html` using the html `lang` attribute.
Fixes #8102
> feat(@angular-devkit/build-angular): set document locale with i18n

- package.json
- packages/angular_devkit/core/BUILD
- packages/angular_devkit/core/src/experimental/jobs/strategy.ts
- packages/angular_devkit/core/src/workspace/json/utilities.ts
- yarn.lock
`require` statements make g3 imports difficult because the dependency is not visible to the Bazel system. Moreover proper typings make the code more robust.
> build: use import instead of require for fast-json-stable-stringify

- docs/design/analytics.md
- etc/api/angular_devkit/core/src/_golden-api.d.ts
- packages/angular_devkit/build_angular/plugins/webpack/analytics.ts
- packages/angular_devkit/core/src/analytics/index.ts
Look for `ngComponentDef` or `ngModuleDef` in the webpack analytics plugin
to report back whether the current build is Ivy enabled.
> feat(@angular-devkit/build-angular): add analytics for ivy/non-ivy builds

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
PR #15607 removed the `_pure_getters` optimization as it no longer has effect on the framework size.
But it does have an effect on third party library.
For example a simple project using `@ng-bootstrap/ng-bootstrap` goes from `444K` uncompressed with CLI `9.0.0-next.5` to `488K` with CLI `9.0.0-next.6` which introduced the removal.
> fix(@angular-devkit/build-angular): re-introduce pure_getters

- packages/angular_devkit/build_angular/src/protractor/index.ts
`baseUrl` is not provided to protractor config because it was undefined
Fixes #15716
> fix(@angular/cli): initialize baseUrl variable

- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
- packages/angular_devkit/build_optimizer/src/transforms/import-tslib.ts
- packages/angular_devkit/build_optimizer/src/transforms/import-tslib_spec.ts
This transformer can cause size regressions when it introduces `tslib` imports across independent chunks.
It should be deprecated because tslib adoption has become more ubiquitous.
Should also speed up Build Optimizer processing time because there's one less thing to do.
> feat(@angular-devkit/build-optimizer): don't use getImportTslibTransformer

- packages/angular/cli/models/schematic-command.ts
This PR provides a way for subclass that extends `SchematicCommand` to
provide a different default collection name.
This is needed in g3 where the collection name is different from
external.
> feat(@angular/cli): allow subclass to override default collection name

- packages/angular/cli/BUILD
- packages/angular_devkit/core/BUILD
Removing `@typings` allows us to use a single transform rule: `@node_module`
> build: update BUILD files for g3 sync

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/browser/action-cache.ts
- packages/angular_devkit/build_angular/src/browser/action-executor.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- yarn.lock
This also provides a workaround for an issue wherein larger files (10MB+) currently cause an excessive amount of memory usage during AST processing.  This is currently being remedied upstream.  However for the current time period, this change allows for successful builds without increasing the Node.js memory limit.
> Backport additional differential loading improvements

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/copy-assets.ts
- packages/angular_devkit/build_angular/src/utils/copy-file.ts
This is currently only supported when performing a differential loading build (no watch mode).  This will eventually be expanded to cover watch mode and non-differential loading builds.
> refactor(@angular-devkit/build-angular): initial copy-on-write asset processing support

- packages/schematics/update/update/index.ts
Previously:
```
Name                                               Version                  Command to update
------------------------------------------------------------------------------------------------
@angular/cli                                       9.0.0-next.5 -> 9.0.0-next.8ng update @angular/cli --next
```
After:
```
Name                                               Version                  Command to update
------------------------------------------------------------------------------------------------
@angular/cli                                       9.0.0-next.5 -> 9.0.0-next.8 ng update @angular/cli --next
```
And it still looks fine with non-next versions
```
Name                                               Version                  Command to update …
```
> refactor(@schematics/update): missing space in usageMessage output

- packages/angular_devkit/build_angular/src/browser/action-cache.ts
- packages/angular_devkit/build_angular/src/browser/action-executor.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
This separates the logic currently in the browser builder `index.ts` into separate files and classes.  As well as simplifying the logic within the browser builder itself.
> refactor(@angular-devkit/build-angular): reorganize bundle processing for browser builder

- etc/api/angular_devkit/core/src/_golden-api.d.ts
- packages/angular/cli/commands/xi18n.json
- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/extract-i18n/schema.json
- packages/angular_devkit/build_angular/src/server/schema.json
- packages/angular_devkit/build_angular/test/extract-i18n/works_spec_large.ts
- packages/angular_devkit/core/src/experimental/workspace/workspace-schema.json
- packages/angular_devkit/core/src/experimental/workspace/workspace-schema.ts
- packages/angular_devkit/core/src/experimental/workspace/workspace_spec.ts
- tests/legacy-cli/e2e/tests/i18n/extract-xmb.ts
> New i18n schema

- lib/packages.ts
- package.json
- packages/angular/cli/bin/ng
- packages/angular_devkit/benchmark/package.json
- yarn.lock
Version 10.13.0 was the first version of 10.x that was considered LTS.  This also provides an improved performance baseline as well as access to newer Node.js APIs and Javascript language features which the Angular CLI will now be able to leverage.
> build: set minimum Node.js version to 10.13

- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/webpack-rollup-loader.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/webpack.ts
- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
- packages/angular_devkit/build_angular/test/browser/rollup_spec_large.ts
- packages/angular_devkit/build_angular/test/utils.ts
- tests/legacy-cli/e2e/tests/build/rollup.ts
- yarn.lock
In applications that make heavy use of lazy routes and ES2015 libraries, this option can improve bundle sizes. It might also break your bundles in ways we don't understand fully, so please test and report any problems you find.
NOTE: the following are known problems with experimentalRollupPass
- vendorChunk, commonChunk, namedChunks: these won't work, because by the time webpack sees the chunks, the context of where they came from is lost.
- webWorkerTsConfig: workers must be imported via a root relative path (e.g.`app/search/search.worker`) instead of a relative path (`/search.worker`) because of the same reason as above.
- loadChildren string syntax: doesn't work because rollup cannot follow the imports.
> feat(@angular-devkit/build-angular): add experimentalRollupPass

- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
Prerelease versions of the `@angular/compiler-cli` package are not supported and should not be considered valid for a stable version of `@angular-devkit/build-angular`.
/cc @IgorMinar
> fix(@angular-devkit/build-angular): remove prerelease @angular/compiler-cli peer dependency

- packages/angular_devkit/build_angular/src/utils/copy-assets.ts
- packages/angular_devkit/build_angular/test/browser/assets_spec_large.ts
Avoid copying directly directories, also which this change we cache `fs.existsSync` to optimize copying when a lot of files are being copied to the same destination.
Closes: #15816
> fix(@angular-devkit/build-angular): avoid attempting to copy directories

- tests/legacy-cli/e2e/tests/build/aot/aot-i18n.ts
The default `source-language` is `en-US` and not `en`.
> test: fix i18n extraction e2e test (Make master green)

- packages/angular/cli/models/architect-command.ts
- packages/angular_devkit/architect/node/node-modules-architect-host.ts
- tests/legacy-cli/e2e/tests/build/multiple-configs.ts
It's now possible to use multiple configurations by separating them with a comma:
```
ng build --configuration=one,two,three
```
They will be applied from left to right. If `--prod` is also present, it will be considered to be the first configuration and thus able to be overriden.
You can also use it in target strings:
```
"serve": {
"builder": "@angular-devkit/build-angular:dev-server",
"options": {
"browserTarget": "latest-project:build:one,two"
},
"configurations": {
"production": {
"browserTarget": "latest-project:build:production,one,two"
}
}
```
Fix #10612
> Support multiple configurations in commands and target strings

- packages/angular/cli/commands/update-impl.ts
After the logs are printing to console clean the logs queue.
Fixes #15839
> fix(@angular/cli): ng update log messages printed twice

- packages/ngtools/webpack/src/angular_compiler_plugin.ts
- tests/angular_devkit/build_webpack/angular-app/tsconfig.json
It should be undefined instead: https://github.com/angular/angular/blob/cd7b1992193be85f3317a4ef793b13c03ac2b215/packages/compiler-cli/src/ngtsc/program.ts#L161
Fix https://github.com/angular/angular-cli/issues/15857
> fix(@ngtools/webpack): don't set ngprogram to null

- packages/angular/cli/commands/update-impl.ts
- tests/legacy-cli/e2e/tests/misc/update-git-clean-subdirectory.ts
As `git status --porcelain` always shows paths relative to the top
level, fetch the top level path in `checkCleanGit` and properly
determine whether any modified files are actually within the
Angular workspace root.
> Determine relative paths correctly

- packages/ngtools/webpack/package.json
- packages/ngtools/webpack/src/angular_compiler_plugin.ts
The forked type checker is only a single process and can be sent a signal directly.
> refactor(@ngtools/webpack): remove unneeded tree-kill dependency

- packages/angular/cli/commands/update-long.md
https://github.com/angular/angular/issues/31259 requests more detail in doc for `ng update` on how to update to a specific version.
This adds Igor's recommendation to the AIO doc for the `ng update` command.
> docs: include major-verson update advice

- packages/angular_devkit/build_ng_packagr/package.json
- packages/schematics/angular/library/files/package.json.template
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/utility/latest-versions.ts
- yarn.lock
ng-packagr version 9 removes support for previous versions of Angular.
> feat(@angular-devkit/build-ng-packagr): limit support to version 9.0

- packages/angular/cli/lib/config/schema.json
- packages/schematics/angular/class/index.ts
- packages/schematics/angular/class/index_spec.ts
- packages/schematics/angular/class/schema.json
- packages/schematics/angular/component/index.ts
- packages/schematics/angular/component/index_spec.ts
- packages/schematics/angular/component/schema.json
- packages/schematics/angular/directive/index.ts
- packages/schematics/angular/directive/schema.json
- packages/schematics/angular/pipe/index.ts
- packages/schematics/angular/pipe/index_spec.ts
- packages/schematics/angular/pipe/schema.json
- packages/schematics/angular/service/index.ts
- packages/schematics/angular/service/schema.json
- tests/legacy-cli/e2e/tests/commands/new/new-style.ts
Deprecated `styleext` and `spec` options have been removed.  Use `style` and `skipTests` options instead.
> refactor(@schematics/angular): remove deprecated `spec` and `styleext` options

- packages/angular_devkit/build_angular/src/dev-server/index.ts
Fixes #9146 
```bash
ng new base-href-socket-path --style=css --inlineStyle=true --inlineTemplate=true --routing=false --minimal=true
ng serve --baseHref="/my-app/" --publicHost="http://localhost:4200/my-app"
```
The auto-reload `sockjs-node/*` websocket requests fails with a 404:
E.g. `curl http://localhost:4200/my-app/sockjs-node/info` returns:
```html
> GET /my-app/sockjs-node/info HTTP/1.1
> Host: localhost:4200
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 162
< Date: Sat, 19 Oct 2019 13:43:22 GMT
< Connection: keep-alive
<
<!DOCTYPE html>
<html lang="en">
<head>
<meta …
```
> fix(@angular-devkit/build-angular): sockPath for custom path

- tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl.ts
'yarn' will nuke the entire node_modules when it is triggered during the above tests. Let's restore the previous node_modules state by re-installing using 'npm' and run 'webdriver-update'.
> test: fix webdriver errors

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/test/browser/bundle-budgets_spec_large.ts
- tests/legacy-cli/e2e/tests/build/extract-licenses.ts
> fix(@angular-devkit/build-angular): keep licenses if extraction is disabled

- packages/angular/cli/lib/config/schema.json
change projects.patternProperties to npm.name.pattern
Closes #14797
> fix(@angular/cli): support the sublevel names of projects

- etc/api/angular_devkit/schematics/tasks/index.d.ts
- package.json
- packages/angular_devkit/schematics/BUILD
- packages/angular_devkit/schematics/package.json
- packages/angular_devkit/schematics/tasks/node-package/executor.ts
- packages/angular_devkit/schematics/tasks/node-package/install-task.ts
- packages/angular_devkit/schematics/tasks/node-package/options.ts
- yarn.lock
Current output:
```
kamik@RED-X1C6 MINGW64 /d/sandbox/latest-app (master)
$ ng update @angular/cli --next --force
Using package manager: 'yarn'
Collecting installed dependencies...
Found 30 dependencies.
Fetching dependency metadata from registry...
Package "@angular-devkit/build-angular" has a missing peer dependency of "@angular/localize" @ "^9.0.0-next.11".
Updating package.json with dependency @angular/cli @ "9.0.0-next.15" (was "9.0.0-next.14")...
Updating package.json with dependency @angular-devkit/build-angular @ "0.900.0-next.15" (was "0.900.0-next.14")...
Updating package.json with dependency typescript @ "3.6.4" (was "3.5.3")...
UPDATE package.json (1353 bytes)
warning @angular-devkit/build-angular@0.900.0-next.15: The engine "pnpm" appears to be invalid.
warning …
```
> fix(@angular-devkit/schematics): hide install output by default

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/postcss-cli-resources.ts
- packages/angular_devkit/build_angular/test/server/base_spec_large.ts
- packages/angular_devkit/build_angular/test/server/resources-output-path_spec_large.ts
- packages/schematics/angular/universal/index.ts
- packages/schematics/angular/universal/index_spec.ts
- packages/schematics/angular/utility/workspace-models.ts
fix(@schematics/angular): universal add outputHashing to media
In case the browser builder hashes the assets we need to add this setting to the server builder as otherwise when assets it will be requested twice. One for the server which will be unhashed, and other on the client which will be hashed.
Closes #15953
fix(@angular-devkit/build-angular): don't emit CSS resources during a server build
The server should serve the assets emitted by the browser builder. In fact the nguniversal schematics are configured to serve the assets from the browser folder
https://github.com/angular/universal/blob/a0cc9ab97a70370eff872664ac46391a193aa45e/modules/express-engine/schematics/install/files/__serverFileName%40stripTsExtension__.ts#L26
Closes #12878
> Several fixes for Universal/Server

- packages/angular/cli/tasks/install-package.ts
In the case users don't have analytics globally configured when the CLI will self update during ng update. It will prompt to configure this.
However, afterwards the update will fail with `Repository is not clean.  Please commit or stash any changes before updating.` as there would be uncommited local changed.
> fix(@angular/cli): updated CLI should not have analytics enabled

- packages/angular/cli/commands/update-impl.ts
- packages/angular_devkit/schematics_cli/bin/schematics.ts
With this change we improve the log messages of migration;
> the migration description
> the outcome of the migration
> we also remove the version of the migration which was misleading (Ex: 9.0.0-beta)
Example of new logs
> fix(@angular/cli): improve statues and description logs during update 

- packages/angular_devkit/build_angular/src/index.ts
- packages/angular_devkit/build_angular/src/protractor/index.ts
When using custom builder for dev-server it is not possible to pass additional parameters through protractor builder to it (`ng e2e --additionalParam`) does not work.
Thus, exposing protractor builder (`executeProtractorBuilder`) would allow building custom protractor builders that internally use custom dev-server builders with additional parameters.
> feat(@angular-devkit/build-angular): export protractor builder

- packages/ngtools/webpack/src/ngcc_processor.ts
If the package.json of a module is read only we should skip calling NGCC. Under Bazel when running under sandbox the filesystem is read-only.
See also: https://github.com/angular/angular/pull/33366
//cc @alexeagle, @gkalpak & @petebacondarwin
> fix(@ngtools/webpack): skip NGCC when file system is read only

- packages/angular/cli/commands/update-impl.ts
Before
```
>  NGCC postinstall migration.
Adds an ngcc invocation to npm/yarn's postinstall script.
Read more about this here: https://v9.angular.io/guide/migration-ngcc
UPDATE package.json (1490 bytes)
√ Packages installed successfully.
√  Migration succeeded.
```
After
```
> NGCC postinstall migration.
Adds an ngcc invocation to npm/yarn's postinstall script.
Read more about this here: https://v9.angular.io/guide/migration-ngcc
UPDATE package.json (1490 bytes)
√ Packages installed successfully.
√ Migration succeeded.
```
> style(@angular/cli): fix alignment of messages

- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
Improves support for the deprecated i18n options when used with Ivy.
> fix(@angular-devkit/build-angular): allow missing i18nFile option when using i18nLocale

- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/utils/load-translations.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
This will simplify the update process for the 9.0 timeframe and does not cause any runtime changes.
This should be reintroduced in 9.1 or 9.2.  The other remaining "hidden" peer dependencies should be included as well (currently `karma` and `node-sass`) with proper version ranges.
> fix(@angular-devkit/build-angular): temporarily remove localize peer dependency

- packages/schematics/angular/migrations/update-9/update-app-tsconfigs.ts
- packages/schematics/angular/migrations/update-9/update-app-tsconfigs_spec.ts
> Tsconfig migration fixes

- packages/angular/cli/tasks/install-package.ts
This is to align with current master https://github.com/angular/angular-cli/blob/85b671147ed67d7aa6ceb4b8fe4d26b73fff75ba/packages/angular/cli/tasks/install-package.ts#L90-L100
Related to https://github.com/angular/angular-cli/pull/16064
> [LTS] - refactor(@angular/cli): fix incorrect merge in install package

- packages/angular/cli/tasks/install-package.ts
> fix(@angular/cli): only show add/update package install output on errors

- packages/schematics/angular/component/schema.json
- packages/schematics/angular/utility/ast-utils.ts
Since version 9.0.0 with Ivy, entryComponents is no longer necessary.
> refactor(@schematics/angular): deprecate component entryComponents

- packages/schematics/angular/migrations/update-9/ivy-libraries.ts
- packages/schematics/angular/migrations/update-9/ngsw-config.ts
- packages/schematics/angular/migrations/update-9/remove-tsickle.ts
- packages/schematics/angular/migrations/update-9/update-app-tsconfigs.ts
- packages/schematics/angular/migrations/update-9/utils.ts
> fix(@schematics/angular): warn when target references a missing tsconfig

- packages/angular_devkit/build_angular/test/browser/output-path_spec_large.ts
> test: verify that link in outputpath is not deleted at source

- .circleci/config.yml
- packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
- packages/ngtools/webpack/src/angular_compiler_plugin.ts
Fix https://github.com/angular/angular-cli/issues/15863
Fix https://github.com/angular/angular-cli/issues/15340
>  fix(@ngtools/webpack): fix resource dep lookup on window

- tests/legacy-cli/e2e/tests/build/prod-build.ts
We verified this size change happens just from increasing FW version from 9.0.0-rc.0 to 9.0.0-rc.1
CLI master with FW rc.1:
```
141032 Nov  6 20:08 main-es2015.ed01ec5f480fa886325f.js
163321 Nov  6 20:08 main-es5.ed01ec5f480fa886325f.js
36808 Nov  6 20:08 polyfills-es2015.b6fe2b19564e29c5d554.js
127927 Nov  6 20:08 polyfills-es5.9cbeb6b4a192c8c548fe.js
1485 Nov  6 20:08 runtime-es2015.52756d3ab8e6582f0541.js
1485 Nov  6 20:08 runtime-es5.52756d3ab8e6582f0541.js
```
CLI master with FW rc.0:
```
139902 Nov  6 20:05 main-es2015.cd909d61c6a4766689e9.js
162180 Nov  6 20:05 main-es5.cd909d61c6a4766689e9.js
36808 Nov  6 20:05 polyfills-es2015.b6fe2b19564e29c5d554.js
127927 Nov  6 20:05 polyfills-es5.9cbeb6b4a192c8c548fe.js
1485 Nov  6 20:05 runtime-es2015.52756d3ab8e6582f0541.js
1485 Nov  6 …
```
> test: update FW size expectations

- packages/angular/cli/tasks/install-package.ts
In some cases when an error occurs in the spawned process the `error` property will be populated instead of `stderr` or `stdout`.
See: https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options
> fix(@angular/cli): use spawned process error when it's available

- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl.ts
Since the deprecated locale data registration was removed, existing tests that rely on locale data will fail if these changes do not properly inject the new form of the locale data.
> fix(@angular-devkit/build-angular): insert locale data when localizing

- packages/schematics/angular/migrations/update-9/update-app-tsconfigs.ts
- packages/schematics/angular/migrations/update-9/update-app-tsconfigs_spec.ts
This migration coverts the TypeScript `module` compiler option to `esnext` or `commonjs` which is required when using `import()`.
Fixes: #16094
> fix(@schematics/angular): migrate module compiler option

- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/commands/update.json
> fix(@angular/cli): disable update commit creation by default

- packages/ngtools/webpack/src/angular_compiler_plugin.ts
> fix(@ngtools/webpack): only remove decorators in VE

- packages/ngtools/webpack/src/transformers/elide_imports.ts
- packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
- packages/ngtools/webpack/src/transformers/remove_decorators_spec.ts
> fix(@ngtools/webpack): also elide type references on transform

- packages/angular_devkit/benchmark/src/monitored-process.ts
`child_process.spawn()` with `shell: true` does not quote its arguments, so any data passed in must be surrounded by quotes to properly include spaces (https://github.com/nodejs/node/issues/5060). This was making tests fail when the repository is checked out to a directory with a space in it.
Easiest solution is to simply not use shell escaping which avoids the whole problem.
Alternatively, we could attempt to wrap every argument in quotes, but that would require escaping any existing quotes, which could cause other problems. In the [original PR](https://github.com/angular/angular-cli/pull/12022) for this file, I don't see a strong motivation for using `shell: true`, and all the tests pass without it, so I think the best solution is to just remove this flag.
> fix(@angular-devkit/benchmark): Allows the CLI repo to be hosted in a directory with spaces.

- .circleci/config.yml
Our yarn cache is now at 4gb:
```
No cache is found for key: angular_devkit-0.11.0-m+RxJhhe6Gc_rzgntffBpEs5LmGYauhWKuRZBYBtlP0=
Found a cache from build 106076 at angular_devkit-0.11.0
Size: 4.0 GB
Cached paths:
* /home/circleci/.cache/yarn
Downloading cache archive...
Unarchiving cache...
```
By bumping the cache key we'll reset it.
> ci: bump cache key

- packages/angular/cli/tasks/install-package.ts
This works around a Windows CI failure that related to the PATH environment variable and a failure to located the `npm` command.
> fix(@angular/cli): re-introduce install package using shell spawn

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
Fixes the CI failure for #16065 and provides a noticeable memory improvement.  The failing test from the aforementioned PR went from 2GB to process the main bundle to just over 550MB.
> fix(@angular-devkit/build-angular): prevent double sourcemap processing

- .github/ISSUE_TEMPLATE/1-bug-report.md
With this change the author will be able to check the command in question after the issue creation.
Ex: https://github.com/angular/angular-cli/issues/16094
> docs: remove backticks from bug report in command section

- packages/angular_devkit/build_angular/src/tslint/index.ts
TSLint [6.0.0-beta0](https://github.com/palantir/tslint/releases/tag/6.0.0-beta0) was released, and `ng lint` throws with:
TSLint must be version 5.5 or higher.
if we try to use it in a CLI project.
It looks like the current version check allows v5.5+ by checking that both the major and minor versions are > 5. So this fails with 6.0 (but would succeed with 6.5).
This fixes the check to allow using v6.0.
> feat(@angular-devkit/build-angular): support TSLint 6.0+

- packages/angular/cli/commands/update-impl.ts
- tests/legacy-cli/e2e/tests/update/update-1.0.ts
- tests/legacy-cli/e2e/tests/update/update-1.7-longhand.ts
- tests/legacy-cli/e2e/tests/update/update-1.7.ts
Any time a `git commit` is made, the CLI now prints out the hash and short message. For migrations, the message is simply the first line of the commit. For schematics, the commit message isn't all that helpful, so I used the list of packages instead.
I didn't see any good place to put tests for this code, so I didn't add any tests for this change. Let me know if there is a particular place I should include some.
Example run with the change:
```
$ ng update -C --next @angular/core --force
Fetching dependency metadata from registry...
Package "@angular-devkit/build-angular" has an incompatible peer dependency to "typescript" (requires ">=3.1 < 3.6", would install "3.6.4").
Updating package.json with dependency @angular/compiler-cli @ "9.0.0-rc.1" (was "8.2.13")...
Updating package.json with …
```
> fix(@angular/cli): Prints out when a commit is made in `ng update`.

- packages/angular/cli/tasks/install-package.ts
Previously we passed `--no-bin-links` because we used to install packages globally in some cases. But now this is no longer needed as we should now have permissions to generate "local" bin links even during a temp installations as these  will no longer generate bin links in the global context.
Fixes #16133
> fix(@angular/cli): remove no-bin-links during npm/yarn install

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
The node modules directory contains a massive set of directories and files.  When watching via polling, that set needs to be queried repeatedly to determine if any files have changed.  Changes within node modules are quite rare while using `ng serve` or `ng build --watch`.  As a result, polling the node modules directory is rarely useful.  This change causes CPU usage to drop from a potential high of ~80% to a more manageable ~5-10%.
This also fixes the flag option variant of `--poll` for `ng serve` so that it results in the default value of 500 ms instead of disabling polling.  `ng build --watch` already contains a fix for this.
> fix(@angular-devkit/build-angular): ignore node modules when polling

- packages/angular_devkit/build_angular/test/browser/unused-files-warning_spec_large.ts
- packages/ngtools/webpack/src/angular_compiler_plugin.ts
> fix(@ngtools/webpack): recursive look up unused files

- packages/angular/cli/utilities/config.ts
Explained here: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
Current change affects reading of global config from `.angular-config.json`. By default it will be created in user's home directory. If user moves it manually to `$HOME/.config/angular/.angular-config.json`, it will be subsequently read from new location.
> feat(@angular/cli): Support XDG Base Directory Specfication

- packages/angular/cli/commands/update-impl.ts
We don't actually know for certain that the migration was successful, only that it finished. This updates the messaging to be more clear about this distinction. I also removed the check mark and green coloring which implied success.
> fix(@angular/cli): Renames "Migration succeeded" to "Migration completed. (#16016)

- packages/angular_devkit/build_angular/plugins/webpack/analytics.ts
Current we are always sending `0` as the number of components in JIT mode because ` Component({` doesn't match the component source
> fix(@angular-devkit/build-angular): fix numberOfComponents in JIT mode

- packages/angular_devkit/build_ng_packagr/package.json
This way it'll be automatically updated if present.
> fix(@angular-devkit/build-ng-packagr): add tsickle as optional peer dep

- docs/process/release.md
This includes instructions on how to cherry-pick commits into the patch branch. Since `cherry-pick` isn't that commonly used, it's useful to write this down for developers who might not be that familiar with it. It also includes fetching the commit beforehand, so users don't get "bad object" errors which can be annoying to work around.
The `-x` option is used as well to include a reference to the commit the cherry-pick came from.
> docs(@angular/cli): add cherry-pick instructions.

- packages/schematics/angular/guard/files/__name@dasherize__.guard.spec.ts.template
The current guard spec schematic uses `inject` whereas we dropped it for the service spec a while ago.
This commits updates the guard spec schematic to be similar to the current service spec.
> fix(@schematics/angular): uniformize guard spec with service spec

- packages/schematics/angular/guard/files/__name@dasherize__.guard.ts.template
- packages/schematics/angular/guard/index.ts
- packages/schematics/angular/guard/schema.json
- tests/legacy-cli/e2e/tests/generate/guard/guard-multiple-implements.ts
This generates a generic `CanDeactivate<unknown>` guard.
Fixes #15668
> fix(@schematics/angular): add CanDeactivate guard

- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-es2015.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-es5.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-server.ts
- tests/legacy-cli/e2e/tests/i18n/legacy.ts
This also adds global local data support to the development server.
> Re-enable global locale data support for Ivy

- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
- packages/angular_devkit/build_angular/src/utils/output-paths.ts
- tests/legacy-cli/e2e/tests/i18n/ve-localize-es2015.ts
This allows one set of options to be used for localization regardless of Ivy usage.  Also simplifies Ivy opt out.
> fix(@angular-devkit/build-angular): allow new i18n options to work with VE

- packages/schematics/angular/utility/ast-utils.ts
- packages/schematics/angular/utility/ast-utils_spec.ts
Adds a new route before the wildcard route to prevent that we always redirect to the wildcard route.
For example, starting point:
```
const routes = [
{ path: '**', component: AppComponent }
];
```
Before:
```ts
const routes = [
{ path: '**', component: AppComponent },
{ path: 'foo', component: FooComponent }
];
```
After:
```ts
const routes = [
{ path: 'foo', component: FooComponent },
{ path: '**', component: AppComponent }
];
```
Closes #15255
> fix(@schematics/angular): add new route before wildcard route

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
The ES5 polyfills file was erroneously being suffixed with `es2015`.  The webpack configuration does not support conditional customization per chunk for the output filenames (`chunkFilename` option schema only supports string values).  This change adds an additional small webpack plugin that allows the chunk filenames to be adjusted based on the chunk name.  The plugin is only added when differential loading is enabled as this is the only time that a chunk currently requires its filename to be adjusted.
Closes #15915
> fix(@angular-devkit/build-angular): prevent webpack from adding suffixes to polyfill files

- packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
- packages/ngtools/webpack/src/angular_compiler_plugin.ts
- packages/ngtools/webpack/src/loader.ts
> fix(@ngtools/webpack): fix rebuilds for transitive and global type deps

- .gitignore
- .idea/angular-cli.iml
Intellij and Webstorm unfortunately don't the use the exact same
configuration system. For example, Intellij treats every project as
`JAVA_MODULE` but Webstorm doesn't recognize the `JAVA_MODULE`.
Therefore, I think that the modules.xml and iml should be left
out from version control.
refs #16152
> refactor(@angular/cli): update Intellij/Webstorm settings

- packages/angular_devkit/build_angular/src/utils/version.ts
This link is rarely seen by developers but when they do see it, they should get the real one.
> fix(@angular-devkit/build-angular): update link to update.angular.io

- packages/ngtools/webpack/src/angular_compiler_plugin.ts
The plugin's package could technically be installed outside of the location containing the Angular dependencies and/or the project root.  This is particularly relevant for `pnpm` or `yarn pnp` (even though the later is not yet supported) since they strictly enforce package presence and versioning.
Closes #16219
> fix(@angular-devkit/build-angular): resolve lazy route Angular package from project base

- docs/process/release.md
Added some additional details for how the caretaker should merge PRs, including a GitHub search which lists all pending PRs.
> docs: update release doc with more merge details

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/action-cache.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- packages/angular_devkit/build_angular/test/browser/differential_loading_spec_large.ts
A target of es2015 was previously assumed when using differential loading.  This could result in erroneously downleveling an es2016+ output file instead of generating a new es5 output file.
Closes #15610
> fix(@angular-devkit/build-angular): properly process es2016+ targets with differential loading

- packages/angular/cli/bin/ng
- packages/angular/cli/lib/cli/index.ts
This change ensures that both the global version and the project version Node.js version requirements are met before the CLI executes a command.  Previously an older global version of the CLI would allow a newer project version to execute even if the project version had more strict Node.js version requirements.  The Node.js version is now checked twice.  Once in an ES5 safe script to ensure that ancient Node.js versions are not in use.  And secondly in the CLI entry code that is executed after global/project bootstrapping.
> fix(@angular/cli): improve robustness of Node.js version check

- packages/angular_devkit/build_angular/src/utils/version.ts
Allow version "0.0.0" for integration testing in the angular/angular repository with the generated development @angular/core npm package which is versioned "0.0.0".
This is a pre-req for https://github.com/angular/angular/pull/33927 which runs integration tests against the bazel generated npm packages.
To green up that PR I have a patch that does the same thing https://github.com/angular/angular/pull/33927/files#diff-817b74474f8a65162b6115d04a6f43c7 which will get removed once this change makes it in to the next release
> refactor(@angular-devkit/build-angular): allow @angular/core version 0.0.0

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/single-test-transform.ts
- packages/angular_devkit/build_angular/test/karma/selected_spec_large.ts
I've ran into an issue at work with the mocked context in single test transform - it does not match [webpack API](https://webpack.js.org/guides/dependency-management/#requirecontext).
Basically I have to filter out certain values from `require.context(...).keys()` before importing the actual file to fix another issue in `test.ts`. (Desired outcome is for code coverage to include untested ts files)
Currently with angular 8 (and master branch) it fails when running `ng test --include <file>`, as the value returned from keys does not have a `filter` method. This PR fixes that by returning an empty array instead of partial object.
@filipesilva since you approved my original PR, could you give a quick look here? It is a very minor change :)
> fix(@angular-devkit/build-angular): mocked context in single test transform matches webpack API

- docs/design/ngConfig.md
Fixed spelling mistakes and verb forms.
> docs: fix typos in the ngConfig design document

- packages/ngtools/webpack/README.md
Issue #15287.
I have added descriptions for the rest of the options.
I haven't touched those options that marked as `@deprecated` and `host|platformTransformers`.
Not sure if `host` and `platformTransformers` have to be documented :slightly_smiling_face:
> docs(@ngtools/webpack): document missing options

- packages/angular_devkit/build_angular/src/karma/schema.json
This option is unused and has no effect.
> refactor(@angular-devkit/build-angular): deprecate karma `environment` option

- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
All other paths within the workspace file are relative to the workspace root.
> fix(@angular-devkit/build-angular): make i18n translation files relative to workspace

- packages/angular/cli/commands/version-impl.ts
- packages/angular/cli/utilities/config.ts
- tests/legacy-cli/e2e/tests/misc/version.ts
> fix(@angular/cli): `ng version` should report if ivy is enabled

- packages/angular/pwa/pwa/files/root/manifest.webmanifest
Icon Mask is a new feature coming to app manifest that allows developers to specify if their icons could be masked to better fit the system's design. A detailed explainer can be found on the Web App Manifest spec page
https://www.w3.org/TR/appmanifest/#icon-masks
And an more abridged version can be found here
https://css-tricks.com/maskable-icons-android-adaptive-icons-for-your-pwa/
This PR adds support for the `purpose` key and `maskable` value in app manifest.
In testing on [maskable.app](https://maskable.app), it appears the current set of Icons will need to be resized a bit. The suggest size is about 40% of the entire image dimension.
I did not include this in the PR and the current icons are just placeholders and not sure it would make sense to mondify.
> feat(@angular/pwa): support for maskable icons

- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/index_spec.ts
- packages/schematics/angular/workspace/files/tsconfig.json.template
- scripts/test.ts
- Currently the library schematic doesn't support adding a secondary entry-point and having deep imports is not recommanded.
It's best if paths are more stricter when having a secondary entry-point instead of a wildcard.
Instead of :
```
"lib/*": [
"dist/lib/*"
]
```
Users should configure:
```
"lib/secondary": [
"dist/lib/secondary"
]
```
This would allow a better DX experience when using auto imports in IDE's.
Closes: #15952
> Library imports

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
- packages/angular_devkit/core/src/experimental/workspace/workspace-schema.json
- packages/schematics/angular/migrations/update-9/update-workspace-config.ts
- packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-basehref.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl-xliff2.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-es2015.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-es5.ts
- tests/legacy-cli/e2e/tests/i18n/legacy.ts
- tests/legacy-cli/e2e/tests/i18n/ve-localize-es2015.ts
All locale i18n options now support an object form which allows a base HREF to be defined for the locale.  This allows each locale to optionally define a custom base HREF that will be combined with the base HREF defined for the build configuration.
By default if the shorthand form for the locale is used or the field is not present in the longhand form, the locale code will be used as the base HREF.  To disable automatic augmentation, a base HREF value of an empty string (`""`) can be used.  This will prevent anything from being added to the existing base HREF.
For common scenarios, the shorthand form will result in the preferred and recommended outcome of each built locale variant of the application having a defined base HREF containing the locale code.
Closes #16301
> fix(@angular-devkit/build-angular): augment base HREF when localizing

- .circleci/env.sh
Currently all saucelabs usage in our repos is done using the same
account angular-ci.  By migrating to use individual accounts
for each repo, we can better track the usage for each repo as well
as providing concurrency limiting on a per repo basis.
> ci: update saucelabs to use angular-tooling account

- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
Refs #16193
This detects and filters out error messages about duplicate `3rdpartylicenses.txt`. This is a short-term fix intended to get us to 9.0.x release while a follow up effort will work to properly fix this bug. Left a `TODO` to remove this filter once a real fix is ready.
> fix(@angular-devkit/build-angular): suppress duplicate 3rdpartylicenses.txt warning

- packages/angular/cli/commands/deploy.json
I remove the alias for deploy command.
- Because alias 'd' is a duplicate.
- The image below shows the result of the `$ ng help` command.
- I removed alias for deploy command instead of doc.
- https://github.com/angular/angular-cli/pull/16364#issuecomment-562251529
- Angular CLI : 8.3.20
> fix(@angular/cli): remove alias for deploy command

- packages/angular_devkit/build_angular/src/browser/index.ts
Originally intended to be part of #16332
Closes #16390
> fix(@angular-devkit/build-angular): localize service worker base href

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
> Fix bazel integration

- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/index.ts
export executeExtractI18nBuilder for use in custom builders and to be consistent with browser- and dev-server-builder.
no breaking changes, no issue
> refactor(@angular-devkit/build-angular): export executeExtractI18nBuilder

- packages/schematics/angular/migrations/update-9/update-workspace-config.ts
- packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
Output paths that use the locale within a locale specific configuration will now be automatically removed.  This will prevent the potential for the migrated configuration to generate an output path with double locale segments.
Closes #16384
> fix(@schematics/angular): improve i18n output path option migration

- packages/angular_devkit/build_angular/src/dev-server/index.ts
This reverts commit 5260bbb9a3d17aefb90bcf1b660e252996cf68df.
The public host option should only affect how clients access the development server and not how the development server actually serves the files.
Fixes #16410
Fixes #16266
> revert: fix(@angular-devkit/build-angular): sockPath for custom path

- packages/angular_devkit/build_angular/package.json
- yarn.lock
Closes #16414
NOTE TO CARETAKER: pending status of `ci/angular: merge status` is incorrect and can be ignored.  The two _missing_ status checks do not exist on this branch.
> Fix audit vulnerability warnings for 8.3.x

- packages/ngtools/webpack/src/compiler_host.ts
- packages/ngtools/webpack/src/ngcc_processor.ts
> fix(@ngtools/webpack): invalidate ngcc processor cache

- CONTRIBUTING.md
- docs/process/release.md
- scripts/templates/contributing.ejs
This label should be placed by the author (or last reviewer if author is not a collaborator) when the PR is complete and ready to merged. This requires the author to explicitly acknolwedge that they are done with the PR and the caretaker is free to merge it. This label brings the CLI caretaking process into alignment with the frameworks and components repos.
A more automated solution is desired but difficult due to google3 merging challenges. That would be a separate problem, but this should at least get the Angular organization to a more consistent state and we can revisit that challenge when we get to it.
I chose to link to the existing PR target definitions in the framework docs, let me know if I should duplicate this for the CLI.
> doc: adds "PR action: merge" label

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Replacing the node path can cause stack overflows for very large files.
Closes #16441
> fix(@angular-devkit/build-angular): optimize web worker differential loading processing

- packages/schematics/angular/service-worker/index.ts
- packages/schematics/angular/service-worker/index_spec.ts
- packages/schematics/angular/utility/ast-utils.ts
Closes: #16226
The exception `Cannot read property 'length' of undefined` wasn't really informative thus I had to find out where this exception was actually thrown. All ways led me to the `Chunk` class and the `insertLeft` method that used `buffer`'s variable `length` property. The `buffer` was `undefined`, that's why that exception was thrown. It was `undefined` because there is no way to check if `environment` is already imported.
This PR adds the ability to handle the already existing "environment" import or the aliased one.
> fix(@schematics/angular): handle aliased or existing environment import

- packages/angular/cli/commands/update-impl.ts
This is a workaround for the schematics runtime to support the requirement of packages containing migrations (or other schematics) to not have a direct/runtime dependency on the schematics package.
Closes: #16392
> fix(@angular/cli): inform user and error if schematics package is in unreachable location

- packages/ngtools/webpack/src/diagnostics.ts
By passing all diagnostics through formatDiagnostics from compiler-cli.
Without this we were printing negative TS error codes which was
compiler-cli way of marking Angular errors.
> fix(@ngtools/webpack): format Ivy diagnostics properly

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
This can drastically reduce memory usage; especially in cases where bundled code modules contain individual sourcemap comments and vendor sourcemaps are disabled.  Enabling the vendor sourcemap option has the side effect of removing all individual module sourcemap comments and as a result removes the potential for those comments to be found and processed.
> fix(@angular-devkit/build-angular): prevent differential loading double sourcemap search

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
This can drastically reduce memory usage; especially in cases where bundled code modules contain individual sourcemap comments and vendor sourcemaps are disabled.  When enabling the vendor sourcemap option it has the side effect of removing all individual module sourcemap comments and as a result removes the potential for those comments to be found and processed.  This option can be used as a workaround, where possible, until this PR is merged and released.
NOTE TO CARETAKER: pending status of `ci/angular: merge status` is incorrect and can be ignored.  The two _missing_ status checks do not exist on this branch.
> [8.3.x] fix(@angular-devkit/build-angular): prevent differential loading double sourcemap search

- packages/angular/cli/commands/update-impl.ts
This allows the CLI version check during update bootstrapping to be disabled via the `NG_DISABLE_VERSION_CHECK` environment variable.  This is not considered an officially supported option and is intended mainly for testing/troubleshooting scenarios.
Closes #16122
> refactor(@angular/cli): allow update version check to be disabled

- packages/angular/cli/lib/init.ts
Set the `BROWSERSLIST_IGNORE_OLD_DATA` enviorment variable to disable Browserslist old data warning
`Browserslist: caniuse-lite is outdated. Please run next command `npm update`
See: https://github.com/browserslist/browserslist/blob/819c4337456996d19db6ba953014579329e9c6e1/node.js#L324
> fix(@angular/cli): disable Browserslist old data warning

- package.json
- packages/angular_devkit/benchmark/package.json
- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
- yarn.lock
While the CLI is not affected by the following advisory, this change will address the audit warning and prevent any potential future usage of the package within the CLI from being affected.
Advisory: https://www.npmjs.com/advisories/1432
Closes https://github.com/angular/angular-cli/issues/16629
> [8.3.x] fix(@angular-devkit/build-angular): update tree-kill dependency to 1.2.2

- package.json
- packages/angular_devkit/benchmark/package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
While the CLI is not affected by the following advisory, this change will address the audit warning and prevent potential future usage of the package within the CLI from being affected.
Advisory: https://www.npmjs.com/advisories/1432
> [9.0.x] fix(@angular-devkit/build-angular): update tree-kill dependency to 1.2.2

- package.json
- yarn.lock
Update tree-kill dependency to ^1.2.2 in response to https://npmjs.com/advisories/1432.  Advisory affects tree-kill package, not angular-cli directly.
> build: update tree-kill to version ^1.2.2

- renovate.json
This label is expected to be added by authors after the review once they have made final edits to the PR (per contributing guidelines: https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-a-pull-request-pr). The bot will never make additional edits from a review, so it is always ready to merge. This adds the "PR action: merge" label so it will show up correctly in the caretaker search for PRs ready to merge (https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-a-pull-request-pr). Renovate PRs will still require review and passing status checks before becoming visible to caretakers.
> ci: add "PR action: merge" label to renovate bot PRs

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/test/browser/scripts-array_spec_large.ts
While we currently invoke the `callback` with the error in https://github.com/angular/angular-cli/blob/d4f1ff82c5d994aca68c39ff31f5d8b22e694b87/packages/angular_devkit/build_angular/src/angular-cli-files/plugins/scripts-webpack-plugin.ts#L163 this is not bubbled up to the main webpack compilation due to the usage of `thisCompilation`.
Closes #16659
> fix(@angular-devkit/build-angular): emit error when a script is not found.

- lib/packages.ts
Yarn displays a warning due to an unknown engine value of `pnpm`.  Until this is corrected upstream, the value can be temporarily removed to eliminate the multiple, but otherwise harmless, warnings shown to users upon package install.
Yarn Issue: https://github.com/yarnpkg/yarn/issues/7560
Yarn PR: https://github.com/yarnpkg/yarn/pull/7566
> build: remove pnpm engine value due to lack of yarn support

- packages/angular_devkit/build_angular/test/browser/web-worker_spec_large.ts
- packages/schematics/angular/workspace/files/tsconfig.json.template
- scripts/test.ts
- tests/angular_devkit/build_angular/hello-world-app-ve/tsconfig.json
- tests/angular_devkit/build_angular/hello-world-app/tsconfig.json
- tests/angular_devkit/build_ng_packagr/ng-packaged-ve/tsconfig.json
- tests/angular_devkit/build_ng_packagr/ng-packaged/tsconfig.json
- tests/legacy-cli/e2e/tests/build/skip-lib-check.ts
Add skipLibCheck to speed up TypeScript analysis and prevent compilation errors caused by incompatible declaration files which were generated with older/new TS versions.
//cc @IgorMinar
> fix(@schematics/angular): add `skipLibCheck` to workspace tsconfig

- .circleci/config.yml
ci: use branch filtering to run `e2e-cli-ng-snapshots` and `e2e-cli-ng-ve-snapshots`
Unlike PRs from users, when renovate opens a PR, the branch name will be in the following format `renovate/typescript-3.7.x` with `CIRCLE_BRANCH` being set to the same value. Also, `CIRCLE_PR_USERNAME` will not be defined in this case. Thus currently these 2 tasks are not being run for PRs which are being open by renovate.
Example of such build: https://circleci.com/gh/angular/angular-cli/129384
> ci: use branch filtering to run `e2e-cli-ng-snapshots` and `e2e-cli-ng-ve-snapshots

- .circleci/config.yml
Currently certain steps like `e2e-cli-node-10` and `snapshot_publish` are being run for PRs which are created via non forked repos. Such as renovate and users who create PRs directly from github via `Edit file`.
Example of such branch names are;
```
renovate/sass-loader
alan-agius4-testing-branch
```
> ci: update ignore_pull_requests to only include release-able branches

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
The rxjs path mapping function does not have any parameters and has not since version 5.5.0 which is not supported.
> refactor(@angular-devkit/build-angular): remove nonexistent argument from rxjs path mapping call

- .circleci/config.yml
Only run running `e2e-cli-ng-snapshots`  and `e2e-cli-ve-ng-snapshots` for non `renovate/angular` and `master` PRs to reduce CI time for renovate PRs.
> ci: reduce ci time for renovate PRs

- docs/process/release.md
I hid the sensitive URLs behind a short link just to be extra careful with them while still providing useful click-through functionality for Googlers.
> docs: add NPM login details to releasing docs.

- packages/angular/cli/models/schematic-command.ts
The `@angular/cli` package contains a built-in version of the `@schematics/angular` package.  The module resolution paths for the schematics workflow should not assume package hoisting behavior when resolving.  This change corrects that oversight.
> fix(@angular/cli): ensure built-in Angular schematics package can be found

- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/index_spec.ts
- packages/schematics/angular/workspace/files/tsconfig.json.template
fix(@schematics/angular): regression tsconfig.json  …
Unverified
0e318ae
Regression in tsconfig.json set `"outDir": "./dist/out-tsc"` for problems in VSCode TS(2307) when building library referred in tsconfig "paths" 
Closes: #16708
> fix(@schematics/angular): regression tsconfig.json #16708

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/test/browser/optimization-level_spec_large.ts
- tests/legacy-cli/e2e/tests/basic/ivy.ts
> fix(@angular-devkit/build-angular): ensure output is ASCII only

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/utils/environment-options.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
`NG_BUILD_MINIFY` can be used to separately disable minification (terser's compress)
`NG_BUILD_BEAUTIFY` can be used to format the output code even when otherwise optimized
> refactor(@angular-devkit/build-angular): add additional debug build environment variables

- packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
- packages/ngtools/webpack/src/angular_compiler_plugin.ts
- packages/ngtools/webpack/src/loader.ts
- packages/ngtools/webpack/src/resource_loader.ts
> fix(@ngtools/webpack): correctly determine resource dependencies

- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
- packages/schematics/angular/e2e/files/src/app.po.ts.template
Fixes #16754 
Make Angular CLI schematics compliant with `typedef: ["call-signature"]` TSLint rule.
> fix(@schematics/angular): add compliance with call-signature lint rule

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
The latest version of Babel (e.g. 7.8.3) requires a filename
to be passed to `parseSync()`.
Fixes #16781
> fix(@angular-devkit/build-angular): pass filename to `parseSync`

- .circleci/config.yml
Estimated credit cost reduction: 40%
Estimated critical path runtime reduction: 8 minutes
Previous critical path: `setup` -> `build` -> `e2e-cli`
New critical path: `setup` -> `build` -> `build-and-setup` -> `test-win`
> ci: reduce resource classes

- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
The `configFile` option needs to be set to false to ensure Babel does not attempt to discover and load any file based configurations.
> fix(@angular-devkit/build-angular): ensure babel configurations are isolated

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts
- packages/ngtools/webpack/src/angular_compiler_plugin.ts
- packages/ngtools/webpack/src/interfaces.ts
- packages/ngtools/webpack/src/transformers/remove-ivy-jit-support-calls.ts
- packages/ngtools/webpack/src/transformers/remove-ivy-jit-support-calls_spec.ts
- tests/legacy-cli/e2e/tests/build/prod-build.ts
This change allows the import eliding capabilities of the plugin to more completely remove the effects of the `setClassMetadata` and `setNgModuleScope` functions.  This provides equivalent behavior to the Decorator removal functionality for View Engine.  As a result, Angular components are no longer retained in chunks that do not use the component.
This corrects the factory code location problem discussed in https://github.com/angular/angular-cli/issues/16146#issuecomment-557559287.
> Control emitting Ivy class metadata and Angular module scope information

- packages/schematics/angular/application/files/src/test.ts.template
- packages/schematics/angular/e2e/files/src/app.po.ts.template
- packages/schematics/angular/library/files/src/test.ts.template
- packages/schematics/angular/pipe/files/__name@dasherize@if-flat__/__name@dasherize__.pipe.ts.template
- packages/schematics/angular/pipe/index_spec.ts
- tests/angular_devkit/build_angular/hello-world-app-ve/e2e/app.po.ts
- tests/angular_devkit/build_angular/hello-world-app-ve/src/test.ts
- tests/angular_devkit/build_angular/hello-world-app/e2e/app.po.ts
- tests/angular_devkit/build_angular/hello-world-app/src/test.ts
- tests/angular_devkit/build_ng_packagr/ng-packaged-ve/projects/lib/src/test.ts
- tests/angular_devkit/build_ng_packagr/ng-packaged/projects/lib/src/test.ts
Fixes #16770
Make Angular CLI schematics compliant with `no-any` TSLint rule.
For `test.ts` files, as they are just configuration files for unit tests, not real code, the rule is just disabled.
> fix(@schematics/angular): add compliance with no-any lint rule

- packages/schematics/angular/workspace/files/package.json.template
New projects will now be created with `~5.4.3`
> fix(@schematics/angular): update protractor version for new projects

- packages/angular_devkit/build_angular/src/angular-cli-files/models/es5-polyfills.js
This imports the individual regex polyfills allowing control of each element.  The new (core-js 3.6.0) sticky related polyfills are not included as they are not needed and may cause conflicts with some existing third-party libraries.
Related: #16715
> fix(@angular-devkit/build-angular): remove unneeded regex polyfills

- packages/schematics/angular/migrations/update-9/update-app-tsconfigs.ts
- packages/schematics/angular/migrations/update-9/update-app-tsconfigs_spec.ts
- packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
- packages/schematics/angular/migrations/update-9/utils.ts
> fix(@schematics/angular): resolve windows paths in tsconfig migration

- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-hashes.ts
This change ensures that any changes to translation files is represented in the output file names when output hashing is enabled.  This prevents the situation where a translation file only change to an application would result in built files with no change in output name.
> fix(@angular-devkit/build-angular): use translation file in bundle hash calculations

- packages/angular_devkit/build_angular/src/angular-cli-files/models/es5-polyfills.js
Several of the string polyfills were mentioned twice in the polyfill imports.
This had no runtime impact since the imports were only included in the application once.
> refactor(@angular-devkit/build-angular): remove redundant ES2015 string polyfills

- packages/angular/cli/commands/doc.json
Backport #16368 to 8.x branch
Closes: #16825
> fix: remove alias for ng doc command

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/build-browser-features.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
By default the browserslist `configPath` will default to `process.cwd()`. This might return incorrect data in a multi app workspace setup.
https://babeljs.io/docs/en/babel-preset-env#configpath
> fix(@angular-devkit/build-angular): provide supported browsers to babel

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/build-browser-features.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
By default the browserslist `configPath` will default to `process.cwd()`. This might return incorrect data in a multi app workspace setup.
https://babeljs.io/docs/en/babel-preset-env#configpath
LTS version of https://github.com/angular/angular-cli/pull/16829
> [LTS] fix(@angular-devkit/build-angular): provide supported browsers to babel

- packages/angular/cli/lib/config/schema.json
- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.__style__.template
- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
- packages/schematics/angular/component/index_spec.ts
- packages/schematics/angular/component/schema.json
This is a proposal regarding the discussion about #12244,  components should create a `display:block` style by default (they really should). However the decision was made to **not change the default behaviour**.  So I was thinking maybe an opt-in kind of way to handle this is a feasible way to go:
```ng generate component dashboard --displayBlock=true```
```
...
"projectType": "application",
"schematics": {
"@schematics/angular:component": {
"displayBlock": true
}
}
...
```
If you think this could be a way forward, I'll look into the following things:
> feat(@schematics/angular): add opt-in option for 'display: block;'

- packages/angular/cli/commands/doc-impl.ts
> fix(@angular/cli): change the url for doc search

- packages/angular_devkit/build_angular/src/protractor/index.ts
The webdriver-manager package is a direct dependency of protractor.  The only guaranteed method to resolve the webdriver-manager package in this case is to resolve it from a base of the protractor location.
> fix(@angular-devkit/build-angular): resolve webdriver-manager from protractor location

- packages/angular/cli/commands/doc-impl.ts
In #16846, the URL for docs search was updated to point to the corresponding vX.angular.io website (with an appropriate query for the search). However, on the archive versions of the website (i.e. versions older than the current stable), non-docs pages (including the home page) are redirected to `/docs` (losing the query params).
This commit fixes the URL to include `/docs`, so that it is not redirected (and preserve the query params that will trigger the search).
> fix(@angular/cli): fix the URL for doc search

- packages/angular_devkit/core/node/host.ts
- packages/angular_devkit/core/node/host_spec.ts
Schematics: rename to a non-existing dir fails on sync to disk #16484
> fix(@angular-devkit/core): Rename to a non-existing dir

- etc/api/angular_devkit/schematics/tools/index.d.ts
- packages/angular/cli/commands/add-impl.ts
- packages/angular/cli/models/schematic-command.ts
- packages/angular/cli/tasks/install-package.ts
- packages/angular_devkit/schematics/tasks/node-package/executor.ts
- packages/angular_devkit/schematics/tasks/node-package/options.ts
- packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
- tests/legacy-cli/e2e/tests/commands/add/registry-option.ts
> Several package install fixes (ng add/update)

- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator.ts
WARNING in budgets exceeded message showing wrong number
Fixes angular#16871.
> fix(@angular-devkit/build-angular): wrong budgets

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/core/src/experimental/workspace/workspace-schema.json
> fix(@angular/cli): expand locale pattern in workspace schema

- packages/angular/cli/bin/ng
This change resolves the error in the console if the nodejs version is not supported showing the actual version instead of "undefined".
> Node.js version *undefined* detected.
> The Angular CLI requires a minimum Node.js version of either v10.13 or v12.0.
> fix(@angular/cli): typo in error message

- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
> fix(@angular-devkit/build-angular): only remove localize polyfill if in AOT mode

- packages/schematics/angular/migrations/update-9/update-app-tsconfigs.ts
- packages/schematics/angular/migrations/update-9/update-app-tsconfigs_spec.ts
> fix(@schematics/angular): add include to type definitions in tsconfig

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/utils.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/action-cache.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- packages/angular_devkit/build_angular/test/browser/differential_loading_spec_large.ts
> fix(@angular-devkit/build-angular): generate correct filenames when targeting ESNext

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
> fix(@angular-devkit/build-angular): insert sourcemap source content when using fast path

- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
This commits allows the cli to correctly print the sum of the sizes of the assets of a given chunk instead of the size of the first emitted asset
Attached:
-Before.PNG: What was happening before the fix in my local environment
-After.PNG: What's happening after the fix, notice that now the size of the "main-client" is the actual sum of the sizes of main-client.js and initial.css
-[webpack.config.js](https://pastebin.com/MreT3kuc): As requested, my current webpack configuration. This problem happens when i'm using the [MiniCssExtractPlugin ](https://github.com/webpack-contrib/mini-css-extract-plugin)to extract my initial.css together with the main client
Before.PNG
After.PNG
> Correctly prints the size of the chunk during the build statistic print

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/protractor/index.ts
- packages/angular_devkit/build_angular/src/protractor/schema.json
- packages/angular_devkit/build_angular/test/protractor/works_spec_large.ts
Jasmine has a useful "tagging" feature that allows specific suites/specs to be targeted by pattern.
Protractor also exposes this via a `grep` option in both the Protractor CLI and Protractor config, as well as an `invertGrep` option that "inverts" whatever pattern was specified in the `grep` option. However, the Angular Protractor Builder currently does not recognize the `grep` or `invertGrep` options, so in order to take advantage of this useful feature, developers had to find a way around the builder.
I added these two options to the Protractor Builder JSON schema, as well as made sure they got passed to the Protractor runner correctly. I also needed to add these options to the top-level Angular CLI schema to satisfy `angular.json`.
1. Because the Protractor config expects these options …
> feat(@angular-devkit/build-angular): pass "grep" and "invertGrep"

- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/lib/cli/index.ts
- packages/angular/cli/utilities/log-file.ts
When an error occurs during `ng update` we currently discard the stack trace which in some cases made it hard to identify the cause of the error.
Now, we print the stack trace to a log file similarly to unhandled exceptions.
Example of CMD output;
```cmd
** Executing migrations of package '@angular/core' **
> Static flag migration.
Removes the `static` flag from dynamic queries.
As of Angular 9, the "static" flag defaults to false and is no longer required for your view and content queries.
Read more about this here: https://v9.angular.io/guide/migration-dynamic-flag
× Migration failed: x
See "C:\Users\alag\AppData\Local\Temp\ng-NgmC1G\angular-errors.log" for further details.
```
Example of log file contents:
```txt
[error] Error: x
at UpdateCommand.executeSchematic …
```
> fix(@angular/cli): print `ng update` errors stack to log file

- packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts
- packages/ngtools/webpack/src/angular_compiler_plugin.ts
We now add non node_modules `.d.ts` as a dependency of the main chunk. This is important under Ivy, because NG metadata is now part of the declarations files ex:
```ts
export declare class FooComponent implements OnInit {
constructor();
ngOnInit(): void;
static ɵfac: i0.ɵɵFactoryDef<FooComponent>;
static ɵcmp: i0.ɵɵComponentDefWithMeta<FooComponent, "lib-foo", never, {}, {}, never>;
}
```
Previously such files were not being added as dependency and such files didn't get invalidated when changed.
Closes #16920 and closes #16921
Ref: TOOL-1323
> fix(@ngtools/webpack): add local dts file as dependencies

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
I noticed that when creating a project with the `minimal` flag like this `npx @angular/cli new my-demo --minimal true` it will create an `app.component.ts` with inline styles and inline templates. However when creating another component with `ng generate component another-component` it will have an external template and external styles.
This pull request tries to fix this inconsistency by setting the `inlineTemplate` and `inlineStyle` options when creating a `minimal` project to make sure all generated components will have inlined styles and templates.
Please let me know if there is anything that needs to be changed.
> fix(@angular/cli): set inlineTemplate and inlineStyle for minimal projects

- packages/ngtools/webpack/src/transformers/elide_imports.ts
- packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
Running the `remove-ivy-jit-support-calls` and `remove_decorators` transformers causes the following TS bug https://github.com/microsoft/TypeScript/issues/17552 which is why the `elide-imports` transformer exists in the first place.
However, when having a syntax like the below;
```ts
import { AccountComponentChild } from '../@types';
export class SignUpComponent implements AccountComponentChild{}
```
The `implements` parts of the class is called a `HeritageClause` with child statements of `ExpressionWithTypeArguments` also the same is for `abstract`. With this change we check the token of the `HeritageClause` and if it's an `ImplementsKeyword` we elide the import.
Closes #16907
Ref TOOL-1324
> fix(@ngtools/webpack): elide imports for `implements` keywords

- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/src/transformers/spec_helpers.ts
- yarn.lock
Spec helper change is related to https://github.com/microsoft/tslib/pull/90
> build: update tslib to 1.11.0

- packages/angular/cli/lib/cli/index.ts
- packages/angular/cli/utilities/color.ts
Third party libraries can attempt to write color codes to the output even though the CLI has already determined that color should not be used.  The previously implemented color removal code is no longer functional since the update of ansi-colors to 4.1.0.  While this appears to be a defect in the aforementioned package, the new CLI removal method not only bypasses the defect but also unneeded execution logic that the CLI does not need in this case.
Fixes: #17053
> fix(@angular/cli): directly remove ansi color codes when no color support

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/index.ts
- packages/angular_devkit/build_angular/src/utils/url.ts
- packages/angular_devkit/build_angular/src/utils/url_spec.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-basehref.ts
`posix.join` will dedupe double forward slashes resulting in incorrect protocol.
Closes: #17029
> fix(@angular-devkit/build-angular): baseHref with protocol and localize option

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
- packages/angular_devkit/build_angular/test/browser/styles_spec_large.ts
Change Scss output style to `expanded` as otherwise sass will remove comments that are needed for autoprefixer when webpack is in prod mode because of the following implementation in `sass-loader`:
See: https://github.com/webpack-contrib/sass-loader/blob/45ad0be17264ceada5f0b4fb87e9357abe85c4ff/src/getSassOptions.js#L68-L70
Fixes #17041
> fix(@angular-devkit/build-angular): fix  autoprefixer comments support in scss

- packages/ngtools/webpack/src/transformers/ctor-parameters.ts
- packages/ngtools/webpack/src/transformers/ctor-parameters_spec.ts
Currently constructor parameters with union types that contains nullable argument are not being converted properly and result in broken behaviour.
With this change we align the ctor-parameters downlevel transformer to be closer to the NGTSC reflector: https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngtsc/reflection/src/typescript.ts#L65-L66
This change should also be synced to ng-packagr.
Closes: #17063
Reference: FW-1883
> fix(@ngtools/webpack): handle union type with a nullable argument

- packages/angular/pwa/pwa/files/root/manifest.webmanifest
Use relative paths instead of absolute paths in `manifest.webmanifest`, so PWA (including the service worker) can work with apps with `base-href` different from just `/`. It's especially important since Angular CLI v9 as the new `--localize` option uses `base-href` values different from just `/`. 
Fixes #16922 
Fixes #15092
> fix(@angular/pwa): use relative paths in webmanifest

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/utils/action-executor.ts
- packages/angular_devkit/build_angular/src/utils/index.ts
- packages/angular_devkit/build_angular/src/utils/workers.ts
See: https://github.com/angular/angular-cli/issues/16860#issuecomment-588828079
> fix(@angular-devkit/build-angular): limit the amount of CPUs used by workers

- packages/ngtools/webpack/src/angular_compiler_plugin.ts
When in JIT mode during lazy route discovery, the Ivy compiler willl attempt to parse templates which may fail when this plugin is used with webpack loaders that support custom template formats.  The string lazy routes must be discovered before the webpack build starts but the template loading/processing does not occur until the webpack build commences.
Fixes: #17002
> fix(@ngtools/webpack): always use VE for deprecated string route discovery

- packages/ngtools/webpack/src/transformers/elide_imports.ts
- packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
Fixes #17080
Reference: TOOL-1334
> fix(@ngtools/webpack): don't elide decorated method parameter type reference

- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.spec.ts.template
- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
- packages/schematics/angular/component/index.ts
- packages/schematics/angular/component/index_spec.ts
Currently, Component and Class have the options to add custom type. In the case of class, It's already working fine with  an empty string in type but in the case  of component When setting the type to an empty string the file names generated will contain an extra period (.) which breaks the flow.
With this PR, It will generate the files without an extra period (.)
Reference #16811 and #16891
> fix(@schematics/angular): Allow empty string in the type option

- scripts/changelog.ts
If generating a changelog between tags that are on different branches (e.g., 9.0.3 on 9.0.x and 9.1.0-next.0 on master), commits that were cherry-picked and present in the previous version would also show in the newer version's changelog.  This update analyzes the commits and excludes any that fit this scenario.  Any commits that had conflicts will not be able to be matched authoritatively.  Manual review of the generated changelog may still be needed for attempted cherry-pick commits that had conflicts.
> build: exclude redundant cherry-picked commits when generating changelog

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
- packages/ngtools/webpack/package.json
- packages/schematics/angular/migrations/update-9/update-server-main-file.ts
- packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
- packages/schematics/schematics/blank/project-files/package.json.template
- packages/schematics/schematics/schematic/files/package.json
- yarn.lock
New projects are not yet created with TypeScript 3.8.  That change requires support from within the AOT compiler and can be done separately once supported.
> Initial TypeScript 3.8 Support

- packages/schematics/angular/workspace/files/tsconfig.json.template
By default TypeScript will look up in this directory (see [docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types)).
> refactor(@schematics/angular): remove redundant typeRoots

- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-locale-data.ts
This synchronizes the behavior with the FW's wherein the language code will be used if the data for the full locale is not found.  The user will still be notified in the event this occurs.
> fix(@angular-devkit/build-angular): provide locale data discovery fallbacks

- tests/angular_devkit/build_webpack/angular-app/tsconfig.json
This is to avoid having NGCC go through and transform ES5 entrypoints
> test: change webpack angular tests to use es2015 

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- tests/legacy-cli/e2e/tests/commands/serve/reload-shims.ts
This change reduces the workaround to a single file location as well as ensuring that only the shims of interest from the two necessary live reload files are affected.  This makes sure that build and serve behavior is the same in this regard.
> fix(@angular-devkit/build-angular): ensure live-reload shim workaround isolation

- packages/ngtools/webpack/src/ngcc_processor.ts
Under Bazel some dependencies might be readonly we shouldn't run NGCC async version because we are unable to verify which modules are read-only and which not.
> fix(@ngtools/webpack): disable ngcc async under Bazel

- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-10/update-tslint.ts
- packages/schematics/angular/migrations/update-10/update-tslint_spec.ts
- packages/schematics/angular/workspace/files/package.json.template
- packages/schematics/angular/workspace/files/tslint.json.template
- tests/angular_devkit/build_angular/hello-world-app-ve/tslint.json
- tests/angular_devkit/build_angular/hello-world-app/tslint.json
- tests/angular_devkit/build_ng_packagr/ng-packaged-ve/tslint.json
- tests/angular_devkit/build_ng_packagr/ng-packaged/tslint.json
tslint 6.1 adds support for TypeScript 3.8 syntax
See: https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v610
Pr to update the package in the repo https://github.com/angular/angular-cli/pull/17202
See individual commits for more details.
> feat(@schematics/angular): generate new projects with tslint 6.1.0

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/any-component-style-budget-checker.ts
- packages/angular_devkit/build_angular/test/browser/bundle-budgets_spec_large.ts
Currently anyComponentStyle works only for css styles. Files with other extensions are ignored.
> fix(@angular-devkit/build-angular): add missing styles extensions in anyComponentStyle budget

- packages/angular/cli/commands/update-long.md
Update upgrade guide to reference version 9 as the latest angular version
> docs: update latest angular version referenced in upgrade guide

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/common-js-usage-warn-plugin.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/webpack.ts
- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/test/browser/common-js-warning_spec_large.ts
feat(@angular-devkit/build-angular): show warnings when depending on CommonJS.
Depending on CommonJS modules is know to cause optimization bailouts. With this change when running a browser build and scripts optimization is enabled we display a warning.
To suppress the warning for a particular package, users can use the `allowedCommonJsDepedencies` builder options.
Example:
```
"build": {
"builder": "@angular-devkit/build-angular:browser",
"options": {
...
"allowedCommonJsDepedencies": ["bootstrap"]
},
}
```
Reference: TOOL-1328
> feat(@angular-devkit/build-angular): show warnings when depending on CommonJS

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
High fidelity sourcemap processing can be expensive for larger bundle sizes.  This reduces the threshold to the original 500KB value to improve performance.
> fix(@angular-devkit/build-angular): reduce fast sourcemap threshold

- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-es2015.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-es5.ts
> fix(@angular-devkit/build-angular): improve quality of localized source maps

- docs/process/release.md
This commit adds guidance on when to merge commits into LTS branches and how PRs should be opened.
Please note that the third criteria is not in effect for now since we don't run CI on LTS branches. We'll discuss this in the upcoming tooling meeting.
> docs: Update policy on LTS fixes

- docs/process/release.md
This excludes draft PRs from Caretaker search, as the Caretaker does not actually care about draft PRs.
Also took the opportunity to make the `latest-versions.ts` file a clickable link, because it is a pain to navigate to that file in GitHub's UI.
> docs: adds `-is:draft` to Caretaker search

- packages/angular_devkit/schematics/tools/node-module-engine-host.ts
> fix(@angular-devkit/schematics): fully resolve schematic entries within packages

- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
When generating a new component, if `inlineStyle` and either
`viewEncapsulation` or `changeDetection` flag are provided, there is an
extra comma after `styles: [],,` causing the component to bug out.
- With `ChangeDetection`
```typescript
@Component({
selector: 'app-test-two',
templateUrl: './test-two.component.html',
styles: [
],, // <-- extra comma
changeDetection: ChangeDetectionStrategy.OnPush
})
export class TestTwoComponent implements OnInit {
constructor() { }
ngOnInit(): void {
}
}
```
- With both `ViewEncapsulation` and `ChangeDetection`
```typescript
import { Component, OnInit, ViewEncapsulation, ChangeDetectionStrategy } from '@angular/core';
@Component({
selector: 'app-test-three',
templateUrl: './test-three.component.html',
styles: [
],, // <-- extra comma
encapsulation: …
```
> fix(@schematics/angular): remove extra comma when inlineStyle is on

- packages/schematics/angular/migrations/update-10/update-tslint.ts
> fix(@schematics/angular): clarify tslint:recommended warning message

- packages/angular/cli/commands/deploy.json
fix(@angular/cli):  allow configuration option in `ng deploy`
Previously we only allowed `--project` and `--help` as a valid options. With this change we also allow `--configuration`
Fixes #17332
> fix(@angular/cli):  allow configuration options in `ng deploy`

- package.json
- packages/angular/cli/package.json
- packages/schematics/update/package.json
- yarn.lock
Closes #17314 and closes #16615
Patch version of https://github.com/angular/angular-cli/pull/17358
> fix(@angular/cli): downgrade pacote to 9.5.12

- packages/angular_devkit/build_angular/src/server/schema.json
- packages/schematics/angular/universal/files/root/__tsconfigFileName__.json.template
- packages/schematics/angular/universal/index_spec.ts
- tests/angular_devkit/build_angular/hello-world-app-ve/src/tsconfig.server.json
- tests/angular_devkit/build_angular/hello-world-app/src/tsconfig.server.json
With this change, lazy-loading on the server becomes enabled out of the box for new projects. This is because webpack will only split ES6 imports into separate chunks. However when using commonjs all lazy loaded paths will be concatenated into the main.js file.
> feat(@schematics/angular): enable lazy loading on the server for new projects

- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
- tests/legacy-cli/e2e/ng-snapshot/package.json
- tests/legacy-cli/e2e/tests/build/material.ts
- yarn.lock
When used within the build optimizer, TypeScript 3.8 will consider certain imports to be unreferenced and errantly remove them even though they are used within the module.  This results in runtime errors during application load.  TypeScript 3.7 cannot be used due to it causing a build time error when used within the build optimizer.  The build optimizer uses an independent version of TypeScript which allows it to use TypeScript 3.6 while applications continue to use TypeScript 3.7 or 3.8 to build the actual application.
Fixes: #17320
> fix(@angular-devkit/build-optimizer): use TypeScript 3.6

- renovate.json
In most cases, this setting up creating more PRs instead of reducing them. This is because if a depedency is listed as both a `devDependencies` and `dependencies`, Renovate will create 2 PRs;
Example: https://github.com/angular/angular-cli/pull/17380 and https://github.com/angular/angular-cli/pull/17379
This will happen more often now when adding Bazel integration tests see: https://github.com/angular/angular-cli/pull/17304#discussion_r400840301
> ci: disable separate renovate PRs for devDependencies and dependencies

- packages/angular/pwa/pwa/files/root/manifest.webmanifest
The `purpose` property defines the purpose of an icon, for example if the icon is intended to serve some special purpose in the context of the host OS (i.e., for better integration).
`Purpose` can have one or more of the following values, separated by spaces:
- `badge`: A user agent can present this icon where space constraints and/or color requirements differ from those of the application icon.
- `maskable`: The image is designed with icon masks and safe zone in mind, such that any part of the image outside the safe zone can safely be ignored and masked away by the user agent.
- `any`: The user agent is free to display the icon in any context (this is the default value).
Closes #17384
> fix(@angular/pwa): add purpose any to manifest icons

- packages/angular_devkit/build_angular/src/browser/index.ts
All non-processed files are copied from the temporary location during localization.  Previously original sourcemap files were not marked as processed.
> fix(@angular-devkiit/build-angular): avoid overwriting localize sourcemaps

- docs/process/release.md
- scripts/publish.ts
If no `--registry` argument is provided when calling to publish
use the Wombat proxy.  Additionally, updates the release process
documentation to instruct usage of the Wombat proxy.
> build: default to wombat proxy for publishing

- .circleci/config.yml
Initial base set of tests to execute daily on the 8.3.x LTS branch.
NOTE TO CARETAKER: pending status of `ci/angular: merge status` is incorrect and can be ignored. The two missing status checks do not exist on this branch.
> Schedule daily CI for LTS branch 8.3.x

- lib/packages.ts
Currently, we can't publish v10 because the `--match` pattern in describe can't match the tag `v10.0.0`. The new glob has the following semantics:
```
v[0-9]*.[0-9]*.[0-9]*
```
Couldn't make it stricter because didn't find an easy way to enable extglobs for git for everyone.
> build: version from git tag which consists two or more digits

- packages/ngtools/webpack/src/angular_compiler_plugin.ts
When Ivy is enabled in an app, the app's dependencies are processed by ngcc (the Angular compatibility compiler), which will generate new Ivy-compatible entry-points in each package. To allow webpack find those entry-points, it will add references to them in `package.json`, named after the original property with the `_ivy_ngcc` suffix. So, for example, `es2015` and `module` will become `es2015_ivy_ngcc` and `module_ivy_ngcc`.
Previously, the `mainFields` passed to webpack would give higher priority to an Ivy entry-point compared to the corresponding non-ivy entry-point but not compared to other entry-points. For example, `es2015, module` would becode `es2015_ivy_ngcc, es2015, module_ivy_ngcc, module`. This could mean that `es2015` would be preferred over `module_ivy_ngcc`, even though the …
> fix(@ngtools/webpack): give higher priority to ivy-specific entry-points

- tests/angular_devkit/build_ng_packagr/ng-packaged-ve/tsconfig.json
- tests/angular_devkit/build_ng_packagr/ng-packaged/tsconfig.json
This seems to be the root cause of the failures in the following PR:
https://github.com/angular/angular-cli/pull/17455
> test: update ng-packagr tests tsconfig as per CLI default

- packages/angular_devkit/core/src/workspace/json/reader_spec.ts
- packages/angular_devkit/core/src/workspace/json/utilities.ts
Spread and Rest uses `[[GetOwnProperty]]`. Previously, properties with falsy values were being removed when using the spread operator due to an incorrect check.
https://tc39.es/proposal-object-rest-spread/#AbstractOperations-CopyDataProperties
Fixes #17021
> fix(@angular-devkit/core): workspace reader spread/rest operator usage with falsy values

- docs/process/release.md
This is a few different edits to make caretakers more aware of problems that can occur during a release.
* Added a comment to reinforce that pushing tags needs to happen with the push of the release commit. Otherwise CI can fail `npm install` because the relevant tags are not set.
* Changed to check out the publish branch rather than the tag because checking out a tag fails the subsequent `publish` command.
* Added `yarn` before the `publish` command because dependencies may be out of date and cause errors.
> docs: add notes about various release foot-guns

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/schematics/angular/workspace/files/package.json.template
- yarn.lock
With this change we generate new workspaces with Karma version 5.
The previous version has several security vulnerabilities which were addressed in version 5.
https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#500-2020-04-09
Closes #17388 and closes #17241
> fix(@schematics/angular): generate new projects with Karma v5

- packages/schematics/angular/guard/index.ts
- packages/schematics/angular/guard/schema.json
- packages/schematics/angular/migrations/migration-collection.json
BREAKING CHANGE
Deprecated guard schematic option `spec` has been removed. Please use `skipTests` instead.
> refactor(@schematics/angular): remove deprecated guard `spec` option

- packages/schematics/angular/workspace/files/package.json.template
This version of codelyzer will not be broken after the removal of view engine from Angular's code base.
> build: update to codelyzer@6.0.0-next.1

- .circleci/config.yml
Cache fallback can be useful in some cases, but in our case it is hindering the CI performance as the cache is growing everyday which results in slower CI times because of the restoring and saving phases.
A fresh cache size is about 450Mb, while currently with fallbacking enabled it has grown to 3.8Gb
Below are some timings taken were we see that having cache fallbacking is doesn't help CI times:
| Caching                   | Cache Size | Restore Cache | Yarn Install | Save Cache | Total Time Elapsed |
|---------------------------|------------|---------------|--------------|------------|--------------------|
| Cache w/ Fallback (Miss)  | 3.81Gb     | 2m 50s        | 30s          | 7m 20s     | 10m 40s            |
| Cache w/ Fallback (Hit)   | 3.81Gb      | 2m 50s        | 20s          | …
>  ci: remove circle ci cache fallback

- packages/schematics/angular/app-shell/app-shell-long.md
`universal-project` has been deprecated and has no effect. See: https://github.com/angular/angular-cli/blob/493aa74019104fe029e3527b519918a0ae6febf0/packages/schematics/angular/app-shell/schema.json#L19
> docs: remove `universal-project` options reference from app-shell docs

- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/postcss-cli-resources.ts
- packages/angular_devkit/build_angular/test/browser/styles_spec_large.ts
- yarn.lock
Previously, when using a preprocessor, resources (e.g., `url(./my-image.jpg)`) referenced in a stylesheet that was imported into another stylesheet would retain the exact URL.  This would be problematic as the resource would not be at the relative location within the new combined stylesheet.  With this change the resource URLs will now be adjusted to reference the origin location of the resource.  This allows the resources to be found without any additional changes to the application or build process.
CSS and Less already functioned in this manner. This change brings Sass and Stylus to parity.
Fixes: #12797
> rebase relative stylesheet assets when using preprocessors

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/optimize-css-webpack-plugin.ts
SVGO can cause optimizations which are not compatible in all browsers.
FIxes: #17564
> fix(@angular-devkit/build-angular): disable inline svg optimizations

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
This path mapping was used during the transition to rxjs 5 via the use of rxjs-compat package during the Angular 5.x timeframe.  Now that the minimum version is 6.x and this transition is complete, these mappings are no longer necessary.
> refactor(@angular-devkit/build-angular): remove unused rxjs path mapping

- package.json
Disable ngcc async mode, because the circle ci container is low on resources and causes worker failures when run in async.
> ci: disable ngcc async

- packages/schematics/angular/workspace/files/package.json.template
This package is no longer required since the VS code extension is already shipped with it.
> [PATCH] fix(@schematics/angular): don't add `@angular/language-service` in new Angular projects

- packages/ngtools/webpack/src/angular_compiler_plugin.ts
`isSupported` method has been removed from `AngularCompilerPlugin` as it has become redundant with peer dependencies.
Note: this change only effects direct `@ngtools/webpack` users and not the application developers.
> refactor(@ngtools/webpack): remove deprecated isSupported method

- packages/angular_devkit/build_angular/src/server/schema.json
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-10/update-angular-config.ts
BREAKING CHANGE: options `commonChunk` and `vendorChunk` have been removed from the server builder.
Note: this change only effects direct @angular-devkit/build-angular users and not the application developers as users will be migrated automatically off these options.
> refactor(@angular-devkit/build-angular): remove unused server builder options

- integration/angular_cli/package.json
- packages/schematics/angular/workspace/files/package.json.template
This package is no longer required since the VS code extension is already shipped with it.
> fix(@schematics/angular): don't add `@angular/language-service` in new Angular projects

- etc/api/angular_devkit/schematics/testing/index.d.ts
- packages/angular_devkit/schematics/testing/schematic-test-runner.ts
- packages/schematics/angular/interceptor/index_spec.ts
BREAKING CHANGE
Deprecated `SchematicTestRunner.runSchematic` and  `SchematicTestRunner.runExternalSchematic` have been removed. Use `SchematicTestRunner.runSchematicAsync` or `SchematicTestRunner.runExternalSchematicAsync` instead.
Note: this change only effects direct `@angular-devkit/schematics` users and not the application developers.
> refactor(@angular-devkit/schematics): remove deprecated sync test helpers

- packages/ngtools/webpack/src/transformers/replace_resources.ts
- packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
Previously, the import default TypeScript helper was emitted for every file when in JIT mode.  This was unused code in the majority of cases.  The helper is now emitted only when needed.  For this package that would be when an Angular component decorator's resource URL properties are adjusted to support JIT execution with Webpack.
> fix(@ngtools/webpack): only emit import default helper when needed

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/application/other-files/package.json.template
- packages/schematics/angular/application/schema.json
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-10/side-effects-package-json.ts
- packages/schematics/angular/migrations/update-10/side-effects-package-json_spec.ts
- packages/schematics/angular/ng-new/index.ts
- packages/schematics/angular/ng-new/schema.json
- packages/schematics/angular/workspace/files/tsconfig.json.template
- packages/schematics/angular/workspace/index_spec.ts
- packages/schematics/angular/workspace/schema.json
- tests/legacy-cli/e2e/setup/500-create-project.ts
- tests/legacy-cli/e2e/tests/basic/ivy-opt-out.ts
- tests/legacy-cli/e2e/tests/build/strict-mode.ts
- tests/legacy-cli/e2e/tests/build/strict-workspace.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl-xliff2.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-es2015.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-es5.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-serviceworker.ts
- tests/legacy-cli/e2e/tests/i18n/ve-localize-es2015.ts
- tests/legacy-cli/e2e/tests/packages/webpack/test-app.ts
- tests/legacy-cli/e2e/utils/project.ts
With this change we enable stricter type checking and optimization effective coding rules when using the `--strict` option.
Changes in schematics
- `ng-new`: A prompt for the `strict` option was added. This option is a proxy and will be passed to the application and workspace schematics.
- `application`: A `package.json` was added in the `app` folder, to tell the bundlers whether the application is free from side-effect code. When `strict` is `true`. the `sideEffects` will be set `false`.
- `workspace` When `strict` is true, we add stricter TypeScript and Angular type-checking options.
Note: AIO is already using these strict TypeScript compiler settings. PR to enable `strictTemplates`  https://github.com/angular/angular/pull/36391
Reference: TOOL-1366
> feat(@schematics/angular): enable stricter type checking and optimization effective coding rules 

- packages/ngtools/webpack/src/angular_compiler_plugin.ts
`.ngtypecheck.ts` files are used by NGTSC for type-checking purposes.
See: https://github.com/angular/angular/pull/36211
> fix(@ngtools/webpack): don't emit unused file warning for`.ngtypecheck.ts`

- .idea/angular-cli.iml
Exclude .yarn directory from IntelliJ IDEs searches. Selecting a Yarn release file from the files search results will cause the IDE to halt, this commit removes those files from search results.
To recover from such a situation you need to `killall -9 java`.
The configuration files for IntelliJ IDEs were added in c5671e08699d165941c82ccb8a8837329259fc68
cc: @dgp1130
> refactor(@angular/cli): exclude .yarn directory

- integration/angular_cli/e2e/tsconfig.json
- integration/angular_cli/tsconfig.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator.ts
- packages/angular_devkit/build_angular/test/hello-world-app/e2e/tsconfig.e2e.json
- packages/angular_devkit/build_angular/test/hello-world-app/tsconfig.json
- packages/angular_devkit/build_ng_packagr/test/ng-packaged/tsconfig.json
- packages/angular_devkit/build_webpack/test/angular-app/src/tsconfig.app.json
- packages/schematics/angular/e2e/files/tsconfig.json.template
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-10/update-module-and-target-compiler-options.ts
- packages/schematics/angular/migrations/update-10/update-module-and-target-compiler-options_spec.ts
- packages/schematics/angular/workspace/files/tsconfig.json.template
- tests/legacy-cli/e2e/assets/1.7-project/e2e/tsconfig.e2e.json
- tests/legacy-cli/e2e/assets/7.0-project/e2e/tsconfig.e2e.json
With this change we update the target and module settings of various compilation units.
- We replace ES5 target in protractor. Protractor runs on Node.Js which support ES2018
- For applications we now use `ES2020` instead of `ESNext` as a module to avoid unexpected changes in behaviour
This changes also adds a migration to update existing projects and also removes `module` from the Universal tsconfig as per #17352 to enable lazy loading on the server.
> feat(@schematics/angular): update compiler options target and module settings

- packages/schematics/angular/app-shell/index.ts
- packages/schematics/angular/app-shell/index_spec.ts
- packages/schematics/angular/app-shell/schema.json
- packages/schematics/angular/universal/schema.json
BREAKING CHANGE:  The below options have been removed as they had no effect:
- `test` and `testTsconfigFileName` have been removed form the universal schematic
- `universalProject`, `name`, `outDir`, `root` and `index` have been removed from the app-shell schematic
> refactor(@schematic/angular): remove deprecated options from app-shell and universal schematics

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl-xliff2.ts
Locale data is now transformed to be compatible with the ECMAScript level of the application bundles.  The locale data is also optimized to remove comments and unnecessary whitespace.
Fixes: #17497
> fix(@angular-devkit/build-angular): downlevel and optimize locale data

- packages/angular/cli/commands/config-impl.ts
- packages/angular/cli/lib/config/schema.json
- packages/angular/cli/models/command-runner.ts
- packages/schematics/angular/migrations/update-10/update-angular-config.ts
- packages/schematics/angular/migrations/update-10/update-angular-config_spec.ts
- packages/schematics/angular/utility/config.ts
Removed deprecated `typescriptMismatch` warning option. Users will be migrated off this option automatically. Users wishing to disable TypeScript version checks should use the Angular compiler option `disableTypeScriptVersionCheck`, see https://angular.io/guide/angular-compiler-options#disabletypescriptversioncheck for more information.
> refactor(@angular/cli): remove deprecated typescriptMismatch

- scripts/validate-licenses.ts
This is required for tslib versions >= 1.11.2. Tslib changed it's license to 0BSD which should allow projects that embed or bundle tslib to omit its license header.
See: https://opensource.google/docs/thirdparty/licenses/#unencumbered
> ci: add 0BSD as a valid license

- tests/legacy-cli/e2e/tests/misc/third-party-decorators.ts
The older versions used (6.x) do not work with newer versions of Angular 10+ due to breaking changes in later majors.
> test: update third-party decorators E2E to use latest package versions

- .circleci/config.yml
CI on master is currently failing because the node v10 e2e test is failing due to the following error:
```
error move-file@2.0.0: The engine "node" is incompatible with this module. Expected version ">=10.17". Got "10.16.3"
```
> ci: Use node v10.20 for node v10 e2e test

- packages/angular_devkit/build_optimizer/BUILD.bazel
- packages/angular_devkit/build_optimizer/no_typescript_runtime_dep_spec.js
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts
- packages/angular_devkit/build_optimizer/src/helpers/transform-javascript.ts
- packages/angular_devkit/build_optimizer/src/transforms/prefix-classes.ts
- packages/angular_devkit/build_optimizer/src/transforms/prefix-functions.ts
- packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
- packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
- packages/angular_devkit/build_optimizer/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
- packages/angular_devkit/build_optimizer/third_party/github.com/Microsoft/TypeScript/LICENSE
- packages/angular_devkit/build_optimizer/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
- packages/schematics/angular/no_typescript_runtime_dep_spec.js
- packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
- yarn.lock
With this change we "vendor" TypeScript 3.6 in build optimizer instead of using directly the npm package.
Reasons:
- We cannot update to a more recent version of TypeScript due to microsoft/TypeScript#38412
- Yarn workspace are not supported under Bazel. This means currently we are running unit testswhich uses a different TypeScript version at runtime.
- In TypeScript 3.9, the shape of ES2015 classes changed microsoft/TypeScript#32011, this requires some changes in the UT expects, but this again will not be correct to change now.
>  build: vendor typescript 3.6 in build optimizer

- package.json
This reverts commit 6c8b0f131595edcc278e14a4723ff01fd4419279.
Should no longer be needed, as @gkalpak did a fix for this.
> revert: "ci: disable ngcc async"

- packages/ngtools/webpack/src/compiler_host.ts
- packages/ngtools/webpack/src/utils.ts
Unlike TSC which has it's own mechanism the resolve and join paths in POSIX format, NGTSC heavily relies onNode.JS `fs` and `path` modules. This prevents `Path` usage because in Windows `path.resolve` will causes an absolute path to be resolved or joined incorrectly.  Example:  `/D/MyPath/MyProject` -> `D:/d/mypath/myproject`.
With this change we change the `getCanonicalFileName` method to return FS compatible paths.
> fix(@ngtools/webpack): getCanonicalFileName should return FS compatible paths

- WORKSPACE
- package.json
- yarn.lock
Migrates to using @bazel/bazelisk rather than @bazel/bazel as the
latter is being deprecated.  @bazel/bazelisk is a drop in
replacement for @bazel/bazel.
> build: use @bazel/bazelisk rather than @bazel/bazel

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/protractor/index.ts
- packages/angular_devkit/build_angular/src/protractor/schema.json
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-10/update-angular-config.ts
- packages/schematics/angular/migrations/update-10/update-dependencies.ts
- packages/schematics/angular/workspace/files/package.json.template
- tests/legacy-cli/e2e/tests/basic/e2e.ts
potractor <7 contains a low severity vulnerability due to one of its dependencies (yargs-parser)
See: https://npmjs.com/advisories/1500
Fixes #17642
Protractor `elementExplorer` debugger and element explorer cannot be used for Node.js 8+ since it relied on `_debugger` module.
In protractor version 5, this resulted in the below error:
```
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
[10:25:35] I/direct - Using ChromeDriver directly...
[10:25:37] I/protractor -
[10:25:37] I/protractor - ------- Element Explorer -------
[10:25:37] I/protractor - Starting WebDriver debugger in a child process. Element Explorer is still beta, please report issues at github.com/angular/protractor
[10:25:37] …
```
> fix(@schematics/angular): address vulnerability in protractor

- docs/process/release.md
Since we are just doing round robin, I deleted the google3 tooling rotation and made a new public calendar (link in the commit).
> docs: add primary-secondary pairs and update calendar link

- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/protractor/index.ts
- packages/angular_devkit/build_angular/src/protractor/schema.json
- packages/schematics/angular/workspace/files/package.json.template
- tests/legacy-cli/e2e/tests/basic/e2e.ts
- yarn.lock
webpack-dev-server <3.11.0 and protractor <7 contains a low severity vulnerability due to one of its dependencies (yargs-parser)
See: https://npmjs.com/advisories/1500
Fixes #17642
> Address vulnerability in protractor and webpack-dev-server

- packages/angular_devkit/build_angular/package.json
- packages/schematics/angular/workspace/files/package.json.template
- tests/legacy-cli/e2e/tests/basic/e2e.ts
- yarn.lock
webpack-dev-server <3.11.0 contains a low severity vulnerability due to one of its dependencies (yargs-parser).  This change updates to 3.11.0 to remove the vulnerability.
https://npmjs.com/advisories/1500
Closes: #17716
> fix(@angular-devkit/build-angular): address vulnerability in webpack-dev-server

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/common-js-usage-warn-plugin.ts
Add a link to https://web.dev/commonjs-larger-bundles when a commonJS module is used in browsers builds
> fix(@angular-devkit/build-angular): add link when displaying commonJS usage warnings

- packages/schematics/angular/library/files/package.json.template
Tslib version is bound to the TypeScript version used to compile the library. Thus, we shouldn't list `tslib` as a `peerDependencies`. This is because, a user can install libraries which have been compiled with older versions of TypeScript and thus require multiple `tslib` versions to be installed.
Reference: TOOL-1374
> fix(@schematics/angular): add tslib as a direct dependency for new libraries

- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
- yarn.lock
The newly introduced plugin can cause performance degradation during builds.  This becomes more apparent the larger the project becomes.  Switching to the previous plugin removes the performance problems.
> Revert license checker plugin to previously used plugin

- packages/angular_devkit/core/src/json/schema/registry.ts
- packages/angular_devkit/core/src/json/schema/registry_spec.ts
`http://json.schemastore.org/tslint` has moved permanently to `https://json.schemastore.org/tslint` which is causing this test to fail
(cherry picked from commit 8d1309e697fbe78a23b1e7cd2c70ee995c1bb777)
> test: make CoreSchemaRegistry test green again

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/single-test-transform.ts
- packages/angular_devkit/build_angular/src/karma/selected_spec.ts
Minor cleanup of SingleTestTransformLoader and fix interface issue which causes  #17823 to be red.
> refactor(@angular-devklit/build-angular): clean up SingleTestTransformLoader

- packages/angular_devkit/build_angular/test/hello-world-app/src/tsconfig.server.json
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-10/update-module-and-target-compiler-options.ts
- packages/schematics/angular/migrations/update-10/update-module-and-target-compiler-options_spec.ts
- packages/schematics/angular/universal/files/root/tsconfig.server.json.template
- packages/schematics/angular/universal/index_spec.ts
fix(@schematics/angular): use ES2016 as syntax target for server bundles
The supported versions of Node.js support up to ES2018, the only reason why we don't use ES2017+ is because native `async` and `await` don't work with zone.js
See: https://github.com/angular/angular/issues/31730
With this change, we also ensure that we don't downlevel the server bundle to ES5 which is unnecessary.
Closes: #17794
> fix(@schematics/angular): use ES2016 as syntax target for server bundles

- tests/legacy-cli/e2e/tests/build/differential-cache.ts
There is a large amount of performance variability on CI which can cause test flakes.
> test: skip differential loading cache test on CI

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/optimize-css-webpack-plugin.ts
Disable `calc` optimizations due to several issues.
Closes #16910 closes #16875 and closes #17890
> fix(@angular-devkit/build-angular): disable CSS `calc` optimizations

- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- yarn.lock
Fixes security issue serialize-javascript prior to 3.1.0 allows remote attackers
Closes #17912
> fix(@angular-devkit/build-angular): update terser-webpack-plugin to 3.0.3

- packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/tsconfig.lib.json
- packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/tsconfig.lib.prod.json
- packages/schematics/angular/library/files/tsconfig.lib.json.template
- packages/schematics/angular/library/files/tsconfig.lib.prod.json.template
With this change we enable emitting declaration maps when building libraries to be consumed locally as this improved DX as this will allow editors to go to the original typescript file when using `Go to Definition`.
For production builds, declaration maps are disabled because they are not useful since the source files are not included in the distributable package.
Closes #17888
> feat(@schematics/angular): emit declaration maps for local library builds

- packages/angular/cli/models/architect-command.ts
Adds a check to see if the specified project exists, otherwise throws an error. This prevents it from falling through to the "build target not supported" error which is misleading.
Closes #17682
> fix(@angular/cli): throw error when specified project does not exist

- tests/legacy-cli/e2e/tests/misc/dedupe-duplicate-modules.ts
This commit attempts to identify flakiness in the dedupe-duplicate-modules.ts test
in which the signature string occasionally fails to show up in stderr.
Dumping out the whole stderr would help us identify the bug.
Example failure on master:
https://app.circleci.com/pipelines/github/angular/angular-cli/7867/workflows/fdabb867-5dbe-4b85-80c5-24b6bca328dd/jobs/167264/steps
> test: print stderr if DedupeModuleResolvePlugin not found

- tests/legacy-cli/e2e/tests/misc/dedupe-duplicate-modules.ts
Following #17973, which we emitted the stderr when this test failed on CI.
We see that the resolved module order sometimes changes, which is totally fine because of the async nature of the operation.
https://circleci.com/gh/angular/angular-cli/167318#tests/containers/5
```
[DedupeModuleResolvePlugin]: /tmp/angular-cli-e2e-i03vMQ/test-project/node_modules/tslib-1 -> /tmp/angular-cli-e2e-i03vMQ/test-project/node_modules/tslib-1-copy
```
With this change we handle both cases which should eliminate the flakes
> ci: fix dedupe-duplicate-modules flakes

- packages/schematics/angular/migrations/migration-collection.json
This adds links to current migration guides for several of the migrations as well as adjusts some of the descriptions to provide additional inline information.
Blocked on migration guide inclusions:
https://github.com/angular/angular/pull/37512
https://github.com/angular/angular/pull/37429
https://github.com/angular/angular/pull/37402
> docs(@schematics/angular): update v10 migration descriptions

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/browser/specs/assets_spec.ts
Optimized asset processing was only being performed when differential loading was enabled.  This change ensures that the optimized approach is used for all builds.  This does not affect `ng serve` usage since it currently requires all application files to be in memory.
> fix(@angular-devkit/build-angular): use copy-on-write asset processing for non-watch builds

- tests/legacy-cli/e2e/tests/misc/dedupe-duplicate-modules.ts
Following #17973, which we emitted the stderr when this test failed on CI.
We see that the resolved module order sometimes changes, which is totally fine because of the async nature of the operation.
https://circleci.com/gh/angular/angular-cli/167318#tests/containers/5
```
[DedupeModuleResolvePlugin]: /tmp/angular-cli-e2e-i03vMQ/test-project/node_modules/tslib-1 -> /tmp/angular-cli-e2e-i03vMQ/test-project/node_modules/tslib-1-copy
```
With this change we handle both cases which should eliminate the flakes
(cherry picked from commit bf599e4fac433c0b7041b5fac72d10a1677070cc)
> [patch] ci: fix dedupe-duplicate-modules flakes

- tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js
```
UnsupportedOperationError: Misconfigured -- Unsupported OS/browser/version/device combo: OS: 'Mac 10.15', Browser: 'safari', Version: '13.0.', Device: 'unspecified'
```
> ci: fix saucelabs unsupported OS/browser/version/device combo

- tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js
- tests/legacy-cli/e2e/tests/build/material.ts
- tests/legacy-cli/e2e/tests/update/update-1.0.ts
- tests/legacy-cli/e2e/tests/update/update-1.7-longhand.ts
- tests/legacy-cli/e2e/tests/update/update-1.7.ts
- tests/legacy-cli/e2e/tests/update/update-7.0.ts
```
UnsupportedOperationError: Misconfigured -- Unsupported OS/browser/version/device combo: OS: 'Mac 10.15', Browser: 'safari', Version: '13.0.', Device: 'unspecified'
```
(cherry picked from commit 5a894657e94cdf3b7d3c51f3f581e5b51da154f2)
> [LTS] ci: make v9 patch branch green

- packages/schematics/angular/migrations/update-10/solution-style-tsconfig.ts
- packages/schematics/angular/migrations/update-10/solution-style-tsconfig_spec.ts
During the solution-style-tsconfig migration we are unexpectedly erroring out when encounter a blank JSON file. This PR fixes this behaviour and also prints the file path when an error occurs when parsing JSON contents.
Closes: #18012 and closes: #18038
> fix(@schematics/angular): don't error out on blank JSON files during migrations

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
Prior versions of copy-webpack-plugin 6.x contained a memory usage regression that could cause gigabytes of memory to be used during a build.  Version 6.0.3 contains a fix that prevents this issue.
Referenced Issue: https://github.com/webpack-contrib/copy-webpack-plugin/issues/505
10.0.x variant of https://github.com/angular/angular-cli/pull/18088
PR closes https://github.com/angular/angular-cli/issues/18087
> fix(@angular-devkit/build-angular): update copy-webpack-plugin to 6.0.3

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/common-js-usage-warn-plugin.ts
- packages/angular_devkit/build_angular/src/browser/specs/common-js-warning_spec.ts
**fix(@angular-devkit/build-angular): match allowed dependencies against the package name**
With this change we add the functionality to also match an allowed dependency against a package name. The package name is retrieved from the rawRequest.
Previously, users needed to add the request path which in some case might be a deep import. Ex: `zone.js/dist/zone-error`. With this change adding the package name example `zone.js` will suffice.
Closes: #18058
**fix(@angular-devkit/build-angular): show warning when using non global locale data**
When using the `localize` option directly importing locale data from `@angular/common` is not needed because the Angular CLI  will automatically include locale data. When not using the `localize` option, most likely users meant to import the global variant …
> fix(@angular-devkit/build-angular): several fixes for commonjs warnings 

- packages/ngtools/webpack/src/ngcc_processor.ts
With this change we consume the change in https://github.com/angular/angular/pull/37075 where the NGCC now exposes a new option `--use-program-dependencies`, to only process packages which are part of the TypeScript program.
From the initial benchmarking the time taken for NGCC to process that dependencies needed for an `ng new` application went down by 36% from 10526ms to 6708ms.
> perf(@ngtools/webpack): only process dependent packages with NGCC

- packages/angular/cli/commands/update-impl.ts
> Fix for migration from v8.x to v9.x installs latest @angular-devkit/build-angular (0.1000.0) and tslib (2.0.0)

- packages/schematics/angular/migrations/update-10/update-dependencies.ts
- packages/schematics/angular/workspace/files/package.json.template
This version uses `@angular/core` and `@angular/compiler` as dependencies to prepare for the removal of view engine. It also updates `peerDependencies` for compatibility with v10.
> build: update codelyzer to v6

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/common-js-usage-warn-plugin.ts
- packages/angular_devkit/build_angular/src/browser/specs/common-js-warning_spec.ts
We have not yet deprecated the non-global locale data modules (e.g. `@angular/common/locales/fr`) so we should not be issuing warnings about developers using them.
We recently added warning suggesting that a "global" locale should be used instead, and the previous CommonJS/AMD warning about the format of these non-global modules are just confusing for the developer.
Reference: TOOL-1388
Closes: #18123
> fix(@angular-devkit/build-angular): remove non-global locale import warning

- packages/schematics/angular/ng-new/index.ts
When an invalid project name is given, throw an error before going through prompts.
I'm not sure if this validation can be removed but let me know if it should: https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/application/index.ts#L335
Closes #14994
> fix(@schematics/angular): validate project name before prompts

- packages/schematics/angular/migrations/update-10/solution-style-tsconfig.ts
- packages/schematics/angular/migrations/update-10/solution-style-tsconfig_spec.ts
> fix(@schematics/angular): provide more context on offending invalid JSON file

- scripts/validate-commits.ts
The commit linter expects a certain type and/or scope in the commit message,
but if the right type/scope is not provided it doesn't tell us what to do.
Instead of this:
```
The following commit has an unknown type. You can use wip: to avoid this.
```
It now outputs this:
```
The following commit has an unknown type. It must be one of [docs, refactor, style, test, feat, fix, build, revert, ci, release]. You can use wip: to avoid this.
```
> build: update validate-commits script to list valid types and scopes

- docs/process/release.md
- lib/packages.ts
- scripts/dist-tag.ts
This PR documents some of the learnings from the recent v10.0.0 release.
Our release doc does not sufficiently capture the process of a major release, and our tooling is insufficient to support the workflow.
There are two commits:
1. Update the release doc
- It now reminds the caretaker to double check the versions we are about to release.
- It adds instructions for major release.
2. Add a script to automatically retag CLI packages.
Since there isn't a test for the scripts, the best I could do is attach the command output.
```
$ yarn run -s admin dist-tag --version 10.0.0 --tag latest --verbose
npm dist-tag add '@angular/cli@10.0.0' 'latest'
npm dist-tag add '@angular/pwa@0.1000.0' 'latest'
npm dist-tag add '@angular-devkit/architect@0.1000.0' 'latest'
npm dist-tag add …
```
> Improve documentation for major release

- tests/legacy-cli/e2e/tests/schematics_cli/blank-test.ts
- tests/legacy-cli/e2e/tests/schematics_cli/schematic-test.ts
After a new tag is pushed, the schematic e2e test will attempt to
install the latest version, but it incorrectly installs the version
from the actual NPM registry instead of the local registry.
> test(@schematics/schematics): run npm install from local registry

- tests/legacy-cli/e2e/tests/basic/rebuild.ts
This helps validate and profile rebuilds when TypeScript can fully reuse a previous Program.
> test: add a non-structural file change to rebuild E2E

- packages/angular_devkit/build_angular/src/browser/specs/differential_loading_spec.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
This change ensures that classic (ES5) script's top-level function helpers do not get overwritten by other scripts top-level functions that happen to have the same name.  This is not an issue when using module script types because each module has its own scope.
Closes https://github.com/angular/angular/issues/36521
> fix(@angular-devkit/build-angular): wrap ES5 differential loading bundles

- packages/angular_devkit/build_angular/src/browser/specs/web-worker_spec.ts
CI performance variability can cause test flakes in rebuild tests due to the rebuilds taking longer than expected.  This change increases the 500ms debounce time for the web worker rebuild tests to 1000ms to mitigate these issues.
> test(@angular-devkit/build-angular): increase rebuild debounce times

- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/e2e/index.ts
- packages/schematics/angular/e2e/index_spec.ts
- packages/schematics/angular/universal/index_spec.ts
- packages/schematics/angular/web-worker/index_spec.ts
Since the tsconfig for e2e’s is named tsconfig.json there is no reason why it should be included in the solutions typescript configuration file.
Closes #18190
> fix(@schematics/angular): don't add e2e tsconfig reference in solution tsconfig

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/utility/json-file.ts
The schematics recently siwtcher to `jsonc-parser` as the JSOn parser, and that introduced a small regression in the tslint.json file where the rules order is not the same as previously.
See https://github.com/cexbrayat/angular-cli-diff/compare/10.0.2...10.1.0-next.0
This commit should fix the issue by providing the insertion index when merging the tslint files.
A test has also been added to avoid further regressions.
> fix(@schematics/angular): keep tslint rules ordered

- .circleci/config.yml
- packages/angular_devkit/build_angular/test/app-shell/app-shell_spec_large_disabled.ts
App-shell builder imports zone.js, which patches the global promises. In some cases this will causes flakiness in tests that run after this one.
With this change we move the app-shell tests to the flake jail and force them to be run at the very last.
Successful runs when disabling app-shell tests from test-large
https://circleci.com/workflow-run/4afb40f2-19ec-46ab-bb94-4153d448e6ad
> [8.3.x] test: move app-shell tests to flake jail

- .circleci/config.yml
- packages/angular_devkit/build_angular/test/app-shell/app-shell_spec_large_disabled.ts
App-shell builder imports zone.js, which patches the global promises. In some cases this will causes flakiness in tests that run after this one.
With this change we move the app-shell tests to the flake jail and force them to be run at the very last.
Successful runs when disabling app-shell tests from test-large
https://circleci.com/workflow-run/4afb40f2-19ec-46ab-bb94-4153d448e6ad
(cherry picked from commit 7cb470f32ea6fffdb8915a2948abb355101e927f)
> [9.1.x] test: move app-shell tests to flake jail

- packages/schematics/angular/module/files/__name@dasherize@if-flat__/__name@dasherize__-routing.module.ts.template
> fix(@schematics/angular): consecutive blank lines in routing.module.ts

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/common-js-usage-warn-plugin.ts
- packages/angular_devkit/build_angular/src/browser/specs/common-js-warning_spec.ts
Currently, when users use either absolute paths, or path mappings in JIT mode, we issue a warning for templateUrl and styleUrl. With this change we suppress those warning.
Closes: #18057
> fix(@angular-devkit/build-angular): suppress warning for CommonJS templateUrl and styleUrl

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
This change prevents import statements from being added to commonjs files when downleveling helpers are needed.  These imports would then cause webpack to assume that the file is an ES module and potentially break the commonjs file.
Fixes #18284
> fix(@angular-devkit/build-angular): avoid ES module assumption for vendor files

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
This change prevents webpack from removing the operator add imports from the rxjs package (for example, `import 'rxjs/add/operator/filter';`).  The entire rxjs package is currently marked as side effect free from within the rxjs `package.json` but the files in the add directory intentionally contain side effects.
> fix(@angular-devkit/build-angular): mark rxjs add imports as having side effects

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
fixes: https://github.com/angular/angular-cli/issues/18288
> fix(@schematics/angular): remove reference to tsconfig.spec.json in tsconfig.json when minimal=true

- packages/angular/cli/commands/update.json
`--next` arg description probably should be 
Use the **latest** version, including beta and RCs and not **largest**
> docs: fix typo in ng update --next description

- renovate.json
With this change we fix an issue where dev dependencies in the root package.json are not being updated.
In #18299 we that the `open` has been updated in 2 child `package.json`, however the root `package.json` has been left out of sync. https://github.com/angular/angular-cli/blob/65d0d952f193f8c8e419a62659ac0954cf57b6b8/package.json#L177
> ci: fix issue where renovate is not updating the root level package.json

- lib/registries.ts
- scripts/publish.ts
- tests/legacy-cli/e2e/setup/010-local-publish.ts
This is a patch PR for #18219. The `dist-tag` changes are not present here because that script does not exist and would not be used from this branch.
I also dropped the `doc:` commit since we don't typically look at docs on the non-master branch.
> Fixes publish script to require NPM tag, use Wombat registry, and correctly read check flags

- docs/process/release.md
- lib/registries.ts
- scripts/dist-tag.ts
- scripts/publish.ts
- tests/legacy-cli/e2e/setup/010-local-publish.ts
This fixes a few known bugs in `publish` and `dist-tag`, as well as a few new ones I found along the way.
Ideally this would have been at least two distinct PRs, but they touched each other when it relates to registries in a way that would have been a pain with multiple PRs.
> Fixes publish and dist-tag scripts.

- docs/process/release.md
Previously instructions for merging to patch instructed caretakers
to only merge commits which were "applicable" to patch.  However,
for PRs targeting master and patch, all commits from the PR should
land in both branches.
> docs: update release doc to remove outdate information on patch merges

- .circleci/config.yml
The previous images are now considered legacy.  The new images are smaller and faster to load.
For additional details: https://hub.docker.com/r/cimg/node
> ci: update configuration to use new CircleCI docker images

- docs/process/release.md
This changes from using lightweight tags to annotated tags. The later includes author, time, and message information that is lacking from the former. It is also included in Git's `--follow-tags` option. This should allow us to push tags alongside release commits more atomically and hopefully eliminate or at least reduce the possibility of a race condition arising from CI starting on the release commit before the associated tag is pushed. Such a state causes CI failures, because they take the latest version from the most recent `v*` tag.
I tested the flow on my local fork, but I can't test a real release unfortunately. I believe our existing infrastructure should "just work", but please let me know if that doesn't appear to be the case.
> ci: update release docs to use annotated tags for releases

- .circleci/config.yml
- scripts/validate.ts
This also speeds up the validation checks because the GitHub API request method is no longer used.
> ci: use CircleCI pipeline SHA variables for commit validation

- .circleci/config.yml
The setup job performs a large amount of disk IO including yarn install and ngcc.
> ci: use ramdisk for setup job

- packages/angular/cli/BUILD.bazel
- packages/angular/cli/commands/add-impl.ts
- packages/angular/pwa/BUILD.bazel
- packages/angular_devkit/architect/BUILD.bazel
- packages/angular_devkit/architect/node/BUILD.bazel
- packages/angular_devkit/architect/testing/BUILD.bazel
- packages/angular_devkit/benchmark/BUILD.bazel
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_ng_packagr/BUILD.bazel
- packages/angular_devkit/build_optimizer/BUILD.bazel
- packages/angular_devkit/build_webpack/BUILD.bazel
- packages/angular_devkit/core/BUILD.bazel
- packages/angular_devkit/core/src/terminal/caps.ts
- packages/angular_devkit/core/src/terminal/text.ts
- packages/angular_devkit/schematics/BUILD.bazel
- packages/angular_devkit/schematics_cli/BUILD.bazel
- packages/ngtools/webpack/BUILD.bazel
- packages/schematics/angular/BUILD.bazel
- packages/schematics/schematics/BUILD.bazel
- packages/schematics/schematics/blank/factory.ts
- packages/schematics/update/BUILD.bazel
- tools/BUILD.bazel
- tools/defaults.bzl
This commit makes a few minor changes to enable syncing the CLI repository
into google3.
1. mark pkg_tar and pkg_npm as external
2. remove dependencies (marked as comment) which are stale in google3
3. add code fence for TS files generated from JSON schema in BUILD files
since these files are compiled and added to the g3 codebase at sync time
4. Some minor typing changes
5. Remove duplicate licenses
6. mark dependencies which are not available in g3 as external
7. Immediately type the result of JSON.parse() as required by g3 linter.
Otherwise, the type defaults to `any`.
> build: minor fixes for google3 sync

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/any-component-style-budget-checker.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/bundle-budget.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/common-js-usage-warn-plugin.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/optimize-css-webpack-plugin.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/utils/webpack-diagnostics.ts
Additional preparation for Webpack 5 integration.
> refactor(@angular-devkit/build-angular): add webpack diagnostic helpers

- tests/legacy-cli/e2e/tests/misc/ask-analytics-install.ts
The npm install can take longer than the default 30 second timeout.
> test: increase wait time for ask analytics npm install E2E test

- packages/ngtools/webpack/src/entry_resolver.ts
- packages/ngtools/webpack/src/lazy_routes.ts
- packages/ngtools/webpack/src/refactor.ts
- packages/ngtools/webpack/src/transformers/find_resources.ts
- packages/ngtools/webpack/src/transformers/insert_import.ts
- packages/ngtools/webpack/src/transformers/replace_resources.ts
- packages/ngtools/webpack/src/utils.ts
- packages/ngtools/webpack/src/virtual_file_system_decorator.ts
By leveraging TypeScript's AST type guards, function parameter assumptions and casting can be removed.  Many of these cases caused errors when enabling TypeScript's strict option. This is preliminary work to support enabling full TypeScript strict mode within the project.
> refactor(@ngtools/angular): use type guard based narrowing with TS AST

- packages/schematics/angular/app-shell/index.ts
- packages/schematics/angular/migrations/update-6/index.ts
- packages/schematics/angular/service-worker/index.ts
- packages/schematics/angular/utility/change.ts
- packages/schematics/angular/utility/ng-ast-utils.ts
- packages/schematics/update/update/index.ts
Several code changes to support enabling TypeScript's strict compilation options.  See individual commits for details.
> Schematics code cleanup and refactoring to support strict compilation

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/worker.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/named-chunks-plugin.ts
Multiple Webpack plugins are only used when certain options are enabled.  By only requiring them when needed, startup time can be reduced by potentially eliminating large dependency hierarchies from being loaded that will then be unused.  This change currently only applies to plugins that are required.  This limitation is due to the current webpack configuration infrastructure being synchronous which prevents dynamic import usage.
> perf(@angular-devkit/build-angular): lazy load several optional webpack plugins

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
By leveraging the chunks function filter option, the test option can be reduced to only a regular expression instead of the more complex function.  This change also provides support for Webpack 5.
> refactor(@angular/devkit-build-angular): simplify Webpack split chunks configuration

- .circleci/config.yml
Bazel does not provide additional output while testing and this can cause unintended failures for long test times.
> ci: increase CircleCI no output timeout for bazel tests

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/karma/index.ts
This change reduces the number of variables needed as well as reduces type casting.
> refactor(@angular-devkit/build-angular): cleanup Webpack rule generation

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/dedupe-module-resolve-plugin.ts
- tests/legacy-cli/e2e/tests/misc/dedupe-duplicate-modules.ts
With this change we change the `DedupeModuleResolvePlugin` to act similar to `NormalModuleReplacementPlugin`
Closes: #18411
> fix(@angular-devkit/build-angular): don't use parent modules while deduping

- packages/schematics/angular/migrations/update-10/add-deprecation-rule-tslint.ts
- packages/schematics/angular/migrations/update-10/update-module-and-target-compiler-options.ts
- packages/schematics/angular/migrations/update-10/update-tslint.ts
- packages/schematics/angular/utility/dependencies.ts
- packages/schematics/angular/utility/json-file.ts
- packages/schematics/angular/web-worker/index.ts
This change provides more fine-grained warnings during the `update-module-and-target-compiler-options` migration for V10.0 in the event a TypeScript configuration file could not be updated.  This can help prevent update issues where, for instance, a tsconfig path was misspelled prior to the update.  The `JSONFile` utility class was also augmented to directly throw when creating to ensure that the `content` property is always initialized.
> Improve compiler options migration error reporting

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts
When `bundleDependencies` is turned off, webpack is configured to bundle all modules imported via relative path.
It works well for import paths like `'./some/file'` but fails for imports traversing the dir structure up, like `'../some/file'`.
In most cases it would still work well, because of the additional fallback (which checks whether node can resolve this module at all). However, in rare cases this fallback fails (see https://github.com/angular/universal/issues/1792)
Closes: #18493
> Fix relative paths with bundleDependencies=false

- packages/ngtools/webpack/src/angular_compiler_plugin.ts
`strictMetadataEmit` option which is not intended to be used  for applications. See: https://angular.io/guide/angular-compiler-options#strictmetadataemit
Closes #18424
> fix(@ngtools/webpack): issue warning when using `strictMetadataEmit`

- .circleci/config.yml
E2E jobs perform a large amount of disk IO including multiple package installs, builds, and git operations.
> ci: use ramdisk for E2E jobs

- packages/angular_devkit/architect/node/node-modules-architect-host.ts
This PR should improve debugging angular.json. In my case I could not figure out which project was missing. There was a small typo in one of the references to the project-name. Displaying the name of the missing project helps finding the error.
> fix(@angular-devkit/architect): add name of the non-existing project

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
- packages/angular_devkit/build_angular/src/utils/load-translations.ts
- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
- packages/angular_devkit/core/src/experimental/workspace/workspace-schema.json
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-merging.ts
This change implements the capability to specify multiple translation files per locale. The specified translation files for each locale will be merged prior to localization. The Angular configuration file has been updated to allow for both a single path string or an array of path strings when specifying the translations for each locale. If the same message identifier is present in multiple translation files, a warning will currently be issued and the last file with the duplicate message identifier will take precedence.
Closes #18276
> feat(@angular-devkit/build-angular): support multiple translation files per locale

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
The latest versions of mini-css-extract-plugin support HMR, see: https://github.com/webpack-contrib/mini-css-extract-plugin#hot-module-reloading-hmr for more details
> feat(@angular-devkit/build-angular): enable HMR for extracted CSS

- packages/schematics/angular/e2e/index.ts
- packages/schematics/angular/e2e/index_spec.ts
- packages/schematics/angular/workspace/files/package.json.template
Bugfix for the `ng new --createApplication=false` command.
Currently, it creates an `e2e` script in `package.json`. This change will only add the script when the application is created.
Closes #13412
> fix(@schematics/angular): don't create e2e script when createApplication is false

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/common-js-usage-warn-plugin.ts
- packages/angular_devkit/build_angular/src/browser/specs/common-js-warning_spec.ts
At the moment in AOT mode if a CommonJS dependency has transitive CommonJS dependency we are issue warning for both.
With this change we align the behaviour with JIT mode, where we issue warnings only for direct CommonJS dependencies or ES dependencies which have CommonJS dependencies.
Closes #18526
Kudos to @ms-dosx86 for investigating this 🥳
> fix(@angular-devkit/build-angular): don't warn on transitive CommonJS dependencies in AOT mode

- packages/angular_devkit/core/src/virtual-fs/host/sync.ts
While testing compiler performance with [ng9-aot-build-times](https://github.com/JoostK/ng9-aot-build-times) I noticed RxJS's `SafeSubscriber` to show up as hot function. I opened ReactiveX/rxjs#5646 to mitigate it, however this change cannot be accepted because it breaks a certain usage pattern. As an alternative, this PR avoids the performance penalty by switching over the anonymous observer object to use 3 separate callbacks instead, such that RxJS doesn't have to create calling context objects using slow `Object.create`.
On a new CLI app, local testing indicates that this saves about 120ms or 2%, whereas the [ng9-aot-build-times](https://github.com/JoostK/ng9-aot-build-times) repo shows approximately 2 second improvement, or ~6%.
> perf(@angular-devkit/core): avoid RxJS performance penalty in sync fs calls

- packages/angular/cli/commands/config-impl.ts
- packages/angular/cli/utilities/config.ts
This change removes one of the last usages of the experimental workspace API.
> refactor(@angular/cli): replace experimental workspace API with stable API

- packages/schematics/angular/migrations/update-10/remove-solution-style-tsconfig.ts
- packages/schematics/angular/migrations/update-10/remove-solution-style-tsconfig_spec.ts
> fix(@schematics/angular): change `extends`  from `tsconfig.base.json` to `tsconfig.json`

- etc/api/angular_devkit/core/src/_golden-api.d.ts
- packages/angular/cli/models/architect-command.ts
- packages/angular/cli/models/interface.ts
- packages/angular/cli/models/parser.ts
- packages/angular/cli/models/parser_spec.ts
- packages/angular/cli/models/schematic-command.ts
- packages/angular/cli/utilities/json-schema.ts
- packages/angular_devkit/architect_cli/bin/architect.ts
- packages/angular_devkit/core/src/json/schema/interface.ts
- packages/angular_devkit/core/src/json/schema/registry.ts
- packages/angular_devkit/core/src/json/schema/registry_spec.ts
- packages/angular_devkit/schematics_cli/bin/schematics.ts
With this change we show a warning when a deprecated option is also defined in the workspace configuration file (angular.json).
Closes: #14966
> Show warning on deprecated option usage

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/common-js-usage-warn-plugin.ts
- packages/ngtools/webpack/src/transformers/replace_resources.ts
- packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
With this change we update the replace_resources transformer for styles and templates to use ES6 module import syntax instead of the CommonJs require syntax.
> refactor(@ngtools/webpack): use ES modules imports instead of `require`

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/extract-i18n/ivy-extract-loader.ts
- packages/angular_devkit/build_angular/src/extract-i18n/schema.json
- tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts
- tests/legacy-cli/e2e/tests/i18n/legacy.ts
This change adds support for extracting i18n translation messages with an Ivy enabled application. This is accomplished by using the new extraction capabilities present in the `@angular/localize` package and will require version 10.1 or later of the package.  Since this change uses an new extraction method, it currently must be enabled during extraction by using the `--ivy` flag. The flag is a precaution to prevent unintentional breakage for existing applications but will become the default behavior for all Ivy enabled applications in a future release.
Closes #18275
> Support i18n message extraction with Ivy

- etc/api/angular_devkit/core/src/_golden-api.d.ts
- packages/angular_devkit/core/src/json/schema/registry.ts
- packages/angular_devkit/core/src/logger/logger.ts
- packages/angular_devkit/core/src/virtual-fs/host/buffer.ts
- packages/angular_devkit/core/src/virtual-fs/host/test.ts
This commit fixes typings errors after "strict: true" is enabled in
tsconfig.json for the json, logger, and virtual-fs subpackages in
`@angular-devkit/core`.
> fix(@angular-devkit/core): strict typings for json, logger, and virtual-fs

- etc/api/angular_devkit/architect/src/index.d.ts
- packages/angular_devkit/architect/src/api.ts
- packages/angular_devkit/architect/src/create-builder.ts
- packages/angular_devkit/architect/src/index_spec.ts
"Watch" type builders (builders with more than one result) can now be implemented as async generator functions. This allows such a builder to be more easily implemented in cases where an upstream API is async iterator/generator based or when async generators are the preferred method of implementation.
> feat(@angular-devkit/architect): support async generator based builders

- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
This change allows the underlying webpack configuration of the i18n extraction builder to be modified when programmatically using the builder.  This change also aligns the i18n extraction builder with the other Webpack-based builders in the package.
Programmatic usage of the `@angular-devkit/build-angular` builders is currently considered experimental.
Closes #16679
> feat(@angular-devkit/build-angular): allow transformation of i18n extraction builder configuration

- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-11/replace-ng-packagr-builder.ts
- packages/schematics/angular/migrations/update-11/replace-ng-packagr-builder_spec.ts
In 10.1, `@angular-devkit/build-ng-packagr` was deprecated in favor of `@angular-devkit/build-angular`. This migration updates the library build target to use the non deprecated builder.
> feat(@schematics/angular): add migration to replace deprecated library builder

- packages/angular_devkit/build_angular/src/extract-i18n/ivy-extract-loader.ts
- tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts
Not doing so results in a circular sourcemap warning when attempting extraction.
> fix(@angular-devkit/build-angular): ensure ivy extraction file names match sourcemaps

- .github/workflows/lock-closed.yml
Update to the latest lock-closed action to fix the link which is used.
> build: bump to lastest sha of angular/dev-infra's lock-closed action

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/utils.ts
- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/browser/specs/base-href_spec.ts
- packages/angular_devkit/build_angular/src/browser/specs/cross-origin_spec.ts
- packages/angular_devkit/build_angular/src/browser/specs/differential_loading_spec.ts
- packages/angular_devkit/build_angular/src/browser/specs/index_spec.ts
- packages/angular_devkit/build_angular/src/browser/specs/service-worker_spec.ts
- packages/angular_devkit/build_angular/src/browser/specs/works_spec.ts
- packages/angular_devkit/build_angular/src/dev-server/index_spec.ts
- packages/angular_devkit/build_angular/src/karma/schema.json
- packages/schematics/angular/app-shell/schema.json
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-11/update-angular-config.ts
- packages/schematics/angular/migrations/update-11/update-angular-config_spec.ts
- packages/schematics/angular/universal/schema.json
- tests/legacy-cli/e2e/tests/misc/es5-polyfills.ts
**feat(@schematics/angular): add migration to replace deprecated options**
**refactor(@angular-devkit/build-angular): remove deprecated `scripts[].lazy` and `styles[].lazy`**
- Deprecated `scripts[].lazy` has been renamed with `scripts[].inject`
- Deprecated `styles[].lazy` has been renamed with `styles[].inject`
Note: this change only effects direct `@angular-devkit/build-angular` users and not application developers. Users will be migrated automatically off these options.
**refactor(@schematics/angular): remove deprecated `tsconfigFileName` option from universal schematic**
**refactor(@angular-devkit/build-angular): deprecate `extractCss` browser builder option**
Browser builder `extractCss` option default value has been changed from `false` to `true`. …
> ExtractCss and Inject migrations

- packages/schematics/angular/workspace/files/package.json.template
Re-arrange the node types npm package so that `devDependencies` are sorted in  alphabetical order
> refactor(@schematics/angular): change the order of node types in package.json template

- .circleci/config.yml
- packages/angular_devkit/build_angular/src/extract-i18n/ivy-extract-loader.ts
POSIX path handling was errantly being used to resolve paths which does not handle Windows drive letters.
> fix(@angular-devkit/build-angular): correct Windows paths in ivy i18n extract

- packages/angular_devkit/core/src/workspace/json/test/cases/ObjectRemove.json
- packages/angular_devkit/core/src/workspace/json/test/cases/ObjectRemoveMultiple.json
- packages/angular_devkit/core/src/workspace/json/utilities.ts
- packages/angular_devkit/core/src/workspace/json/writer_spec.ts
Removal changes were previously being improperly recorded with the wrong parent.  A property can now be directly removed by setting the value to undefined or by using the delete operator.
> fix(@angular-devkit/core): allow property remove with workspace API

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/utils.ts
- packages/angular_devkit/build_angular/src/browser/specs/differential_loading_spec.ts
- packages/angular_devkit/build_angular/src/browser/specs/vendor-source-map_spec.ts
- tests/legacy-cli/e2e/tests/build/sourcemap.ts
This reduced the build time of an `ng new` application from `5920ms` to `4616ms`
Closes #18060
> fix(@angular-devkit/build-angular): don't generate `vendor.js.map` when vendor sourcemaps is disabled

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
The type of the first parameter of the internal unwrapTemplateLiteral function should be a `NodePath<types.TaggedTemplateExpression>` not a `NodePath<types.TemplateLiteral>`.
> fix(@angular-devkit/build-angular): correct i18n function parameter type

- packages/angular/cli/lib/cli/index.ts
- packages/angular/cli/lib/init.ts
This also does some minor code cleanup to the version mismatch check logic which contained the node modules directory reference.
> refactor(@angular/cli): remove node module directory assumption during initialization

- package.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/utils.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts
- tests/legacy-cli/e2e/tests/build/relative-sourcemap.ts
- tests/legacy-cli/e2e/tests/misc/karma-error-paths.ts
- yarn.lock
**fix(@angular-devkit/buid-angular): generate sourcemaps with relative paths in monorepo**
With this change we fix the issue that when having a monorepo style workspace, sourcemaps sources references absolute paths.
Closes #17046
**fix(@angular-devkit/build-angular): improve debugging experience**
With this change we improve the debugging experience with 2 things.
1. Cleaner Karma stack traces in the terminal
Before
```
Chrome 84.0.4147.105 (Mac OS 10.15.5) AppComponent should have as title 'foo' FAILED
Error: Expected 'foo' to equal 'fox'.
at <Jasmine>
at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/projects/foo/src/app/app.component.spec.ts:22:23)
at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js: …
```
> Generate sourcemaps with relative paths 

- integration/angular_cli/karma.conf.js
- integration/angular_cli/package.json
- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts
- packages/angular_devkit/build_angular/src/karma/code-coverage_spec.ts
- packages/angular_devkit/build_angular/src/karma/index.ts
- packages/angular_devkit/build_angular/test/hello-world-app/karma.conf.js
- packages/angular_devkit/build_ng_packagr/test/ng-packaged/projects/lib/karma.conf.js
- packages/schematics/angular/application/files/karma.conf.js.template
- packages/schematics/angular/library/files/karma.conf.js.template
- packages/schematics/angular/workspace/files/package.json.template
- yarn.lock
This commit switches coverage tooling from karma-coverage-istanbul-reporter
to karma-coverage since it's better supported.
Fixes https://github.com/angular/angular-cli/issues/17757
> feat(@angular-devkit/build-angular): Switch to karma-coverage

- packages/schematics/angular/workspace/files/angular.json.template
Apply consistent formatting in closing brackets at the end of the `angular.json` file.
Currently, if you create a new Angular CLI project, the end of the `angular.json` looks like this:
This PR adds a new line between the two brackets so that it can be easier to understand where each section of the JSON file ends.
> refactor(@schematics/angular): Brackets formatting in angular.json

- README.md
- scripts/templates/readme.ejs
Updated the information around testing as discussed in #18710 
Closes: #18710
> docs: update testing chapter with general test commands

- packages/ngtools/webpack/src/transformers/replace_resources.ts
- packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
When using CommonJs as module format TypeScript will generate unreferenced `require` when using `ts.createImportDeclaration`.
```js
const external_component_html_1 = require("!raw-loader!./external.component.html");
const core_1 = require("@angular/core");
let ExampleComponent = class ExampleComponent {
};
ExampleComponent = __decorate([
core_1.Component({
selector: 'example-compoent',
template: __NG_CLI_RESOURCE__0,
})
], ExampleComponent);
```
More context: https://github.com/microsoft/TypeScript/issues/18369#issuecomment-329852888
Closes #18718
> fix(@ngtools/webpack): emit `require` in replace resources when using CommonJS as module

- packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
- packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
> fix(@angular-devkit/build-optimizer): remove decorators calls when tslib helpers are inlined

- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
Webpack 5+ has no facility to disable this warning. `System.import` is used in `@angular/core` for deprecated string-form lazy routes.
> fix(@angular-devkit/build-angular): filter unactionable System.import webpack warning

- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/server/index.ts
With this change we align all builders to have the same output structure.
> refactor(@angular-devkit/build-angular): use common logging function for webpack stats

- tests/legacy-cli/e2e/tests/build/deploy-url.ts
The public path will not be stored in the Webpack runtime chunk in Webpack 5 unless the public path is used by the application.  A lazy import is added to the test to ensure that the public path is used.
> test: support Webpack 5 in deployUrl E2E test

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/suppress-entry-chunks-webpack-plugin.ts
In addition, this adds Webpack 5 support, cleans up the code, and ensures lint checks pass.
> refactor(@angular-devkit/build-angular): use Webpack ChunkGraph API in SuppressExtractedTextChunksWebpackPlugin

- packages/schematics/angular/guard/files/__name@dasherize__.guard.ts.template
using the guard schematic with the `--implements CanLoad` option, the signature of the canLoad generated method is missing `UrlTree`.
```
export class TestGuard implements CanLoad {
canLoad(
route: Route,
segments: UrlSegment[]): Observable<boolean> | Promise<boolean> | boolean {
return true;
}
}
```
Issue Number: #18751
The schematic file has been updated to provide the following result : 
```
export class TestGuard implements CanLoad {
canLoad(
route: Route,
segments: UrlSegment[]): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {
return true;
}
```
> fix(@schematics/angular): canLoad guard signature

- packages/schematics/angular/application/files/karma.conf.js.template
- packages/schematics/angular/library/files/karma.conf.js.template
In many users will not use lcov reports, also  this reporter generates an HTML report, which we are already generating using the html reporter.\
> refactor(@schematics/angular): remove lcov from coverage reporters

- packages/angular/cli/commands/version-impl.ts
This change removes all direct usage of the `node_modules` directory from the version command.  This provides improved support for yarn PnP as well as prevents a crash when a workspace does not have a `node_modules` directory.
Fixes #10474
> fix(@angular/cli): remove version command node module assumptions

- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/models/schematic-command.ts
- packages/angular_devkit/schematics_cli/bin/schematics.ts
When a large number of migration are executed, it's hard to differentiate between the title and description.
Before
After
> fix(@angular/cli): improve logs in ng update

- tests/legacy-cli/e2e/tests/build/platform-server.ts
The platform server E2E test checks for a Webpack specific output to determine if the server module is present.  This output is different for Webpack 5.  This change tries to match either the Webpack 4 or Webpack 5 output.
> test: support Webpack 5 in platform server E2E test

- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-11/add-declaration-map-compiler-option.ts
- packages/schematics/angular/migrations/update-11/add-declaration-map-compiler-option_spec.ts
Since version 10.1 we added declaration maps for local library builds, to improve the DX. With this change we add it to existing project.
See: #17920
> feat(@schematics/angular): add migration to add declaration maps to libraries

- etc/api/angular_devkit/schematics/src/_golden-api.d.ts
- etc/api/angular_devkit/schematics/tools/index.d.ts
- packages/angular_devkit/schematics/src/engine/engine.ts
- packages/angular_devkit/schematics/src/engine/interface.ts
- packages/angular_devkit/schematics/src/rules/schematic.ts
- packages/angular_devkit/schematics/tools/fallback-engine-host.ts
- packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
- packages/angular_devkit/schematics/tools/node-module-engine-host.ts
- packages/angular_devkit/schematics/tools/node-modules-test-engine-host.ts
- tests/legacy-cli/e2e/assets/nested-schematic-dependency/collection.json
- tests/legacy-cli/e2e/assets/nested-schematic-dependency/index.js
- tests/legacy-cli/e2e/assets/nested-schematic-dependency/package.json
- tests/legacy-cli/e2e/assets/nested-schematic-main/collection.json
- tests/legacy-cli/e2e/assets/nested-schematic-main/index.js
- tests/legacy-cli/e2e/assets/nested-schematic-main/package.json
- tests/legacy-cli/e2e/tests/misc/nested-schematic-packages.ts
- tests/legacy-cli/e2e/utils/assets.ts
This change first attempts to resolve a schematic referenced via the external schematic rule from the requesting schematic collection.  This allows schematic packages that are direct dependencies of another schematic package to be used with the external schematic rule without manual package resolution code within the schematic.
> fix(@angular-devkit/schematics): resolve external schematics from requesting collection

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- packages/angular_devkit/build_angular/src/utils/webpack-diagnostics.ts
- packages/angular_devkit/build_angular/src/utils/webpack-version.ts
- packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/configs/server.ts
- packages/ngtools/webpack/src/virtual_file_system_decorator.ts
- tests/legacy-cli/e2e/tests/misc/webpack-5.ts
This change enables experimental support for Webpack v5 in the Angular CLI. At this point, we don't recommend using Webpack v5 for production usage.
By default, the Angular CLI uses Webpack v4. To enable Webpack v5, use `yarn` as your package manager and add the following top-level property to `package.json`:
```
"resolutions": {
"webpack": "^5.0.0-beta.30"
}
```
Please note that the support is experimental, and webpack v5 is still in beta. Some Angular CLI features and options are partially supported, and new prereleases of webpack v5 may contain breaking changes. You may temporarily see Webpack deprecation warnings, which we'll fix over time.
> Experimental Webpack 5 Support

- packages/angular/cli/plugins/karma.js
For Angular 6, an error inducing file was introduced in the 1.x location of the karma plugin for the Angular CLI.  This was useful during the 1.x -> 6 transition to assist users to migrate with a helpful error message.  Now that 1.x and 6 are no longer supported, this can be removed.
> refactor(@angular/cli): remove outdated 1.x karma plugin error placeholder

- packages/angular/cli/lib/config/schema.json
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
If I understand the comments of @alan-agius4 on #17579 correct this PR will fix the IDE validation error that it is providing today.
I've replaced the regex with the correct one, just to make sure we are not forgetting when closing the ticket there is a second comment by @alan-agius4:
>When it comes to project directories, I am inclined towards always dasherizing the project folder name to align with other schematics where the folder name is always dasherized, that being said It's not a biggy, as long as the schema validation is fixed.
Should we make a separate issue for this or are we leaving this as is?
Let me know if I need to make changes or add additional information.
Closes #17579
> Replace regex with correct project name valdiation

- packages/angular/cli/models/schematic-command.ts
This ensures that the correct build-in version of `@schematics/angular` is resolved.
Closes #18840
> fix(@angular/cli): favor dirname when resolving @schematics/angular

- docs/design/third-party-libraries.md
Replace the usage of blacklist with a description of the prevention/disclusion
methods which are beging described.
> docs: remove usage of blacklist from third-party-libraries documentation

- packages/schematics/angular/migrations/update-10/remove-solution-style-tsconfig.ts
- packages/schematics/angular/migrations/update-10/remove-solution-style-tsconfig_spec.ts
`remove-solution-style-tsconfig` migration fails when upgrading from version 10.0.* to 10.1.* with the following error:
```bash
[error] Error: Could not read 'tsconfig.json'
```
There is no issue regarding this but you can see the following comments:
https://github.com/angular/angular-cli/issues/18744#issuecomment-689790320
https://github.com/angular/angular-cli/issues/18040#issuecomment-689833338
Btw, the files are not formatted correctly by the `prettier` configuration but I decided to leave these changes out of the scope of this PR.
> fix(@schematics/angular): remove solution style throw an error

- docs/process/release.md
Since we no longer use `beta` tags, this PR updates the guide to use `next`.
> docs: change beta to next tag in release process

- packages/angular_devkit/build_angular/src/browser/specs/unused-files-warning_spec.ts
The test was previously run only in Ivy mode but with VE specific test case files.  The test now also enables strict templates to ensure template type checking files are properly excluded.
> test(@angular-devkit/build-angular): test Ivy specific files in unused file tests

- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- tests/legacy-cli/e2e/tests/i18n/extract-ivy-libraries.ts
**feat(@angular-devkit/build-angular): extract i18n messages from libraries**
Closes #18871
> Extract messages libs

- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/webpack/hmr.js
With this change we configure HMR internally and therefore users which want to use basic HMR functionality will not longer be required to change their application code.
This is important because previously a lot of users missed out on HMR or reported a broken behaviour. This also gives novice/new users a better chance to appreciate HMR and Angular because of the zero effort required to use HMR.
Closes #17324
> feat(@angular-devkit/build-angular): auto configure hot module replacement (HMR)

- packages/angular_devkit/build_angular/src/browser/specs/styles_spec.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
The browser builder's `styles` and `scripts` options now support using a package name in the path when specifying a style or script.  This removes the need to use a relative path to the node modules directory in these options.  This provides support for Yarn PnP as well as reducing the complexity of the options especially for monorepo setups.  Relatively located files will take precedence over packages if they exist.  This precedence provides backwards compatibility with existing configurations.
Before :
`"styles": ["../node_modules/bootstrap/dist/css/bootstrap.css"]`
After:
`"styles": ["bootstrap/dist/css/bootstrap.css"]`
> feat(@angular-devkit/build-angular): support package references in styles & scripts options

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/browser/specs/browser-support_spec.ts
- packages/schematics/angular/application/files/.browserslistrc.template
- packages/schematics/angular/application/index_spec.ts
- tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js
Deprecated support for IE 9-10 has been removed in Angular 11.
Only IE 9-10 support has been removed. IE 11 is officially supported in Angular 11.
Additional information can be found here: https://v10.angular.io/guide/deprecations#ie-9-10-and-mobile
> fix(@schematics/angular): remove IE9/10 from browserslist for new projects

- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/karma/index.ts
- packages/angular_devkit/build_angular/src/tslint/index.ts
- packages/angular_devkit/build_angular/src/utils/load-translations.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
karma is currently used by the karma builder within this package but is not represented in the dependencies.  The can lead to accidental version mismatches as well as package manager hoisting problems due to the package manager not knowing the full dependency set of the package.
> fix(@angular-devkit/build-angular): add karma as an optional peer dependency

- packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/common-js-usage-warn-plugin.ts
fixes 24 occurances of `Error: module property was removed from Dependency (use compilation.moduleGraph.getModule(dependency) instead)`
in:
```bash
yarn bazel test //packages/angular_devkit/build_angular:build_angular_browser_test
yarn bazel test //packages/angular_devkit/build_angular:build_angular_browser_ve_test
```
> fix(@angular-devkit/build-angular): webpack5 deprecation of module property in Dependency

- packages/angular_devkit/build_angular/src/webpack/configs/stats.ts
maxModules were deprecated and renamed to modulesSpace
> fix(@angular-devkit/build-angular): maxModules were deprecated and renamed to modulesSpace

- packages/angular_devkit/build_angular/src/extract-i18n/ivy-extract-loader.ts
This will be needed when the changes in angular/angular#39006 is merged.
> fix(@angular-devkit/build-angular): implement `relative` method in extractor FS

- packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts
Closes #18895
fixes:
- 229 deprecation warnings in tests and in ng prod build
`[DEP_WEBPACK_COMPILATION_AFTER_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: afterOptimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)`
- 90 test errors like `Error: .../app.component.less exceeded maximum budget. Budget 1 bytes was not met by 82 bytes with a total of 83 bytes. ' to match 'ERROR.+app.component.less'.`
> fix(@angular-devkit/build-angular): fixed afterOptimizeChunkAssets is deprecated in webpack 5

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/dedupe-module-resolve-plugin.ts
- tests/legacy-cli/e2e/tests/build/ts-paths.ts
Closes #18631
(cherry picked from commit 09cfb29c0747f82db105acf738246536ce3dc3c3)
Patch version of https://github.com/angular/angular-cli/pull/18922
> [PATCH] fix(@angular-devkit/build-angular): handle undefined descriptionFileData

- packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts
should fix 18 webpack 5 deprecation warnings `[DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_PUSH] DeprecationWarning: chunk.files was changed from Array to Set (using Array method 'push' is deprecated)`
> fix(@angular-devkit/build-angular): fix webpack 5 deprecation warning for chunk.push

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/remove-hash-plugin.ts
should fix 20 warnings in unit tests `[DEP_WEBPACK_MAIN_TEMPLATE_ASSET_PATH] DeprecationWarning: MainTemplate.hooks.assetPath is deprecated (use Compilation.hooks.assetPath instead)`
> fix(@angular-devkit/build-angular): fixes deprecation warning for MianTemplate.hooks.assetPath in webpack 5

- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/commands/update.json
- packages/schematics/update/update/index.ts
- tests/legacy-cli/e2e/tests/misc/update-git-clean-subdirectory.ts
- tests/legacy-cli/e2e/tests/misc/update-git-clean.ts
`--all` functionality has been removed from `ng update` as updating multiple packages at once is not recommended. To update the depencencies in your workspace 'package.json' use the update command of your package manager.
Closes #15278
Closes #13095
Closes #12261
Closes #12243
Closes #18813
> fix(@angular/cli): no-op ng update --all

- packages/angular/cli/models/schematic-command.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/browser/specs/browser-support_spec.ts
- packages/angular_devkit/build_angular/src/browser/specs/bundle-budgets_spec.ts
- packages/angular_devkit/build_angular/src/browser/specs/common-js-warning_spec.ts
- packages/angular_devkit/build_angular/src/browser/specs/web-worker_spec.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/server/index.ts
- packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
- packages/ngtools/webpack/src/type_checker.ts
- tests/legacy-cli/e2e/tests/build/bundle-budgets.ts
- tests/legacy-cli/e2e/tests/build/rebuild-deps-type-check.ts
- tests/legacy-cli/e2e/tests/misc/circular-dependency.ts
Sometimes the WARNING IN/ERROR IN can lead of ambiguous messages
- Use `Warning` instead of `WARNING IN`
-  Use `Error` instead of `Error In`
> refactor(@angular-devkit/build-angular): change errors and warnings messages

- packages/angular_devkit/build_angular/src/extract-i18n/empty-export-default.js
- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
When building an application for i18n extraction we are currently redundantly process components stylesheets. With this change we replace the components stylesheets with an empty string which helps reduce the i18n build time.
> fix(@angular-devkit/build-angular): don't process stylesheets in extraction builder

- packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts
- packages/angular_devkit/build_webpack/src/webpack/index.ts
- tests/legacy-cli/e2e/tests/misc/webpack-5.ts
With Webpack 5, passing the watch configuration option into the `webpack` factory function will cause the Webpack compiler to assume it should immediately start watching which requires a callback to be passed as well.  Since the execution of the compiler is handled later in the process, a callback at the compiler creation stage is undesirable and could result in potentially breaking changes to accomplish.
> fix(@angular-devkit/build-webpack): avoid deprecation warning with Webpack 5 watch mode

- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/application/other-files/package.json.template
- packages/schematics/angular/application/schema.json
- packages/schematics/angular/ng-new/schema.json
- packages/schematics/angular/workspace/files/tslint.json.template
- packages/schematics/angular/workspace/index_spec.ts
Following feedback from the community, which showed a high number of users found it hard to work with the `no-any` lint rule and also the `sideEffects` package.json file. With DevRel we decided to remove both features when generating a strict workspace and/or application.
> feat(@schematics/angular): don't generate  special `package.json` and `no-any` when using `--strict`

- tests/legacy-cli/e2e/tests/update/update-7.0.ts
This is currently failing with FW 11.0.0-next.4 due to a migration using double quotes instead of single quotes. This is
for a beta release and the impact is relatively minor, so we've decided to just disable the test for now.
> ci: disable lint check in the update test

- packages/schematics/angular/application/schema.json
Display the url of the Stylus format in the list of stylesheet format selection with SSL
> refactor(@schematics/angular): display Stylus documentation url with HTTPS

- etc/api/angular_devkit/schematics/tools/index.d.ts
- packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
- packages/angular_devkit/schematics_cli/bin/schematics.ts
See individual commits for details.
> Schematics CLI Refactoring

- packages/angular/cli/commands/add-impl.ts
- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/commands/version-impl.ts
- packages/angular/cli/lib/cli/index.ts
- packages/angular/cli/models/architect-command.ts
- packages/angular/cli/models/command-runner.ts
- packages/angular/cli/models/command.ts
- packages/angular/cli/models/interface.ts
- packages/angular/cli/models/schematic-command.ts
- packages/angular/cli/utilities/config.ts
- packages/angular/cli/utilities/project.ts
Previously, the workspace configuration file was found and loaded by individual commands potentially multiple times.  This change moves the initial workspace location discovery and loading of the workspace to the CLI startup.  It also provides the workspace to each command so that the commands can reuse the already loaded and parsed workspace configuration.
This change will serve as a base to further refactor and consolidate workspace option usage.
> refactor(@angular/cli): discover/load workspace on startup

- packages/schematics/angular/application/files/src/polyfills.ts.template
IE 10 is no longer supported therefore we removed it from the classlist polyfill comment.
> fix(@schematics/angular) remove reference to IE10 in comment

- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/models/schematic-command.ts
This change reduces the amount of schematic runtime setup code by leveraging the new options for the root path and schema validation in the NodeWorkflow class.
> refactor(@angular/cli): use new NodeWorkflow schematic features

- packages/angular/cli/commands/update-impl.ts
When using the `-C` option of `update`, the commit message of the migration is missing a blank line between the subject and body. 
For example,
Previously was missing blank line after the commit subject:
```
@angular/cli migration - rename-browserslist-config
Update Browserslist configuration file name to '.browserslistrc' from deprecated 'browserslist'.
```
Now fixed:
```
@angular/cli migration - rename-browserslist-config
Update Browserslist configuration file name to '.browserslistrc' from deprecated 'browserslist'.
```
> fix(@angular/cli): add blank line in migration commit message

- packages/schematics/angular/e2e/files/protractor.conf.js.template
- packages/schematics/angular/e2e/files/src/app.e2e-spec.ts.template
- packages/schematics/angular/e2e/files/src/app.po.ts.template
- packages/schematics/angular/e2e/files/tsconfig.json.template
- packages/schematics/angular/workspace/files/package.json.template
- tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js
- tests/legacy-cli/e2e/tests/build/lazy-load-syntax.ts
- tests/legacy-cli/e2e/tests/build/rollup.ts
- tests/legacy-cli/e2e/tests/generate/library/library-consumption.ts
- tests/legacy-cli/e2e/tests/i18n/legacy.ts
- tests/legacy-cli/e2e/tests/misc/browsers.ts
- tests/legacy-cli/e2e/tests/misc/third-party-decorators.ts
This change adjusts the E2E schematic to generate a protractor configuration with the selenium promise manager disabled.  It also adjusts the generated test files to use native promises and async/await to control test execution.
> feat(@schematics/angular): generate E2E tests with native promise support

- packages/schematics/angular/utility/ast-utils.ts
- packages/schematics/angular/utility/ast-utils_spec.ts
`findNodes` is not recursive when `recursive` flag is set.
Pass down `recursive` flag when  calling `findNodes` recursively.
> fix(@schematics/angular): fix recursion in `findNodes` ast utils

- tests/legacy-cli/e2e/tests/misc/webpack-5.ts
Webpack 5 causes a runtime error when used with tslib 2.0.2, disable for the time being until we investigate this further.
> test(@angular/cli): disable Webpack 5 e2e tests

- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/dev-server/schema.json
**refactor(@angular-devkit/build-angular): deprecate a number of dev-server options**
With this change we deprecate a number of dev-server builder options which proxied to the browser builder. This pattern also wrongly assumes that 3rd party browser builders also support all these options.
Configure the below deprecated options directly in the browser builder target options instead.
- aot
- sourceMap
- deployurl
- baseHref
- vendorChunk
- commonChunk
- optimization
- progress
**refactor(@angular-devkit/build-angular): deprecate hmrWarning and servePathDefaultWarning options**
With this change we deprecate servePathDefaultWarning and hmrWarning which no longer has an effect.
Using any unsupported deploy-url or base-href serve path value will result in a hard warning.
> Deprecate several dev-server builder options

- packages/angular/cli/commands/build-impl.ts
- packages/angular/cli/commands/deploy-impl.ts
- packages/angular/cli/commands/generate-impl.ts
- packages/angular/cli/commands/serve-impl.ts
- packages/angular/cli/models/architect-command.ts
- packages/angular/cli/models/command.ts
- packages/angular/cli/models/schematic-command.ts
With this change we fix two analytics collection bugs:
- We now collect the usage of options defined in the workspace config (angular.json).
- We now also collect values set via schematic prompts.
Closes: #17900
> fix(@angular/cli): collect analytics option usage from workspace config and prompts

- .bazelrc
Some initial preparation for building the packages with bazel. Currently unused.
> build: use @angular/dev-infra-private for bazel stamping

- etc/api/angular_devkit/core/src/_golden-api.d.ts
- packages/angular_devkit/core/src/utils/lang.ts
Deprecated `isObservable` function removed.  As an alternative, use `isObservable` from the `rxjs` package.
NOTE: This change does not affect application development.
> fix(@angular-devkit/core): remove deprecated isObservable function

- docs/design/analytics.md
- etc/api/angular_devkit/core/src/_golden-api.d.ts
- packages/angular_devkit/core/src/analytics/index.ts
- packages/schematics/angular/application/schema.json
- packages/schematics/angular/ng-new/schema.json
- packages/schematics/angular/workspace/schema.json
> feat(@schematics/angular): add prompt and analytics to strict mode

- packages/angular_devkit/build_angular/src/webpack/plugins/common-js-usage-warn-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/optimize-css-webpack-plugin.ts
Additional support for building with Webpack 5.
> refactor(@angular-devkit/build-angular): additional webpack 5 type improvements

- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts
Now that 11.0 is the minimum supported version, the 10.1 support checks for the `@angular/localize` package can be removed.
> refactor(@angular-devkit/build-angular): remove unneeded 10.1 localize checks

- .github/dependabot.yml
The configuration is currently only used for automated security updates.
For information about the `open-pull-requests-limit` option: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#open-pull-requests-limit
> build: add required fields to dependabot configuration

- packages/angular_devkit/build_ng_packagr/README.md
Add deprecation message so that it shows up on https://www.npmjs.com/package/@angular-devkit/build-ng-packagr
> docs(@angular-devkit/build-ng-packagr): Add deprecation message

- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
- @angular/core package no longer contain ESM5 and FESM5 entrypoints
- ngfactory/ngstyle file extension is always .js
> refactor(@angular-devkit/build-optimizer): remove old checks

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
IE9 and 10 are no longer supported.
> fix(@angular-devkit/build-angular): use IE11 as oldest browser when downlevelling

- packages/angular_devkit/build_angular/src/browser/specs/rollup_spec.ts
- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
- packages/angular_devkit/build_optimizer/src/index.ts
- packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
- packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
This change lowers the potential for code to be errantly removed by the prefix functions and scrub file transformers.  Only known safe modules are used with the prefix functions transformer as it can easily remove required module level side effects (as opposed to global level side effects) such as `__decorate` calls.
The scrub file transformer will now keep parameter metadata if non-Angular decorators are present. This allows libraries that use that information to continue to function.
Closes #14033
Closes #18621
> fix(@angular-devkit/build-optimizer): increase safety of code removal

- tests/legacy-cli/e2e/tests/misc/webpack-5.ts
Reverts angular/angular-cli#18987
Tslib 2.0.3 works-around this issue.
Full discussion here: https://github.com/webpack/webpack/issues/11613
> Revert "test(@angular/cli): disable Webpack 5 e2e tests"

- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/dev-server/schema.json
- packages/angular_devkit/build_angular/src/dev-server/works_spec.ts
Make it possible to configure dev-server to send custom HTTP headers on
every client request. These headers can be specified as a key-value map
under the new "headers" property of the dev-server builder in
angular.json. These headers are then passed on to the webpack devserver.
An example use case for this is to enable various security features,
such as CSP and Trusted Types, both in local application development and
in integration tests, by setting appropriate HTTP headers.
This is part of an effort to add support for Trusted Types in Angular.
The ability to enforce Trusted Types during development and integration
tests is essential, as this can help detect Trusted Types violations
that might otherwise break applications when they're pushed to
production where such security features may …
> feat(@angular-devkit/build-angular): support custom headers in dev-server

- packages/angular/cli/utilities/package-tree.ts
- packages/schematics/update/update/index.ts
Unlike `require.resolve`, the `resolve` package `paths` is only used as a fallback when the package is not resolved from the `basedir`,
Previously this resulted in the temporary version of CLI being resolved here which resulted in `ng update` incorrectly stating that there are no updates.
> fix(@angular/cli): resolve packages package.json from workspace directory

- tsconfig.json
`packages/angular_devkit/build_angular/src/typings.d.ts` is only needed for a Bazel build to workaround https://github.com/bazelbuild/rules_nodejs/issues/1033
Including this typings in a non Bazel build creates broken triple slash references https://unpkg.com/browse/@angular-devkit/build-angular@0.1100.0-next.6/src/utils/process-bundle.d.ts
Closes #19072
> build: only include `packages/angular_devkit/build_angular/src/typings.d.ts` during bazel builds

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
- packages/ngtools/webpack/src/angular_compiler_plugin.ts
- packages/ngtools/webpack/src/virtual_file_system_decorator.ts
- packages/ngtools/webpack/src/webpack-version.ts
- tests/legacy-cli/e2e/tests/basic/rebuild.ts
- tests/legacy-cli/e2e/tests/misc/webpack-5.ts
Several additional fixes and improvements for Webpack 5 support.
> Additional Webpack 5 fixes

- package.json
- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/browser/specs/font-optimization_spec.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/utils/action-cache.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts_spec.ts
- packages/angular_devkit/build_angular/src/utils/index-file/transforms.ts
- packages/angular_devkit/build_angular/src/utils/index-file/write-index-html.ts
- packages/angular_devkit/build_angular/src/utils/normalize-optimization.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/index-html-webpack-plugin.ts
- yarn.lock
With this change we inline Google fonts and icons in the index html file when optimization is enabled.
**Before**
```html
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```
**After**
```html
<style>
@font-face {
font-family: 'Material Icons';
font-style: normal;
font-weight: 400;
src: url(https://fonts.gstatic.com/s/materialicons/v55/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2) format('woff2');
}
.material-icons {
font-family: 'Material Icons';
font-weight: normal;
font-style: normal;
font-size: 24px;
line-height: 1;
letter-spacing: normal;
text-transform: none;
display: inline-block;
white-space: nowrap;
word-wrap: normal;
direction: ltr;
}
</style>
```
To opt-out of this feature set `optimization.fonts: false` or `optimization.fonts.inline: false` in …
> feat(@angular-devkit/build-angular): enable font inlining optimizations

- packages/schematics/angular/collection.json
- packages/schematics/angular/resolver/files/__name@dasherize__.resolver.spec.ts.template
- packages/schematics/angular/resolver/files/__name@dasherize__.resolver.ts.template
- packages/schematics/angular/resolver/index.ts
- packages/schematics/angular/resolver/index_spec.ts
- packages/schematics/angular/resolver/schema.json
This will add the `resolvers` as an option to generate. 
You can use it by `ng g r <name> ` or `ng generate resolver <name> `  
closes: #17569
> feat(@schematics/angular): add generation for resolvers

- tests/legacy-cli/e2e/tests/update/update-7.0.ts
Re-enabling the lint check to merge once `11.0.0-next.4` is released.
I'll leave this PR in the blocked state until the version is released and https://github.com/angular/angular/pull/39070 is merged. Once those have both happened, it should be safe to merge this as well.
> Revert "ci: disable lint check in the update test"

- packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
- packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
- packages/ngtools/webpack/src/transformers/remove-ivy-jit-support-calls.ts
- packages/ngtools/webpack/src/transformers/remove-ivy-jit-support-calls_spec.ts
This adds support for an alternate emit form of `ɵsetClassMetadata` that is guarded by `ngJitMode` instead of a pure annotation.
> fix(@ngtools/webpack): support jit mode guarded class metadata removal

- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/dev-server/index_spec.ts
When using the non-deprecated localization options, the development server was not properly setting the HTML `lang` attribute for the application.  This change ensures that the active locale is used within the application's index HTML file.
Closes #18094
> fix(@angular-devkit/build-angular): set HTML lang attribute when serving

- packages/ngtools/webpack/src/resource_loader.ts
The error message for when a TypeScript or JavaScript file is incorrectly used as a style or template within a component will now also provide the name of the file being incorrectly used.
Partially addresses: #17728
> fix(@ngtools/webpack): improve bad component resource error message

- tests/legacy-cli/e2e/tests/commands/add/add-material.ts
Adding material to a project can fail if an incompatible version of the CDK is already present in the project.  This change adjusts the E2E test to include extra package cleanup between test cases.
> test(@angular/cli): cleanup CDK in add material E2E test

- packages/angular_devkit/build_angular/src/utils/action-cache.ts
- tests/legacy-cli/e2e/tests/build/differential-loading-sri.ts
Previously, the cached integrity values for a subsequent differential loading build would not be properly integrated.  This resulted in builds with incorrect integrity values after an initial build.  The cached differential loading builds will now use the correct integrity values on subsequent builds.
Closes #18254
> fix(@angular-devkit/build-angular): ensure correct SRI values with differential loading

- packages/angular_devkit/build_angular/src/webpack/plugins/hmr/hmr-loader.ts
- tests/legacy-cli/e2e/tests/basic/serve.ts
Backslashes need to be changed to forward slashes for absolute imports to work in Windows.
Closes: https://github.com/angular/angular-cli/issues/19099
> fix(@angular-devkit/build-angular): correctly reference hmr-accept.js file in windows error

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/application/schema.json
- packages/schematics/angular/ng-new/schema.json
This change allows `inlineTemplate=false` and/or `inlineStyle=false` to be used with the `minimal` option when creating an application either by `ng new` or `ng generate application`.
Closes #17528
> fix(@schematics/angular): allow inlineTemplate/inlineStyle with minimal application

- packages/angular_devkit/build_angular/src/webpack/plugins/karma-debug.html
This commits adds a base href value in the karma context iframe used to run unit tests.
It solves #19116  where a unit test throws:
```
No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
```
Even if the application is fine. This is because the index.html from Angular CLI contains a base href value, but not the Karma context iframe. So when adding a unit test with a testing module that imports a NgModule, for example AppModule, which itself imports RouterModule, the unit test used to throw an error (regression appeared in router 3.1).
That could be solved by either adding `RouterTestingModule` to the testing module, or by adding a provider `{ provide: APP_BASE_HREF, useValue: '/' }`, but required to understand the issue.
This solves …
> fix(@angular-devkit/build-angular): add a base href to karma debug context

- integration/angular_cli/package.json
- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
Block until https://github.com/angular/angular/pull/39313 is merged.
> Remove TypeScript 3.9 support

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/browser/specs/styles_spec.ts
- packages/angular_devkit/build_angular/src/utils/build-options.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/postcss-cli-resources.ts
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-11/update-angular-config.ts
Deprecated `rebaseRootRelativeCssUrls` browser builder option has been removed without replacement. This option was used to change root relative URLs in stylesheets to include base HREF and deploy URL and was used only for compatibility and transition as this behavior is non-standard.
> refactor(@angular-devkit/build-angular): remove deprecated browser build option rebaseRootRelativeCssUrls

- packages/angular/cli/models/interface.ts
- packages/angular/cli/utilities/json-schema.ts
This option is used to mark deprecated options as such in AIO.
> fix(@angular/cli): include deprecated option in JSON help

- packages/angular_devkit/core/node/fs.ts
`isFile` and `isDirectory` are tooling only APIs for Node.js that are no longer used by the Angular CLI.
> refactor(@angular-devkit/core): deprecate unused isFile/isDirectory utilities

- packages/angular/cli/commands/add-impl.ts
When attempting to add a package via the add command, packages that have been marked as deprecated will no longer be installed when the deprecated package's peer dependencies match the project's dependencies.
Partially addresses: #17983
> fix(@angular/cli): skip searching deprecated packages with ng add

- packages/angular/cli/commands/update-long.md
> docs: remove `=true` from `--next`

- .github/ISSUE_TEMPLATE/1-bug-report.md
- .github/ISSUE_TEMPLATE/2-feature-request.md
- packages/angular/cli/BUILD.bazel
- packages/angular/cli/commands.json
- packages/angular/cli/commands/extract-i18n-impl.ts
- packages/angular/cli/commands/extract-i18n.json
- packages/angular/cli/models/command-runner.ts
- tests/legacy-cli/e2e/tests/i18n/extract-default.ts
- tests/legacy-cli/e2e/tests/i18n/extract-errors.ts
- tests/legacy-cli/e2e/tests/i18n/extract-ivy-libraries.ts
- tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts
- tests/legacy-cli/e2e/tests/i18n/extract-locale.ts
- tests/legacy-cli/e2e/tests/i18n/extract-outfile.ts
- tests/legacy-cli/e2e/tests/i18n/extract-xmb.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-app-shell.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-serviceworker.ts
- tests/legacy-cli/e2e/tests/i18n/legacy.ts
- tests/legacy-cli/e2e/utils/process.ts
`ng i18n-extract` and `ng xi18n` has been deprecated in favor of `ng extract-i18n` to have a better intuitive naming and match the architect key in `angular.json`.
> refactor(@angular/cli): rename `ng xi18n` to `ng extract-i18n`

- etc/api/angular_devkit/core/src/_golden-api.d.ts
- packages/angular/cli/models/schematic-command.ts
- packages/angular_devkit/core/src/json/schema/interface.ts
- packages/angular_devkit/core/src/json/schema/registry.ts
This change converts answers from prompts into the property type requested from the schema.  This allows properties that expect a number to correctly validate when an input prompt is used.
> fix(@angular/cli): coerce prompt answers to requested property types

- packages/schematics/angular/application/schema.json
- packages/schematics/angular/component/schema.json
- packages/schematics/angular/directive/schema.json
- packages/schematics/angular/enum/schema.json
- packages/schematics/angular/guard/schema.json
- packages/schematics/angular/interceptor/schema.json
- packages/schematics/angular/interface/schema.json
- packages/schematics/angular/library/schema.json
- packages/schematics/angular/module/schema.json
- packages/schematics/angular/service/schema.json
Since will remove lintFix usage warnings when the option is set by a default of another schematic.
Example when executing
```
ng generate module customers --route customers --module app.module
```
The lintFix default of the module schematic will be passed down to the component schematic which would cause a warning to be shown.
Closes #19169
> fix(@schematics/angular): remove lint fix default value

- packages/angular_devkit/build_angular/src/app-shell/index.ts
> refactor(@angular-devkit/build-angular): remove legacy server bundle guess logic

- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
With this change we remove the unintentional breaking change that added publicHost pathname to sockPath instead we now prepend the sockPath with the servePath, which can be either the passed servePath option, baseHref or deployUrl.
> fix(@angular-devkit/build-angular): don't add publicHost pathname to sockPath in dev-server

- packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts
- packages/angular_devkit/build_webpack/src/webpack/index.ts
- tests/legacy-cli/e2e/tests/misc/webpack-5.ts
The Webpack 5 compiler now contains a close function that should be called when the compiler is finished.
> fix(@angular-devkit/build-webpack): fully close Webpack 5 compiler

- .gitignore
Ahead of upgrading to husky v5, adding the shell file location
to .gitignore to prevent it from randomly showing up when devs
checkout older branches.
> build: add husky ignored files to .gitignore

- docs/process/release.md
In the latest release, I was not able to build even after running `yarn` to refresh dependencies. Eventually, we tracked
the issue down to `rm -rf node_modules/`. There may be some instances where this can be necessary to ensure clean
builds.
I opted to just include this change directly in the commands to be more clear that people saw it. If devs want to be lazy they can always skip that step, but they will hopefully at least see it and be reminded that if something doesn't work, they should at least try `rm -rf node_modules/`.
> docs: add `rm -rf node_modules/` to release docs

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
The file-loader within the browser builder's Webpack configuration previously did not allow emitting AVIF images.
> fix(@angular-devkit/build-angular): support emitting AVIF image files

- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
The application output files are not needed during an extraction.  Previously the files were emitted to a memory file system and discarded.  This change removes the processing overhead of emitting the files.  It also provides Webpack 5 support due to the internal memory file system no longer being exported.
> fix(@angular-devkit/build-angular): skip application emit during i18n extraction

- package.json
- yarn.lock
Temp workaround to solve the CI validation error
```
/home/circleci/ng/node_modules/.bin/ng-dev commit-message validate-range --range f6d9028f8b088e1e4aca80c73c455c61b97400a5...fa4e13adf1a4e30048ef541d6af7c6fc5d0b1683
/home/circleci/ng/node_modules/.bin/ng-dev: 1: Syntax error: word unexpected (expecting ")")
```
Will properly be resolved via https://github.com/angular/angular/pull/39443
> build: revert @angular/dev-infra-private package to bb9763f15077a4cb279ba0e210d337e2fde4be0e

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
With this change function and arrow function arguments are not wrapped in parenthesis during the optimization phase. 
`wrap_func_args` which is enabled by default in terser will wrap function arguments in parenthesis. Recently this was also changed to wrap lamdas as well:
https://github.com/terser/terser/commit/66c3a5ce66c7873bded8c6466e72027f9816c548
An increase in bundle size was observed without this change. See: https://github.com/angular/angular/pull/39432#discussion_r512345752
> fix(@angular-devkit/build-angular): when optimizing don't wrap function arguments in parenthesis

- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
The rxjs package contains module level side effects that are not marked with a pure annotation.  However, these side effects are safe to remove if the values are unused.
> fix(@angular-devkit/build-optimizer): set rxjs as having safe side effects

- packages/schematics/update/update/index.ts
- packages/schematics/update/update/index_spec.ts
> fix(@schematics/update): update fail when using yarn 2.0 protocols

- packages/ngtools/webpack/src/transformers/elide_imports.ts
- packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
> fix(@ngtools/webpack): elide type-only imports when using emitDecoratorMetadata

- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/dev-server/works_spec.ts
- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
The source locale was intended to be used when building an application; even when not specifically localizing.  This includes setting the HTML `lang` attribute, injecting locale data, and setting `LOCALE_ID` within the application.
This PR fixes the dev server only.  A followup PR will provide support during builds as well.
Partially addresses: #16950
> fix(@angular-devkit/build-angular): use source locale with non-localized serving

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
- packages/angular_devkit/build_angular/src/webpack/configs/worker.ts
- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
With updates to the `license-webpack-plugin` and adjustments to the web worker plugin configuration, license extraction can now be used with webpack 5.  This change also removes the need to filter out the duplicate asset warning on Webpack 4 that was previously being generated.
> fix(@angular-devkit/build-angular): re-enable webpack 5 license extraction support

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/ngtools/webpack/README.md
- packages/ngtools/webpack/src/angular_compiler_plugin.ts
- packages/ngtools/webpack/src/interfaces.ts
> fix(@ngtools/webpack): show zone.js incompatibility warning when using ES2017+

- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
This change prevents the build optimizer from removing the operator add imports from the rxjs package (for example, `import 'rxjs/add/operator/filter';`).  The entire rxjs package is currently marked as side effect free from within the rxjs `package.json` but the files in the add directory intentionally contain side effects.
> fix(@angular-devkit/build-optimizer): mark rxjs add imports as having side effects

- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
> fix(@angular-devkit/build-angular): improve network error message during fonts inlining

- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/extract-i18n/works_spec.ts
This change will analyze the extract i18n messages for duplicates and issue warnings for each case.  This provides the same default behavior as the standalone message extractor contained within `@angular/localize`.  Configurability of the behavior of a detected duplicate (ignore, warn, error) will be added in a future feature.
Closes #19207
> Validate extracted i18n messages for duplicates

- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
title is not a valid style tag attribute.
Closes #19271
> fix(@angular-devkit/build-angular): remove title attribute from inlined fonts style tag

- tests/legacy-cli/e2e/tests/build/styles/node-sass.ts
The curent version of sass-loader doesn't support node-sass version 5.
https://github.com/webpack-contrib/sass-loader/issues/898
(cherry picked from commit 6717d181bd58a3c14818afd4dfa9c9dffe93b9b4)
(cherry picked from commit c4e8c71e36c56c8d43e913288700f8d8efaa7dde)
> test(@angular-devkit/build-angular): pin node-sass to version 4

- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
A custom babel preset is introduced to centralize the configuration of babel within the package.  Application related presets and plugins are now encapsulated within the custom preset which is used via the Webpack babel-loader.  This new custom preset will also provide the integration point for the upcoming Angular linker.
> refactor(@angular-devkit/build-angular): use custom babel preset to configure babel-loader

- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
See each commit.
These changes are following feedback from twitter and GDE slack channel.
> Bundle output stats fixes

- packages/angular/cli/commands/update-impl.ts
For `ng update --migrateOnly ...` the update implementation checks for transitive
dependencies and tries to parse the containing directory as JSON. This PR
fixes this by providing the correct path to the package.json.
> fix(@angular/cli): correctly read transitive dependency

- packages/angular_devkit/build_angular/src/browser/specs/lazy-module_spec.ts
- packages/angular_devkit/build_angular/src/utils/environment-options.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
- packages/ngtools/webpack/src/index.ts
- packages/ngtools/webpack/src/ivy/diagnostics.ts
- packages/ngtools/webpack/src/ivy/host.ts
- packages/ngtools/webpack/src/ivy/index.ts
- packages/ngtools/webpack/src/ivy/loader.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
- packages/ngtools/webpack/src/ivy/symbol.ts
- packages/ngtools/webpack/src/ivy/system.ts
- packages/ngtools/webpack/src/ivy/transformation.ts
- packages/ngtools/webpack/src/paths-plugin.ts
- packages/ngtools/webpack/src/resource_loader.ts
This change introduces a new Ivy-only Webpack compiler plugin. The plugin leverages the Ivy APIs from the @angular/compiler-cli package. The plugin also simplifies and reduces the amount of code within the plugin by leveraging newer TypeScript features and capabilities. The need for the virtual filesystem has also been removed. The file replacements capability was the primary driver for the previous need for the virtual filesystem. File replacements are now implemented using a two-pronged approach. The first, for TypeScript, is to hook TypeScript module resolution and adjust the resolved modules based on the configured file replacements. This is similar in behavior to TypeScript path mapping. The second, for Webpack, is the use of the NormalModuleReplacementPlugin to facilitate bundling …
> Ivy Webpack compiler plugin

- tests/legacy-cli/e2e/tests/build/platform-server.ts
`@nguniversal/express-engine` currently relies on `^0.1100.0-rc.2` of `@angular-devkit/architect`  which is not present in the local package registry and not semver compatible with master build`^11.0.0-next.7`
> test(@angular-devkit/build-angular): update platform server devkit packages

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/server/schema.json
fileReplacement is meant to replace compilation source files (JavaScript or TypeScript) with other compilation source files in the build. With this change we add validation to fail the build when the files have unsupported extensions.
Closes #11451
> fix(@angular-devkit/build-angular): add validation to fileReplacement values

- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/webpack/plugins/karma.ts
- packages/schematics/angular/workspace/files/package.json.template
There's a bug in Karma 5.2.x that causes unit tests to fail when they
should not. It was supposed to be fixed in
https://github.com/karma-runner/karma/pull/3565 but CI still failed,
blocking the release of Karma.
In order to mitigate this, we temporarily downgrade Karma back to 5.1.x
A side-effect of this is that coverage tests that uses karma-coverage
and exceeds the threshold will not fail, because karma-coverage requires
Karma 5.2.x. We expect this to be fixed very soon.
> fix(@angular-devkit/build-angular): Downgrade Karma to 5.1.x

- tests/legacy-cli/e2e/tests/i18n/ivy-localize-locale-data-augment.ts
This adds an E2E test that demonstrates the usage of a direct import of locale data to augment existing locale data.
> test(@angular-devkit/build-angular): add E2E test for i18n locale data augmentation

- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts_spec.ts
> fix(@angular-devkit/build-angular): properly handle comment removal during font inlining

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
- tests/legacy-cli/e2e/tests/basic/build.ts
```
Initial Chunk Files                      | Names                |      Size
main-es5.6f60fbc22c7e19b5d179.js         | main                 | 154.89 kB
main-es2015.6f60fbc22c7e19b5d179.js      | main                 | 135.87 kB
polyfills-es5.0351d1276e488726c8dc.js    | polyfills-es5        | 129.34 kB
polyfills-es2015.904e51532a46df6b991c.js | polyfills            |  36.12 kB
scripts.b7f93721b30caf483f97.js          | scripts              |   3.45 kB
runtime-es2015.76bfea807ccb0a24e182.js   | runtime              |   1.45 kB
runtime-es5.76bfea807ccb0a24e182.js      | runtime              |   1.45 kB
styles.3ff695c00d717f2d2a11.css          | styles               |   0 bytes
| Initial ES5 Total    | 289.13 kB
| Initial ES2015 Total | 176.88 kB
```
Closes #19330
> fix(@angular-devkit/build-angular): separate initial total size in build output

- packages/schematics/angular/application/files/karma.conf.js.template
- packages/schematics/angular/library/files/karma.conf.js.template
We usually don't have trailing commas in the generated code of the CLI (and this one makes the linter/formatter angry).
> fix(@schematics/angular): remove trailing comma in karma conf

- packages/angular_devkit/build_angular/src/webpack/plugins/karma.ts
This fixes an issue where previously `karma-coverage must be installed in order to run code coverage` error was shown incorrectly.
Closes: #19359
> fix(@angular-devkit/build-angular): show missing karma-coverage error when it's not configured

- packages/angular_devkit/build_angular/package.json
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-11/update-dependencies.ts
This change reuses the v10 migration with update package versions to ensure that an updated project matches the development dependency versions of a newly generated project.
> fix(@schematics/angular): migrate project dependencies to new project versions

- packages/angular_devkit/build_angular/package.json
- yarn.lock
Closes #19374
(cherry picked from commit 44109481ab3b5b1ae7536962fe590cab3ff2e652)
> [patch] fix(@angular-devkit/build-angular): rollback css-loader to version 4

- integration/angular_cli/karma.conf.js
- packages/angular_devkit/build_angular/test/hello-world-app/karma.conf.js
- packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/karma.conf.js
- packages/schematics/angular/application/files/karma.conf.js.template
- packages/schematics/angular/library/files/karma.conf.js.template
Currently, Karma is reporting a failed test and the total twice in a bare CLI project:
```
12 11 2020 13:59:46.666:INFO [launcher]: Starting browser Chrome
✔ Browser application bundle generation complete.
12 11 2020 13:59:50.457:INFO [Chrome 86.0.4240.198 (Mac OS 10.15.7)]: Connected on socket F0ehOBWL6BYFqXfbAAAA with id 69358036
Chrome 86.0.4240.198 (Mac OS 10.15.7) AppComponent should render title FAILED
Error: Expected 'ponyracer app is running!' to contain 'other'.
at <Jasmine>
at UserContext.<anonymous> (src/app/app.component.spec.ts:29:65)
at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-evergreen.js:364:1)
at ProxyZoneSpec.push.QpwO.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:292:1)
Chrome 86.0.4240.198 (Mac OS 10.15.7): Executed 2 of 3 (1 FAILED) (0 …
```
> fix(@schematics/angular): remove duplicated Karma traces

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/server/schema.json
JSON files a can also be valid fileReplacement when using the `resolveJsonModule` TypeScript feature. This causes JSON files to be resolved as JS modules and hence be part of the TypeScript program.
Closes #19378
> fix(@angular-devkit/build-angular) allow json files in fileReplacement

- packages/angular/cli/package.json
This package is no longer released.
> fix(@angular/cli): remove @angular-devkit/build-ng-packagr from update

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
The `webpack-sources` library no longer throws an error when used to process sourcemaps during differential loading.
> fix(@angular-devkit/build-angular): remove workaround for Webpack 5 sourcemaps

- packages/angular_devkit/build_angular/src/dev-server/hmr_spec.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/hmr/hmr-accept.ts
Don't query for hidden inputs when using HMR
> fix(@angular-devkit/build-angular): ignore hidden inputs with hmr

- packages/ngtools/webpack/src/angular_compiler_plugin.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
- packages/ngtools/webpack/src/ngcc_processor.ts
fix(@ngtools/webpack): only use `require.resolve` as a fallback in NGCC processing
Use `enhanced-resolve` instead of `require.resolve` to ensure that we can use symlink path instead of real-path when resolving a linked module.
Closes #19395
> fix(@ngtools/webpack): only use `require.resolve` as a fallback in NGCC processing

- packages/angular_devkit/build_angular/package.json
The `ng-update` field errantly caused this package to show up in the ng update list.  The package group with `codelyzer` also did not provide a benefit as `codelyzer` is updated via a migration and tslint support is now deprecated.
> fix(@angular-devkit/build-angular): remove unneeded update package group

- packages/schematics/update/update/index.ts
This package is deprecated and is removed via a migration.
Closes #19384
> fix(@schematics/update): ignore `@angular-devkit/build-ng-packagr` incompatible peer dependency

- packages/ngtools/webpack/src/ivy/plugin.ts
The `Compilation.compilationDependencies` property is now deprecated in Webpack 5.  The `Compilation.fileDependencies` property is now used instead with Webpack 5.
> fix(@ngtools/webpack): remove use of Webpack 5 deprecated compilationDependencies

- packages/angular_devkit/build_webpack/src/webpack/index.ts
This change ensures that the compiler instance is used when closing the compiler.
> fix(@angular-devkit/build-webpack): properly shutdown webpack 5 compilation

- packages/schematics/angular/application/files/karma.conf.js.template
- packages/schematics/angular/library/files/karma.conf.js.template
Currently it can be hard to find how to configure Jasmine in the Karma config.
For example, a developer might want to reproduce a randomly failing test with a specific seed.
This commit adds some information that may be helpful to beginners.
> fix(@schematics/angular): document jasmine options

- packages/angular_devkit/build_angular/src/dev-server/index.ts
- tests/legacy-cli/e2e/tests/basic/ivy.ts
Using output hashing with the dev-server can cause memory leaks because the dev server does not know when to clean up the old files.
See: https://github.com/webpack/webpack-dev-server/issues/377#issuecomment-241258405
Closes #10411
> fix(@angular-devkit/build-angular): disable output hashing when running dev-server

- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html_spec.ts
> fix(@angular-devkit/build-angular): handle HTML file with no body and  head tags

- .circleci/config.yml
This will run a full E2E test suite with Node.js 14 on master and release branches.  PRs are currently Node.js 12 only.  Node.js 10 is also not run on PRs.
> ci: add Node.js 14 E2E job

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
With this change we apply sourcemaps of libraries in a monorepo without the need to enable `vendor: true`. This is more intuitive behavior and  in line with what the users expect.
We also suppress the `Failed to parse source map from` in-actionable warning.
Closes #11305
> fix(@angular-devkit/build-angular): apply local libraries sourcemap without `vendor: true`

- packages/angular/cli/commands/definitions.json
- packages/angular/cli/commands/deploy.json
- packages/angular/cli/commands/run.json
- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/app-shell/schema.json
- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/dev-server/schema.json
- packages/angular_devkit/build_angular/src/extract-i18n/schema.json
- packages/angular_devkit/build_angular/src/protractor/schema.json
- packages/angular_devkit/build_angular/src/server/schema.json
Closes #16572
Closes https://github.com/angular/angular/issues/39780
> docs: improve description for optimization and target options.

- .circleci/config.yml
Version 8 is close to it's end of life.
> ci: disable 8.3 nightly build

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
With upstream fixes in place, the default Webpack 5 caching behavior can now be enabled.  In development mode, memory caching will now be used, and in production, caching will be disabled as per Webpack 5 default behavior.
> fix(@angular-devkit/build-angular): allow default Webpack 5 caching

- packages/ngtools/webpack/src/ivy/cache.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
- packages/ngtools/webpack/src/resource_loader.ts
The `fileTimestamps` property on the Webpack compilation object no longer exists with Webpack 5.  This change uses the Webpack compiler's property of the same name instead.  The cache invalidation is also moved to a separate file and now calculates the changed file set as well.  This eliminates the second iteration of the file timestamps within the resource loader.
> fix(@ngtools/webpack): remove use of Webpack compilation fileTimestamps property

- packages/angular_devkit/core/src/utils/object.ts
- packages/angular_devkit/core/src/utils/object_spec.ts
> fix(@angular-devkit/core): correctly handle null prototype in deepCopy

- package.json
Ahead of moving to common merge tooling, the current version
of the packages must be tracked in the package.json at the root
of the project.
> build: establish current version in package.json

- packages/schematics/angular/application/other-files/app.module.ts.template
- packages/schematics/angular/e2e/files/src/app.e2e-spec.ts.template
- packages/schematics/angular/module/files/__name@dasherize@if-flat__/__name@dasherize__-routing.module.ts.template
In this PR I've alphabetized some imports to avoid potential linting errors when generating files with angular-cli.
Also see:
https://palantir.github.io/tslint/rules/ordered-imports/
> Fix alphabetize imports

- scripts/packages.ts
`chalk` is not a dev dependency in this repo. We use `ansi-colors` instead.
> build: use ansi-colors instead of chalk in release checks

- .ng-dev/config.ts
- .ng-dev/merge.ts
- .ng-dev/release.ts
- docs/process/release.md
Set up the configurations required for caretakers to be able to rely
on ng-dev for performing merges to all targeted branches.
Blocked on #19515, #19516, #19517 and updating labeling scheme.
> build: set up ng-dev tooling to perform merges in the repository

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- yarn.lock
- Adds usage of webpackImporter https://www.npmjs.com/package/stylus-loader#webpackimporter
- Removes resolve-url-loader usage since stylus handles resolve paths https://stylus-lang.com/docs/js.html#stylusresolveroptions
Closes #19524
> fix(@angular-devkit/build-angular): stylus not resolving imports from libraries

- package.json
- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/app-shell/app-shell_spec.ts
- packages/angular_devkit/build_angular/src/app-shell/index.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/browser/specs/inline-critical-css-optimization_spec.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/dev-server/inline-critical-css-optimization_spec.ts
- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/utils/build-options.ts
- packages/angular_devkit/build_angular/src/utils/index-file/index-html-generator.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css_spec.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts_spec.ts
- packages/angular_devkit/build_angular/src/utils/normalize-builder-schema.ts
- packages/angular_devkit/build_angular/src/utils/normalize-optimization.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/index-html-webpack-plugin.ts
- packages/angular_devkit/build_angular/test/hello-world-app/angular.json
- yarn.lock
This is another feature that we mentioned in the Eliminate Render Blocking Requests RFC (#18730)
Inlining of critical CSS is turned off by default. To opt-in this feature set `inlineCritical` to `true`.
Example:
```json
"configurations": {
"production": {
"fileReplacements": [
{
"replace": "src/environments/environment.ts",
"with": "src/environments/environment.prod.ts"
}
],
"optimization": {
"styles": {
"minify": true,
"inlineCritical": true,
}
},
```
To learn more about critical CSS see;
https://web.dev/defer-non-critical-css
https://web.dev/extract-critical-css/
In a future version of the Angular CLI `inlineCritical` will be enabled by default.
Closes: #17966
Closes: #11395
Closes: #19445
> feat(@angular-devkit/build-angular): enable inlining of critical CSS optimizations

- packages/angular/cli/commands/config.json
- packages/angular/cli/commands/definitions.json
- packages/angular/cli/commands/doc.json
- packages/angular/cli/commands/new.json
- packages/angular/cli/commands/update.json
- packages/angular/cli/lib/config/schema.json
- packages/schematics/angular/application/schema.json
- packages/schematics/angular/class/schema.json
- packages/schematics/angular/component/schema.json
- packages/schematics/angular/directive/schema.json
- packages/schematics/angular/enum/schema.json
- packages/schematics/angular/guard/schema.json
- packages/schematics/angular/interceptor/schema.json
- packages/schematics/angular/interface/schema.json
- packages/schematics/angular/library/schema.json
- packages/schematics/angular/module/schema.json
- packages/schematics/angular/ng-new/schema.json
- packages/schematics/angular/pipe/schema.json
- packages/schematics/angular/resolver/schema.json
- packages/schematics/angular/service/schema.json
- packages/schematics/angular/universal/schema.json
- packages/schematics/angular/workspace/schema.json
- packages/schematics/update/update/schema.json
It's confusing and redundant to use `When true` and `when false` in descriptions for a CLI arguments because specifying false/true is redundant in a command line argument flag and in most cases users will not do it.
Example:
`--foo=true` is the same as `--foo`
`--foo=false` is the same as `--no-foo`
> docs: remove when true, when false from argument descriptions

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
By configuring the optimizer (`terser`) to be aware that the Angular `forwardRef` helper function is a pure function, the optimizer can completely remove the helper call when the return value is unused.
Closes #19572
> fix(@angular-devkit/build-angular): define `forwardRef` as a pure function

- packages/angular/cli/utilities/json-file.ts
- packages/schematics/angular/utility/json-file.ts
Currently, both tsconfigs and workspace configuration files can contain trailing commas
Closes #19576
> fix(@angular/cli): allow trailing commas in JSON files

- packages/angular_devkit/build_angular/src/karma/code-coverage_spec.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/karma.ts
Karma plugins could be provided either a string or object, but our detection    
logic for code coverage plugin only covers the string case.                     
Fix #19571
> fix(@angular-devkit/build-angular): identify plugin provided as string

- docs/process/release.md
During the release today my eyes completely skipped over the new requirement to update `package.json`. I didn't notice this requirement and was very confused when the release check failed. Changed this to a list to give more visual weight and guide readers eyes to both places that need to be modified.
> doc: update package.json version note to be more visible

- .github/angular-robot.yml
- .github/dependabot.yml
- CONTRIBUTING.md
- docs/process/release.md
- renovate.json
- scripts/templates/contributing.ejs
Completes the migration to use the new unified target label system, updating
dependabot, renovate and angular-robot to expect the new labels.
> ci: update remaining references to old pr targeting system

- etc/api/angular_devkit/schematics/tasks/index.d.ts
- packages/angular_devkit/schematics/tasks/package-manager/install-task.ts
In this context this is not a breaking change for two reasons.
- `NodePackageInstallTaskOptions` is not exported.
- `NodePackageInstallTask` is using `NodePackageInstallTaskOptions` with `Partial` type which would cause the Class to become an object literal. This can be seen here: https://github.com/angular/angular-cli/blob/efb97c87f023497dc59a2f4fa3825a2ca78606da/packages/schematics/angular/ng-new/index.ts#L81-L84
> refactor(@angular-devkit/schematics): replace `NodePackageInstallTasKOptions` class with interface

- packages/angular/cli/package.json
- packages/angular/cli/utilities/package-metadata.ts
- packages/schematics/update/package.json
- packages/schematics/update/update/npm.ts
- yarn.lock
With this change Pacote is updated to version 11.1.13.
This also requires normalization of options because Pacote now passes the options to `npm-registry-fetch` which requires some options to be camelCased.
Partially addresses #19624
>     fix(@angular/cli): update pacote to version 11

- packages/schematics/angular/workspace/files/package.json.template
When new application is generated with `--minimal` flag it will be created without any testing frameworks, linters, etc. But `package.json` still contains broken scripts and dependencies. So `"test": "ng test"`, `"lint": "ng lint"` and `"tslint": "~6.1.0"` should be removed. By analogy with `"e2e": "ng e2e"`.
> fix(@schematics/angular): remove unnecessary scripts and dependencies

- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/src/browser/specs/works_spec.ts
- packages/angular_devkit/build_angular/src/browser/tests/options/main_spec.ts
- packages/angular_devkit/build_angular/src/browser/tests/setup.ts
- packages/angular_devkit/build_angular/src/testing/builder-harness.ts
- packages/angular_devkit/build_angular/src/testing/builder-harness_spec.ts
- packages/angular_devkit/build_angular/src/testing/index.ts
- packages/angular_devkit/build_angular/src/testing/jasmine-helpers.ts
This introduces a Builder test harness to facilitate testing of each of the builders within the `build-angular` package.  The test harness is intended to reduce the amount of test code necessary to test the implementations of each builder while also moving the inputs of the test into the test code itself where possible.
> Angular Builders testing refactor

- packages/angular/cli/commands/lint-long.md
> docs: clarify that the options of `ng lint` in AIO are of the deprecated builder

- packages/angular_devkit/build_angular/src/browser/tests/options/polyfills_spec.ts
This change adds expanded unit tests for the browser builder's `polyfills` option using the builder test harness.
> test(@angular-devkit/build-angular): add browser builder polyfills option tests

- packages/angular_devkit/build_angular/src/browser/tests/options/tsconfig_spec.ts
This change adds expanded unit tests for the browser builder's `tsConfig` option using the builder test harness.
> test(@angular-devkit/build-angular): add browser builder tsConfig option tests

- packages/angular_devkit/build_angular/src/browser/tests/options/assets_spec.ts
This change adds expanded unit tests for the browser builder's `assets` option using the builder test harness.
> test(@angular-devkit/build-angular): add browser builder assets option tests

- packages/angular_devkit/build_angular/src/browser/tests/options/scripts_spec.ts
- packages/angular_devkit/build_angular/src/testing/jasmine-helpers.ts
This change adds expanded unit tests for the browser builder's `scripts` shorthand option using the builder test harness.
> test(@angular-devkit/build-angular): add browser builder scripts shorthand option tests

- packages/angular_devkit/build_angular/src/browser/tests/options/watch_spec.ts
- packages/angular_devkit/build_angular/src/testing/builder-harness.ts
- packages/angular_devkit/build_angular/src/testing/file-watching.ts
- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/builder-watch-plugin.ts
This change adds internal support for providing a custom file watching mechanism to the browser (and associated) builders.  The support integrates and overrides the Webpack watch system when enabled.  This is currently intended to support builder unit testing use cases.
> test(@angular-devkit/build-angular): add initial browser builder watch option tests

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
This library is minified and it causes Babel to consume a lot of resources when trying to downlevel.
Closes #19660
> fix(@angular-devkit/build-angular): don't downlevel web-animations-js

- packages/angular_devkit/build_angular/src/browser/tests/options/stats-json_spec.ts
This change adds expanded unit tests for the browser builder's `statsJson` option using the builder test harness.
> test(@angular-devkit/build-angular): add browser builder statsJson option tests

- packages/angular_devkit/build_angular/src/browser/tests/options/styles_spec.ts
This change adds expanded unit tests for the browser builder's `styles` option using the builder test harness.
> test(@angular-devkit/build-angular): add browser builder styles option tests

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- tests/legacy-cli/e2e/tests/build/styles/symlinked-global.ts
With this change we resolve the global stylesheet entrypoint path to use the realpath instead of the symlink path.
Fixes #3500
> fix(@angular-devkit/build-angular): correctly resolve symlinked global styles entrypoints

- packages/schematics/angular/utility/ast-utils.ts
- packages/schematics/angular/utility/ast-utils_spec.ts
> fix(@schematics/angular): correctly handle PropertyAssignments with StringLiteral keys

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/extract-i18n/schema.json
- packages/angular_devkit/build_angular/src/utils/load-translations.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl-arb.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl-json.ts
- tests/legacy-cli/e2e/tests/i18n/legacy.ts
`@angular/localize` supports extracting as `json` file, but CLI does not support this.
> feat(@angular-devkit/build-angular): `ng extract-i18n` support json and arb

- scripts/changelog.ts
This change will handle github reverts such as https://github.com/angular/angular-cli/pull/19736
> build: update revert pattern in changelog generator

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/utils/build-options.ts
- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
This change uses the project's TypeScript configuration script target to determine the required Babel processing.
> refactor(@angular-devkit/build-angular): use script target in custom babel loader

- .ng-dev/merge.ts
Change the merge method used by merge tooling to use rebase instead of using
squash.
> ci: change merge strategy to rebase instead of squash

- packages/angular_devkit/build_angular/src/webpack/es5-polyfills.js
This change adds the following polyfills for IE11 (`nomodule` browsers):
ES2016:
Array.prototype.includes
ES2017:
Object.entries
Object.values
Object.getOwnPropertyDescriptors
ES2019:
Object.fromEntries
Array.prototype.flat
Array.prototype.flatMap
> feat(@angular-devkit/build-angular): update IE11 Object/Array polyfills

- packages/angular_devkit/build_angular/src/browser/tests/options/scripts_spec.ts
This change adds expanded unit tests for the browser builder's `scripts` longhand option using the builder test harness.
> test(@angular-devkit/build-angular): add browser builder scripts longhand option tests

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/browser/specs/differential_loading_spec.ts
- packages/angular_devkit/build_angular/src/browser/specs/scripts-array_spec.ts
- packages/angular_devkit/build_angular/src/utils/build-options.ts
- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
- packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- tests/legacy-cli/e2e/tests/build/differential-loading-watch.ts
With this change we generate consistent file names when using the browser builder in watch mode with differential loading.
Closes #15157
> fix(@angular-devkit/build-angular): generate consistent filenames

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/webpack/plugins/karma.ts
- packages/schematics/angular/workspace/files/package.json.template
- tests/legacy-cli/e2e/tests/test/test-karma-5.ts
- yarn.lock
This change adds support for using karma 6.x within a project.
> feat(@angular-devkit/build-angular): support karma version 6.x

- package.json
This is needed as otherwise the ng-dev tools will fail due to `Error: Discovered unexpected version-branch "11.1.x" for a release-train that is already active in the "master" branch. Please either delete the branch if created by accident, or update the version in the next branch (master).`
> build: update next branch to reflect new release-train `v11.2.0-next.0`

- packages/angular/cli/models/schematic-command.ts
- packages/angular_devkit/core/src/json/schema/registry.ts
This change provides the first schema validation error to a prompt provider when using a prompt definition's `validate` function.  This allows a prompt provider to show additional context to a user when an entered value is invalid.
> feat(@angular-devkit/core): provide prompt validation errors to provider

- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
If someone uses the `extract-i18n` command with the deprecated `--i18n-format` option,
then `options.format` is undefined and the `outFile` defaults to `messages.xlf`,
whereas the content will be using the proper format.
ng extract-i18n --i18n-format json
As the command is deprecated I'm not sure it's worth adding a complete e2e test. Let me know if the PR needs to be improved.
> fix(@angular-devkit/build-angular): resolve i18n outFile with normalized format

- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/utils/service-worker.ts
- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
The `@angular/service-worker` package is used by the browser and app-shell builders.
By adding the package as an optional peer dependency, package managers can ensure that the package is available to import.
> fix(@angular-devkit/build-angular): add service-worker as optional peer dependency

- packages/angular_devkit/build_angular/src/app-shell/index.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/utils/normalize-asset-patterns.ts
- packages/angular_devkit/build_angular/src/utils/normalize-builder-schema.ts
- packages/angular_devkit/build_angular/src/utils/normalize-file-replacements.ts
- packages/angular_devkit/build_angular/src/utils/service-worker.ts
- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
The virtualfs Host was only used for exist and directory checks during asset and file replacement option normalization within the browser and dev-server builders.
> refactor(@angular-devkit/build-angular): remove virtualfs host usage from browser/dev-server

- packages/angular/cli/package.json
Having `@angular-devkit/architect` as a dependency and running `ng update @angular/cli` leaves it not updated.
Adding this package to `@angular/cli` `packageGroup` will solve this inconvenience.
> fix(@angular/cli): add @angular-devkit/architect to ng-update packageGroup

- packages/angular/cli/models/analytics.ts
The `cli` workspace configuration property was previously checked to determine if it was an object even if the property did not yet exist.
> fix(@angular/cli): avoid analytics cli object check if not present

- packages/ngtools/webpack/src/ivy/transformation.ts
- packages/ngtools/webpack/src/transformers/elide_imports.ts
- packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
- packages/ngtools/webpack/src/transformers/spec_helpers.ts
Due to the method used by TypeScript to emit decorator metadata via the `emitDecoratorMetadata` function, the import eliding algorithm within the Angular compiler plugin may errantly remove imports to type metadata included in the emitted decorator calls. By moving the eliding before TypeScript, the eliding can use the Type nodes to analyze for used imports when `emitDecoratorMetadata` is enabled. This fix also reworks the previous fix to prevent the eliding to errantly remove certain factory functions that TypeScript may use in emitted code but are not yet referenced in the input code. The previous fix was to move the eliding after the TypeScript transformations.  The new fix is therefore not as comprehensive as the original but covers the usecase within the originating issue (#13297). …
> fix(@ngtools/webpack): perform import eliding before TypeScript transforms

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- yarn.lock
`postcss-loader` version 4.2.0 added an `implementation` option. Using the using will ensure that the correct postcss version is used.
More info: https://github.com/webpack-contrib/postcss-loader/commit/deac9787eed614b1c445f091a2b70736a6212812
Fixes #19839
> fix(@angular-devkit/build-angular): resolve postcss from build-angular package

- package.json
- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
- yarn.lock
With this change users can now their proxy server via the `HTTPS_PROXY` environment variable. The specified proxy will be used when making requests to inline fonts.
Closes #19401
> fix(@angular-devkit/build-angular): inlining fonts behind proxy

- packages/angular_devkit/core/src/json/schema/interface.ts
- packages/angular_devkit/core/src/json/schema/registry.ts
The flatten schema method has been deprecated without replacement.
Producing a flatten schema document does not in all cases produce a schema with identical behavior to the original.
See: https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.appendix.B.2
> refactor(@angular-devkit/core): deprecate flatten schema method

- packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
- packages/ngtools/webpack/src/transformers/export_ngfactory.ts
- packages/ngtools/webpack/src/transformers/import_factory.ts
- packages/ngtools/webpack/src/transformers/insert_import.ts
- packages/ngtools/webpack/src/transformers/register_locale_data.ts
- packages/ngtools/webpack/src/transformers/replace_bootstrap.ts
- packages/ngtools/webpack/src/transformers/replace_resources.ts
- packages/ngtools/webpack/src/transformers/replace_server_bootstrap.ts
- tests/legacy-cli/e2e/assets/webpack/test-app/package.json
- tests/legacy-cli/e2e/assets/webpack/test-app/tsconfig.json
- tests/legacy-cli/e2e/assets/webpack/test-app/webpack.config.js
- tests/legacy-cli/e2e/tests/packages/webpack/test-app.ts
TypeScript provides a set of  pure  functions for producing syntax tree nodes. Since TypeScript 4.0 these methods have been deprecated in favor of the `factory` API.
See: https://github.com/microsoft/TypeScript/wiki/API-Breaking-Changes#typescript-40
> Replace deprecated TypeScript methods

- packages/angular/cli/utilities/package-metadata.ts
- packages/schematics/update/update/npm.ts
Before only first line end was being replaced.
Also, the replace value was incorrectly escaped.
The CA read from cafile being corrupt resulted in broken updates
when using registry with self-signed certificate.
The workaround till this is merged is to use `ca` or `ca[]` properties in `.npmrc`.
Before:
```
-----BEGIN CERTIFICATE-----\nMIIC5DCCAcwCCQDBp0EioJnYqTANBgkqhkiG9w0BAQsFADA0MQswCQYDVQQGEwJT
RTESMBAGA1UEBwwJU3RvY2tob2xtMREwDwYDVQQKDAhTd2VkYmFuazAeFw0yMTAx
...rest_of_certificate
-----END CERTIFICATE-----
```
After:
```
-----BEGIN CERTIFICATE-----
MIIC5DCCAcwCCQDBp0EioJnYqTANBgkqhkiG9w0BAQsFADA0MQswCQYDVQQGEwJT
RTESMBAGA1UEBwwJU3RvY2tob2xtMREwDwYDVQQKDAhTd2VkYmFuazAeFw0yMTAx
...rest_of_certificate
-----END CERTIFICATE-----
```
> fix(@schematics/update): update line end normalization for CA file read from .npmrc

- packages/ngtools/webpack/src/ivy/transformation.ts
TypeScript provides a set of pure functions for producing syntax tree nodes. Since TypeScript 4.0 these methods have been deprecated in favor of the factory API.
See: https://github.com/microsoft/TypeScript/wiki/API-Breaking-Changes#typescript-40
> refactor(@ngtools/webpack): replace deprecated TypeScript methods

- packages/angular/cli/BUILD.bazel
- packages/angular/cli/commands/add-impl.ts
- packages/angular/cli/package.json
- packages/angular/cli/utilities/install-package.ts
- packages/angular/cli/utilities/spinner.ts
This adds a spinner as well as shows more information regarding what package version was selected to be installed.
Closes #17983
> feat(@angular/cli): provide additional status messaging for ng add

- packages/angular_devkit/schematics/src/tree/host-tree.ts
- packages/angular_devkit/schematics/src/tree/host-tree_spec.ts
- tests/legacy-cli/e2e/tests/generate/component/component-duplicate.ts
This fixes #11337 to allow for merging of a tree with another when the the file already exists in the tree being merged into.
> fix(@angular-devkit/schematics): Fix merge that causes an overwrite

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/bundle-budget.ts
- packages/angular_devkit/build_angular/src/webpack/utils/async-chunks.ts
> fix(@angular-devkit/build-angular): styles that are not injected do count for initial bundle size

- .bazelrc
- .bazelversion
- .gitignore
- WORKSPACE
Update to the latest version of bazel (4.0.0).
> build: update bazel to 4.0.0

- packages/angular_devkit/build_angular/src/utils/bundle-calculator.ts
- packages/angular_devkit/build_angular/src/utils/bundle-calculator_spec.ts
Currently `processResults` is ignored inside the any, any script, all and all script calculators, so the wrong file size is checked against the budgets. This PR fixes the issue by fetching the correct asset size for es2015 assets from the `processResults` array.
Fixes https://github.com/angular/angular-cli/issues/19849
> Fix bundle budgets with any script and differential loading

- etc/api/angular_devkit/schematics/tools/index.d.ts
- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/models/schematic-command.ts
- packages/angular/cli/models/schematic-engine-host.ts
- packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
- tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
- tests/legacy-cli/e2e/utils/packages.ts
This change adds logic to redirect module resolution requests for Angular schematics to ensure that the correct versions of core schematic related packages are used.  This also ensures that the runtime version of the schematics package matches the version used inside the schematic and that object instances passed into the schematic are compatible.
The current set of core schematic related packages are `@angular-devkit/*` and `@schematics/angular`.  Only first-party Angular schematics are currently affected by this change.
This change also solves issues such as #16392 which were caused by the package manager not hoisting the core schematic packages to a location the update migrations could access.
> fix(@angular/cli): direct Angular schematic dependency requests to known versions

- packages/angular_devkit/schematics/src/rules/schematic.ts
- packages/angular_devkit/schematics/src/tree/host-tree.ts
This corrects several underlying schematics Tree issues encountered when using the `applyToSubtree` rule.
Fixes #16082
> Schematics scoped tree fixes

- packages/angular/cli/BUILD.bazel
- packages/angular/cli/commands/doc-impl.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
Main benefit is to use type definitions.
> use ES6 imports instead of require

- packages/angular_devkit/build_angular/src/browser/tests/behavior/rebuild-errors_spec.ts
- packages/ngtools/webpack/src/resource_loader.ts
Webpack doesn't handle well expections and promise rejections. With this change we use the compilation errors.
Closes #19892
> fix(@ngtools/webpack): recover from component stylesheet errors

- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
During font inlining, a request can return a response status code other than 200. In which case, the contents of the page should not be inlined.
> fix(@angular-devkit/build-angular): error with status code when response code is not 200

- packages/schematics/angular/ng-new/schema.json
There is a broken link inside `ng new` section (https://angular.io/cli/new). When you click on that link, placed next to `strict` option, you are redirected to 404 (Page not found).
> docs: replace broken link
