angular/angular-cli

packages/angular/cli/commands/add-impl.ts
packages/angular/cli/commands/update-impl.ts
packages/angular/cli/package.json
packages/angular/cli/utilities/package-metadata.ts
yarn.lock

8.3.x variant of https://github.com/angular/angular-cli/pull/15605

refactor(@angular/cli): use canonical npm logic to determine update package version

---

packages/schematics/angular/ng-new/index.ts
packages/schematics/angular/ng-new/schema.json

fix(@schematics/angular): add strict option to ng-new

---

packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
packages/angular_devkit/build_angular/src/browser/schema.json
packages/angular_devkit/build_angular/src/server/schema.json
packages/ngtools/webpack/src/interfaces.ts

Deprecate options related to string form of lazy loading and SystemJsNgModuleLoader 

---

.circleci/config.yml

Patch version of https://github.com/angular/angular-cli/pull/15038

8.3.x win cache workspace

---

packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_angular/src/browser/action-executor.ts
packages/angular_devkit/build_angular/src/browser/index.ts
packages/angular_devkit/build_angular/src/utils/process-bundle.ts
yarn.lock

Improve performance of parallel bundle processing [8.3.x]

---

packages/angular/cli/BUILD
packages/angular/cli/commands/add-impl.ts
packages/angular_devkit/core/BUILD
packages/schematics/angular/service-worker/index.ts
packages/schematics/angular/web-worker/index.ts

build: g3 sync for packages/schematics and packages/angular

---

packages/schematics/angular/application/other-files/app.component.html.template

Subtracting the top space from image vh(viewport height) to remove scroll
Closes: #15596

fix(@schematics/angular): scroll issue on new app

---

packages/schematics/angular/migrations/update-9/update-workspace-config.ts
packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
packages/schematics/angular/migrations/update-9/utils.ts

This migration will update current projects by adding the `i18n` project level option and add `localize` option in the server and browser builder configurations when both `i18nLocale` and `i18nFile` are defined.

feat(@schematics/angular): add migration to add new i18n options for Ivy

---

packages/schematics/angular/workspace/files/package.json.template

Followup to https://github.com/angular/angular/pull/32999#discussion_r334177360

fix(@schematics/angular): update ngcc postinstall command

---

packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_angular/src/browser/action-cache.ts
packages/angular_devkit/build_angular/src/browser/index.ts
packages/angular_devkit/build_angular/src/extract-i18n/index.ts
packages/angular_devkit/build_angular/src/utils/i18n-options.ts
packages/angular_devkit/build_angular/src/utils/load-translations.ts
packages/angular_devkit/build_angular/src/utils/process-bundle.ts
tests/legacy-cli/e2e/ng-snapshot/package.json
tests/legacy-cli/e2e/tests/i18n/ivy-localize.ts

Initial support for differential loading builds to enable integration testing.

feat(@angular-devkit/build-angular): initial support for i18n translation inlining

---

packages/angular/cli/lib/config/schema.json

fix(@angular/cli) change analytics type to string

---

packages/angular/cli/tasks/install-package.ts

fix(@angular/cli): don't install using global command but rather install in a different folder

---

packages/angular/cli/commands/add-impl.ts
tests/legacy-cli/e2e/tests/commands/add/add-material.ts

fix(@angular/cli): verify package specifier when adding a package

---

packages/angular/cli/commands/update-impl.ts

fix(@angular/cli): pass next option to all update logic

---

packages/angular/cli/commands/update-impl.ts

fix(@angular/cli): add migration name to commit header

---

packages/angular/cli/commands/update-impl.ts

fix(@angular/cli): remove unneeded git HEAD update message

---

packages/angular_devkit/build_angular/src/dev-server/index.ts

fix(@angular-devkit/build-angular): silence internal webpack dev server logging

---

packages/schematics/angular/workspace/files/package.json.template

fix(@schematics/angular): remove ngcc postinstall hook

---

packages/angular/cli/commands/update-impl.ts
packages/angular/cli/tasks/install-package.ts
packages/schematics/update/update/schema.json

fix(@angular/cli): add pnpm options to install package task 

---

packages/angular_devkit/build_angular/src/utils/i18n-options.ts
packages/angular_devkit/build_angular/src/utils/load-translations.ts

fix(@angular-devkit/build-angular): support XMB/XTB translation file parser

---

packages/angular_devkit/core/src/json/schema/registry.ts

fix(@angular-devkit/core): allow multiselect list defaults

---

packages/angular/cli/commands/update-impl.ts
packages/angular/cli/tasks/install-package.ts
packages/schematics/update/update/schema.json

LTS version of #16151

---

packages/angular_devkit/schematics/src/tree/host-tree.ts
packages/schematics/angular/migrations/update-9/add-tslib.ts

See each commit 
Fixes: #16191

fix(@angular-devkit/schematics): only commit to disk when contents of file changes 

---

packages/angular/cli/commands/update-impl.ts
packages/angular/cli/commands/update.json
packages/angular_devkit/core/src/json/schema/utility.ts

fix(@angular/cli): support running a single migration from a package

---

packages/angular/cli/tasks/install-package.ts

fix(@angular/cli): fix package manager warnings when running temporary install

---

packages/angular_devkit/build_angular/src/browser/index.ts
packages/angular_devkit/build_angular/src/utils/process-bundle.ts
packages/angular_devkit/build_angular/test/browser/differential_loading_spec_large.ts

Ensures that iteration is properly down leveled and allows proper differential loading processing when tsconfig target is greater than ES2015.

Several 8.3.x differential loading fixes

---

packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
packages/angular_devkit/build_angular/src/browser/index.ts
packages/angular_devkit/build_angular/src/utils/process-bundle.ts
tests/legacy-cli/e2e/tests/build/worker.ts

fix(@angular-devkit/build-angular): support differential loading for web workers

---

packages/angular_devkit/build_angular/src/dev-server/index.ts
packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts

Patch version of https://github.com/angular/angular-cli/pull/16317

fix(@angular-devkit/build-angular): pass webpack factor to runWebpack

---

packages/schematics/angular/library/index.ts
packages/schematics/angular/library/index_spec.ts
packages/schematics/angular/workspace/files/tsconfig.json.template

Patch version of https://github.com/angular/angular-cli/pull/16340/

Library imports patch

---

packages/angular/cli/lib/config/schema.json
packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts
packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/utils.ts
packages/angular_devkit/build_angular/src/server/index.ts
packages/angular_devkit/build_angular/src/server/schema.json
packages/angular_devkit/build_angular/test/server/base_spec_large.ts
packages/angular_devkit/build_angular/test/server/external_dependencies_spec_large.ts
tests/legacy-cli/e2e/tests/build/platform-server.ts
tests/legacy-cli/e2e/tests/misc/universal-bundle-dependencies.ts

Server builders bundle-dependencies and external-dependencies

---

packages/angular_devkit/build_angular/src/utils/i18n-options.ts
tests/legacy-cli/e2e/tests/i18n/ivy-localize-sourcelocale.ts

fix(@angular-devkit/build-angular): ensure source locale data is injected when localizing

---

docs/design/build-system.md

I think this still needs more detail but is a good starting point.

docs: add build system doc

---

packages/angular_devkit/build_angular/package.json
yarn.lock

`yarn upgrade terser` on the 9.0.x branch.

build: update terser to version 4.5.1

---

packages/angular/cli/lib/init.ts

LTS version of https://github.com/angular/angular-cli/pull/16593

[LTS] fix(@angular/cli): disable Browserslist old data warning

---

packages/angular_devkit/build_angular/src/utils/process-bundle.ts
packages/angular_devkit/build_optimizer/BUILD
packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-loader.ts

The `webpack-sources` package provides the `SourceMapSource` class which provides sourcemap merging functionality including identity mapping.  This provides for higher quality sourcemaps than the previous merging strategy.  The merging logic is also simplified as a result of the change.

Improve source map generation quality

---

etc/api/angular_devkit/core/node/_golden-api.d.ts
etc/api/angular_devkit/core/node/testing/index.d.ts
etc/api/angular_devkit/core/src/_golden-api.d.ts
etc/api/angular_devkit/schematics/src/_golden-api.d.ts
etc/api/angular_devkit/schematics/testing/index.d.ts
etc/api/angular_devkit/schematics/tools/index.d.ts
package.json
packages/angular_devkit/architect/node/node-modules-architect-host.ts
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_optimizer/package.json
packages/ngtools/webpack/package.json
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
packages/schematics/schematics/schematic/files/package.json
tests/angular_devkit/build_ng_packagr/ng-packaged/tsconfig.json
yarn.lock

Patch version of https://github.com/angular/angular-cli/pull/16599

patch version of 16599

---

package.json
yarn.lock

build: update @types/jasmine to ~3.5.0

---

docs/design/build-system-overview.dot
docs/design/build-system.md

Followup from https://github.com/angular/angular-cli/pull/16400

docs: address remaining review items

---

packages/angular/cli/bin/postinstall/script.js

fix(@angular/cli): prevent postinstall script errors from blocking install

---

packages/angular_devkit/build_angular/src/utils/process-bundle.ts

fix(@angular-devkit/build-angular): re-introduce fast sourcemap path

---

docs/process/release.md

Preview: https://github.com/kyliau/angular-cli/blob/docs/docs/process/release.md

docs: Reorganize release docs to emphasize updating release notes

---

packages/angular_devkit/build_angular/package.json
yarn.lock

Patch version of https://github.com/angular/angular-cli/pull/16785

[Patch] build: update terser-webpack-plugin to version 2.3.3

---

packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
packages/angular_devkit/build_angular/src/utils/action-cache.ts
packages/angular_devkit/build_angular/src/utils/environment-options.ts
packages/angular_devkit/build_angular/src/utils/process-bundle.ts

`NG_BUILD_DEBUG_OPTIMIZE` when enabled will turn off minify and mangle as well as enable beautify.

refactor(@angular-devkit/build-angular): improve debug optimize environment variables

---

scripts/validate-licenses.ts
yarn.lock

Needed due to https://github.com/angular/angular-cli/pull/16818

ci: update pako version

---

packages/angular_devkit/build_angular/package.json
yarn.lock

[8.3.x] Update browserslist & caniuse-lite

---

packages/angular/cli/commands/update-impl.ts

fix(@angular/cli): added clarity on angular cli version issues

---

packages/schematics/angular/migrations/migration-collection.json
packages/schematics/angular/migrations/update-9/schematic-options.ts
packages/schematics/angular/migrations/update-9/schematic-options_spec.ts

fix(@schematics/angular): migrate spec and styleext schematic options

---

packages/angular/cli/lib/config/schema.json

@schematics/angular:component misses skipTests

Add skipTests to @schematics/angular:component

---

packages/angular_devkit/build_angular/src/extract-i18n/index.ts

fix(@angular-devkit/build-angular): provide explicit return type for extract-i18n builder

---

packages/schematics/angular/application/other-files/app.component.html.template

Starter app is janky after adding Angular Material
Fixes angular#16966

fix(@schematics/angular): scroll issue on new app after adding Material

---

packages/angular_devkit/build_angular/package.json
yarn.lock

fix(@angular-devkit/build-angular): update core-js to 3.6.4

---

packages/angular_devkit/schematics_cli/bin/schematics.ts

fix(@angular-devkit/schematics-cli): provide resolvePaths to NodeWorkflow

---

packages/schematics/angular/workspace/files/__dot__editorconfig.template

feat(@schematics/angular): set quote_type = single in .editorconfig

---

docs/specifications/update.md

am -> an or probably even better the

docs: fix typo in the schematics ng update

---

packages/angular/cli/lib/config/schema.json
packages/angular_devkit/build_angular/src/tslint/schema.json

Change the default tslint formatter to stylish as offers a better output

feat(@angular-devkit/build-angular): change tslint default formatter to stylish

---

package.json
packages/angular_devkit/benchmark/package.json
packages/angular_devkit/build_angular/package.json
packages/ngtools/webpack/package.json
yarn.lock

NOTE TO CARETAKER: pending status of ci/angular: merge status is incorrect and can be ignored. The missing status checks do not exist on this branch.

[7.3.x] Correct various vulnerability audit warnings

---

package.json
packages/angular/cli/package.json
packages/schematics/update/package.json
yarn.lock

Closes #17314 and closes #16615

fix(@angular/cli): downgrade pacote to 9.5.12

---

packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
yarn.lock

The plugin is a noop when yarn PnP is not used.

feat(@angular-devkit/build-angular): provide webpack support for resolving via Yarn PnP

---

packages/schematics/angular/application/other-files/app.component.html.template

fix(@schematics/angular): invalid rgba color in app.component.html

---

packages/schematics/angular/migrations/migration-collection.json
packages/schematics/angular/migrations/update-10/update-dependencies.ts
packages/schematics/angular/workspace/files/package.json.template

Related to: https://github.com/angular/angular-cli/pull/17435

feat(@schematics/angular): update karma to 5.0.0

---

packages/angular/cli/bin/ng

Removes errant comma within the message log call and allows the process to exit naturally to better ensure that it is written to the console.

fix(@angular/cli): ensure Node.js message is shown on old Node.js versions

---

.yarnrc
WORKSPACE
package.json

This commit vendors yarn v1.22.4 into angular cli repo and updates yarnrc.
Reference PR: https://github.com/angular/angular/pull/36464

build: update to yarn 1.22.4

---

packages/angular/cli/commands/deploy.json

fix(@angular/cli): allow configuration option in `ng deploy`

---

packages/schematics/angular/workspace/files/package.json.template

Dev dependency updated via https://github.com/angular/angular-cli/pull/17667

build: generate project using karma-coverage-istanbul-reporter version 3.0.2

---

packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
packages/angular_devkit/build_angular/src/angular-cli-files/plugins/dedupe-module-resolve-plugin.ts
packages/angular_devkit/build_angular/src/angular-cli-files/plugins/webpack.ts
packages/schematics/angular/library/files/package.json.template
packages/schematics/angular/migrations/migration-collection.json
packages/schematics/angular/migrations/update-10/update-dependencies.ts
packages/schematics/angular/migrations/update-10/update-libraries-tslib.ts
packages/schematics/angular/migrations/update-10/update-libraries-tslib_spec.ts
packages/schematics/angular/utility/dependencies.ts
packages/schematics/angular/utility/latest-versions.ts
tests/legacy-cli/e2e/tests/build/material.ts
tests/legacy-cli/e2e/tests/commands/add/add-material.ts
tests/legacy-cli/e2e/tests/misc/debupe-duplicate-modules.ts

Tslib 2.0 changes

---

packages/schematics/angular/workspace/files/tslint.json.template
packages/schematics/angular/workspace/index_spec.ts

feat(@schematics/angular): add tslint no-any and typedef rules when in strict mode

---

packages/schematics/angular/migrations/migration-collection.json
packages/schematics/angular/migrations/update-10/update-dependencies.ts
tests/legacy-cli/e2e/tests/update/update-7.0.ts

Patch version of https://github.com/angular/angular-cli/pull/17839

fix(@schematics/angular): update several testing dev dependencies

---

packages/schematics/angular/ng-new/schema.json

From initial feedback from devrel we should remove the prompt

fix(schematics/angular): remove strict prompt

---

tests/legacy-cli/e2e/tests/misc/dedupe-duplicate-modules.ts

This should help removing the flakes

test: remove progress from dedupe-duplicate-modules e2e test

---

packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
yarn.lock

Fixes security issue serialize-javascript prior to 3.1.0 allows remote attackers
Closes #17912

fix(@angular-devkit/build-angular): update terser-webpack-plugin to 3.0.3

---

packages/schematics/angular/utility/ast-utils.ts

By leveraging TypeScript's AST type guards, function parameter assumptions and casting can be removed.  Many of these cases caused errors when enabling TypeScript's strict option. This is preliminary work to support enabling full TypeScript strict mode within the project.

refactor(@schematics/angular): use type guard based narrowing in ast-utils

---

packages/schematics/angular/application/files/tsconfig.app.json.template
packages/schematics/angular/application/files/tsconfig.spec.json.template
packages/schematics/angular/application/index_spec.ts
packages/schematics/angular/application/other-files/package.json.template
packages/schematics/angular/e2e/files/tsconfig.json.template
packages/schematics/angular/library/files/tsconfig.lib.json.template
packages/schematics/angular/library/files/tsconfig.lib.prod.json.template
packages/schematics/angular/library/files/tsconfig.spec.json.template
packages/schematics/angular/library/index_spec.ts
packages/schematics/angular/migrations/update-10/side-effects-package-json.ts
packages/schematics/angular/migrations/update-10/solution-style-tsconfig.ts
packages/schematics/angular/migrations/update-9/update-app-tsconfigs_spec.ts
packages/schematics/angular/universal/files/root/tsconfig.server.json.template
packages/schematics/angular/universal/index_spec.ts
packages/schematics/angular/web-worker/files/worker-tsconfig/tsconfig.worker.json.template
packages/schematics/angular/web-worker/index_spec.ts
packages/schematics/angular/workspace/files/tsconfig.base.json.template
packages/schematics/angular/workspace/files/tsconfig.json.template
packages/schematics/angular/workspace/index_spec.ts
tests/legacy-cli/e2e/utils/project.ts

See individual commits.
Blocked on: https://github.com/angular/angular/pull/37533

Add links to generated configs

---

packages/angular_devkit/build_ng_packagr/package.json
packages/schematics/angular/utility/latest-versions.ts

(cherry picked from commit 45aee7d37c52574384c391104c5c6defd3f86ba9)

build: update ng-packagr to stable

---

packages/schematics/angular/application/files/.browserslistrc.template
packages/schematics/angular/application/index_spec.ts
tests/legacy-cli/e2e/tests/build/differential-cache.ts
tests/legacy-cli/e2e/tests/build/differential-loading.ts
tests/legacy-cli/e2e/tests/build/polyfills.ts
tests/legacy-cli/e2e/tests/build/prod-build.ts
tests/legacy-cli/e2e/tests/build/sourcemap.ts
tests/legacy-cli/e2e/tests/build/worker.ts
tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl-xliff2.ts
tests/legacy-cli/e2e/tests/misc/browsers.ts

fix(@schematics/angular): split browserslist IE entries and provide better comments

---

packages/ngtools/webpack/src/ngcc_processor.ts

This change performs a ngcc run check to determine if an initial execution is required. If a run hash file exists that matches the current package manager lock file and the project's tsconfig, then an initial ngcc run has already been performed.
By limiting the need to spawn and execute ngcc in another process on each build, the total build time can be reduced on subsequent builds.

fix(@ngtools/webpack): add ngcc initial run check

---

packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
packages/angular_devkit/build_angular/src/browser/index.ts

fix(@angular-devkit/build-angular): show child compilation errors 

---

packages/schematics/angular/application/files/.browserslistrc.template

refactor(@schematics/angular): pluralize Safari entry in .browserslistrc

---

packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts

fix(@angular-devkit/build-angular): don't emit empty warnings

---

packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts

fix(@angular-devkit/build-angular): flatten child compilation errors and warnings

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/core/package.json
yarn.lock

Fixes security notice https://snyk.io/vuln/SNYK-JS-AJV-584908
Closes: #18308

fix(@angular-devkit/core): update `ajv` to `6.12.3`

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/core/package.json
yarn.lock

Fixes security notice https://snyk.io/vuln/SNYK-JS-AJV-584908
Closes: #18308

[LTS - 9] fix(@angular-devkit/core): update `ajv` to `6.12.3`

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/core/package.json
yarn.lock

Fixes security notice https://snyk.io/vuln/SNYK-JS-AJV-584908
Closes: #18308

[LTS - 8] fix(@angular-devkit/core): update `ajv` to `6.12.3`

---

packages/angular/cli/lib/init.ts
packages/angular/cli/models/analytics.ts
packages/angular/cli/utilities/json-schema.ts
packages/angular_devkit/architect_cli/bin/architect.ts
packages/angular_devkit/schematics_cli/bin/schematics.ts
packages/ngtools/webpack/src/transformers/make_transform.ts

Most of these changes are requires for TS 4 update

refactor: clean up several files

---

packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
packages/angular_devkit/build_angular/src/angular-cli-files/plugins/any-component-style-budget-checker.ts
packages/angular_devkit/build_angular/src/angular-cli-files/plugins/bundle-budget.ts
packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts
packages/angular_devkit/build_angular/src/angular-cli-files/plugins/optimize-css-webpack-plugin.ts

Initial preparation for Webpack 5 integration.

refactor(@angular-devkit/build-angular): cleanup webpack type usage

---

packages/schematics/schematics/schematic/files/src/my-full-schematic/index_spec.ts

(cherry picked from commit 56c5bce169d57b8f75fb09e64bcb2f8d601d687f)

fix(@schematics/schematics): await expect result in full schematic test

---

packages/angular_devkit/schematics/src/tree/action.ts

fix(@angular-devkit/schematics): set correct parent id in actions lists

---

packages/ngtools/webpack/src/resource_loader.ts

This change allows the result of the stylesheet Webpack compilation to be explicitly available for access after the output source code is generated.  The previous method relied on assumptions within the code generated by Webpack and no longer worked with Webpack 5.

refactor(@angular-devkit/build-angular): use library output for stylesheet child compilations

---

packages/angular_devkit/build_angular/src/angular-cli-files/plugins/optimize-css-webpack-plugin.ts
packages/angular_devkit/build_angular/src/angular-cli-files/plugins/remove-hash-plugin.ts
packages/angular_devkit/build_angular/src/dev-server/index.ts
packages/angular_devkit/build_angular/src/karma/index.ts
packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-plugin.ts
packages/angular_devkit/build_webpack/src/utils.ts
packages/angular_devkit/build_webpack/src/webpack/index.ts
packages/ngtools/webpack/src/angular_compiler_plugin.ts
packages/ngtools/webpack/src/loader.ts
packages/ngtools/webpack/src/ngcc_processor.ts

Several changes to cleanup Webpack usage.  This is an incremental step towards Webpack 5 support.  See individual commits for more details.

Webpack configuration and usage cleanup

---

packages/angular_devkit/schematics/src/engine/schematic.ts
packages/angular_devkit/schematics/src/rules/base.ts
packages/angular_devkit/schematics/tasks/node/index.ts
packages/angular_devkit/schematics/tasks/package-manager/executor.ts
packages/angular_devkit/schematics/tasks/package-manager/install-task.ts
packages/angular_devkit/schematics/tasks/repo-init/executor.ts
packages/angular_devkit/schematics/tasks/run-schematic/executor.ts
packages/angular_devkit/schematics/tasks/tslint-fix/executor.ts
packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts

These changes will support the eventual use of TypeScript's strict option.

Schematic type usage cleanup

---

packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts

Refactoring and minor reorganization to simplify eventual Webpack 5 support.

refactor(@angular-devkit/build-angular): cleanup server webpack configuration

---

packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
packages/angular_devkit/build_angular/src/browser/index.ts
packages/angular_devkit/build_angular/src/extract-i18n/index.ts

fix(@angular-devkit/build-angular): don't log blank warnings in console

---

packages/angular_devkit/schematics_cli/bin/schematics.ts

fix(@angular-devkit/schematics-cli): use workflow to list schematics

---

tests/legacy-cli/e2e/tests/build/multiple-configs.ts

Currently the options are incorrectly set under architect instead of the build target.

test: fix multiple configs e2e test

---

packages/schematics/angular/workspace/files/tsconfig.json.template

Related to https://github.com/angular/angular/issues/38400

feat(@schematics/angular): add `strictInputAccessModifiers` option when using strict mode

---

packages/schematics/schematics/schematic/factory.ts

fix(@schematics/schematics): run install step with sample schematics

---

packages/schematics/angular/guard/files/__name@dasherize__.guard.ts.template

refactor(@schematics/angular): rename guard param of generated file

---

etc/api/angular_devkit/schematics/src/_golden-api.d.ts
packages/angular_devkit/schematics/src/engine/interface.ts
packages/schematics/angular/migrations/update-7/polyfill-metadata.ts
packages/schematics/angular/migrations/update-8/differential-loading.ts
packages/schematics/angular/migrations/update-8/drop-es6-polyfills.ts
packages/schematics/angular/migrations/update-9/schematic-options.ts

This PR continues updating older schematics to use newer utilities and helper functions with the goal to reduce complexity as well as remove older helper code.

Angular schematics cleanup - Part 2

---

packages/schematics/angular/migrations/update-6/index.ts
packages/schematics/angular/migrations/update-7/typescript-helpers.ts
packages/schematics/angular/migrations/update-9/ivy-libraries.ts
packages/schematics/angular/migrations/update-9/remove-tsickle.ts
packages/schematics/angular/utility/config.ts
packages/schematics/angular/utility/workspace.ts

This PR starts updating older schematics to use newer utilities and helper functions with the goal to reduce complexity as well as remove older helper code.

Initial Angular schematics cleanup

---

packages/angular_devkit/build_angular/src/dev-server/index.ts
packages/angular_devkit/build_webpack/src/webpack/index.ts
packages/ngtools/webpack/src/angular_compiler_plugin.ts
packages/ngtools/webpack/src/virtual_file_system_decorator.ts
packages/ngtools/webpack/src/webpack.ts

Refactoring and minor reorganization to simplify eventual Webpack 5 support.

Additional Webpack integration cleanup

---

tests/legacy-cli/e2e/tests/build/platform-server.ts

The `@nguniversal/express-engine` package was previously not added with a prelease version taken into account.
Now when the CLI is in a prelease state, the package will be added using the prelease `next` tag.

test: support prelease versions in platform server E2E

---

packages/angular_devkit/build_angular/src/angular-cli-files/plugins/dedupe-module-resolve-plugin.ts

The structure of the data from the `afterResolve` hook has changed in Webpack 5.  This change provides compatibility for both the Webpack 5+ and Webpack 4 variants.

refactor(@angular-devkit/build-angular): support dedupe plugin with Webpack 5

---

packages/schematics/angular/application/files/karma.conf.js.template
packages/schematics/angular/library/files/karma.conf.js.template

Tiny commit to improve the formatting of the karma conf after the recent modifications for coverage reproters.

style(@schematics/angular): fix formatting of coverage reporters

---

packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts

Webpack 5 uses an object to represent errors and warnings unlike Webpack 4 which used a string.  This change provides support for both scenarios.

refactor(@angular-devkit/build-angular): support Webpack 5 errors/warnings

---

packages/ngtools/webpack/src/angular_compiler_plugin.ts
packages/ngtools/webpack/src/webpack-diagnostics.ts
packages/ngtools/webpack/src/webpack-version.ts

Additional preparation for Webpack 5 integration.

refactor(@ngtools/webpack):  add webpack diagnostic helpers

---

packages/angular_devkit/build_angular/BUILD.bazel
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_angular/src/browser/index.ts
packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts

refactor(@angular-devkit/build-angular): add spinners for localize and downlevelling

---

.yarnrc

Update the vendored version of yarn to the latest version.

build: update to latest version of yarn

---

packages/schematics/angular/migrations/update-9/ngsw-config.ts
packages/schematics/angular/migrations/update-9/remove-tsickle.ts
packages/schematics/angular/migrations/update-9/update-app-tsconfigs.ts
packages/schematics/angular/migrations/update-9/update-server-main-file.ts
packages/schematics/angular/migrations/update-9/update-workspace-config.ts
packages/schematics/angular/utility/workspace.ts

This PR continues updating older schematics to use newer utilities and helper functions with the goal to reduce complexity as well as remove older helper code.

Angular schematics cleanup - Part 3

---

package.json
packages/angular_devkit/build_angular/BUILD.bazel
packages/angular_devkit/build_angular/src/browser/index.ts
packages/angular_devkit/build_angular/src/dev-server/index.ts
packages/angular_devkit/build_angular/src/utils/build-browser-features.ts
packages/angular_devkit/build_angular/src/utils/build-browser-features_spec.ts
packages/angular_devkit/build_angular/src/utils/build-options.ts
packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
packages/angular_devkit/build_angular/src/webpack/configs/common.ts
packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
yarn.lock

refactor(@angular-devkit/build-angular): clean up differential loading config generation

---

packages/angular_devkit/architect_cli/bin/architect.ts

fix(@angular-devkit/architect-cli): remove minimist `_` from options

---

packages/angular_devkit/build_angular/src/webpack/plugins/common-js-usage-warn-plugin.ts

Closes #18895
Should fix all or part of
225 warnings `[DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API`

fix(@angular-devkit/build-angular): fixed Module.issuer is deprecated in webpack 5 for commonjs warn plugin

---

packages/angular_devkit/build_angular/src/webpack/plugins/dedupe-module-resolve-plugin.ts
tests/legacy-cli/e2e/tests/build/ts-paths.ts

fix(@angular-devkit/build-angular): handle undefined descriptionFileData

---

packages/angular_devkit/build_angular/src/webpack/plugins/optimize-css-webpack-plugin.ts

should fix 83 warnings `[DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)`

fix(@angular-devkit/build-angular): fixes optimizeChunkAssets is deprecated in webpack 5

---

.github/dependabot.yml

configure dependabot updates to use the expected commit message type/scope

build: configure dependabot updates

---

packages/angular/cli/models/schematic-command.ts

With this change we use the addUndefinedDefaults transformer post validation and don't create prompts which have a default value when options.defaults is truthy.
Closes: #18692

fix(@angular/cli): don't show deprecation messages for defaults when using `--defaults`

---

packages/angular/cli/models/schematic-command.ts

fix(@angular/cli): don't display prompts twice

---

.circleci/config.yml
packages/angular_devkit/schematics/tasks/package-manager/executor.ts
tests/legacy-cli/e2e/assets/1.0-yarn-workspace-project/packages/app/.angular-cli.json

Please see individual commits.

Additional Yarn E2E test improvements/fixes

---

.circleci/config.yml

ci: remove docs-preview branch filter

---

packages/angular/cli/lib/init.ts

This allows improvements and bugfixes in later versions of the update command to be used in projects with older versions of the Angular CLI that do not have update bootstrapping (<8.3.13).
Fixes #18227

fix(@angular/cli): use newer update command if global version is newer

---

packages/angular_devkit/build_angular/src/tslint/works_spec.ts
packages/angular_devkit/core/src/json/schema/schema.ts

Please see individual commits.

Minor code cleanup in core and build-angular

---

packages/angular_devkit/build_angular/src/dev-server/index.ts

fix(@angular-devkit/build-angular): correctly index and remove `webpack-dev-server/client` in non main chunk

---

packages/schematics/update/update/index.ts
packages/schematics/update/update/index_spec.ts

Patch version of https://github.com/angular/angular-cli/pull/19217

fix(@schematics/update): update fail when using yarn 2.0 protocols

---

packages/angular_devkit/core/node/host.ts

- Remove redundant try/catch block
- Use `mkdir` with `recursive: true` instead of custom implementation

refactor(@angular-devkit/core): clean up NodeJsAsyncHost and NodeJsSyncHost

---

packages/angular_devkit/build_angular/src/app-shell/index.ts
packages/angular_devkit/build_angular/src/browser/index.ts
packages/angular_devkit/build_angular/src/browser/specs/bundle-budgets_spec.ts
packages/angular_devkit/build_angular/src/dev-server/index.ts
packages/angular_devkit/build_angular/src/server/index.ts
packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts
packages/angular_devkit/build_angular/src/utils/spinner.ts
packages/angular_devkit/build_angular/src/webpack/configs/common.ts
packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
tests/legacy-cli/e2e/tests/basic/build.ts
tests/legacy-cli/e2e/tests/basic/e2e.ts
tests/legacy-cli/e2e/tests/basic/rebuild.ts
tests/legacy-cli/e2e/tests/build/poll.ts
tests/legacy-cli/e2e/tests/build/rebuild-css-change.ts
tests/legacy-cli/e2e/tests/build/rebuild-deps-type-check.ts
tests/legacy-cli/e2e/tests/build/rebuild-error.ts
tests/legacy-cli/e2e/tests/build/rebuild-ngfactories.ts
tests/legacy-cli/e2e/tests/build/rebuild-replacements.ts
tests/legacy-cli/e2e/tests/build/rebuild-types.ts
tests/legacy-cli/e2e/tests/misc/live-reload.ts
tests/legacy-cli/e2e/utils/project.ts

fix(@angular-devkit/build-angular): improve builder phase reporting

---

packages/angular_devkit/build_angular/src/dev-server/index.ts

Add new lines to reduce logs clutter.

fix(@angular-devkit/build-angular): reduce clutter in dev-server logs

---

packages/angular/cli/models/command.ts
packages/angular_devkit/core/src/experimental/jobs/simple-scheduler_spec.ts

Please see individual commits.

Initial preparation for TypeScript 4.1 Support

---

tests/legacy-cli/e2e/tests/build/platform-server.ts

Using `@nguniversal/express-engine` requires a lot of maintenance and manual updates to set the correct versions of `@angular-devkit/architect` and `'@angular-devkit/core`.  This is because `@nguniversal/express-engine` can rely on different versions of this packages from the local built versions which would cause package installations failure.

test(@angular-devkit/build-angular): refactor platform server test to use universal schematic

---

packages/angular_devkit/architect/node/node-modules-architect-host.ts

This change allows architect runtime implementations to have more control over how builder information and options for targets are found.  A workspace file (and accompanying definition class) is not necessarily needed now.  This also has benefits for unit testing by reducing the amount of potential setup needed per test.

refactor(@angular-devkit/architect): abstract workspace access from architect

---

etc/api/angular_devkit/schematics/tools/index.d.ts
packages/angular/cli/models/schematic-command.ts
packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
tests/legacy-cli/e2e/tests/generate/module/module-route.ts

Schematic workflow option transforms improvements

---

packages/angular_devkit/schematics_cli/bin/schematics.ts

fix(@angular-devkit/schematics-cli): remove `_` property from options

---

package.json
packages/schematics/angular/utility/latest-versions.ts
yarn.lock

Update zone.js to the latest version of 0.11.3

build: update zone.js to 0.11.3

---

packages/ngtools/webpack/src/ivy/host.ts
packages/ngtools/webpack/src/ivy/paths.ts
packages/ngtools/webpack/src/ivy/plugin.ts
packages/ngtools/webpack/src/ivy/system.ts
packages/ngtools/webpack/src/resource_loader.ts
tests/legacy-cli/e2e/tests/basic/rebuild.ts

This adds additional testing for the basic rebuild test to include a change to an external component stylesheet and an external component template.
Closes: #19461

test(@ngtools/webpack): update rebuild E2E with component resource changes

---

packages/angular_devkit/build_angular/src/browser/specs/source-map_spec.ts
packages/angular_devkit/build_angular/src/webpack/configs/styles.ts

fix(@angular-devkit/build-angular): resolve partial SCSS files in sourcemaps

---

docs/process/release.md
lib/packages.ts
scripts/packages.ts

Now included in the release process is updating the root package.json version.

build: update release process to reflect including updates to package.json

---

packages/angular_devkit/build_webpack/src/webpack/index.ts

The Webpack `Stats.toJson` function can be expensive.  A new programmatic option is now available (`shouldProvideStats`) which can be used to control whether the `webpackStats` property on the builder output object is present.  For backwards compatibility, the option is currently enabled by default.
This is currently unused but will serve as infrastructure for end of build performance improvements.

feat(@angular-devkit/build-webpack): add option for webpack stats output

---

packages/angular_devkit/build_angular/src/utils/spinner.ts

fix(@angular-devkit/build-angular): fix termination of process when using CTRL+C

---

packages/schematics/angular/collection.json

docs: replace appShell with app-shell

---

packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts

fix(@angular-devkit/build-angular): update ScriptsWebpackPlugin to work with Webpack 5

---

packages/angular_devkit/build_angular/src/webpack/plugins/optimize-css-webpack-plugin.ts

fix(@angular-devkit/build-angular): add file path in CSS optimization exception

---

packages/angular/cli/commands/definitions.json
packages/angular/cli/lib/config/schema.json
packages/angular_devkit/build_angular/src/browser/schema.json
packages/angular_devkit/build_angular/src/dev-server/schema.json
packages/angular_devkit/build_angular/src/karma/schema.json
packages/angular_devkit/build_angular/src/server/schema.json
tests/angular_devkit/core/json/schema/serializers/schema_benchmark.json

The latter is more in used in other articules such as:
-  https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map
- https://developers.google.com/web/tools/chrome-devtools/javascript/source-maps

Schema docs fixes 

---

packages/schematics/angular/application/files/src/polyfills.ts.template
packages/schematics/angular/migrations/update-8/drop-es6-polyfills_spec.ts

https://github.com/Microsoft/tslint-microsoft-contrib
ERROR: 21:1  **no-single-line-block-comment**  Replace block comment with a single-line comment

fix(@schematics/angular): adjust block comment 

---

packages/angular_devkit/build_angular/src/webpack/plugins/hmr/hmr-accept.ts

fix(@angular-devkit/build-angular): add console error when using HMR in production mode

---

packages/schematics/update/update/index.ts

fix grammar typo in note about additional packages  from #18888

fix(@schematics/update): fix typo in info log

---

packages/angular_devkit/build_angular/src/webpack/plugins/karma.ts

This changes the internal Angular Karma plugin's asset fallback middleware to rewrite the request URL directly instead of trying to copy the request properties.  With changes in newer Node.js versions, not all request properties may be enumerable.
Fixes: #19644

fix(@angular-devkit/build-angular): use URL rewrite in karma fallback middleware

---

packages/angular/cli/lib/config/schema.json
packages/angular_devkit/build_angular/src/browser/schema.json
packages/angular_devkit/build_angular/src/dev-server/schema.json
packages/angular_devkit/build_angular/src/karma/schema.json
packages/angular_devkit/build_angular/src/server/schema.json

https://next.angular.io/guide/workspace-config#source-map-configuration
https://next.angular.io/guide/workspace-config#optimization-configuration

docs: update optimization and sourceMap descriptions with new links

---

tests/legacy-cli/e2e/tests/build/styles/symlinked-global.ts

test(@angular-devkit/build-angular): fix symlink tests on windows
https://app.circleci.com/pipelines/github/angular/angular-cli/12344/workflows/8f9a6efd-818e-492d-81f7-3395067018cd/jobs/216073

test(@angular-devkit/build-angular): fix symlink tests on windows

---

packages/angular_devkit/build_angular/src/karma/schema.json

Reverts angular/angular-cli#19657
Closes #19735

Revert "docs: add default value for karma watch option"

---

.yarnrc

Update to the latest version of yarn.

build: update to yarn v1.22.10

---

packages/angular/cli/models/schematic-command.ts

while I was making myself familiar with the code-base
to solve an open issue, I saw this super minor typo
and decided to fix it

refactor(@angular/cli): fix super minor typo

---

packages/angular/cli/commands/doc-impl.ts

fix(@angular/cli): remove unnecessary promise around "open"

---

packages/ngtools/webpack/src/resource_loader.ts

This change reduces the complexity of the component resource loader caching as well as moves the caching check earlier in the workflow to further minimize the amount of processing needed.

fix(@ngtools/webpack): improve resource loader caching

---

tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts

When installing an outdated version of `@schematics/angular`, the package manager will also analyze installed dependencies.  In the case of a release commit those dependencies are not yet on the npm registry and the outdated package install will fail. To remedy this situation, the outdated package and its two dependencies are published to the local test registry which allows the unreleased versions of the tooling packages to also be available to the package manager.

test(@angular/cli): allow invalid deps E2E to pass on release commits

---

packages/schematics/angular/workspace/files/package.json.template

feat(@schematics/angular): update new project dependencies versions

---

packages/schematics/angular/application/other-files/app.component.html.template

remove augury
add youtube to social links
replace gitter with discord

fix(@schematics/angular): update ng new links

---

package.json
packages/angular/cli/BUILD.bazel
packages/angular/cli/lib/cli/index.ts
packages/angular/cli/models/analytics-collector.ts
packages/angular/cli/models/analytics.ts
packages/angular/cli/models/command-runner.ts
packages/angular/cli/models/version.ts
packages/angular/cli/package.json
yarn.lock

With this change we remove the dependency on the unmaintained universal-analytics package. We also solve several package deprecation warnings when creating a new workspace.
Closes #16952

refactor(@angular/cli): remove dependency on universal-analytics

---

packages/angular_devkit/build_angular/src/app-shell/app-shell_spec.ts

The test now waits until the express server is listening and uses a try/finally block to ensure the server is shutdown.
The test server also only now binds to localhost and lets the OS choose a port. This provides better support for running multiple tests in parallel.

test(@angular-devkit/build-angular): improve reliability of app-shell server-worker test

---

packages/angular_devkit/build_angular/src/webpack/configs/styles.ts

Webpack styles configuration refactor and cleanup

---

packages/angular/cli/lib/config/schema.json

fix(@angular/cli): remove `project` from required properties in ng-packagr schema

---

packages/ngtools/webpack/src/ivy/plugin.ts

This change uses the newly introduced precalculated file dependencies for each TypeScript file instead of querying TypeScript for the SourceFile's dependencies when performing the unused file check at the end of the build cycle. This change removes the need to recalculate the dependencies for each TypeScript file present in the Webpack compilation.

perf(@ngtools/webpack): use precalculated dependencies in unused file check

---

packages/angular_devkit/build_angular/src/webpack/plugins/analytics.ts

Webpack's `Stats.toJson` function is an expensive operation and is recommended to be avoided where possible. In the case of the analytics plugin, the chunks and assets can be accessed directly from the Webpack compilation.

perf(@angular-devkit/build-angular): remove Webpack Stats.toJson usage in analytics plugin

---

tests/legacy-cli/e2e/tests/update/update-8.ts

This commit changes the update-8 E2E test to use the recommended update procedure of updating one major version at a time.

test(@angular/cli): fully test update process in update from v8 E2E

---

tests/legacy-cli/e2e/tests/generate/component/component-path-case.ts

Windows CI is failing when trying to use the common test cleanup routine for the `generate/component/component-path-case` E2E test. This fix manually removes the newly created directory within the test.

ci: fix component-path-case E2E test on Windows CI

---

package.json
packages/schematics/angular/utility/latest-versions.ts

build: bump version to v12.0.0-next.7

---

package.json
packages/schematics/angular/utility/latest-versions.ts

build: bump version to v11.2.7

---

packages/angular/cli/models/schematic-engine-host.ts
packages/angular/cli/src/commands/update/schematic/index.ts
tests/legacy-cli/e2e/tests/update/update-8.ts

Update refactor fixes and improvements

---

.circleci/config.yml

See: https://github.com/angular/angular/commit/381ea9d7d4c88f75260dcc616822fc334ea700a8

ci: use new method for checking range of commits

---

CONTRIBUTING.md
package.json
yarn.lock

Update `@angular/dev-infra-private` package to the latest version.

build: update `@angular/dev-infra-private` package

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_angular/src/webpack/plugins/optimize-css-webpack-plugin.ts
yarn.lock

build: update to `cssnano` to version `5.0.0`

---

packages/angular_devkit/schematics_cli/README.md
packages/angular_devkit/schematics_cli/bin/schematics.ts

This commit adds a README for the package.

docs(@angular-devkit/schematics-cli): Add README

---

packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts

Webpack 5 now uses a `chunkHash` hook that is accessible from `JavascriptModulesPlugin.getCompilationHooks()`. The `hashForChunk` hooks have been deprecated in Webpack 5.

fix(@angular-devkit/build-angular): replace Webpack 4 `hashForChunk` hook usage

---

packages/ngtools/webpack/src/ivy/plugin.ts
packages/ngtools/webpack/src/resource_loader.ts

Improve resource loader performance

---

packages/angular/cli/commands/e2e.json

Removing reference to protractor from e2e command

docs: remove reference to protractor.

---

packages/angular/cli/commands/e2e-impl.ts
packages/schematics/angular/application/index.ts
packages/schematics/angular/e2e/index.ts
packages/schematics/angular/ng-new/index_spec.ts
packages/schematics/angular/workspace/files/README.md.template
packages/schematics/angular/workspace/files/package.json.template
tests/legacy-cli/e2e/utils/project.ts

Do not include Protractor for new projects since we do not have a concrete plan for Protractor yet.
Closes https://github.com/angular/angular-cli/issues/18844

refactor(@schematics/angular): Do not include Protractor test in new project

---

packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
packages/schematics/angular/application/index.ts
packages/schematics/angular/application/index_spec.ts
packages/schematics/angular/application/schema.json
packages/schematics/angular/component/schema.json
packages/schematics/angular/ng-new/schema.json

Deprecate stylus

---

packages/ngtools/webpack/src/ivy/plugin.ts

Webpack 5 contains improved types and exports that reduce the need to perform additional type casting throughout the Angular Webpack Plugin.

refactor(@ngtools/webpack): remove Webpack 4 specific type casting

---

packages/schematics/angular/README.md

Universal and E2E schematics are hidden/private.

docs(@schematics/angular): remove hidden schematics from readme

---

packages/angular_devkit/build_angular/src/ng-packagr/works_spec.ts

(cherry picked from commit a8ff9d408b82ff73b79ae2d3441510a3286bca82)
This fixes CI

test(@angular-devkit/build-angular): add `debounceTime` to stabilize FS

---

packages/ngtools/webpack/src/ivy/plugin.ts

Angular Webpack plugin small performance enhancements

---

packages/schematics/angular/migrations/update-12/remove-emit-decorator-metadata.ts
packages/schematics/angular/migrations/update-12/remove-emit-decorator-metadata_spec.ts

Removal of `emitDecoratorMetadata` might cause runtime errors on projects which don't use the Angular Compiler to compile TypeScript code and therefore dependent on Decorators metadata during runtime.  One such example of these builders is `@nrwl/jest`.

fix(@schematics/angular): only run `emitDecoratorMetadata` removal migration in safe workspaces

---

package.json
packages/angular_devkit/build_angular/package.json
tests/legacy-cli/e2e/tests/build/styles/node-sass.ts
yarn.lock

fix(@angular-devkit/build-angular): update dependency resolve-url-loader to v4

---

packages/angular/cli/commands/e2e-impl.ts

Add Cypress schematic/builder, see
https://github.com/cypress-io/cypress/tree/master/npm/cypress-schematic
and
https://www.npmjs.com/package/@cypress/schematic

docs(@angular/cli): Add Cypress schematic to e2e command

---

packages/angular_devkit/build_angular/src/webpack/configs/common.ts

fix(@angular-devkit/build-angular): add experimental web-assembly

---

package.json
packages/angular/cli/package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

fix(@angular-devkit/build-angular): revert open to 8.0.2

---

packages/angular_devkit/build_angular/src/dev-server/schema.json

docs(@angular-devkit/build-angular): add more info link to `proxyConfig`

---

.ng-dev/config.ts
.ng-dev/release.ts
scripts/build.ts

Note: This does not update the instructions for releasing yet as we are not yet using this for releases.

build: set up releasing using ng-dev

---

packages/ngtools/webpack/src/ivy/plugin.ts

When not in a watch mode, the analyis performed by TypeScript to improve incremental type checking can be avoided by creating an abstract builder program that only wraps the underlying TypeScript program.
Performance enhancements in the upcoming TypeScript 4.3 may remove the need for this.  However, TypeScript 4.3 is not yet released and is not yet supported. In addition, TypeScript 4.2 will continue to be supported throughout the v12 major even when TypeScript 4.3 is also supported.

perf(@ngtools/webpack): reduce non-watch mode TypeScript diagnostic analysis overhead

---

packages/angular_devkit/build_angular/src/browser/tests/options/inline-style-language_spec.ts
packages/ngtools/webpack/src/ivy/host.ts
packages/ngtools/webpack/src/resource_loader.ts

fix(@angular-devkit/build-angular): ensure latest inline stylesheet data is used during rebuilds

---

packages/angular/cli/utilities/install-package.ts

fix(@angular/cli): ng update on windows to allow path

---

packages/angular_devkit/build_angular/src/extract-i18n/index.ts

fix(@angular-devkit/build-angular): allow  i18n extraction on application that uses web-workers

---

packages/angular_devkit/build_angular/src/webpack/configs/common.ts

fix(@angular-devkit/build-angular): resolve absolute outputPath properly

---

lib/packages.ts

This is to match the supported versions by the framework https://github.com/angular/angular/pull/42205
Closes #20796

fix(@angular/cli): update supported range of node versions to be less restrictive

---

goldens/public-api/angular_devkit/core/src/_golden-api.d.ts
packages/angular/cli/models/architect-command.ts
packages/angular_devkit/core/src/experimental/jobs/simple-scheduler_spec.ts
packages/angular_devkit/core/src/json/schema/interface.ts
packages/angular_devkit/core/src/json/schema/registry.ts
packages/angular_devkit/core/src/json/schema/registry_spec.ts
packages/angular_devkit/core/src/virtual-fs/host/memory_spec.ts
packages/angular_devkit/core/src/workspace/core_spec.ts
packages/angular_devkit/core/src/workspace/host_spec.ts

Fix several @angular-devkit/core issues

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

This includes https://github.com/xz64/license-webpack-plugin/pull/102

perf(@angular-devkit/build-angular): update `license-webpack-plugin` to `2.3.19`

---

packages/angular_devkit/core/node/host.ts
packages/angular_devkit/core/node/host_spec.ts

submit a new PR replace #20997 use a feature branch

fix(@angular-devkit/core): transform path using getSystemPath for NodeJsAsyncHost's `exists` method

---

packages/ngtools/webpack/src/resource_loader.ts

The size of the cache could grow quite large over long active development periods. Webpack 5 memory caching will also allow for caching of the data.
12.0.x variant of #20974

[12.0.x]fix(@ngtools/webpack): remove redundant inline style cache

---

packages/angular/cli/utilities/install-package.ts

fix(@angular/cli) escape paths using double quotes

---

packages/angular_devkit/build_angular/package.json
packages/ngtools/webpack/package.json

build: update peerDependencies to support `^12.1.0-next`

---

.gitignore
.ng-dev/release.ts
lib/packages.ts

build: create a listing of the packages which are released.

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_optimizer/package.json
packages/angular_devkit/build_webpack/package.json
packages/ngtools/webpack/package.json
yarn.lock

This includes fixes to reduce memory usage.

build: update wepack to version 5.39.1

---

packages/angular/cli/src/commands/update/schematic/npm.ts
packages/angular/cli/utilities/package-metadata.ts

Patch version of https://github.com/angular/angular-cli/pull/21140

fix(@angular/cli): handle unscoped authentication details in .npmrc 

---

packages/schematics/angular/application/other-files/app.component.html.template

Adds Angular DevTools and link to the resources list of ng new

fix(@schematics/angular): add devtools to ng new

---

packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts

With this change we cache JavaScriptOptimizerPlugin results in memory or on the file system based on the caching strategy used.

perf(@angular-devkit/build-angular): cache JavaScriptOptimizerPlugin results

---

packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts

This reverts commit 47a1ccc50729ad25e4fa4e38704c8dbd3b1737f7.

Revert "refactor: disable esbuild worker threads"

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_optimizer/package.json
packages/angular_devkit/build_webpack/package.json
packages/ngtools/webpack/package.json
yarn.lock

- fix a memory leak in the unsafe cache

build: update `webpack` to `5.42.0`

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

build: update `license-webpack-plugin` to `2.3.20`

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_optimizer/package.json
packages/angular_devkit/build_webpack/package.json
packages/ngtools/webpack/package.json
yarn.lock

Related change https://github.com/webpack/webpack/releases/tag/v5.42.1
Closes #21349

build: update webpack to 5.44.0

---

.ng-dev/release.ts

Update the configuration for releasing via ng-dev.

build: update ng-dev configuration for release

---

package.json
yarn.lock

Update version of @angular/dev-infra-private.

build: update to the latest @angular/dev-infra-private

---

package.json
yarn.lock

(cherry picked from commit 78cb7a2dcb20999f7f1efed9e196584acdc6e222)

build: update @angular/dev-infra-private commit hash to 6df6965

---

renovate.json

Reverts angular/angular-cli#21376
See:https://github.com/angular/angular-cli/pull/21376#discussion_r675423514

Revert "build: update renovate to update @angular/dev-infra-private as target: patch"

---

packages/angular/cli/utilities/package-metadata.ts

fix(@angular/cli): merge npmrc files values

---

packages/angular/cli/commands/e2e-long.md

Used for https://angular.io/cli/e2e

docs(@angular/cli): update e2e long description

---

packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts

fix(@angular-devkit/build-angular): avoid attempting to optimize copied JavaScript assets

---

packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
packages/angular_devkit/build_angular/src/builders/extract-i18n/index.ts
packages/angular_devkit/build_angular/src/builders/protractor/index.ts
packages/angular_devkit/build_angular/src/builders/server/index.ts
packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts

Additional cleanup of `build-angular` helper utilities

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_optimizer/package.json
packages/angular_devkit/build_webpack/package.json
packages/ngtools/webpack/package.json
yarn.lock

To benefit from a number of performance related fixes.

build: update `webpack` to `5.50.0`

---

renovate.json

Update renovate config to allow GitHub workflow updates

ci: configure renovate to manage GitHub workflow updates

---

.ng-dev/config.ts
.ng-dev/pull-request.ts

More info: https://github.com/angular/dev-infra/commit/c3f5729376048af3ce939a505e5389dba11ff7d2

build: replace ng-dev MergeConfig wiith PullRequestConfig

---

packages/angular_devkit/build_angular/src/babel/presets/application.ts
packages/angular_devkit/build_angular/src/utils/i18n-options.ts

Previously, the search for a locale's data when using i18n was performed by a series of file system accesses that searched through the `@angular/common` package. The search is now conducted via Node.js module resolution which has several advantages. The internal structure of the package is no longer assumed and allows the `@angular/common` package to change its internal implementation without affecting the locale data search. File extensions of the locale data files are also not hard-coded as only the name of the locale data is needed to perform a search. There are also less direct file system access calls and the search can leverage whatever internal caching Node.js performs during module resolution.
A Babel webpack loader specific `@angular/localize` package `Diagnostics` object is now …

Additional `@angular/localize` ESM support improvements

---

.yarnrc

Update to the latest version of yarn, 1.22.17.

build: update to yarn v1.22.17

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_webpack/package.json
yarn.lock

This contains several fixes that have been reported in the CLI repo.

build: update `webpack` to `5.64.1`

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

Patch version of https://github.com/angular/angular-cli/pull/22151

build: update dependency license-webpack-plugin to v4

---

packages/schematics/angular/application/files/src/test.ts.template
packages/schematics/angular/library/files/src/test.ts.template

fix(@schematics/angular): address eslint linting failures in `test.ts`

---

package.json
packages/angular/cli/package.json
yarn.lock

This addresses a security vulnerability.
Closes #22233

fix(@angular/cli): update `pacote` to `12.0.2`

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

Closes #22280
Already updated on master via https://github.com/angular/angular-cli/pull/22263

build: update `@ampproject/remapping` to `1.0.2`

---

packages/angular/cli/README.md

This section is outdated.
Closes #20336

docs: update CPU profiling section

---

.circleci/config.yml
.ng-dev/pull-request.ts
.ng-dev/release.ts
.ng-dev/tsconfig.json
package.json
yarn.lock

Adds a CI tests to verify that we don't merge accident breaking changes

build: check ng-dev tool configuration in CI

---

packages/angular_devkit/build_angular/src/webpack/configs/common.ts

fix(@angular-devkit/build-angular): correctly resolve `core-js/proposals/reflect-metadata`

---

packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts

After the webpack-dev-server migration to v4, the websocket client was always injected, even if not required. This caused unnecessary 'ws' requests when live-reload and hmr were disabled.
This PR modifies the building of the webpack-dev-server configuration to configure the websocket client only if either live-reload is enabled or hmr.

fix(@angular-devkit/build-angular): websocket client only injected if required

---

packages/schematics/angular/workspace/files/__dot__gitignore.template

Updated casings so all categories starts with a capital letter and did some small reorganizations

refactor(@schematics/angular): changed casings and small reorganizing

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

Cherry-pick of https://github.com/angular/angular-cli/pull/22179

build: update dependency postcss-preset-env to v7

---

.github/workflows/feature-requests.yml

Add feature request voting process github actions to the repo.

build: add an action for handling feature requests

---

packages/angular_devkit/core/src/json/schema/registry.ts
packages/angular_devkit/core/src/json/schema/transforms.ts
packages/angular_devkit/core/src/json/schema/transforms_spec.ts

fix(@angular-devkit/core): correctly resolve schema references defaults

---

packages/angular/cli/src/command-builder/utilities/json-help.ts

With this change we remove the JSON serialized description from the help output and also align the description properties between commands and subcommands.
<details>
<summary markdown="span">add.json</summary>
```json
{
"name": "add",
"command": "ng add <collection>",
"shortDescription": "Adds support for an external library to your project.",
"longDescriptionRelativePath": "@angular/cli/src/commands/add/long-description.md",
"longDescription": "Adds the npm package for a published library to your workspace, and configures\nthe project in the current working directory (or the default project if you are\nnot in a project directory) to use that library, as specified by the library's schematic.\nFor example, adding `@angular/pwa` configures your project for PWA support:\n\n```bash\nng add …

fix(@angular/cli): remove JSON serialized description from help output

---

package.json

We won't actually be releasing an RC, but this is necessary for the release tool to understand that it will do a minor release from this branch.

refactor: bump CLI version to `13.3.0-rc.0`

---

packages/angular/cli/src/analytics/analytics.ts
packages/angular/cli/src/command-builder/schematics-command-module.ts
packages/angular/cli/src/utilities/package-manager.ts
packages/angular/cli/src/utilities/prompt.ts
packages/angular_devkit/build_angular/src/utils/check-port.ts

With this change we reduce the time that is needed to bootstrap the CLI by ~200ms
Before
```
time ng b --help  1.65s
```
After
```
time ng b --help  1.49s
```

Improve CLI bootstrapping time

---

lib/bootstrap-local.js
packages/angular/cli/src/commands/analytics/cli.ts
packages/angular/cli/src/commands/analytics/info/cli.ts
packages/angular/cli/src/commands/analytics/settings/cli.ts
packages/angular/cli/src/commands/doc/cli.ts
packages/angular/cli/src/commands/e2e/cli.ts

…calration
fix(common): improved the code quality and removed the unnecessary decalration in cli.ts file

refactor(@angular/cli): improved code quality 

---

packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts

fix(@angular-devkit/build-webpack): emit devserver setup errors

---

packages/angular_devkit/core/src/experimental/jobs/strategy.ts

This is not needed as inputs are typed checked to be `JsonValue`. With this change we get a step closer to remove `fast-json-stable-stringify` dependency.

refactor(@angular-devkit/core): remove `fast-json-stable-stringify` usage in memoize helper

---

CHANGELOG.md
tests/legacy-cli/e2e/tests/build/prod-build.ts

Cherry-picks the changelog from the "13.3.x" branch to the next branch (master).

docs: release notes for the v13.3.3 release

---

goldens/public-api/angular_devkit/schematics/tools/index.md
packages/angular/cli/src/command-builder/schematics-command-module.ts
packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
packages/angular_devkit/schematics/tools/schema-option-transform.ts
packages/angular_devkit/schematics/tools/workflow/node-workflow.ts

Support null for options parameter from OptionTransform type

---

.circleci/config.yml

Preparation for the framework repo as outlined our planning
document.

[11.2.x] build: preparation for primary branch rename in the Angular repos

---

.circleci/config.yml

Preparation for the framework repo as outlined our planning
document.

[12.2.x] build: preparation for primary branch rename in the Angular repos

---

.circleci/config.yml
.github/workflows/scorecard.yml

Preparation for the framework repo as outlined our planning
document.

build: preparation for primary branch rename in the Angular repos

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

fix(@angular-devkit/build-angular): update `@ampproject/remapping` to `2.2.0`

---

packages/angular_devkit/build_angular/test/hello-world-app/src/test.ts
packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/src/test.ts
packages/schematics/angular/application/files/src/test.ts.template
packages/schematics/angular/library/files/src/test.ts.template
tests/legacy-cli/e2e/assets/10.0-project/src/test.ts

refactored the code and removed the code smells

refactor(@angular/cli): refactored the code and removed the code smells

---

goldens/public-api/angular_devkit/schematics/tools/index.md
package.json
packages/ngtools/webpack/package.json
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
yarn.lock

Bumps up the repo to the RC version of TypeScript 4.7.

build: update to TypeScript 4.7 RC

---

packages/angular_devkit/build_angular/src/webpack/plugins/css-optimizer-plugin.ts
packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts

This can be useful to debug slow builds.
Example of output
```
LOG from build-angular.JavaScriptOptimizerPlugin
<t> optimize asset: runtime.ad5c30339e926c89.js: 221.959564 ms
<t> optimize asset: polyfills.ec3ffae5bac27204.js: 1071.080092 ms
<t> optimize asset: main.aa8a15155ca2133f.js: 3391.588635 ms
<t> optimize js assets: 3483.799739 ms
LOG from build-angular.CssOptimizerPlugin
<t> optimize asset: styles.d251c5bf54715558.css: 26.569907 ms
<t> optimize css assets: 34.441737 ms
```
```
LOG from build-angular.JavaScriptOptimizerPlugin
<i> polyfills.ec3ffae5bac27204.js restored from cache.
<i> runtime.ad5c30339e926c89.js restored from cache.
<t> optimize asset: main.69fb55a243b46bfa.js: 2618.5191210000003 ms
<t> optimize js assets: 2721.226144 ms
LOG from build-angular.CssOptimizerPlugin …
```

fix(@angular-devkit/build-angular): add debugging and timing information in JavaScript and CSS optimization plugins

---

.circleci/env.sh

build: update saucelabs key

---

tests/legacy-cli/e2e_runner.ts

I found this useful while debugging anything npm related...

test: keep npm servers alive while in debug state

---

tests/legacy-cli/e2e/tests/commands/completion/completion-prompt.ts
tests/legacy-cli/e2e/tests/commands/completion/completion-script.ts
tests/legacy-cli/e2e/tests/commands/completion/completion.ts

test(@angular/cli): move `completion` command test in own directory

---

package.json
packages/angular_devkit/build_angular/package.json
packages/ngtools/webpack/package.json
yarn.lock

Only stable versions are officially supported.

fix(@angular-devkit/build-angular): update Angular peer dependencies to 14.0 stable

---

tests/legacy-cli/e2e/setup/002-npm-sandbox.ts
tests/legacy-cli/e2e/tests/misc/ask-missing-builder.ts
tests/legacy-cli/e2e/tests/misc/e2e-host.ts
tests/legacy-cli/e2e/tests/misc/proxy-config.ts
tests/legacy-cli/e2e/tests/misc/title.ts
tests/legacy-cli/e2e/utils/git.ts
tests/legacy-cli/e2e/utils/test_process.ts
tests/legacy-cli/e2e_runner.ts
tests/legacy-cli/tsconfig.json

Clean up E2E tests

---

.circleci/config.yml
tests/legacy-cli/e2e/utils/process.ts

See each commit. 
Green run https://app.circleci.com/pipelines/github/angular/angular-cli/23222/workflows/8afc60f4-ed0b-4158-b48f-0904e8855b76/jobs/308980/parallel-runs/7?filterBy=ALL
FYI: @jbedard

Windows E2E CI fixes

---

packages/angular/cli/BUILD.bazel
packages/angular_devkit/architect/BUILD.bazel
packages/angular_devkit/core/BUILD.bazel
packages/angular_devkit/schematics/BUILD.bazel

(cherry picked from commit 1e21440c10066d771066ac5eed195d749384d45f)

build: mark external only bazel rules

---

packages/ngtools/webpack/src/ngcc_processor.ts

Prior to this change the CLI would fail with an error when ngcc could not
be run due to a missing `node_modules` directory, as is the case with Yarn
Plug'n'Play for example. The workaround was to create an empty `node_modules`
directory, but this is inconvenient and shouldn't make any difference.
This commit removes the error and simply skips ngcc processing.

fix(@ngtools/webpack): do not run ngcc when `node_modules` does not exist

---

tests/legacy-cli/e2e/tests/build/styles/include-paths.ts

These are causes Windows CI to fail.

test: add missing `await` to float promises

---

packages/angular_devkit/build_angular/src/builders/dev-server/specs/live-reload_spec.ts

- assign dynamic port to proxy server
- remove RXJS `finalize` in favor of `finally`

test: update live-reload test to reduce flakes 

---

CHANGELOG.md
package.json

Trying again since the last attempt failed due to a connection issue.

Bump version to "v14.1.0-rc.0" with changelog.

---

.circleci/dynamic_config.yml
.circleci/env.sh

Circle config clean up

---

packages/angular_devkit/build_angular/test/hello-world-app/angular.json
packages/angular_devkit/build_webpack/test/angular-app/angular.json
packages/angular_devkit/build_webpack/test/basic-app/angular.json

This causes logs to be printed during test runs.

test(@angular-devkit/build-angular): remove invalid project extensions from test projects

---

tests/legacy-cli/e2e_runner.ts

test: add shard and test type/name information to test logging

---

packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/serve-live-reload-proxies_spec.ts

With this change we replace the live-reload proxy tests to use the new test harness. This is an effort to reduce the flakiness of these tests.

test(@angular-devkit/build-angular): re-write live-reload tests to use new test harness.

---

package.json
packages/angular_devkit/build_angular/BUILD.bazel
packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
scripts/validate-licenses.ts
yarn.lock

Patch specific PR for https://github.com/angular/angular-cli/pull/23626 to resolve `yarn.lock` merge conflict.

build: remove dependency on font-awesome

---

package.json
packages/angular_devkit/architect_cli/bin/architect.ts
packages/angular_devkit/architect_cli/package.json
packages/angular_devkit/benchmark/package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/schematics_cli/package.json
yarn.lock

(cherry picked from commit db047b22e31ee196792636ee3349e3033ded0f49)

build: update all non-major dependencies

---

.circleci/dynamic_config.yml

ci: re add `test-browsers` step

---

package.json

Attempt to solve Windows E2E flakes

ci: update `ChromeDriver` to `104.0.5112.79`

---

packages/angular/cli/lib/config/workspace-schema.json
packages/angular/cli/src/analytics/analytics.ts
tests/legacy-cli/e2e/tests/misc/ask-analytics-command.ts

Swapping `anonymous` for `pseudonymous` to align with privacy communication guidelines.

refactor(@angular/cli): update analytics prompt copy

---

package.json
yarn.lock

update to the latest version of ng-dev

build: update ng-dev version

---

packages/angular_devkit/build_angular/src/webpack/configs/styles.ts

With this change we add a warning when using deprecated tilde/`~` imports.

fix(@angular-devkit/build-angular): issue warning when using deprecated tilde imports

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

Closes https://github.com/angular/angular-cli/issues/23857

build: update `webpack-dev-server` to `4.11.0`

---

packages/ngtools/webpack/src/ivy/transformation.ts

To support AOT compilation the Angular bootstrap call needs to be converted from using `platform-browser-dynamic` to `platform-browser`. This transform was previously being executed against every source file within the program regardless of the presence of `platformBrowserDynamic`. An initial check is now performed that can avoid AST traversal when the bootstrapping call is not present in a file.

perf(@ngtools/webpack): avoid bootstrap conversion AST traversal where possible

---

package.json
yarn.lock

Update to saucelabs connect 4.8.1

build: update saucelabs connect version

---

packages/angular_devkit/build_angular/BUILD.bazel
packages/angular_devkit/build_angular/src/builders/app-shell/app-shell_spec.ts
tests/legacy-cli/e2e/tests/build/app-shell/app-shell-with-schematic.ts
tests/legacy-cli/e2e/tests/build/app-shell/app-shell-with-service-worker.ts

This particular unit tests was really an e2e test.

test(@angular-devkit/build-angular): rewrite app-shell unit test into e2e

---

packages/angular_devkit/build_angular/src/webpack/plugins/typescript.ts

Remove redundant switch statement.

refactor(@angular-devkit/build-angular): simplify configuration of `inlineStyleFileExtension`

---

.circleci/dynamic_config.yml

This should fix that branches with slashes are causing failures

build: update dev-infra orb for recent rebase command fixes

---

.circleci/dynamic_config.yml

CI build-bazel-e2e fix

---

packages/angular_devkit/build_angular/src/webpack/configs/styles.ts

This change add a Sass File importer that uses Webpack resolvers to better support scenarios when node packages are not stored in node_modules, such as Yarn PNP.

fix(@angular-devkit/build-angular): support Yarn PNP resolution in modern SASS API

---

packages/angular/cli/src/commands/completion/long-description.md

docs(@angular/cli): update platform support information in auto-completion

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
packages/angular_devkit/build_angular/src/builders/browser/specs/scripts-array_spec.ts
packages/angular_devkit/build_angular/src/builders/browser/tests/options/scripts_spec.ts
packages/angular_devkit/build_angular/src/builders/browser/tests/options/styles_spec.ts
packages/angular_devkit/build_angular/src/webpack/configs/common.ts
packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts
packages/angular_devkit/build_angular/src/webpack/plugins/styles-webpack-plugin.ts
packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts

With this change scripts and styles options better support Yarn PNP resolution.
Closes #23568

fix(@angular-devkit/build-angular): handle conditional exports in `scripts` and `styles` option

---

packages/angular_devkit/core/src/workspace/json/reader.ts

- [ x ] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ x ] Bugfix
When logging invalid project extensions, the project name is identified to make it easier to determine which project is malformed in a large workspace
- [ x ] No

fix(@angular-devkit/core): project extension warning message should identify concerned project

---

goldens/public-api/angular_devkit/core/index.md
packages/angular_devkit/core/src/logger/logger.ts
packages/angular_devkit/core/src/utils/partially-ordered-set.ts
packages/angular_devkit/core/src/utils/strings.ts
packages/angular_devkit/core/src/utils/template.ts
packages/angular_devkit/core/src/virtual-fs/host/memory.ts
packages/angular_devkit/schematics/src/sink/sink.ts
packages/angular_devkit/schematics/src/tree/scoped.ts
packages/schematics/angular/utility/ast-utils.ts

Currently, builds happen without strictNullChecks enabled in TS compiler. This change enables that.

refactor(@angular/cli) Address issues and enable strictNullChecks.

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts

The Sass preprocessor's modern API will generate absolute file URLs for the `sources` field of generated sourcemaps. These URLs will not be properly processed by esbuild and will not be correctly adjusted to be relative to the workspace root directory for the built application. To correct this behavior, the Sass generated sourcemaps are now adjusted to remove the `file:` protocol prefix and to make each path relative to its input file. This allows esbuild to properly resolve and process the paths.

fix(@angular-devkit/build-angular): use relative sourcemap source paths for Sass in esbuild builder

---

packages/schematics/angular/universal/index_spec.ts

A test has a wrong description, and some have typos.
Description and typos fixed.

test(@schematics/angular): test names typos

---

docs/design/analytics.md
packages/angular/cli/src/analytics/analytics-parameters.ts
scripts/validate-user-analytics.ts

Page views are no longer used in GA4.

docs: remove page view section from analytics doc

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts

When using the experimental esbuild-based browser application builder in watch mode, the in-memory incremental caching will now use Uint8Arrays where possible to limit the amount of encoding needed when passing data to esbuild. When passing a string to esbuild, it must encode the string prior to sending it. By providing the pre-encoded data from the in-memory cache, this step can be skipped for rebuilds of input files that have not changed.

perf(@angular-devkit/build-angular): use Uint8Arrays for incremental caching with esbuild-based builder

---

docs/design/analytics.md
packages/angular/cli/src/analytics/analytics-collector.ts
packages/angular/cli/src/analytics/analytics-parameters.ts
packages/angular/cli/src/command-builder/command-module.ts

Add workspace info and user id to analytics 

---

.github/workflows/scorecard.yml

RC specific cherry pick of https://github.com/angular/angular-cli/pull/24175.

build: update github/codeql-action action to v2.1.30

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts

When using the experimental esbuild-based browser application builder with the `fileReplacements` option,
TypeScript missing compilation file errors will now contain a note that the requested file was a
replacement for another file and show the path of the file.

fix(@angular-devkit/build-angular): show file replacement in TS missing file error in esbuild builder

---

.circleci/config.yml
tests/legacy-cli/e2e/tests/commands/add/version-specifier.ts
tests/legacy-cli/e2e/tests/update/update-9.ts

This is easier to manage from Circle CI UI and align with the version 14.2.x branch setup
See: https://circleci.com/docs/scheduled-pipelines/?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--emea-en-dsa-maxConv-auth-nb&utm_term=g_-_c__dsa_&utm_content=&gclid=Cj0KCQiA1NebBhDDARIsAANiDD2Ja2WCBYtxifWx9d8uD2bEZzDjtO4mB2aq7fEtvoUKZZ8GeQbeNtgaAoW5EALw_wcB and https://app.circleci.com/settings/project/github/angular/angular-cli/triggers?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fangular%2Fangular-cli&triggerSource=&scheduledTriggerId=8e3e6898-fd55-41b1-a3e8-85c52981d941&success=true

ci: replace scheduled jobs with scheduled pipelines (Make v13 branch green)

---

.circleci/dynamic_config.yml

ci: update browser-tools

---

packages/schematics/angular/resolver/functional-files/__name@dasherize__.resolver.spec.ts.template

The current functional resolver generates: 
```ts
const executeResolver: ResolveFn<boolean> = ...
it('should be created', () => {
expect(resolver).toBeTruthy();
});
```
with `resolver` a variable that is never declared
```ts
const executeResolver: ResolveFn<boolean> = ...
it('should be created', () => {
expect(executeResolver).toBeTruthy();
});
```

fix(@schematics/angular): use proper variable in resolver functional spec

---

packages/schematics/angular/interceptor/functional-files/__name@dasherize@if-flat__/__name@dasherize__.interceptor.spec.ts.template

An import is missing in the interceptor spec

fix(@schematics/angular): add missing import for functional interceptor spec

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer.ts

When using the experimental esbuild-based browser application builder, the JavaScript transformation workers will now only receive the explicit options expected. Previously, additional Angular compiler plugin options could have been serialized and sent as well. While these would be unused, there was no need to serialize/deserialize these option values.

fix(@angular-devkit/build-angular): explicitly send options to JS transformer workers

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

fix(@angular-devkit/build-angular): update `css-loader` to `6.7.3`

---

packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/src/lib/lib.component.ts

test: removed empty methods

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/css-resource-plugin.ts

When using the experimental esbuild-based browser application builder with the `--stats-json`
option, all referenced CSS resources will now use paths relative to the workspace root within
the output JSON file. Previously, the resource paths within the stats JSON file were absolute
and were inconsistent with the other JavaScript and CSS paths within the file. CSS resources
include files that have been referenced in a bundled stylesheet `url()` such as images or fonts.

fix(@angular-devkit/build-angular): use relative css resource paths in esbuild JSON stats

---

CHANGELOG.md

docs: release notes for the v15.1.0 release

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts

When using the experimental esbuild-based browser application builder and an exception is thrown during the initial build, the process may hang indefinitely due to the Sass worker pool not shutting down fully. This does not happen for rebuilds after the initial.  To remedy this situation, The initial build is now wrapped in a try block to ensure that a full shutdown of the Sass worker pool occurs.

fix(@angular-devkit/build-angular): prevent hanging initial build during exception with esbuild

---

packages/angular/cli/src/analytics/analytics-collector.ts

Issue Number: http://b/264671793
No privacy concerns right now, but still waiting on formal approval.

Re-enable analytics

---

packages/angular/cli/src/commands/generate/cli.ts

Previously base collections where not being taken into account and the recent changes caused an exception
```
An unhandled exception occurred: Cannot destructure property 'aliases' of 'collection.description.schematics[schematicName]' as it is undefined.
```
See: https://angular-team.slack.com/archives/CHEEH2LCA/p1674122139247359

fix(@angular/cli): handle extended schematics when retrieving aliases

---

packages/angular_devkit/build_angular/src/utils/supported-browsers.ts
packages/schematics/angular/config/files/.browserslistrc.template

https://github.com/angular/angular/pull/48669 added support for the last 2 Chrome versions. This commit the proper configuration in the Angular CLI.

Update browserslist config to include last 2 Chrome versions

---

.bazelrc
.circleci/dynamic_config.yml
.circleci/env.sh
.circleci/win-ram-disk.ps1
BUILD.bazel
WORKSPACE
docs/DEVELOPER.md
packages/angular/cli/src/utilities/version.ts
packages/angular_devkit/build_angular/src/builders/karma/index.ts
tests/legacy-cli/BUILD.bazel
tests/legacy-cli/e2e.bzl
tests/legacy-cli/e2e/assets/13.0-project/karma.conf.js
tests/legacy-cli/e2e/assets/BUILD.bazel
tests/legacy-cli/e2e/initialize/500-create-project.ts
tests/legacy-cli/e2e/initialize/BUILD.bazel
tests/legacy-cli/e2e/ng-snapshot/BUILD.bazel
tests/legacy-cli/e2e/setup/001-create-tmp-dir.ts
tests/legacy-cli/e2e/setup/002-npm-sandbox.ts
tests/legacy-cli/e2e/tests/BUILD.bazel
tests/legacy-cli/e2e/tests/basic/test.ts
tests/legacy-cli/e2e/tests/build/esbuild-unsupported.ts
tests/legacy-cli/e2e/tests/generate/confg/type-karma.ts
tests/legacy-cli/e2e/utils/BUILD.bazel
tests/legacy-cli/e2e/utils/bazel.ts
tests/legacy-cli/e2e/utils/process.ts
tests/legacy-cli/e2e/utils/project.ts
tests/legacy-cli/e2e/utils/utils.ts
tests/legacy-cli/e2e_runner.ts
tools/defaults.bzl

See the fixup commits for what changed since the last PR and what was reverted.

run e2e tests under bazel

---

package.json
scripts/build-bazel.ts
scripts/build.ts
scripts/packages.ts
scripts/publish.ts
scripts/snapshots.ts

This reverts commit 8f4e1018ddfa1c421769fda4e4e973375c7b8db6.

Revert "build: remove no longer used scripts"

---

scripts/build-schema.ts
tsconfig.json

This commit updates the build-schema script to use Bazel.

build: update use bazel to build schemas for development

---

.circleci/dynamic_config.yml

Update to the latest RBE setup after key rotation.

build: update to latest remote build execution setup

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_webpack/package.json
packages/ngtools/webpack/package.json
yarn.lock

[LTS 14] fix(@angular-devkit/build-angular): update webpack dependency to `5.76.1`

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_webpack/package.json
packages/ngtools/webpack/package.json
yarn.lock

[PATCH] fix(@angular-devkit/build-angular): update `webpack` dependency to `5.76.1`

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_webpack/package.json
packages/ngtools/webpack/package.json
yarn.lock

[LTS 13] fix(@angular-devkit/build-angular): update webpack dependency to `5.76.1`

---

tests/legacy-cli/e2e/tests/build/server/platform-server-standalone.ts
tests/legacy-cli/e2e/tests/build/server/platform-server.ts

Add an E2E to test the generated universal application.

test: add an E2E to tests standalone server build

---

packages/schematics/angular/app-shell/index.ts
packages/schematics/angular/app-shell/index_spec.ts
tests/legacy-cli/e2e/tests/build/app-shell/app-shell-standalone.ts

This commit adds support to run `ng generate app-shell` in standalone applications.

feat(@schematics/angular): update app-shell schematic to support standalone applications     

---

renovate.json

This package can now be updated following https://github.com/angular/angular-cli/pull/24993

ci: re-enable cacache updates

---

packages/schematics/angular/migrations/update-15/remove-browserslist-config.ts

fix(@schematics/angular): ignore hidden directories when running browserlist migration

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts

When using the esbuild-based browser application builder, the output path is deleted prior to performing a build to ensure a clean output with only the built files. The deletion will now be performed asynchronously using the Node.js promised-based API. This should provide a small performance improvement for projects with large output directories.

perf(@angular-devkit/build-angular): asynchronously delete output path in esbuild builder

---

packages/schematics/angular/utility/latest-versions/package.json

For preleases the version must be `-next.0`
See: https://github.com/angular/angular-cli/blob/63e994445d6332bf161bbd1b601d70c687704908/scripts/release-checks/dependency-ranges/latest-versions-check.mts

build: update ng-packagr version to pass prerelease checks

---

packages/angular/cli/src/commands/doc/cli.ts

docs: improve wording in doc command version description

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

When using the esbuild-based browser application builder with the development server, the incoming URL for the index HTML may contain search parameters or other URL elements that can cause the index HTML content to not be found or processed incorrected by the development server. These elements are cleaned prior to comparison and the original URL is not longer passed to Vite to avoid unneeded Vite specific processing of the content.
Closes #25080

fix(@angular-devkit/build-angular): clean incoming index URL before processing in esbuild builder

---

packages/angular_devkit/build_angular/src/utils/service-worker.ts

When using the esbuild-based build system with the service worker enabled, binary assets were unintentionally being hashed with the assumption of UTF-8 encoding. The assets are now hashed directly to ensure correct output hashes.
Closes #25200

fix(@angular-devkit/build-angular): correctly generate serviceworker hashes for binary assets

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/global-scripts.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/global-styles.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/virtual-module-plugin.ts

This commit adds a new plugin to enable us to create virtual modules more easily.

refactor: create a common plugin to generate virtual modules

---

package.json
packages/angular_devkit/schematics_cli/blank/project-files/package.json
packages/angular_devkit/schematics_cli/schematic/files/package.json
packages/ngtools/webpack/package.json
packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
packages/schematics/angular/utility/latest-versions/package.json
tests/legacy-cli/e2e/assets/webpack/test-app/package.json
yarn.lock

Bumps up the TypeScript version to 5.1 final and switches new projects to use 5.1.

build: update to TypeScript 5.1 final

---

package.json
packages/angular_devkit/benchmark/src/default-reporter.ts
packages/angular_devkit/build_angular/package.json
yarn.lock

build: update `vite` to `4.3.9`

---

packages/angular/cli/src/command-builder/schematics-command-module.ts
packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
packages/schematics/angular/universal/index.ts

refactor: removed unused import statements

---

CHANGELOG.md
tools/defaults.bzl

docs: removed the duplicate words

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts
packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts

This commit extracts code in separate files.

refactor: move esbuild index generator, code bundle option and execution results

---

packages/angular/cli/src/commands/run/cli.ts

docs: remove duplicate words

---

README.md
scripts/templates/readme.ejs

docs: removed the deprecated tag of align center in readme file

---

packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/src/lib/lib.service.ts

refactor: remove unused constructor method

---

CHANGELOG.md

docs: updated the b tag to the strong tag in the docs

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

Patch version of https://github.com/angular/angular-cli/pull/25379

fix(@angular-devkit/build-angular): unpin and downgrade `browserslist`

---

packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts

Postcss plugins may provide result messages that contain stylesheet dependencies that should be watched and should trigger a rebuild of the stylesheet being processed. These files will now be linked to the stylesheet and will allow the provided file dependencies to be watched and in-memory caches to be invalidated. Both the `dependency` and `dir-dependency` postcss messages are supported.

fix(@angular-devkit/build-angular): track postcss provided file depenencies in esbuild builder

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_angular/src/builders/app-shell/app-shell_spec.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/inline-critical_spec.ts
packages/angular_devkit/build_angular/src/builders/browser/tests/options/inline-critical_spec.ts
packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css_spec.ts
yarn.lock

Update critters to the latest version.
Closes #25388

build: update critters to 0.19.0

---

packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts

As of esbuild v0.18.9, vendor prefixing of CSS is now supported. The esbuild target option is generated from a project's browserslist and the vendor prefixing will reflect the configured browsers for a project. This improvement allows for the removal of the postcss autoprefixer plugin from the build pipeline. This can provide a performance benefit for projects especially when project stylesheets contain nothing that would require prefixing since postcss processing can potentially be skipped completely.

refactor(@angular-devkit/build-angular): use built-in CSS vendor prefixing in esbuild

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

This fixes and issue with negative source maps columns
Closes #25414

build: update `@babel/generator` to `7.22.8`

---

CHANGELOG.md

docs: updated the b tag to the strong tag in the changelog docs

---

packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts

This commit ensure that server "polyfills" like `zone.js` and `@angular/compiler` are loaded as well when using the `ssr` option

fix(@angular-devkit/build-angular): ensure that server dependencies are loaded also in ssr entrypoint

---

packages/angular_devkit/build_angular/src/tools/babel/plugins/adjust-typescript-enums.ts
packages/angular_devkit/build_angular/src/tools/babel/plugins/adjust-typescript-enums_spec.ts

PATCH VERSION
When optimizing a CommonJS exported enum, the build optimizer enum wrapping pass was previously dropping the `exports` object assignment from the enum wrapper function call expression. This would not occur with application code but is possible with library code that was built with TypeScript and shipped as CommonJS.
Assuming the following TypeScript enum:
```
export enum ChangeDetectionStrategy {
OnPush = 0,
Default = 1,
}
```
TypeScript 5.1 will emit an exported enum for CommonJS as follows:
```
exports.ChangeDetectionStrategy = void 0;
var ChangeDetectionStrategy;
(function (ChangeDetectionStrategy) {
ChangeDetectionStrategy[ChangeDetectionStrategy["OnPush"] = 0] = "OnPush";
ChangeDetectionStrategy[ChangeDetectionStrategy["Default"] = 1] = "Default"; …
```

[16.1.x] fix(@angular-devkit/build-angular): correctly wrap CommonJS exported enums when optimizing

---

packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/sass-language.ts

When using Sass files with module import references in the esbuild-based browser application builder, the module resolution attempts will now be cached in memory. This caching is only local to each entry Sass file currently. However, this may be expanded to encompass all Sass entries within a build in the future. In addition to caching the entire resolution attempt, individual package root resolution is also cached for deep import attempts. This is useful for packages (such as `@material/*`) which deep import to multiple different files in the same package.
With this change combined with the previous lexer change (#25534), package managers (pnpm & Yarn PnP) that require workarounds for functioning resolution will now perform at an equivalent level to other package managers.

perf(@angular-devkit/build-angular): use in-memory Sass module resolution cache

---

CHANGELOG.md
package.json

This reverts commit a978636147b2d9ed2f4877206dc870f5b87bae08.

Revert "release: cut the v16.2.0-next.4 release"

---

packages/angular_devkit/build_angular/src/tools/webpack/plugins/index-html-webpack-plugin.ts

fix(@angular-devkit/build-angular): hot update filename suffix with `.mjs`

---

CHANGELOG.md

docs: updated the changelog doc with the obsolete tag

---

packages/angular_devkit/build_angular/src/tools/babel/webpack-loader.ts

docs: omit repetitions

---

packages/angular_devkit/architect/src/api.ts

docs: fix typo in api.ts

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

Update to latest version of critters.

build: update critters

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/angular-compilation.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts

When using the esbuild-based browser application builder, TypeScript diagnostics are now converted into esbuild messages within the compilation base class instead of the plugin. This helps further isolate the TypeScript details within the compilation classes. Additionally, this provides diagnostic objects that can be more easily serialized earlier in the build process.

refactor(@angular-devkit/build-angular): move TypeScript diagnostic conversion into compilation base

---

CONTRIBUTING.md
scripts/templates/contributing.ejs

docs: update the http tag with https

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-file-loader.ts
packages/angular_devkit/build_angular/src/utils/server-rendering/prerender.ts

Cherry-pick of https://github.com/angular/angular-cli/pull/25653

fix(@angular-devkit/build-angular): update vite to be able to serve app-shell and SSG pages [cherry-pick]

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

This commit updates the Vite based dev-server to send updates for global styles using the HMR update instead of a full page reload when the the dev-server builder `hmr` option to be enabled.

fix(@angular-devkit/build-angular): handle HMR updates of global CSS when using Vite

---

package.json
tools/postinstall/patches/@bazel+jasmine+5.8.1.patch
yarn.lock

PR to fix upstream `@bazel/jasmine` change https://github.com/bazelbuild/rules_nodejs/pull/3691

build: update dependency jasmine to v5

---

packages/angular/pwa/package.json
packages/angular/ssr/package.json
packages/angular_devkit/build_angular/package.json
packages/ngtools/webpack/package.json

This is needed to satisfy the pre-release checks.

build: update peer Angular peer deps

---

.github/SAVED_REPLIES.md

docs: updated the http tag with https

---

packages/angular_devkit/build_angular/src/builders/application/schema.json

docs: update statsJson application builder description

---

packages/angular_devkit/build_angular/src/builders/dev-server/load-proxy-config.ts

The development server proxy configuration file for Webpack supports a `pathRewrite` field that is not directly supported by the underlying Vite development server when using the application or esbuild- browser builders. To provide equivalent support, especially for JSON file-based proxy configurations, the `pathRewrite` field is now converted internally to a proxy `rewrite` function.
Fixes: #25562

fix(@angular-devkit/build-angular): support dev server proxy `pathRewrite` field in Vite-based server

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
yarn.lock

This commit updates `https-proxy-agent` to version 7+

build: update `https-proxy-agent` to version `7.0.2`

---

.github/workflows/ci.yml
goldens/public-api/angular/ssr/index.md
goldens/public-api/ngtools/webpack/index.md

At the moment not all tests under `//packages/`. This commit removes the matrix for `test` and always execute all tests.

ci: run all unit tests in CI

---

packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
packages/angular_devkit/build_angular/src/tools/esbuild/global-scripts.ts
packages/angular_devkit/build_angular/src/tools/esbuild/sourcemap-ignorelist-plugin.ts

- [] Tests for the changes have been added (for bug fixes / features)

refactor(@angular-devkit/build-angular): typo in ignore list plugin function

---

packages/angular/ssr/schematics/ng-add/index.ts

This commit configures both `ssr` and `prerender` both both development and production configurations. This is needed to improve DX and allow for a better debugging.

fix(@angular/ssr): enable `prerender` and `ssr` for all build configuration

---

renovate.json

`sass` requires some changes to be updated.

ci: temporary disable `sass` from auto updates

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

Prior to this change, async/await in external packages were not being correctly downlevelled when using vite dev-server with cache enabled.t checkout
Closes #25985
(cherry picked from commit 968ee3428046eaad8eb56518c73195f43b6d4ead)
Patch version of https://github.com/angular/angular-cli/pull/25986

fix(@angular-devkit/build-angular): fully downlevel async/await when using vite dev-server with caching enabled

---

packages/schematics/angular/application/files/common-files/src/app/app.component.html.template
tests/legacy-cli/e2e/assets/14.0-project/src/app/app.component.html

Changed the twitter logo from old one to new X logo

fix(@schematics/angular): change Twitter logo to X

---

packages/angular/cli/src/commands/build/long-description.md

docs(@angular/cli): update build description

---

CHANGELOG.md
docs/DEVELOPER.md
docs/design/ngConfig.md
docs/process/release.md
docs/specifications/schematic-prompts.md

```pseudo
descrption > description
redudant > redundant
targetting > targeting
suppport > support
Specfication > Specification
peform > perform
```

docs: Fix typo in multiple files

---

packages/angular_devkit/build_angular/src/builders/application/schema.json
packages/angular_devkit/build_angular/src/builders/prerender/schema.json

This commit updates several option descriptions

docs(@angular-devkit/build-angular): update prendering options descriptions

---

packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts

With the full set of dependencies and watch files tracked within the bundler context object for component stylesheets, the entire bundler output can be cached in memory and reused when none of the relevant files have changed since the last rebuild. This is particularly useful for scenarios when a large tree of components are considered affected and must be recompiled by the AOT compiler.

perf(@angular-devkit/build-angular): fully avoid rebuild of component stylesheets when unchanged

---

packages/angular_devkit/build_angular/src/builders/app-shell/render-worker.ts

There might be cases were currently, the render application promise does not resolve because the application never becomes stable in most cases this is due to errors, this causes the worker to never exit and the build to keep running until it's manually terminated.
With this change, we add a maximum rendering timeout of 30seconds for each page.

fix(@angular-devkit/build-angular): add a maximum rendering timeout for SSR and SSG during development

---

.circleci/dynamic_config.yml
.github/workflows/ci.yml
scripts/saucelabs/start-tunnel.sh

[Successful run](https://github.com/angular/angular-cli/actions/runs/6669610803/job/18127775616)

ci: move saucelabs browser testing to GHA

---

packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer.ts

The Worker thread pool that is used by the JavaScript Transformer within the application builder is now only initialized if there is JavaScript that must be transformed. This removes any overhead associated with the worker pool if no work is required. This is particularly useful when using the development server with caching enabled and all the dependencies have already been prebundled.

refactor(@angular-devkit/build-angular): lazily initialize JS transformer worker pool

---

package.json
yarn.lock

Reverts angular/angular-cli#26191

Revert "build: update dependency ng-packagr to v17.0.0-rc.1"

---

tests/legacy-cli/e2e/tests/jest/basic.ts

More context in https://github.com/angular/angular/pull/52505

test: temporary disable Jest E2E tests

---

packages/angular/cli/bin/ng.js

The Node.js's release link is not working.
The Node.js's release link is working.

docs: fix the node.js's link that not working

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

This fixes the following warnings
```
Cannot optimize dependency: url, present in 'ssr.optimizeDeps.include'
Cannot optimize dependency: path, present in 'ssr.optimizeDeps.include'
```

fix(@angular-devkit/build-angular): exclude node.js built-ins from vite dependency optimization

---

tests/legacy-cli/e2e/tests/jest/basic.ts

Reverts angular/angular-cli#26220

Revert "test: temporary disable Jest E2E tests"

---

tests/legacy-cli/e2e/tests/vite/reuse-dep-optimization-cache.ts

Add timeout to wait for FS to stablize

test: add timeout to vite re-use cache

---

packages/schematics/angular/application/files/common-files/src/app/app.component.html.template

The div was badly aligned in `app.component.html`
It's now properly aligned

fix(@schematics/angular): html indentation

---

packages/angular_devkit/build_angular/BUILD.bazel

These tests have become flaky.

build: mark karma and dev-server tests are flaky

---

package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build-assets_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
yarn.lock

(cherry picked from commit 5b93b9d1dddd34b2b2d7b6ec9e84be8dfc0e52c6)

build: update dependency vite to v5

---

packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-errors_spec.ts

A unit-test for the application builder has been added to that tests the rebuilds are triggered when a template error has been introduced in a rebuild. The test also confirms that rebuilds continue to function after the error has been corrected.

test(@angular-devkit/build-angular): add template error recovery unit-test for application builder

---

packages/schematics/angular/app-shell/index.ts
packages/schematics/angular/application/files/common-files/src/app/app.component.html.template
packages/schematics/angular/application/files/module-files/src/app/app.component.ts.template
packages/schematics/angular/application/files/standalone-files/src/app/app.component.ts.template
packages/schematics/angular/application/index_spec.ts

The template now uses the new control flow syntax

refactor(schematics): remove `CommonModule`

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

Prior to this change the vendor sourcemaps option was not being considered when in the vite JavaScript transformation pipeline.

fix(@angular-devkit/build-angular): only include vendor sourcemaps when using the dev-server when the option is enabled  

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/file-reference-tracker.ts

The path comparisons for the TypeScript and AOT file reference tracking now use the native path normalization functions. This avoids issues where the TypeScript paths which use POSIX separators may not correct match system paths. The file reference tracking is used to trigger updates to both web workers as well as component stylesheets that have preprocessor (Sass/Less/etc.) dependencies.

fix(@angular-devkit/build-angular): always normalize AOT file reference tracker paths

---

packages/angular_devkit/build_angular/src/utils/environment-options.ts

This comment is no longer correct.

refactor(@angular-devkit/build-angular): remove no longer applicable comment

---

packages/angular_devkit/build_angular/src/tools/esbuild/watcher.ts
packages/angular_devkit/build_angular/src/utils/environment-options.ts

File watching improvements 

---

packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/watch_spec.ts

These tests can now be enabled.

test(@angular-devkit/build-angular): enable dev-server watch tests for vite

---

packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/serve_service-worker_spec.ts

Enable service worker tests for vite.

test(@angular-devkit/build-angular): enable vite service worker unit tests

---

packages/angular_devkit/build_angular/src/tools/esbuild/i18n-locale-plugin.ts

All specified locales in the i18n configuration for an application use the `application` or `browser-esbuild` builders will now be normalized using the `Intl` API. This ensures that the provided locale tags are both well-formed and correctly cased. This also more easily allowed an optimization for the default locale which is already embedded into the framework and will now no longer be injected by the build process if active.

fix(@angular-devkit/build-angular): normalize locale tags with `Intl` API when resolving in application builder

---

packages/angular_devkit/build_angular/src/builders/ssr-dev-server/index.ts

Remove `rxjs/operators` legacy import

refactor: update rxjs imports

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

build: update dependency vite to v4.5.1

---

packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-loader/register-hooks.ts
yarn.lock

Fixed version of https://github.com/angular/angular-cli/pull/26571

build: lock file maintenance

---

packages/angular_devkit/build_angular/src/builders/application/schema.json

The description had different types of quotes.

fix(@angular-devkit/build-angular): typo in preloadInitial option description

---

packages/angular/cli/BUILD.bazel
packages/angular/cli/lib/config/workspace-schema.json

Add missing schemas to improve IDE DX

fix(@angular/cli): add prerender and ssr-dev-server schemas in angular.json schema

---

packages/schematics/angular/server/index.ts

This commit updates the server schematic to use the new dependency utility.

refactor(@schematics/angular): update server schematic to use new dependency utility

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

Reverts angular/angular-cli#26760

Revert "build: update dependency webpack-dev-middleware to v7"

---

.husky/commit-msg
.husky/pre-commit
.husky/prepare-commit-msg
package.json

husky v9 simplified its setup, see `How to migrate` in https://github.com/typicode/husky/releases/tag/v9.0.1

refactor: simplify husky setup

---

tests/legacy-cli/e2e/tests/packages/webpack/test-app.ts

test: update webpack tests filenames and size checks to pass with latest webpack

---

packages/angular_devkit/build_angular/src/builders/application/tests/behavior/index-preload-hints_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts

https://github.com/angular/angular-cli/commit/41ea985f9317b11cfa6627a2d3f6b34ff4dbc134#diff-239ad7beb7d8a76046cdc7b4d2263b2e05c300e3e0510916cb907e93efec5af0 introduced a regression which causes server enter-points

fix(@angular-devkit/build-angular): avoid preloading server chunks

---

packages/angular/cli/src/commands/update/schematic/index.ts

To prevent `JSON.parse` errors triggered by Byte Order Marks (BOMs) in package.json files, the `readJson` tree method is now utilized for more reliable BOM handling.
Closes #27052

fix(@angular/cli): prevent BOM errors in `package.json` during `ng update`

---

tests/legacy-cli/e2e/tests/packages/webpack/test-app.ts

This is a cherry pick of #27135 and #27138 targeting the patch (`17.2.x`) branch.
This fixes CI issues and unblocks the patch release.

test: generalize webpack direct E2E chunk size testing

---

packages/angular_devkit/build_angular/src/utils/index-file/html-rewriting-stream.ts

The Node.js async `pipeline` helper function reduces the amount of infrastructure code needed to pipe HTML content through the parse5 transform stream.

refactor(@angular-devkit/build-angular): use async pipeline helper in HTML rewriting stream

---

packages/angular_devkit/build_angular/src/utils/purge-cache.ts

When purging stale build cache entries, the `readdir` call will fail if the cache base path does not exist. This allows for a single check and the removal of the previous separate `existSync` call. Additionally, a repeat join call has also been removed during the stale directory check.

refactor(@angular-devkit/build-angular): remove extra exist check when purging stale build caches

---

packages/angular_devkit/build_angular/src/builders/application/options.ts

The usage of several Webpack-centric option helper functions has now been removed from the `application` builder. This allows for more efficient processing of incoming options but also removes additional imports across builder code.

refactor(@angular-devkit/build-angular): remove Webpack helpers from application builder option normalization

---

renovate.json

Reverts angular/angular-cli#27214

Revert "ci: disable auto updates for `critters`"

---

packages/schematics/angular/app-shell/index.ts
packages/schematics/angular/library/index.ts
packages/schematics/angular/migrations/update-17/replace-nguniversal-engines.ts
packages/schematics/angular/migrations/update-17/use-application-builder.ts
packages/schematics/angular/module/index.ts
packages/schematics/angular/utility/ng-ast-utils.ts
packages/schematics/angular/utility/paths.ts

Some Angular schematic cleanup

---

packages/angular_devkit/build_angular/src/builders/application/execute-post-bundle.ts
packages/angular_devkit/build_angular/src/builders/browser/index.ts
packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts
packages/angular_devkit/build_angular/src/tools/webpack/plugins/index-html-webpack-plugin.ts
packages/angular_devkit/build_angular/src/utils/index-file/add-event-dispatch-contract.ts
packages/angular_devkit/build_angular/src/utils/index-file/add-event-dispatch-contract_spec.ts
packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
packages/angular_devkit/build_angular/src/utils/index-file/index-html-generator.ts
packages/angular_devkit/build_angular/src/utils/index-file/nonce.ts
packages/angular_devkit/build_angular/src/utils/index-file/nonce_spec.ts

This commit add support in the Angular CLI to inject the event-dispatcher script when using the application builder.

feat(@angular-devkit/build-angular): inject event-dispatcher in SSR HTML page

---

goldens/public-api/angular_devkit/build_angular/index.md
package.json
packages/angular/cli/src/commands/build/long-description.md
packages/angular_devkit/build_angular/src/builders/ng-packagr/index.ts
packages/angular_devkit/build_angular/src/builders/ng-packagr/schema.json
yarn.lock

This commit adds support for polling when using the ng-packagr builder
Closes #27420

feat(@angular-devkit/build-angular): add support for the `poll` option in  the library builder

---

packages/angular/build/src/builders/dev-server/tests/options/headers_spec.ts
packages/angular/build/src/builders/dev-server/vite-server.ts

Headers were not configured correctly.
Closes #27464

fix(@angular/build): properly configure headers for media resources and HTML page

---

packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/headers_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

Headers were not configured correctly.
Closes #27464

fix(@angular-devkit/build-angular): properly configure headers for media resources and HTML page

---

packages/angular/build/src/tools/sass/sass-service.ts
packages/angular/build/src/tools/sass/worker.ts

The multi-threaded Sass rendering system now uses a thread pool back by the `piscina` package. This package is already used in multiple locations throughout the build system. This replaces the custom worker implementation and reduces the direct code complexity as well as providing improved handling of worker turndown and cleanup.

refactor(@angular/build): use piscina-based worker pool for Sass rendering

---

packages/angular/cli/package.json
packages/angular/cli/src/commands/update/cli.ts
packages/schematics/angular/migrations/migration-collection.json

Several ng update display fixes for v18

---

packages/schematics/angular/library/files/README.md.template
packages/schematics/angular/workspace/files/README.md.template

The currently generated readme mentions angular.io
It now references angular.dev

fix(@schematics/angular): use angular.dev in readme

---

.github/ISSUE_TEMPLATE/config.yml
README.md
SECURITY.md
docs/design/build-system.md
docs/process/release.md
scripts/templates/readme.ejs

- **N/A** Tests for the changes have been added (for bug fixes / features)
- **N/A** Docs have been added / updated (for bug fixes / features)
Links in README.md, docs directory and `.github` directory point to angular.io
Point to angular.dev
Related aio -> adev PRs in #27713

docs: update aio->adev links in README, docs and .github dirs

---

modules/testing/builder/projects/hello-world-app/src/polyfills.ts
packages/angular/build/src/builders/application/schema.json
packages/angular/build/src/builders/dev-server/schema.json
packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular/build/src/utils/i18n-options.ts
packages/angular/cli/src/analytics/analytics.ts
packages/angular/cli/src/commands/deploy/cli.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
packages/angular_devkit/build_angular/src/builders/browser/schema.json
packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
packages/angular_devkit/build_angular/src/builders/karma/schema.json
packages/angular_devkit/build_angular/src/builders/protractor/index.ts
packages/angular_devkit/build_angular/src/builders/server/index.ts
packages/angular_devkit/build_angular/src/builders/server/schema.json
packages/angular_devkit/build_angular/src/builders/web-test-runner/schema.json
packages/angular_devkit/build_angular/src/tools/babel/presets/application.ts
packages/angular_devkit/build_angular/src/tools/webpack/plugins/typescript.ts
packages/angular_devkit/build_webpack/test/angular-app/src/polyfills.ts
packages/schematics/angular/config/files/.browserslistrc.template

- **N/A** Tests for the changes have been added (for bug fixes / features)
- **N/A** Docs have been added / updated (for bug fixes / features)
Several links point to angular.io despite angular.dev being new docs site
Specifically:
- workspace config
- browser support
- i18n, deploy
- build guide 
- blog, analytics, hydration
Use angular.dev for docs
Looking for `angular.io` seems they're some links that can be updated in batches:
- **README, `docs/` and `.github`**: #27712 
- **Several aio links around**: this PR
- **`tsconfig` template files comment**: #27714
- **License headers**. Which contain a link to `angular.io/license`
- **Test fixtures**. They could …

docs: more aio->adev link updates

---

packages/angular/build/src/tools/esbuild/stylesheets/sass-language.ts

When `dart-sass` returns an error, the provided location span may not be the exact location of the error but can instead be the location of the `@error` call within a Sass function. The generated stack trace string does contain all files related to the error including the usage site in the case of the function `@error` case. To ensure all related files for the error are watched and allow for a rebuild that may correct the error, the stack trace is parsed and found files are added to the watch list. Unfortunately, `dart-sass` does not provide the list directly. If that changes in the future, the stack trace parsing could be removed.

fix(@angular/build): watch all related files during a Sass error

---

.github/dependency-review-config.yml
yarn.lock

Closes https://github.com/angular/angular-cli/pull/27557 as a pr takeover.
See: https://github.com/angular/angular-cli/actions/runs/9383120071/job/25836024369?pr=27557

Pr takeover 27557

---

packages/schematics/angular/application/files/common-files/tsconfig.app.json.template
packages/schematics/angular/application/files/common-files/tsconfig.spec.json.template
packages/schematics/angular/e2e/files/tsconfig.json.template
packages/schematics/angular/library/files/tsconfig.lib.json.template
packages/schematics/angular/library/files/tsconfig.lib.prod.json.template
packages/schematics/angular/library/files/tsconfig.spec.json.template
packages/schematics/angular/server/files/root/tsconfig.server.json.template
packages/schematics/angular/web-worker/files/worker-tsconfig/tsconfig.worker.json.template
packages/schematics/angular/workspace/files/tsconfig.json.template

- **N/A** Tests for the changes have been added (for bug fixes / features)
- **N/A** Docs have been added / updated (for bug fixes / features)
`tsconfig` template files point to a non-existent link in Angular.io . Also, the page no longer exists in Angular.dev
Point to Typescript official documentation about `tsconfig.json` + Angular compiler options
Checkout #27713 for references to related PRs

docs: update tsconfig template link aio->adev

---

packages/angular/build/src/tools/esbuild/index-html-generator.ts

If the module preload limit is not met by shallow (depth 1) initial scripts, deeper initial scripts can now be added. This allows for deeper import graphs to take advantage of the browser's module preloading. Additionally, the limit has been increased to ten now that the module preloads are added at the end of the body along with the actual script elements.

fix(@angular/build): allow additional module preloads up to limit

---

.github/workflows/ci.yml
.github/workflows/pr.yml

This commit removes redundant configuration.

ci: clean up PR and CI workflow

---

.github/workflows/ci.yml
.github/workflows/pr.yml
docs/DEVELOPER.md
tests/legacy-cli/e2e/setup/010-local-publish.ts

CI Updates

---

packages/angular_devkit/build_angular/package.json
renovate.json
yarn.lock

Tested on Windows https://github.com/angular/angular-cli/actions/runs/9500301066?pr=27840 as previously this update caused problems on Windows.

build: update copy-webpack-plugin to 12.0.2

---

.github/workflows/pr.yml

Begin checking upstream dependency licenses.

ci: begin checking licenses of upstream dependencies to ensure they are approved

---

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts

If the persistent cache store for the JavaScript transformations fails to initialize, a warning will now be shown to better explain the outcome and to allow the build to continue. The build will still complete without the cache but may be slower to finish.

fix(@angular/build): show JavaScript cache store initialization warning

---

packages/angular/build/src/tools/babel/plugins/adjust-static-class-members.ts
packages/angular_devkit/build_angular/src/tools/babel/presets/application.ts
packages/angular_devkit/build_angular/src/utils/run-module-as-observable-fork.ts
packages/angular_devkit/schematics/tools/file-system-engine-host.ts
scripts/devkit-admin.mts

Several smaller code changes to improve type information and remove now unneeded code structures based on improvements to both Node.js, TypeScript, and underlying dependencies.

refactor: minor code cleanup to improve code health

---

packages/angular_devkit/schematics/tools/node-modules-test-engine-host.ts

The `NodeModulesTestEngineHost` class has been adjusted to use modern JavaScript language features such as private fields and nullish coalescing.

refactor(@angular-devkit/schematics): use modern language features in test engine host

---

packages/angular/cli/src/command-builder/utilities/schematic-engine-host.ts

The schematics encapsulation process now uses a similar wrapping setup to Node.js itself. This removes some custom code and also provides a more comprehensive global object which should provide improved compatibility for third-party packages used within schematics.

refactor(@angular/cli): use Node.js CommonJS wrapping for schematic encapsulation

---

scripts/templates.mts

Issue Number: https://github.com/angular/angular-cli/pull/27862

build: run async task in concurrent

---

packages/angular/build/src/tools/vite/id-prefix-plugin.ts

refactor: rename internal vite plugin name.

---

packages/angular/build/src/tools/vite/middlewares/index-html-middleware.ts

Ensure direct requests to HTML files result in them being served.
Closes #28063

fix(@angular/build): serve HTML files directly

---

tsconfig.json

The excluded files are no longer relevant.

build: remove unnecessary excludes from tsconfig.json

---

packages/angular/cli/src/command-builder/schematics-command-module.ts
packages/angular_devkit/schematics_cli/bin/schematics.ts

fix(@angular-devkit/schematics-cli): prevent bypassing select/checkbox prompts on validation failure

---

packages/angular/ssr/src/app.ts

Removed redundant `.push()` call by directly adding the provider during array initialization phase.

refactor(@angular/ssr): reorganize platform providers initialization in `AngularServerApp`

---

.github/workflows/ci.yml
.github/workflows/pr.yml

Optimize Bazel build with unified module and package tests

ci: run modules and packages tests using a single bazel invocation

---

package.json
packages/angular_devkit/build_angular/package.json
packages/ngtools/webpack/src/ivy/plugin.ts
yarn.lock

build: update webpack to `5.94.0`

---

packages/angular_devkit/build_angular/src/builders/karma/index.ts
packages/schematics/angular/config/files/karma.conf.js.template

This works around https://github.com/angular/angular-cli/issues/28271.

fix(@angular-devkit/build-angular): clear context in Karma by default for single run executions

---

packages/angular/cli/src/command-builder/command-module.ts

Remove unused imports from command-module file.

refacor(@angular/cli): remove unused imports

---

packages/angular/ssr/src/routes/ng-routes.ts
packages/angular/ssr/test/routes/ng-routes_spec.ts

This option allows validation during the build process to ensure that, when the output mode is set to static, no routes requiring server-side rendering are included.

refactor(@angular/ssr): add option to exclude fallback SSG routes from extraction

---

packages/angular/build/BUILD.bazel
packages/angular/build/src/tools/vite/middlewares/ssr-middleware.ts

Updated the SSR Vite middleware to align with the latest API improvements

refactor(@angular/build): update SSR Vite middleware to utilize the enhanced API

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

Includes a fix for CVE-2024-45812 / CVE-2024-45811
CVE-2024-45812 / CVE-2024-45811 fix for 17.3.x branch

fix(@angular-devkit/build-angular): update vite to 4.1.8

---

tests/legacy-cli/e2e/tests/build/rebuild-dot-dirname.ts

Minor changes to the testing setup to fix failures on Windows CI.

test: update test logic to fix windows CI  

---

package.json
packages/angular/build/package.json
yarn.lock

Contains fix for CVE-2024-47068.
See: https://github.com/advisories/GHSA-gcx4-mw62-g8wm
```
yarn up rollup@4.22.4
```
Rollup version is affected by a CVE.
Issue Number: https://github.com/angular/angular-cli/issues/28478

fix(@angular/build): update rollup to 4.22.4

---

tests/legacy-cli/e2e/tests/vite/ssr-entry-express.ts
tests/legacy-cli/e2e/tests/vite/ssr-entry-fastify.ts
tests/legacy-cli/e2e/tests/vite/ssr-entry-h3.ts
tests/legacy-cli/e2e/tests/vite/ssr-entry-hono.ts

Introduce a delay in amending files during tests to reduce flakiness.

test: delay file modifications to mitigate flaky tests

---

packages/angular/build/src/utils/server-rendering/manifest.ts

See: https://github.com/angular/angular-cli/security/code-scanning/77

refactor(@angular/build): incomplete string escaping or encoding

---

packages/angular/build/src/builders/dev-server/vite-server.ts

The previous logic was not on point
Closes #28556

fix(@angular/build): update logic to support both internal and external SSR middlewares

---

packages/schematics/angular/application/files/module-files/src/app/app.component.spec.ts.template
packages/schematics/angular/application/files/standalone-files/src/app/app.component.spec.ts.template

refactor(@schematics/angular): minor formatting fixes

---

packages/angular/ssr/package.json

Add `sideEffects` in the `package.json`

fix(@angular/ssr): designate package as side-effect free

---

packages/angular/ssr/third_party/beasties/rollup.config.mjs

build: remove debug code

---

packages/angular/ssr/src/app.ts

refactor(@angular/ssr): remove redundant `new URL`

---

.ng-dev/dx-perf-workflows.yml

Add integration test to workflows which are tracked on CI

ci: add @angular/build integration test to workflows

---

packages/angular/cli/src/command-builder/architect-base-command-module.ts
packages/angular/cli/src/commands/lint/cli.ts

`@angular-eslint/schematics` is the referenced schematic collection.
`angular-eslint` is the referenced schematic collection, which is my recommended/the preferred way for a cleaner setup in v19 and aligns it with the angular-eslint README: https://github.com/angular-eslint/angular-eslint

fix(cli): update angular-eslint reference

---

tests/legacy-cli/e2e/tests/vite/ssr-new-dep-optimization.ts

With recent updates to Vite, rebuild times have become significantly faster. To ensure reliable testing, we’ve added a deliberate delay to slow down the process during file writes.

test: Introduce delay for file write to minimize flakiness

---

packages/angular/build/src/builders/dev-server/vite-server.ts
packages/angular/build/src/tools/vite/utils.ts

Reduce the amount of code in vite-server.ts

refactor(@angular/build): move `getDepOptimizationConfig` into utils file

---

packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts
packages/angular_devkit/build_angular/src/builders/karma/jasmine_global.js
packages/angular_devkit/build_angular/src/builders/karma/jasmine_global_cleanup.js
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/jasmine-clock_spec.ts

Ports the logic from WTR and webpack and adds a regression test for this behavior.
Fixes https://github.com/angular/angular-cli/issues/28813

fix(@angular-devkit/build-angular): jasmine.clock with app builder

---

renovate.json

This command is not compatible with Yarn 4.

ci: update `yarn` command

---

packages/angular/build/src/builders/dev-server/vite-server.ts

refactor(@angular/build): remove redundant ESLint disabling comments

---

packages/angular_devkit/architect_cli/BUILD.bazel
packages/angular_devkit/build_angular/BUILD.bazel
packages/angular_devkit/build_webpack/BUILD.bazel
packages/angular_devkit/core/BUILD.bazel
packages/angular_devkit/schematics/BUILD.bazel

See individual commits.
All verified via the diff script locally.

Migrate many more packages to `npm_package`

---

packages/angular/pwa/pwa/schema.json
packages/angular/ssr/schematics/ng-add/schema.json
packages/schematics/angular/app-shell/schema.json
packages/schematics/angular/application/schema.json
packages/schematics/angular/class/schema.json
packages/schematics/angular/component/schema.json
packages/schematics/angular/config/schema.json
packages/schematics/angular/directive/schema.json
packages/schematics/angular/enum/schema.json
packages/schematics/angular/environments/schema.json
packages/schematics/angular/guard/schema.json
packages/schematics/angular/interceptor/schema.json
packages/schematics/angular/interface/schema.json
packages/schematics/angular/library/schema.json
packages/schematics/angular/ng-new/schema.json
packages/schematics/angular/pipe/schema.json
packages/schematics/angular/resolver/schema.json
packages/schematics/angular/server/schema.json
packages/schematics/angular/service-worker/schema.json
packages/schematics/angular/service/schema.json
packages/schematics/angular/ssr/schema.json
packages/schematics/angular/web-worker/schema.json
packages/schematics/angular/workspace/schema.json

Refined and clarified the descriptions for various schematics options to improve their readability and accuracy. These changes aim to make the documentation more user-friendly and accessible for developers.
Closes #25571

docs: enhance descriptions for schematics options

---

packages/angular/build/package.json
packages/angular/pwa/package.json
packages/angular/ssr/package.json
packages/angular_devkit/build_angular/package.json
packages/ngtools/webpack/package.json
packages/schematics/angular/utility/latest-versions/package.json

Need to wait for FW release for CI to pass.

build: update Angular versions to 19.1 stable

---

tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js

test: update saucelabs browsers versions

---

packages/angular/ssr/node/src/response.ts

writeResponseToNodeResponse will stream an response without draining.
Node.js streams should be drained to ensure efficient and uninterrupted data flow. This PR adds draining logic to `writeResponseToNodeResponse`
I'm not sure if all checks will pass. Bazel is a weird alien to me

refactor(@angular/ssr): drain node stream

---

packages/angular/build/src/tools/vite/plugins/angular-memory-plugin.ts

refactor(@angular/build): remove unused import

---

goldens/public-api/angular_devkit/build_angular/index.api.md
packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts
packages/angular_devkit/build_angular/src/builders/karma/schema.json
packages/angular_devkit/build_angular/src/builders/karma/tests/options/aot_spec.ts

Rebase version of https://github.com/angular/angular-cli/pull/28854/commits.
Conflicts were resolved via running `yarn public-api:update`.

feat: add aot option to karma

---

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx
package.json
pnpm-lock.yaml
yarn.lock

Consume https://github.com/angular/dev-infra/pull/2586

build: update `@angular/ng-dev` to `9d865e0e4202ed88ccec184739819c09637b5ede`

---

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx
goldens/public-api/angular_devkit/schematics/index.api.md
package.json
packages/angular/build/package.json
packages/angular_devkit/build_angular/package.json
packages/ngtools/webpack/package.json
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
pnpm-lock.yaml
yarn.lock

Updates the repo to TypeScript 5.8 and expands the peer dependency ranges.

build: update to TypeScript 5.8

---

.mailmap

build: modify Alan in the mailmap file

---

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx
package.json
packages/angular_devkit/schematics_cli/blank/project-files/package.json
packages/angular_devkit/schematics_cli/schematic/files/package.json
packages/ngtools/webpack/package.json
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
packages/schematics/angular/utility/latest-versions/package.json
pnpm-lock.yaml
yarn.lock

* Updates the repo to TypeScript 5.8 final.
* Updates the vendored TypeScript binary to 5.8 final.
* Switches the newly-generated projects to TypeScript 5.8.

build: update to TypeScript 5.8 final

---

renovate.json

More info https://docs.renovatebot.com/configuration-options/#followtag

ci: renovate update Angular group to follow next tag

---

package.json
packages/angular/build/package.json
pnpm-lock.yaml

This fixes https://github.com/vitejs/vite/security/advisories/GHSA-x574-m823-4x7w
Closes #29936

fix(@angular/build): update vite to 6.2.3

---

package.json
packages/angular/build/package.json
pnpm-lock.yaml

Addresses GHSA-4r4m-qw57-chr8
Closes #29996

fix(@angular/build): update vite to 6.2.4 due to a security issues

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

Addresses GHSA-4r4m-qw57-chr8
Closes #29996

fix(@angular-devkit/build-angular): update vite to 5.4.16 due to a security issues

---

package.json
packages/angular/build/package.json
pnpm-lock.yaml

build: update `beasties` to `0.3.2`

---

package.json
packages/angular/build/package.json
pnpm-lock.yaml

build: update vite to 6.2.5

---

package.json
packages/angular/build/package.json
pnpm-lock.yaml

fix(@angular/build): update vite to 6.2.6

---

constants.bzl

Date before feature freeze of v20

build: update baseline date to `2025-04-30`

---

package.json
packages/angular/build/package.json
pnpm-lock.yaml

Addresses: https://github.com/vitejs/vite/security/advisories/GHSA-859w-5945-r5v3
Closes #30206

fix(@angular/build): update vite to 6.2.7

---

packages/angular/build/src/builders/unit-test/options.ts

refactor: remove unused function

---

WORKSPACE

Updates dev-infra for latest RBE changes.

build: update dev-infra for latest RBE changes

---

packages/angular/build/src/utils/worker-pool.ts

This is a workaround for https://github.com/piscinajs/piscina/issues/816
Closes #30549

fix(@angular/build): increase worker idle timeout

---

packages/angular/build/package.json
packages/angular_devkit/build_angular/package.json
pnpm-lock.yaml

Includes https://github.com/piscinajs/piscina/pull/818

build: update piscina to 5.1.1

---

packages/schematics/angular/component/schema.json

Several option descriptions were outdated and have been revised for accuracy.
Closes #30566

docs: update component schematic option descriptions

---

goldens/public-api/angular/build/index.api.md
packages/angular/build/src/builders/unit-test/builder.ts
packages/angular/build/src/builders/unit-test/index.ts
packages/angular/build/src/builders/unit-test/karma-bridge.ts
packages/angular/build/src/builders/unit-test/options.ts
packages/angular/build/src/index.ts

This commit exposes the Karma and Unit test builder API
Closes: #30644

fix(@angular/build): expose unit test and karma builder API

---

package.json
packages/angular/build/src/utils/index-file/inline-fonts.ts
pnpm-lock.yaml

This contains the fix for https://github.com/TooTallNate/proxy-agents/issues/379#issuecomment-3063084174

build: update `@types/node` to `20.19.7`

---

packages/angular/cli/src/commands/mcp/cli.ts

The suggested MCP server command options now use the `-y` option for `npx`. This provides better supported for global usage of the Angular CLI MCP server in addition to the workspace usage.

refactor(@angular/cli): update suggested MCP server configuration output

---

WORKSPACE
packages/angular/build/BUILD.bazel
packages/angular/ssr/BUILD.bazel
packages/angular/ssr/third_party/beasties/BUILD.bazel
packages/angular_devkit/architect/BUILD.bazel
packages/angular_devkit/build_angular/BUILD.bazel
packages/angular_devkit/build_webpack/BUILD.bazel
packages/angular_devkit/core/BUILD.bazel
packages/angular_devkit/schematics/BUILD.bazel
packages/ngtools/webpack/BUILD.bazel
tests/legacy-cli/e2e.bzl
tests/legacy-cli/e2e/tests/mcp/registers-tools.ts

Update to latest dev-infra in the workspace and rules_browsers browser toolchains

[20.1.x] build: update to latest dev-infra in the workspace

---

packages/angular/cli/src/commands/mcp/mcp-server.ts

Capabilities are part of the `ServerOptions`, the _second_ argument of the constructor.
This change also adds logging as a supported capability.

refactor(@angular/cli): Fix capabilities registration

---

packages/schematics/angular/workspace/files/package.json.template

*Rebase & squash of https://github.com/angular/angular-cli/pull/30882.*
Closes #30744

fix(@schematics/angular): add extra prettier config

---

packages/schematics/angular/library/index.ts

Removes the manual `NodePackageInstallTask` from the library schematic. The responsibility for scheduling the installation is now delegated to the `addDependency` utility by passing the correct `InstallBehavior`.

refactor(@schematics/angular): remove manual install task in library schematic

---

packages/angular/cli/src/commands/mcp/tools/modernize.ts

`inject-flags` is a migration that can't be run via `ng g @angular/core`.
Use the `inject` schematics instead, as the documentation URL already references it

refactor(@angular/cli): use inject migration in mcp modernize tool

---

packages/schematics/angular/ng-new/schema.json

This definition is a duplicate of the one already present in the application schematic

refactor(@schematics/angular): remove duplicate prompt definition.

---

.github/shared-actions/windows-bazel-test/action.yml

This reduces the post cleanup step timings

build: update `dev-infra` action SHA

---

packages/schematics/angular/application/schema.json

Zoneless is now stable in Angular v20.2 (see https://github.com/angular/angular/commit/141bb75ff241425a93ce5b60b56a4247e67d7648)

fix(@schematics/angular): zoneless is now stable

---

packages/angular/cli/src/utilities/package-manager.ts
packages/angular_devkit/schematics/tasks/package-manager/executor.ts
packages/angular_devkit/schematics/tasks/repo-init/executor.ts
scripts/diff-release-package.mts

This approach has been recommanded by a Node.js member in https://github.com/nodejs/help/issues/5063#issuecomment-3132899776
Closes #30821

fix(@angular/cli): address Node.js deprecation DEP0190

---

packages/schematics/angular/ai-config/schema.json

This improves the prompt wording and adds more context.

fix(@schematics/angular): improve AI config prompt wording

---

packages/angular/cli/src/commands/add/cli.ts

The `run` method within the `add` command module exceeded recommended line limits. This commit refactors the method by extracting the logic for each Listr task into a separate private method.

refactor(@angular/cli): improve structure of `ng add` command

---

packages/angular_devkit/schematics_cli/schematic/files/package.json

The `typescript` npm package is installed as a runtime dependency
The `typescript` npm package will be installed as a development dependency

build(@angular-devkit/schematics-cli): add TypeScript to `devDependencies`

---

packages/schematics/angular/ai-config/schema.json

The labels in the `ai-config` schematic were not aligned, this commit fixes the alignment.

fix(@schematics/angular): align labels in ai-config schema

---

packages/angular/cli/src/commands/mcp/mcp-server.ts
packages/angular/cli/src/commands/mcp/resources/ai-tutor.md
packages/angular/cli/src/commands/mcp/tools/ai-tutor.ts
tests/legacy-cli/e2e/tests/mcp/ai-tutor.ts

Exposes the [Angular AI Tutor](https://github.com/angular/ai-tutor/) via a tool in our MCP server.

feat(@angular/cli): add ai-tutor mcp tool

---

MODULE.bazel
MODULE.bazel.lock
package.json
packages/ngtools/webpack/package.json
pnpm-lock.yaml

See associated pull request for more information.
Closes #31364 as a pr takeover

build: update dependency typescript to v5.9.3
