- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- tests/legacy-cli/e2e/tests/build/styles/tailwind.ts
This feature adds detection of the `tailwindcss` package (https://tailwindcss.com) and provides a mechanism to automatically include support. To enable tailwindcss for a project, two actions must be taken:
1) Install `tailwindcss` into the Angular workspace (`npm install -D tailwindcss`/`yarn add -D tailwindcss`)
2) Create a tailwindcss configuration file (`tailwind.config.js`) in either the workspace root or the project root.  A configuration file in the project root takes precedence over one in the workspace root.
When both conditions are met, the Angular CLI will initialize and integrate tailwindcss into the stylesheet build pipeline.
> feat(@angular-devkit/build-angular): detect and use tailwindcss in projects

- packages/angular/cli/commands/update-impl.ts
This change ensures that migration collections defined in a package's `ng-update` metadata are resolved from the containing package.  This avoids issues that may arise from package manager hoisting behavior which can result in the wrong migration collection being chosen.  The `--migrate-only` option already contained this resolution logic and now the full update contains it as well.
> fix(@angular/cli): resolve migration collections from containing package

- packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
With this change we add a new `jitMode` option to the ivy AngularWebpackPlugin.
`readConfiguration` from `@angular/compiler-cli` will use file configuration options over programmaticly supplied options. By using a separate option the options precedence issue can be avoided.
Closes #19949
> fix(@ngtools/webpack): don't use `skipTemplateCodegen` to determine if compilation is JIT mode

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- yarn.lock
`file-loader` resolves `import/require()` on a file into a url. This is non standard, undocumented, unsupported Webpack specific functionality. This was introduced in the Angular CLI  before `postcss-cli-resources` existed and was never removed.
Using `file-loader` and `postcss-cli-resources` are no longer needed with Webpack 5, because of the introduction of [Assets Modules](https://webpack.js.org/guides/asset-modules/).
**BREAKING CHANGE:**
The unsupported/undocumented, Webpack specific functionality to `import`/`require()` a non-module file has been removed.
Before
```js
import img from './images/asset.png';
```
After
```html
```
> refactor(@angular-devkit/build-angular): remove file-loader dependency

- package.json
- renovate.json
This is needed as otherwise the ng-dev tools will fail due to `Error: Discovered unexpected version-branch "11.2.x" for a release-train that is already active in the "master" branch. Please either delete the branch if created by accident, or update the version in the next branch (master).
> build: update next branch to reflect new release-train `v12.0.0-next.0` 

- .circleci/config.yml
Latest npm is now 7.x and 7.x appears to cause CI failures when setting up the E2E test framework on Node.js 10.
(cherry picked from commit dfc6d89155cb717d09a8101ec8ce6622e34bae44)
> ci: use npm 6.x on Node.js 10 CI jobs

- .circleci/config.yml
This is currently redundant and hence we should disable it.
> ci: remove integration job

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
This provides a default cache identifer to the babel loader that includes all internal options from the customized babel loader.
> fix(@angular-devkit/build-angular): increase resilience of babel cache identifier

- lib/packages.ts
- packages/angular/cli/commands/add-impl.ts
- packages/angular/cli/commands/new-impl.ts
- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/utilities/package-manager.ts
- tests/legacy-cli/e2e/tests/misc/npm-7.ts
This change will display an error message if using npm 7 (or versions earlier than 6). This is a temporarily change while npm 7 usability concerns are addressed.
> fix(@angular/cli): temporarily limit npm to version 6

- lib/packages.ts
- packages/angular/cli/commands/add-impl.ts
- packages/angular/cli/commands/new-impl.ts
- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/utilities/package-manager.ts
- tests/legacy-cli/e2e/tests/misc/npm-7.ts
This change will display an error message if using npm 7 (or versions earlier than 6). This is a temporarily change while npm 7 usability concerns are addressed.
(cherry picked from commit 331f6281394338ec7c4cbf38b777dc5ff09495c2)
> [11.1.x] fix(@angular/cli): temporarily limit npm to version 6

- tests/legacy-cli/e2e/tests/misc/npm-7.ts
Due to the setup of the Windows CI image, attempting to replace npm will fail.  This change skips the npm version limit test for now pending infrastructure updates to the Windows CI image.
> test(@angular/cli): skip npm version limit E2E on Windows

- .circleci/config.yml
- lib/packages.ts
- package.json
- packages/angular/cli/bin/ng
- packages/angular_devkit/benchmark/package.json
This change provides an improved performance baseline as well as access to newer Node.js APIs and Javascript language features which the Angular CLI will now be able to leverage.
Node.js version 10 will become EOL on 2021-04-30.
Angular CLI 12 will require Node.js 12.13+ or 14.15+. Node.js 12.13 and 14.15 are the first LTS releases for their respective majors.
> build: set minimum Node.js version to 12.13

- packages/ngtools/webpack/src/ivy/plugin.ts
- packages/ngtools/webpack/src/ivy/symbol.ts
This change adds additional checks to reduce the number of Webpack `rebuildModule` calls when the Angular compiler requests additional files to be rebuilt. Now if an emitted file's output does not change from its previous emit, a Webpack rebuild of the module is not performed. This can greatly reduce the amount of computation needed during a rebuild as any files that required re-analysis by the Angular compiler but whose final output did not change will not trigger potential expensive Webpack module graph analysis and additonal module rebuilds.
> fix(@ngtools/webpack): reduce overhead of Angular compiler rebuild requests

- packages/angular_devkit/build_angular/src/karma/code-coverage_spec.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts
In angular 11 Previously `karma-coverage` was validated only when in karma plugins config one of these was added
``'karma-coverage'` or `require('karma-coverage')`
This change will allow cli to validate `karma-coverage` plugin if in `karma.conf.js` `'karma-*'` is used. Example:
```
plugins: [
...
'karma-*',
require('@angular-devkit/build-angular/plugins/karma'),
...
]
```
Fixes #19993
> fix(@angular-devkit/build-angular): fixed ignoring of karma plugins config

- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
Some Webpack loaders use loader context flags to control sourcemap generation. This fix ensures that Webpack will set the appropriate flags for loaders to leverage.
> fix(@angular-devkit/build-angular): ensure i18n extraction sourcemaps are fully configured

- packages/angular/cli/commands/new-impl.ts
- packages/angular/cli/models/schematic-command.ts
- packages/angular/cli/utilities/package-manager.ts
- tests/legacy-cli/e2e/tests/misc/npm-7.ts
Update NPM 7 behavior based on https://github.com/angular/angular-cli/issues/19957#issuecomment-775407654
> fix(@angular/cli): update NPM 7 guidance

- scripts/validate.ts
This fixes 9.1.x/10.2.x CI failures as well as synchronizes commit validation activity with master.
> ci: only validate PR commit messages

- tests/legacy-cli/e2e/tests/generate/component/component-child-dir.ts
Windows CI is failing when trying to use the common test cleanup routine for the `generate/component/component-child-dir` E2E test. This fix manually removes the newly created directory within the test.
> ci: fix component-child-dir E2E test on Windows CI

- .circleci/config.yml
This fixes 10.2.x CI failures as well as synchronizes validation activity with master.
> ci: only validate PR commit messages and remove do not submit check

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
The `RuleSetLoader` type is not exported from the Webpack 5 types.
> refactor(@angular-devkit/build-angular): remove use of Webpack RuleSetLoader type

- .circleci/config.yml
The CI size check uses the `e2e-cli` job to retrieve the build artifacts. But with the nightly E2E job having the same name, CircleCI named the regular E2E job `e2e-cli-1` which caused the CI size check to get stuck in a pending state.
> [10.2.x] ci: provide names for nightly E2E jobs

- packages/schematics/angular/application/schema.json
- packages/schematics/angular/ng-new/schema.json
- packages/schematics/angular/workspace/schema.json
- tests/legacy-cli/e2e/tests/build/strict-mode.ts
With this change we workspaces are generated strict by default. To create non-strict workspace the `--no-strict` command line option.
> feat(@schematics/angular): strict mode by default

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/bundle-calculator.ts
- packages/angular_devkit/build_angular/src/utils/bundle-calculator_spec.ts
- packages/angular_devkit/build_angular/src/webpack/utils/async-chunks.ts
- packages/angular_devkit/build_angular/src/webpack/utils/async-chunks_spec.ts
- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
The `Stats.ToJsonOutput` type is not present in the Webpack 5 typings. There was also a large amount of forced typing in the code to successfully compile.
Minimal Webpack JSON stat types are now used that represent the fields used by the tooling.
> refactor(@angular-devkit/build-angular): remove usage of Webpack Stats.ToJsonOutput type

- packages/angular/cli/commands/update-impl.ts
Failure to resolve a migration package from the workspace root will now not crash and instead error with a message.  Verbose logging (`--verbose`) is also added to provide more details regarding the resolution process.
> fix(@angular/cli): improve error logging when resolving update migrations

- packages/angular_devkit/build_angular/src/utils/version.ts
The integration tests run in the framework repo use `0.0.0` as version and not a previously stated `0.0.0-PLACEHOLDER`
> build: changer angular packages local version to `0.0.0`

- packages/angular/cli/models/analytics.ts
Since angular.io/analytics supports HTTPS, why not use that instead of HTTP?
> Switch angular.io from HTTP to HTTPS

- etc/api/angular_devkit/build_optimizer/src/_golden-api.d.ts
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-loader.ts
- packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-plugin.ts
The `@angular-devkit/build-optimizer` package now officially supports Webpack 5.
Webpack 4 support is temporarily maintained while the remainder of the tooling is transitioned.
> feat(@angular-devkit/build-optimizer): support Webpack 5

- packages/angular/cli/bin/ng
> fix(@angular/cli): ensure odd number Node.js version message is a warning

- packages/angular/cli/commands/update-impl.ts
Some schematic only packages may not have entry points defined (`main`/`exports`).  These type of packages will now be correctly resolved when attempting to locate update migrations.
Fixes #20032
> fix(@angular/cli): support update migration packages with no entry points

- etc/api/angular_devkit/build_optimizer/src/_golden-api.d.ts
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-plugin.ts
- packages/angular_devkit/build_optimizer/src/webpack.d.ts
This change provides both Webpack 4 and 5 compatible types for the the build optimizer Webpack plugin.
> refactor(@angular-devkit/build-optimizer): improve transitional Webpack 5 compatibility

- scripts/build.ts
Several test case files were unintentionally being published with the `@angular/core` package.
> build: exclude workspace json test files from core package

- packages/ngtools/webpack/src/ivy/plugin.ts
Pruning rebuild requests containing Windows paths could potentially fail if not normalized.
This is a backport of the same fix for 12.x from #20037 (second commit)
> fix(@ngtools/webpack): normalize paths when pruning AOT rebuild requests

- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-12/remove-emit-decorator-metadata.ts
- packages/schematics/angular/migrations/update-12/remove-emit-decorator-metadata_spec.ts
Add migration to remove 'emitDecoratorMetadata' TypeScript compiler option. Decorator metadata is no longer needed by Angular.
Read more about this option here: https://www.typescriptlang.org/docs/handbook/decorators.html#metadata
> feat(@schematics/angular): add migration to remove emitDecoratorMetadata

- packages/schematics/angular/universal/files/src/__main@stripTsExtension__.ts.template
- packages/schematics/angular/universal/index_spec.ts
In angular/angular#40559, a new `@angular/platform-server/shims` entry-point was introduced, which can be used to shim the server environment with APIs normally provided by the browser (such as DOM globals).
If the project is using a version of Angular (and thus `@angular/platform-server`) that is known to include this new entry-point, the newly generated `main.server.ts` file should import it at the top in order to ensure that the shims will be available as soon as possible (before other direct or transitive imports that may rely on them). See also angular/angular#40559 for more details.
NOTE:
This `universal` schematic is the base for `app-shell`, `@nguniversal/express-engine` and `@nguniversal/hapi-engine`.
> feat(@schematics/angular): augment `universal` schematics to import `platform-server` shims

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
In version 4, LESS did a breaking change that set `parens-division` as the default math setting. With this change we change the behavior to mimic version 3.5.
See: https://github.com/less/less.js/releases/tag/v4.0.0
**Note**: In Angular CLI version 12, the math setting will be the default provided by the LESS compiler in v4.0.0
Closes #20088
> fix(@angular-devkit/build-angular): force less version 3.5 math behaviour

- packages/angular_devkit/build_angular/src/browser/specs/lazy-module_spec.ts
- packages/angular_devkit/build_angular/src/browser/tests/options/named-chunks_spec.ts
This change adds expanded unit tests for the browser builder's `namedChunks` option using the builder test harness.
> test(@angular-devkit/build-angular): add browser builder namedChunks option tests

- packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
When building an application or testing a library. TypeScript declarations are not needed.
Closes #20103
> fix(@angular-devkit/build-angular): disable declaration and declarationMap

- packages/angular_devkit/build_angular/src/browser/tests/options/tsconfig_spec.ts
The `tsconfig` browser builder option unit test was unintentionally loading all development typings.
> test(@angular-devkit/build-angular): avoid loading dev typings in unit test

- packages/ngtools/webpack/src/angular_compiler_plugin.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
This change reduces the number of different Webpack resolver factory hooks required to initialize the compiler plugins.
Webpack 5 also requires the path plugin to be configured earlier in the process and the options hook provides that ability.
> refactor(@ngtools/webpack): initialize paths plugin in resolve options hook

- docs/design/build-system-overview.dot
When I was looking at different documents I found out that graph wasn't working anymore. 
This PR should resolve this, I don't believe I've seen a issue around this.
> docs: fix build-system-overview graph

- packages/angular_devkit/build_angular/src/browser/index.ts
Previously the `Index html generation complete` and `Service worker generation complete` where displayed multiple times when localization was enabled.
> fix(@angular-devkit/build-angular): only show index and service worker status once

- lib/packages.ts
- packages/angular/cli/utilities/package-manager.ts
- tests/legacy-cli/e2e/tests/misc/npm-7.ts
npm 7.5.6 contains several fixes that allow it to work successfully with the Angular CLI.
The minimum npm engine value is now set to support npm versions greater than 7.5.6 (npm 6 support remains unchanged).
A warning will be shown to users with npm 7 versions less than 7.5.6 when used with the new, add, or update commands.
Closes #19957
> fix(@angular/cli): remove npm 7 incompatibility notification

- lib/packages.ts
- packages/angular/cli/utilities/package-manager.ts
- tests/legacy-cli/e2e/tests/misc/npm-7.ts
npm 7.5.6 contains several fixes that allow it to work successfully with the Angular CLI.
The minimum npm engine value is now set to support npm versions greater than 7.5.6 (npm 6 support remains unchanged).
A warning will be shown to users with npm 7 versions less than 7.5.6 when used with the new, add, or update commands.
(cherry picked from commit 065ac4546fbb4928245609d52c1f6d81fdd48cb9)
> [11.2.x] fix(@angular/cli): remove npm 7 incompatibility notification

- lib/packages.ts
- packages/angular/cli/commands/new-impl.ts
- packages/angular/cli/models/schematic-command.ts
- packages/angular/cli/utilities/package-manager.ts
- tests/legacy-cli/e2e/tests/misc/npm-7.ts
npm 7.5.6 contains several fixes that allow it to work successfully with the Angular CLI.
The minimum npm engine value is now set to support npm versions greater than 7.5.6 (npm 6 support remains unchanged).
A warning will be shown to users with npm 7 versions less than 7.5.6 when used with the new, add, or update commands.
> [9.1.x] fix(@angular/cli): remove npm 7 incompatibility notification

- lib/packages.ts
- packages/angular/cli/commands/new-impl.ts
- packages/angular/cli/models/schematic-command.ts
- packages/angular/cli/utilities/package-manager.ts
- tests/legacy-cli/e2e/tests/misc/npm-7.ts
npm 7.5.6 contains several fixes that allow it to work successfully with the Angular CLI.
The minimum npm engine value is now set to support npm versions greater than 7.5.6 (npm 6 support remains unchanged).
A warning will be shown to users with npm 7 versions less than 7.5.6 when used with the new, add, or update commands.
> [10.2.x] fix(@angular/cli): remove npm 7 incompatibility notification

- docs/process/release.md
Today when releasing v9 and v10, I found two extra files in Git (`.husky/` and `.ng-dev.log`). These are a part of the toolchain in later versions, but not known ignored in older versions. Using `git commit -a` would have included both of those files in the release commit which would not be desirable. Instead, the solution for releases is to add the specific files that are modified to remove this possibility.
I'll do a separate PR to back-port the `.gitignore` updates to those branches and start a broader discussion about how we should manage `.gitignore` for LTS branches.
cc @kyliau @josephperrott for visibility to other caretakers.
> docs: use specific `git add` command to avoid adding unnecessary files

- tests/legacy-cli/e2e/tests/basic/e2e.ts
- tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
- tests/legacy-cli/e2e/tests/generate/library/library-consumption-linker.ts
- tests/legacy-cli/e2e/tests/misc/webpack-5.ts
- tests/legacy-cli/e2e/tests/update/update-8.ts
- tests/legacy-cli/e2e/utils/assets.ts
- tests/legacy-cli/e2e/utils/packages.ts
- tests/legacy-cli/e2e/utils/project.ts
This changes the E2E test project setup to reuse the repository's existing puppeteer chrome instance and already downloaded chrome driver.  Previously puppeteer was added to each E2E test project which required an additional download of both chrome and an associated chromedriver.  Downloads previously needed to occur multiple times during the test process due to tests changing/removing the test project's node modules directory.
> test(@angular/cli): reuse chrome/chromedriver in E2E tests

- package.json
- packages/angular_devkit/build_optimizer/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/utility/latest-versions.ts
- packages/schematics/schematics/schematic/files/package.json
- yarn.lock
TypeScript v4.1.3 and below are susceptible to a security risk involving
language service plugin loading.
https://github.com/microsoft/TypeScript/releases/tag/v4.1.4
Note typescript in `master` branch has already been updated.
> build: bump typescript to 4.1.5 due to security issue

- .circleci/config.yml
- .circleci/env.sh
Initial use of CircleCI matrix support to reduce the amount of configuration needed.  Expanded use should be possible in the future with further refactoring of the workflow.
> ci: use CircleCI matrix support for E2E jobs

- tests/legacy-cli/e2e/tests/basic/e2e.ts
- tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
- tests/legacy-cli/e2e/tests/generate/library/library-consumption-linker.ts
- tests/legacy-cli/e2e/tests/misc/webpack-5.ts
- tests/legacy-cli/e2e/tests/update/update-8.ts
- tests/legacy-cli/e2e/utils/assets.ts
- tests/legacy-cli/e2e/utils/packages.ts
- tests/legacy-cli/e2e/utils/project.ts
This changes the E2E test project setup to reuse the repository's existing puppeteer chrome instance and already downloaded chrome driver.  Previously puppeteer was added to each E2E test project which required an additional download of both chrome and an associated chromedriver.  Downloads previously needed to occur multiple times during the test process due to tests changing/removing the test project's node modules directory.
(cherry picked from commit 206d62ab7dc0aa55d86598686114651095be05c1)
> [11.2.x] test(@angular/cli): reuse chrome/chromedriver in E2E tests

- tests/legacy-cli/e2e/setup/010-local-publish.ts
- tests/legacy-cli/e2e/setup/100-global-cli.ts
- tests/legacy-cli/e2e/setup/500-create-project.ts
- tests/legacy-cli/e2e/tests/commands/add/registry-option.ts
- tests/legacy-cli/e2e/tests/misc/ask-analytics-install.ts
- tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
- tests/legacy-cli/e2e/tests/misc/npm-7.ts
- tests/legacy-cli/e2e/tests/misc/webpack-5.ts
- tests/legacy-cli/e2e/tests/schematics_cli/basic.ts
- tests/legacy-cli/e2e/tests/schematics_cli/blank-test.ts
- tests/legacy-cli/e2e/tests/schematics_cli/schematic-test.ts
- tests/legacy-cli/e2e/utils/assets.ts
- tests/legacy-cli/e2e/utils/project.ts
- tests/legacy-cli/e2e_runner.ts
E2E test registry configuration to ensure that package managers use the test registry during tests is now moved out of the tests and into the setup phase.
> test(@angular/cli): centralize E2E test registry configuration

- tests/legacy-cli/e2e/tests/basic/e2e.ts
- tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
- tests/legacy-cli/e2e/utils/project.ts
This changes the E2E test project setup to reuse the repository's existing puppeteer chrome instance and already downloaded chrome driver.  Previously puppeteer was added to each E2E test project which required an additional download of both chrome and an associated chromedriver.  Downloads previously needed to occur multiple times during the test process due to tests changing/removing the test project's node modules directory.
(cherry picked from commit 206d62ab7dc0aa55d86598686114651095be05c1)
> [10.2.x] test(@angular/cli): reuse chrome/chromedriver in E2E tests

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/utils/normalize-optimization.ts
Critical CSS inlining is now enabled by default. If you wish to turn this off set `inlineCritical` to `false`.
See: https://angular.io/guide/workspace-config#optimization-configuration
> feat(@angular-devkit/build-angular): enable inlineCritical by default

- packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
When critical font rules are not inlined it will cause blinking as during first render the fallback font will be rendered.
Related to https://github.com/angular/universal/issues/2002
> fix(@angular-devkit/build-angular): inline critical font-face rules when using critical css inlining

- .circleci/config.yml
- tests/legacy-cli/e2e/tests/basic/e2e.ts
- tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
- tests/legacy-cli/e2e/utils/project.ts
This changes the E2E test project setup to reuse the repository's existing puppeteer chrome instance and already downloaded chrome driver.  Previously puppeteer was added to each E2E test project which required an additional download of both chrome and an associated chromedriver.  Downloads previously needed to occur multiple times during the test process due to tests changing/removing the test project's node modules directory.
(cherry picked from commit 206d62ab7dc0aa55d86598686114651095be05c1)
> [9.1.x] test(@angular/cli): reuse chrome/chromedriver in E2E tests

- tests/legacy-cli/e2e/tests/generate/application/application-basic.ts
- tests/legacy-cli/e2e/tests/generate/library/library-basic.ts
- tests/legacy-cli/e2e/utils/project.ts
This change removes the attempted addition of the `karma-chrome-launcher` package which is already present in new projects.
The karma configuration custom launcher section is also no longer added and instead `ChromeHeadless` is configured as the default browser which removes the need to modify the Angular workspace configuration to add the custom browser launcher.
> test(@angular/cli): minimize project changes during E2E project CI setup

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
This change ensures that hidden source maps will be propagated through the loader chain and are extracted for global stylesheets.  This is also needed to allow hidden source maps to function with Webpack 5.
> refactor(@angular-devkit/build-angular): only inline component stylesheet sourcemaps

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
The custom babel loader allows files to be conditionally processed by the i18n inlining transforms based on both file path and content.
By allowing content based checks, the entire babel parse/transform/print process can be skipped for files that do not contain localizations.
Closes: #18398
> refactor(@angular-devkit/build-angular): use custom babel loader for i18n dev-server support

- packages/angular_devkit/core/src/utils/array.ts
- packages/angular_devkit/core/src/utils/object.ts
The `clean` and `mapObject` utility functions are unused by the Angular CLI.
> refactor(@angular-devkit/core): deprecate unused utility functions

- etc/api/angular_devkit/core/src/_golden-api.d.ts
- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/architect/node/node-modules-architect-host.ts
- packages/angular_devkit/build_angular/src/testing/builder-harness.ts
- packages/angular_devkit/core/src/workspace/definitions.ts
- packages/angular_devkit/core/src/workspace/json/reader.ts
- packages/angular_devkit/core/src/workspace/json/writer.ts
- tests/legacy-cli/e2e/tests/misc/target-default-configuration.ts
With this change, the architect can be configured to use a default configuration when it's not provided as part of the target.
Consider the below, where `defaultConfiguration` is configured to `production`. Running `ng build` will be invoked with "production" configuration.
```js
"build": {
"builder": "@angular-devkit/build-angular:browser",
"defaultConfiguration": "production",
"options": {
...
},
"configurations": {
"production": {
...
}
}
}
```
>  feat(@angular-devkit/architect): add implementation for defaultConfiguration

- packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
> fix(@angular-devkit/build-angular): only remove nomodule and defer attributes empty values

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/schematics/angular/application/schema.json
- packages/schematics/angular/ng-new/schema.json
Internet Explorer 11 support is deprecated and will be removed in future versions of the Angular CLI.
> feat(@angular-devkit/build-angular): show warning during build when project requires IE 11 support

- packages/angular/cli/commands/deploy-impl.ts
- packages/angular/cli/models/architect-command.ts
- packages/angular/cli/models/command.ts
Errors caused by invalid options or workspace configuration will now be presented as fatal console messages and the CLI will exit gracefully with an exit code of 1.
This prevents the `An unhandled exception occurred` messaging on errors that are actually handled.
> fix(@angular/cli): avoid exceptions for expected errors in architect commands

- packages/angular/cli/commands/add-impl.ts
- packages/angular/cli/commands/add.json
- packages/angular/cli/utilities/prompt.ts
- tests/legacy-cli/e2e/tests/build/material.ts
- tests/legacy-cli/e2e/tests/commands/add/add-material.ts
- tests/legacy-cli/e2e/tests/commands/add/add-pwa-yarn.ts
- tests/legacy-cli/e2e/tests/commands/add/add-pwa.ts
- tests/legacy-cli/e2e/tests/commands/add/add-version.ts
- tests/legacy-cli/e2e/tests/commands/add/add.ts
- tests/legacy-cli/e2e/tests/commands/add/dir.ts
- tests/legacy-cli/e2e/tests/commands/add/file.ts
- tests/legacy-cli/e2e/tests/commands/add/peer.ts
- tests/legacy-cli/e2e/tests/commands/add/registry-option.ts
- tests/legacy-cli/e2e/tests/commands/add/version-specifier.ts
- tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
The `ng add` command will now ask the user to confirm the package and version prior to installing and executing an uninstalled package.
This new behavior allows a user to abort the action if the version selected is not appropriate or if a typo occurred on the command line and an incorrect package would be installed.
A `--skip-confirmation` option has been added to skip the prompt and directly install and execute the package. This option is useful in CI and non-TTY scenarios such as automated scripts.
> feat(@angular/cli): confirm ng add action before installation

- packages/ngtools/webpack/src/ivy/host.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
This change augments a TypeScript Compiler Host's resolveModuleNames function to collect dependencies of the containing file based on the module names passed to the resolveModuleNames function. This process assumes that consumers of the Compiler Host will call resolveModuleNames with modules that are actually present in a containing file.  The TypeScript compiler exhibits such behavior making this process effective at generating a set of all direct dependencies for a given source file.
This process is a workaround for gathering a TypeScript SourceFile's dependencies as there is no currently exposed public method to do so. A BuilderProgram does have a `getAllDependencies` function. However, that function returns all transitive dependencies as well which can cause excessive Webpack rebuilds …
> perf(@ngtools/webpack): avoid adding transitive dependencies to Webpack's dependency graph

- integration/angular_cli/src/app/app.component.html
- integration/angular_cli/src/environments/environment.ts
- packages/schematics/angular/application/files/src/environments/environment.ts.template
- packages/schematics/angular/application/other-files/app.component.html.template
As the `--prod` is now deprecated, and `ng build` uses by default the `production` configuration,
then we should remove the references to `ng build --prod` in the generated project.
> fix(@schematics/angular): remove references to the prod flag

- packages/ngtools/webpack/src/ivy/plugin.ts
The deprecated lazy route string form requires code analysis prior to each build to locate any lazy routes and connect them with Webpack.
This change uses the previous fast but less accurate AST based lazy route discovery for JIT rebuilds. The first build will still perform a full Angular compiler analysis to ensure an accurate list of all initial deprecated string form lazy routes.
> perf(@ngtools/webpack): avoid full compiler lazy route analysis on JIT rebuilds

- packages/ngtools/webpack/src/ivy/host.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
This change augments a TypeScript Compiler Host's resolveModuleNames function to collect dependencies of the containing file based on the module names passed to the resolveModuleNames function. This process assumes that consumers of the Compiler Host will call resolveModuleNames with modules that are actually present in a containing file.  The TypeScript compiler exhibits such behavior making this process effective at generating a set of all direct dependencies for a given source file.
This process is a workaround for gathering a TypeScript SourceFile's dependencies as there is no currently exposed public method to do so. A BuilderProgram does have a `getAllDependencies` function. However, that function returns all transitive dependencies as well which can cause excessive Webpack rebuilds …
> [11.2.x] perf(@ngtools/webpack): avoid adding transitive dependencies to Webpack's dependency graph

- tsconfig.json
Since we no longer support Node.JS 10 we can ship our code in ES2019
See: https://node.green/#ES2019
> build: update Angular CLI repo to use ES2019

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
This ensures that vendor sourcemaps are not loaded from file when they have not been previously loaded via sourcemap-loader.
When vendor sourcemap is enabled, `inputSourceMap` is not needed, since the sourcemap is already available and the `sourceMappingURL` comment is removed from source.
> fix(@angular-devkit/build-angular): don't load an input sourcemap from file when using Babel

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
Skip  `async` transformation when the path matches a FESM2015 entrypoint.  Ng-packagr doesn't allow changing the script target for entry-points which makes this possible https://github.com/ng-packagr/ng-packagr/blob/master/src/lib/ng-package/entry-point/compile-ngc.transform.ts#L48
This is important to reduce greatly the cold build performance overhead when targeting ES2017+
> perf(@angular-devkit/build-angular): skip FESM2015 from `async` transformation

- packages/ngtools/webpack/src/ivy/plugin.ts
This change uses the newly introduced precalculated file dependencies for each TypeScript file instead of querying TypeScript for the SourceFile's dependencies when performing the unused file check at the end of the build cycle. This change removes the need to recalculate the dependencies for each TypeScript file present in the Webpack compilation.
> [11.2.x] perf(@ngtools/webpack): use precalculated dependencies in unused file check

- packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts
Webpack's `Stats.toJson` function is an expensive operation and is recommended to be avoided where possible. In the case of the karma plugin, the compilation errors can be accessed directly without the need for the function call.
> perf(@angular-devkit/build-angular): remove Webpack Stats.toJson usage in karma plugin

- packages/schematics/angular/application/other-files/app.component.html.template
change youtube icon style from `margin-left: 16px;` to `margin: 0 16px;`
to be like this 
instead of this
> fix(@schematics/angular): fix youtube icon margin

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
Workaround for https://github.com/babel/babel-loader/pull/896
> perf(@angular-devkit/build-angular): enforce Babel not to load sourcemaps from file

- packages/schematics/angular/ng-new/index.ts
…
This ensures that the deprecate warning is only displayed when the option is used.
> fix(@schematics/angular): only show legacy browsers deprecation warning when option is used

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/server/index.ts
- packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts
- packages/angular_devkit/build_webpack/src/webpack/index.ts
This change adds the output path for the Webpack build directly to the result of the builder. This removes one of the reasons for using the Webpack JSON stats object which is expensive to generate.
> feat(@angular-devkit/build-webpack): provide output path in builder results

- packages/schematics/angular/application/schema.json
- packages/schematics/angular/component/schema.json
- packages/schematics/angular/ng-new/schema.json
This commit remove "Native" value from `viewEncapsulation` option in `ng new`, `ng generate application` and `ng generate component`.
Has been removed here: [#38882](https://github.com/angular/angular/pull/38882)
> fix(@schematics/angular): remove Native value from viewEncapsulation option

- packages/ngtools/webpack/src/resource_loader.ts
The resource loader used to process component styles and templates has been changed to be fully typed and to leverage more of Webpack's child compilation APIs.
The later of which removes the need to manually propagate most information from the child compilation to the parent compilation.
> refactor(@ngtools/webpack): reduce complexity of resource loader processing

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/babel-bazel.d.ts
- packages/angular_devkit/build_angular/src/typings.d.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- tsconfig.json
- yarn.lock
When using the `statsJson` browser builder option, the resulting JSON data is now streamed into a file instead of written in one large block.  This mitigates crashes due to the generated string exceeded the Node.js limit.
Fixes #20271
> fix(@angular-devkit/build-angular): support writing large Webpack stat output

- packages/ngtools/webpack/src/resource_loader.ts
This change adds support for using the Webpack `processAssets` hook to handle the resource loader child compilation's assets. This new hook is the recommended way to process assets in Webpack 5+.
> fix(@ngtools/webpack): remove Webpack 5 deprecation warning in resource loader

- packages/angular_devkit/build_angular/src/test-utils.ts
Previously, if a browser build failed using the `browserBuild` test utility function, the test utility would try to access properties that did not exist and would crash. This increased the complexity to debug failing tests. With the new behavior, the `browserBuild` test utility will return with an empty `files` object and the failed builder result.
> test(@angular-devkit/build-angular): avoid crashing during test failure in utility function

- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/extract-i18n/schema.json
We recently added a new message format called `legacy-extract` that is used to migrate between legacy and canonical message IDs (see https://github.com/angular/angular/pull/41026).
These changes expose the new format in `extract-i18n`.
> feat(@angular-devkit/build-angular): expose legacy-migrate message format

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/babel-bazel.d.ts
- packages/angular_devkit/build_angular/src/typings.d.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- tsconfig.json
- yarn.lock
When using the `statsJson` browser builder option, the resulting JSON data is now streamed into a file instead of written in one large block.  This mitigates crashes due to the generated string exceeded the Node.js limit.
> [11.2.x] fix(@angular-devkit/build-angular): support writing large Webpack stat outputs

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/core/src/workspace/json/utilities.ts
- packages/ngtools/webpack/package.json
- packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
- packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
- packages/schematics/angular/utility/latest-versions.ts
- packages/schematics/schematics/schematic/files/package.json
- tests/legacy-cli/e2e/setup/500-create-project.ts
- tests/legacy-cli/e2e/utils/project.ts
- yarn.lock
BREAKING CHANGE
Drop support for TypeScript versions prior to 4.2.3
> feat(@angular/cli): support TypeScript 4.2

- docs/process/release.md
In today's release, running `yarn` modified the `yarn.lock` file, which is not desireable for releases which should be as close to CI as possible. This updates the docs to freeze the lockfile (similar to `npm ci`) to avoid changing dependency verisons mid-release.
/cc Caretakers for release (@kyliau and @josephperrott).
> doc: update `yarn` command to freeze lockfile.

- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- tests/legacy-cli/e2e/tests/generate/library/library-consumption-linker.ts
With this change we intergate JIT mode linker into the Angular CLI.
Closes #20281
> feat(@angular-devkit/build-angular): integrate JIT mode linker

- scripts/templates/changelog.ejs
Previously `a.type - b.type` always returned NaN, which broke sorting
> build: sort changelog by commit message scope

- packages/ngtools/webpack/src/ivy/host.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
- packages/ngtools/webpack/src/resource_loader.ts
During JIT mode, deprecated string-form lazy routes are discovered by analyzing the application via the compiler-cli.
This process, however, does not need any of the component resources nor does the CLI need to load them. In JIT mode,
a no-op resource loader is now used that will provide the compiler with blank templates and styles. This can greatly
reduce the amount of processing required during an initial JIT build, especially for large projects.
> perf(@ngtools/webpack): reduce resource processing during JIT initial lazy route analysis

- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-12/production-default-config.ts
- packages/schematics/angular/migrations/update-12/production-default-config_spec.ts
- packages/schematics/angular/utility/workspace-models.ts
With this change we add an optional migration to update Angular CLI workspace configurations to 'production' mode by default.
To run this migration use the below commands
```
ng update @angular/cli
ng update @angular/cli --migrate-only production-by-default
```
> feat(@schematics/angular): add production by default optional migration

- docs/process/release.md
- lib/packages.ts
- package.json
- packages/schematics/angular/utility/latest-versions.ts
- scripts/packages.ts
- scripts/publish.ts
Currently, the version of a release is determined by the git tag.
This PR changes the release script to determine the release version from the
`version` property in the root `package.json`.
With this change, the caretaker will have to update the version in both
`package.json` and `latest-versions.ts` **after** the release.
Release doc has also been updated.
> build: determine release version from package.json instead of git tag

- docs/process/release.md
- lib/packages.ts
- package.json
- packages/schematics/angular/utility/latest-versions.ts
- scripts/packages.ts
- scripts/publish.ts
This is patch PR for #20353 
Currently, the version of a release is determined by the git tag.
This PR changes release script to determine the release version from the
`version` property in the root `package.json`.
Release docs have also been updated.
> build: determine version to publish from package.json

- packages/angular_devkit/build_angular/src/browser/tests/behavior/rebuild-errors_spec.ts
- packages/angular_devkit/build_angular/test/hello-world-app/tsconfig.json
- packages/ngtools/webpack/src/ivy/cache.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
This change improves the performance of incremental type checking of Angular templates by reducing the number of calls to retrieve the diagnostics.
Only the set of affected files will be queried on a rebuild. The affected set includes files TypeScript deems affected, files that
are required to be emitted by the Angular compiler, and the original file for any TTC shim file that TypeScript deems affected.
> perf(@ngtools/webpack): only check affected files for Angular semantic diagnostics

- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/karma/schema.json
> fix(@angular-devkit/build-angular): validate scripts and styles bundleName

- .circleci/config.yml
- .github/angular-robot.yml
- packages/angular_devkit/build_angular/BUILD.bazel
With the upcoming removal of View Engine support for applications in version 12, the View Engine E2E test job and unit tests are no longer needed.
Only application build support for View Engine will be removed in version 12.  Libraries will continue to support View Engine to maintain backward compatibility.
> ci: remove View Engine related test jobs

- packages/schematics/angular/component/index_spec.ts
- packages/schematics/angular/directive/index_spec.ts
- packages/schematics/angular/library/index_spec.ts
- packages/schematics/angular/pipe/index_spec.ts
- packages/schematics/angular/service-worker/index.ts
- packages/schematics/angular/service-worker/index_spec.ts
- packages/schematics/angular/utility/ast-utils.ts
- packages/schematics/angular/utility/ast-utils_spec.ts
- tests/legacy-cli/e2e/tests/generate/component/component-module-export.ts
- tests/legacy-cli/e2e/tests/generate/directive/directive-module-export.ts
- tests/legacy-cli/e2e/tests/generate/pipe/pipe-module-export.ts
This PR updates the `service-worker` schematics to explicitly specify the ServiceWorker registration strategy in the [ServiceWorkerModule.register()] call.
We still use the default strategy, so there should be no change in the behavior of the generated apps. However, it will help people find out what the default behavior is when debugging potential issues with delayed ServiceWorker registration.
(See the discussion in angular/angular#41223 for more details.)
##
In order to be able to do this (and format the code in a readable way), this PR also makes some updates to the `addSymbolToNgModuleMetadata()` function. See individual commits for details.
[1]: https://angular.io/api/service-worker/ServiceWorkerModule#register
> fix(@schematics/angular): explicitly specify ServiceWorker registration strategy

- packages/angular/cli/commands/version-impl.ts
- tests/legacy-cli/e2e/tests/misc/version.ts
In version 12, only Ivy will be allowed to be used to compile an application.
> refactor(@angular/cli): remove `Ivy Workspace` from `ng version`

- tests/legacy-cli/e2e/assets/webpack/test-app/package.json
- tests/legacy-cli/e2e/assets/webpack/test-app/webpack.config.js
This webpack E2E test application now uses the Ivy webpack plugin instead of the deprecated ViewEngine plugin.
> test(@ngtools/webpack): update webpack test-app E2E to use ivy plugin

- packages/ngtools/webpack/src/resource_loader.ts
The asset extraction within the Angular compiler plugin resource loader needs to occur at the end of the Webpack asset processing pipeline. This ensures that all analysis and preprocessing of the asset have been performed before the resource asset is extracted from the Webpack child compilation.
> fix(@ngtools/webpack): use correct Webpack asset stage in resource loader

- packages/angular/pwa/BUILD.bazel
- packages/angular/pwa/package.json
- packages/angular/pwa/pwa/index.ts
The `@angular-devkit/core` dependency was only used for two path manipulation functions. Since this schematic already uses Node.js builtins, the `path` builtin can also be used to provide equivalent function without the need for an additional dependency.
> refactor(@angular/pwa): remove `@angular-devkit/core` dependency

- etc/api/angular_devkit/architect/src/index.d.ts
- packages/angular_devkit/architect/src/api.ts
- packages/angular_devkit/architect/src/create-builder.ts
- packages/angular_devkit/build_webpack/BUILD.bazel
- packages/angular_devkit/build_webpack/package.json
- packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts
- packages/angular_devkit/build_webpack/src/webpack-dev-server/index_spec.ts
- packages/angular_devkit/build_webpack/src/webpack/index.ts
- packages/angular_devkit/build_webpack/src/webpack/index_spec.ts
- yarn.lock
The `json.JsonObject` generic constraint did not force the options type to be a valid JSON object but required all builders to add the `json.JsonObject` type to all builder option types when calling `createBuilder`.
> refactor(@angular-devkit/architect): remove builder option generic json constraint

- packages/angular_devkit/build_angular/src/utils/environment-options.ts
- packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
- tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts
BREAKING CHANGE: Removal of View Engine support from application builds
With the removal of the deprecated View Engine compiler in Angular version 12 for applications, Ivy-based compilation will always be used when building an application.
The default behavior for applications is to use the Ivy compiler when building and no changes are required for these applications.
For applications that have opted-out of Ivy, a warning will be shown and an Ivy-based build will be attempted. If the build fails,
the application may need to be updated to become Ivy compatible.
> fix(@angular-devkit/build-angular): remove usage of deprecated View Engine compiler

- renovate.json
This eliminates the requirement that when master is not a major we require to change the label.  `target: minor` is always get merged into master (and master only): https://github.com/angular/angular/blob/ed77bfea26e64bd24019812131e14f5dd450fcf5/docs/BRANCHES.md#pull-request-examples  hence using `target: major` is not needed in this case.
> ci: change renovate label to `target: minor`

- package.json
- yarn.lock
This updates to a version that contains the following fix https://github.com/angular/angular/pull/41430
> build: update `@angular/dev-infra-private` package

- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/extract-i18n/schema.json
- packages/schematics/angular/migrations/migration-collection.json
BREAKING CHANGE: Removal of deprecated `extract-i18n` command options
The deprecated `i18nLocale` option has been removed and the `i18n.sourceLocale` within a project's configuration should be used instead.
The deprecated `i18nFormat` option has been removed and the `format` option should be used instead.
> fix(@angular-devkit/build-angular): remove deprecated i18nLocale and i18nFormat options

- .circleci/config.yml
With this change we use yarn `--cache-folder` to make sure that yarn cache is used in all platforms. Previously on Windows we where using the wrong path which resulted in node packages not to be cached.
> ci: use `--cache-folder` to make sure that yarn cache is used

- .circleci/config.yml
All PR jobs will use Node.js v14.
A Node.js v12 E2E job is now run on release branches.
> ci: set Node.js v14 as the default version for jobs

- .circleci/config.yml
Webpack 4 profiling mode fails on Windows with Node.js 14.
> Windows CI fixes

- packages/angular/pwa/package.json
As discussed in the weekly sync meeting, promote `@angular/pwa` to stable
since it is just a schematic library and does not have public facing APIs.
> build(@angular/pwa): promote to stable

- packages/angular_devkit/build_angular/BUILD.bazel
With recent improvements to the dev-server builder unit tests, additional parallel testing should now be possible.
The unused `express` dependencies are also removed.
> test(@angular-devkit/build-angular): increase bazel shards for dev-server tests

- .circleci/config.yml
- .github/angular-robot.yml
The Windows CI test jobs are now contained within one `e2e-cli-win` job. This removes the need to start up multiple jobs to initialize Windows as well as store and retrieve the saved workspace.
The parallelism is increased to 8 and the Windows test job is started earlier in the workflow to decrease the total time for the workflow.
This change also removes the partial double Windows testing currently present on release branches due to the previous `test-win` and `e2e-cli-win` jobs.
NOTE: This requires the removal of `test-win` from the required Github checks and the addition of `e2e-cli-win`.
> ci: consolidate Windows test jobs

- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/karma/index.ts
- packages/angular_devkit/build_angular/src/karma/selected_spec.ts
With this change we update the Karma builder to use the new Server API.
Closes: #20479
> fix(@angular-devkit/build-angular): update karma builder to use non-deprecated API

- docs/process/release.md
This more clearly specifies that version bumps should have a PR which is assigned to the next caretaker. It also specifies that the caretaker should include these PRs in the hand-off to the next caretaker. If anyone who notices these links missing, they should escalate to the caretaker just to make sure this step is not forgotten. This should make it less likely for a caretaker for forget to do the post-release version bump.
/cc @josephperrott
> docs: post-release version bump PRs

- scripts/validate-licenses.ts
`Python-2.0` is in the same category as `MIT`, hence it's a valid license that we can allow.
This is needed for `verdaccio` version 5 which uses `argparse` which is licenced as `Python-2.0`.
> ci: add `Python-2.0` as a valid license

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
In some scenarios in Webpack 5 percentage goes from 1 back to 0.99, ex: 0.99 -> 1 -> 0.99 -> 1. This causes the "complete" message to be displayed multiple times.
> fix(@angular-devkit/build-angular): remove duplicate application bundle generation complete message

- .circleci/config.yml
- scripts/validate.ts
`--ci` is not used in any way.
> ci: remove unused --ci option from validate script

- packages/angular_devkit/schematics_cli/package.json
This package contains just the executable for schematics and two internal
schematics, there is no public facing APIs.
> build: promote @angular-devkit/schematics-cli to stable

- etc/api/angular_devkit/build_optimizer/src/_golden-api.d.ts
- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/analytics.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/index-html-webpack-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts
- packages/angular_devkit/build_optimizer/BUILD.bazel
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-loader.ts
- packages/ngtools/webpack/BUILD.bazel
- packages/ngtools/webpack/package.json
- packages/ngtools/webpack/src/resource_loader.ts
- yarn.lock
Webpack 5 now provides common utility functions and class as direct exports.  This includes getting a loader's options (`getOptions`) and the source classes from `webpack-sources`.
> Webpack 5 Cleanup - Remove redundant dependencies

- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/browser/tests/options/inline-style-language_spec.ts
- packages/angular_devkit/build_angular/src/karma/schema.json
- packages/angular_devkit/build_angular/src/server/schema.json
- packages/angular_devkit/build_angular/src/utils/build-options.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
- tests/legacy-cli/e2e/tests/build/differential-loading-sri.ts
- tests/legacy-cli/e2e/tests/build/worker.ts
A new build option named `inlineStyleLanguage` has been introduced that will allow a project to define the stylesheet language used in an application's inline component styles. Inline component styles are styles defined via the `styles` property within the Angular `Component` decorator. Both JIT and AOT mode are supported. However, JIT mode requires that inline styles only be string literals (compile-time partial evaluation is not supported in JIT mode). Currently supported language options are: `CSS` (default), `Sass`, `SCSS`, and `Less`. If the option is not specified, `CSS` will be used and enables existing projects to continue to function as expected.
> feat(@angular-devkit/build-angular): support specifying stylesheet language for inline component styles

- packages/angular_devkit/build_angular/src/utils/service-worker.ts
With the minimum version of Node.js now set to v12, the promise fs API can now be leveraged within the tooling.
This change also uses `copyFile` (with copy-on-write where available) to setup the the service worker files as well a streaming APIs to generate service worker hashes. Both of which improves performance and reduces memory usage.
> refactor(@angular-devkit/build-angular): use Node.js promise fs API in service-worker augmentation

- packages/angular/pwa/README.md
This mostly just copies the "Getting started with service workers" guide cited to explain what the schematic itself does and defering to that doc for more info on PWA's and how to actually build one.
> docs: add README to `@angular/pwa`.

- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-12/update-web-workers.ts
- packages/schematics/angular/migrations/update-12/update-web-workers_spec.ts
Webpack 5 now includes web worker support. However, the structure of the URL within the `Worker` constructor must be in a specific format.
A migration has been added for Angular v12 that will convert web workers from the old structure to the new structure.
Before: `new Worker('./app.worker', ...)`
After: `new Worker(new URL('./app.worker', import.meta.url), ...)`
> feat(@schematics/angular): migrate web workers to support Webpack 5

- packages/angular_devkit/architect_cli/README.md
- packages/angular_devkit/architect_cli/package.json
A `README.md` file is now included in the package with an overview of the utility and the help output of the command.
> docs(@angular-devkit/architect-cli): add a README file for the package

- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/src/commands/update/schematic/index.ts
- packages/angular/cli/src/commands/update/schematic/schema.json
**fix(@angular/cli): run all migrations when updating from or between prereleases**
With this change we consider the update schematics are idempotent. When updating from or between prereleases we will execute all migrations for the version.
**refactor(@angular/cli): clean up left over @schematics/update code**
**fix(@angular/cli): ignore `tsickle` during updates**
`tsickle` doesn't be a dependency in users projects, if it is most certain it will cause updates to fail due to mismatching peer dependency on TypeScript.
> Several `ng update` fixes

- package.json
- yarn.lock
This is needed as currently this breaks lock file maintenance Renovate  PR https://github.com/angular/angular-cli/pull/20107 due to quicktype-core has an unspecified dependency on lodash.
```
bazel-out/host/bin/tools/quicktype_runner.sh packages/angular_devkit/build_angular/src/app-shell/schema.json bazel-out/k8-fastbuild/bin/packages/angular_devkit/build_angular/src/app-shell/schema.ts)
Execution platform: //tools:rbe_ubuntu1604-angular
Error: Cannot find module 'lodash'. Please verify that the package.json has a valid "main" entry
at Function.module.constructor._resolveFilename (/b/f/w/bazel-out/host/bin/tools/quicktype_runner.sh.runfiles/angular_cli/tools/quicktype_runner_require_patch.js:480:17)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Module.require …
```
> build: pin quicktype-core

- packages/angular_devkit/build_angular/src/browser/tests/behavior/rebuild-errors_spec.ts
- packages/angular_devkit/build_angular/test/hello-world-app/tsconfig.json
- packages/ngtools/webpack/src/ivy/cache.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
This change improves the performance of incremental type checking of Angular templates by reducing the number of calls to retrieve the diagnostics.
Only the set of affected files will be queried on a rebuild. The affected set includes files TypeScript deems affected, files that
are required to be emitted by the Angular compiler, and the original file for any TTC shim file that TypeScript deems affected.
Patch version of #20348
Closes #20558
> [11.2.x] perf(@ngtools/webpack): only check affected files for Angular semantic diagnostics

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/karma/index.ts
- packages/angular_devkit/build_angular/src/server/index.ts
- packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
- tests/legacy-cli/e2e/tests/build/differential-loading-sri.ts
- tests/legacy-cli/e2e/tests/build/worker.ts
TypeScript files had the potential to be processed twice by the build optimizer. This did not affect the output code but could lead to longer production build times. The build optimizer is now configured in one centralized location for both TypeScript and JavaScript files. The Webpack configuration partial for TypeScript support is also reduced to one common function for both AOT and JIT as a result.
> fix(@angular-devkit/build-angular): avoid double build optimizer processing

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/universal/index.ts
The `style` option for the application schematic specifies the language/preprocessor to use for the application's external style files and should also setup the default for inline styles as well via the `inlineStyleLanguage` build option. The value can be adjusted after application generation if needed.
> fix(@schematics/angular): set `inlineStyleLanguage` when application `style` option is used

- packages/schematics/angular/README.md
- packages/schematics/angular/class/schema.json
- packages/schematics/angular/component/schema.json
- packages/schematics/angular/directive/schema.json
- packages/schematics/angular/interface/schema.json
- packages/schematics/angular/library/schema.json
- packages/schematics/angular/module/schema.json
- packages/schematics/angular/ng-new/schema.json
- packages/schematics/angular/package.json
- packages/schematics/angular/pipe/schema.json
- packages/schematics/angular/web-worker/schema.json
- packages/schematics/angular/workspace/schema.json
Create README for the package, and add missing description in some schema.
Closes: https://github.com/angular/angular-cli/issues/13315
> docs(@schematics/angular): add README and update description in schema

- .github/angular-robot.yml
Previously, running `yarn ng-dev caretaker check` would fail with `Multi-line double-quoted string needs to be sufficiently indented`.
> ci: format angular-robot configuration

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
The Webpack 5 automatic public path support can cause an incorrect public path to be used to load assets and lazy loaded routes. The current logic relies on the last script element found at runtime in the application's index HTML which may not be related to the application scripts. Now if a `deployUrl` is not specified, the Webpack `publicPath` option is defaulted to an empty string which provides equivalent behavior to Webpack 4.
> fix(@angular-devkit/build-angular): disable Webpack 5 automatic public path support

- docs/process/release.md
- packages/schematics/angular/utility/latest-versions.ts
Now that `@angular-devkit/build-angular` is promoted to stable
(https://github.com/angular/angular-cli/pull/20528), it will
always have the same version as `@schematics/angular`.
With this change, there is no need to manually update `DevkitBuildAngular`
field in `latest-versions.ts` anymore.
> refactor(@schematics/angular): read build-angular's version from package.json

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
The GC caching mode will remove any unused cache entries after each rebuild. This prevents old modules from being retained indefinitely during long-lived development sessions.
> perf(@angular-devkit/build-angular): use Webpack's GC memory caching in watch mode

- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
The current stable version of `webpack-dev-server` does not fully handle Webpack 5's configuration options. In this case, the `target` option can now be an array. However, the array form is ignored by the dev server which can cause the live reload client code to not be included in the output bundles. To remedy this, the `injectClient` option is used when live reload is enabled which forces the client code to be included regardless of the `target` option.
> fix(@angular-devkit/build-angular): always inject live reload client when using live reload

- packages/ngtools/webpack/src/ivy/cache.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
Webpack 5 directly provides the set of modified and removed files. This feature allows for the removal of the file timestamp logic within the plugin that was previously used to generated the set of changed files on a rebuild.
> refactor(@ngtools/webpack): use Webpack 5 modified/removed file sets for changed list

- packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
When using the `ContextReplacementPlugin` https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/webpack/configs/common.ts#L496 the new resource path will be watched by Webpack file watcher. This causes a redundant file remove event after the first build, which causes another partial rebuild right way.
Note: changing the call to ` new ContextReplacementPlugin(/\@angular(\\|\/)core(\\|\/)/);` doesn't address the problem.
> fix(@angular-devkit/build-angular): avoid triggering file change after file build

- packages/schematics/angular/e2e/index.ts
- packages/schematics/angular/workspace/files/package.json.template
The dependency is only needed for protractor tests, so it should only be added by the e2e schematics.
> fix(@schematics/angular): remove jasmine-spec-reporter from default workspace

- packages/schematics/angular/application/other-files/app.component.html.template
As Protractor is no longer used by default, maybe it could be removed from the home page?
> fix(@schematics/angular): remove Protractor from home page

- packages/angular_devkit/build_angular/src/karma/index.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts
With this change we now use Webpack memory cache when running Karma in watch mode.
> perf(@angular-devkit/build-angular): improve incremental time during Karma tests

- packages/angular_devkit/core/src/json/schema/registry.ts
> fix(@angular-devkit/core): improve handling of set schema values

- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
With this change we configure `webpack-dev-middleware` and `webpack-dev-server` to print errors to the console, which previously were not displayed. This is because both of these libraries log/emit errors using the logger and the compilation API.
Certain errors such as the one below, were being swallowed during `ng serve`.
```
An unhandled exception occurred: Prevent writing to file that only differs in casing or query string from already written file.
This will lead to a race-condition and corrupted files on case-insensitive file systems.
/home/circleci/ng/aio/dist/generated/docs/api/router/Routes.json
/home/circleci/ng/aio/dist/generated/docs/api/router/ROUTES.json
```
> fix(@angular-devkit/build-angular): output webpack-dev-server and webpack-dev-middleware errors

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
Library code inside fesm2015/esm2015/_esm2015 directories has been downlevelled to ES2015 which will not have native async/await. As a result, code from those directories can be skipped from the additional checks as well as the downlevel processing. RxJS uses the `_esm2015` directory naming convention.
> perf(@angular-devkit/build-angular): avoid async downlevel for known ES2015 code

- renovate.json
With this change we configure renovate to group all non-major dependencies and create a single PR
> ci: configure renovate to group all non-major dependencies

- packages/schematics/angular/workspace/files/package.json.template
Angular 12 does not provide the default linter but CLI adds the ng lint
this PR removes the ng lint from new app created
Fixes #20618
> fix(@schematics/angular) remove lint command from package.json

- renovate.json
This is needed as currently this breaks lock file maintenance Renovate  PR https://github.com/angular/angular-cli/pull/20107 due to quicktype-core has an unspecified dependency on lodash.
```
bazel-out/host/bin/tools/quicktype_runner.sh packages/angular_devkit/build_angular/src/app-shell/schema.json bazel-out/k8-fastbuild/bin/packages/angular_devkit/build_angular/src/app-shell/schema.ts)
Execution platform: //tools:rbe_ubuntu1604-angular
Error: Cannot find module 'lodash'. Please verify that the package.json has a valid "main" entry
at Function.module.constructor._resolveFilename (/b/f/w/bazel-out/host/bin/tools/quicktype_runner.sh.runfiles/angular_cli/tools/quicktype_runner_require_patch.js:480:17)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Module.require …
```
> ci: configure Renovate to ignore quicktype-core

- renovate.json
Renovate creates better commit message.
> ci: remove `commitMessage` from Renovate configuration

- packages/angular_devkit/build_angular/src/utils/action-executor.ts
We now don't support Node 10 hence `worker_threads` are always available.
> refactor(@angular-devkit/build-angular); remove old worker_threads detection

- README.md
- lib/packages.ts
- package.json
- packages/angular/cli/bin/ng
- packages/angular/cli/lib/cli/index.ts
- scripts/templates/readme.ejs
This is to match the ranges in the framework repo.
> build: update minimum supported node.js version to 12.14

- .prettierignore
- .prettierrc
Quoted properties are now configured to be preserved within code and is needed for cases of closure compiler usage.
The ignore files list is also updated to now ignore all directories that contain code that should not be formatted; either because the code is auto-generated, an output directory, or third party vendor code.
> build: update prettier configuration and ignore files

- packages/angular/cli/commands/add-impl.ts
- packages/angular/cli/commands/extract-i18n-impl.ts
- packages/angular/cli/commands/new-impl.ts
- packages/angular/cli/commands/serve-impl.ts
- packages/angular/cli/lib/init.ts
- packages/angular/cli/models/command.ts
- packages/angular/cli/models/schematic-command.ts
- packages/angular/cli/package.json
- packages/angular/cli/src/commands/update/schematic/index.ts
This change cleans up some of the CLI code by removing unused variables/imports, unnecessary double negation, and some long line lengths.
> refactor(@angular/cli): correct various uncaught code style issues

- packages/angular/cli/utilities/config.ts
Reading throw  #16034 the angular config should be placed in the `$XDG_CONFIG_HOME/angular/` directory, but if the environmental variable $XDG_CONFIG_HOME is set the first check in the `xdgConfigHome` function will only put it in `$XDG_CONFIG_HOME` instead of the `angular/` directory.
Also renamed the config file from `.angular-config.json` to `config.json`  when it is in the `~/.config/angular/` directory since it doesn't need to be hidden.
> fix(@angular/cli): Support XDG Base Directory Specfication

- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
With this change we replace usage of the deprecated `webpack.JavascriptModulesPlugin` with `webpack.javascript.JavascriptModulesPlugin`
> refactor(@angular-devkit/build-angular): replace deprecated `webpack.JavascriptModulesPlugin`

- packages/schematics/angular/migrations/update-12/update-angular-config.ts
- packages/schematics/angular/migrations/update-12/update-angular-config_spec.ts
The value for `namedChunk` was inverted, as previously `namedChunks` default value was `true` and not `false`.
> fix(@schematics/angular): fix migration for namedChunks option

- package.json
- scripts/validate-licenses.ts
- tslint.json
- yarn.lock
The `tslint-sonarts` package is both deprecated and unmaintained. The rules provided by the package are now removed from the `tslint` configuration for the project.
> test: remove unmaintained third-party tslint rules

- .github/workflows/lock-closed.yml
The latest version fixes a runtime warning concerning an invalid configuration property.
Warning: `Unexpected input(s) 'lock-bot-key', valid inputs are ['lock-bot-token', 'locks-per-execution']`
> ci: update lock workflow action to latest sha version

- package.json
- scripts/validate-licenses.ts
- tslint.json
- yarn.lock
The `tslint-sonarts` package is both deprecated and unmaintained. The rules provided by the package are now removed from the `tslint` configuration for the project.
12.0.x variant of #20647
> [12.0.x] test: remove unmaintained third-party tslint rules

- .prettierignore
This change is needed so that new/modified E2E tests get formatted.
> test: remove `/tests/` from paths that prettier should ignore

- packages/angular_devkit/build_angular/src/webpack/plugins/optimize-css-webpack-plugin.ts
CSS declaration orders matters in some cases. This optimization is currently causing broken CSS output.
Closes #20693
> fix(@angular-devkit/build-angular): disable CSS declaration sorting optimizations

- packages/angular/cli/commands/add-impl.ts
- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/utilities/install-package.ts
With this change we change the package installation to async. This is needed as otherwise during `ng-add` the spinner gets stuck. With this change we also add the spinner in the installation methods.
> fix(@angular/cli): change package installation to async

- packages/angular/cli/models/schematic-command.ts
- packages/schematics/angular/app-shell/index.ts
- packages/schematics/angular/app-shell/index_spec.ts
- packages/schematics/angular/app-shell/schema.json
- packages/schematics/angular/migrations/update-9/update-app-tsconfigs_spec.ts
- packages/schematics/angular/migrations/update-9/update-server-main-file_spec.ts
- packages/schematics/angular/migrations/update-9/update-workspace-config_spec.ts
- packages/schematics/angular/universal/index.ts
- packages/schematics/angular/universal/index_spec.ts
- packages/schematics/angular/universal/schema.json
- tests/legacy-cli/e2e/tests/build/build-app-shell-with-schematic.ts
- tests/legacy-cli/e2e/tests/build/platform-server.ts
- tests/legacy-cli/e2e/tests/generate/schematic-defaults.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-app-shell.ts
Previously, the `--project` flag was ignored when gathering and merging the schematics defaults from the angular workspace configuration file.
Closes #20666
> fix(@angular/cli): infer schematic defaults correctly when using `--project`

- .bazelrc
- .bazelversion
- WORKSPACE
- package.json
- renovate.json
- tools/BUILD.bazel
- yarn.lock
Uses the new shared RBE platform from the dev-infra package.
We introduced a shared Bazel platform for remote execution builds
using Google cloud. Previously we used `bazel_toolchains` for
providing the platform w/ additional CPP and Java toolchains
`bazel_toolchains` no longer provides default toolchains with the
latest version, but provides a tool (linux and windows only) for
generating toolchain/platforms, which then need to be checked
into the repository. This is quite inconvenient and cumbersome
(especially with no macOS support), so we just provided our own
platform and CPP toolchain within `@angular/dev-infra-private`. This is
more simple than all the effort we'd need to make the toolchain
generation tool work (while it would also increase the amount
of checked-in sources …
> build: use platform from shared dev-infra package for remote execution

- goldens/public-api/angular_devkit/schematics/tools/index.d.ts
- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/commands/update.json
- packages/angular_devkit/schematics/tasks/package-manager/executor.ts
- packages/angular_devkit/schematics/tasks/package-manager/options.ts
- packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
When the CLI update command's `--force` option is used, the underlying package manager will also be executed with its force option. This behavior is especially important with the advent of npm 7 which will fail installation if any peer dependency version ranges are mismatched.
> fix(@angular/cli): propagate update's force option to package managers

- packages/angular/cli/commands/config-impl.ts
- tests/legacy-cli/e2e/tests/commands/config/config-set.ts
**fix(@angular/cli): allow config object to be of JSON.**
With this change we allow unset a config value to be a JSON.
Example, `ng config -g schematics {}` will remove the entire `schematics` section from the configuration.
**fix(@angular/cli): allow unsetting config when value is `undefined`**
With this change we allow unset a config value when the provided value is `undefined`.
Example, `ng config -g schematics undefined` will remove the entire `schematics` section from the configuration.
Closes #20718
> Unset config

- packages/angular/cli/lib/config/workspace-schema.json
With this change we disallow add additional properties to the `target` object.
> fix(@angular/cli): disallow additional properties in builders sections

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/src/sass/sass-service.ts
- packages/angular_devkit/build_angular/src/sass/worker.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- yarn.lock
The dart-sass Sass implementation will now be executed in a separate worker thread. The wrapper worker implementation provides an interface that can be directly used by Webpack's `sass-loader`.
The worker implementation allows dart-sass to be executed in its synchronous mode which can be up to two times faster than its asynchronous mode. The worker thread also allows Webpack to continue other bundling tasks while the Sass stylesheets are being processed.
Initial testing indicated a ~14% build time improvement for AIO.
> perf(@angular-devkit/build-angular): execute dart-sass in a worker

- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
With this change we reduce the size of the JSON stats object, the main benefit that this change brings is that unspecified stats now default to `false`, due to the `all: false` configuration in https://github.com/angular/angular-cli/blob/e992c9a70b55b6cedbe15e4af7ad9c287a33ee29/packages/angular_devkit/build_angular/src/webpack/configs/stats.ts#L12
> perf(@angular-devkit/build-angular): reduce JSON stats

- packages/schematics/angular/workspace/files/README.md.template
New apps using Angular 12 defaults `ng build` to use `--production configuration` (formerly `--prod`)
> fix(@schematics/angular): remove --prod option from README template

- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
fixes: #20750
When extracting inline styles in Angular 12 there seems to be no CSS loader specified and there will be something like the following message:
```
angular-resource://:2:4 - Error: Module parse failed: Unexpected token (2:4) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
>     :host {
|       display: block;
|       height: 0;
```
This change adds a `webpack.NormalModuleReplacementPlugin` in extract-i18n for `angular-resource://` handling them as the non inline styles are handled.
> fix(@angular-devkit/build-angular): fix error with inline styles when running extract-i18n

- packages/angular/cli/commands/add-impl.ts
- packages/angular/cli/utilities/install-package.ts
This fixes an issue where the installation of the temporary Angular CLI failed with `Cannot locate bin for temporary package: @angular/cli.`
> fix(@angular/cli): cannot locate bin for temporary package

- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/src/commands/update/schematic/index.ts
- packages/angular/cli/utilities/install-package.ts
Prior to performing the initial updated package installation during the `ng update` process, the workspace node modules directory will be removed. This cleaning increases the guarantees that the package manager will hoist packages into the correct locations and avoid peer dependency inconsistencies. This change should also help to ensure a more complete package update.
> fix(@angular/cli): clean node modules directory prior to updating

- packages/angular_devkit/build_angular/src/sass/sass-service.ts
A pool of Workers is now used to process Sass render requests. This change allows multiple synchronous render operations to occur at the same time. Sass synchronous render operations can be up to two times faster than the asynchronous variant. The benefit will be most pronounced in applications with large amounts of Sass stylesheets.
Initial benchmarking with test projects containing large amounts of Sass stylesheets resulted in an additional ~15% total build time improvement over https://github.com/angular/angular-cli/pull/20740
> perf(@angular-devkit/build-angular): render Sass using a pool of workers

- packages/angular/cli/models/architect-command.ts
> fix(@angular/cli): improve `--prod` deprecation warning

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Addresses #20800.
I don't know if this is the best fix for this issue, but seems to be an effective temporary workaround at least. It's possible that a bug may need to be fixed in `babel-loader` or `@babel/runtime`.
> Fix for webpack 5 + babel "failed to resolve" error

- renovate.json
Disable the mentioned package from being managed by Renovate until https://github.com/benmosher/eslint-plugin-import/issues/2065 is fixed.
> ci: disable `eslint-plugin-import` from auto updates

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
This reduce memory consumption during re-builds.
```
runtime.ba93f81591909b93394f.hot-update.js.map will be removed
styles.ba93f81591909b93394f.hot-update.js.map will be removed
runtime.ba93f81591909b93394f.hot-update.json will be removed
runtime.ba93f81591909b93394f.hot-update.js will be removed
styles.ba93f81591909b93394f.hot-update.js will be removed
```
See https://github.com/webpack/webpack/issues/12947#issuecomment-812108140 and https://github.com/webpack/webpack/issues/13127
> perf(@angular-devkit/build-angular): clean no-longer used assets during builds

- packages/schematics/angular/application/index.ts
> Data path  must NOT have additional properties(skipTests)

- packages/angular_devkit/schematics/README.md
In the README for the schematics library, currently the quick reference for Templating is displayed wrong (on GitHub and npm) as the `__` was not escaped and is replaced to `**` due to reformating.
To properly display the templating syntax as its supposed to be used, they are now wrapped in inline code blocks.
> docs(@angular-devkit/schematics): properly escape code in Templating

- packages/angular_devkit/core/src/json/schema/registry.ts
AJV only support a single schema with the same ID, compiling schemas async can cause a race condition were multiple schemas with the same name as compiled at the same time.
Closes #20847
> fix(@angular-devkit/build-angular): compile schema in synchronously

- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-12/schematic-options.ts
- packages/schematics/angular/migrations/update-12/schematic-options_spec.ts
Migration for #20842
Closes #20848
> fix(@schematics/angular): add migration to remove `skipTests` from `@schematics/angular:module`

- .circleci/config.yml
Update the e2e-cli job on CI to use 12.20 rather than 12.18.
> ci: update e2e-cli to use node 12.20

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
This version replaces the `source-map` package with `source-map-js`. This can lead up to 4x performance improvements in parsing map from processing step before PostCSS.
See full changelog: https://github.com/postcss/postcss/releases/tag/8.3.0
> perf(@angular-devkit/build-angular): update PostCSS to 8.3

- packages/angular_devkit/build_angular/src/sass/sass-service.ts
- packages/angular_devkit/build_angular/src/sass/worker.ts
The Worker constructor option for a transfer list is unfortunately not supported until Node.js 12.17. For Node.js versions prior to 12.17, a manual message post is now used to transfer the necessary initialization data to the Sass workers.
Closes #20863
> fix(@angular-devkit/build-angular): ensure Sass worker implementation supports Node.js 12.14

- packages/angular_devkit/build_angular/src/webpack/plugins/index-html-webpack-plugin.ts
> fix(@angular-devkit/build-angular): don't add `.hot-update.js` script tags

- packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
- tests/legacy-cli/e2e/tests/misc/http-headers.ts
- tests/legacy-cli/e2e/tests/misc/trusted-types.ts
As reported in #20113, webpack triggers a Trusted Types violation when lazy-loading is used. To mitigate that, enable webpack's Trusted Types module (introduced in https://github.com/webpack/webpack/pull/9856) using 'angular#bundler' as the policy name.
> fix(@angular-devkit/build-angular): enable webpack Trusted Types support

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Since we rely on child compilations to compile components CSS, using the `parallel` option will cause a significant overhead because each compilation will need to spawn a worker, in this mode the worker limit is not be honored because `css-minimizer-webpack-plugin` spawn and calulators workers during the optimization phase of a compilation and not globally per instance hence causes OOM because a large number of workers to be spawned simultaneously.
Closes #20883
> perf(@angular-devkit/build-angular): disable CSS optimization parallelism for components styles

- packages/angular_devkit/build_angular/src/webpack/plugins/postcss-cli-resources.ts
- packages/ngtools/webpack/src/resource_loader.ts
With this change we re-emit assets referenced in component stylesheets which where uneffected by the change that re-triggered a re-compilation.
Since we cache the the result of processed component CSS, during a re-compilation `postcss-cli-resources` plugin will not run which causes assets to be to emit. With this change we now cache the asset and re-emit them on every change.
Closes #20882
> fix(@ngtools/webpack): re-emit component stylesheet assets

- packages/angular/cli/commands/version-impl.ts
- tests/legacy-cli/e2e/tests/misc/version.ts
Unsupported versions of Node.js will now show an unsupported warning when the `ng version` command is executed.
Currently Node.js major versions 12 and 14 are considered supported and tested.
Closes #20879
> feat(@angular/cli): show Node.js version support status in version command

- packages/angular_devkit/build_angular/src/utils/service-worker.ts
- tests/legacy-cli/e2e/tests/commands/add/add-pwa.ts
Since #20518, the generation of the ServiceWorker configuration has been broken on Windows. The reason is the use of `path.posix.*` methods on non-POSIX paths, resulting in broken paths. I.e. we ended up with something like the following:
```js
path.posix.relative('C:\\foo', 'C:\\foo\\bar/baz');
// Expected result: `bar/baz`
// Actual result:   `../C:\\foo\\bar/baz`
```
This caused the config generator to fail to find any files and thus fail to populate the config with cacheable assets.
This commit fixes this by using platform-specific `path.*` methods for path manipulation and manually normalizing the path separators before returning the results.
Fixes #20894.
> fix(@angular-devkit/build-angular): correctly generate ServiceWorker config on Windows

- packages/circular-deps-test.conf.js
Fix an incorrect mapping path in the circular dependency checker configuration.
> test: fix local mapping path of @ angular-devkit/schematics-cli

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Loading the postcss-preset-env plugin includes building a mapping of unsupported
browsers by feature, which is somewhat expensive. In large compilations, this mapping
would be recomputed for each postcss-loader instance, as the plugin was recreated
for each loader invocation. By extracting the plugin instance outside of the dynamic
plugin computation, this overhead is avoided.
> perf(@angular-devkit/build-angular): load postcss-preset-env configuration once

- tests/legacy-cli/e2e/ng-snapshot/package.json
- tests/legacy-cli/e2e/tests/commands/add/add-pwa.ts
When executing the add-pwa E2E test with Angular snapshots, the package versions need to be updated after the `ng add @angular/pwa` call to ensure that the correct version of `@angular/service-worker` is used.
> test: use correct snapshot versions in add-pwa E2E test

- package.json
- packages/angular_devkit/build_angular/package.json
- tests/legacy-cli/e2e/setup/010-local-publish.ts
- tests/legacy-cli/e2e/tests/update/update-8.ts
- tests/legacy-cli/e2e/utils/packages.ts
- tests/legacy-cli/e2e/utils/project.ts
- yarn.lock
> fix(@angular-devkit/build-angular): update to postcss 8.2.15

- packages/angular_devkit/build_angular/src/browser/tests/options/inline-style-language_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
- packages/ngtools/webpack/src/inline-data-loader.ts
- packages/ngtools/webpack/src/ivy/host.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
- packages/ngtools/webpack/src/ivy/transformation.ts
- packages/ngtools/webpack/src/resource_loader.ts
- packages/ngtools/webpack/src/transformers/replace_resources.ts
Webpack provides a method to construct a special request string that will remap a loader chain to appear to be from a specific resource path. This requires a custom loader, however, it allows rule matching to leverage the existing file extension based approach and allows providing a path to other loaders which simplifies relative request handling.
> refactor(@ngtools/webpack): use Webpack inline resource matching for inline resources

- tests/legacy-cli/e2e/tests/commands/add/add-pwa.ts
When executing the add-pwa E2E test with Angular snapshots, the package versions need to be updated after the `ng add @angular/pwa` call to ensure that the correct version of `@angular/service-worker` is used.
Yarn requires a different package installation strategy due to Yarn not always installing a new version of a github sha when directly adding an individual package.
> test: use correct snapshot versions in add-pwa E2E test with yarn

- packages/angular_devkit/build_angular/src/dev-server/index.ts
> fix(@angular-devkit/build-angular): show `--disable-host-check` warning only when not using `disableHostCheck`

- packages/angular_devkit/build_angular/src/server/base_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/server.ts
Web-workers are not supported on the server and therefore we should not try to request these files from the Angular plugin.
Closes #20877
> fix(@angular-devkit/build-angular): do not resolve web-workers in server builds

- docs/process/release.md
The process has changed and post-release bumps are no longer necessary.
Also updated the doc to include a section on changing shifts with the caveat that you must be logged in to the `@angular.io` account to have edit access to the calendar.
/cc release caretakers @josephperrott @kyliau
> docs: fold post-release version bump with the release commit

- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
With this change we provide earlier feedback in the console during a build. The setup phase can take some times if the project has a large set of dependencies.
We also move several warnings in the dev-server to an earlier phase so that we don't clutter the progress indicator.
Closes #20957
> fix(@angular-devkit/build-angular): provided earlier build feedback in console

- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/extract-i18n/works_spec.ts
> fix(@angular-devkit/build-angular): correctly ignore inline styles during i18n extraction

- packages/angular_devkit/build_angular/src/extract-i18n/empty-export-default.js
- packages/angular_devkit/build_angular/src/extract-i18n/empty-loader.ts
- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/extract-i18n/works_spec.ts
Stylesheets are not processed during i18n extraction to improve performance  and the rules to support them are intentionally not present.
> [12.1.x]fix(@angular-devkit/build-angular): correctly ignore inline styles during i18n extraction

- packages/schematics/angular/migrations/update-12/update-angular-config.ts
- packages/schematics/angular/migrations/update-12/update-angular-config_spec.ts
With this change we ensure that `update-angular-config-v12` migration is idempotent
Closes #20979
> fix(@schematics/angular): make version 12 workspace config migration idempotent

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/browser/specs/differential_loading_spec.ts
- packages/angular_devkit/build_angular/src/browser/specs/scripts-array_spec.ts
- packages/angular_devkit/build_angular/test/hello-world-app/angular.json
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/build_webpack/package.json
- packages/ngtools/webpack/package.json
- yarn.lock
With this change we update to `webpack` to `5.38.1`, this also updates `webpack-sources` to `2.3.0`, The latter is causing OOM errors on our CI, but it in real projects the memory usage only increased by a small fraction. Also, the OOM errors don't manifest themselves when the entire test suit is run locally.
Therefore with this change we also disable sourcemap genertation for most of the browser builds to speed up the tests and reduce memery usage.
> build: update Webpack to version 5.38.1

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/browser/specs/differential_loading_spec.ts
- packages/angular_devkit/build_angular/src/browser/specs/scripts-array_spec.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/index-html-webpack-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts
- packages/angular_devkit/build_angular/test/hello-world-app/angular.json
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/build_webpack/package.json
- packages/ngtools/webpack/package.json
- yarn.lock
With this change we update to `webpack` to `5.38.1`, this also updates `webpack-sources` to `2.3.0`, The latter is causing OOM errors on our CI, but it in real projects the memory usage only increased by a small fraction. Also, the OOM errors don't manifest themselves when the entire test suit is run locally.
Therefore with this change we also disable sourcemap genertation for most of the browser builds to speed up the tests and reduce memery usage.
> [12.0.x] build: update Webpack to version 5.38.1 

- packages/ngtools/webpack/src/ivy/plugin.ts
This caused Webpack to mark all TypeScript files as removed after the first compilation on Windows because the file separators didn't match
Closes #20891
A big thanks goes to @elvisbegovic, who provided multiple teamviewer sessions to track down this issue.
> fix(@ngtools/webpack): normalize paths when adding file dependencies

- packages/ngtools/webpack/src/resource_loader.ts
The size of the cache could grow quite large over long active development periods. Webpack 5 memory caching will also allow for caching of the data.
> fix(@ngtools/webpack): remove redundant inline style cache

- packages/schematics/angular/component/index.ts
- packages/schematics/angular/directive/index.ts
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/utility/workspace.ts
> fix(@schematics/angular): show better error when non existing project  is passed to the component schematic

- packages/angular_devkit/build_angular/src/webpack/configs/stats.ts
- packages/angular_devkit/build_webpack/src/webpack/index.ts
Until we depend on `webpackStats` in the browser builder we should only included the required stats.
The below are the needed stats;
```
all: false,
colors: true,
hash: true,
timings: true,
chunks: true,
builtAt: true,
warnings: true,
errors: true,
assets: true,
ids: true,
entrypoints: true,
```
> perf(@angular-devkit/build-webpack): include only required stats in webpackStats

- tests/legacy-cli/e2e/setup/010-local-publish.ts
- tests/legacy-cli/e2e/tests/update/update-8.ts
The tooling packages needed to perform a canonical update process are now published to the local test package registry. This removes the need to switch back and forth between the npm registry and the test registry during E2E tests. It also ensures that CLI versions are used that are compatible with the Node.js version used for the tests.
> test(@angular/cli): locally publish LTS tooling packages for E2E update tests

- packages/angular/cli/utilities/install-package.ts
This change removes the usage of the shell execution when spawning the latest CLI version when bootstrapping the update command. The absolute path of the node process is now spawned which removes the need for any shell path resolution. This also removes the need to quote and/or escape command arguments which can be error-prone. Node.js and the OS will now handle any quoting and escaping automatically and without any custom logic.
> fix(@angular/cli): avoid shell exec when bootstrapping update command

- docs/process/release.md
This will hopefully make things a little more clear and reduce the possibility that devs put the same number in both places when they actually reflect completely different values.
> docs: update release documentation to be more clear about the differences between the two version numbers

- packages/angular/cli/BUILD.bazel
- packages/angular/cli/package.json
- packages/angular/cli/utilities/install-package.ts
- scripts/build-schema.ts
- scripts/build.ts
With the removal of support for Node.js v10, the Node.js native support for recursively removing a directory can now be used.
Also updates several of the dev scripts as well.
> refactor(@angular/cli): remove usage of rimraf dependency

- packages/angular_devkit/build_angular/src/webpack/configs/stats.ts
Webpack will only provide emitted assets in the returned Stats each rebuild unless the `cachedAssets` option is enabled. This is currently needed for the bundle budget calculations.
Fixes #21038
> fix(@angular-devkit/build-angular): ensure all Webpack Stats assets are present on rebuilds

- packages/angular_devkit/build_angular/src/sass/sass-service.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Sass Worker instances and resource requests are now cleaned up when the Webpack compiler is shutdown. This removes the need to unreference the workers upon creation.
Fixes #20985
> fix(@angular-devkit/build-angular): dispose Sass worker resources on Webpack shutdown

- packages/angular_devkit/build_angular/src/utils/spinner.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
With the recent changes in https://github.com/angular/angular-cli/pull/20960 we moved the spinner to be started outside of the progress callback, this causes a side-effect that after `succeed` is called the spinner will stop reporting progress unless it is started again.
> fix(@angular-devkit/build-angular): show progress during re-builds

- packages/schematics/angular/web-worker/index.ts
I have found one issue while working with a web worker.
I have a simple web-worker and working perfectly with `ng build ` but in the case of the `ng test` will fail.
after some time I found that  `"webWorkerTsConfig": "tsconfig.worker.json"` missing in test options.
and also check --target with ng g web-worker CLI reference.
Today I have made a simple change in angular-cli so that it will also added same config into test if it available it will change.
> fix(@schematics/angular): added webWorkerTsConfig into test options

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Unless `deleteOutputPath` is false, we should clean, this helps reduce assets in tests.
> perf(@angular-devkit/build-angular): reduce memory usage by cleaning output directory before emitting

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/webpack/utils/async-chunks.ts
- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Web-workers are not marked as `initial` since their initialization can be guarded.
Closes #21059
> fix(@angular-devkit/build-angular): add web-workers in lazy chunks in stats output

- packages/schematics/angular/web-worker/index.ts
- packages/schematics/angular/web-worker/index_spec.ts
- packages/schematics/angular/web-worker/schema.json
Remove code that used to handle version 8 applications. These should have migrated to the new structure when using ng-update.
> refactor(@schematics/angular): clean up web-worker schematic

- packages/angular/cli/models/schematic-engine-host.ts
> fix(@angular/cli): correctly redirect nested Angular schematic dependency requests

- packages/ngtools/webpack/src/ivy/plugin.ts
- packages/ngtools/webpack/src/ngcc_processor.ts
By using the Webpack compiler to request a resolver, configuration supplied options will automatically be used (such as symlinks) and also ensures that the same version of the resolver code will be used. Additionally, this removes one of the reasons to directly depend on the `enhanced-resolve` package.
> refactor(@ngtools/webpack): create ngcc resolver from Webpack Compiler

- packages/ngtools/webpack/src/inline-data-loader.ts
- packages/ngtools/webpack/src/ivy/cache.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
- packages/ngtools/webpack/src/resource_loader.ts
- packages/ngtools/webpack/src/webpack-diagnostics.ts
Webpack 5 provides the Webpack instance as a property on the Webpack compiler which allows Webpack plugins to leverage the same Webpack instance that was used to initiate the build. The `AngularWebpackPlugin` now will only use the provided instance to ensure that differing Webpack instances and/or versions are not used.
> fix(@ngtools/webpack): ensure plugin provided Webpack instance is used

- packages/ngtools/webpack/src/ivy/cache.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
- packages/ngtools/webpack/src/resource_loader.ts
- packages/ngtools/webpack/src/webpack-diagnostics.ts
Webpack 5 provides the Webpack instance as a property on the Webpack compiler which allows Webpack plugins to leverage the same Webpack instance that was used to initiate the build. The `AngularWebpackPlugin` now will only use the provided instance to ensure that differing Webpack instances and/or versions are not used.
> [12.0.x]fix(@ngtools/webpack): ensure plugin provided Webpack instance is used

- packages/angular_devkit/schematics/src/sink/host.ts
- packages/angular_devkit/schematics/src/sink/host_spec.ts
With this change we fix an issue which caused a file not found error when trying to modify the file after it was renamed.
Closes #14255 and closes #21083
> fix(@angular-devkit/schematics): handle updating renamed files

- packages/ngtools/webpack/src/ivy/plugin.ts
- packages/ngtools/webpack/src/paths-plugin.ts
Usage of async functions and promises were removed from the TypeScript paths resolver plugin to allow it to be used with both a synchronous and asychronous Webpack resolver.
> refactor(@ngtools/webpack): support both sync and async resolvers with TypeScript paths plugin

- packages/ngtools/webpack/src/ivy/loader.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
The Angular Webpack loader will now access the Angular Webpack Plugin's file emitters via the loader context directly. This is instead of using the not fully public Webpack compilation property on the loader context. This change also removes the need to directly alter the Webpack compilation object which previously added an additional property.
> refactor(@ngtools/webpack): use Webpack loader context hook to access file emitters

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Users should not install `postcss` in their workspace as this is a dependency of `@angular-devkit/build-angular`.
> refactor(@angular-devkit/build-angular): ignore postcss-loader warning

- packages/angular_devkit/build_angular/src/webpack/configs/test.ts
This is to retain version 11 behaviour.
Closes #21108
> fix(@angular-devkit/build-angular): don't parse `new Worker` syntax when `webWorkerTsConfig` is not defined in karma builder

- packages/angular_devkit/build_angular/src/webpack/configs/test.ts
When not set, and browserslist returns no supported result due to the file being empty or commented. Webpack will generate invalid code because it doesn't know which enviorment we want to target.
```diff
- (self["webpackChunktest_app"] = self["webpackChunktest_app"] || []).push([["vendor"],{
/***/ 8583:
```
Closes #21111
> fix(@angular-devkit/build-angular): explicitly set compilation target  in test configuration

- packages/angular_devkit/build_angular/src/app-shell/index.ts
- packages/angular_devkit/build_angular/src/utils/environment-options.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
With this change we enable Webpack's filesystem cache, this important because `terser-webpack-plugin`, `css-minimizer-webpack-plugin` and `copy-webpack-plugin` all use Webpacks' caching API to avoid additional processing during the 2nd cold build.
This changes causes `node_modules` to be treated as immutable. Webpack will avoid hashing and timestamping them, assume the version is unique and will use it as a snapshot.
To opt-in using the experimental persistent build cache use the`NG_PERSISTENT_BUILD_CACHE` environment variable. 
```
NG_PERSISTENT_BUILD_CACHE=1 ng serve
```
> perf(@angular-devkit/build-angular): enable opt-in usage of file system cache 

- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-12/replace-prod-flag.ts
- packages/schematics/angular/migrations/update-12/replace-prod-flag_spec.ts
With this change we add migration to replace the deprecated `--prod` with `--configuration production` in the scripts section of the package.json.
Closes #21036
> feat(@schematics/angular): add migration to replace deprecated `--prod`

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Solves the following regression in Angular 12: https://github.com/angular/angular-cli/issues/21129
> fix(@angular-devkit/build-angular): use the name as chunk filename instead of id

- tsconfig.json
With the removal of support for Node.js v10, the TypeScript library version can be updated to ES2020. Node.js v12.11+ supports the API elements of ES2020.
The compilation target must still be set to ES2019 as the language syntax elements are not fully supported until Node.js v14+.
> build: support ES2020 API usage

- tests/legacy-cli/e2e/tests/commands/add/registry-option.ts
- tests/legacy-cli/e2e/tests/commands/add/secure-registry.ts
- tests/legacy-cli/e2e/tests/update/update-secure-registry.ts
- tests/legacy-cli/e2e/utils/registry.ts
- tests/legacy-cli/e2e_runner.ts
- tests/legacy-cli/verdaccio.yaml
- tests/legacy-cli/verdaccio_auth.yaml
With this change we add E2E tests to validate that `ng add` and `ng update` work with secure NPM registries.
This is a follow up of #21140 which addressed several issues with secure registries.
> tests(@angular/cli): add `ng add` and `ng update` E2E tests for secure repositories

- packages/schematics/angular/class/index_spec.ts
- packages/schematics/angular/component/index_spec.ts
- packages/schematics/angular/directive/index_spec.ts
- packages/schematics/angular/pipe/index_spec.ts
add missing unit test of skipTests flag for component, class, directive, and pipe
> test(@schematics/angular): add missing unit test for skipTests flag

- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
- packages/schematics/angular/component/index.ts
- packages/schematics/angular/component/index_spec.ts
- packages/schematics/angular/component/schema.json
Allow setting `--style=none` for the component schematic to prevent generation of any style file.  Previously this was possible only with `--inlineStyle=true`, which had the side-effect of adding an inline style block to the component decorator.  Useful for components or projects which have entirely externalised stylesheets and never want to use component-specific styles.
**Motivation**
In our project we have an externally-managed SCSS project to allow our customers theming flexibility.  As such our components only use the BEM classes from this project.  Almost none of our components contain any actual CSS. 
Every time we run `ng g c ...` we have to then manually delete the style file or style block from the component decorator in the generated .component.ts file, which is a little …
> feat(@schematics/angular): add 'none' value for the 'style' option of the component schematic

- packages/angular_devkit/build_angular/src/ng-packagr/index.ts
Ng-packagr will throw an error when a compilation fails.
> fix(@angular-devkit/build-angular): handle ng-packagr errors more gracefully

- packages/angular_devkit/build_angular/src/webpack/configs/test.ts
The logic was inverted which caused workers not to be parsed when webWorkerTsConfig is defined.
Patch version of https://github.com/angular/angular-cli/pull/21160
> [patch] fix(@angular-devkit/build-angular): parse web-workers in tests when webWorkerTsConfig is defined

- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
This change allows the linker sourcemap behavior to be controlled by the Webpack sourcemap configuration. For example, if a vendor file is being processed and vendor sourcemaps are disabled, the linker will now skip its internal sourcemap loading and processing steps.
> fix(@angular-devkit/build-angular): control linker template sourcemapping via builder sourcemap options

- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/src/karma/tests/options/web-worker-tsconfig_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/test.ts
The logic was inverted which caused workers not to be parsed when `webWorkerTsConfig` is defined.
> fix(@angular-devkit/build-angular): parse web-workers in tests when webWorkerTsConfig is defined

- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
This change allows the linker sourcemap behavior to be controlled by the Webpack sourcemap configuration. For example, if a vendor file is being processed and vendor sourcemaps are disabled, the linker will now skip its internal sourcemap loading and processing steps.
12.0.x variant of #21155
> [12.0.x] fix(@angular-devkit/build-angular): control linker template sourcemapping via builder sourcemap options

- packages/angular/cli/commands/new-impl.ts
- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/lib/init.ts
- packages/angular/cli/models/analytics.ts
- packages/angular/cli/models/schematic-engine-host.ts
These set of changes reduce the number of `require` calls through the `@angular/cli` package and will aid in the transition to ESM.  This also helps remove duplicate code as well as some now unused code.
> Reduce usage of `require` calls in `@angular/cli` package

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/build_webpack/package.json
- packages/ngtools/webpack/package.json
- yarn.lock
This includes several performance improvements
- improve LazySet memory usage by shortcircuiting empty sets
- reduce algorithmic complexity of the structure analysis for plain objects serialization
> build: update `webpack` to `5.40.0`

- .bazelrc
Update to use remote instance name, primary_instance, for RBE
> build: update to new remote instance name for RBE

- packages/angular/cli/commands/e2e-impl.ts
**Overview**
Added Nightwatch Schematic to e2e command. Nightwatch schematics would add both schematics and custom builder to Angular Project.
Ref:
https://github.com/nightwatchjs/nightwatch-schematics
https://www.npmjs.com/package/@nightwatch/schematics
> docs(@angular/cli): Add Nightwatch schematics to e2e command

- packages/angular/cli/commands/version-impl.ts
NPM updater notifier will prevents the child process from closing until it timeout after 3 minutes.
Closes #21172
> fix(@angular/cli): disable update notifier when retrieving package manager version during `ng version`

- .bazelrc
Update to use remote instance name, primary_instance, for RBE
(cherry picked from commit 4d31fc6a74b68968707ff8aa12b0842e0ea5dd10)
> [11.2.x] build: update to new remote instance name for RBE

- packages/angular_devkit/build_angular/BUILD.bazel
This should help to reduce heap out of memory errors during Karma tests.
> ci: increase shards for karma tests

- .bazelrc
- .circleci/config.yml
- tests/legacy-cli/e2e/tests/misc/update-git-clean-subdirectory.ts
Update to use remote instance name, primary_instance, for RBE
(cherry picked from commit 4d31fc6a74b68968707ff8aa12b0842e0ea5dd10)
> [9.1.x] build: update to new remote instance name for RBE

- .bazelrc
- .ng-dev.log
- tests/legacy-cli/e2e/tests/misc/update-git-clean-subdirectory.ts
Update to use remote instance name, primary_instance, for RBE
(cherry picked from commit 4d31fc6a74b68968707ff8aa12b0842e0ea5dd10)
> [10.2.x] build: update to new remote instance name for RBE

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/utils/action-executor.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- yarn.lock
> Cleanup and remove unneeded dependencies for differential loading processing

- packages/angular_devkit/build_angular/src/utils/delete-output-dir.ts
> fix(@angular-devkit/build-angular): handle `ENOENT` and `ENOTDIR` errors when deleting outputs

- packages/angular_devkit/build_angular/src/browser/schema.json
- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts_spec.ts
With this change we add support to inline external Adobe fonts into the index html, we also add a `preconnect` hint which helps improve page load speed.
Closes #21186
> feat(@angular-devkit/build-angular): add support to inline Adobe Fonts

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
This addresses a number of memory leaks and slow re-compilations.
> perf(@angular-devkit/build-angular): update `mini-css-extract-plugin` to `1.6.2`

- packages/ngtools/webpack/src/transformers/replace_resources.ts
We now encode the data using `encodeURIComponent` which safely encodes `+` signs. Without this a portion of the buffer was lost and caused `Unrecognised input` errors.
Closes #21236
> fix(@ngtools/webpack): encode component style data

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/browser/tests/behavior/typescript-target_spec.ts
- yarn.lock
…
Closes #21196
(cherry picked from commit 367de35623af90b3764f4e55b83cbf4803d72be1)
> [patch] fix(@angular-devkit/build-angular): downlevel `for await...of` when targetting ES2018+

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/browser/tests/behavior/typescript-target_spec.ts
- yarn.lock
> fix(@angular-devkit/build-angular): downlevel `for await...of` when targetting ES2018+

- packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/configs/server.ts
Previously, `target` was unset for `test` which caused the target to be set incorrectly.
Closes #21239
> fix(@angular-devkit/build-angular): configure webpack target in common configuration

- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
The `@ampproject/remapping` package is now used for sourcemap processing instead of Webpack for differential loading and i18n processing. This dependency is already used within the recently added JavaScript optimizer refactoring and reduces the amount of code that needs to be loaded into each worker to support differential loading source maps. Testing with large output bundles (~12MB vendor bundles) resulted in an ~8% total build time improvement when using differential loading and source maps.
> refactor(@angular-devkit/build-angular): avoid loading Webpack for differential loading sourcemaps

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
With this change we enable `quietDeps`, which causes the Sass compiler not to emit warnings from a stylesheet that is loaded through load-path.
The `--verbose` option can be used to opt-out from this behaviour and display all warnings.
Closes #21235
> fix(@angular-devkit/build-angular): silence Sass compiler warnings from 3rd party stylesheets

- packages/ngtools/webpack/src/resource_loader.ts
`fileDependencies` can contain directories and not just files which can cause incorrect cache invalidation on rebuilds.
Example
```
'/Users/***/tailwindcss-angular12-replica/src/app/component19/component19.component.scss',
'/Users/***/tailwindcss-angular12-replica/tailwind.config.js',
'/var/folders/mp/zsgl3srd389_js72bk4_bkgh0000gn/T/tmp-19814-FDsnpPo5zlQK',
'/Users/***/tailwindcss-angular12-replica/package.json',
'/Users/***/tailwindcss-angular12-replica/src/app/component19',
'/Users/***/tailwindcss-angular12-replica/src/app',
'/Users/***/tailwindcss-angular12-replica/src',
'/Users/***/tailwindcss-angular12-replica',
'/Users/***',
'/Users/****',
'/Users',
'/'
```
Closes #21228
> fix(@ngtools/webpack): only track file dependencies

- packages/angular_devkit/build_angular/src/extract-i18n/ivy-extract-loader.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/postcss-cli-resources.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/single-test-transform.ts
Webpack now provides loader function type definitions. These type definitions are now used in custom loaders within the package.
This improves type safety and behavior correctness of the loaders when used with Webpack.
The direct usage of the `loader-utils` package is also reduced as the Webpack 5 loader context now provides the `getOptions` function.
> refactor(@angular-devkit/build-angular): use Webpack provided loader types

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
This change fixes `NG_PERSISTENT_BUILD_CACHE` sometimes creating cache entries that live outside of the cache directory by using a hex encoding rather than a base64 encoding. This error is caused because the base64 alphabet includes `/`. According to the webpack documentation [1] the default `cacheLocation` is: `path.resolve(cache.cacheDirectory, cache.name)` which means cache names with a leading `/` would remove the `cacheDirectory` altogether.
[1]: https://webpack.js.org/configuration/other-options/#cachecachelocation
> fix(@angular-devkit/build-angular): ensure `NG_PERSISTENT_BUILD_CACHE` always creates a cache in the specified cache directory

- package.json
- scripts/changelog.ts
Node.js now provides simplified stream construction capabilities which removes the need for the `through2` dependency.
This change allows for the removal of the `through2` development dependency which was otherwise unused.
Probably easier to review with "Hide whitespace changes" enabled.
> build: use simplified stream construction in changelog script

- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- tests/legacy-cli/e2e/tests/generate/library/library-consumption-ivy-full.ts
- tests/legacy-cli/e2e/tests/generate/library/library-consumption-ivy-partial.ts
- tests/legacy-cli/e2e/tests/generate/library/library-consumption-ve.ts
Reverts angular/angular-cli#21155
Following a debugging and investigation with @petebacondarwin it appears that when the external template handling in the linker generates Babel AST nodes that reference the external template files which breaks Babel when it tried to flatten final source-map, which ends up no emitting any source-maps.
As an interim solution we should revert this. 
Closes #21271
> Revert "fix(@angular-devkit/build-angular): control linker template sourcemapping via builder sourcemap options"

- packages/angular_devkit/build_angular/src/webpack/plugins/builder-watch-plugin.ts
Webpack 5 now provides type definitions for the majority of the watch subsystem. These type definitions allow the removal of the custom types that were previously used.
> refactor(@angular-devkit/build-angular): use Webpack provided watcher typings instead of custom

- packages/ngtools/webpack/src/loaders/direct-resource.ts
- packages/ngtools/webpack/src/loaders/inline-resource.ts
- packages/ngtools/webpack/src/resource_loader.ts
- packages/ngtools/webpack/src/transformers/replace_resources.ts
- packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
The source file for the internal inline resource loader is moved into a `loaders` subdirectory for better code organization. The need to call `require.resolve` is also removed from the consumers of this loader.
When JIT mode and `directTemplateLoading` were enabled, the plugin would reference the `raw-loader` dependency. This dependency was not mentioned in the `package.json` and is also now deprecated. An internal direct resource loader is now used instead which removes the usage of the implicit dependency.
> Cleanup `ngtools/webpack` internal loaders

- packages/angular_devkit/build_angular/test/hello-world-app/src/test.ts
- packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/src/test.ts
- packages/schematics/angular/application/files/src/test.ts.template
- packages/schematics/angular/library/files/src/test.ts.template
In version 12.1, the framework added the `destroyAfterEach` an opt-in feature that improves tests performance and also addresses two long-standing issues.
The idea, is to have this enabled by default in the future.  Related PR: https://github.com/angular/angular/pull/42566
Closes #21280
> feat(@schematics/angular): destroy test module after every test

- packages/schematics/angular/application/other-files/app.component.spec.ts.template
The `nativeElement` property on a `TestBed` fixture is of type `any`. In one of the tests within a new application's spec file, the `nativeElement` is accessed but not cast to an appropriate type which results in potentially unsafe member access. The `nativeElement` is now cast as an `HTMLElement` and allows additional usage to be type checked.
> fix(@schematics/angular): remove unsafe `any` usage in application spec file

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- packages/angular_devkit/build_webpack/BUILD.bazel
- packages/angular_devkit/build_webpack/test/angular-app/webpack.config.js
- tests/legacy-cli/e2e/assets/webpack/test-app/package.json
- tests/legacy-cli/e2e/assets/webpack/test-app/webpack.config.js
- yarn.lock
With Webpack 5, the `raw-loader` is no longer needed and its functionality is provided via configuration options within the Webpack configuration via asset modules.  Asset modules (https://webpack.js.org/guides/asset-modules/) provide a built-in way to provide `raw-loader`, `url-loader`, and `file-loader` functionality without additional dependencies.
> refactor(@angular-devkit/build-angular): replace `raw-loader` with Webpack 5 asset modules

- packages/schematics/angular/application/other-files/app.component.html.template
A keyboard user who has a problem in using a mouse, will not be able to select the `div`, because he cannot initiate the click event, which is specific to the mouse. Interactive elements like button can initiate the click event on keyboard events.
Instead of adding additional events, such as `keyup`, `keydown` or `keypress`, we replace these with a `button`.
> fix(@schematics/angular): replace interactive `div` with `button` in application component template

- packages/ngtools/webpack/src/resource_loader.ts
The asset caching for Angular component resources previously required that all assets had an originating file. However, some Webpack plugins may generate assets that do not originate from on-disk files and are instead synthetic. These type of assets are now supported by generating a cache key based on the output name of the asset. These assets will persist within the cache due to the lack of knowledge on the dependencies of these assets which results in the inability to invalidate the assets. Updated assets of the same output name will, however, replace older versions of the asset on rebuilds.
Fixes: #21290
> fix(@ngtools/webpack): allow generated assets of Angular component resources

- packages/ngtools/webpack/src/ivy/plugin.ts
The AOT compiler's internal template type-checking files are not intended to be directly analyzed for diagnostics by the emitting program and are instead analyzed during the template type-checking phase. Previously, only semantic diagnostics were ignored. Now both syntactic and semantic diagnostics are ignored. This change prevents non-actionable diagnostics from being shown during a build.
Addresses: https://github.com/angular/angular/issues/42667
> fix(@ngtools/webpack): avoid non-actionable template type-checker syntax diagnostics

- packages/angular_devkit/build_angular/src/browser/index.ts
Currently, when there is an error during index generation this is just been logged in the console.
> fix(@angular-devkit/build-angular): fail browser build when index generation fails

- package.json
- packages/schematics/angular/workspace/files/package.json.template
- yarn.lock
This is not the first time, that this package caused a breaking change in a minor version, were it drops support for older `jasmine-core` versions.
Related to #21326
> fix(@schematics/angular): use stricter semver for `karma-jasmine-html-reporter`

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/karma/index.ts
- packages/angular_devkit/build_angular/src/server/index.ts
- packages/angular_devkit/build_angular/src/utils/version.ts
The logger API writes logs in an async fasion which previously caused messages not to be printed in the terminal when `process.exit` was invoked.
Closes #21322
> fix(@angular-devkit/build-angular): display incompatibility errors

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
The stylesheet optimization pipeline now uses `esbuild` for component stylesheets. The usage of `esbuild` provides noticeable build time improvements as well as, on average, smaller output sizes.
`esbuild` currently does not support stylesheet sourcemaps. However, since the Angular CLI does not support component stylesheet sourcemaps when optimizing, this lack of support is not problematic.
Global stylesheets will continue to use `cssnano` as an optimizer due to sourcemaps being required for global stylesheets even when optimizing. When `esbuild` adds stylesheet sourcemap support, global stylesheets may be transitioned to `esbuild` as well.
> perf(@angular-devkit/build-angular): use `esbuild` as a CSS optimizer for component styles

- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
Limiting the terser passes to two helps to workaround an issue with terser wherein terser will errantly inline a function argument containing a `yield` expression inside an inner arrow function.  This results in a syntax error since the yield expression is no longer within the scope of a generator.
Reducing the number of terser passes to two does cause a minor increase in size as shown below.  However, the change is far less than 1% in both cases.
| File      | 2 passes (this PR) | 3 passes (master) | Change       |
| --------- | ----------------- | ----------------- | ------------ |
| main      | 3755283           | 3754440 (broken)  | 843 (~0.02%) |
| polyfills | 37207             | 37207             | 0            |
| runtime   | 1545              | 1545              | 0            |
| …
> fix(@angular-devkit/build-angular): limit advanced terser passes to two

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
With this change we exclude `outputPath` from cache key due to i18n extraction which causes it to change on every build https://github.com/angular/angular-cli/blob/736a5f89deaca85f487b78aec9ff66d4118ceb6a/packages/angular_devkit/build_angular/src/utils/i18n-options.ts#L264-L265
Closes #21275
> fix(@angular-devkit/build-angular): exclude `outputPath` from persistent build cache key

- .circleci/config.yml
When failures occur on CI, we should not continue to run the CI checks as a failing case has already
been discovered.  Instead we now cancel the workflow stopping the other jobs to prevent unnecessary
resource usage.
> ci: introduce configuration to fail fast for CI failures

- packages/schematics/angular/class/index.ts
- packages/schematics/angular/enum/index.ts
- packages/schematics/angular/guard/index.ts
- packages/schematics/angular/interceptor/index.ts
- packages/schematics/angular/interface/index.ts
- packages/schematics/angular/resolver/index.ts
- packages/schematics/angular/service/index.ts
- packages/schematics/angular/utility/generate-from-files.ts
An internal schematics helper rule has been introduced for Angular schematics that only generate a set of project files from a set of templated files. Multiple current generation schematics contained essentially the same code which increased the sustainment burden and made refactoring and improvements more complicated.
> refactor(@schematics/angular): use a helper function for basic generation schematics

- scripts/build.ts
Provide the location of the directories rather than the tar files as the
release tooling inspects the package.json fiels to confirm the correct
version being published.
> build: provide build artifact location directories instead of tar files

- packages/ngtools/webpack/src/ivy/loader.ts
The `AngularPluginSymbol` and `FileEmitterCollection` types are not intended to be exported for use within the public API of the package.
> refactor(@ngtools/webpack): avoid exposing internal types in public API

- packages/angular_devkit/build_angular/src/dev-server/index.ts
Camel case arguments have been deprecated and therefore shouldn't be suggested.
> fix(@angular-devkit/build-angular): dasherize disable-host-check suggestion

- CHANGELOG.md
Establish a CHANGELOG file to be updated on each release.  This changelog only contains
changes being with `12.0.0-next.0`, prior release notes will continue to be available
in the Github Releases UI.  To generate this changelog, the body contents of each release
published to the Github Releases was extracted.
> ci: establish a CHANGELOG file

- packages/angular/cli/utilities/package-metadata.ts
- tests/legacy-cli/e2e/tests/commands/add/npm-env-vars.ts
- tests/legacy-cli/e2e/tests/commands/add/registry-option.ts
- tests/legacy-cli/e2e/tests/commands/add/secure-registry.ts
- tests/legacy-cli/e2e/tests/update/update-secure-registry.ts
- tests/legacy-cli/e2e/utils/registry.ts
Some organizations are moving away from storing tokens/secrets in an npm config file in favor of environment variables that only exist for the span of a terminal session.  This commit will read those variables in when no options have been configured via a file.
From a testing perspective, I was not able to get the full unit test/e2e suites to run successfully.  The unit test suite fails immediately with a Bazel build failure. If you have any insight into what might be causing this, I'm more than happy to keep trying things.  I wasn't very successful at finding similar issues in the normal places (i.e. Stack Overflow).  
The full e2e suite failed at different steps in each of my attempts.  The latest one is below as an example.  If there's some common gotchas with the e2e tests, I'm …
> fix(@angular/cli): handle NPM_CONFIG environment variables during ng update and ng add

- tests/legacy-cli/verdaccio.yaml
- tests/legacy-cli/verdaccio_auth.yaml
See: https://verdaccio.org/blog/
> build: migrate from deprecated `logs` verdaccio option

- packages/angular/cli/utilities/package-metadata.ts
- tests/legacy-cli/e2e/tests/commands/add/npm-env-vars.ts
- tests/legacy-cli/e2e/tests/commands/add/registry-option.ts
- tests/legacy-cli/e2e/tests/commands/add/secure-registry.ts
- tests/legacy-cli/e2e/tests/commands/add/yarn-env-vars.ts
- tests/legacy-cli/e2e/tests/update/update-secure-registry.ts
- tests/legacy-cli/e2e/utils/packages.ts
- tests/legacy-cli/e2e/utils/registry.ts
- tests/legacy-cli/e2e_runner.ts
With this change we handle yarn specific environment variables during `ng update` and `ng add`. This is a follow up of #21297
> fix(@angular/cli): handle `YARN_` environment variables during `ng update` and `ng add`     

- renovate.json
Updating the @angular/dev-infra-private packages should be done on all active
development branches.
> build: update renovate to update @angular/dev-infra-private as target: patch

- packages/schematics/angular/utility/latest-versions.ts
Automatically determine the latest compatible Angular Framework version by using `~` matching for the current minor version of @schematics/angular.
> refactor(@schematics/angular): automatically determine the version string to match latest Angular

- packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members.ts
- packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members_spec.ts
When script optimizations are enabled, classes containing downlevelled static properties are wrapped in a pure annotated IIFE to allow the class to be removed if it is otherwise unused. Only properties with initializer values that do not have the potential for side effects can be safely wrapped. Previously, pure annotations were not considered when analyzing the values and this caused classes to be retained that could be considered safe for removal. To resolve this issue, pure annotations are now considered when analyzing a property's initializer value for potential side effects.
> fix(@angular-devkit/build-angular): allow classes with pure annotated static properties to be optimized

- packages/schematics/angular/utility/latest-versions.ts
With this change we improve the versions we set in the users project to be less confusing.  Previously, for both stable and next versions we set the versions of Angular packages to the below;
```
"@angular/animations": "~12.2.0-"
```
This might be problematic as one might not immediately notice that they might depend on a prerelease. The `-` is short character and can be missed when having a large set of dependencies.
With this can we are more explicate by adding `--next` when it's a prerelease and omit the suffix for stable releases.
> refactor(@schematics/angular): improve automatic versions

- renovate.json
With this change we restore the behaviour that Angular packages are updated via a separate PR.
> ci: exclude angular packages from all-minor-patch

- package.json
- packages/ngtools/webpack/BUILD.bazel
- packages/ngtools/webpack/package.json
- packages/ngtools/webpack/src/ngcc_processor.ts
- packages/ngtools/webpack/src/paths-plugin.ts
- yarn.lock
The types used from the `enhanced-resolve` package are available from the `webpack` package and the `getInnerRequest` helper function used in the TypeScript paths resolver plugin is not actually needed.  Webpack's `AliasPlugin` which has similar behavior also does not use the `getInnerRequest` helper function.
> refactor(@ngtools/webpack): remove usage of `enhanced-resolve` dependency

- packages/angular_devkit/build_angular/src/app-shell/index.ts
- packages/angular_devkit/build_webpack/src/webpack/index.ts
With this change we emit the compilation result when the compilation is closed, when the compilation is not in watch mode.
This is needed so that when persistent caching is enabled and architect promise API is used (`.result`) instead of `.output` we wait for the cache to be written prior to terminating the process/resolving the result promise.
The `result` API currently, takes the first emit https://github.com/angular/angular-cli/blob/4f9df9f4a4da81c9ecd8733204226c030f8f7d56/packages/angular_devkit/architect/src/schedule-by-name.ts#L118-L120
Closes #21419
> fix(@angular-devkit/build-webpack): emit result when webpack is closed

- packages/angular/cli/commands/add-impl.ts
- packages/angular/cli/commands/update-impl.ts
The typings package was already present for `npm-package-arg` and the removal of require usage supports the eventual shift to an ESM output for the CLI package.
> refactor(@angular/cli): convert `npm-package-arg` usage from require to import

- packages/schematics/angular/utility/latest-versions.ts
While npm supports a package specifier with a trailing dash, the trailing dash is technically not SemVer compliant and fails with Yarn 2+.
The 12.1.x branch will not have another prerelease which allows the prelease specifiers to be ignored in this case.
> fix(@schematics/angular): ensure valid SemVer range for new project Angular packages

- renovate.json
With this change we update renovate configuration to disallow major update for rxjs and tslib
> ci: disable major updates for rxjs and tslib

- CHANGELOG.md
Cherry-picks the changelog from the "12.1.x" branch to the next branch (master).
> docs: release notes for the v12.1.4 release

- CHANGELOG.md
- package.json
Also this PR cherry-picks the changelog for v12.2.0-rc.0 into the master branch so that the changelog is up to date.
> Update next branch to reflect new release-train "v12.3.0-next.0".

- packages/schematics/angular/utility/latest-versions.ts
Update the version of Angular in latest-versions as `13.0.0-next.0` is not on npm.
> refactor(@schematics/angular): hard code version of Angular in latest-versions

- packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
- packages/angular_devkit/build_angular/src/webpack/configs/worker.ts
Several unused imports and variables as well as redundant conditional checks were removed from the Webpack configuration partials.
> refactor(@angular-devkit/build-angular): remove unused code in webpack configuration partials

- .ng-dev/merge.ts
Currently, we are unable to merge breaking changes, because the label doesn't match the default value set in https://github.com/angular/angular/blob/1684b70b8830684deae4bae20c1e12aeddc4e1df/dev-infra/pr/merge/pull-request.ts#L23
> build: add missing `breakingChangeLabel`

- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/browser/specs/font-optimization_spec.ts
- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/utils/index-file/index-html-generator.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts_spec.ts
We remove inlining of Google fonts in WOFF format since IE 11 is no longer supported. Other supported browsers use WOFF2.
> refactor(@angular-devkit/build-angular): remove WOFF handling from inline-fonts processor

- CHANGELOG.md
> docs: release notes for the v12.2.0 release

- renovate.json
This should avoid Renovate creating redudant PRs such as https://github.com/angular/angular-cli/pull/21480
> ci: disable lockFileMaintenance for `all-schematics-dependencies` group

- packages/angular_devkit/schematics_cli/bin/schematics.ts
- packages/angular_devkit/schematics_cli/bin/schematics_spec.ts
When using the schematics-cli with a local collection, the debug mode is enabled by default. Debug mode also enables dry run mode by default. This can result in a confusing situation when developing a schematic locally as files will not be written to disk but no messages are present explaining why. To improve the developer experience, messages will now be shown both when debug mode is enabled and when dry run is enabled. If either is enabled by default the reason will also be shown.
> fix(@angular-devkit/schematics-cli): log when in debug and/or dry run modes

- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/cross-origin_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/index_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/scripts-array_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/service-worker_spec.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html_spec.ts
- packages/angular_devkit/build_angular/src/utils/index-file/index-html-generator.ts
- packages/angular_devkit/build_angular/src/utils/package-chunk-sort.ts
- packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/index-html-webpack-plugin.ts
- tests/legacy-cli/e2e/tests/basic/scripts-array.ts
- tests/legacy-cli/e2e/tests/build/polyfills.ts
- tests/legacy-cli/e2e/tests/third-party/bootstrap.ts
With this change we add `type=module` to all script tags. This is now possible since IE is no longer supported.
More information about modules can be found here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
> feat(@angular-devkit/build-angular): add `type=module` to all scripts tags

- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
`asset.map` can be `null` which causes an unhandled exception.
```
Error: Optimization error [generated/js/custom-elements-es5-polyfills.js]: TypeError: Cannot destructure property 'mappings' of 'map' as it is null.
at decodeSourceMap (/angular/aio/node_modules/@ampproject/remapping/dist/remapping.umd.js:178:15)
at Array.map (<anonymous>)
at buildSourceMapTree (/angular/aio/node_modules/@ampproject/remapping/dist/remapping.umd.js:725:37)
at Object.remapping [as default] (/angular/aio/node_modules/@ampproject/remapping/dist/remapping.umd.js:831:23)
at default_1 (/angular/aio/node_modules/@angular-devkit/build-angular/src/webpack/plugins/javascript-optimizer-worker.js:44:44)
```
AIO CI failure: https://app.circleci.com/pipelines/github/angular/angular/35940/workflows/c9c91ad3-1645-4a88-bb5b- …
> fix(@angular-devkit/build-angular): handle null maps in JavaScript optimizer worker

- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/src/builders/ng-packagr/works_spec.ts
The unit tests for builders are now within the `src/builders/...` path.
> test(@angular-devkit/build-angular): properly discover Bazel units tests

- packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build-assets_spec.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts
When in watch mode (`ng serve`/`ng build --watch`), Webpack's `copy-webpack-plugin` is currently used to implement the project `assets` option within `angular.json`. Files specified by the `assets` option are intended to be copied to the output unmodified and in their original form.  However, if any JavaScript assets were present they previously would have been unintentionally subject to their respective optimization plugins which would result in modified asset outputs and the potential for breakage of the assets. `ng build` outside of watch mode uses a direct file copy with copy-on-write (where supported) to process assets and is therefore not affected by this situation.
When the `copy-webpack-plugin` is used, it adds a `copied` flag to an asset's info metadata. This flag is now used to …
> fix(@angular-devkit/build-angular): avoid attempting to optimize copied JavaScript assets

- packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts
Support for `karma-coverage-instanbul-reporter` has been dropped in favor of the official karma coverage plugin `karma-coverage`.
> feat(@angular-devkit/build-angular): drop support for `karma-coverage-instanbul-reporter`

- packages/angular/cli/commands/add-impl.ts
> fix(@angular/cli): show error when using non-TTY terminal without passing `--skip-confirmation` during `ng add`

- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/utility/latest-versions.ts
- tests/legacy-cli/e2e/tests/build/prod-build.ts
This sets the peer dependency ranges for Angular packages to the upcoming v13.
> Update Angular peer dependency ranges to v13 prerelease

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Not removing inline sourcemaps when vendor sourcemaps is disabled causes an issue during the JS optimization sourcemap merging phase.
```
Optimization error [936.cf7797927c7f989bd40d.js]: Error: Transformation map 1 must have exactly one source file.
```
When vendor sourcemaps is disabled we are not interested into the said sourcemaps so now we remove the inline sourcemap.
Closes #21508
> fix(@angular-devkit/build-angular): do not consume inline sourcemaps when vendor sourcemaps is disabled.

- packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members.ts
- packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members_spec.ts
The static property optimization pass analyzes the initializers of static properties for possible side effects to determine if optimization is safe to perform. Previously the pure annotation of the form `@__PURE__` was not considered during the analysis. This has now been corrected and all of the following forms are supported: `@__PURE__`, `#__PURE__`, and `@pureOrBreakMyCode`.
> fix(@angular-devkit/build-angular): support both pure annotation forms for static properties

- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
- packages/angular_devkit/build_angular/src/builders/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/builders/server/index.ts
- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
- packages/angular_devkit/build_angular/src/webpack/configs/analytics.ts
- tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts
An application's TypeScript configuration was previously being loaded multiple times in several different aspects of the build setup process. These aspects need to access specific compiler options relevant to that particular area of the setup. However, loading the configuration can be expensive due to the process also calculating the root files for the TypeScript compilation which can result in a large amount of file access. To improve the setup performance, the number of times the TypeScript configuration will be loaded has now been reduced with further reductions possible with additional refactorings.
> refactor(@angular-devkit/build-angular): reduce repeat TypeScript configuration loading

- packages/angular_devkit/build_angular/src/builders/browser/specs/service-worker_spec.ts
- packages/schematics/angular/service-worker/files/ngsw-config.json.template
- packages/schematics/angular/service-worker/index_spec.ts
With this change we update service worker ngsw-config resources extensions.
- Remove `eot`. Old IE font format. Not supported by browsers which support service worker.
- Remove `ani`. Not supported by browsers.
- Add `jpeg` as common alias for `jpg`.
- Add `apng` as modern alternative to `gif`.
- Add `avif` a modern image format.
Closes #21526
> feat(@schematics/angular): update ngsw-config resources extensions

- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
The legacy standalone build optimizer was still used when targetting ES5 due to the new babel-based build optimizer only supporting the analysis of ES2015+ code. Mainly due to the presence of native classes, the new build optimizer is faster and significantly less complex. To fully remove the legacy build optimizer, ES5 downleveling of application code is now also performed by babel when the TypeScript configuration specifies an ES5 target. TypeScript will now internally emit ES2015 in this configuration and ES2015 code will be used as the input to the remainder of the build pipeline. This has been the behavior for third-party packages and now all code will be consistently downleveled to ES5 using the same tooling.
> refactor(@angular-devkit/build-angular): remove legacy ES5 build optimizer usage

- packages/schematics/angular/workspace/files/tsconfig.json.template
With this change, when the workspace is created in strict mode (the default) we add the following  additional tsconfig options;
- [noImplicitOverride](https://www.typescriptlang.org/tsconfig#noImplicitOverride)
- [noPropertyAccessFromIndexSignature](https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature)
Closes #21279
> feat(@schematics/angular): add `noImplicitOverride` and `noPropertyAccessFromIndexSignature` to workspace tsconfig

- lib/packages.ts
- package.json
- packages/angular/cli/bin/ng
- packages/angular_devkit/build_angular/src/sass/sass-service.ts
- packages/angular_devkit/build_angular/src/sass/worker.ts
We drop support for Node.js versions prior to `12.20`.
> fix(@angular/cli): update `engines` to require `node` `12.20.0`

- goldens/public-api/angular_devkit/schematics/src/index.md
- packages/angular_devkit/schematics/src/tree/action.ts
`isAction` has been removed without replacement as it was unused.
> feat(@angular-devkit/schematics): remove deprecated `isAction`

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/css-optimizer-plugin.ts
- tests/legacy-cli/e2e/tests/third-party/bootstrap.ts
- yarn.lock
Esbuild now support CSS sourcemaps which now makes it possible to be used to optimize global CSS.
> perf(@angular-devkit/build-angular): use esbuild as a CSS optimizer for global styles

- goldens/public-api/angular_devkit/build_angular/src/index.md
- packages/angular_devkit/build_angular/src/builders/browser/schema.json
- packages/angular_devkit/build_angular/src/builders/server/schema.json
With this change we deprecate deployUrl which in many case causes unexpected and undesired behaviour. Such as #12322, #21432 and #6666. This is because one of the drawbacks of deploy Url is that this url needs to be injected all over the bundles.
This option was previously introduced to handle application that only assets are hosted on a CDN. This setup is now mostly considered as legacy as it is recommended that the entire application is hosted on a CDN. That said, this legacy behaviour can still be achieved by setting the `baseHref` to the CDN address, while setting the `APP_BASE_HREF` to the application address.
Closes angular#12322 and closes #14901 and closes angular#6666
> feat(@angular-devkit/build-angular): deprecate deployUrl

- packages/angular_devkit/core/src/json/schema/registry.ts
- tests/legacy-cli/e2e/tests/commands/add/version-specifier.ts
BREAKING CHANGE: With this change we drop support for the deprecated behaviour to transform `id` in schemas. Use `$id` instead.
Note: this only effects schematics and builders authors.
> feat(@angular-devkit/core): remove deprecated schema id handling

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/builders/browser/tests/behavior/typescript-target_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
- yarn.lock
`esbuild` and `terser` are now used to optimize global scripts in addition to the previous performance enhancement of optimizing application bundles. This change removes the need for the `terser-webpack-plugin` as a direct dependency and provides further production build time improvements for applications which use global scripts (`scripts` option in the `angular.json` file).
Since `esbuild` does not support optimizing a script with ES2015+ syntax when targetting ES5, the JavaScript optimizer will fallback to only using terser in the event that such a situation occurs. This will only happen if ES5 is the output target for an application and a global script contains ES2015+ syntax. In that case, the global script is technically already invalid for the target environment and may fail at …
> perf(@angular-devkit/build-angular): use esbuild/terser combination to optimize global scripts

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
Application code (TS files) will only contain native async if the TypeScript configuration target is ES2017+. However, third-party libraries can contain native async regardless of the target option. To address these third-party libraries, all non-application files need to be analyzed to determine if they must have native async downlevelled. The analysis is first resource path based and then a string match search for the async keyword. This approach has the potential for rare false positives (for example, the word async in a comment) but the outcome would only be a small amount of additional processing for that one file due to the no-op transformation. This is in contrast to a more exact method covering those rare false positives but that would require a more expensive analysis operation …
> fix(@angular-devkit/build-angular): ensure native async is downlevelled in third-party libraries

- CHANGELOG.md
> docs: release notes for the v12.2.1 release

- docs/process/release.md
The PR search link still has the old label "PR action: merge", but this has been updated to "action: merge".
> doc: fix caretaker PR search

- .ng-dev/commit-message.ts
- .ng-dev/format.ts
- .ng-dev/github.ts
- .ng-dev/merge.ts
- .ng-dev/release.ts
- package.json
- yarn.lock
Update the version of @angular/dev-infra-private being used, migrating to use
the version generated from angular/dev-infra rather than from angular/angular.
> build: update @angular/dev-infra-private

- .github/workflows/dev-infra.yml
Automatically add/remove `breaking changes` label to PRs as needed based on whether
the PR contains a commit with a breaking change.
> ci: add breaking changes auto labeling action

- packages/angular_devkit/build_angular/src/webpack/utils/async-chunks.ts
When using custom builders, it is possible to remove entries from the webpack-configuration manually. This may eventually lead to undefined entryPoints in async-chunks.ts - this fix handles exactly this problem
> fix(@angular-devkit/build-angular): handle undefined entrypoints when marking async chunks

- docs/process/release.md
When transitioning from prerelease to stable, several SemVer ranges for packages referenced in the `package.json` files need to be adjusted so that the unsupported prerelease versions are not mentioned in the final stable release.
> docs: update release documentation regarding prerelease semver ranges

- packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/css-optimizer-plugin.ts
With this change we provide the list of supported browsers to Esbuild during CSS optimizations, so it can perform optimizations based on the browser support needed.
Closes #21594
> fix(@angular-devkit/build-angular): provide supported browsers to esbuild

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
…
With this change we provide the list of supported browsers to Esbuild during CSS optimizations, so it can perform optimizations based on the browser support needed.
Closes #21594
> [patch] fix(@angular-devkit/build-angular): provide supported browsers to esbuild

- CHANGELOG.md
> docs: release notes for the v12.2.2 release

- goldens/public-api/angular_devkit/schematics/src/index.md
- packages/angular_devkit/schematics/BUILD.bazel
- packages/angular_devkit/schematics/package.json
- packages/angular_devkit/schematics/src/sink/host.ts
- packages/angular_devkit/schematics/src/tree/recorder.ts
- packages/angular_devkit/schematics/src/tree/recorder_spec.ts
- packages/angular_devkit/schematics/src/utility/environment-options.ts
- packages/angular_devkit/schematics/src/utility/update-buffer.ts
- packages/angular_devkit/schematics/src/utility/update-buffer_spec.ts
This PR adds UpdateBuffer2 which should eventually replace UpdateBuffer. UpdateBuffer2 internally uses the magic-string library.
UpdateBuffer and related symbols have been marked as deprecated.
Closes #21110
> feat(@angular-devkit/schematics): add UpdateBuffer2 based on magic-string

- .circleci/config.yml
> ci: remove nightly CI run for 9.1.x branch

- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
This is no longer needed size differential loading was removed.
> refactor(@angular-devkit/build-angular): remove differential loading stats generation

- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-13/update-libraries.ts
- packages/schematics/angular/migrations/update-13/update-libraries_spec.ts
This migration updates libraries to be published in partial mode instead of view engine. Also, it removed deprecated options from ng-packagr configuration.
> feat(@schematics/angular): migrate libraries to be published from ViewEngine to Ivy Partial compilation

- packages/ngtools/webpack/src/paths-plugin.ts
The internal TypeScript path mapping Webpack resolver plugin is used to adjust module resolution during builds via the TypeScript configuration `paths` option. Prior to a build, the `paths` option is now preprocessed to limit the amount of analysis that is needed within each individual module resolution attempt during a build. Since module resolution attempts can occur frequently during a build, this change offers the potential to reduce the total cost of module resolution especially for applications with a large amount of configured path mappings.
> perf(@ngtools/webpack): reduce repeat path mapping analysis during resolution

- packages/angular/cli/commands/lint-long.md
- Update the description of the lint command for when a project name is not provided.
- Use diction equivalent to the [description of the test command](https://github.com/angular/angular-cli/blob/master/packages/angular/cli/commands/test-long.md).
Notes
- Closes #21619
> docs: update the description of the lint command

- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/commands/version-impl.ts
- packages/angular/cli/models/schematic-engine-host.ts
- packages/angular/cli/models/version.ts
- packages/angular/cli/src/typings.d.ts
- packages/angular/cli/utilities/package-metadata.ts
Preparation for future transition to ESM output for `@angular/cli`.
See individual commits.
> `@angular/cli` global require cleanup

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
Using `css-loader` version 6 exposed a bug in `mini-css-extract-plugin` which doesn't handle `@import` rules order correctly.
See https://github.com/webpack-contrib/css-loader/issues/1365
Closes: #21662
> fix(@angular-devkit/build-angular): update `mini-css-extract-plugin` to `2.2.1`

- CHANGELOG.md
> docs: release notes for the v12.2.4 release

- packages/angular_devkit/build_angular/src/webpack/plugins/css-optimizer-plugin.ts
The browser targets provided by `browserslist` have several differences than what `esbuild` expects for the Safari browsers. The first is that the iOS Safari is named `ios_saf` within browserslist and `ios` by esbuild. The former is now converted to the later when generating the target list for esbuild.  The second difference is that `browserslist` supports a `TP` (Technology Preview) version for Safari but esbuild expects a numeric value for all versions. Since a TP version of Safari is assumed to be the latest unreleased version and as a result supports all currently known features, a high version number (999) is used as a replacement when generating the target list for esbuild.
Closes: #21700
> fix(@angular-devkit/build-angular): improve Safari browserslist to esbuild target conversion

- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
Compression isn't particular useful during development, also in version 13 we disable this completely due to timeouts issues which it causes.
This backports this change which also addresses another issues as described here #21720
Closes #21720
> fix(@angular-devkit/build-angular): disable dev-server response compression

- CHANGELOG.md
> docs: release notes for the v12.2.5 release

- .ng-dev/merge.ts
Merge configuration no longer accepts custom labels, in order to achieve consistent labelling as specified in the Angular versioning/branching/labelling spec.
> build: update dev-infra merge configuration

- packages/angular/cli/utilities/color.ts
- packages/angular_devkit/build_angular/src/utils/color.ts
In some cases, custom implementation of stdout, don't extend `WriteStream` which causes colors not to be included in the output.
Closes #21732
> fix(@angular-devkit/build-angular): handle `FORCE_COLOR` when stdout is not instance of `WriteStream`

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Polyfill related packages should not be downlevelled due to the nature of their code which may need to perform feature testing or leverage native capabilities to extract browser support information necessary to properly polyfill a given browser. In the case of `web-streams-polyfill`, it leverages the `%AsyncIteratorPrototype%`, when available, to fully polyfill its stream implementations.  To access `%AsyncIteratorPrototype%`, a native async generator is needed and therefore the code present in the package cannot have this case of a native async generator downlevelled. `core-js` is also excluded for similar (and additional reasons).
Closes: #21735
> fix(@angular-devkit/build-angular): add web-streams-polyfill to downlevel exclusion list

- CHANGELOG.md
> docs: release notes for the v12.2.6 release

- packages/angular_devkit/build_angular/src/utils/build-options.ts
- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
- packages/angular_devkit/build_angular/src/utils/read-tsconfig.ts
- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/configs/typescript.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
With the Angular CLI currently being a CommonJS package, this change uses a dynamic import to load `@angular/compiler-cli` which may be ESM. CommonJS code can load ESM code via a dynamic import. Unfortunately, TypeScript will currently, unconditionally downlevel dynamic import into a require call. require calls cannot load ESM code and will result in a runtime error. To workaround this, a Function constructor is used to prevent TypeScript from changing the dynamic import. Once TypeScript provides support for keeping the dynamic import this workaround can be dropped and replaced with a standard dynamic import.
> Support a future ESM-only `@angular/compiler-cli` package (1)

- packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts
Webpack-dev-server doesn't handle concurrency very well. When using port 0, and 2 processes start at the same time, they end up being given the same port. The main reason for the issue is that it find a free port, put only uses at a later stage.
> fix(@angular-devkit/build-webpack): better handle concurrent dev-servers

- packages/angular/cli/commands/new.md
`--createApplication` is deprecated in favor of `--create-application`
> docs: replace deprecated camel-case argument

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/esbuild-check.js
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/webpack/plugins/css-optimizer-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/esbuild-executor.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
- tests/legacy-cli/e2e/tests/build/esbuild-unsupported.ts
- yarn.lock
In the event that the Angular CLI is executed on a platform that does not yet have native support for esbuild, the WASM-based variant of esbuild will now be used. If the first attempt to optimize a file fails to execute the native variant of esbuild, future executions will instead use the WASM-based variant instead which will execute regardless of the native platform. The WASM-based variant, unfortunately, can be significantly slower than the native version (some cases can be several times slower). For install time concerns regarding the esbuild post-install step, esbuild is now listed as an optional dependency which will allow the post-install step to fail but allow the full npm install to pass. This install scenario should only occur in the event that the esbuild native binary cannot be …
> fix(@angular-devkit/build-angular): support WASM-based esbuild optimizer fallback

- CHANGELOG.md
> docs: release notes for the v12.2.7 release

- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/utils/load-esm.ts
- packages/angular_devkit/build_angular/src/utils/read-tsconfig.ts
- packages/angular_devkit/build_angular/src/utils/service-worker.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
This is a followup PR for #21771 that addresses partial compilation linker and service worker usage.
With the Angular CLI currently being a CommonJS package, this change uses a dynamic import to load `@angular/compiler-cli/linker[/babel]` and `@angular/service-worker` which may be ESM. CommonJS code can load ESM code via a dynamic import. Unfortunately, TypeScript will currently, unconditionally downlevel dynamic import into a require call. require calls cannot load ESM code and will result in a runtime error. To workaround this, a Function constructor is used to prevent TypeScript from changing the dynamic import. Once TypeScript provides support for keeping the dynamic import this workaround can be dropped and replaced with a standard dynamic import.
> Support ESM `@angular/compiler-cli` linker and `@angular/service-worker` usage

- packages/schematics/angular/utility/latest-versions/package.json
With the Angular framework supporting rxjs 7 for Angular 13, new projects (`ng new ...`) can now be created using rxjs 7. rxjs 6 is also still fully supported with Angular 13 allowing existing projects to continue to use rxjs 6 if preferred or required.
Support for rxjs 7 within the framework was enabled via https://github.com/angular/angular/pull/42991
> feat(@schematics/angular): create new projects with rxjs 7

- .circleci/config.yml
The Windows CI test job is now isolated from the linux jobs.
The previous Windows CI setup reused the workspace from the linux CI setup job. This job performed a package install which would install linux specific dependencies. Some dependencies (e.g., `esbuild`) modify themselves as a post-install action to optimize the runtime performance and may alter themselves in platform specific ways. As a result the existing packages may then be invalid on Windows. Even though the Windows CI job performed another package install, these self-modified packages may persist and cause install and/or runtime issues on Windows. By isolating the Windows CI jobs via separately checking out and rebasing the code, the Windows dependencies will no longer be affected by the linux CI jobs. This change also has …
> ci: ensure Windows CI installs Windows specific npm dependencies

- packages/angular_devkit/build_angular/src/utils/load-esm.ts
- packages/angular_devkit/build_angular/src/utils/service-worker.ts
Absolute import paths, especially on Windows, must be `file://` URLs when using ESM. Otherwise, Windows drive letters (e.g., `C:`) would be interpreted as a protocol instead of a drive letter when performing the import.
> fix(@angular-devkit/build-angular): use URLs for absolute import paths with ESM

- packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/proxy-config_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
The `proxyConfig` option now supports loading ESM configuration files in addition to JSON and CommonJS files. ESM files (such as those ending with `.mjs`) must provide a default export with the configuration object.
For example, a `proxy.config.mjs` containing the follow is now possible:
```
export default { "/api/*": { "target": "http://127.0.0.1:5001" } };
```
Closes #21623
> feat(@angular-devkit/build-angular): support ESM proxy configuration files for the dev server

- packages/angular_devkit/build_angular/src/babel/plugins/adjust-typescript-enums.ts
- packages/angular_devkit/build_angular/src/babel/plugins/adjust-typescript-enums_spec.ts
With Angular Package Format v13, we will be using a more recent version of rollup. Rollup
always suffixed exports to avoid collisions, but with the most recent version, the order
has changed slightly changed. e.g. previously for `@angular/core`, there were two instances
of the `ViewEncapsulation` enum part of the `fesm` bundle. The second instance of the enum
orginated from the compiler <--> core facade and it got renamed to avoid conflicts with the
actual declaration of `ViewEncapsulation`.
Now this has changed, and the first export is being renamed instead. This now breaks at runtime 
because the first export is being incorrectly transformed by the adjust enum plugin of `build-angular`.
The plugin always had this problem of incorrectly transforming the enums, but it never surfaced …
> fix(@angular-devkit/build-angular): babel adjust enum plugin incorrectly transforming loose enums

- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/builders/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/builders/extract-i18n/ivy-extract-loader.ts
- packages/angular_devkit/build_angular/src/utils/load-translations.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
With the Angular CLI currently being a CommonJS package, this change uses a dynamic import to load `@angular/localize` which may be ESM. CommonJS code can load ESM code via a dynamic import. Unfortunately, TypeScript will currently, unconditionally downlevel dynamic import into a require call. require calls cannot load ESM code and will result in a runtime error. To workaround this, a Function constructor is used to prevent TypeScript from changing the dynamic import. Once TypeScript provides support for keeping the dynamic import this workaround can be dropped and replaced with a standard dynamic import.
> refactor(@angular-devkit/build-angular): support ESM `@angular/localize` usage

- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
Since version 4.2.0 webpack-dev-server supports read the mentioned files.
See:
https://github.com/webpack/webpack-dev-server/blob/9bb6f7894833fa561882258a307e45294427187b/CHANGELOG.md#420-2021-09-09
> refactor(@angular-devkit/build-angular): pass SSL cert and key path to dev-server

- packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts
No longer needed due to a change in webpack-dev-server. See: https://github.com/webpack/webpack-dev-server/blob/ed67f66fc41eb1dd83fb84ecaa18703559dbe2ae/lib/Server.js#L77-L79
> refactor(@angular-devkit/build-webpack): port 0 WEBPACK_DEV_SERVER_BASE_PORT workaround

- packages/angular/cli/lib/config/workspace-schema.json
This fixes the JSON workspace schema and removed options projects `.project.cli`. Currently only `defaultCollection` is used from `projects.cli` other options are ignored.
https://github.com/angular/angular-cli/blob/9afe185fc61390efec6bfbb16a0586487fd6f118/packages/angular/cli/models/schematic-command.ts#L381
> fix(@angular/cli): remove unused cli project options.

- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/browser-support_spec.ts
> fix(@angular-devkit/build-angular): update IE unsupported and deprecation messages

- packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/source-map_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/web-worker_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/tests/options/output-hashing_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- tests/legacy-cli/e2e/tests/basic/build.ts
- tests/legacy-cli/e2e/tests/build/output-hashing.ts
- tests/legacy-cli/e2e/tests/build/prod-build.ts
- tests/legacy-cli/e2e/tests/update/update-9.ts
`xxhash64` uses a faster WASM based hash mechanism.
> perf(@angular-devkit/build-angular): change webpack hashing function to `xxhash64`

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
This is a follow-up to fb210e5b747ce0351dd9ee7d482770b9cfa71133 which
added support for the ESM-variant of the `@angular/localize` package,
and also prepared for the `tools/` secondary entry-point we will expose
as of v13.
Unfortunately this change currently does not pass-through the ESM-loaded
plugin creators as the option (which is passed to the Babel plugin) is
incorrect. This was hidden due to a type cast. This commit fixes the
issue and also ensures TS would complain in the future if the option
names differ.
Also removes an unnecessary second `typeof import` where one already exists in the same file.
> fix(@angular-devkit/build-angular): ESM-interop loaded plugin creators of `@angular/localize/tools` not respected

- tests/legacy-cli/e2e/assets/webpack/test-app/app/feature/lazy-feature.module.ts
One E2E test was still using the deprecated string-form of the routing `loadChildren` property. The `loadChildren` usage has now been converted to use the suppported dynamic import form. The string-form has been removed from Angular v13.
> test: remove last string-form loadChildren usage

- packages/schematics/angular/application/files/src/polyfills.ts.template
This removes polyfills only required on Internet Explorer since it is no longer supported (`web-animations-js`). Also updates the doc comment to leave specific versions unspecified, since they are already out of date and updating them now would just cause them to go out of date again in the future. Instead, users can visit the browser support guide to understand find the most up to date browser versions supported.
Not sure if this is considered a breaking change, but personally I don't view the exact contents of any generated files to be strict public API. Since this PR doesn't change the polyfills actually used in a new project, I don't think this needs to be called out as a breaking change.
> refactor(@schematics/angular): drop IE-only polyfills and drop versions from comment

- packages/angular_devkit/build_angular/src/webpack/configs/browser.ts
- packages/angular_devkit/build_angular/src/webpack/configs/server.ts
- packages/angular_devkit/build_angular/src/webpack/configs/test.ts
APF version 13 will include es2020, with this change we favor es2020 entrypoints.
> feat(@angular-devkit/build-angular): favor es2020 main fields

- CHANGELOG.md
> docs: release notes for the v12.2.8 release

- packages/angular/cli/src/commands/update/schematic/index.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
- packages/angular_devkit/build_angular/src/builders/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/configs/test.ts
- tests/legacy-cli/e2e/assets/webpack/test-app/webpack.config.js
The original update analysis would prepend the package name to all migration collection files. This was required at the time to ensure the migration collection files would be found. The existing update logic, however, no longer requires this change but the change previously had no negative effects as both the relative and module specifier methods would successfully resolve the migrations. But with the conversion to ESM-based packages that use the package.json `exports` field, deep imports into a package are no longer possible unless the migration collection files are explicitly exported. Relative migration collection paths are now preferred since they are based off of the location of the package's `package.json` and do not require additional `exports` field entries. The original update …
> fix(@angular/cli): keep relative migration paths during update analysis

- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-13/drop-ie-polyfills.ts
- packages/schematics/angular/migrations/update-13/drop-ie-polyfills_spec.ts
Removes the `classlist.js` and `web-animations-js` polyfills from any polyfills files in a workspace. Specifically, it looks for `import 'classlist.js';` and `import 'web-animations-js';`, then removes those them along with any preceeding comments (aside from the file overview and browser polyfills header comment).
Previous versions of `ng new` generated a polyfills file with commented out imports for both modules, to avoid including them by default while giving users an easy way to enable them. This migration also looks for these commented out imports and removes them along with associated descriptive comments. This has no effect on the application, but cleans up unnecessary noise from the polyfills file.
This PR was heavily inspired by a [previous …
> feat(@schematics/angular): drop polyfills required only for Internet Explorer now that support has been dropped for it

- packages/angular_devkit/build_angular/src/builders/browser/tests/options/named-chunks_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- tests/legacy-cli/e2e/tests/build/worker.ts
With the removal of suppport for the string form of `loadChildren` within the Angular router, the usage of `System.import` has also been removal from `@angular/core`. This removal allows for the additional removal of all workarounds within the Angular CLI due to the `System.import` usage. Webpack's deprecated support for `System.import` was previously required to be enabled which resulted in warnings that then needed to be suppressed. A Webpack context dependency replacement was also previously required to prevent Webpack from failing due to the otherwise unknown behavior of the `System.import` call. All of these workarounds have now been removed. Since Webpack bases its output file numbering system on both the content and the configuration, several of the unnamed output test files needed …
> refactor(@angular-devkit/build-angular): remove unneeded `@angular/core` System.import workarounds

- packages/angular_devkit/build_angular/src/builders/browser/schema.json
- packages/angular_devkit/build_angular/src/builders/browser/tests/options/inline-critical_spec.ts
- packages/angular_devkit/build_angular/src/utils/normalize-optimization.ts
With this change we disable critical css inline by default. The main motivations are the following issues #20760 and #20864.
Inlining of critical CSS is no longer enable by default. Users already on Angular CLI version 12 and have not opted-out from using this feature are encouraged to opt-in using the browser builder `inlineCritical` option.
The motivation behind this change is that the package used to parse the CSS has a number of defects which can lead to unactionable error messages when updating to Angular 13 from versions priors to 12. Such errors can be seen in the following issue #20760.
```json
"configurations": {
"production": {
"optimization": {
"styles": {
"inlineCritical": true,
}
},
...
}
```
> feat(@angular-devkit/build-angular): disable critical CSS inlining by default

- packages/angular_devkit/build_optimizer/README.md
It's functionality has been included in `@angular-devkit/build-angular` so this package is no longer needed by the CLI and we will stop publishing the package soon.
> docs: mark `@angular-devkit/build-optimizer` as deprecated.

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
ES2020 can contain JS syntax which are not compatible with all supported Node.js versions such as optional chaining.
> fix(@angular-devkit/build-angular): use es2015 when generating server bundles

- packages/angular_devkit/build_angular/src/utils/action-executor.ts
There was previously the potential for two workers to complete quickly at the same time which could result in one of the results not being propagated to the remainder of the system. This situation has now been corrected by removing the worker execution at a later point in the process.
> fix(@angular-devkit/build-angular): remove potential race condition in i18n worker execution

- CHANGELOG.md
Cherry-picks the changelog from the "13.0.x" branch to the next branch (master).
> docs: release notes for the v13.0.0-rc.3 release

- CHANGELOG.md
> docs: release notes for the v12.2.13 release

- packages/ngtools/webpack/README.md
When not using the Angular CLI, the Babel-based Ivy linker is also required to successfully build an application. A section describing the setup of the linker in addition to the Angular compiler plugin has now been included with links to the AIO documentation and the babel-loader for additional information.
> docs(@ngtools/webpack): add Ivy linker setup documentation to readme

- CHANGELOG.md
Cherry-picks the changelog from the "13.0.x" branch to the next branch (master).
> docs: release notes for the v13.0.1 release

- packages/angular_devkit/build_angular/src/builders/dev-server/hmr_spec.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/hmr/hmr-accept.ts
```
Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
```
Closes #22084
> fix(@angular-devkit/build-angular): don't restore `input` of type `file` during HMR

- packages/angular/cli/models/schematic-engine-host.ts
Files should not redirect `@angular/core` and instead use the direct dependency of the `@schematics/angular` package. This allows old major version migrations to continue to function even though the latest major version may have breaking changes in `@angular/core`.
> fix(@angular/cli): avoid redirecting @angular/core in Angular migrations

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
esbuild will issue a warning when `@charset` is in the middle of the file. This is caused by css-loader will concats the file and doesn't hoist `@charset`, (https://github.com/webpack-contrib/css-loader/issues/1212).
While, esbuild will issue a warning regarding the above, it will hoist to the very top.
In many cases, this warning is not actionable by the users as the `@charset` would be likely specified in 3rd party libs.
Closes #22097
> fix(@angular-devkit/build-angular): suppress "@charset" must be the first rule in the file warning

- packages/schematics/angular/migrations/update-13/update-libraries.ts
Our migrations only handle JSON configs.
Closes #22107
> fix(@schematics/angular): show warning when migrating ng-packagr JS configurations

- packages/angular/cli/src/commands/update/schematic/index.ts
With this change we favor the `packageGroupName` name when specified and only fallback to use the first item in in the `packageGroup` array when it is not specified.
Closes #22087
> fix(@angular/cli): favor ng-update `packageGroupName` in ng update output

- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/code-coverage_spec.ts
We now pass the input sourcemap to istanbul babel plugin, since this is used directly by the instrumenter https://github.com/istanbuljs/babel-plugin-istanbul/blob/d58c92a7de5e8ac84c598e02325b05f5b9800107/src/index.js#L126-L129 and is needed to remapped instrumented code back to the original source.
Previously, the lack of this caused incorrect reports of uncovered and coverage code and also incorrectly mappings in the HTML report.
Closes #22118
> fix(@angular-devkit/build-angular): improve sourcemap fidelity during code-coverage

- packages/schematics/angular/application/other-files/app.component.html.template
Fixes that the `new new` generated app component template currently
provides a link to Angular Animations with the Angular Material logo,
according to: https://angular.io/presskit.
This commit switches the link to Angular Material with the assumption
that this was intended to point to Angular Material from the
beginning on.
> refactor: fix ng-new template pointing to Angular animations with Material logo

- packages/schematics/angular/migrations/update-13/update-libraries.ts
- packages/schematics/angular/migrations/update-13/update-libraries_spec.ts
Currently ng-packagr, can be configured used in package.json. Previously, the migration didn't handle this case.
Closes #22129
> fix(@schematics/angular): migrate ng-packagr configurations in package.json

- package.json
- yarn.lock
Update to the latest package which properly checks if the running version of ng-dev is the version
described in yarn lock.
> build: update to latest @angular/dev-infra-private to address issues related to verifying environment

- package.json
- yarn.lock
Update to the latest package which properly checks if the running version of ng-dev is the version
described in yarn lock.
> [Patch Version] build: update to latest @angular/dev-infra-private to address issues related to verifying environment

- .github/angular-robot.yml
Remove `cla: yes` from the require labels for merging as the CLACheck
tool no longer relies on labels.
Enforcement of the CLA being signed is still enforced by the status check
which is visible both in Github as well as checked by merge tooling.
> ci: remove `cla: yes` from required labels

- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/proxy-config_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
The `proxyConfig` option for the `dev-server` builder now supports JSON files containing comments and trailing commas.
Several additional tests regarding the use of ESM and CommonJS JavaScript configuration files were also added to reduce the likelihood of future regressions.
Closes: #21862
> feat(@angular-devkit/build-angular): support JSON comments in dev-server proxy configuration file

- packages/schematics/angular/application/files/karma.conf.js.template
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/application/schema.json
- packages/schematics/angular/component/index.ts
- packages/schematics/angular/component/index_spec.ts
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/schema.json
- packages/schematics/angular/ng-new/index.ts
- packages/schematics/angular/ng-new/schema.json
- packages/schematics/angular/utility/validation.ts
- packages/schematics/angular/workspace/schema.json
With this change we update the validation of the libraries and application projects names to fully allow characters that make a valid NPM package name. http://json.schemastore.org/package has been used as reference.
We also remove validators that are no longer needed.
Closes #11051
> feat(@schematics/angular): loosen project name validation

- packages/angular/cli/models/architect-command.ts
- tests/legacy-cli/e2e/tests/commands/builder-not-found.ts
When a builder-based command is executed (build, serve, test, etc.) and the builder's node package cannot be found a more user-friendly error message is now displayed. In addition, when the builder's node package cannot be found, a check is performed to determine if the node packages for the workspace may have not been installed. Previously, a potentially long stacktrace was shown which did not provide much information regarding how to correct the issue.
Closes: #10536
> feat(@angular/cli): provide more detailed error for not found builder

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/transfer-size-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
- tests/legacy-cli/e2e/tests/basic/build.ts
When optimizations are enabled (either scripts or styles), an additional column will now be present in the output report shown in the console for an application build. This additonal column will display the estimated transfer size for each file as well as the total initial estimated transfer size for the initial files. The estimated transfer size is determined by calculating the compressed size of the file using brotli's default settings. In a development configuration (a configuration with optimizations disabled), the calculations are not performed to avoid any potential increase in rebuild speed due to the large size of unoptimized files.
```
Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
main.51c3048e87eac4fd.js      | main          | 132.07 kB | …
```
> feat(@angular-devkit/build-angular): add estimated transfer size to build output report

- package.json
- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
- yarn.lock
See: https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#450-2021-11-13
> refactor(@angular-devkit/build-angular): replace usage of `webpack-dev-server` deprecated `https` option

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
See https://github.com/webpack/webpack/releases/tag/v5.62.0 and https://github.com/webpack/webpack/issues/14580 for more context.
> perf(@angular-devkit/build-angular): disable webpack backwards compatible APIs

- .github/angular-robot.yml
The CLA tools no longer report statuses as it is being run as Github actions.
> ci: remove `cla/google` from required statues

- CHANGELOG.md
Cherry-picks the changelog from the "13.0.x" branch to the next branch (master).
> docs: release notes for the v13.0.3 release

- packages/schematics/angular/workspace/files/__dot__vscode/extensions.json.template
- packages/schematics/angular/workspace/files/__dot__vscode/launch.json.template
- packages/schematics/angular/workspace/files/__dot__vscode/tasks.json.template
When generating a new workspace we now generate several VS Code configurations.
- extensions: we added config to recommand to use official VS Code extensions.
- launch: added run and debug launch scripts for `ng test` and `ng serve`
- tasks: configured `npm start` and `npm test` to better support the launch scripts
More information about each files can be found
- extensions: https://go.microsoft.com/fwlink/?linkid=827846
- launch: https://go.microsoft.com/fwlink/?linkid=830387
- tasks: https://go.microsoft.com/fwlink/?LinkId=733558
Closes #2672
> feat(@schematics/angular): add VS Code configurations when generating a new workspace

- packages/angular/cli/commands/lint-impl.ts
- packages/angular/cli/models/architect-command.ts
To improve the developer experience for the `ng lint` command in new projects, the lint command will now ask the developer if they wish to install `@angular-eslint/schematics` when no lint target has been configured for the specified project. `@angular-eslint/schematics` is currently the only option listed in the warning shown prior to the introduction of the prompt in this change. If additional example packages are added to the warning text in the future, the confirmation prompt should be changed to a list prompt which would allow the user to pick one of the potential future listed example packages.
Closes: #21387
> feat(@angular/cli): ask to install angular-eslint when running ng lint in new projects

- goldens/circular-deps/packages.json
- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/bundle-calculator.ts
- packages/angular_devkit/build_angular/src/utils/bundle-calculator_spec.ts
- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
> feat(@angular-devkit/build-angular): colorize file raw sizes based on failing budgets

- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/lib/init.ts
- tests/legacy-cli/e2e/tests/misc/npm-7.ts
- tests/legacy-cli/e2e/tests/update/update-secure-registry.ts
Previously, when using an older version of the Angular CLI, during `ng update`, we download the temporary `latest` version to run the update. The ensured that when running that the runner used to run the update contains the latest bug fixes and improvements.
This however, can be problematic in some cases. Such as when there are API breaking changes, when running a relatively old schematic with the latest CLI can cause runtime issues, especially since those schematics were never meant to be executed on a CLI X major versions in the future.
With this change, we improve the logic to determine which version of the Angular CLI should be used to run the update.
Below is a summarization of this.
- When using the `--next` command line argument, the `@next` version of the CLI will be used to run …
> fix(@angular/cli): logic which determines which temp version of the CLI is to be download during `ng update`

- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html_spec.ts
We add the `dir` (direction) HTML attribute when using localization.
Closes #16047
> feat(@angular-devkit/build-angular): set `dir` attribute when using localization

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
Hello,
I am opening this PR to fix one of the problems we noticed when upgrading to Angular 13 in [ng-bootstrap](https://ng-bootstrap.github.io/) (cf https://github.com/ng-bootstrap/ng-bootstrap/issues/4178)
We are using a custom webpack configuration with `@angular-builders/custom-webpack:browser` to add `coverage-istanbul-loader` but it fails with the `don't know how to turn this value into a node` error.
This similar to #21967 which was previously fixed in commit da1733cc69eeac1417e47df23389da1658850ada but the fix was lost as part of commit 0c44ab305836abab26dc81d7c962f330898213fd.
Cf also https://github.com/istanbuljs/istanbuljs/issues/646
`remapping` returns a SourceMap object and not a plain object. This causes Babel to fail with `don't know how to turn this value into a node` when …
> fix(@angular-devkit/build-angular): transform remapped sourcemap into a plain object

- packages/angular/cli/commands/update-impl.ts
In some cases, when a migration fails an error is not thrown, instead the `executeMigration` return a `false` value when resolved.
With this change, we fix an issue were failed migrations resulted in the process of not terminating with a non-zero error code.
> fix(@angular/cli): exit with a non-zero error code when migration fails during `ng update`

- .circleci/config.yml
- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/lib/cli/index.ts
- packages/angular/cli/lib/init.ts
- packages/angular/cli/models/version.ts
- packages/schematics/update/update/index.ts
- tests/legacy-cli/e2e/tests/update/update-1.0.ts
- tests/legacy-cli/e2e/tests/update/update-1.7-longhand.ts
- tests/legacy-cli/e2e/tests/update/update-1.7.ts
- tests/legacy-cli/e2e/tests/update/update-7.0.ts
- tests/legacy-cli/e2e/tests/update/update-multiple-versions.ts
Back-porting of https://github.com/angular/angular-cli/pull/22033, https://github.com/angular/angular-cli/pull/21986/ and https://github.com/angular/angular-cli/pull/22200
> v10 `ng update` fixes 

- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build_translation_watch_spec.ts
- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
When using i18n with the dev server, the translation files will now be linked as a dependency to any file containing translated text. This allows translation files to be watched and the application to be rebuilt using the changed translation files.
Closes #16341
> feat(@angular-devkit/build-angular): watch i18n translation files with dev server

- packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/module-cjs_spec.ts
- packages/ngtools/webpack/src/loaders/direct-resource.ts
- packages/ngtools/webpack/src/transformers/replace_resources.ts
- packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
With this change we fix an issue in JIT mode were we try to access an inexistent `default` property of styles modules when emitted in CJS.
Also, we now emit templates modules without the default property when not targeting ES2015 or greater to normalize the how to `require` templates and styles.
Closes #21588
> fix(@ngtools/webpack): JIT mode CommonJS accessing inexistent `default` property

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Previously the glob didn't catch nested `node_modules`.
Closes #22163
> fix(@angular-devkit/build-angular): don't watch nested `node_modules` when polling is enabled

- packages/angular/pwa/BUILD.bazel
- packages/angular_devkit/architect_cli/BUILD.bazel
- packages/angular_devkit/schematics_cli/BUILD.bazel
Before re-writing the `build.ts` script to use bazel for building, I thought a good place to start would be to add some missing rules. Three of the packages built by `build.ts` didn't have corresponding `pkg_npm` targets.
> build: add pkg_npm rules for remaining packages

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Before:
```
✔ Browser application bundle generation complete.
Initial Chunk Files | Names         |   Raw Size
styles.js           | styles        |    9.47 kB |
runtime.js          | runtime       |    4.98 kB |
polyfills.js        | polyfills     |    1.81 kB |
vendor.js           | vendor        | 1012 bytes |
main.js             | main          | 1004 bytes |
| Initial Total |   18.24 kB
Build at: 2021-12-01T15:36:51.797Z - Hash: fe036e992695bafa - Time: 2775ms
./node_modules/css-loader/dist/runtime/api.js - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot use a JavaScript or TypeScript file (/Users/alanagius/cli-reproductions/error-testing/src/app/app.component.ts) in a component's styleUrls or templateUrl.
at …
```
> fix(@angular-devkit/build-angular): display cleaner errors

- packages/angular_devkit/build_angular/src/builders/extract-i18n/ivy-extract-loader.ts
- tests/legacy-cli/e2e/tests/i18n/extract-ivy-disk-cache.ts
Extracted messages are not part of Webpack pipeline and hence they cannot be retrieved from cache. Therefore, we need to mark the extraction loader as non cacheable.
Closes #22264
> fix(@angular-devkit/build-angular): correctly extract messages when using cached build

- CHANGELOG.md
Cherry-picks the changelog from the "13.0.x" branch to the next branch (master).
> docs: release notes for the v13.0.4 release

- packages/ngtools/webpack/src/ivy/loader.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
Currently, when `analyzeAsync` promise is rejected, the build fails with an `UnhandledPromiseRejectionWarning`.
Example:
```
(node:69086) UnhandledPromiseRejectionWarning: Error: Cannot use a JavaScript or TypeScript file (/Users/error-testing/src/app/app.component.ts) in a component's styleUrls or templateUrl.
at WebpackResourceLoader._compile (/Users/error-testing/node_modules/@ngtools/webpack/src/resource_loader.js:107:19)
at WebpackResourceLoader.get (/Users/error-testing/node_modules/@ngtools/webpack/src/resource_loader.js:266:44)
at Object.resourceHost.readResource (/Users/error-testing/node_modules/@ngtools/webpack/src/ivy/host.js:48:35)
at AdapterResourceLoader.preload (file:///Users/error-testing/node_modules/@angular/compiler-cli/bundles/index.js:12177:31)
at resolveStyleUrl …
```
> fix(@ngtools/webpack): handle promise rejection during Angular program analyzes

- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html_spec.ts
In some cases we don't ship certain locales, or they map to files which are named only the language IDs. Example `en-US`, which it's locale data is available from `@angular/common/locales/en.mjs`
Closes #22285
> fix(@angular-devkit/build-angular): fallback to use language ID to set the `dir` attribute

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
When `process.versions.webcontainer` is a string it means that we are running in a StackBlitz webcontainer. `SassWorkerImplementation` uses `receiveMessageOnPort` Node.js `worker_thread` API to ensure sync behavior which is ~2x faster. However, it is non trivial to support this in a webcontainer and while slower we choose to use `dart-sass` which in Webpack uses the slower async path.
// cc @markwhitfeld
> fix(@angular-devkit/build-angular): Sass compilation in StackBlitz webcontainers

- CHANGELOG.md
> docs: release notes for the v12.2.14 release

- packages/angular_devkit/build_angular/src/builders/browser/specs/lazy-module_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
Previously, we always consumed the ES2020 entrypoints, which caused issues in environments where the application compilation target is ES2019 or lower and ES2020 is not supported.
This is because we only downlevel code when we target ES5 or below.
- ES5 or below compilations, ES2015 entrypoints are used and their code is downlevelled to ES5.
- ES2019 or below, ES2015 entrypoints are used and no downlevelling is involved.
- ES2020 or later, ES2020 entrypoints are used.
Closes #22270
> fix(@angular-devkit/build-angular): prefer ES2015 entrypoints when application targets ES2019 or lower

- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
Use WHATWG URL API instead of the deprecated url utils.
See https://nodejs.org/api/url.html
> refactor(@angular-devkit/build-angular): remove usage of deprecated url methods

- CHANGELOG.md
- package.json
Also this PR cherry-picks the changelog for v13.1.0-rc.0 into the master branch so that the changelog is up to date.
> Update next branch to reflect new release-train "v13.2.0-next.0".

- CHANGELOG.md
Cherry-picks the changelog from the "13.1.x" branch to the next branch (master).
> docs: release notes for the v13.1.0 release

- packages/schematics/angular/utility/latest-versions.ts
New CLI projects are generated with Angular v13 (see https://github.com/cexbrayat/angular-cli-diff/blob/13.1.0/ponyracer/package.json) and TS v4.5 (which is only supported by Angular v13.1).
A new project is currently failing out of the box, as Angular v13 does not support TS 4.5.
```
npx @angular/cli@13.1.0 new v131 --defaults
cd v131
ng serve
```
throws:
```
UnhandledPromiseRejectionWarning: Error: The Angular Compiler requires TypeScript >=4.4.2 and <4.5.0 but 4.5.3 was found instead.
at checkVersion (file:///Users/ced-pro/Code/test/cli-tests/v131/node_modules/@angular/compiler-cli/bundles/index.js:17440:11)
```
Fixes #22333
> fix(@schematics/angular): updated Angular new project version to v13.1.0

- .bazelrc
- BUILD.bazel
- WORKSPACE
- packages/angular/cli/BUILD.bazel
- packages/angular/pwa/BUILD.bazel
- packages/angular_devkit/architect/BUILD.bazel
- packages/angular_devkit/architect_cli/BUILD.bazel
- packages/angular_devkit/benchmark/BUILD.bazel
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_optimizer/BUILD.bazel
- packages/angular_devkit/build_webpack/BUILD.bazel
- packages/angular_devkit/core/BUILD.bazel
- packages/angular_devkit/schematics/BUILD.bazel
- packages/angular_devkit/schematics_cli/BUILD.bazel
- packages/ngtools/webpack/BUILD.bazel
- packages/schematics/angular/BUILD.bazel
- packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
- tools/defaults.bzl
@gregmagolan @josephperrott 
This PR modifies the existing bazel rules to reproduce the packages that are currently being produced by the `build.ts` script. I also added version stamping which works for snapshot and release builds.
There are still some differences between the `package.json` files that bazel produces compared to `build.ts`, which I will work through in future pull requests. These differences include:
* using tars as dependency versions for local builds
* additional substitutions such as removing devDependencies, merging keywords from the base package.json, etc.
Once bazel is producing identical pacakges, I will switch the `build.ts` script to call bazel instead of tsc. Until then, none of this should affect the currently used build process.
> build: reproduce original package structure using bazel

- packages/angular_devkit/core/src/workspace/core.ts
Internally, we've gotten a lot of bugs of users running the CLI in the wrong directory and not understanding this error. Hopefully calling this out more explicitly will key users to double-check their working directory before filing a bug.
> refactor(@angular-devkit/core): update missing workspace file error to explicitly call out `angular.json`

- tests/legacy-cli/e2e/setup/500-create-project.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-es2015.ts
This option causes our CI to be green even when new projects are created with mismatching TypeScript versions, which causes failures in a real-world project.
> test: remove `disableTypeScriptVersionCheck` from tests setup

- docs/process/release.md
In v13.1, we forgot to increment this value and caused an error for early adopters of `13.1.0`. CI should catch this mistake now, and these docs will serve as a reminder to bump the value before release.
/cc @josephperrott FYI, since you're the other release caretaker.
> docs: add `latest-versions.ts` bump to minor/major version release instructions

- package.json
- scripts/build-bazel.ts
@gregmagolan @josephperrott 
This script is the functional equivalent of `build.ts`, but instead invokes the bazel build. Eventually we'll flip this to replace `build.ts`. I tried to preserve the structure, methods, and logging format of the original script as best I could.
> build: add parallel script to build using bazel

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
This fixes an issue were in some cases when importing CSS in the compilation using import syntax caused CSS to be extracted which causes a runtime error.
In general this is not something that we fully support since this is a specific webpack features and importing CSS as if they were ES modules not supported by the browsers. However, certain widely using libraries such as Monaco editor depend on this specific Webpack feature.
Note: This non-standard unsupported behaviour will no longer be possible in the next major version.
Closes #22358
> fix(@angular-devkit/build-angular): only extract CSS styles when are specified in `styles` option

- packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
With this change we enabling Webpack to display additional cache related logs when the `verbose` option is enabled. This is helpful to debug cache misses.
> fix(@angular-devkit/build-angular): display FS cache information when `verbose` option is used

- packages/ngtools/webpack/src/ivy/plugin.ts
With this change we reduce the redundant module rebuilds when Webpack's FS cache is restored.
Previously, when the cache was restored we caused all modules to be rebuild even though their contents didn't change. This is because the file emit history wasn't persisted to disk.
This also caused the side effect that Webpack will create additional cache `pack` files due to the unnecessary module rebuilds, which ultimately causes increase of the size of the cache on disk.
Partially addresses https://github.com/angular/angular-cli/issues/22323#issuecomment-991081570
> perf(@ngtools/webpack): reduce redundant module rebuilds when cache is restored

- CHANGELOG.md
Cherry-picks the changelog from the "13.1.x" branch to the next branch (master).
> docs: release notes for the v13.1.2 release

- CHANGELOG.md
Put the new release notes underneath the latest stable version so users don't think this LTS release is actually the latest.
> docs: release notes for the v11.2.16 release

- CHANGELOG.md
I put this under today's releases to be more clear that this is an LTS release and not the latest stable.
> docs: release notes for the v10.2.4 release

- CHANGELOG.md
Put this right before `11.2.16` but after the latest stable and next releases so users don't think this is the latest and greatest.
Also fixed a `0.0.0` version number that leaked in. `git blame` shows that this came from https://github.com/angular/angular-cli/pull/22387, originally intended as the `10.2.4` release.
> docs: release notes for the v11.2.17 release

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
Currently when using the `:where` CSS pseudo-class in Angular CLI projects,
a warning will be emitted, as `:where` could not be interpreted. Updating
to the latest version of `critters` fixes this issue.
Closes https://github.com/angular/angular-cli/issues/22437
> fix(@angular-devkit/build-angular): enable `:where` CSS pseudo-class

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
This env var only now exists as a workaround for older `postcss-loader` versions that don't support build dependencies. It is not necessary when using postcss-loader >= 5.3. Additionally it does not work with polling. This shows itself when running docker containers on Windows which require angular to poll for changes because filesystem events from volumes are not delivered to the container.
Internally we use postcss dependencies and rely on the build tool running tailwind to track file changes for us. Using `TAILWIND_MODE=watch` sidesteps that entirely and causes tailwind to watch files for changes itself. We only use this as a workaround for when tools aren't behaving properly.
The relevant issue on tailwindcss is here: https://github.com/tailwindlabs/tailwindcss/issues/6343
Relevant …
> Don't set TAILWIND_MODE=watch

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
Currently when creating a new project with `ng new xy --skip-tests`, the `ng g` command will still generate spec files for resolvers.
This PR aims to fix this issue.
> fix(@schematics/angular): set `skipTests` flag for resolvers when using ng new --skip-tests

- .bazelrc
- .prettierignore
- BUILD.bazel
- WORKSPACE
- packages/angular/cli/BUILD.bazel
- packages/angular/pwa/BUILD.bazel
- packages/angular_devkit/architect/BUILD.bazel
- packages/angular_devkit/architect_cli/BUILD.bazel
- packages/angular_devkit/benchmark/BUILD.bazel
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_optimizer/BUILD.bazel
- packages/angular_devkit/build_webpack/BUILD.bazel
- packages/angular_devkit/core/BUILD.bazel
- packages/angular_devkit/schematics/BUILD.bazel
- packages/angular_devkit/schematics_cli/BUILD.bazel
- packages/ngtools/webpack/BUILD.bazel
- packages/schematics/angular/BUILD.bazel
- scripts/build-bazel.ts
- tools/BUILD.bazel
- tools/defaults.bzl
- tools/link_package_json_to_tarballs.bzl
- tools/package_json_release_filter.jq
- tools/test/BUILD.bazel
- tools/test/expected_package.json
- tools/test/project_package.json
- tools/test/root_package.json
@josephperrott @gregmagolan 
This pr mimics the package.json substitutions that build.ts performs. The current build will not be affected by this change as we haven't yet flipped build.ts to use bazel.
> build: perform package.json substitutions in bazel build

- docs/design/analytics.md
`universal-analytics` has been removed via https://github.com/angular/angular-cli/commit/dbce2a3f28673991db1059c902cae326c725518a which makes `DEBUG=universal-analytics` unusable.
> docs: remove old information from debugging section

- packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
See https://github.com/waysact/webpack-subresource-integrity/tree/main/webpack-subresource-integrity#caching and https://github.com/waysact/webpack-subresource-integrity/issues/162 for more information about this.
Closes #22439
> fix(@angular-devkit/build-angular): use `contenthash` instead of `chunkhash` for chunks

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
- packages/angular_devkit/build_angular/src/builders/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/builders/karma/index.ts
- packages/angular_devkit/build_angular/src/builders/ng-packagr/index.ts
- packages/angular_devkit/build_angular/src/builders/server/index.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
- packages/angular_devkit/build_angular/src/utils/normalize-cache.ts
- packages/angular_devkit/build_angular/src/utils/package-version.ts
- packages/angular_devkit/build_angular/src/utils/purge-cache.ts
- packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
- tests/legacy-cli/e2e/tests/build/disk-cache-purge.ts
With every build-angular release, previously created cache entries get stale and are no longer used. This causes the cache to keep growing as older files are not purged.
With this change we automatically purge entries that have been created with older version of build-angular and can no longer be used with the current installed version.
Closes #22323
> fix(@angular-devkit/build-angular): automatically purge stale build cache entries

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
updated webpack-dev-server to latest security patch
webpack-dev-server version 3.11.2 was using ansi-html which is depreciated but in latest version 3.11.3 it's changed to ansi-html-community version 0.0.8 which resolves issue.
closes #22433
> fix(@angular-devkit/build-angular): updated webpack-dev-server to latest minor version

- packages/schematics/update/BUILD.bazel
- packages/schematics/update/README.md
This just points out that the package is deprecated and should no longer be used.
@alan-agius4, I believe this is considered a private package since it's experimental, so I didn't really give much context or justification in the README. Let me know if you think there's anything worth mentioning here.
> docs: add README to `@schematics/update`

- docs/process/release.md
This allows CLI releases to generally be done in parallel with framework and save a lot of time. Major and minor version bumps do require waiting for FW however and that is unchanged.
> docs: clarify that patch/next releases do not require framework to release in advance

- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/tests/behavior/localize_watch_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/tests/behavior/rebuild-errors_spec.ts
- packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts
- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
Previously, we used to delete the temporary emitted JS and map files. However this causes a problem in watch mode, as Webpack will not re-emit these deleted files during the next incremental re-build.
With this change we now delete the entire temporary directory when the process is being terminated instead of a file by file bases.
Closes #22395
> fix(@angular-devkit/build-angular): localized bundle generation fails in watch mode

- packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build_localize_replaced_watch_spec.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/tests/setup.ts
When `translations` is undefined `$localize` calls are not replaced. 
https://github.com/angular/angular-cli/blob/2c9a33dddb38694b6940ec6981c49904de1ab636/packages/angular_devkit/build_angular/src/builders/dev-server/index.ts#L382
Closes #22435
> fix(@angular-devkit/build-angular): ensure `$localize` calls are replaced in watch mode

- package.json
- yarn.lock
Update shelljs dependencies to ^0.8.5 to fix a vulnerability reported to shelljs.
> build: update shelljs dependencies to "^0.8.5"

- CHANGELOG.md
Cherry-picks the changelog from the "13.1.x" branch to the next branch (master).
> docs: release notes for the v13.1.3 release

- CHANGELOG.md
Placed these under the latest and next releases to avoid giving the impression that this is the latest-and-greatest Angular since it is only an LTS release.
> docs: release notes for the v12.2.15 release

- CHANGELOG.md
Inserted underneath today's releases so as not to imply that this LTS release is the latest-and-greatest Angular.
> docs: release notes for the v11.2.18 release

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
When web-workers are enabled we allowing parsing `new URL` syntax which has the side-effect that Webpack will treat all assets as asset modules (https://webpack.js.org/guides/asset-modules/#url-assets). With this change we remove this inconsistency by disabling the `url` parsing which doesn't effect `new Worker(new URL(...))`.
> fix(@angular-devkit/build-angular): disable parsing `new URL` syntax

- .circleci/config.yml
Node v10 is no longer supported by the Node.js team and it is difficult to keep CI green when the NPM infrastructure underneath the CLI is no longer expected to maintain Node v10 support.
I noticed that we still have this job running in Angular v11 and it has consistently failed for some time.
> ci: remove Node v10

- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
…
Previously, when ESNext was used, we fallbacked to ES2020 which caused ESBuild to output broken code.
Closes #22486
> fix(@angular-devkit/build-angular): support ESNext as target for JavaScript optimizations

- packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts
With this change we exit the function early, when there are no budgets defined.
> refactor(@angular-devkit/build-angular): exit early when there are no component style budgets

- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
`next` releases are currently for 13.2.0, so this is necessary to avoid peer dep warnings.
> build: bump Angular peer deps to 13.2.0-next

- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
Currently when making a change while serving a localized application, duplicate
translation warnings appear for every translation id. This fixes that by
replacing the whole translation object with a new one each time translations
are loaded.
fixes #22398
Minor version of https://github.com/angular/angular-cli/pull/22460
> fix(@angular-devkit/build-angular): load translations fresh start

- CHANGELOG.md
Cherry-picks the changelog from the "13.1.x" branch to the next branch (master).
> docs: release notes for the v13.1.4 release

- CHANGELOG.md
- package.json
Also this PR cherry-picks the changelog for v13.2.0-rc.0 into the master branch so that the changelog is up to date.
> Update next branch to reflect new release-train "v13.3.0-next.0".

- .bazelrc
- .monorepo.json
- BUILD.bazel
- constants.bzl
- packages/angular/cli/package.json
- packages/angular_devkit/architect/package.json
- packages/angular_devkit/architect_cli/package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/build_webpack/package.json
- scripts/build.ts
- scripts/validate-licenses.ts
- tools/defaults.bzl
- tools/snapshot_repo_filter.bzl
@josephperrott @devversion  @gregmagolan
The first commit performs stamping for experimental packages which get a different version format (e.g., `0.1302.0-next.1` vs `13.2.0-next.1`). Basically any package with `"experimental": true` gets the alternative placeholder. If it becomes non-experimental then the version placeholder should also change. The two should be manually kept in sync.
The second commit performs substitutions for github snapshot repos in a snapshot build similar to the non-bazel snapshot build, so it stamps versions like `github:angular/angular-devkit-architect-builds:174fe1056a9ca4987c9176f5f2d18faf0e71c92b`.
> build: experimental stamping and snapshot repo substitutions

- CHANGELOG.md
> docs: release notes for the v13.2.0-rc.1 release

- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
This will allow `13.2.0-rc` CLI packages like `@angular-devkit/build-angular` to depend on RC versions of FW packages like `@angular/compiler-cli`. As it stands, `next` releases are allowed, but `rc` aren't, which makes prerelease testing more difficult than it needs to be.
Related: https://github.com/angular/angular-cli/commit/4de2eb54f82c676b94f352f694ffa7268ce98d0d
> build: add RC releases to framework peer deps

- packages/angular_devkit/schematics/README.md
Add '\' prefix so character code is rendered literally,
not as the character it represents.
> docs: fix character code in expression example

- CHANGELOG.md
- package.json
- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/utility/latest-versions.ts
NOTE: This is a non-standard release since it is a minor. This PR includes manual edits to `latest-versions.ts` and peer deps on the framework to drop prerelease tags and bump the versions to `13.2.0` where appropriate.
> Bump version to "v13.2.0" with changelog.

- CHANGELOG.md
> docs: release notes for the v13.2.0 release

- goldens/public-api/ngtools/webpack/src/index.md
- packages/ngtools/webpack/src/index.ts
`ivy` namespace has been removed from the public API.
- `ivy.AngularWebpackPlugin` -> `AngularWebpackPlugin`
- `ivy.AngularPluginOptions` -> `AngularPluginOptions`
> refactor(@ngtools/webpack) remove deprecated ivy namespace

- docs/specifications/update.md
- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/commands/update.json
- packages/angular/cli/src/commands/update/schematic/index.ts
`--all` option from `ng update` has been removed without replacement. To update packages which don’t provide `ng  update` capabilities in your workspace `package.json` use `npm update`, `yarn upgrade-interactive` or `yarn upgrade` instead.
> refactor(@angular/cli): remove deprecated `--all` option from `ng update`

- packages/angular_devkit/build_angular/src/builders/browser/tests/behavior/styles_unsupported_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/tests/options/allowed-common-js-dependencies_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
BREAKING CHANGE:  
We now issue a build time error since importing a CSS file as an ECMA module is non standard Webpack specific feature, which is not supported by the Angular CLI.
This feature was never truly supported by the Angular CLI, but has as such for visibility.
> fix(@angular-devkit/build-angular): fail build when importing CSS files as an ECMA modules

- packages/angular_devkit/build_angular/src/builders/browser/specs/allow-js_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/lazy-module_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/resolve-json-module_spec.ts
- packages/angular_devkit/build_angular/test/hello-world-app/tsconfig.json
- packages/angular_devkit/build_angular/test/hello-world-lib/tsconfig.json
- packages/angular_devkit/build_webpack/test/angular-app/tsconfig.json
- packages/angular_devkit/build_webpack/test/basic-app/tsconfig.json
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-14/update-tsconfig-target.ts
- packages/schematics/angular/migrations/update-14/update-tsconfig-target_spec.ts
- packages/schematics/angular/workspace/files/tsconfig.json.template
- tests/legacy-cli/e2e/tests/build/prod-build.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-es2015.ts
With this change we update the TypeScript compilation target to `ES2020` for both new and existing projects. This is because all browsers that Angular supports (https://angular.io/guide/browser-support) support `ES2020` features without the need for polyfills.
> feat(@schematics/angular): update new and existing projects compilation target to `ES2020`

- packages/angular/cli/commands/definitions.json
- packages/angular/cli/models/architect-command.ts
- tests/legacy-cli/e2e/assets/9.0-project/README.md
- tests/legacy-cli/e2e/tests/build/lazy-load-syntax.ts
- tests/legacy-cli/e2e/tests/build/material.ts
- tests/legacy-cli/e2e/tests/build/rebuild-replacements.ts
- tests/legacy-cli/e2e/tests/misc/third-party-decorators.ts
- tests/legacy-cli/e2e/tests/test/test-environment.ts
- tests/legacy-cli/e2e/tests/update/update-9.ts
Deprecated option `--prod` has been removed from all builders. `--configuration production`/`-c production` should be used instead if the default configuration of the builder is not configured to `production`.
> refactor(@angular/cli): remove deprecated `--prod` flag

- goldens/public-api/angular_devkit/schematics/src/index.md
- goldens/public-api/angular_devkit/schematics/testing/index.md
- goldens/public-api/angular_devkit/schematics/tools/index.md
- packages/angular_devkit/schematics/src/engine/interface.ts
Deprecated `analytics` property has been removed from `TypedSchematicContext` interface
> refactor(@angular-devkit/schematics): remove deprecated `analytics` property

- packages/angular_devkit/build_angular/src/webpack/plugins/css-optimizer-plugin.ts
This change addresses the `Invalid version: "15.2-15.3"` range error. We previously only handled version ranges for `ios_safari`. Now, we handle such versions for all browsers.
Closes #22606
> fix(@angular-devkit/build-angular): invalid browsers version ranges

- CHANGELOG.md
> docs: release notes for the v13.2.1 release

- goldens/public-api/angular_devkit/build_angular/src/index.md
- packages/angular_devkit/build_angular/src/builders/browser/schema.json
- packages/angular_devkit/build_angular/src/builders/karma/schema.json
- packages/angular_devkit/build_angular/src/index.ts
- packages/angular_devkit/build_angular/src/utils/build-options.ts
- packages/angular_devkit/build_angular/src/utils/package-chunk-sort.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
In some cases unexpected files may be provided which can cause to unsupported or broken behaviour.
One such use-case is users can provide TypeScript files as `scripts` input, this would not be processed by the TypeScript compiler, see: https://github.com/angular/angular-cli/issues/17125 and would cause the build to fail with a an unhelpful error message during optimization as the JS optimizers cannot parse TypeScript input.
Browser builder `script` and `styles` options input files extensions are now validated.
Valid extensions for `scripts` are:
- `.js`
- `.cjs`
- `.mjs`
- `.jsx`
- `.cjsx`
- `.mjsx`
Valid extensions for `styles` are:
- `.css`
- `.less`
- `.sass`
- `.scss`
- `.styl`
> feat(@angular-devkit/build-angular): validate file extensions for `scripts` and `styles` options

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
Changes that improve performance:
- use resolve data already present in most modules
- use throwIfNoEntry option on filesystem operations to improve performance
> perf(@angular-devkit/build-angular): update `license-webpack-plugin` to `4.0.1`

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Similar to https://github.com/angular/angular-cli/pull/21739, `whatwg-url` seems to suffer from the same issue as https://github.com/angular/angular-cli/issues/21735
```ts
const AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf(async function* () {}).prototype);
```
> fix(@angular-devkit/build-angular): add `whatwg-url` to downlevel exclusion list

- packages/angular_devkit/build_angular/src/utils/build-options.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
> Patch version of #22612

- packages/angular_devkit/build_angular/src/utils/build-options.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
Previously we used hash which resulted in a unique hash generated for every build even when the contents of the files didn't differ.
More info: https://webpack.js.org/guides/caching/#output-filenames
NB: I did try to add a unit test, but it non trivial.
> fix(@angular-devkit/build-angular): ensure to use content hash as filenames hashing mechanism

- .circleci/config.yml
- lib/packages.ts
- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- scripts/snapshots.ts
- tools/defaults.bzl
- tools/snapshot_repo_filter.bzl
- yarn.lock
@gregmagolan @josephperrott 
Here are the snapshot repo diffs caused by flipping to the bazel build.
| Snapshot repo  | Diff |
| ------------- | ------------- |
| @angular/cli  | [diff](https://github.com/angular/cli-builds/compare/master...snapshot-test)  |
| @angular/pwa  | [diff](https://github.com/angular/angular-pwa-builds/compare/master...snapshot-test)  |
| @angular-devkit/architect | [diff](https://github.com/angular/angular-devkit-architect-builds/compare/master...snapshot-test)  |
| @angular-devkit/architect-cli | [diff](https://github.com/angular/angular-devkit-architect-cli-builds/compare/master...snapshot-test)  |
| @angular-devkit/build-angular | [diff](https://github.com/angular/angular-devkit-build-angular-builds/compare/master...snapshot-test)  |
| …
> build: use bazel for snapshot builds

- CHANGELOG.md
> docs: release notes for the v13.2.2 release

- CONTRIBUTING.md
- packages/angular/cli/commands/config-impl.ts
- packages/angular/cli/models/architect-command.ts
- packages/angular/cli/utilities/config.ts
- packages/angular/cli/utilities/package-manager.ts
- packages/angular/cli/utilities/project.ts
- packages/angular_devkit/build_angular/test/hello-world-app/src/environments/environment.ts
- scripts/templates/contributing.ejs
**refactor(@angular/cli): remove support for legacy Angular CLI version 1 configurations**
Remove references to legacy Angular CLI version 1 configurations. By now users should have been migrated to use the new configuration.
**feat(@angular/cli): use PNPM as package manager when pnpm-lock.yaml exists**
While supported, we didn't automatically try to determine if PNPM was used through the lock files like we do for other package managers.
> Use PNPM as package manager when `pnpm-lock.yaml` exists

- packages/ngtools/webpack/src/ngcc_processor.ts
Previously, we only handled Yarn and NPM lock files even though PNPM is supported as package manager.
The lock file is used to perform checks to determine if an initial execution of NGCC was already performed.
Closes #22632
> fix(@ngtools/webpack): support locating PNPM lock file during NGCC processing

- renovate.json
With this change we group all the scorecard action dependencies so that Renovate opens a single PR.
> ci: group all scorecard action dependencies

- WORKSPACE
Add a missing toolchain that was causing the nodejs_binary target for ng_cli_schema to fail on windows. I encountered this while trying to flip the ci to build with bazel.
Caused this error: https://app.circleci.com/pipelines/github/angular/angular-cli/20529/workflows/7f1860fe-0296-49d0-8466-6b23d9347ff8/jobs/287310?invite=true#step-112-31
> build: fix bazel build on windows

- packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts
This change is inspired by https://github.com/karma-runner/karma-chrome-launcher/issues/154#issuecomment-986661937 which blocks Karma from launching the browsers until the compilation is complete.
This is needed especially for large applications when using code-coverage where otherwise the users would have to fine-tune several Karma timeouts such as  `captureTimeout` for various environments.
Closes #22495
> fix(@angular-devkit/build-angular): block Karma from starting until build is complete

- CHANGELOG.md
> docs: release notes for the v13.2.3 release

- packages/angular/cli/commands/extract-i18n-impl.ts
- packages/angular/cli/commands/extract-i18n.json
Deprecated `ng x18n` and `ng i18n-extract` commands have been removed in favor of `ng extract-i18n`.
> refactor(@angular/cli): remove deprecated command aliases for `extract-i18n`.

- .github/workflows/dev-infra.yml
- .github/workflows/feature-requests.yml
- .github/workflows/lock-closed.yml
- .github/workflows/scorecard.yml
The currently recommended best practice for Github action workflows is to set top-level permissions to read only. And if the job uses the automatic `GITHUB_TOKEN`, fine-grained permissions for each job based on the job's requirements should also be added.
All existing workflows in the repository now have top-level read only permission blocks.
Only the `scorecard` workflow currently requires additional job level permissions and the minimum set of permissions were already present for the job.
> build: add permissions to current github action workflows

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
7.17.3 is breaking vendor sourcemaps in windows.
See: https://app.circleci.com/pipelines/github/angular/angular-cli/20692/workflows/9fc4f39e-d2f2-47c3-af01-f3a01c1bf542/jobs/288690
Related to https://github.com/babel/babel/issues/14277
> build: revert to @babel/core version 7.17.2 

- CHANGELOG.md
> docs: release notes for the v13.2.4 release

- tests/legacy-cli/e2e/tests/build/prod-build.ts
Improvements to the framework for `14.0.0-next.3` resulted in reduced main bundle sizes.
```
Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
main.f6e8bb94b78b0b43.js      | main          | 120.24 kB |                36.23 kB
```
> test: update E2E production application size expectations

- tests/legacy-cli/e2e/ng-snapshot/package.json
Updates the snapshot e2e setup to reflect the builds repository rename
where `material2-builds` got renamed to `material-builds`.
> build: update snapshot e2e setup to reflect builds repository rename

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
This brings in a fix for RegExp with unicode.
See: https://github.com/terser/terser/blob/master/CHANGELOG.md#v5110
> fix(@angular-devkit/build-angular): update `terser` to `5.11.0`

- packages/angular_devkit/build_angular/src/webpack/plugins/named-chunks-plugin.ts
When using the unsupported `webpackChunkName` magic comment we renamed the chunk which in some cases causes a runtime error.
Closes #22525
> fix(@angular-devkit/build-angular): don't rename blocks which have a name

- .github/workflows/dev-infra.yml
- .github/workflows/scorecard.yml
Renovate supports use hashed version pinning for individual Github actions while still following SemVer-based tags.
All workflow actions external to the Angular organization now leverage this support to ensure both that stable versions of the actions are used and that the actions are pinned to a hashed version of the tag.
> ci: use renovate Github Action tag version pinning

- tests/legacy-cli/e2e/ng-snapshot/package.json
Updates the snapshot e2e setup to reflect the builds repository rename
where `material2-builds` got renamed to `material-builds`.
> [13.2.x] build: update snapshot e2e setup to reflect builds repository rename

- CHANGELOG.md
> docs: release notes for the v13.2.5 release

- packages/angular_devkit/core/src/utils/strings.ts
Typo in underscore function code documentation.
> docs(@angular-devkit/core): typo in string.ts docs

- packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/normalize-builder-schema.ts
- packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts
During the build initialization phase, many paths are converted back and forth between multiple normalized forms. These conversions involve potentially expensive string operations. The majority of the custom path `resolve` function from `@angular-devkit/core` usages have now been removed in favor of the Node.js builtin path functions. This change reduces the need to perform additional string manipulation where possible.
> refactor(@angular-devkit/build-angular): replace most custom path `resolve` usages with Node.js builtins

- goldens/public-api/angular_devkit/build_angular/src/index.md
- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
- packages/angular_devkit/build_angular/src/builders/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/builders/protractor/index.ts
- packages/angular_devkit/build_angular/src/builders/server/index.ts
The use of the `@angular-devkit/core` `JsonObject` type is no longer needed to satisfy the type requirements of `@angular-devkit/architect` package builder creation functions.
> refactor(@angular-devkit/build-angular): remove unneeded JsonObject type casting

- .circleci/config.yml
Node.js v12 will become EOL on 2022-04-30. As a result, Angular as of v14 will no longer support Node.js v12.
> ci: remove Node.js v12 E2E job

- packages/angular_devkit/build_angular/src/webpack/plugins/named-chunks-plugin.ts
Don't name CSS only chunks.
Closes #22769
> fix(@angular-devkit/build-angular): ignore css only chunks during naming

- scripts/json-help.ts
- scripts/snapshots.ts
Previoiusly we generated the JSON help files prior to building which caused the `help` directory in the `dist` to be deleted.
> build: fix order of JSON help generation

- packages/angular/cli/src/command-builder/command-module.ts
Needed for consistency that will fix a Windows CI failure
> refactor(@angular/cli): always use posix separator in `longDescriptionRelativePath`

- CHANGELOG.md
> docs: release notes for the v13.2.6 release

- packages/angular/cli/src/command-builder/command-module.ts
Needed to fix Windows CI.
Successful run: https://app.circleci.com/pipelines/github/angular/angular-cli/21152/workflows/06f9c9c2-ae91-454d-939e-ee50b7919cee/jobs/292323/parallel-runs/0?filterBy=ALL
> refactor(@angular/cli): replace `longDescription` line endings with `\n`

- packages/angular/cli/src/commands/update/cli.ts
The long-description.md was not referenced in `UpdateCommandModule`.
> fix(@angular/cli): add long description to `ng update`

- packages/angular/cli/src/command-builder/command-module.ts
This addresses the issue  when trying to disable analytics the prompt will be shown
```
ng analytics off
Would you like to share anonymous usage data about this project with the Angular Team at Google under Google’s Privacy Policy at https://policies.google.com/privacy? For more details and how to change this setting, see http://angular.io/analytics. (y/N)
```
Closes #16784
> fix(@angular/cli): don't prompt for analytics when running `ng analytics`

- packages/angular/cli/src/command-builder/architect-command-module.ts
- tests/legacy-cli/e2e/tests/commands/builder-project-by-cwd.ts
When running architect command such as `ng build`, `ng test`, `ng lint`... and no project is provided as a positional argument. The project in the current working directory is favoured instead of the configured as default project.
> fix(@angular/cli): favor project in cwd when running architect commands 

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/build_webpack/package.json
- packages/ngtools/webpack/package.json
- yarn.lock
This brings a couple of fixes to HMR, one of which is double reloaded.
See: https://github.com/webpack/webpack/releases/tag/v5.70.0
Closes #22839
> build: update webpack to 5.70.0

- packages/angular_devkit/build_angular/src/utils/environment-options.ts
- packages/angular_devkit/build_angular/src/utils/normalize-cache.ts
`NG_BUILD_CACHE` environment variable has been removed. `cli.cache` in the workspace configuration should be used instead.
> refactor(@angular-devkit/build-angular): remove deprecated `NG_BUILD_CACHE` environment variable

- docs/design/analytics.md
- packages/angular/cli/bin/postinstall/analytics-prompt.js
- packages/angular/cli/src/analytics/analytics-environment-options.ts
- packages/angular/cli/src/analytics/analytics.ts
- packages/angular/cli/src/command-builder/command-module.ts
- packages/angular/cli/src/command-builder/command-runner.ts
- packages/angular/cli/src/command-builder/utilities/command.ts
- packages/angular/cli/src/commands/analytics/cli.ts
- packages/angular/cli/src/commands/analytics/info/cli.ts
- packages/angular/cli/src/commands/analytics/long-description.md
- packages/angular/cli/src/commands/analytics/settings/cli.ts
- tests/legacy-cli/e2e/tests/commands/help/help-json.ts
- tests/legacy-cli/e2e/tests/misc/ask-analytics-command.ts
With this change we add a `--global` option to `ng analytics` command.
Several changes to the `ng analytics` command syntax.
- `ng analytics project <setting>` has been replaced with `ng analytics <setting>`
- `ng analytics <setting>` has been replaced with `ng analytics <setting> --global`
---
feat(@angular/cli): add `ng analytics info` command
With this change we add a subcommand to `ng analytics`. This command can be used tp display analytics gathering and reporting configuration.
Example:
```
$ ng analytics info                              
Global setting: off
Local setting: on
Effective status: disabled
```
> feat(@angular/cli): add `--global` option to `ng analytics` command

- packages/schematics/angular/e2e/index.ts
- packages/schematics/angular/universal/index.ts
- packages/schematics/angular/workspace/files/package.json.template
The `@types/node` package is now only added if E2E tests (`ng generate e2e`) or universal are added to a project.
> fix(@schematics/angular): remove `@types/node` from new projects

- packages/angular/cli/bin/postinstall/analytics-prompt.js
- packages/angular/cli/src/analytics/analytics.ts
With this change we clean up further the analytics code and re-use the `getAnalytics` to determine if the config is set or not.
Also, this change inclused a refactor to the `createAnalytics` method to make it more readable.
> refactor(@angular/cli): remove `hasAnalyticsConfig` analytics logic

- CHANGELOG.md
Cherry-picks the changelog from the "13.3.x" branch to the next branch (master).
> docs: release notes for the v13.3.0 release

- packages/angular/cli/src/commands/config/cli.ts
- tests/legacy-cli/e2e/tests/commands/config/config-get.ts
- tests/legacy-cli/e2e/tests/commands/help/help-json.ts
This fixes a regression were when no positional args are provided to `ng config` the entire config file should to be printed in the console.
> fix(@angular/cli): print entire config when no positional args are provided to `ng config`

- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.spec.ts.template
Since f463c8403547 we use native `async`/`await` and thus we do not need
to split setup in two `beforeEach()`
This would avoid confusion for newcomers as seen in https://stackoverflow.com/questions/52170948/why-component-generated-by-ng-cli-has-the-spec-file-with-2-beforeeach-method
> fix(@schematics/angular): Consolidated setup with a single `beforeEach()`

- lib/bootstrap-local.js
- lib/packages.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/postcss-cli-resources.ts
- packages/angular_devkit/core/src/json/parser.ts
- packages/angular_devkit/core/src/utils/strings.ts
- packages/angular_devkit/core/src/virtual-fs/path.ts
- packages/angular_devkit/core/src/workspace/json/utilities.ts
- packages/angular_devkit/schematics/src/rules/move.ts
- packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
- packages/angular_devkit/schematics_cli/bin/schematics.ts
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/ng-new/index.ts
- scripts/build.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> refactor: replace deprecated String.prototype.substr()

- packages/angular/cli/lib/config/workspace-schema.json
- packages/angular/cli/src/command-builder/architect-command-module.ts
- packages/angular/cli/src/command-builder/schematics-command-module.ts
- packages/angular/cli/src/commands/add/long-description.md
- packages/angular/cli/src/utilities/config.ts
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/index_spec.ts
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-14/remove-default-project-option.ts
- packages/schematics/angular/migrations/update-14/remove-default-project-option_spec.ts
- tests/legacy-cli/e2e/tests/misc/multiple-targets.ts
**feat(@schematics/angular): add migratiom to remove `defaultProject` in workspace config**
This option is deprecated in Angular CLI and will be removed in a future major version.
**refactor(@schematics/angular): remove usage of deprecated `defaultProject`**
This option is deprecated in Angular CLI and will be removed in a future major version.
**feat(@angular/cli): deprecated `defaultProject` option**
With this change we deprecate the angular.json `defaultProject` option.
DEPRECATED:
The `defaultProject` workspace option has been deprecated. The project to use will be determined from the current working directory.
Closes #22852
> Deprecate defaultProject

- package.json
- packages/angular_devkit/architect_cli/package.json
- packages/angular_devkit/benchmark/package.json
- packages/angular_devkit/schematics_cli/package.json
- yarn.lock
Closes https://github.com/angular/angular-cli/issues/22872
> build: update `minimist` to `1.2.6`

- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
Updates the peer dependency to reflect the TS 4.6 support, avoiding
warnings like:
```
warning "@angular-devkit/build-angular > @ngtools/webpack@14.0.0-next.6" has incorrect peer dependency "typescript@>=4.4.3 <4.6".
```
TS 4.4 and 4.5 have been removed in https://github.com/angular/angular-cli/commit/7fa3e6587955d0638929758d3c257392c242c796
> fix(@ngtools/webpack): update peer dependency to reflect TS 4.6 support

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_webpack/test/angular-app/src/polyfills.ts
- tests/legacy-cli/e2e/assets/webpack/test-app/app/main.ts
- tests/legacy-cli/e2e/assets/webpack/test-app/package.json
- tests/legacy-cli/e2e/tests/build/polyfills.ts
- tests/legacy-cli/e2e/tests/misc/minimal-config.ts
Since Angular 8, the CLI has transformed decorator metadata to a form that can be used by the Angular dependency injector without the TDZ limitations of Typescript's decorator metadata emit feature.
As a result, a JIT application compiled with the CLI no longer requires the reflect metadata polyfill that was provided by `core-js`.
This polyfill was also the last remaining usage of the `core-js` package within `@angular-devkit/build-angular` which allows the `core-js` package to also be removed.
Refs: https://github.com/angular/angular-cli/pull/14473 & https://github.com/angular/angular/pull/37382
BREAKING CHANGE: Reflect metadata polyfill is no longer automatically provided in JIT mode
Reflect metadata support is not required by Angular in JIT applications compiled by the CLI. …
> fix(@angular-devkit/build-angular): remove unneeded JIT reflect metadata polyfill

- docs/design/analytics.md
- goldens/public-api/angular_devkit/core/src/index.md
- packages/angular/cli/src/analytics/analytics-collector.ts
- packages/angular_devkit/build_angular/src/webpack/configs/analytics.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/analytics.ts
- packages/angular_devkit/core/src/analytics/index.ts
With this change we replace the custom dimension 8 `AOT Enabled`, with `Angular CLI Major Version`. The motivation behind replacing this dimension is that the there is already an `aot` dimension with id 13 which serves for the same purpose.
More information to why we need a new dimension for the Angular CLI major version can be found #22130
Closes #22130
> fix(@angular-devkit/core): add Angular CLI major version as analytics dimension

- packages/angular_devkit/build_angular/src/typings.d.ts
This package now ships TypeScript declaration files.
> refactor(@angular-devkit/build-angular): remove types for `@discoveryjs/json-ext`

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
This is no longer needed as Stackblitz implemented the missing Node.Js worker APIs.//cc @d3lm from StackBlitz.
> fix(@angular-devkit/build-angular): allow Workers in Stackblitz

- packages/angular_devkit/build_angular/src/webpack/plugins/css-optimizer-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/transfer-size-plugin.ts
Currently, we are overriding asset info instead of appending additional data to it.
> fix(@angular-devkit/build-angular): don't override asset info when updating assets

- goldens/public-api/angular_devkit/core/index.md
- packages/angular_devkit/core/src/exception.ts
- packages/angular_devkit/core/src/exception/index.ts
- packages/angular_devkit/core/src/experimental/jobs/create-job-handler.ts
- packages/angular_devkit/core/src/experimental/jobs/exception.ts
- packages/angular_devkit/core/src/index.ts
- packages/angular_devkit/core/src/json/schema/registry.ts
With this change we deprecate exception classes that are not used in the CLI repo.
DEPRECATED:
- `ContentHasMutatedException`, `InvalidUpdateRecordException`, `UnimplementedException` and `MergeConflictException` symbol from `@angular-devkit/core` have been deprecated in favor of the  symbol from `@angular-devkit/schematics`.
- `UnsupportedPlatformException` - A custom error exception should be created instead.
> refactor(@angular-devkit/core): deprecate unused exception classes

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Without the `node_modules` prefix, projects named the same as the excluded package names ex: `webpack` will not compile successfully as all files under the mentioned project will be excluded from being requested by the respective loaders.
Closes #22902
> fix(@angular-devkit/build-angular): add `node_modules` prefix to excludes RegExp

- packages/angular/cli/src/commands/update/cli.ts
This also aligns the output to have the same style of `ng add`
> fix(@angular/cli): display package manager during `ng update`

- CHANGELOG.md
Cherry-picks the changelog from the "13.3.x" branch to the next branch (master).
> docs: release notes for the v13.3.1 release

- packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/karma/index.ts
- packages/angular_devkit/build_angular/src/utils/normalize-asset-patterns.ts
- packages/angular_devkit/build_angular/src/utils/normalize-builder-schema.ts
- packages/angular_devkit/build_angular/src/utils/normalize-file-replacements.ts
- packages/angular_devkit/build_angular/src/utils/service-worker.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/typescript.ts
During the build initialization phase, many paths are converted back and forth between multiple normalized forms. These conversions involve potentially expensive string operations. The majority of the custom path `normalize` function from `@angular-devkit/core` usages have now been removed in favor of the Node.js builtin path functions. This change reduces the need to perform additional string manipulation where possible.
> refactor(@angular-devkit/build-angular): replace most custom path normalize usage with Node.js builtins

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
It seems that in the last dev dependencies update the version of minimatch has been updated in one place and omitted in the other.
> Minimatch v3.0.5 for branch 13.3.x

- packages/angular/cli/src/command-builder/architect-command-module.ts
- packages/angular/cli/src/command-builder/command-module.ts
- packages/angular/cli/src/command-builder/schematics-command-module.ts
- packages/angular/cli/src/commands/new/cli.ts
- packages/angular/cli/src/utilities/memoize.ts
- packages/angular/cli/src/utilities/memoize_spec.ts
- packages/angular/cli/src/utilities/package-manager.ts
- tsconfig.json
With this change we clean up repeated caching code by creating a `memoize` decorator that can be used on get accessors and methods.
> refactor(@angular/cli): create a `memoize` decorator

- packages/angular/cli/commands/lint-impl.ts
When no lint target is present for a project, the command will ask if linting should be added to the project.
However, after adding the package, the command incorrectly kept executing and then failing due to the lint command not being fully setup yet.
Instead, the command will now exit after adding the linting package. This also allows inspection and/or adjustment of the linting configuration prior to actually linting.
Fixes: #22937
> fix(@angular/cli): ensure lint command auto-add exits after completion

- packages/angular_devkit/core/src/json/parser.ts
- packages/angular_devkit/core/src/json/parser_spec.ts
`parseJson` and `ParseJsonOptions` APIs have been removed in favor of 3rd party JSON parsers such as `jsonc-parser`.
> refactor(@angular-devkit/core): remove deprecated `parseJson` and `ParseJsonOptions` APIs

- goldens/public-api/angular_devkit/schematics/tools/index.md
- packages/angular/cli/src/command-builder/utilities/schematic-engine-host.ts
- packages/angular_devkit/schematics/tools/description.ts
- packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
- packages/angular_devkit/schematics/tools/node-module-engine-host.ts
Infrastructure has been added to the schematics runtime within the `@angular/cli`
package to allow schematics executed via the Angular CLI to have access upcoming
built-in modules. These built-in modules will be imported/required using the
`schematics:` scheme similar to the Node.js `node:` scheme available for Node.js
built-in modules. No built-in modules exist yet but will be added in the future.
Schematics must be executed via the Angular CLI Schematics runtime's custom VM context
to use the upcoming built-in modules. All first-party Angular schematics have been
executed in this manner for several major versions. Third-party schematics can now
opt-in to the behavior by enabling the `encapsulation` option within a schematic collection
JSON file.
> refactor(@angular/cli): add infrastructure support for schematics built-in modules

- packages/angular/cli/src/analytics/analytics.ts
- packages/angular/cli/src/commands/analytics/settings/cli.ts
- packages/angular/cli/src/commands/cache/settings/cli.ts
- packages/angular/cli/src/commands/cache/utilities.ts
- packages/angular/cli/src/utilities/config.ts
This changes removes most of the usage of `getWorkspaceRaw` in the Angular CLI. This is needed to eventually drop the direct dependency on `jsonc-parser`.
> refactor(@angular/cli): remove most of `getWorkspaceRaw` usages

- packages/angular/cli/src/command-builder/architect-base-command-module.ts
- packages/angular/cli/src/command-builder/architect-command-module.ts
- packages/angular/cli/src/command-builder/command-module.ts
- packages/angular/cli/src/command-builder/command-runner.ts
- packages/angular/cli/src/commands/completion/cli.ts
- packages/angular/cli/src/commands/completion/long-description.md
- packages/angular/cli/src/commands/run/cli.ts
- tests/legacy-cli/e2e/tests/misc/browsers.ts
- tests/legacy-cli/e2e/tests/misc/completion.ts
To enable bash and zsh real-time type-ahead autocompletion, copy and paste the generated script by the `ng completion` command to your `.bashrc`, `.bash_profile`, `.zshrc` or `.zsh_profile`.
Closes #11043
> feat(@angular/cli): add support for auto completion

- packages/angular/cli/src/commands/config/cli.ts
`cli.cache` cannot be configured globally and therefore it should not be listed as part of the `validCliPaths` Map.
> fix(@angular/cli): remove cache path from global valid paths

- .circleci/config.yml
- packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts
The `glob`-based check when adding the sourcemap support packages to the karma setup was incorrectly
skipping the files due to Windows pathing issues. The `glob`-based check, however, is unneeded due
to the already present `require.resolve` checks for the sourcemap support packages which will
throw if the packages are not present.
> fix(@angular-devkit/build-angular): ensure karma sourcemap support on Windows

- CHANGELOG.md
- package.json
Due to an issue in releasing the next.10 package to npm re-releasing it as next.11
> release: cut the v14.0.0-next.11 release

- .circleci/config.yml
- packages/angular_devkit/build_angular/builders.json
- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/esbuild.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- tests/legacy-cli/e2e/setup/500-create-project.ts
- tests/legacy-cli/e2e/tests/basic/build.ts
- tests/legacy-cli/e2e/tests/basic/styles-array.ts
- tests/legacy-cli/e2e/tests/build/prod-build.ts
- tests/legacy-cli/e2e_runner.ts
An experimental browser application builder (`browser-esbuild`) has been introduced that leverages esbuild as the bundler.
This new builder is compatible with options of the current browser application builder (`browser`) and can be enabled
for experimentation purposes by replacing the `builder` field of `@angular-devkit/build-angular:browser` from an existing
project to `@angular-devkit/build-angular:browser-esbuild`. The builder will generate an ESM-based application and provides support for ES2015+ compatible output with ES2020 as the default.
This builder is considered experimental and is not recommended for production applications.
Currently not all `browser` builder options and capabilities are supported with this experimental builder. Additional support for these options may be …
> feat(@angular-devkit/build-angular): add initial experimental esbuild-based application browser builder

- packages/ngtools/webpack/package.json
- packages/ngtools/webpack/src/ivy/plugin.ts
- packages/ngtools/webpack/src/resource_loader.ts
Webpack provides built-in support for creating hashes using the xxhash64 algorithm via a WebAssembly module.
This can be significantly faster than the previously used md5 algorithm and is currently used as the output hashing algorithm  within the Webpack configuration.
The Webpack peer dependency has also been update to a minimum of 5.54.0 to ensure xxhash64 supported is available.
> perf(@ngtools/webpack): use Webpack's built-in xxhash64 support

- goldens/public-api/angular_devkit/schematics/index.md
- goldens/public-api/angular_devkit/schematics/testing/index.md
- goldens/public-api/angular_devkit/schematics/tools/index.md
- packages/angular_devkit/schematics/BUILD.bazel
- packages/angular_devkit/schematics/src/tree/delegate.ts
- packages/angular_devkit/schematics/src/tree/host-tree.ts
- packages/angular_devkit/schematics/src/tree/host-tree_spec.ts
- packages/angular_devkit/schematics/src/tree/interface.ts
- packages/angular_devkit/schematics/src/tree/null.ts
- packages/angular_devkit/schematics/src/tree/scoped.ts
- packages/angular_devkit/schematics_cli/blank/factory.ts
- packages/schematics/angular/app-shell/index.ts
- packages/schematics/angular/component/index.ts
- packages/schematics/angular/directive/index.ts
- packages/schematics/angular/module/index.ts
- packages/schematics/angular/pipe/index.ts
- packages/schematics/angular/service-worker/index.ts
- packages/schematics/angular/universal/index.ts
- packages/schematics/angular/utility/json-file.ts
- packages/schematics/angular/utility/ng-ast-utils.ts
- packages/schematics/angular/utility/workspace.ts
- packages/schematics/angular/web-worker/index.ts
The schematics `Tree` now contains an additional `readText` method that supports directly
reading the content of a file as UTF-8 text. This avoids the need to manually decode a Buffer
within a schematic when text content is needed. If a file path does not exist, an exception
will be thrown. While this differs from the semantics of `read`, it helps reduce the amount
of code needed for common schematic use cases.
The schematics `Tree` now contains an additional `readJSON` method that supports directly
reading and parsing the content of a file as UTF-8 JSON with comment support. This avoids the need to manually
decode a Buffer, parse and handle JSON comments within a schematic when JSON content is needed.
If a file path does not exist, an exception will be thrown. While this differs from the …
> Introduce Schematics Tree methods for `readText` and `readJSON`

- packages/angular/cli/src/command-builder/utilities/schematic-engine-host.ts
Fixes the schematic wrapper function used to capture the module's exports to correctly return `module.exports` instead of just `exports`.
```ts
(function() {
var exports = {};
var module = { exports };
// schematic #1 code example
// exports.default = ...
// schematic #2 code example
// module.exports = ...
// works for schematic #1 but fails for schematic #2
return exports['default'];
});
```
> fix(@angular/cli): change wrapping of schematic code

- packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/service-worker_spec.ts
- packages/angular_devkit/build_angular/src/utils/service-worker.ts
Paths within the `angular.json` file should be relative to the location of the `angular.json` file.
The `ngswConfigPath` option was incorrectly using the current working directory for a base path when
a relative configuration path was specified. Most of the time this would work as a build command usually
is executed from the root of the workspace. However, this may not always be the case and for those cases
the actual workspace root is now used to resolve the full path for the service worker configuration file.
> fix(@angular-devkit/build-angular): correctly resolve custom service worker configuration file

- packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/service-worker_spec.ts
- packages/angular_devkit/build_angular/src/utils/service-worker.ts
Paths within the `angular.json` file should be relative to the location of the `angular.json` file.
The `ngswConfigPath` option was incorrectly using the current working directory for a base path when
a relative configuration path was specified. Most of the time this would work as a build command usually
is executed from the root of the workspace. However, this may not always be the case and for those cases
the actual workspace root is now used to resolve the full path for the service worker configuration file.
> [13.3.x] fix(@angular-devkit/build-angular): correctly resolve custom service worker configuration file

- docs/design/analytics.md
- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.spec.ts.template
- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
- packages/schematics/angular/component/index.ts
- packages/schematics/angular/component/index_spec.ts
- packages/schematics/angular/component/schema.json
- packages/schematics/angular/directive/files/__name@dasherize@if-flat__/__name@dasherize__.directive.ts.template
- packages/schematics/angular/directive/index.ts
- packages/schematics/angular/directive/index_spec.ts
- packages/schematics/angular/directive/schema.json
- packages/schematics/angular/pipe/files/__name@dasherize@if-flat__/__name@dasherize__.pipe.ts.template
- packages/schematics/angular/pipe/index.ts
- packages/schematics/angular/pipe/index_spec.ts
- packages/schematics/angular/pipe/schema.json
- packages/schematics/angular/utility/find-module.ts
Adds the `--standalone` flag when generating components, directives or pipes through `ng generate`.
> feat(@schematics/angular): add --standalone to ng generate

- CHANGELOG.md
Cherry-picks the changelog from the "13.3.x" branch to the next branch (master).
> docs: release notes for the v13.3.4 release

- .github/workflows/dev-infra.yml
- .github/workflows/feature-requests.yml
- .github/workflows/lock-closed.yml
- package.json
- yarn.lock
Updates dev-infra to the latest snapshot, supporting for the
new migrate to main helper command.
> build: update dev-infra to latest snapshot

- .ng-dev/github.ts
- renovate.json
- scripts/publish.ts
- scripts/snapshots.ts
Changes part of the `DIRECT` phase of the "renaming master
to main" planning doc.
> build: changes for primary branch rename to `main` [12.2.x]

- renovate.json
- scripts/publish.ts
- scripts/snapshots.ts
Changes part of the `DIRECT` phase of the "renaming master
to main" planning doc.
Note the version of ng-dev used in this LTS branch does not properly
support custom primary branches, but this should be non-relevant here
because this commit will only land in a version branch (11.2.x)
> build: changes for primary branch rename to `main` [11.2.x]

- .circleci/config.yml
- goldens/public-api/angular_devkit/schematics/tasks/index.md
- packages/angular_devkit/schematics/tasks/package-manager/executor.ts
- packages/angular_devkit/schematics/tasks/package-manager/install-task.ts
- packages/angular_devkit/schematics/tasks/package-manager/options.ts
- tests/legacy-cli/e2e/assets/schematic-allow-scripts/collection.json
- tests/legacy-cli/e2e/assets/schematic-allow-scripts/index.js
- tests/legacy-cli/e2e/assets/schematic-allow-scripts/package.json
- tests/legacy-cli/e2e/assets/schematic-allow-scripts/schema.json
- tests/legacy-cli/e2e/tests/generate/install-allow-scripts.ts
- tests/legacy-cli/e2e/tests/misc/check-postinstalls.ts
In an effort to improve supply chain security, the `NodePackageInstallTask` will now use the package
manager's `--ignore-scripts` option by default. Without the option, all direct and transitive
dependencies would have their scripts executed during the task's package manager installation operation.
The change only affects the package manager behavior controlled by the Schematics `NodePackageInstallTask`.
First-party Angular schematics do not currently require any direct or transitive dependency
`install`/`postinstall` scripts to execute. Only two dependencies within a v14.0 new project would
potentially be affected by this: `nice-napi` (transitive from `piscina`) and `esbuild`. The `nice-napi`
functionality of `piscina` is unused within the Angular CLI with no plans to use it in the …
> feat(@angular-devkit/schematics): disable package script execution by default in `NodePackageInstallTask`

- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
- packages/schematics/angular/component/index_spec.ts
This commit adds the CommonModule imports to the standalone components
generated by the Angular's ng add component schematic.
> refactor(@schematics/angular): include CommonModule for standalone components

- packages/schematics/angular/BUILD.bazel
- packages/schematics/angular/utility/dependency.ts
- packages/schematics/angular/utility/dependency_spec.ts
An `addDependency` schematics rule has been added to the newly introduced `utility` subpath export for the `@schematics/angular` package.
This new rule allows for adding a package as a dependency to a `package.json`. By default the `package.json` located
at the schematic's root will be used. The `packageJsonPath` option can be used to explicitly specify
a `package.json` in different location. The type of the dependency can also be specified instead
of the default of the `dependencies` section by using the `type` option for either development or peer dependencies.
Will be added to the export path in #23041
> feat(@schematics/angular): introduce `addDependency` rule to utilities

- packages/angular/pwa/pwa/index.ts
- packages/schematics/angular/e2e/index.ts
- packages/schematics/angular/package.json
- packages/schematics/angular/service-worker/index.ts
- packages/schematics/angular/utility/index.ts
- packages/schematics/angular/utility/workspace-models.ts
- packages/schematics/angular/utility/workspace.ts
- packages/schematics/angular/utility/workspace_spec.ts
The `@schematics/angular` package now contains a defined set of package `exports` including a `utility` subpath export.
A wildcard export is also temporarily defined to support transition away from existing deep-import usage.
The `@schematics/angular/utility` subpath export will contain supported utility methods used by the first-party schematics
contained within the `@schematics/angular` package and can be considered public API that will follow SemVer stability constraints.
The first group of utilities introduced in this change are used to modify the `angular.json` workspace file
within the schematics and include the `updateWorkspace` rule and `readWorkspace`/`writeWorkspace` helpers.
> feat(@schematics/angular): introduce a utility subpath export for Angular rules and utilities

- packages/angular/cli/src/command-builder/command-module.ts
- packages/angular/cli/src/commands/completion/cli.ts
- packages/angular/cli/src/commands/completion/long-description.md
- packages/angular/cli/src/commands/config/cli.ts
- packages/angular/cli/src/utilities/completion.ts
- packages/angular/cli/src/utilities/environment-options.ts
- tests/legacy-cli/e2e/tests/misc/ask-analytics-command.ts
- tests/legacy-cli/e2e/tests/misc/completion-prompt.ts
- tests/legacy-cli/e2e/tests/misc/completion-script.ts
- tests/legacy-cli/e2e/tests/misc/completion.ts
- tests/legacy-cli/e2e/utils/process.ts
This updates the CLI to set up autocompletion for users automatically. Running `ng completion` now finds the relevant `~/.bashrc`, `~/.zshrc`, etc. file and adds the command to load Angular autocompletion for you, so users don't have to understand how to do it. `ng completion script` prints the actual shell script which needs to be evaluated in the shell (previously this was done by `ng completion` directly).
This also includes a prompt which is displayed to users on first command execution. After set up or if the user refuses the prompt, the CLI stores this state in the global workspace configuration and avoids prompting again. Users are expected to use `ng completion` if they want to set up autocompletion after previously refusing the prompt. This hopefully provides a good middle ground …
> feat(@angular/cli): prompt to set up autocompletion and add `ng completion init`

- .circleci/config.yml
- package.json
- yarn.lock
Cherry pick of #23071 targeting `13.3.x`.
Merge conflict was just from surrounding `package-lock.json` changes, nothing too interesting.
> build: update SauceLabs connect proxy version to 4.7.1

- .circleci/config.yml
- .github/ISSUE_TEMPLATE/1-bug-report.md
- .github/ISSUE_TEMPLATE/5-support-request.md
- .github/SAVED_REPLIES.md
- .github/angular-robot.yml
- .github/workflows/scorecard.yml
- CONTRIBUTING.md
- README.md
- docs/DEVELOPER.md
- docs/design/build-system.md
- docs/process/release.md
- packages/angular_devkit/build_angular/test/hello-world-app/README.md
- packages/angular_devkit/schematics/README.md
- packages/ngtools/webpack/package.json
- scripts/templates/contributing.ejs
- scripts/templates/readme.ejs
- tests/angular_devkit/core/json/schema/serializers/schema_benchmark.json
- tests/legacy-cli/e2e_runner.ts
Cleans up all referneces to the old `master` branch.
> build: cleanup references to old `master` branch

- CHANGELOG.md
> docs: release notes for the v13.3.5 release

- packages/angular/cli/src/utilities/completion.ts
- tests/legacy-cli/e2e/tests/misc/completion-prompt.ts
- tests/legacy-cli/e2e/tests/misc/completion.ts
Autocompletion tests [were failing on Windows](https://app.circleci.com/pipelines/github/angular/angular-cli/22152/workflows/8d883186-c144-4924-8a14-088e32d7c584/jobs/300321) due to a missing `$HOME` variable, presumably Windows wasn't inheriting the `$HOME` variable like Linux does?
Also fixing a semi-related typo I happened to notice around the same time.
Not sure exactly how to test this on Windows before merging, just hope for the best I guess?
> fix(@angular/cli): improve error message for Windows autocompletion use cases

- .circleci/config.yml
- .github/ISSUE_TEMPLATE/1-bug-report.md
- .github/ISSUE_TEMPLATE/5-support-request.md
- .github/SAVED_REPLIES.md
- .github/angular-robot.yml
- .github/workflows/scorecard.yml
- CONTRIBUTING.md
- README.md
- docs/DEVELOPER.md
- docs/design/build-system.md
- docs/process/release.md
- packages/angular_devkit/build_angular/test/hello-world-app/README.md
- packages/angular_devkit/schematics/README.md
- packages/ngtools/webpack/package.json
- scripts/templates/contributing.ejs
- scripts/templates/readme.ejs
- tests/angular_devkit/core/json/schema/serializers/schema_benchmark.json
- tests/legacy-cli/e2e_runner.ts
Patch port of changes for the `master` rename that conflicted with the 13.3.x branch
> [13.3.x] build: cleanup references to old `master` branch

- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
There is an extra space after the new `imports` decorator option in standalone components, whereas there are none after all the other existing options.
> fix(@schematics/angular): remove extra space in standalone imports

- goldens/public-api/angular_devkit/schematics/index.md
- goldens/public-api/angular_devkit/schematics/testing/index.md
- package.json
- packages/angular/cli/src/command-builder/architect-base-command-module.ts
- packages/angular/cli/src/command-builder/utilities/command.ts
- packages/angular_devkit/architect/src/create-builder.ts
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/testing/builder-harness.ts
- packages/angular_devkit/core/src/json/schema/registry.ts
- packages/angular_devkit/core/src/utils/object.ts
- packages/angular_devkit/core/src/workspace/json/reader_spec.ts
- packages/angular_devkit/schematics/src/engine/engine.ts
- packages/angular_devkit/schematics/src/engine/interface.ts
- packages/angular_devkit/schematics/src/rules/template.ts
- packages/angular_devkit/schematics/testing/schematic-test-runner.ts
- packages/ngtools/webpack/package.json
- packages/ngtools/webpack/src/ivy/host.ts
- packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
- packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
- packages/schematics/angular/utility/latest-versions/package.json
- tests/legacy-cli/e2e/tests/misc/third-party-decorators.ts
- yarn.lock
Bumps up the dev dependency of TypeScript to 4.7 and widens the peer dependency to allow `< 4.8`.
> build: update to TypeScript 4.7

- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-14/update-libraries-secondary-entrypoints.ts
- packages/schematics/angular/migrations/update-14/update-libraries-secondary-entrypoints_spec.ts
`package.json` files have been remove from secondary entrypoints in version 14 of Angular package format (APF).
With this change we delete the now redundant files and in case these contained the deprecated way of how to configure secondary entrypoints in ng-packagr we migrate these as well.
//cc @devversion
> fix(@schematics/angular): add migration to remove `package.json` in libraries secondary entry-points

- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/index_spec.ts
With the APF changes in version 14, the dts entrypoint file has been changed to `index.d.ts`, this results in TypeScript being able to resolve the type definition file without the need of the additional path to the flat module file dts.
> fix(@schematics/angular): don't add path mapping to old entrypoint file

- packages/angular/cli/src/command-builder/command-runner.ts
It appears that enabling this no longer causes a slugish experience.
> fix(@angular/cli): display option descriptions during auto completion

- scripts/validate-licenses.ts
This is what node, npm use. I'm hitting this when switching the e2e tests to bazel (https://github.com/angular/angular-cli/pull/23074).
> test: allow Artistic-2.0 license

- tests/legacy-cli/e2e/tests/basic/standalone.ts
A new E2E test has been added that updates a newly generated application to use a standalone component that
is bootstrapped with the newly introduced `bootstrapApplication` API. This test is intended to check that
the minimal functionality for a standalone-based application functions with the Angular CLI. More expansive
tests will be added as standalone features and capabilities are introduced within the Angular CLI.
Closes #23044
> test: add a minimal standalone component application E2E test

- .github/angular-robot.yml
- tests/legacy-cli/e2e/tests/build/prod-build.ts
The E2E test suite contains a production build test (`build/prod-build`) that performs
a size comparison check to ensure a production build of a newly generated application
stays within 10% of a predefined value (currently 124,000 bytes).
As a result of this preexisting check, the need to perform another check that involves
the added complexity of Github status hooks and API calls is currently not needed.
> ci: disable redundant Angular bot size check

- bin/devkit-admin
`minimist` is not in package.json. This causes errors when building e2e tests with bazel which enforces this. Removing it was simple to reduce dependencies instead of adding more...
>  build: replace minimist with yargs-parser 

- packages/ngtools/webpack/src/paths-plugin.ts
- tests/legacy-cli/e2e/tests/build/library-with-demo-app.ts
Locally-built APF v14 libraries should be resolved properly. Webpack
currently does not resolve them (in e.g. `dist/`) because the local
distribution folders are not marked as module roots, causing Webpack
to never hit the `resolve-in-package` with the proper description file (of
the locally built-package) and therefore skipping package exports resolution
and breaking secondary entry-points from being resolved properly (when bundling).
We fix this by determining local module/package roots through the
tsconfig. Ideally we could have leveraged information from other targets
in the project but the builder does not have access to that, and
leveraging tsconfig `paths` might also make this more flexible.
> fix(@angular-devkit/build-angular): properly handle locally-built APF v14 libraries

- tests/legacy-cli/e2e/utils/registry.ts
- tests/legacy-cli/e2e_runner.ts
- tests/legacy-cli/verdaccio.yaml
- tests/legacy-cli/verdaccio_auth.yaml
Best viewed [ignoring whitespace](https://github.com/angular/angular-cli/pull/23114/files?w=1).
When working on the bazel e2e tests (#23074) we might run tests in parallel such as bazel + non-bazel, npm + yarn etc.
Unfortunately the verdaccio `--listen` only sets the primary port and not the fallback which we need to also set, so we need to do the `.replace` thing :(
> test: use random ports for local verdaccio npm servers

- CHANGELOG.md
> docs: release notes for the v14.0.0-rc.0 release

- tests/legacy-cli/e2e/tests/basic/standalone.ts
After https://github.com/angular/angular/pull/45885, testability now needs to be explicitly added to `bootstrapApplication()`.
(cherry picked from commit 329a2a3798c1d5e60a7c6b165e9da2b9040c223b)
> test: update standalone test to add Protractor testing support

- packages/ngtools/webpack/src/paths-plugin.ts
With this change we refactor the paths-plugin resolution flow by using generators which makes the code more readable and easier to follow.
Please review with whitespace turned off. https://github.com/angular/angular-cli/pull/23125/files?diff=split&w=1
> refactor(@ngtools/webpack): simplify resolution flow by using generators

- docs/design/analytics.md
- docs/process/release.md
Analytics approvers and caretaker pairings are out of date. Updated to not list explicit names at all so this doesn't require updating as consistently.
FYI @mgechev as current DevRel lead.
FYI @jelbourn as current UberTL who is now dropped from explicit analytics approvals in favor of the tooling TL (I assume you're fine with me and Minko making analytics calls).
> Remove out-of-date names in documentation

- goldens/public-api/angular_devkit/schematics/tools/index.md
- package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
- packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
- yarn.lock
This is an RC port of #23122.
Bumps up the repo to the RC version of TypeScript 4.7.
> build: update to TypeScript 4.7 RC

- packages/angular/cli/lib/cli/index.ts
- packages/angular/cli/src/command-builder/schematics-command-module.ts
Previously, the errors were JSON stringified (https://github.com/angular/angular-cli/blob/main/packages/angular/cli/lib/cli/index.ts#L80) which caused them not to be displayed correctly.
Closes #23141
> fix(@angular/cli): print schematic errors correctly

- packages/angular/cli/src/command-builder/schematics-command-module.ts
Relative schematics referenced in `angular.json` `schematicCollections` and `defaultCollection` were always resolved from the current working directory, which is not correct and caused the collection not to be resolved when the this is different from the location of the workspace config.
Closes #23136
> fix(@angular/cli): resolve relative schematic from `angular.json` instead of current working directory

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
The newer version of `babel-loader` contains a fix for its hash function usage
that will cause it to not use MD4 on Node.js versions that no longer support that
hashing algorithm.
Fixes #23134
> fix(@angular-devkit/build-angular): update `babel-loader` to 8.2.5

- packages/angular/cli/src/commands/doc/cli.ts
When the `--search` option is passed to `ng doc`, it should open a URL that does a search across the whole website (instead of the default behavior of limiting the search to API docs).
Fix the `ng doc` command to implement the iteded behavior (previously, it did the opposite).
> fix(@angular/cli): correctly handle `--search` option in `ng doc`

- packages/angular/cli/src/commands/update/cli.ts
- tests/legacy-cli/e2e/tests/update/update-10.ts
For v14, the update command migration execution logic was incorrectly exiting after
the success of the first package's migrations. This prevented any other updated
packages from executing migrations automatically. The success check is now a failure
check and will allow the migration execution process to continue to execute migrations
until complete or a failure occurs.
> fix(@angular/cli): ensure all available package migrations are executed

- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
change the order of imports during component generation using `changeDetectionStrategy` set to `OnPush`
closes angular#23156
> fix(@schematics/angular): alphabetically order imports during component generation

- packages/angular/cli/src/commands/completion/long-description.md
Spin off from https://github.com/angular/angular/pull/45995.
This explains how to set up autocompletion with the Angular CLI:
1. Via the automated prompt on first execution.
2. Via `ng completion`.
3. Manually via appending `source <(ng completion script)` to the user's `~/.bashrc` file.
It also specifically calls out supported and unsupported platforms as well as the requirement for a global install of the Angular CLI.
The demo `/generated/images/guide/cli/completion.gif` needs to be merged to the angular/angular repository. https://github.com/angular/angular/pull/45995 will submit that image so it can be used from this doc.
@mgechev, not sure if you want anyone from the docs team to take an edit pass on this?
/cc @twerske, @alan-agius4
> docs: add Angular CLI autocompletion doc

- packages/angular/cli/src/commands/completion/cli.ts
- packages/angular/cli/src/utilities/completion.ts
- tests/legacy-cli/e2e/tests/misc/completion-prompt.ts
- tests/legacy-cli/e2e/tests/misc/completion.ts
- tests/legacy-cli/e2e/utils/process.ts
If the user does not have a global install of the Angular CLI, the autocompletion prompt is skipped and `ng completion` emits a warning. The reasoning for this is that `source <(ng completion script)` won't work without `ng` on the `$PATH`, which is only really viable with a global install. Local executions like `git clone ... && npm install && npm start` or ephemeral executions like `npx @angular/cli` don't benefit from autocompletion and unnecessarily impede users.
A global install of the Angular CLI is detected by running `which -a ng`, which appears to be a cross-platform means of listing all `ng` commands on the `$PATH`. We then look over all binaries in the list and exclude anything which is a directo child of a `node_modules/.bin/` directory. These include local executions and …
> fix(@angular/cli): skip prompt or warn when setting up autocompletion without a global CLI install

- CHANGELOG.md
> docs: release notes for the v13.3.6 release

- CHANGELOG.md
> docs: release notes for the v14.0.0-rc.1 release

- tests/legacy-cli/e2e/assets/webpack/test-app/package.json
- tests/legacy-cli/e2e/tests/build/material.ts
- tests/legacy-cli/e2e/tests/build/styles/tailwind-v2.ts
- tests/legacy-cli/e2e/tests/build/styles/tailwind-v3.ts
- tests/legacy-cli/e2e/tests/commands/add/version-specifier.ts
Several tests that perform package actions during the test have been updated to
function correctly when used with npm. npm 7+ performs additional resolution
on peer dependencies which can result in failures during testing.
The following tests have been updated:
* `build/material` - This test contained an actual error in that it was installing the `latest`
version of `@angular/material-moment-adapter` when testing prereleases even though
it should have been installing the `next` tag instead.
* `build/styles/tailwind-v[23]` - This test had to be reordered due to npm 7+ keeping the
installed `tailwindcss` peer dependency in a non-hoisted location even after the project
level package was uninstalled. The ordering also uncovered a Webpack cache key creation defect
wherein the cache key does …
> test: update E2E tests to support using npm 7+

- tests/legacy-cli/e2e_runner.ts
Was there another reason to do this that tests aren't covering?
> build: do not depend on test build order

- .ng-dev/caretaker.ts
- .ng-dev/config.ts
- docs/process/release.md
Add the caretaker configuration to set up being able to run both the carataker
check and the handoff commands.
The caretaker handoff command will operate using the angular-cli-caretaker group
which has already been seeded with the current information.
Caretakers can update the current caretakers in the angular-cli-caretaker group, granting them the necessary access for caretaking using the `ng-dev caretaker handoff` command.  Additionally, the caretaker can check the status of the repository and merge queues using `ng-dev caretaker check`.
> build: add caretaker configuration to ng-dev config

- packages/angular/cli/src/commands/update/cli.ts
The `next` option is not ignored when using the `migrate-only` option. This option is used to determine if a newer version of the CLI needs to be downloaded.
https://github.com/angular/angular-cli/blob/3d76cef369b936a6d01108802cfe7dabca602f2e/packages/angular/cli/src/commands/update/cli.ts#L876
> fix(@angular/cli): remove incorrect warning during `ng update`

- goldens/public-api/angular_devkit/schematics/index.md
- packages/angular_devkit/schematics/src/rules/base.ts
- packages/angular_devkit/schematics/src/rules/base_spec.ts
Previously, the `chain` base rule only accepted an `Array` of schematics rules.
In addition to still allowing an `Array`, `chain` now can accept either an `Iterable<Rule>`
or `AsyncIterable<Rule>`. This provides support for sync and async generator functions
with the `chain` rule.
> feat(@angular-devkit/schematics): allow `chain` rule to accept iterables of rules

- tests/legacy-cli/e2e/setup/001-create-tmp-dir.ts
- tests/legacy-cli/e2e/setup/002-npm-sandbox.ts
- tests/legacy-cli/e2e/setup/010-local-publish.ts
- tests/legacy-cli/e2e/setup/200-create-project-dir.ts
- tests/legacy-cli/e2e/setup/500-create-project.ts
- tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
- tests/legacy-cli/e2e/tests/misc/update-git-clean-subdirectory.ts
- tests/legacy-cli/e2e/utils/assets.ts
- tests/legacy-cli/e2e/utils/process.ts
Removing the use of globally installed npm and npm packages. Instead npm+yarn within the test-runner use npm+yarn from package.json (not globals). Tests no longer depend on any `--global` and use npm+ng installed locally within the temporary test directories.
This might be the last step before being able to run multiple tests concurrently (https://github.com/angular/angular-cli/pull/23114 was the other big one).
This might be the last one before getting the e2e tests working in bazel (https://github.com/angular/angular-cli/pull/23074)
EDIT: this has changed to keep globals but use a isolated global cache per invocation, see comment below
Original attempt removing use of `--global`: https://github.com/angular/angular-cli/commit/02f703999694056b5b4253a6b7da63f3c5926dc3
> test: remove use of global npm cache and config 

- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/builders/browser/tests/behavior/typescript-target_spec.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build_localize_replaced_watch_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/typescript.ts
There is no standard for library authors to ship their library in different ES versions, which can result in vendor libraries to ship ES features which are not supported by one or more browsers that the user's application supports.
With this change, we will be downlevelling libraries based on the list of supported browsers which is configured in the browserslist configuration. Previously, we only downlevelled libraries when targeting ES 5.
The TypeScript target option will not effect how the libraries get downlevelled.
Closes #23126
> fix(@angular-devkit/build-angular): downlevel libraries based on the browserslist configurations

- packages/angular/cli/src/command-builder/command-module.ts
- packages/angular/cli/src/command-builder/schematics-command-module.ts
- packages/schematics/angular/app-shell/schema.json
- packages/schematics/angular/class/schema.json
- packages/schematics/angular/component/schema.json
- packages/schematics/angular/directive/schema.json
- packages/schematics/angular/enum/schema.json
- packages/schematics/angular/guard/schema.json
- packages/schematics/angular/interceptor/schema.json
- packages/schematics/angular/interface/schema.json
- packages/schematics/angular/module/schema.json
- packages/schematics/angular/pipe/schema.json
- packages/schematics/angular/resolver/schema.json
- packages/schematics/angular/service/schema.json
- packages/schematics/angular/web-worker/schema.json
With this change we change the how we handle `"format": "path"` schematic property option. We replace the formatter in favour of a `SmartDefaultProvider`, which ensures that nested schematics can access the `workingDirectory`.
> fix(@angular/cli): populate path with working directory in nested schematics
