angular/angular-cli

- packages/angular/cli/src/commands/completion/long-description.md
Assets paths in AIO need to be relative. This also ensures that the base href element is respected if changed. 
https://app.circleci.com/pipelines/github/angular/angular/46755/workflows/ea228e6e-62ab-4d7f-9764-2c1056ad0366/jobs/1173152
> docs: correct `completion.gif` image path

- packages/schematics/angular/utility/dependency.ts
- packages/schematics/angular/utility/dependency_spec.ts
- packages/schematics/angular/utility/index.ts
When using the `addDependency` rule from `@schematics/angular/utility` a new option is now
available that supports controlling the rule's behavior when scheduling the `NodePackageInstallTask`.
Previously, the behavior was automatic and the rule would only schedule the task if it was not already
scheduled by a previous `addDependency` rule usage for the `package.json`. This behavior is still the
default behavior. However, it can now be customized per rule invocation via the `install` rule option
which can be either `InstallBehavior.None`, `InstallBehavior.Auto`, or `InstallBehavior.Always`.
> feat(@schematics/angular): support controlling `addDependency` utility rule install behavior

- CHANGELOG.md
> docs: release notes for the v13.3.7 release

- CHANGELOG.md
- tests/legacy-cli/e2e/utils/project.ts
> docs: release notes for the v14.0.0-rc.2 release

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
The `es2015` exports package condition is used by `rxjs` to allow bundlers to use the ES2015-based
ESM code instead of the default of ES5-based ESM code. The ES5-based ESM code is larger in size
and harder to optimize due to the downlevelled classes. This change results in a ~5Kb size reduction
for the main bundle of a new application (129920 -> 124183).
> fix(@angular-devkit/build-angular): add es2015 exports package condition to browser-esbuild

- packages/angular/cli/src/commands/update/cli.ts
npm 7+ can fail due to it incorrectly resolving peer dependencies that have valid SemVer
ranges during an `ng update`. Update will set correct versions of dependencies within the
package.json file. However, the failing npm package installation will cause the update process
to abort. To workaround these errors, the npm force option is set during package
installation when the npm package manager at version 7.0.0 or greater is used during an update.
Example error:
```
npm ERR! Conflicting peer dependency: @angular/compiler-cli@14.0.0-rc.0
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^14.0.0 || ^14.0.0-rc" from @angular-devkit/build-angular@14.0.0-rc.0
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev …
```
> fix(@angular/cli): workaround npm 7+ peer dependency resolve errors during updates

- packages/schematics/angular/package.json
- packages/schematics/angular/private/components.ts
- packages/schematics/angular/private/standalone.ts
- packages/schematics/angular/private/standalone_spec.ts
The standalone component helper utilities introduced into the `@angular/cdk` via
https://github.com/angular/components/pull/24931 have been added to an export path (`private/components`)
within `@schematics/angular`. The export path is primarily intended for the use of the components schematics
within `@angular/cdk` and `@angular/material`. The API exported from this path is not considered public API,
does not provide SemVer guarantees, and may be modified or removed without a deprecation cycle.
> refactor(@schematics/angular): move standalone component helpers to a private export for Angular components

- .circleci/config.yml
Node.js v16 is now the default development environment for the CLI. v16
also should provide performance improvements for the E2E test runs and is
the more commonly used version of Node.js at this time. v16.10 is currently
the minimum supported version of the Node.js v16 major for the Angular CLI.
> ci: update Windows E2E job to use Node.js 16.10

- packages/angular/cli/src/utilities/package-manager.ts
- packages/angular_devkit/schematics/tasks/package-manager/executor.ts
Yarn 2 and higher no longer support the `--silent` flag.
The Angular CLI will now spawn package managers with the stdout ignored when silent
mode is needed and only show stderr when the process exits unsuccessfully. This
provides the necessary functionality for the CLI without relying on package manager
options.
> fix(@angular/cli): support silent package installs with Yarn 2+

- packages/angular_devkit/schematics/tasks/package-manager/executor.ts
Yarn 2 and higher no longer support the `--ignore-scripts` flag.
The `NodePackageInstallTask` will now spawn Yarn with environment variables to ignore
scripts instead of the commandline option. Other package managers remain unchanged.
This provides the necessary functionality for the task without relying on Yarn
commandline options.
> fix(@angular-devkit/schematics): support ignore scripts package installs with Yarn 2+

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- tests/legacy-cli/e2e/tests/build/styles/tailwind-v3-cjs.ts
`tailwind.config.cjs` is a valid tailwindcss configuration file as it's listed in https://github.com/tailwindlabs/tailwindcss/blob/8845d112fb62d79815b50b3bae80c317450b8b92/src/util/resolveConfigPath.js#L46-L52 as such we should also take this filename into consideration.
Closes #23236
> fix(@angular-devkit/build-angular): detect `tailwind.config.cjs` as valid tailwindcss configuration

- tests/legacy-cli/e2e/tests/misc/npm-7.ts
`NPM_CONFIG_legacy_peer_deps` is set to `true` during snapshot test runs https://github.com/angular/angular-cli/blob/177fa0d8c0076589fc12bce5ca5969606d541336/tests/legacy-cli/e2e/utils/packages.ts#L67-L69. This causes the `ng add @angular/localize` to not fail because of incorrect peer dependencies, which isn't the case when test against latest or next versions.
With this change, we update this test to always set `NPM_CONFIG_legacy_peer_deps` to `true`.
> test(@angular/cli): force using `NPM_CONFIG_legacy_peer_deps` for  `ng add` NPM 7 test

- packages/schematics/angular/application/index.ts
This setting is redundant under an application project since an application cannot be created under another application.
> fix(@schematics/angular): remove strict setting under application project

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
Only the `replaceBootstrap` TypeScript transform is needed with the `browser-esbuild` builder.
The `replaceBootstrap` transform converts the default generated JIT bootstrap call into an AOT
bootstrap call within an application. The other transforms were used to remove the development
and JIT related metadata from the AOT compiler generated code. However, with the esbuild based
build pipeline, these will be automatically removed without the need for additional transforms
via the earlier usage of the `ngJitMode` and `ngDevMode` defines.
> refactor(@angular-devkit/build-angular): remove unneeded TypeScript transforms with esbuild

- packages/angular/cli/src/commands/update/cli.ts
- packages/angular/cli/src/utilities/package-manager.ts
The package manager `--force` option is only relevant to npm 7+ wherein the option controls
the strictness of the npm 7+ peer dependency resolution. Yarn 2+ does not support a `--force`
option. When the `ng update` `--force` option was used, `ng update` was incorrectly
applying the package manager `--force` option to Yarn which lead to an installation failure.
This has now been corrected and the package manager `--force` option is now only applied to npm 7+.
> fix(@angular/cli): during an update only use package manager force option with npm 7+

- packages/angular/cli/src/commands/cache/clean/cli.ts
- packages/angular/cli/src/commands/cache/cli.ts
- packages/angular/cli/src/commands/cache/info/cli.ts
- packages/angular/cli/src/commands/cache/settings/cli.ts
Currently, this was being shown available as a global command which shouldn't be the case.
> fix(@angular/cli): correct scope cache command

- packages/angular/cli/src/command-builder/command-runner.ts
With this change we add a footer to indicate that more commands are available when running the CLI in a different context. Ie inside or outside of a workspace.
> fix(@angular/cli): add text to help output to indicate that additional commands are available when ran in different context

- packages/angular/cli/src/command-builder/command-module.ts
- packages/angular/cli/src/command-builder/command-runner.ts
- packages/angular/cli/src/command-builder/schematics-command-module.ts
- packages/angular/cli/src/commands/config/cli.ts
- packages/angular/cli/src/utilities/config.ts
- packages/angular/cli/src/utilities/package-manager.ts
Previously, when a global configuration was not found on disk we forcefully created it even when it was not needed.
This causes issues in CI when multiple `ng` commands would run in parallel as it caused a read/write race conditions.
See: https://angular-team.slack.com/archives/C46U16D4Z/p1654089933910829
> fix(@angular/cli): avoid creating unnecessary global configuration

- packages/angular/cli/lib/cli/index.ts
- tests/legacy-cli/e2e/tests/misc/completion-script.ts
In certain situations the existing console logger created via `@angular-devkit/core` `createConsoleLogger`
could try to write to a closed stdout pipe stream. This would result in an error during
execution. For cases such as the completion script command, this would also prevent the
command from functioning. To mitigate these cases, `createConsoleLogger` is no longer used
and instead a logger instance is directly created within the CLI that uses `Console.log`
and `Console.error` to write output. Exiting the CLI also now waits for messages to be
logged before proceeding with the exit.
Fixes #23288
> fix(@angular/cli): improve resilience of logging during process exit

- .github/angular-robot.yml
The issue triage behavior is no longer used within this repository.
For the merge behavior, only the label status checks are potentially
beneficial but they are already checked via the `ng-dev` tooling
when merging.
> ci: disable outdated Angular robot merge and triage behavior

- packages/angular/pwa/package.json
The peer dependency is needed so that the correct version that mathes the installed Angular CLI is installated.
> fix(@angular/pwa): add peer dependency on Angular CLI

- packages/angular/cli/src/command-builder/architect-command-module.ts
- tests/legacy-cli/e2e/tests/commands/project-cannot-be-determined-by-cwd.ts
When the workspace has multiple projects and we the project to use cannot be determined from the current working directory, we now issue an actionable error message.
Closes #23291
> fix(@angular/cli): provide actionable error when project cannot be determined

- packages/angular_devkit/build_angular/src/builders/browser/tests/options/verbose_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/watch-files-logs-plugin.ts
With this change we print out the modified and removed files when running a build in verbose mode. This can be useful to debug builds that rebuilds multiple times without an apparent file change.
> fix(@angular-devkit/build-angular): log modified and removed files when using the `verbose` option

- packages/angular/cli/src/command-builder/architect-base-command-module.ts
- tests/legacy-cli/e2e/tests/commands/builder-not-found.ts
I was testing if we supported a warning here today and noticed that it was printing "Try installing with '[object Object] install'". Easy fix at least.
> fix(@angular/cli): correctly print package manager name when an install is needed

- tests/legacy-cli/e2e/setup/002-npm-sandbox.ts
- tests/legacy-cli/e2e/tests/commands/add/registry-option.ts
- tests/legacy-cli/e2e/utils/packages.ts
This way npmrc can be used for global cross-test configuration and environment variables can be overridden locally for each test case. There's probably more but these are some simple ones for now.
> test: reduce use of npmrc for test npm configuration

- packages/angular/cli/lib/cli/index.ts
- packages/angular/cli/src/analytics/analytics.ts
- packages/angular/cli/src/command-builder/architect-base-command-module.ts
- packages/angular/cli/src/command-builder/command-runner.ts
- packages/angular/cli/src/command-builder/schematics-command-module.ts
- packages/angular/cli/src/command-builder/utilities/schematic-engine-host.ts
- packages/angular/cli/src/commands/add/cli.ts
- packages/angular/cli/src/commands/completion/cli.ts
- packages/angular/cli/src/commands/update/cli.ts
- packages/angular/cli/src/commands/update/schematic/index.ts
- packages/angular/cli/src/utilities/completion.ts
- packages/angular/cli/src/utilities/error.ts
Prepares the `@angular/cli` package for the eventual change of enabling the
TypeScript `useUnknownInCatchVariables` option. This option provides additional
code safety by ensuring that the catch clause variable is the proper type before
attempting to access its properties. Similar changes will be needed in the other
packages in the repository prior to enabling `useUnknownInCatchVariables`.
> refactor(@angular/cli): assert catch clause variable type before usage

- tests/legacy-cli/e2e/tests/basic/rebuild.ts
- tests/legacy-cli/e2e/tests/basic/serve.ts
- tests/legacy-cli/e2e/tests/commands/serve/serve-path.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-basehref.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-es2015.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-es5.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-locale-data-augment.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-server.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-serviceworker.ts
- tests/legacy-cli/e2e/tests/i18n/setup.ts
- tests/legacy-cli/e2e/tests/misc/fallback.ts
- tests/legacy-cli/e2e/tests/misc/proxy-config.ts
- tests/legacy-cli/e2e/tests/misc/public-host.ts
- tests/legacy-cli/e2e/tests/misc/ssl-default.ts
- tests/legacy-cli/e2e/tests/misc/ssl-with-cert.ts
- tests/legacy-cli/e2e/utils/network.ts
- tests/legacy-cli/e2e/utils/project.ts
- tests/legacy-cli/e2e_runner.ts
To allow concurrent tests on the same machine...
Can probably just squash the commits? 🤷
> test: use dynamic ports for e2e tests

- tests/legacy-cli/e2e/tests/build/disk-cache-purge.ts
- tests/legacy-cli/e2e/tests/build/disk-cache.ts
We don't need to include all applications code to verify disk cache existence.
This reduces the test duration of `disk-cache.ts` by a whopping `~65s` since this tests runs `ng build` 5 times and `disk-cache-purge.ts` by `~13s`.
These timings were gathered using gLinux and is expected that the gain is more significant on Circle CI Linux and Windows executors
> test: reduce disk-cache E2E tests duration

- .circleci/config.yml
This reduced the Linux CI time by around 7 mins
> ci: increase parallelism for Linux E2E

- packages/angular/cli/lib/init.ts
Running autocompletion with `14.0.1` installed globally in a `14.0.0` project logs the version warning in a very annoying fashion:
```
$ ng verYour global Angular CLI version (14.0.1) is greater than your local version (14.0.0). The local Angular CLI version is used.
To disable this warning use "ng config -g cli.warnings.versionMismatch false".
sion
```
This adds an exception for `ng completion` commands to avoid this edge case.
> fix(@angular/cli): disable version check when running `ng completion` commands

- CHANGELOG.md
- packages/angular/cli/src/commands/run/cli.ts
- tests/legacy-cli/e2e/tests/basic/run.ts
- tests/legacy-cli/e2e/tests/commands/run-configuration-option.ts
With this commit we issue a more actionable error message when using the unsupported
`--configuration` option with the`ng run` command.
Closes #23385
> fix(@angular/cli): provide an actionable error when using `--configuration` with `ng run`

- packages/angular_devkit/build_angular/src/builders/karma/index.ts
- tests/legacy-cli/e2e/tests/test/test-include-glob.ts
Previously, we amended the project source root to the source root which resulted in an invalid path.
Closes #23396
> fix(@angular-devkit/build-angular): fix incorrect glob cwd in karma when using `--include` option

- package.json
Apparently the `ng-dev` command does not work with Git Bash on windows
because of the environment variable being set. We should use `ts-node`
directly to avoid this issue, and also avoid the `$PWD` access which
might not work depending on the shell.
Also on the dev-infra side we would need to remove the ts-node shebang
and leave the responsibility to the consumer project.
> build: ensure ng-dev command works on windows

- packages/angular/cli/BUILD.bazel
- packages/angular/cli/lib/config/workspace-schema.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/builders.json
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/external-dependencies_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/setup.ts
This commit add a new `externalDependencies` option to the experimental browser builder.
Dependencies listed in this option will not be included in the final bundle, instead the user would need to provide them at runtime using import maps or another method.
Closes #23322
>     feat(@angular-devkit/build-angular): add `externalDependencies` to the esbuild browser builder

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/builders/extract-i18n/index.ts
Since extraction doesn't work on the browser we can ignore the `supportedBrowsers` configuration during message extraction.
Closes #23420
> fix(@angular-devkit/build-angular): ignore supported browsers during i18n extraction

- CHANGELOG.md
> docs: release notes for the v14.0.3 release

- package.json
- tests/legacy-cli/e2e/setup/010-local-publish.ts
- tests/legacy-cli/e2e/setup/100-global-cli.ts
- tests/legacy-cli/e2e/utils/BUILD.bazel
- tests/legacy-cli/e2e/utils/process.ts
- tests/legacy-cli/e2e_runner.ts
- yarn.lock
When sandboxed in bazel there is no accessible npm and it must be installed manually some way or another. The npm shipped with node is also not accessible (see https://github.com/bazelbuild/rules_nodejs/pull/3467).
This ~~yarn~~ npm is for the test-runner to install the packages being tested, not for the tests themselves which use a custom cli/npm/yarn within the test process.
Best attempt at using yarn: https://github.com/angular/angular-cli/commit/975f92a33b989b05cb917e099d045dbc8d0a47e4
> test: do not depend on a global npm binary

- packages/angular/cli/lib/config/workspace-schema.json
- packages/angular/cli/src/commands/config/cli.ts
- packages/angular/cli/src/utilities/config.ts
- tests/legacy-cli/e2e/tests/commands/config/config-global-validation.ts
- tests/legacy-cli/e2e/tests/commands/config/config-set.ts
Add `cliOptions.completion` to workspace-schema.json.
Resolve an error found using `ng-config` to disable version mismatch:
```
$ ng config -g cli.warnings.versionMismatch false
Your global Angular CLI version (14.0.2) is greater than your local version (14.0.1). The local Angular CLI version is used.
To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Error: Schema validation failed with the following errors:
Data path "/cli" must NOT have additional properties(completion).
```
---
Please note that I was unable to run the test suite locally on my M1 Mac. After running `yarn bazel test //packages/...`, I received the following error that I was unable to resolve (I tried following the error message guidance to no avail):
```
ERROR: no such package …
```
> fix(@angular/cli): prevent schema validation error

- renovate.json
It seems the Angular CLI uses schedule strings which end up being
incorrect according to `@beejs/later` (which is used by Renovate)
The Renovate app dashboard also seems to show some uncaught errors
(no logs available) and based on communication with the team, it
sounds like Renovate is missing some updates.
Also migrates to the new properties as recommended by the Renovate
config validator.
> ci: attempt to fix renovate configuration schedules

- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
Since version 4, webpack-dev-server by default will shutdown gracefully. This results in `CTRL+C` needed to be pressed multiple times to exit the process.
See: https://github.com/webpack/webpack-dev-server/blob/c76b6d11a3821436c5e20207c8a38deb6ab7e33c/lib/Server.js#L1801-L1827
Closes #22216
> fix(@angular-devkit/build-angular): exit dev-server when CTRL+C is pressed

- packages/angular/cli/src/commands/new/cli.ts
- tests/legacy-cli/e2e/tests/commands/ng-new-collection.ts
Previously, this option was ignored due to an incorrect deconstruction.
Closes #23414
> fix(@angular/cli): correctly handle `--collection` option in `ng new`

- packages/angular/cli/src/utilities/color.ts
- packages/angular_devkit/architect_cli/bin/architect.ts
- packages/angular_devkit/benchmark/src/main.ts
- packages/angular_devkit/build_angular/src/utils/color.ts
- packages/angular_devkit/schematics_cli/bin/schematics.ts
- tests/legacy-cli/e2e/utils/process.ts
This has been fixed in https://github.com/doowb/ansi-colors/pull/44
> refactor: clean up old ansi-colors castings

- packages/ngtools/webpack/src/ivy/plugin.ts
A TypeScript version mismatch with the Angular compiler will no longer cause an
exception to propagate up through the Webpack system. In Node.js v14, this resulted
in an unhandled promise rejection warning and the build command never completing.
This can also be reproduced in newer versions of Node.js by using the Node.js
option `--unhandled-rejections=warn`. To correct this issue, the version mismatch
is now treated as a compilation error and added to the list of errors that are
displayed at the end of the build. This also has the benefit of avoiding the stack
trace of the exception from being shown which previously drew attention away from
the actual error message.
New output example:
```
./src/main.ts - Error: Module build failed (from …
```
> fix(@ngtools/webpack): show a compilation error on invalid TypeScript version

- packages/angular_devkit/build_angular/src/utils/i18n-options.ts
When using localization we setup `SIGINT` signal to delete the temporary directory. In some cases this resulted in delaying the process from exiting a couple of seconds.
Closes #22216
> fix(@angular-devkit/build-angular): exit localized build when CTRL+C is pressed

- packages/ngtools/webpack/src/ngcc_processor.ts
More context about this can be found in the following comment: https://github.com/angular/angular-cli/issues/19205#issuecomment-722727791
Closes #19205
> fix(@ngtools/webpack): restore process title after NGCC is executed

- goldens/public-api/angular_devkit/build_angular/index.md
- packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/server/index.ts
- packages/angular_devkit/build_angular/src/testing/test-utils.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-app-shell-service-worker.ts
Previously, the base href was not set when using the app-shell builder and i18n.
Closes #22389
> fix(@angular-devkit/build-angular): set base-href in service worker manifest when using i18n and app-shell

- packages/angular_devkit/architect/src/create-builder.ts
- packages/angular_devkit/architect/src/index_spec.ts
Waiting to complete the builder until the next tick allows the logging
subscription to flush and provide queued logging entries to the builder
consumer.
Closes #20865
> fix(@angular-devkit/architect): complete builders on the next event loop iteration

- packages/angular_devkit/build_angular/src/builders/karma/find-tests.ts
- packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage-exclude_spec.ts
- packages/angular_devkit/build_angular/src/builders/karma/tests/options/include_spec.ts
- packages/angular_devkit/build_angular/src/utils/copy-assets.ts
- packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
By default, a glob pattern starting with a forward slash will be "mounted" onto the system root. This causes globs to escape the workspace root.
With this change we configure disable glob "mounting".
Closes #23467
---
Note: we should probably eventually validate the paths in the workspace config.
> fix(@angular-devkit/build-angular): disable glob mounting for patterns that start with a forward slash

- goldens/public-api/angular_devkit/build_angular/index.md
- packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/base-href_spec.ts
- packages/angular_devkit/build_angular/src/testing/test-utils.ts
With this change we fix a regression were we  set the base-href to `/` when the browser builder `baseHref` option is not set.
Closes #23475
> fix(@angular-devkit/build-angular): don't override base-href in HTML when it's not set in builder

- .bazelrc
This is useful when running tests locally as otherwise 50 workers are spawned when running the `//packages/angular_devkit/build_angular:build_angular_browser_test` target even when having an `fit` on a single test. This also disabled re-runs on flaky tests.
//cc @devversion, not sure if there is a better way.
> build: add bazel config that disabled sharding and flaky re-runs

- CONTRIBUTING.md
- scripts/templates/contributing.ejs
We just renamed the Angular code of conduct repository default branch
to `main`. This repository was not part of the large migration and is
now handled separately as a little clean-up.
> build: account for rename of `angular/code-of-conduct` default branch

- packages/angular_devkit/build_angular/src/webpack/plugins/common-js-usage-warn-plugin.ts
With this change we include `CommonJsSelfReferenceDependency` and `CommonJsExportsDependency` in the CJS checks.
Closes #23505
> fix(@angular-devkit/build-angular): improve detection of CommonJS dependencies

- CHANGELOG.md
> docs: release notes for the v14.0.5 release

- tests/legacy-cli/e2e/tests/build/prod-build.ts
The change in regexp now matched the below output
```
bootstrapModule($a).catch(e=>console.error(e));
```
> test: update prod-build E2E test to handle esbuild output

- packages/angular/cli/lib/init.ts
Previously when having completion enabled and the current workspaces has an older version of the Angular CLI installed in the terminal the below errors is show. This is because the older versions of the CLI do not implement this command. Now we exit gracefully.
```
The specified command ("completion") is invalid. For a list of available options,
run "ng help".
Did you mean "analytics"?
```
Closes #23518
> fix(@angular/cli): handle cases were having completion enabled but running in an older CLI workspace

- packages/angular/cli/src/command-builder/command-module.ts
- tests/legacy-cli/e2e/tests/misc/negated-boolean-options.ts
Prefixing options with `no` in schema definitions appears to be used more widely than initially thought.
The `noOption` can also be provided in the `angular.json` which makes this property definition less ambiguous, since boolean options don't get prefixed with `no` in the JSON config. Therefore, in order to reduce the community changes we remove the deprecation warning for such options and change the interim solution to permanent one.
None-the-less, it's still recommended that options are defined without the `no` prefix.
> fix(@angular/cli): remove deprecation warning of `no` prefixed schema options

- .circleci/config.yml
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
- tests/legacy-cli/e2e/tests/build/styles/include-paths.ts
This change adds support for using Sass stylesheets within an application built with the experimental
esbuild-based browser application builder. Global stylesheets (`styles` build option) and component
stylesheets (`@Component({ styleUrls: [...], ...})`) with Sass can now be used.
The `stylePreprocessorOptions.includePaths` option is also available for Sass stylesheets.
Both the default format (`.scss`) and the indented format (`.sass`) are supported.
Inline component stylesheet support is not yet available with the esbuild-based builder.
> feat(@angular-devkit/build-angular): add Sass file support to experimental esbuild-based builder

- packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts
- tests/legacy-cli/e2e/tests/build/scripts-output-hashing.ts
Instead of generating the content hash based on the content of scripts BEFORE the optimization phase,
the content hash is generated AFTER the optimization phase.
Prevents caching issues where browsers block execution of scripts due to the integrity hash not matching
with the cached script in case of a script being optimized differently than in a previous build,
where it would previously result in the same content hash.
Fixes #22906
Test case is based on the reproduction example as specified in #22906 (thanks!).
> fix(@angular-devkit/build-angular): generate different content hashes for scripts which are changed during the optimization phase

- CHANGELOG.md
> docs: release notes for the v14.0.6 release

- package.json
This should have been done automatically in the `14.1.0-rc.0` release, but tooling issues mean this was missed and we can't successfully fix the RC release since `main` and `14.1.x` and in inconsistent states, which confuses `ng-dev`.
> refactor: bump version of `main` branch to `14.2.0-next.0`

- packages/angular_devkit/core/src/workspace/json/reader.ts
When parsing the angular.json file, the 'i18n' key used to configure localization in a localized project should be treated as a special project extension key.
This fixes the warning "Project extension with invalid name found." printed when starting/building the project.
> fix(@angular-devkit/core): add i18n as valid project extension

- packages/angular_devkit/core/src/workspace/json/reader.ts
When logging the warning `Project extension with invalid name found.`, include the name of the project extension, to facilitate debugging.
> fix(@angular-devkit/core): log name of invalid extension too

- tests/legacy-cli/e2e/tests/i18n/ivy-localize-sourcemaps.ts
- tests/legacy-cli/e2e/tests/i18n/setup.ts
This helps to cut down on the time taken i18n tests take to run.
> test: remove unnecessary `extract-i18n` command from i18n setup

- packages/angular_devkit/architect_cli/BUILD.bazel
- packages/angular_devkit/architect_cli/bin/architect.ts
- packages/angular_devkit/architect_cli/package.json
`rxjs` was only a dependency for the `tap` operator which can be replaced
by accessing the result object returned from awaiting the builder output
`Observable` which is already converted to a Promise.
> refactor(@angular-devkit/architect-cli): remove rxjs as a dependency

- packages/schematics/angular/application/other-files/app.component.html.template
Fixes that the component generated by `ng new` had an incorrect logo for Angular Material.
For reference, here's the current logo:
And this is what it should look like:
https://angular.io/presskit#angular-material
> fix(@schematics/angular): incorrect logo for Angular Material

- packages/angular/create/README.md
NPM doesn't correctly handle version specifier for scoped packages when using the `init` command
See: https://github.com/npm/cli/issues/5175
> docs: remove `@latest` reference from `npm init` command

- .circleci/dynamic_config.yml
Currently fail_fast doesn't work in Windows as the shell is set to Powershell
```
#!powershell.exe -ExecutionPolicy Bypass
curl -X POST --header "Content-Type: application/json" "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel?circle-token=${CIRCLE_TOKEN}"
Invoke-WebRequest : A parameter cannot be found that matches parameter name 'X'.
At line:1 char:6
+ curl -X POST --header "Content-Type: application/json" "https://circl ...
+      ~~
+ CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Exited with code exit status 1
CircleCI received exit code 1
```
> ci: change shell to bash in fail_fast job

- packages/schematics/angular/e2e/index.ts
- packages/schematics/angular/utility/dependency.ts
- packages/schematics/angular/utility/dependency_spec.ts
- packages/schematics/angular/utility/index.ts
The E2E schematic will now (as it did previously) skip adding dependencies
if they already exist within the `package.json` regardless of the specifier.
This is accomplished with the `existing` option for the `addDependency` rule
which allows defining the behavior for when a dependency already exists.
Currently the two option behaviors are skip and replace with replace being
the default to retain behavior for existing rule usages.
> fix(@schematics/angular): Allow skipping existing dependencies in E2E schematic

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
While this vulnerability cannot be exploited through the Angular CLI as we don't expect it to be run on production servers. We update terser to remove the unnecessary vulnerability noise.
Closes #23593
> fix(@angular-devkit/build-angular): update terser to address CVE-2022-25858

- CHANGELOG.md
> docs: release notes for the v13.3.9 release

- .circleci/dynamic_config.yml
This commits changes the CI workflow to run all the complete E2E test suit on Windows for PRs.
The also increase the parallelism for Windows tests to 16 to reduce the time taken for this step and removes the requirement for the `build` step before running `e2e-cli-win`.
Based on the current timings, this change will not increase PR CI times.
> ci: enable full E2E suit test on Windows for PRs

- .circleci/dynamic_config.yml
With this commit, we create different matrices for our e2e tests. This reduces the duration of the workflow by ~7mins
More information: https://circleci.com/docs/using-matrix-jobs
> ci: create e2e matrices

- packages/angular_devkit/core/src/utils/strings.ts
- packages/schematics/angular/class/index_spec.ts
- packages/schematics/angular/component/index_spec.ts
- packages/schematics/angular/enum/index_spec.ts
- packages/schematics/angular/module/index.ts
- packages/schematics/angular/module/index_spec.ts
- packages/schematics/angular/pipe/index.ts
- packages/schematics/angular/pipe/index_spec.ts
- packages/schematics/angular/utility/generate-from-files.ts
- packages/schematics/angular/utility/validation.ts
**fix(@angular-devkit/core): `classify` string util should concat string without using a `.`**
`.` is not a valid character in ES6 class names.
Prior to this change `foo.module` before used to be incorrectly classified to `Foo.Module` instead of `FooModule`.
Closes #13824
----
**fix(@schematics/angular): prevent numbers from class names**
With this change we prevent creating classes with invalid characters.
Closes #12868
---
Combined into a single PR as they are dependent on each other.
> Schematics class name validation

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
The esbuild-based experimental builder will now leverage the bundler to perform resolution of CSS imports.
This allows for more comprehensive resolution including packages which use the `sass` and/or `style` custom
conditions within a `package.json` exports field.
> fix(@angular-devkit/build-angular): allow the esbuild-based builder to fully resolve global stylesheet packages

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
During development we should not set `ngDevMode` to `true`, as this is expected to be an object literal.
Closes #23627
> fix(@angular-devkit/build-angular): correctly set `ngDevMode` in esbuilder

- packages/angular/create/README.md
- packages/angular/create/src/index.ts
- tests/legacy-cli/e2e/tests/misc/create-angular.ts
Previously, NPM was always used to install dependencies even when using `yarn create` or `pnpm create`
> fix(@angular/create): use appropriate package manager to install dependencies

- .circleci/bazel.rc
When something is tagged as manual you should still be able to manually run it...
> test: remove exclusion of bazel tests based on manual tag

- tests/legacy-cli/e2e/tests/misc/supported-angular.ts
- tests/legacy-cli/e2e_runner.ts
To prevent cascading errors in other tests. Normally one error stops the entire suite but I've found this annoying when experimenting 🤷
> test: revert local test project file changes on test completion

- packages/angular/cli/src/utilities/error.ts
- packages/angular_devkit/build_angular/src/utils/error.ts
Errors thrown in RxJs are not instanceof Error and therefore the check will always fail.
Closes #23631
> fix(@angular/cli): catch clause variable is not an Error instance

- tests/legacy-cli/e2e/setup/001-create-tmp-dir.ts
- tests/legacy-cli/e2e/tests/commands/completion/completion-prompt.ts
- tests/legacy-cli/e2e/tests/commands/completion/completion.ts
- tests/legacy-cli/e2e/utils/registry.ts
- tests/legacy-cli/e2e/utils/utils.ts
To put the login in a common location. This will allow easily using the bazel temp dir when converting to bazel.
> test: move tempdir creation to util method

- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
- tests/legacy-cli/e2e/tests/commands/serve/preflight-request.ts
With this commit, we add a middleware that handles preflight requests as currently responses for this type of requests returning 404.
This is a temporary workaround until this issue is fixed upstream. See: https://github.com/webpack/webpack-dev-server/issues/4180
Closes #23639
> fix(@angular-devkit/build-angular): correctly respond to preflight requests

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
- scripts/validate-licenses.ts
- yarn.lock
This dependency is only used to valid that node packages are resolved correctly.
With this change we mock the structure of font-awesome to avoid having to install it.
> build: remove dependency on font-awesome

- CHANGELOG.md
Cherry-picks the changelog from the "14.1.x" branch to the next branch (main).
> docs: release notes for the v14.1.1 release

- packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/postcss-cli-resources.ts
Previously, the RegExp didn't correctly handle cases where data URIs had escaped quotes like the below
```css
url("data:image/svg+xml;charset=utf-8,<svg width=/"16/" height=/"15/"></svg>")
```
Closes #23680
> fix(@angular-devkit/build-angular): correctly handle data URIs with escaped quotes in stylesheets

- tests/legacy-cli/e2e/tests/commands/completion/completion-prompt.ts
- tests/legacy-cli/e2e/tests/commands/completion/completion.ts
- tests/legacy-cli/e2e/tests/misc/ask-analytics-command.ts
- tests/legacy-cli/e2e/utils/utils.ts
Primarily because one of them was using `fs.mkdtemp` instead of the util `mktempd` method which standardizes the tempdir logic. Using the common util method will allow bazel (#23074) to use the bazel tempdir instead of system tempdir
> test: use common mockHome method

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
When using the experimental esbuild-based browser application builder, babel transformation
is now only performed on a file if the file requires the specific transformations enabled
for the build. This has the benefit of removing the need to parse and process files that
will not be affected by the enabled transformations.
From initial testing, this provides a 30% build time improvement for development builds of a
newly generated application and a 10% improvement for production builds.
> perf(@angular-devkit/build-angular): reduce babel transformation in esbuild builder

- packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/serve_service-worker_spec.ts
- packages/angular_devkit/build_angular/src/utils/service-worker.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/service-worker-plugin.ts
With this change we add the ability for the dev-server to serve service workers when configured in the browser builder.
Closes #9869
> feat(@angular-devkit/build-angular): add ability to serve service worker when using dev-server

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
With this change we replace Sass legacy with the modern API in the experimental esbuilder. The goal is that in the next major version this change is propagated to the Webpack builder.
Based on the benchmarks that we did Sass modern API is faster compared to the legacy version.
> feat(@angular-devkit/build-angular): switch to Sass modern API in esbuild builder

- packages/ngtools/webpack/src/transformers/elide_imports.ts
- packages/ngtools/webpack/src/transformers/elide_imports_spec.ts
With this change we fix an issue where type only named imports were being emitted. As a result webpack failed to resolve such symbols as they don't exist in JavaScript.
Closes #23667
> fix(@ngtools/webpack): elide type only named imports when using `emitDecoratorMetadata`

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/css-resource-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
Stylesheet url tokens (`url(....)`) will now be processed when using the esbuild-based experimental browser
application builder. The paths will be resolved via the bundler's resolution system and then loaded
via the bundler's `file` loader. The functionality is implemented using an esbuild plugin to allow for all
file types to be supported without the need to manually specify each current and future file extension within
the build configuration.
The `externalDependencies` option also applies to the referenced resources. This allows for resource paths
specified with the option to remain unprocessed within the application output. This is useful if the relative
path for the resource does not exist on disk but will be available when the application is deployed.
> fix(@angular-devkit/build-angular): process stylesheet resources from url tokens with esbuild browser builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/css-resource-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
Stylesheet url tokens (`url(....)`) will now be processed when using the esbuild-based experimental browser
application builder. The paths will be resolved via the bundler's resolution system and then loaded
via the bundler's `file` loader. The functionality is implemented using an esbuild plugin to allow for all
file types to be supported without the need to manually specify each current and future file extension within
the build configuration.
The `externalDependencies` option also applies to the referenced resources. This allows for resource paths
specified with the option to remain unprocessed within the application output. This is useful if the relative
path for the resource does not exist on disk but will be available when the application is deployed.
(cherry picked from commit …
> [14.1.x]fix(@angular-devkit/build-angular): process stylesheet resources from url tokens with esbuild browser builder

- tools/toolchain_info.bzl
With this change we disable running UTs on multiple node.js versions. This is mainly an interim solution until we find the root cause of the memory increase and OOM errors during bazel test.
During this change I also noticed that the toolchain was configured incorrectly. Setting the toolchain to use Node.js 16 causes the App-shell tests to fail when used under Bazel. See: https://app.circleci.com/pipelines/github/angular/angular-cli/25009/workflows/4ea86ec8-d1f7-4c91-8810-76f10f8e878c/jobs/325982
> build: disable UT testing multiple node versions

- packages/angular_devkit/build_angular/src/webpack/plugins/analytics.ts
This commit updates to bundle stats logic to skip checking chunks with no files.
Closes #23717
> fix(@angular-devkit/build-angular): avoid collect stats from chunks with no files

- CHANGELOG.md
Cherry-picks the changelog from the "14.1.x" branch to the next branch (main).
> docs: release notes for the v14.1.2 release

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
CSS does not support the single line JS comment (`//`) but rather only the multi-line comment (`/* */`).
When generating the sourcemap URL comment with the modern Sass API, the multi-line comment syntax will
now be used. This removes the esbuild warnings per Sass file that would have otherwise been generated
when stylesheet sourcemaps are enabled for the build.
> fix(@angular-devkit/build-angular): use valid CSS comment for sourcemaps with Sass in esbuild builder

- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
The upstream fix https://github.com/webpack/webpack-dev-server/issues/4180 has been merged and released as part of `webpack-dev-server` version `4.10.0`
> refactor(@angular-devkit/build-angular): remove workaround for handle options requests

- tests/legacy-cli/e2e_runner.ts
While adding more params + defaults I noticed these were missing 🤷
> test: add missing yargs config

- tests/legacy-cli/e2e/utils/assets.ts
The source files within the git repo would normally be `rwxr-xr-x`, so writable only by the owner. If the tests are run under a different user they need write permission on the files once copied into the temp directory the e2e tests are running in.
> test: ensure test assets are writable when copied for use in e2e tests

- packages/angular_devkit/core/src/workspace/json/reader.ts
Warnings about workspace extensions are phrased:
> Invalid project extension....
Warnings about workspace extensions are phrased:
> Invalid workspace extension....
> fix(@angular-devkit/core): update workspace extension warning to use correct phrasing

- packages/angular_devkit/core/src/logger/logger.ts
The RxJS `empty` function is deprecated and will be removed in future versions.
The `EMPTY` constant is the recommended replacement.
Closes #23729
> refactor(@angular-devkit/core): remove deprecated rxjs `empty` function usage

- packages/angular_devkit/schematics/src/engine/schematic.ts
- packages/angular_devkit/schematics/src/rules/call.ts
The amount of additional RxJS operators and chaining has been reduced within the `callRule`
and `callSource` functions. This also reduces the complexity of the code and removes
several repetitive code segments.
> refactor(@angular-devkit/schematics): reduce RxJS usage in callRule/callSource functions

- CHANGELOG.md
Cherry-picks the changelog from the "14.1.x" branch to the next branch (main).
> docs: release notes for the v14.1.3 release

- packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/postcss-cli-resources.ts
PR #23691 introduced a regression that caused paranthesis in url not to be handled correctly.
This change correct this behaviour and adds a test case to valid this.
Closes #23773
> fix(@angular-devkit/build-angular): correctly handle parenthesis in url

- .bazelrc
The first+last in the diff prevent busting the analysis cache between build+test. The others are minor improvements or will be required for e2e tests.
> build: prevent busting bazel analysis cache between build and test

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
The global stylesheet processing using esbuild and the code bundling that also uses esbuild are now executed
asynchronously. Previously, the global stylesheet processing was required to wait until the code bundling was
complete before starting. Any warnings and/or errors for global stylesheets will also now be shown even if there
are errors during code bundling.
> refactor(@angular-devkit/build-angular): process esbuild builder global stylesheets and code at the same time

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
When using the experimental esbuild-based browser application builder with Sass stylesheets, an
additional string creation for each output stylesheet will now be avoided when sourcemaps are disabled.
Previously, the Sass compiler was imported on the start of every build regardless of its usage.
The Sass compiler will now only be loaded if a Sass stylesheet is requested.
> Minor performance improvements for esbuild-based builder Sass support

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
The sourcemap URL in the output CSS files for global stylesheets is now correctly updated to
reflect the name of the global stylesheet output file and not the internal `stdin` virtual
file name.
> fix(@angular-devkit/build-angular): correct esbuild builder global stylesheet sourcemap URL

- CHANGELOG.md
- package.json
- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/utility/latest-versions.ts
As a minor release, this PR is slightly different than most `ng-dev` based releases because we needed to update our dependencies to no longer include `-next` and `-rc`. See https://github.com/angular/angular-cli/blob/main/docs/process/release.md#release.
> Bump version to "v14.2.0" with changelog.

- packages/schematics/angular/utility/latest-versions/package.json
This is one-half of the fix in https://github.com/angular/angular-cli/pull/23801 in case we need to decouple this fix from the TS 4.8 update.
> fix(@schematics/angular): update ng-packagr version to `^14.2.0`

- CHANGELOG.md
> docs: release notes for the v14.2.1 release

- tests/legacy-cli/e2e/tests/build/bundle-budgets.ts
- tests/legacy-cli/e2e/utils/process.ts
- tests/legacy-cli/e2e/utils/utils.ts
... and cleanup a few typescript types.
I've been debugging a failing test where stderr is not being matched. I tried these fixes and figured they may as well be merged? 🤷
> test: watch full stdout when waiting for match

- tests/legacy-cli/e2e/tests/misc/cli-exit-interop.ts
- tests/legacy-cli/e2e/tests/packages/webpack/test-app.ts
- tests/legacy-cli/e2e/tests/update/update-multiple-versions.ts
- tests/legacy-cli/e2e/tests/update/update.ts
- tests/legacy-cli/e2e/utils/assets.ts
- tests/legacy-cli/e2e/utils/project.ts
Remove reliance on tarballs during E2E. Instead we always download the package from the private NPM server.
> test: remove reliance on built tarballs in E2E tests

- .circleci/dynamic_config.yml
- tests/legacy-cli/e2e/tests/misc/browsers.ts
- tests/legacy-cli/e2e/utils/process.ts
The saucelabs tests were blindly noop-ing because the `E2E_BROWSERS` variable was not propagated to the child process.
This fixes the variables not propagating, but I'd like to also ensure this doesn't happen again. Currently I've changed the saucelabs test to fail if running without saucelabs configured instead of being a silent noop, but that means it must be manually excluded when saucelabs is not setup. Any other ideas or preferences?
> test: ensure saucelabs tests are not excluded in CI

- .circleci/dynamic_config.yml
Upload build artifacts from PR builds to the CircleCI storage to allow users to download
an in progress version of a change for testing.
> build: upload build artifacts from PR builds to CircleCI for usage

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
This contains several minor adjustments to the setup steps for the experimental
esbuild-based browser application builder. It better groups the output directory
deletion and creation steps as well as moves entry point normalization into the
normalize options helper function. This should reduce the size of the main
execution function as well as aid in future profiling of the build phases.
> refactor(@angular-devkit/build-angular): reorganize esbuild builder setup steps

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
The experimental esbuild-based browser application builder will now consider SVG files as
Angular component templates. Previously, only HTML files were considered templates and this
resulted in the esbuild-based builder to try to process the SVG file as a stylesheet.
> fix(@angular-devkit/build-angular): allow esbuild-based builder to use SVG Angular templates

- packages/angular_devkit/build_angular/BUILD.bazel
This reverts commit 1193886df5e8110de20ba534e2b4572da72b5e4a.
Commit was causing `ci/circleci: test` to fail.  Example run: https://app.circleci.com/pipelines/github/angular/angular-cli/25678/workflows/18659a91-2a18-466f-8228-011900c623e1/jobs/336368
> Revert "test: enable rbe on all unit tests"

- packages/angular/cli/src/command-builder/schematics-command-module.ts
BREAKING CHANGE: The 'path' option in schematics schema no longer has a special meaning. Use 'workingDirectory' smart default provider should be used instead.
> refactor(@angular/cli): remove deprecated path handler

- packages/schematics/angular/app-shell/schema.json
- packages/schematics/angular/universal/schema.json
BREAKING CHANGE: Removed unused`appDir` option from Universal schematic
> refactor(@schematics/angular): remove deprecated appDir option

- packages/angular/cli/BUILD.bazel
- packages/angular/pwa/BUILD.bazel
- packages/angular_devkit/architect/BUILD.bazel
- packages/angular_devkit/architect/node/BUILD.bazel
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/core/BUILD.bazel
- packages/angular_devkit/core/node/BUILD.bazel
- packages/angular_devkit/core/node/testing/BUILD.bazel
- packages/angular_devkit/schematics/BUILD.bazel
- packages/angular_devkit/schematics/tasks/BUILD.bazel
- packages/angular_devkit/schematics/tasks/node/BUILD.bazel
- packages/angular_devkit/schematics/tools/BUILD.bazel
- packages/angular_devkit/schematics_cli/BUILD.bazel
- packages/schematics/angular/BUILD.bazel
- tools/ng_cli_schema_generator.bzl
- tools/ts_json_schema.bzl
Improvements to the syncing process allow for reduced usage of the comment markers.
> build: adjust BUILD file external comment markers

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
esbuild 0.15.6 now supports transforming `for await..of` syntax and will now be used instead of babel
when the syntax is found within code that will be bundled. Zone.js requires that all async/await
related code be downleveled to properly hook promise callbacks. esbuild does not yet support
transforming async generators and so babel is still used when async generator syntax is detected
in an input file.
esbuild 0.15.6 also adjusted the `supported` option to imply that all dependent features of a
disabled feature are disabled as well. For the CLI, this allows only needing to specify that
`async-await` is disabled in the esbuild options.
> perf(@angular-devkit/build-angular): use esbuild-based builder to directly downlevel `for await...of`

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
See: https://github.com/postcss/postcss-import/pull/496
Note: the major bump is due to drop of support of Node.Js prior to version 14, which the CLI doesn't support anyways.
> fix(@angular-devkit/build-angular): handling of `@media` queries inside css layers

- tests/legacy-cli/e2e_runner.ts
This seems unnecessary.
All the tests where the removed `if` is truthy seem to work locally and CI is green.
> test: remove ci specific logic

- tests/legacy-cli/e2e/utils/process.ts
- tests/legacy-cli/e2e/utils/test_process.ts
This is bloating the logs with in most cases not needed information and make it harder to find the actual errors.
Example output
```
Running test "tests/build/styles/stylus.ts" (8 of 27 [3:8] (60/218))...
==========================================================================================
Running `/usr/local/bin/node "/home/circleci/ng/tests/legacy-cli/e2e/utils/run_test_process" "/home/circleci/ng/tests/legacy-cli/e2e/tests/build/styles/stylus"`...
CWD: /mnt/ramdisk/e2e/e2e-test/test-project
==========================================================================================
Running `ng "build" "--source-map" "--configuration=development"` [silent]...
CWD: /mnt/ramdisk/e2e/e2e-test/test-project
Test Process error Error: Process exit error - "ng build --source-map …
```
> test: remove environment variable from error dump

- packages/angular/cli/src/commands/update/schematic/index.ts
- packages/angular/cli/src/utilities/package-metadata.ts
Prior to this change during update deprecated packages that satisfied the version range constrain where being favored over the non-deprecated versions if the version of the deprecated version is greater. Ex: if `14.3.1` is deprecated and `14.3.0` is not the former was being installed.
With this change we now change the logic to favor non deprecated version of the package and only use the deprecated package when no satisfying version is found.
This fix is needed as in some cases a package which cannot be unpublished from NPM will gave to be to be deprecated, if the version is for a reason or another broken.
> fix(@angular/cli): favor non deprecated packages during update

- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/tests/behavior/index_watch_spec.ts
Since the index augmentation happens outside of Webpack previously the index html was not being watched during watch mode.
Closes #23851
> fix(@angular-devkit/build-angular): watch index file when running build in watch mode

- packages/schematics/angular/class/schema.json
- packages/schematics/angular/component/schema.json
- packages/schematics/angular/directive/schema.json
- packages/schematics/angular/enum/schema.json
- packages/schematics/angular/guard/schema.json
- packages/schematics/angular/interceptor/schema.json
- packages/schematics/angular/interface/schema.json
- packages/schematics/angular/module/schema.json
- packages/schematics/angular/pipe/schema.json
- packages/schematics/angular/resolver/schema.json
- packages/schematics/angular/service/schema.json
- packages/schematics/angular/utility/generate-from-files.ts
While this option is always required it was not marked as such
Closes #23848
> fix(@schematics/angular): mark project as required option

- packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/serve_service-worker_spec.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/service-worker-plugin.ts
Previously, we tried to read the files from the wrong location as during localize we alter the output directory to a different temporary location.
https://github.com/angular/angular-cli/blob/7e64b1537d54fadb650559214fbb12707324cd75/packages/angular_devkit/build_angular/src/utils/i18n-options.ts#L251-L252
Closes #23844
> fix(@angular-devkit/build-angular): handle service-worker serving with localize in dev-server

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/typescript.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
This checks are no longer needed as `enableIvy` option is now meaningless to the compiler
> refactor(@angular-devkit/build-angular): remove Ivy checks

- packages/angular_devkit/build_angular/src/webpack/plugins/service-worker-plugin.ts
Previously, when there was an error during a build that had service workers enabled, the dev-server crashed as the promise was rejected instead of emitting a compilation error.
With this change we update the logic so that any errors during the SW augmentation phase are changed to a compilation error and also update the logic so that when there are compilation errors we don't try to generate a SW.
See: https://github.com/angular/angular-cli/issues/23844#issuecomment-1236311405
> fix(@angular-devkit/build-angular): change service worker errors to compilation errors

- packages/schematics/angular/component/index.ts
- packages/schematics/angular/directive/index.ts
- packages/schematics/angular/module/index.ts
- packages/schematics/angular/pipe/index.ts
- packages/schematics/angular/utility/add-declaration-to-ng-module.ts
This commits extracts all `addDeclarationToNgModule` logic into a common util which is re-used across a number of schematics.
> refactor(@schematics/angular): consolidate `addDeclarationToNgModule`  logic

- CHANGELOG.md
> docs: release notes for the v14.2.2 release

- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Previously, the regexp was incorrectly matching messages which contained "at" as part of the text.
Closes #23865
> fix(@angular-devkit/build-angular): correctly display error messages that contain "at"

- tests/legacy-cli/e2e_runner.ts
This allows debugging the test failures when running in debug mode.
(cherry picked from commit e8e9df875722d23bbfd11c70ad17c492353976ce)
> test: don't run git clean on test failure

- tests/legacy-cli/e2e/setup/002-npm-sandbox.ts
- tests/legacy-cli/e2e/tests/misc/npm-7.ts
- tests/legacy-cli/e2e/utils/process.ts
Applying this to everything to reduce stdout spam. There's also the note about the 3 minute timeout although I don't think I've seen that myself.
> test: suppress npm update warnings

- .github/workflows/scorecard.yml
The `ossf/scorecard-action` action will automatically use the builtin GITHUB_TOKEN as needed.
> ci: remove manually specifying GITHUB_TOKEN in scorecard action

- tests/legacy-cli/e2e/tests/build/material.ts
- tests/legacy-cli/e2e/tests/commands/add/add-material.ts
- tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
Now that `@angular/material` has been released as `15.0.0-next` we can re-enable these tests.
> test: re-enable Angular material tests

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- tests/legacy-cli/e2e/tests/build/rebuild-symlink.ts
This commit addresses an issue which caused symbolic links not to be watched properly.
Closes #23896
> fix(@angular-devkit/build-angular): watch symbolic links

- .circleci/dynamic_config.yml
- packages/angular/cli/BUILD.bazel
- packages/angular/pwa/BUILD.bazel
- packages/angular_devkit/architect/BUILD.bazel
- packages/angular_devkit/benchmark/BUILD.bazel
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_webpack/BUILD.bazel
- packages/angular_devkit/core/BUILD.bazel
- packages/angular_devkit/core/node/BUILD.bazel
- packages/angular_devkit/schematics/BUILD.bazel
- packages/angular_devkit/schematics/tools/BUILD.bazel
- packages/angular_devkit/schematics_cli/BUILD.bazel
- packages/ngtools/webpack/BUILD.bazel
- packages/schematics/angular/BUILD.bazel
- tools/toolchain_info.bzl
This re-enables the multiple node versions/toolchains but runs them as separate circleci jobs to not overload the executors. Also disabling the node16 version of the one test that seems to crash with node16.
> test: unit test multiple node versions in separate jobs

- .github/workflows/scorecard.yml
Version 2 of the `openssf/scorecard-action` GitHub action requires the `id-token: write` permission to publish results.
> ci: adjust workflow permissions for OpenSSF Scorecard results publishing

- package.json
- yarn.lock
Update to saucelabs connect 4.8.1
(cherry picked from commit 82649bc6c27d5b9c9f07d5c877a61da8a7d1e61b)
Cherry pick of https://github.com/angular/angular-cli/pull/23909.
> build: update saucelabs connect version

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
Support for the `fileReplacements` option from the Webpack-based builder has now been integrated into the experimental esbuild-based browser application builder. The option will no longer be ignored during builds. Only the officially supported form of the option (`replace`/`with` fields) is implemented.
> feat(@angular-devkit/build-angular): add esbuild-based builder initial support for fileReplacements

- packages/angular_devkit/build_angular/test/hello-world-app/src/test.ts
- packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/src/test.ts
- packages/schematics/angular/application/files/src/test.ts.template
- packages/schematics/angular/library/files/src/test.ts.template
These new options have been introduced in Angular v14. The commit enables the options in a new project, as we did when we introduced the `destroyAfterOption`, with the same long-term goal to have these options enabled by default.
This is similar to #21300 which was done in the past to add `destroyAfterOption: true` by default.
This was discussed with @AndrewKushnir (who wants to discuss it in the next team sync meeting) and the idea would be to change these options to true by default and add a migration to ease the transition in v16 or later.
> feat(@schematics/angular): enable error on unknown properties and elements in tests

- docs/process/release.md
In `14.2.0`, we learned that we can't bump peer deps / `latest-versions.ts` in a release PR, because the released NPM artifact is actually built *before* an opportunity to edit the PR appears. We need to do a separate before the CLI release to make this change.
See: https://angular-team.slack.com/archives/C46U16D4Z/p1661482133013029
Hopefully I'm understanding how and why this works correctly, please let me know if I'm missing anything or if my wording is confusing.
> docs: clarify that version bumps must happen separately from the release PR

- .circleci/dynamic_config.yml
- tests/legacy-cli/e2e/utils/project.ts
If things like the temp dir, project root etc have long paths (such as custom paths passed on the cli, or bazel runfiles/temp directories) then this is required.
> test: enable git core.longpaths option

- tests/legacy-cli/e2e_runner.ts
I had a case of something else above throwing and it was hidden due to this.
> test: catch and log all errors include test setup

- packages/angular/cli/lib/init.ts
- packages/angular/cli/src/command-builder/utilities/schematic-engine-host.ts
- packages/angular/cli/src/commands/add/cli.ts
- packages/angular/cli/src/commands/update/cli.ts
The global require function is not present in Node.js ESM mode. To support the eventual transition of the `@angular/cli` package to ESM, usage of the `require.resolve` function has been converted to use locally created `require` functions via `createRequire` from the `module` builtin.
> refactor(@angular/cli): remove use of global require resolve

- packages/angular_devkit/build_angular/src/builders/server/index.ts
- packages/angular_devkit/build_angular/src/builders/server/platform-server-exports-loader.ts
- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
- packages/angular_devkit/build_angular/test/hello-world-app/src/main.server.ts
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-15/remove-platform-server-exports.ts
- packages/schematics/angular/migrations/update-15/remove-platform-server-exports_spec.ts
- packages/schematics/angular/universal/files/src/__main@stripTsExtension__.ts.template
- tests/legacy-cli/e2e/tests/build/platform-server.ts
This commit adds an internal file to export needed symbols from `@angular/platform-server` when building a server bundle. This is needed.  This is needed so that DI tokens can be referenced and set at runtime outside of the bundle.
Also, it adds a migration to remove these exports from the users files as otherwise an export collision would occur due to the same symbol being exported multiple times.
> feat(@angular-devkit/build-angular): export `@angular/platform-server` symbols in server bundle

- packages/angular_devkit/core/src/workspace/json/reader.ts
- packages/angular_devkit/core/src/workspace/json/reader_spec.ts
BREAKING CHANGE: Workspace projects with missing `root` is now an error.
> fix(@angular-devkit/core): throw error when project has missing root property

- packages/angular_devkit/build_angular/src/utils/webpack-diagnostics.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/transfer-size-plugin.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
- packages/ngtools/webpack/src/resource_loader.ts
With this change we replace all usage of `compilation.errors `and `compilation.warnings.push` with `addError` and `addWarning` respectively.
Also, we update the helpers in build-angular to use `WebpackError` from the current compilation to avoid mismatching instances.
> refactor: use `addWarning` and `addError` helpers to push Webpack diagnostics

- packages/angular/cli/src/command-builder/architect-base-command-module.ts
- packages/angular/cli/src/command-builder/command-module.ts
- packages/angular/cli/src/command-builder/schematics-command-module.ts
With this commit the builder and schematic names are added as page title to page events.
Also, we address a bug where during a watch or error in some cases analytics where not flushed. Examples when the builder has a watch mode.
> fix(@angular/cli): add builders and schematic names as page titles in collected analytics

- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/src/builders/app-shell/app-shell_spec.ts
- packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
With this change we configure the app-shell builder to set the `ɵSERVER_CONTEXT` private provider.
FYI @AndrewKushnir
> feat(@angular-devkit/build-angular): add `ng-server-context` when using app-shell builder

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-15/update-karma-main-file.ts
- packages/schematics/angular/migrations/update-15/update-karma-main-file_spec.ts
With the recent changes in build-angular the `require.context` calls have become unneeded.
BREAKING CHANGE: `require.context` are no longer parsed. Webpack specific features are not supported nor guaranteed to work in the future.
> feat(@schematics/angular): add migration to remove require calls from karma builder main file

- packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
- packages/angular_devkit/build_angular/src/sass/sass-service-legacy.ts
- packages/angular_devkit/build_angular/src/sass/worker-legacy.ts
- packages/angular_devkit/build_angular/src/sass/worker.ts
- packages/angular_devkit/build_angular/src/utils/environment-options.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- tests/legacy-cli/e2e/tests/build/styles/scss-legacy.ts
Sass modern API provides faster compilations times when used in an async manner.
|Application compilation duration | Sass API and Compiler|
|-- | --|
|60852ms | dart-sass legacy sync API|
|52666ms | dart-sass modern API|
Note: https://github.com/johannesjo/super-productivity was used for benchmarking.
Prior art: http://docs/document/d/1CvEceWMpBoEBd8SfvksGMdVHxaZMH93b0EGS3XbR3_Q?resourcekey=0-vFm-xMspT65FZLIyX7xWFQ
- Deprecated support for tilde import has been removed. Please update the imports by removing the `~`.
Before
```scss
@import "~font-awesome/scss/font-awesome";
```
After
```scss
@import "font-awesome/scss/font-awesome";
```
- By default the CLI will use Sass modern API, While not recommended, users can still opt to use legacy API by setting …
> feat(@angular-devkit/build-angular): switch to use Sass modern API

- CHANGELOG.md
> docs: release notes for the v14.2.4 release

- packages/angular_devkit/build_angular/src/sass/worker.ts
In some cases the build will crash when there is a Sass error due to the fact that the `span` property on the Error instance cannot be cloned.
```
process.nextTick(() => { throw err; });
^
DataCloneError: function StaticClosure() {
} could not be cloned.
at MessagePort.<anonymous> (/node_modules/@angular-devkit/build-angular/src/sass/worker.js:61:41)
```
> fix(@angular-devkit/build-angular): fix crash when Sass error occurs

- packages/schematics/angular/application/files/src/main.ts.template
The recet removal of enableProdMode in 283b564d1de985f0af8c2fcb6192801a90baacda introduced unnecessary empty lines in main.ts
See https://github.com/cexbrayat/angular-cli-diff/blob/15.0.0-next.3/ponyracer/src/main.ts
main.ts is now:
```ts
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';
platformBrowserDynamic().bootstrapModule(AppModule)
.catch(err => console.error(err));
```
Note the removal of the extra lines
> fix(@schematics/angular): remove empty lines in main.ts

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
Localization fails to inline translations into module js files. This becomes an issue with module-federation builds.
Issue Number:  #23008
Allow locale to be inlined to both `script` and `module` files using `sourceType: 'unambiguous'`. https://babeljs.io/docs/en/options#sourcetype
> fix(@angular-devkit/build-angular): allow both script and module sourceTypes to be localized

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/watcher.ts
- yarn.lock
The experimental esbuild-based browser application builder now contains initial support for
watching input files and rebuilding the application via the `--watch` option. This initial
implemention is not yet optimized for incremental rebuilds and will perform a full rebuild
upon detection of a change. Incremental rebuild support will be added in followup changes
and will significantly improve the rebuild speed.
The `chokidar` npm package is used to perform the file watching which allows for native file-
system event based watching. Polling is also support via the `--poll` option for environments
that require it.
> feat(@angular-devkit/build-angular): add initial watch support to esbuild-based builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
- packages/angular_devkit/build_angular/src/utils/service-worker.ts
The initial global stylesheet, file replacement, index HTML, and service worker option analysis and cleanup has now been moved into the `normalizeOptions` helper for the esbuild-based browser application builder. This better organizes the option related setup steps as well as reduces the amount of code in the main builder source file.
> refactor(@angular-devkit/build-angular): move more esbuild option setup into normalize option helper

- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
- packages/schematics/angular/component/index_spec.ts
This commit removes the `constructor` and `ngOnInit` as most of the users prefer to add this manually if needed.
Closes #23678
> feat(@schematics/angular): remove `ngOnInit` from component template

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/esbuild.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
The experimental esbuild-based browser application builder will now support incremental JavaScript bundling when run in watch mode via the `watch` option. This initial implementation integrates the esbuild incremental rebuild functionality. TypeScript source file caching has also been added to improve the rebuild initialization time for the TypeScript and Angular compilation steps. This initial support is not yet fully optimized and additional work is planned to further improve the rebuild performance.
> feat(@angular-devkit/build-angular): add initial incremental code rebuilding to esbuild builder

- packages/angular_devkit/schematics/src/rules/call.ts
- packages/angular_devkit/schematics/src/rules/call_spec.ts
A `null` value is not considered a valid return value for a schematics Rule. Previously, this
would accidently be treated the same as a void return due to incomplete result checking.
However, recent refactoring caused the `null` case to fail with a non-obvious error message when
it should have failed with the existing `InvalidRuleResultException`. Non-tree result objects
including `null` will now fail with `InvalidRuleResultException`.
> fix(@angular-devkit/schematics): throw more relevant error when Rule returns invalid null value

- CHANGELOG.md
> docs: release notes for the v14.2.5 release

- packages/angular/cli/src/command-builder/schematics-command-module.ts
Remove interim handling of `"format": "path"`. workingDirectory smart default provider should be used instead.
> refactor(@angular/cli): remove leftover schematics path handling

- packages/angular/cli/src/commands/update/cli.ts
- packages/angular/cli/src/utilities/package-metadata.ts
In the case when `ng update` is ran without a package name, an update is not be performed. In this case using the current installed version of the CLI is good enough.
Closes #24024
> fix(@angular/cli): skip downloading temp CLI when running `ng update` without package names

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
Update the build time calculation for the experimental esbuild-based browser application builder to use the `process.hrtime` time source.  The high resolution time provides a more accurate time source and allows for nanosecond level timings if needed.  Currently the console output is rounded to the nearest millisecond. Future performance monitoring capabilities may leverage the more fine-grained values.
> refactor(@angular-devkit/build-angular): use high resolution time for esbuild builder completion time

- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/utility/latest-versions/package.json
This commit drops support for TypeScript 4.6 and 4.7
BREAKING CHANGE: TypeScript versions older than 4.8.2 are no longer supported.
> feat: drop support for TypeScript 4.6 and 4.7

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/schema.json
This option is useful to create an application outside of the `newProjectRoot`.
Related to https://github.com/angular/angular-cli/pull/23994
> feat(@schematics/angular): mark `projectRoot` as non hidden option in application schematic

- packages/angular/cli/src/utilities/completion.ts
This change updates the `hasGlobalCliInstall` logic so that a pending promise is not created.
Closes #23997
> fix(@angular/cli): handle missing `which` binary in path

- packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
- packages/angular_devkit/build_angular/src/builders/app-shell/render-worker.ts
When generating an app-shell via the app-shell builder, the server application rendering will now take place within a Node.js Worker. Since the rendering requires the presence of Zone.js, this change allows for the Zone.js patching to be isolated from the remainder of the builder and Angular CLI code. This prevents Zone.js from persisting past the needed render operation. This also allows for a workaround to a Zone.js/Node.js v18 problem where the TypeScript dynamic import workaround involving the Function constructor to ensure a native dynamic import expression will cause a failure when running on Node.js v18.10.
> fix(@angular-devkit/build-angular): isolate zone.js usage when rendering server bundles

- packages/angular_devkit/schematics/src/tree/recorder_spec.ts
- packages/angular_devkit/schematics/src/utility/environment-options.ts
- packages/angular_devkit/schematics/src/utility/linked-list.ts
- packages/angular_devkit/schematics/src/utility/update-buffer.ts
- packages/angular_devkit/schematics/src/utility/update-buffer_spec.ts
Reverts angular/angular-cli#24035
Reverting as this breaks Angular material schematics in a number of ways.
See: https://angular-team.slack.com/archives/C46U16D4Z/p1665219000524689
> Revert "refactor(@angular-devkit/schematics): remove `UpdateBuffer` and rename `UpdateBuffer2` to `UpdateBuffer`"

- packages/ngtools/webpack/src/ivy/plugin.ts
The Angular compiler's `incrementalDriver` property has been renamed to `incrementalCompilation`. To facilitate the removal of the old property, the `@ngtools/webpack` package now uses the new name for the property.
> refactor(@ngtools/webpack): use new name of Angular compiler incremental compilation property

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
This commits adds a warning similar to that in the Webpack builder.
> fix(@angular-devkit/build-angular): show warning when using TypeScript target older then ES2022 in esbuild builder

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- tests/legacy-cli/e2e/tests/build/styles/scss-partial-resolution.ts
Prior to this change non relative partial files were not resolved properly. Example we did not try to resolve `@material/button/button` as `@material/button/_button` which caused the compilation to fail.
> fix(@angular-devkit/build-angular): correctly resolve Scss partial files in node packages

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/profiling.ts
When using the experimental esbuild-based browser application builder, the Angular diagnostic analysis performed per rebuild is now reduced to only the affected files for that rebuild. A rebuild will now query the TypeScript compiler and the Angular compiler to determine the list of potentially affected files. The Angular compiler will then only be queried for diagnostics for this set of affected files instead of the entirety of the program.
> perf(@angular-devkit/build-angular): minimize Angular diagnostics incremental analysis in esbuild-based builder

- packages/angular_devkit/build_angular/BUILD.bazel
This is no longer the case and thus this test can be enabled.
> test: remove `node16-broken` from app-shell unit test

- packages/angular_devkit/build_angular/src/builders/karma/find-tests-plugin.ts
Some libraries ship spec in node_modules which might result errors such
```
./node_modules/comment-parser/tests/unit/spacer-description-joiner.spec.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: /Users/kkostadinov/Projects/material.angular.io/node_modules/comment-parser/tests/unit/spacer-description-joiner.spec.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
```
> fix(@angular-devkit/build-angular): ignore specs in node_modules when finding specs

- CHANGELOG.md
- package.json
The previous "next" release-train has moved into the feature-freeze phase. This PR updates the next branch to the subsequent release-train.
Also this PR cherry-picks the changelog for v15.0.0-next.5 into the main branch so that the changelog is up to date.
> Update next branch to reflect new release-train "v15.1.0-next.0".

- CHANGELOG.md
> docs: release notes for the v14.2.6 release

- goldens/public-api/angular_devkit/build_angular/index.md
- packages/angular_devkit/build_angular/src/builders/karma/index.ts
Karma is an optional peer dependency, but with the recent changes we broke this as we imported karma outside of the execution method, which made this package to be always imported even when the Karma builder was not invoked.
> fix(@angular-devkit/build-angular): only import karma when running karma builder

- .ng-dev/pull-request.mts
As part of the labels standardization across repos these options has been removed.
> build: remove labels from pull-requests config

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/builders/browser/specs/styles_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/vendor-source-map_spec.ts
- packages/angular_devkit/build_angular/src/builders/server/tests/options/source-map_spec.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
- packages/ngtools/webpack/src/resource_loader.ts
The `postcss-imports` package was previously used to support `@import` within CSS files. Unfortunately, the package does not account for `package.json` exports fields. This prevents imports defined within that field from working when used within a build.  The `css-loader` package does provide this functionality and is now used to provide support for CSS `@import` instead of `postcss-imports`. This change does not affect preprocessors that provide their own import behavior.
> fix(@angular-devkit/build-angular): account for package.json exports fields with CSS import statements

- goldens/public-api/angular_devkit/core/index.md
- packages/angular_devkit/core/src/logger/logger.ts
`typeof Promise` and `PromiseConstructorLike` are not the same thing. This causes issues in G3 when `strictNullChecks` are being enabled using RXJS 7.
https://github.com/ReactiveX/rxjs/blob/afac3d574323333572987e043adcd0f8d4cff546/src/internal/Observable.ts#L311-L313
FYI @gunan
> fix(@angular-devkit/core): update logger `forEach` `promiseCtor` type

- packages/angular_devkit/build_angular/package.json
`@angular/platform-server` is now an optional peer dep due to the recent changes in https://github.com/angular/angular-cli/blob/1cd53d6be17d6199b6af74a5a1686b3cb8f52268/packages/angular_devkit/build_angular/src/builders/server/index.ts#L182
> fix(@angular-devkit/build-angular): add `@angular/platform-server` as an optional peer dependency

- packages/angular/cli/src/analytics/analytics.ts
- tests/legacy-cli/e2e/tests/commands/analytics/analytics-enable-disable.ts
- tests/legacy-cli/e2e/tests/commands/analytics/analytics-info.ts
- tests/legacy-cli/e2e/tests/commands/analytics/ask-analytics-command.ts
Prior to this change we collected analytics when config was not present and the CLI was running in non TTY mode.
**Note**: this only effects `15.0.0-next.5` package.
> fix(@angular/cli): do not collect analytics when running in non TTY mode

- packages/angular_devkit/build_angular/src/sass/sass-service.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
Enhanced resolver is unable to resolve transitive dependencies in Sass when using Yarn PNP. The main reason for this is that Sass doesn't provide context on which file is requesting the module. See: https://github.com/sass/sass/issues/3247.
As a workaround for this we store previously resolved paths and when a new request comes in we try to resolve this from the previously resolved files if we are unable to resolve the request from the workspace root.
> fix(@angular-devkit/build-angular): resolve transitive dependencies in Sass when using Yarn PNP

- CHANGELOG.md
> docs: release notes for the v15.0.0-next.6 release

- packages/angular_devkit/build_angular/test/hello-world-app/src/tsconfig.app.json
- packages/angular_devkit/build_angular/test/hello-world-app/src/tsconfig.server.json
- packages/angular_devkit/build_angular/test/hello-world-app/src/tsconfig.spec.json
- packages/schematics/angular/universal/files/root/tsconfig.server.json.template
- packages/schematics/angular/universal/index_spec.ts
The `@angular/localize` entrypoint now exposes the global `$localize` method type.
See: https://github.com/angular/angular/pull/47763
> fix(@schematics/angular): add `@angular/localize` as type when localize package is installed

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/profiling.ts
To further improve incremental rebuild performance of the experimental esbuild-based browser
application builder, the output of the TypeScript file loader within the Angular compiler plugin
are now cached in memory by the input file name and invalidated via the file watching events.
This allows an additional TypeScript emit including the associated transformations per input file
to be avoided if the file has not changed or has not been affected by other files within the
TypeScript program.
> perf(@angular-devkit/build-angular): avoid extra TypeScript emits with esbuild rebuilds

- packages/angular/cli/src/commands/analytics/cli.ts
- packages/angular/cli/src/commands/analytics/long-description.md
- packages/angular/cli/src/commands/config/long-description.md
- tests/legacy-cli/e2e/tests/commands/help/help-json.ts
With this change we add a long description to analytics command with the information that is currently contain in https://angular.io/analytics which will be deleted at a later stage.
> docs(@angular/cli): update add long description to analytics command

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/typescript.ts
https://angular.io/guide/build#configuring-browser-compatibility will be updated to include additional information.
> docs: replace browserslist with AIO link

- packages/angular/cli/lib/init.ts
This causes sub broken DX
```
ng bui[TAB]Your global Angular CLI version (14.2.6) is greater than your local version (14.1.3). The local Angular CLI version is used.
To disable this warning use "ng config -g cli.warnings.versionMismatch false".
ld --conf[TAB]Your global Angular CLI version (14.2.6) is greater than your local version (14.1.3). The local Angular CLI version is used.
To disable this warning use "ng config -g cli.warnings.versionMismatch false".
iguration dev[TAB]Your global Angular CLI version (14.2.6) is greater than your local version (14.1.3). The local Angular CLI version is used.
To disable this warning use "ng config -g cli.warnings.versionMismatch false".
elopment
```
Closes #24133
> fix(@angular/cli): disable version check during auto completion

- packages/schematics/angular/library/files/package.json.template
- packages/schematics/angular/library/index_spec.ts
This PR is related to #24122. It introduces the `sideEffects: false` flag to the `package.json` of libraries generated with `ng generate library`.
> feat(@schematics/angular): add sideEffects:false to library package.json

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
The experimental esbuild-based browser application builder will now avoid trying to query the Angular Compiler for template diagnostics when a TypeScript source file is a declaration file (`.d.ts`). This avoids the overhead of the in-memory diagnostics caching logic as well as any Angular Compiler logic to determine if the file has any template diagnostics.
> perf(@angular-devkit/build-angular): avoid template diagnostics for declaration files in esbuild builder

- packages/angular/cli/src/commands/add/cli.ts
When the CLI is a prerelease version, the `ng add` command will now consider the
use of prerelease versions of requested packages. Without this behavior, attempting
to install a package without a version specifier (e.g., `ng add @angular/material`)
will install an older stable version of the requested package instead of the expected
prerelease version compatible with the prerelease Angular project.
> fix(@angular/cli): allow ng add to find prerelease versions when CLI is prerelease

- packages/angular_devkit/core/src/logger/logger.ts
Some build environments build angular with rxjs 7, and see build failures due to this file.
> refactor: Make Logger.forEach compatible with both rxjs 6 and 7.

- packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
The dev-server builder currently does not support the experimental esbuild-based browser application builder and will use the Webpack-based builder instead. To better inform users of this behavior, a warning is now issued upon executing the dev-server.
> fix(@angular-devkit/build-angular): issue dev-server support warning when using esbuild builder

- packages/schematics/angular/universal/files/root/tsconfig.server.json.template
- packages/schematics/angular/universal/index_spec.ts
This is no longer needed due to the recent changes in the CLI which always use ES2022.
> fix(@schematics/angular): remove TypeScript target from universal schematic

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
When using the experimental esbuild-based browser application builder in watch mode, the base cache path defined within the `angular.json` file will now be ignored when detecting file changes. While the builder currently does not persist cache to disk, it may in the future and other builders may currently be run in parallel.
> fix(@angular-devkit/build-angular): ignore cache path when watching with esbuild builder

- CHANGELOG.md
> docs: release notes for the v14.2.7 release

- CHANGELOG.md
> docs: release notes for the v15.0.0-rc.1 release

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
The warning text note for the TypeScript target was incorrectly escaped within a template literal which resulted in a badly formatted error message.
> fix(@angular-devkit/build-angular): correct escaping of target warning text in esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/watcher.ts
When using the experimental esbuild-based browser application builder in watch mode, the file watcher will now wait 250ms from a reported file event before triggering a rebuild. The change allows the rebuild to better capture groups of file changes. This can happen when using an IDE while editing multiple files and would otherwise result in multiple rebuilds where a single rebuild would be ideal.
> fix(@angular-devkit/build-angular): wait during file watching to improve multi-save rebuilds for esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
- packages/angular_devkit/build_angular/src/sass/sass-service.ts
- packages/angular_devkit/build_angular/src/sass/worker.ts
When using the experimental esbuild-based browser application builder, Sass stylesheets will now be processed using a worker pool that is currently also used by the default Webpack-based builder. This allows up to four stylesheets to be processed in parallel and keeps the main thread available for other build tasks. On projects with a large amount of Sass stylesheets, this change provided up to a 25% improvement in build times based on initial testing.
> perf(@angular-devkit/build-angular): use Sass worker pool for Sass support in esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
V8 currently has a performance defect involving object spread operations that can cause degradation
in runtime performance. By specifically not supporting the object spread language feature when using
the esbuild-based browser application builder, a downlevel form will be used instead which provides a
workaround for the performance issue. The downlevel form can cause up to a 600 byte increase in file
size if an object spread operation would otherwise be present in an output file.
For more details: https://bugs.chromium.org/p/v8/issues/detail?id=11536
> fix(@angular-devkit/build-angular): provide workaround for V8 object spread performance defect

- packages/schematics/angular/guard/files/__name@dasherize__.guard.ts.template
- packages/schematics/angular/guard/index.ts
- packages/schematics/angular/guard/index_spec.ts
- packages/schematics/angular/guard/schema.json
The `CanMatch` guard was added in v14.1 but not added to the list of possible interfaces to implement.
This commit adds `CanMatch` to the list of possible interfaces to implement. It has the same type imports as the CanLoad interface.
To reviewers: Should this be a feat instead?
> fix(@schematics/angular): guard schematics should include all guards (CanMatch)

- CHANGELOG.md
> docs: release notes for the v14.2.8 release

- CHANGELOG.md
> docs: release notes for the v15.0.0-rc.2 release

- goldens/public-api/angular_devkit/core/node/index.md
- packages/angular_devkit/core/node/host.ts
This reduces the number of imports for the Node.js file host classes. The `fs` default import was only used in one place and named imports were already in use for `node:fs` which allowed the one use to be converted to a named import. The type only import for `chokidar` was also only used in one type annotation and was moved to the type annotation directly.
> refactor(@angular-devkit/core): remove unneeded import statements from Node.js file host

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
When using the experimental esbuild-based browser application builder, Sass module imports will now resolve using esbuild's resolve methods. This allows for package.json exports and main fields to be recognized when resolving an import or use rules in Sass files (scss or sass file extensions).
> fix(@angular-devkit/build-angular): account for package.json exports with Sass in esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
- packages/angular_devkit/build_angular/src/sass/rebasing-importer.ts
- packages/angular_devkit/build_angular/src/sass/sass-service.ts
- packages/angular_devkit/build_angular/src/sass/worker.ts
When using the experimental esbuild-based browser application builder with Sass, paths contained in `url()` CSS functions will now be rebased to reflect their final location relative to the output of the Sass compiler. This allows the bundler to locate and process any resource files such as images or fonts used within the stylesheet.
The implementation of the rebasing functionality uses a series of custom Sass importers to transform the input stylesheets (from import or use rules) when they are loaded from the file system. However, for the Sass compiler to use the load functionality of an importer, the `canonicalize` function (used to resolve an import) of the same importer must return a resolved path to the requested stylesheet. To support this requirement, all stylesheet resolution has …
> fix(@angular-devkit/build-angular): rebase Sass url() values when using esbuild-based builder

- packages/angular_devkit/build_angular/src/builders/server/index.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/webpack/utils/helpers.ts
This commit fixes an issue where `@angular/platform-server/init` was added as an entry-point during the server build even when this was not installed.
Closes #24188
> fix(@angular-devkit/build-angular): only add `@angular/platform-server/init` when package is installed.

- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/sass/rebasing-importer.ts
- packages/angular_devkit/build_angular/src/sass/sass-service.ts
- packages/angular_devkit/build_angular/src/sass/worker.ts
When using the experimental esbuild-based browser application builder with Sass and sourcemaps, the final sourcemap for an input Sass stylesheet will now contain the original content for any `url` functions that were rebased to support bundling. This required generating internal intermediate source maps for each imported stylesheet that was modified with rebased URLs and then merging these intermediate source maps with the final Sass generated source map. This process only occurs when stylesheet sourcemaps are enabled.
> fix(@angular-devkit/build-angular): update sourcemaps when rebasing Sass url() functions in esbuild builder

- packages/angular_devkit/architect/src/create-builder.ts
Currently, if an architect builder does not provide any results, the CLI will crash trying to access an error message property on the result. Instead architect will now provide a default failure result `{ success: false }` in the event that the builder exits prior to generating a result. Thrown errors continue to be propagated as before.
> fix(@angular-devkit/architect): default to failure if no builder result is provided

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/css-resource-plugin.ts
When using the experimental esbuild-based browser application builder, `url()` functions within stylesheets will no longer cause a build failure due to an attempted local file resolution of URLs that do not represent on-disk resources. This includes absolute, protocol-relative, and root-relative URLs as well as SVG path identifiers.
> fix(@angular-devkit/build-angular): avoid attempted resolve of external CSS URLs with esbuild builder

- CHANGELOG.md
> docs: release notes for the v14.2.9 release

- CHANGELOG.md
> docs: release notes for the v15.0.0-rc.3 release

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
The `supports` query was added in version `4.13`, while `^4.9.1` does match this version is some cases an older version might be used to the presence of a lock file during the update which would cause the package not to be update.
Closes #24212
> fix(@angular-devkit/build-angular): update browerslist package

- packages/angular/cli/src/utilities/package-metadata.ts
- tests/legacy-cli/e2e/tests/update/update-secure-registry.ts
This commit fixes an issue where when `ng update` was ran using `yarn` (`yarn ng update`) the registry was always being overridden to `https://registry.yarnpkg.com`.
This is because yarn will set the `npm_config_registry` env variable to `https://registry.yarnpkg.com` even when an RC file is present with a different repository.
reported by @JoostK and @SanderElias over slack.
> fix(@angular/cli): respect registry in RC when running update through yarn

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/esbuild.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
When using the experimental esbuild-based browser application builder in watch mode, global stylesheets
configured with the `styles` option will now use the incremental rebuild mode of esbuild. This allows
for a reduction in processing when rebuilding the global styles. CSS stylesheets benefit the most currently.
Sass stylesheets will benefit more once preprocessor output caching is implemented.
> perf(@angular-devkit/build-angular): add initial global styles incremental rebuilds with esbuild builder

- CHANGELOG.md
> docs: release notes for the v15.0.0-rc.4 release

- goldens/public-api/angular_devkit/build_angular/index.md
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
- packages/angular_devkit/build_angular/src/builders/browser/schema.json
- packages/angular_devkit/build_angular/src/builders/server/schema.json
- packages/schematics/angular/migrations/update-15/update-workspace-config.ts
- packages/schematics/angular/migrations/update-15/update-workspace-config_spec.ts
- packages/schematics/angular/universal/index.ts
With this change we add the `vendorChunk` option in the server builder. This option should only be used in development as it is intended to be used to improve the incremental re-build time.
This improves the rebuild time as Webpack will have less modules to analyse during a change in the application. Below, we can see the impact this change has in a `ng new` application.
Without vendor chunking
```
$ ng run ssr-vendor:server:development --watch --no-vendor-chunk
Build at: 2022-11-14T08:42:27.089Z - Hash: 0325905b63e43ddb - Time: 15357ms
Build at: 2022-11-14T08:42:37.565Z - Hash: 05cb180a02524656 - Time: 2498ms
Build at: 2022-11-14T08:42:40.325Z - Hash: c5a6996ed1924088 - Time: 1862ms
Build at: 2022-11-14T08:42:43.043Z - Hash: 92ce99f38a769c19 - Time: 1516ms
```
With vendor chunking
```
$ …
```
> perf(@angular-devkit/build-angular): add vendor chunking to server builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular-host.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
The creation of the esbuild Angular plugin's Angular compiler host has now been consolidated in a separate function. This refactor reduces the amount of code within the plugin's main start function as well as centralizing all initialization of the host into one location.
> refactor(@angular-devkit/build-angular): move esbuild angular compiler host creation to separate function

- CHANGELOG.md
> docs: release notes for the v15.0.0-rc.5 release

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
`loader-utils` is vulnerable to Regular Expression Denial of Service (ReDoS) via url variable.
See: https://github.com/advisories/GHSA-3rfm-jhwj-7488
Closes #24241
> fix(@angular-devkit/build-angular): update `loader-utils` to `3.2.1`

- packages/angular/cli/lib/init.ts
In some cases orphan `node_modules` would cause the non global CLI to be used to generate a new workspace.
Closes #14603
> fix(@angular/cli): use global version of the CLI when running `ng new`

- CHANGELOG.md
> docs: release notes for the v14.2.10 release

- CHANGELOG.md
> docs: release notes for the v13.3.10 release

- docs/process/release.md
> docs: updates release documentation to include `latest-versions/package.json` and clarify what can be done in the release PR

- .circleci/dynamic_config.yml
This workflow is used by circle ci scheduled pipelines which is required to create a cron job when using dynamic configurations.
See: https://circleci.com/docs/scheduled-pipelines/?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--emea-en-dsa-maxConv-auth-nb&utm_term=g_-_c__dsa_&utm_content=&gclid=Cj0KCQiA1NebBhDDARIsAANiDD2Ja2WCBYtxifWx9d8uD2bEZzDjtO4mB2aq7fEtvoUKZZ8GeQbeNtgaAoW5EALw_wcB and https://app.circleci.com/settings/project/github/angular/angular-cli/triggers?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fangular%2Fangular-cli&triggerSource=&scheduledTriggerId=8e3e6898-fd55-41b1-a3e8-85c52981d941&success=true
> ci: create daily_run_workflow for 14.2.x branch

- packages/angular_devkit/build_angular/src/sass/rebasing-importer.ts
- packages/angular_devkit/build_angular/src/sass/worker.ts
When performing Sass import resolution within the experimental esbuild-based browser application builder, the directory cache entries will now be preprocessed during the first directory search operation. This will allow a more streamlined search operation on later resolution attempts for the same directory. The caching is still limited to sharing per render request but this change provides for cache entries that can more easily be serialized and shared between workers in the future.
> refactor(@angular-devkit/build-angular): preprocess Sass resolve cache entries in esbuild Sass plugin

- packages/schematics/angular/migrations/update-15/update-typescript-target.ts
Prior to this change an error was shown when a non existing tsconfig was referenced in the angular.json. This causes the update to fail.
Closes #24264
> fix(@schematics/angular): show warning when a TS Config is not found during migrations

- tests/legacy-cli/e2e/tests/update/update-multiple-versions.ts
During releases, there is a brief time where `@angular/core` has released the next version, but `@angular/cli` has not. This test currently fails in such a situation because `@angular/cli` wasn't new enough to trigger the multiple versions upgrade. This fix upgrades `@angular/core` instead, so it will always be consistent.
This file on `15.0.x` slightly diverged from `main` in https://github.com/angular/angular-cli/pull/24249, so https://github.com/angular/angular-cli/pull/24270 applies the same change there to avoid a merge conflict.
> ci: fix update test to work when `@angular/cli` and `@angular/core` majors diverge

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
This dependency is no longer needed since we no longer generate es5 output.
> build: remove `regenerator-runtime` from dependencies

- goldens/public-api/angular_devkit/build_angular/index.md
- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/server/index.ts
- packages/angular_devkit/build_angular/src/builders/server/schema.json
- packages/angular_devkit/build_angular/src/builders/server/tests/options/assets_spec.ts
- packages/angular_devkit/build_angular/src/builders/server/tests/options/resources-output-path_spec.ts
- packages/angular_devkit/build_angular/src/builders/server/tests/setup.ts
- packages/angular_devkit/build_angular/src/utils/normalize-asset-patterns.ts
- packages/angular_devkit/build_angular/test/hello-world-app/src/tsconfig.server.json
This commits adds the `assets` option to the server builder. This can be useful to copy server specific assets such as config files.
Closes #24203
> feat(@angular-devkit/build-angular): add `assets` option to server builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer-worker.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer.ts
When using the experimental esbuild-based browser application builder, the JavaScript transformation steps of the build process will now be performed within a worker pool to allow for the steps to be executed in parallel when possible. This also moves the steps off of the main thread which provides more time for the build orchestration and esbuild integration code to execute.
> perf(@angular-devkit/build-angular): use worker pool for JavaScript transforms in esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
When resolving Sass imports in the experimental esbuild-based browser application builder's Sass plugin, previously imported modules are used as the base for resolution attempts to workaround the lack of the importer file provided by Sass. When attempting to resolve a deep import into a package (including the potential Sass index files), these previously imported modules also need to be checked. This is particularly relevant when using the Yarn PnP or pnpm package managers which enforce strict dependency resolution.
Fixes #24271
> fix(@angular-devkit/build-angular): improve package deep import Sass index resolution in esbuild plugin

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular-compilation.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
The creation of the esbuild Angular plugin's Angular compilation has now been consolidated in a separate class. This refactor reduces the amount of code within the plugin's main start function as well as centralizing initialization, analysis, and source file emitting for the Angular build process.
> refactor(@angular-devkit/build-angular): encapsulate Angular compilation within esbuild compiler plugin

- packages/angular_devkit/build_angular/src/sass/rebasing-importer.ts
When rebasing URLs found within Sass files (sass/scss), the previous regular expression based searching has been replaced with a lexer that scans the Sass files for CSS url() functions and extracts URL values. This change allows for more accurate discovery of URLs as well as reducing the amount of content traversals per file. The lexer logic is based on CSS Syntax Module Level 3 (https://www.w3.org/TR/css-syntax-3/).
Fixes #24245
> fix(@angular-devkit/build-angular): use url function lexer to rebase Sass URLs

- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Similar to errors messages we now hide webpack paths in warnings to reduce clutter.
Before
```
./src/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].rules[1].use[1]!./src/styles.scss?ngGlobalStyle - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation $weight: Passing a number without unit % (60) is deprecated.
To preserve current behavior: $weight * 1%
More info: https://sass-lang.com/d/function-units
@material/slider/_slider-theme.scss 77:5 …
```
> fix(@angular-devkit/build-angular): hide loader paths in webpack warnings

- packages/angular_devkit/build_angular/src/sass/rebasing-importer.ts
When rebasing URLs found within Sass files (sass/scss), the previous regular expression based searching has been replaced with a lexer that scans the Sass files for CSS url() functions and extracts URL values. This change allows for more accurate discovery of URLs as well as reducing the amount of content traversals per file. The lexer logic is based on CSS Syntax Module Level 3 (https://www.w3.org/TR/css-syntax-3/).
(cherry picked from commit 84dc05d28abdecf9312d91931d155139f1e8ff1f)
> [15.0.x] fix(@angular-devkit/build-angular): use url function lexer to rebase Sass URLs

- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Similar to errors messages we now hide webpack paths in warnings to reduce clutter.
Before
```
./src/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].rules[1].use[1]!./src/styles.scss?ngGlobalStyle - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation $weight: Passing a number without unit % (60) is deprecated.
To preserve current behavior: $weight * 1%
More info: https://sass-lang.com/d/function-units
@material/slider/_slider-theme.scss 77:5 …
```
> [15.0.x] fix(@angular-devkit/build-angular): hide loader paths in webpack warnings

- CHANGELOG.md
> docs: release notes for the v15.0.1 release

- packages/schematics/angular/guard/type-files/__name@dasherize__.guard.spec.ts.template
It is unnecessary now that the spec uses `runInInjectionContext` 
The resolver spec does not have this issue as the import was missing in the spec in the first place.
> fix(@schematics/angular): remove EnvironmentInjector import in functional guard spec

- packages/schematics/angular/guard/type-files/__name@dasherize__.guard.spec.ts.template
The current functional guard generates:
```ts
const executeGuard: CanActivateFn = ...
it('should be created', () => {
expect(fooGuard).toBeTruthy();
});
```
with `fooGuard` the guard not run in injection context
```ts
const executeGuard: CanActivateFn = ...
it('should be created', () => {
expect(executeGuard).toBeTruthy();
});
```
> fix(@schematics/angular): use proper variable in functional guard spec

- packages/angular/create/README.md
Reverts angular/angular-cli#23590 as the fix has landed in NPM v8.15.1
Closes #24341
> Revert "docs: remove `@latest` reference from `npm init` command"

- CHANGELOG.md
> docs: release notes for the v15.0.2 release

- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
When optimization is enabled with the `@angular-devkit/build-angular:browser` builder, terser is used as a second phase optimizer. The terser configuration previously set its `ecma` option to `es2020` due to all officially supported browsers supporting the version. However, it is possible to add browsers to the browserslist configuration that are not officially supported that still may work but do not support es2020 syntax features. By setting the terser `ecma` option to `es2015`, terser will not turn existing syntax into newer syntax features that might be unsupported. Terser will also not downlevel any code based on this option.
Fixes #24347
> fix(@angular-devkit/build-angular): prevent optimization adding unsupported ECMASCript features

- packages/schematics/angular/guard/type-files/__name@dasherize__.guard.ts.template
- packages/schematics/angular/interceptor/functional-files/__name@dasherize@if-flat__/__name@dasherize__.interceptor.ts.template
- packages/schematics/angular/resolver/functional-files/__name@dasherize__.resolver.ts.template
The new functional entities are constants, and there is no semicolon at the end of their declaration
Maybe that was a deliberate choice, but we usually have semicolons in the generated code from the CLI
> fix(@schematics/angular): add missing semicolon in functional guard/resolver/interceptor

- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- tests/legacy-cli/e2e/tests/misc/safari-15-class-properties.ts
The Angular compiler is dependent on static fields being attached to
user-defined classes. e.g. `static ecmp = defineComponent`.
These static fields sometimes rely on variables from outside of the
class. e.g. the Angular compiler generates constants for content
projection that are then accessed in the static field initializer.
Surprisingly such access to these variables may break in Safari <=v15
when a page is loaded without devtools open. The bug (already solved in
v16 of Safari)- is very subtle, hard to re-reproduce but basically
variable scope tracking is broken. This bug is triggered by additional
parenthesis in the initializer expression. See:
https://bugs.webkit.org/show_bug.cgi?id=236843.
The TypeScript compiler may generate such additional parenthesis when
it tries to adjust the …
> fix(@angular-devkit/build-angular): downlevel class properties when targeting Safari <=v15

- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
- packages/angular_devkit/build_angular/src/utils/index-file/html-rewriting-stream.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
This PR converts `transformedContent` into a function to give more control when the readable stream is initialized. There might be issues with late "subscribers" where events are added after the readable stream was initialized and the data was already pushed, e.g.
```ts
const { rewriter } = await htmlRewritingStream('<div />');
setTimeout(() => {
rewriter.on('startTag', (tag) => {
console.log(tag);
});
})
```
This will not work and potentially wait indefinitely. I have ran into such issue with WebContainer on stackblitz.com.
With this change the stream now needs to be explicitily initialized:
```ts
const { rewriter, transformedContent } = await htmlRewritingStream('<div />');
setTimeout(() => {
rewriter.on('startTag', (tag) => {
console.log(tag);
});
// calling this function will create …
```
> refactor(@angular-devkit/build-angular): convert `transformedContent` into a function

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/utils/esbuild-targets.ts
To provide a workaround for a Safari bug involving class fields and variable scoping,
the esbuild-based browser application builder will now downlevel class fields if Safari
(desktop or iOS) v15.x or earlier is within the target browsers for an application.
This is an esbuild variant of the fix for the Webpack-based builder. For more details
regarding the issue, please see: https://github.com/angular/angular-cli/pull/24357
> fix(@angular-devkit/build-angular): downlevel class fields with Safari <= v15 for esbuild

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
When using the experimental esbuild-based browser application builder, the `preserveSymlinks` option will now default to the value of the Node.js `--preserve-symlinks` argument. This removes the need to manually specify the option in two places if executing the build manually with Node.js or via the `NODE_OPTIONS` environment variable. This behavior mimics that of the default Webpack-based builder.
> fix(@angular-devkit/build-angular): default preserve symlinks to Node.js value for esbuild

- CHANGELOG.md
> docs: release notes for the v15.0.3 release

- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
This commits enables `sourceMapIncludeSources` when using the modern Sass API so that sources are included in generated source map.
Closes #24394
> fix(@angular-devkit/build-angular): include sources in generated Sass source maps

- packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
This commit changes how we set the `LOCALE_ID` when using the `localize` option
- We now include the locale setting snippet only in the main bundle.
- We use `globalThis` to set the the value globally and be accessible across module boundaries. This is important as in some causes such as when using MF `@angular/core` can be located in a bundles others than `main` and `vendor`.
FYI: @Coly010
> fix(@angular-devkit/build-angular): update locale setting snippet to use `globalThis`.

- packages/angular_devkit/build_angular/src/builders/karma/tests/options/styles_spec.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/styles-webpack-plugin.ts
Prior to this change the the error was not displayed correctly due to compilation being undefined.
Closes #24416
> fix(@angular-devkit/build-angular): display actionable error when a style does not exist in Karma builder

- packages/schematics/angular/collection.json
- packages/schematics/angular/environments/index.ts
- packages/schematics/angular/environments/index_spec.ts
- packages/schematics/angular/environments/schema.json
A schematic has been added that will allow the generation of environment files for all existing build configurations within a project. The `fileReplacements` option will also be setup to allow the replacement of the appropriate environment file. Environment files themselves do not provide any special behavior beyond that of other application TypeScript files and rely on the `fileReplacements` option for build-time behavior. The schematic will skip generating environment files for configurations that already have an appropriately named environment file. The `fileReplacements` option addition will also be skipped if an appropriate entry is already present.
Closes #24381
> feat(@schematics/angular): add environments generation schematic

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
When using the experimental esbuild-based browser application builder, the `inlineStyleLanguage` option and the usage of inline Angular component styles that contain Sass are now supported. The `inlineStyleLanguage` option values of `css`, `sass`, and `scss` can be used and will behave as they would with the default Webpack-based builder. The less stylesheet preprocessor is not yet supported in general with the esbuild-based builder. However, when support is added for less, the `inlineStyleLanguage` option will also be able to be used with the `less` option value.
> feat(@angular-devkit/build-angular): support inline component Sass styles with esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
When using the experimental esbuild-based browser application builder, the `ngDevMode` global runtime variable was unintentionally always being set to false due to a previous bug fix that stopped the variable from being replaced with the value of true when script optimizations were disabled. By doing so, the fix caused the imported compiler-cli `GLOBAL_DEFS_FOR_TERSER_WITH_AOT` constant to take precedence which contains an `ngDevMode` value of false. To prevent this situation for development builds where a non-false `ngDevMode` is helpful to surface potential runtime problems, `GLOBAL_DEFS_FOR_TERSER_WITH_AOT` will no longer change the value of `ngDevMode`. This fix does not have any effect on production builds since `ngDevMode` would have been set to false regardless.
> fix(@angular-devkit/build-angular): only set ngDevMode when script optimizations are enabled

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer-worker.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer.ts
When using the experimental esbuild-based browser application builder, async generator class methods will now be transformed to a downlevel form based on promise objects. This transformation is performed by babel and was previously (and still is) performed on async generator functions. This transformation is necessary to ensure Zone.js can hook async code via the Promise objects. Only async generator transformation is currently performed via babel as esbuild can handle all other native async syntax that requires transformation for Zone.js support.
> fix(@angular-devkit/build-angular): transform async generator class methods for Zone.js support

- CHANGELOG.md
> docs: release notes for the v15.0.4 release

- packages/ngtools/webpack/src/transformers/replace_resources.ts
Support for TypeScript 4.7 was dropped in Angular version 15. These changes remove some code that was used for backwards compatibility.
> refactor(@ngtools/webpack): remove TypeScript 4.7 compatibility code

- packages/schematics/angular/README.md
- packages/schematics/angular/class/schema.json
- packages/schematics/angular/component/schema.json
- packages/schematics/angular/directive/schema.json
- packages/schematics/angular/e2e/schema.json
- packages/schematics/angular/enum/schema.json
- packages/schematics/angular/guard/schema.json
- packages/schematics/angular/interceptor/schema.json
- packages/schematics/angular/interface/schema.json
- packages/schematics/angular/module/schema.json
- packages/schematics/angular/pipe/schema.json
- packages/schematics/angular/resolver/schema.json
- packages/schematics/angular/service/schema.json
- packages/schematics/angular/web-worker/schema.json
The default project is deprecated.
> docs: remove default project from schematic description

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
When using the experimental esbuild-based browser application builder, the `--stats-json` option can now be used to create an esbuild metafile named `stats.json` in the output directory of the application. The metafile contents will contain information about the application JavaScript, global stylesheets, and the component stylesheets used by the Angular compiler. While the `--stats-json` option controls the output of the file onto the filesystem, the metafile data is internally always created to support the future integration of the bundle budget and console build stat output capabilities.
The metafile format follows the structure of the esbuild metafile format. Information regarding the file format can be found here: https://esbuild.github.io/api/#metafile
> feat(@angular-devkit/build-angular): implement stats-json option for esbuild builder

- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
Prior to this change esbuild errors during the javascript optimization phase in the Webpack builder were not being formatting properly which caused meaningful information to be lost.
Closes #24457
> fix(@angular-devkit/build-angular): format esbuild error messages to include more information

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
When using the esbuild-based browser application builder, the Sass compiler will attempt to resolve any relative load paths from the current working directory. However, the load paths from the `angular.json` file should always be relative to the location of the `angular.json` which is considered the workspace root. While the current working directory is typically also the workspace root, it is not required nor always the same. To resolve this potential mismatch, the load paths are now resolved from the workspace root prior to being passed to the Sass compiler.
> fix(@angular-devkit/build-angular): ensure Sass load paths are resolved from workspace root

- packages/angular_devkit/build_angular/src/builders/karma/index.ts
- packages/schematics/angular/collection.json
- packages/schematics/angular/config/files/.browserslistrc.template
- packages/schematics/angular/config/files/karma.conf.js.template
- packages/schematics/angular/config/index.ts
- packages/schematics/angular/config/index_spec.ts
- packages/schematics/angular/config/schema.json
- tests/legacy-cli/e2e/tests/generate/confg/type-browserslist.ts
- tests/legacy-cli/e2e/tests/generate/confg/type-karma.ts
This commits add a schematic to generate Karma and Browserlist files which since version 15 are no longer generated by default. This schematic should be used to generate these files when further customisation is needed.
Usage
```
ng generate config karma
ng generate config browserlist
```
Closes #24294
> feat(@schematics/angular): add configuration files generation schematic

- .circleci/dynamic_config.yml
- .ng-dev/release.mts
- package.json
- packages/angular/cli/BUILD.bazel
- packages/angular/create/BUILD.bazel
- packages/angular/pwa/BUILD.bazel
- packages/angular_devkit/architect/BUILD.bazel
- packages/angular_devkit/architect/node/BUILD.bazel
- packages/angular_devkit/architect_cli/BUILD.bazel
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_webpack/BUILD.bazel
- packages/angular_devkit/core/BUILD.bazel
- packages/angular_devkit/schematics/BUILD.bazel
- packages/angular_devkit/schematics_cli/BUILD.bazel
- packages/ngtools/webpack/BUILD.bazel
- packages/schematics/angular/BUILD.bazel
- scripts/build-packages-dist.mts
- tsconfig-build.json
- yarn.lock
When performing a release via the dev-infra `ng-dev` tooling, the release builds for the packages that will be published are now performed using bazel. Prior to this, the release builds were performed using a custom build script that programmatically invoked TypeScript APIs. The Bazel build and discovery process for the releasable packages is performed by a script that is based on the scripts from components and framework repositories. Several small modifications were performed to match the behavior and structure of the cli repository:
* Use of `packages` as the source root in the bazel query
* Use of `pkg_npm` rule in the bazel query
* Partial transition to …
> build: use bazel to perform release builds

- CHANGELOG.md
> docs: release notes for the v15.0.5 release

- tests/legacy-cli/e2e/tests/build/material.ts
- tests/legacy-cli/e2e/tests/commands/add/add-material.ts
- tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
The Material tests had to be disabled temporarily during the TS 4.9 update, because the peer dependency range didn't allow for `next` versions. Now that the range was expanded in https://github.com/angular/components/pull/26308, the tests should work again.
> build: re-enable material e2e tests

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
Within the experimental esbuild-based browser application builder, the internal paths for angular component stylesheets were being displayed in the esbuild metafile with a duplicate namespace prefix. This had no functional difference to the build output but it did make the paths in the metafile unnecessarily long and potentially confusing. The paths now only contain the prefix a single time. This also has the benefit of reducing the length of the filter regular expressions for the stylesheet plugins used for Angular component styles by not needing to match the namespace in the path in addition to the namespace option.
> refactor(@angular-devkit/build-angular): remove duplicate namespaces in esbuild manifest paths

- goldens/public-api/angular_devkit/build_angular/index.md
- packages/angular_devkit/build_angular/src/builders/karma/find-tests-plugin.ts
- packages/angular_devkit/build_angular/src/builders/karma/index.ts
- packages/angular_devkit/build_angular/src/builders/karma/schema.json
- packages/angular_devkit/build_angular/src/builders/karma/tests/options/exclude_spec.ts
With this change we add an `exclude` option to the Karma builder to provide a way to exclude certain specs from the compilation.
This is useful, when having integration, e2e and unit tests with the same suffix.
Closes #24472
> fix(@angular-devkit/build-angular): provide an option to `exclude` specs in Karma builder

- packages/angular/cli/src/commands/new/cli.ts
- packages/angular/cli/src/commands/new/long-description.md
This appears to have been deleted by mistake when we switched to Yargs.
> docs(@angular/cli): add ng new long description

- packages/schematics/angular/utility/json-file.ts
This is so that this can be used in the Universal repo which is not failing because the type is not available.
https://app.circleci.com/pipelines/github/angular/universal/4483/workflows/25535db2-4a9c-43b0-84a5-3a55071013c6/jobs/20263
> refactor: change `JSONFile` to private instead of internal

- .eslintignore
- .ng-dev/tsconfig.json
- scripts/json-help.ts
- tsconfig.json
General cleanup of the main repository `tsconfig.json` file that is used by the IDE and as a base for the build and test tsconfig files. This includes removal of options that contain default values and removal of no longer existing paths from several options. A project relative path in one of the development scripts was also fixed to use a relative path to be consist with all other paths.
> build: cleanup unneeded and/or default tsconfig options

- packages/angular_devkit/build_angular/src/utils/action-executor.ts
- packages/angular_devkit/build_angular/src/utils/bundle-inline-options.ts
- packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts
- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
The i18n inlining worker code was previously imported in several locations to allow reuse of the options object used to configure the worker. To prevent the worker code from being used outside of an actual worker, the options object definition is now located in a separate file and imported in both the worker and any other files that need to use the inlining options.
The unused worker bootstrap file was also removed since it was only need with the legacy unit testing setup which has been completely replaced.
> refactor(@angular-devkit/build-angular): remove direct import of i18n worker code

- packages/angular/cli/src/commands/update/cli.ts
This change remove the requirement for the `to` option to be provided when using the `from` option in conjunction with `migrate-only`.
Closes #24510
> fix(@angular/cli): remove `--to` option from being required when using `--from` in `ng update`

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/commonjs-checker.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/esbuild.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
When using the experimental esbuild-based browser application builder, input files
for the build will now be checked to determine if they are non-ESM modules. This
behavior is comparable to the existing behavior within the default Webpack-based browser.
Warnings will now be issued for any non-ESM modules (for example, CommonJS or UMD) when
script optimizations are enabled (typically production builds). ESM files can be tree-
shaken and otherwise optimized in ways that CommonJS files cannot which allows for
more optimized and smaller output bundle files.
If any allowed dependencies are provided via the `allowedCommonJsDependencies`
option, both the direct import and any deep imports of the dependency will be ignored
during the checks and no diagnostic will be generated for the dependency.
> feat(@angular-devkit/build-angular): support CommonJS dependency checking in esbuild

- package.json
- tools/defaults.bzl
- yarn.lock
This is to address `error Couldn't find match for "6cdf0f2153298b828934373cc068b6a0f9dcf098" in "refs/heads/main" for "https://github.com/angular/dev-infra-private-build-tooling-builds.git".` and `error Couldn't find match for "301673f54ebe816bbcf13fe503de105c5e5a6a9c" in "refs/heads/main" for "https://github.com/angular/dev-infra-private-ng-dev-builds.git"`
> build: update dev-infra packages

- package.json
- tools/defaults.bzl
- yarn.lock
This is to address `error Couldn't find match for "6cdf0f2153298b828934373cc068b6a0f9dcf098" in "refs/heads/main" for "https://github.com/angular/dev-infra-private-build-tooling-builds.git".` and `error Couldn't find match for "301673f54ebe816bbcf13fe503de105c5e5a6a9c" in "refs/heads/main" for "https://github.com/angular/dev-infra-private-ng-dev-builds.git"`
We also update the the stamping keys to match the changes in dev-infra.
> build: update dev-infra packages [patch]

- packages/angular/cli/src/commands/generate/cli.ts
- tests/legacy-cli/e2e/tests/generate/schematic-aliases.ts
Previously, schematic aliases were not registered when a collection name was provided to `ng generate`.  Example: `ng generate c` where `c` is an alias for `component` would work, but `ng generate @schematics/angular:c` would fail. This commits fixes the schematic registration to handle the latter case.
Closes #24518
> fix(@angular/cli): register schematic aliases when providing collection name in `ng generate`

- tests/legacy-cli/e2e/tests/build/material.ts
- tests/legacy-cli/e2e/tests/commands/add/add-material.ts
- tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
This reverts commit 04e7c25aad3644d0502f0ae30308ccabf4db43ea as it is no longer needed due to the recent changes done in the material packages to expand the peer dependency.
See: https://github.com/angular/components/commit/6afe888a1a1c840c371991051335c19b6a1bdf95
> Revert "test: use `NPM_CONFIG_legacy_peer_deps` when testing prerelease versions of Angular material."

- packages/angular/cli/src/analytics/analytics-collector.ts
Any other kinds of Node version are collected as "other" to avoid pulling in an unbounded user input.
Issue Number: http://b/264671793
> refactor: only collect Node version if it's a standard version string

- packages/schematics/angular/universal/index.ts
- packages/schematics/angular/universal/index_spec.ts
This change fixes an issue where calling the universal schematic on an application with existing `BrowserModule.withServerTransition` will cause an additional `.withServerTransition` call to be added.
With this change we now remove the previous `withServerTransition` call to avoid misconfiguration.
Closes #24563
> fix(@schematics/angular): replace existing `BrowserModule.withServerTransition` calls when running universal schematic

- CHANGELOG.md
> docs: release notes for the v15.1.2 release

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
When using Sass with the experimental esbuild-based browser application builder, bare imports without a path segment that were available via included paths but also happen to be a node module could cause an exception. An example of such an import would be `@import "globals";`. The deep import node module logic would previously attempt to join an undefined path segment to the resolved path for the `globals` package which would raise a argument type exception. This case has now been fixed by only joining if there is actually a path segment present such as `@import "globals/x"`. With this fix in place, the node module case can then continue and if no stylesheet is found, the include paths will then be searched.
> fix(@angular-devkit/build-angular): avoid undefined module path for Sass imports in esbuild

- packages/angular/cli/src/commands/update/cli.ts
This commit updates `ng update` to include the number of files updated when a migration is completed.
Closes #24488
> feat(@angular/cli): log number of files update during `ng update`

- packages/angular_devkit/core/src/workspace/json/test/cases/AddProject3.json
- packages/angular_devkit/core/src/workspace/json/writer.ts
- packages/angular_devkit/core/src/workspace/json/writer_spec.ts
The workspace writer previously transformed number like strings to numbers which causes failures when a project is named using a number like name.
Closes #24541
> fix(@angular-devkit/core): handle number like strings in workspace writer

- package.json
- packages/angular/cli/lib/config/workspace-schema.json
- renovate.json
- yarn.lock
This commit updates `quicktype-core` to `20.0.15` and enables Renovate to update this.
> build: update `quicktype-core` to `20.0.15`

- packages/angular_devkit/schematics_cli/bin/schematics.ts
Can't specify packageManager when running a schematic
Detect packageManager by the lock file, and use the right package manager to install dependencies. Behave like `ng generate <schematic>`
This PR originates from https://github.com/nestjs/nest-cli/issues/1115
As I look into the problem, first I wanted to fix it in [`@nestjs/schematics`](https://github.com/nestjs/schematics/blob/641e8d412d95f6de5393718e0d2e512493e62c45/src/lib/resource/resource.factory.ts#L195)
but then I checked Angular cli, and run the following command, it worked as excepted(using correct package manager).
```bash
ng new test --no-install
cd test
touch yarn.lock
ng g …
```
> feat(@angular-devkit/schematics-cli): auto detect package manager

- WORKSPACE
Synchronizes the aspect bazel library used in patch with the main branch.
> build: update bazel aspect lib to 1.23.3

- CHANGELOG.md
> docs: release notes for the v15.1.3 release

- packages/angular_devkit/build_angular/src/builders/server/index.ts
- packages/angular_devkit/build_angular/src/builders/server/tests/behavior/build-errors_spec.ts
- packages/angular_devkit/build_angular/src/builders/server/tests/behavior/web-workers_spec.ts
Previously server builder errors and warnings were not being printed in the console correctly.
Closes #24612
> fix(@angular-devkit/build-angular): print server builder errors and warnings

- packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma-context.html
- packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma-debug.html
With this change we load bundles as modules when using the Karma builder.
> fix(@angular-devkit/build-angular): load JavaScript bundles as modules in karma

- CHANGELOG.md
> docs: release notes for the v15.1.4 release

- packages/angular_devkit/build_angular/src/utils/esbuild-targets.ts
Fix issue-related to the support of Safari TP versions. This issue was accidentally introduced in angular/angular-cli@a0f9db8
Issue Number: #24639 
You are getting an error when you try to build the project.
```
An unhandled exception occurred: Transform failed with 1 error:
error: Invalid version: "tp.0"
See "/private/var/folders/_1/g7z1fzm54sb_wrdyk00s32580000gn/T/ng-SQbgG6/angular-errors.log" for further details
```
The project was built successfully.
> fix(@angular-devkit/build-angular): fix support of Safari TP versions

- packages/angular/cli/src/analytics/analytics-collector.ts
`querystring.stringify` will not remove undefined values.
> fix(@angular/cli): only set `DebugView` when `NG_DEBUG` is passed

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/jit-compilation.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/jit-plugin-callbacks.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/jit-resource-transformer.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/uri.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer-worker.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
When using the experimental esbuild-based browser application builder, the `aot` build option can now be set to `false` to enable JIT compilation mode. The JIT mode compilation operates in a similar fashion to the Webpack-based builder in JIT mode. All external Component stylesheet and template references are converted to static import statements and then the content is bundled as text. All inline styles are also processed in this way as well to support inline style languages such as Sass. This approach also has the advantage of minimizing the processing necessary during rebuilds. In JIT watch mode, TypeScript code does not need to be reprocessed if only an external stylesheet or template is changed.
> feat(@angular-devkit/build-angular): support JIT compilation with esbuild

- packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma-context.html
- packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma-debug.html
- tests/legacy-cli/e2e/tests/test/test-jasmine-clock.ts
This commit updates changes the way polyfills and runtime are loaded from modules to scripts. This is required as otherwise Jasmine will be loaded prior to Zone.js which causes clock patching not to work.
Closes #24651
> fix(@angular-devkit/build-angular): load polyfills and runtime as scripts instead of modules

- packages/schematics/angular/universal/index.ts
- packages/schematics/angular/universal/index_spec.ts
The bootstrapping wrapping is no longer necessary as of 15.1.3. See: https://github.com/angular/angular/pull/48868
> fix(@schematics/angular): remove bootstrapping wrapping in universal schematic

- packages/angular_devkit/build_angular/src/builders/karma/find-tests-plugin.ts
- packages/angular_devkit/build_angular/src/builders/karma/tests/options/include_spec.ts
Previously, we failed the compilation when the specified patterns did not match any spec file. This breaks the case were users configure Karma to not fail on empty test suit.
Closes #24644
> fix(@angular-devkit/build-angular): do not fail compilation when spec pattern does not match

- packages/angular/cli/src/command-builder/utilities/schematic-engine-host.ts
When a schematic is executed, it is wrapped in a custom Node context. This context doesn't expose the same set of global variables as the default one. This can lead to an error if a schematic is importing the Angular compiler and the app is using i18n, because the `TextEncoder` isn't exposed through the custom context (see https://github.com/angular/angular/issues/48940).
These changes add the `TextEncoder` to the context.
Fixes https://github.com/angular/angular/issues/48940.
> fix(@angular/cli): error if Angular compiler is used in a schematic

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/behavior/browser-support_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/assets_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/output-hashing_spec.ts
- packages/angular_devkit/build_angular/src/testing/builder-harness.ts
The following unit tests have been ported over to test the experimental esbuild-based
browser application builder:
* `assets` option
* `outputHashing` option
* browser support behavior (`browserslist`)
Several small modifications were necessary to accommodate output file differences such
as no runtime chunk. Additionally, two tests are temporarily disabled for the `outputHashing`
tests pending implementation in the builder. These tests are the same stylesheet resource handling
file name test and no hashing of non-injected styles test.
> test(@angular-devkit/build-angular): port several unit tests to esbuild builder

- packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members.ts
- packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members_spec.ts
The build optimizer's static class field pass will now additionally wrap classes that contain side effect free class properties. This allows optimizers and bundlers further along in the build pipeline to downlevel that class properties while still retaining the ability to tree-shake the class if unused. The class properties may need to be downleveled for a variety of reasons such as lack of browser support, browser bugs with certain code structures, or to ensure spec-compliant runtime behavior.
Fixes: #24656
> fix(@angular-devkit/build-angular): build optimizer support for spec-compliant downlevel class properties

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/less-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/inline-style-language_spec.ts
- yarn.lock
When using the experimental esbuild-based browser application builder, stylesheets written in the Less stylesheet language can now be used throughout an application. The support allows Less stylesheets to be used in all locations where CSS and/or Sass can be used. This includes global stylesheets and both inline and external component styles. When using inline component styles, the `inlineLanguageStyle` build option must be set to `less`.
Currently, import resolution within a Less stylesheet is limited to default Less behavior which does not include full node package resolution. Full resolution behavior will be added in a future change.
> feat(@angular-devkit/build-angular): add Less stylesheet support to experimental esbuild-based builder

- CHANGELOG.md
> docs: release notes for the v15.1.5 release

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/typescript.ts
Update the `TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022"` warning message to be more actionable.
Closes: #24697
> fix(@angular-devkit/build-angular): update the ECMA output warning message to be more actionable

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members.ts
- packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members_spec.ts
- packages/angular_devkit/build_angular/src/typings.d.ts
- yarn.lock
Within the build optimizer's static member optimization pass, a class that is directly default exported must be split into two statements: the class declaration and the default export. This is because the pass can wrap classes in a pure annotated IIFE which results in a variable declaration replacement and variable declarations can not be directly default exported. Previously, the pass did this splitting manually but this was causing later babel plugins to fail. In addition to updating the AST in this case, scoping information also needed to be updated. To support this, a babel helper package is now used that handles the details of the statement split operation.
Fixes #24688
> fix(@angular-devkit/build-angular): use babel default export helper in build optimizer

- packages/angular/cli/src/utilities/package-metadata.ts
- tests/legacy-cli/e2e/tests/commands/add/npm-config.ts
Previously, the `before` option in the npmrc was not converted properly to a date.
See: https://docs.npmjs.com/cli/v8/using-npm/config#before
Closes #24685
> fix(@angular/cli): convert `before` option in `.npmrc` to Date

- packages/angular_devkit/build_angular/src/utils/service-worker.ts
Previously, `safety-worker.js` and `worker-basic.min.js` contained incorrect data due to an incorrect path.
Closes #24678
> fix(@angular-devkit/build-angular): correctly copy `safety-worker.js` contents

- .circleci/dynamic_config.yml
- WORKSPACE
- docs/DEVELOPER.md
- tests/legacy-cli/BUILD.bazel
- tests/legacy-cli/e2e.bzl
- tests/legacy-cli/e2e/initialize/500-create-project.ts
- tests/legacy-cli/e2e/tests/build/esbuild-unsupported.ts
- tests/legacy-cli/e2e/tests/update/update-multiple-versions.ts
- tests/legacy-cli/e2e/utils/bazel.ts
- tests/legacy-cli/e2e/utils/process.ts
- tests/legacy-cli/e2e/utils/project.ts
- tests/legacy-cli/e2e/utils/run_test_process.js
- tests/legacy-cli/e2e_runner.ts
- tests/legacy-cli/run_e2e.js
- tools/toolchain_info.bzl
> Remove non Bazel E2E CI jobs

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/commonjs-checker.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/allowed-common-js-dependencies_spec.ts
- yarn.lock
The `zone.js` package is currently built into a module structure form that resembles UMD-like output. This cases the CommonJS checker within the experimental esbuild-based browser application builder to issue a warning for zone.js usage. Until the packaging of zone.js is updated to become fully ESM, the `zone.js` package is automatically allowed when performing the CommonJS module check.
> fix(@angular-devkit/build-angular): avoid CommonJS warning for zone.js in esbuild

- packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts
In some cases, using the `scripts` option caused a lot of `DescriptionFileUtils.loadDescriptionFile` calls which caused a bottleneck during build times.
The why to this is still unknown, but a workaround is to use the resolver from the Webpack compilation instead of the compiler.
Closes #24634
---
From @fearghalom
> On rebuilds, it knocked ~35secs off the time.
> perf(@angular-devkit/build-angular): reduce rebuilt times when using the `scripts` option

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/extract-licenses_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/inline-critical_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/main_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/styles_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/subresource-integrity_spec.ts
The following unit tests have been ported over to test the experimental esbuild-based browser application builder:
* `extractLicenses` option
* `main` option
* `optimization.styles.inlineCritical` option
* `styles` option
* `subresourceIntegrity` option
Several individual tests involving file output logging have been temporarily disabled until build and file output logging has been implemented for the builder.
> test(@angular-devkit/build-angular): port additional unit tests to esbuild builder

- CHANGELOG.md
> docs: release notes for the v15.1.6 release

- packages/schematics/angular/guard/implements-files/__name@dasherize__.guard.ts.template
- packages/schematics/angular/guard/index.ts
- packages/schematics/angular/guard/index_spec.ts
- packages/schematics/angular/guard/schema.json
- packages/schematics/angular/guard/type-files/__name@dasherize__.guard.ts.template
- packages/schematics/angular/utility/ast-utils_spec.ts
- tests/legacy-cli/e2e/tests/generate/guard/guard-implements.ts
- tests/legacy-cli/e2e/tests/generate/guard/guard-multiple-implements.ts
Angular v15.1 deprecated the `CanLoad` guard in favor of `CanMatch`. This commit removes the support for `CanLoad` when generating a guard with the CLI, to encourage developers to use `CanMatch` instead.
> feat(@schematics/angular): remove deprecated CanLoad option for guards

- goldens/public-api/angular_devkit/core/index.md
- packages/angular/cli/src/command-builder/utilities/json-schema.ts
- packages/angular/cli/src/utilities/config.ts
- packages/angular_devkit/architect/src/architect.ts
- packages/angular_devkit/architect/src/jobs/simple-scheduler.ts
- packages/angular_devkit/build_angular/src/testing/builder-harness.ts
- packages/angular_devkit/core/src/json/schema/interface.ts
- packages/angular_devkit/core/src/json/schema/prompt_spec.ts
- packages/angular_devkit/core/src/json/schema/registry.ts
- packages/angular_devkit/core/src/json/schema/registry_spec.ts
- packages/angular_devkit/core/src/json/schema/transforms_spec.ts
- packages/angular_devkit/schematics/src/formats/format-validator.ts
- packages/angular_devkit/schematics/src/formats/html-selector_spec.ts
- packages/angular_devkit/schematics/src/formats/path_spec.ts
- packages/angular_devkit/schematics/tools/schema-option-transform.ts
Use promise based methods to reduce RXJS usage and boiler-platting.
BREAKING CHANGE: Several changes to the `SchemaRegistry`.
- `compile` method now returns a `Promise`.
- Deprecated `flatten` has been removed without replacement.
> feat(@angular-devkit/core): update SchemaRegistry `compile` to return `Promise`

- WORKSPACE
- tools/defaults.bzl
- tsconfig.json
The minimum supported Node.js version is now v16.13. This version provides full support for ES2020 allowing the output code target to be increased. While Node.js v16.13 supports higher ECMAScript versions, a limitation of the bazel `ts_library` rule currently prevents increasing further at this time.
> build: update output target to ES2020

- packages/angular_devkit/build_angular/src/builders/browser/tests/options/scripts_spec.ts
- packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts
When using the internal JavaScript optimizer plugin for Webpack with an empty script file provided via the `scripts` option, the build would fail. This was because of a safety check that was checking whether the terser result was falsy. Since an empty string is considered falsy, the build considered the result to be an error. The safety check now will only trigger if the terser result is not a string value to avoid this case.
Fixes #24736
> fix(@angular-devkit/build-angular): allow empty scripts to be optimized

- packages/schematics/angular/guard/index_spec.ts
- packages/schematics/angular/guard/schema.json
- packages/schematics/angular/resolver/index_spec.ts
- packages/schematics/angular/resolver/schema.json
- tests/legacy-cli/e2e/tests/generate/guard/guard-basic.ts
- tests/legacy-cli/e2e/tests/generate/guard/guard-implements.ts
- tests/legacy-cli/e2e/tests/generate/guard/guard-multiple-implements.ts
As Angular v15.2 deprecates class-based resolvers and guards, this commit switches the `functional` flag default value to `true`.
`ng g resolver` and `ng g guard` now generate a functional resolver or guard by default. It is still possible to generate a (deprecated) class-based resolver or guard by using `ng g resolver --no-functional` or `ng g guard --no-functional`.
> feat(@schematics/angular): generate functional resolvers and guards by default

- renovate.json
quicktype-core publishes on a per commit basis. This change reduces the updates to monthly.
> ci: reduce quicktype-core updates

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/behavior/typescript-path-mapping_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/base-href_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/cross-origin_spec.ts
The following unit tests have been ported over to test the experimental esbuild-based browser application builder:
* `baseHref` option
* `crossOrigin` option
* TypeScript path mapping behavior
> test(@angular-devkit/build-angular): additional unit tests for esbuild builder

- CHANGELOG.md
> docs: release notes for the v15.2.0 release

- .circleci/dynamic_config.yml
The CircleCI commands to store the E2E test results and artifacts was outdated which caused nothing to be saved.
> ci: correctly store E2E test results and artifacts

- packages/circular-deps-test.conf.js
This ensures that all packages are picked up.
> build: refactor circular-deps-test.conf to use package.js file

- .ng-dev/release.mts
- scripts/release-checks/dependency-ranges/index.mts
- scripts/release-checks/dependency-ranges/latest-versions-check.mts
- scripts/release-checks/dependency-ranges/peer-deps-check.mts
- scripts/release-checks/tsconfig.json
Adds an automatic check that runs before cutting releases. This will help avoiding issues where
we forget to update peer dependencies or the `latest-versions.ts` file.
> build: add pre-release checks for dependency on framework

- packages/angular_devkit/build_angular/src/webpack/utils/stats.ts
Webpack errors can sometimes be several hundred of thousands of characters long as it may contain the entire bundle. This can cause a ReDoS. This change improves the way we parse and remove stack traces from error messages.
Closes #24771
> fix(@angular-devkit/build-angular): improve parsing of error messages

- goldens/public-api/angular_devkit/build_angular/index.md
- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/allow-js_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/base-href_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/build-optimizer_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/cross-origin_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/deploy-url_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser/specs/index_spec.ts
- packages/angular_devkit/build_angular/src/builders/server/index.ts
Remove the deprecated `outputPath` and `outputPaths` from the server and browser builder.
Deprecated `outputPath` and `outputPaths` from the server and browser builder have been removed from the builder output. Use `outputs` instead.
Note: this change does not effect application developers.
> refactor(@angular-devkit/build-angular): remove deprecated `outputPaths` and `outputPath` Builder output

- CHANGELOG.md
> docs: release notes for the v15.2.1 release

- packages/angular_devkit/schematics_cli/bin/schematics.ts
This commits ports the same logic from the `@angular/cli` (https://github.com/angular/angular-cli/blob/693d78b80de9e91bd5313353ea5c524742196e0a/packages/angular/cli/src/command-builder/schematics-command-module.ts#L183-L211) to correctly handle numbers in prompts.
Closes #24817
> fix(@angular-devkit/schematics-cli):  correctly transform numbers from prompts

- packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members.ts
- packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members_spec.ts
The build optimizer's static field pass will now additionally wrap classes that contain side effect free TypeScript ES2022 static class properties.
This is needed to update APF to ship ES2022, which have `useDefineForClassFields` set to `false`.
> fix(@angular-devkit/build-angular): build optimizer support for non spec-compliant ES2022 class static properties

- packages/angular/cli/src/commands/update/cli.ts
- packages/angular/cli/src/utilities/prompt.ts
When running `ng update` we now display optional migrations from packages. 
When the terminal is interactive, we prompt the users and ask them to choose which migrations they would like to run.
```
$ ng update @angular/core --from=14 --migrate-only --allow-dirty
Using package manager: yarn
Collecting installed dependencies...
Found 22 dependencies.
** Executing migrations of package '@angular/core' **
▸ Since Angular v15, the `RouterLink` contains the logic of the `RouterLinkWithHref` directive.
This migration replaces all `RouterLinkWithHref` references with `RouterLink`.
Migration completed (No changes made).
** Optional migrations of package '@angular/core' **
This package have 2 optional migrations that can be executed.
Select the migrations that you'd like to run (Press <space> to …
```
> feat(@angular/cli): show optional migrations during update process

- CHANGELOG.md
> docs: release notes for the v15.2.2 release

- tests/legacy-cli/e2e/assets/webpack/test-app/package.json
The latest next release of FW (16.0.0-next.2) now requires zone.js 0.13.
> test: update webpack E2E test to use zone.js 0.13

- packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members.ts
- packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members_spec.ts
Prior to this commit, we only wrapped classes with static properties that were marked with `/*@__PURE__*/` comment due to a bug in the `adjust-static-class-members` Babel plugin were we did not call the `Identifier` name text to the `canWrapProperty` function.
> fix(@angular-devkit/build-angular): correct wrap ES2022 classes with static properties

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/behavior/typescript-resolve-json_spec.ts
The experimental esbuild-based browser application builder now contains a test to ensure that the TypeScript `resolveJsonModule` option works as expected.
> test(@angular-devkit/build-angular): add esbuild test for TS resolveJsonModule option

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Configure Babel to use `setPublicClassFields: true`. As when shipping Angular packages without `"useDefineForClassFields": false` will increase the bundle size of an ng-new app by ~2Kb when `useDefineForClassFields`  is not false. due to the additional `_defineProperty`, which will be added on every class property.
See: https://babeljs.io/docs/babel-plugin-proposal-class-properties
> fix(@angular-devkit/build-angular): set public class fields as properties

- packages/angular_devkit/build_angular/src/builders/app-shell/render-worker.ts
- packages/angular_devkit/build_angular/src/builders/server/platform-server-exports-loader.ts
- tests/legacy-cli/e2e/tests/build/app-shell/app-shell-standalone.ts
This commit adds support for generating an app-shell for a standalone application.
The `main.server.ts`, will need to export a bootstrapping function that returns a `Promise<ApplicationRef>`.
Example
```ts
export default () => bootstrapApplication(AppComponent, {
providers: [
importProvidersFrom(ServerModule),
provideRouter([{ path: 'shell', component: AppShellComponent }]),
],
});
```
> feat(@angular-devkit/build-angular): support standalone app-shell generation

- CHANGELOG.md
> docs: release notes for the v15.2.3 release

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/css-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/behavior/stylesheet_autoprefixer_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/cross-origin_spec.ts
When using the experimental esbuild-based browser application builder, CSS stylesheets will now be processed by the postcss autoprefixer plugin. The autoprefixer plugin will only be used if the browsers provided by browserslist require prefixes to be added. This avoids unnecessary stylesheet parsing and processing if no additional prefixes are needed. Currently, only CSS stylesheets are processed. Preprocessor support including Sass and Less will be added in a future change.
> feat(@angular-devkit/build-angular): initial autoprefixer support for CSS in esbuild builder

- CHANGELOG.md
> docs: release notes for the v13.3.11 release

- CHANGELOG.md
> docs: release notes for the v14.2.11 release

- packages/angular_devkit/build_angular/src/utils/index-file/index-html-generator.ts
- packages/angular_devkit/build_angular/src/utils/index-file/style-nonce.ts
- packages/angular_devkit/build_angular/src/utils/index-file/style-nonce_spec.ts
Companion change to https://github.com/angular/angular/pull/49444. Adds an HTML processor that finds the `ngCspNonce` attribute and copies its value to any inline `style` tags in the HTML. The processor runs late in the processing pipeline in order to pick up any `style` tag that might've been added by other processors (e.g. critical CSS).
> feat(@angular-devkit/build-angular): add CSP support for inline styles

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/utils/copy-assets.ts
- packages/angular_devkit/build_angular/src/utils/service-worker.ts
As a preparation step to allow for in-memory build outputs to support the development server, the output result files of the build are now written to the file system in one location. This includes the generated files from the bundling steps as well as any assets and service worker files.
> refactor(@angular-devkit/build-angular): consolidate result file writes in esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/css-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
- tests/legacy-cli/e2e.bzl
When using the experimental esbuild-based browser application builder, CSS stylesheets will now be processed by tailwindcss if a tailwind configuration file is present and the `tailwindcss` package has been installed in the project. This provides equivalent behavior to the use of tailwind with the current default Webpack-based build system. Currently, only CSS stylesheets are processed. Preprocessor support including Sass and Less will be added in a future change.
> feat(@angular-devkit/build-angular): initial tailwindcss support for CSS in esbuild builder

- packages/schematics/angular/application/files/standalone-files/src/app/app.component.ts.template
Currently, the standalone `app.component.ts` looks like:
```ts
@Component({
selector: 'app-root',
standalone: true,
templateUrl: './app.component.html',
styleUrls: ['./app.component.css'], 
imports: [CommonModule]
})
```
whereas a generated component looks like:
```ts
@Component({
selector: 'app-user',
standalone: true,
imports: [CommonModule],
templateUrl: './user.component.html',
styleUrls: ['./user.component.css']
})
```
Note that the imports are not always in the same place.
The imports are moved to a similar place than in other components.
Note that we could choose the other option (change it in the component template instead of app.component.ts),
but as `app.component.ts` …
> fix(@schematics/angular): use same property order in standalone AppComponent

- packages/angular_devkit/build_angular/src/builders/karma/tests/options/assets_spec.ts
- packages/angular_devkit/build_angular/src/builders/karma/tests/options/styles_spec.ts
- packages/angular_devkit/build_angular/src/builders/karma/tests/options/web-worker-tsconfig_spec.ts
- packages/angular_devkit/build_angular/test/hello-world-app/src/app/app.component.spec.ts
- packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/src/lib/lib.component.spec.ts
- packages/angular_devkit/build_webpack/test/angular-app/src/app/app.component.spec.ts
- packages/schematics/angular/application/files/module-files/src/app/app.component.spec.ts.template
- packages/schematics/angular/application/files/standalone-files/src/app/app.component.spec.ts.template
- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.spec.ts.template
- packages/schematics/angular/component/index_spec.ts
- tests/legacy-cli/e2e/assets/13.0-project/src/app/app.component.spec.ts
- tests/legacy-cli/e2e/tests/test/test-jasmine-clock.ts
- tests/legacy-cli/e2e/tests/test/test-scripts.ts
Note: This is an updated version of #18316 after discussing with @atscott who thought we are now in a place where it could land
`compileComponents` is not necessary when using the CLI (as the templates are inlined) and just adds boilerplate code. So we can remove it from the test schematic and make it independent from `async/await` (only place we would have it in the CLI generated code, and in most Angular apps).
Tests are generating with `compileComponent` calls that aren't needed with the CLI
The boilerplate is reduced to only keep what is really necessary
> fix(@schematics/angular): remove compileComponents from component test schematic

- packages/angular_devkit/build_angular/src/builders/app-shell/app-shell_spec.ts
- packages/schematics/angular/app-shell/schema.json
- packages/schematics/angular/universal/index.ts
- packages/schematics/angular/universal/index_spec.ts
- packages/schematics/angular/universal/schema.json
- packages/schematics/angular/utility/ng-ast-utils.ts
- tests/legacy-cli/e2e/tests/build/app-shell/app-shell-standalone.ts
This commit removes generation of `.withServerTransition` in the universal schematic as is deprecated.
DEPRECATED: the `app-id` option in the app-shell and universal schematics has been deprecated without replacement. See: https://github.com/angular/angular/pull/49422 for more information about the rational of this change.
> feat(@schematics/angular): remove generation of  `BrowserModule.withServerTransition`

- packages/angular_devkit/build_angular/src/builders/app-shell/app-shell_spec.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css_spec.ts
Based on https://github.com/angular/angular-cli/pull/24880#pullrequestreview-1347993316. Critters can generate `link` tags with inline `onload` handlers which breaks CSP. These changes update the style nonce processor to remove the `onload` handlers and replicate the behavior with an inline `script` tag that gets the proper nonce.
Note that earlier we talked about doing this through Critters, which while possible, would still require a custom HTML processor, because we need to both add and remove attributes from an element.
> fix(@angular-devkit/build-angular): support CSP on critical CSS link tags

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/polyfills_spec.ts
Previously when using the esbuild-based browser application, the `polyfills` option was limited to only one entry. The option now can be used with multiple entries and has full support for package resolution. This provides equivalent behavior to the current default Webpack-based builder.
> fix(@angular-devkit/build-angular): allow multiple polyfills with esbuild-based builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/css-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
- tests/legacy-cli/e2e.bzl
- tests/legacy-cli/e2e/tests/build/styles/tailwind-v2.ts
- tests/legacy-cli/e2e/tests/build/styles/tailwind-v3-cjs.ts
- tests/legacy-cli/e2e/tests/build/styles/tailwind-v3.ts
The additional arguments were previously not fully propagated within the bazel rules.
> test: ensure esbuild and yarn E2E tests are executed

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/css-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/less-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/behavior/component-stylesheets_spec.ts
Previously when using the esbuild-based browser application builder, an empty inline component style (`styles: ['']`) would cause the build to fail. This was due to a bad assertion condition that has now been corrected.
Fixes #24935
> fix(@angular-devkit/build-angular): ensure empty component styles compile with esbuild

- packages/schematics/angular/private/components.ts
- packages/schematics/angular/private/standalone.ts
- packages/schematics/angular/private/standalone_spec.ts
When the utilities for adding providers to the `bootstrapApplication` call were written, the structure for a standalone project hadn't been finalized yet which meant that the code made some assumptions around how the app config is being passed in. This code breaks with the final project structure, because there the app config is in a separate file instead of an object literal.
These changes update the utilities to account for the new structure. Note the updates are meant to cover the majority of apps and there are likely some edge cases that aren't covered. Covering all cases is tricky with the current setup, because to do so correctly would require knowledge of the entire app whereas the utilities operate on a file-by-file basis. For example, now the code is able to update a config in a …
> fix(@schematics/angular): update private Components utilities to work with standalone project structure

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
When using the esbuild-based browser application builder, the stat output table was incorrectly displaying source map files and internal component resource files such as inline stylesheets as initial entries.
> fix(@angular-devkit/build-angular): remove unintended files in esbuild output stats table

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/load-proxy-config.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
- yarn.lock
When using the experimental esbuild-based browser application builder, the preexisting `dev-server` builder can now be used to execute the `ng serve` command with an esbuild bundled application. The `dev-server` builder provides an alternate development server that will execute the `browser-esbuild` builder to build the application and then serve the output files within a development server with live reload capabilities. This is an initial integration of the development server. It is not yet fully optimized and all features may not yet be supported. SSL, in particular, does not yet work.
If already using the esbuild-based builder, no additional changes to the Angular configuration are required. The `dev-server` builder will automatically detect the application builder and use the relevent …
> feat(@angular-devkit/build-angular): initial development server for esbuild-based builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/global-scripts.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/scripts_spec.ts
When using the esbuild-based browser application builder, the `scripts` option will now provide equivalent functionality to the current default Webpack-based builder. The option provides full node resolution capabilities which allows both workspace relative paths and package paths with support for the `script` exports condition.
> feat(@angular-devkit/build-angular): support scripts option with esbuild builder

- packages/schematics/angular/private/standalone.ts
- packages/schematics/angular/service-worker/index.ts
- packages/schematics/angular/service-worker/index_spec.ts
This commit adds support to generate a service worker in a standalone application.
> feat(@schematics/angular): add support to add service worker to standalone application

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/less-plugin.ts
When using the esbuild-based browser application builder with Less stylesheets, import rules will now attempt to perform node package resolution if the import cannot be found as a relative path. Built-in Less resolution is performed first to both avoid unnecessary node module resolution overhead when not needed and also ensure Less relative import semantics continue to be supported.
> feat(@angular-devkit/build-angular): support module resolution with less stylesheets in esbuild builder

- goldens/public-api/angular_devkit/architect/index.md
- packages/angular_devkit/architect/src/create-builder.ts
- packages/angular_devkit/architect/src/jobs/create-job-handler.ts
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
The deprecated protractor builder requires that the result object from a development server provide the port used to access the application if the port is not the default (4200). The newly introduced esbuild development server will now provide the port when available.
> fix(@angular-devkit/build-angular): pass listening port in result for esbuild dev server

- CHANGELOG.md
> docs: release notes for the v15.2.5 release

- packages/schematics/angular/application/index.ts
This commit adds a warning when using `ng new --standalone` and `ng generate app --standalone`.
> fix(@schematics/angular): add experimental message when using standalone application schematic

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
- yarn.lock
When using the esbuild-based browser application builder and its newly supported development server, the SSL related `dev-server` builder options can now be used. These include the existing `ssl`, `sslCert`, and `sslKey` options. Additionally, if no certificate and key are provided the `@vitejs/plugin-basic-ssl` plugin will be used to provide an auto-generated one. While not providing a certificate is possible, the browser will display a warning upon accessing the development server when using an auto-generated certificate.
> feat(@angular-devkit/build-angular): support SSL options with esbuild development server

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/experimental-warnings.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
When using the esbuild-based browser application builder, the `progress` option which is enabled by default will now show an activity spinner when building/rebuilding.
> feat(@angular-devkit/build-angular): implement progress option for esbuild builder

- packages/schematics/angular/universal/files/standalone-src/app/app.config.server.ts.template
Update `provideServerSupport` with `provideServerRendering` as the former has been renamed.
> fix(@schematics/angular): replace `provideServerSupport` with `provideServerRendering`

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer.ts
When using the esbuild-based browser application builder in JIT mode, the Angular linker will now be skipped. The runtime Angular compiler present in JIT applications will automatically link any needed code.
> perf(@angular-devkit/build-angular): skip Angular linker in JIT mode with esbuild

- renovate.json
Currently version 0.9.0 causes e2e to fails due to incompatible changes https://github.com/bazelbuild/rules_pkg/releases/tag/0.9.0 until these issues are addressed in our build rules we disable this package from being updated.
> ci: disable `rules_pkg` updates

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/styles_spec.ts
Now that output stat logging for the esbuild-based browser application builder has been implemented, the previously disabled styles option tests can be enabled.
> test(@angular-devkit/build-angular): enable additional styles tests for esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
When using the esbuild-based browser application builder, all the watch-related code is now only imported when the watch mode is enabled. This removes the need for Node.js to resolve and load code that will not be used.
> perf(@angular-devkit/build-angular): only import esbuild watcher when in watch mode

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
When using the esbuild-based browser application builder in watch mode, the underlying file watcher based on chokidar would previously not fully ignore the output path if the path contained a trailing slash. To workaround this, directory paths based on supplied options are now normalized to remove any trailing slashes.
Fixes #24936
> fix(@angular-devkit/build-angular): ensure directories are properly ignored in esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
When using the esbuild-based browser application builder in watch mode, all `node_modules` directories will now be ignored by the file watcher. Instead all relevant package manifests and lock files for `npm`, `yarn, and `pnpm` will be watched to detect potential changes to the project's dependencies. This avoids creating a potentially large amount of filesystem watchers as the node modules directories can be very large.
> refactor(@angular-devkit/build-angular): directly watch package lock files in esbuild builder

- tests/legacy-cli/e2e/tests/build/ts-standard-decorators.ts
The added E2E test checks that it is possible to compile an application with experimental decorators disabled. The test also executes the unit tests inside a CLI generated project.
~~NOTE: This relies on the snapshot artifact build of `@angular/core` from FW PR: https://github.com/angular/angular/pull/49492~~ (merged)
> test: add a standard decorator support E2E test

- packages/schematics/angular/universal/files/standalone-src/app/app.config.server.ts.template
- packages/schematics/angular/universal/files/standalone-src/main.server.ts.template
Angular copyright headers are included in scaffolded files when adding Angular Universal support.
The Angular copyright headers are no longer included in scaffolded files when adding Angular Universal support.
> refactor(@schematics/angular): remove copyright header from universal schematic files

- scripts/validate-licenses.ts
https://skyvine.corp.google.com/issues/1044744690
We were not able to update to the latest `path-scurry` in transitive dependencies because the [Blue Oak](https://blueoakcouncil.org/license/1.0.0) license was not approved.
Blue Oak is now approved and can be used in dependencies.
> ci: add `BlueOak` license now that it is approved by legal

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
The package module resolution logic for Sass stylesheets within the esbuild-based browser application builder has been restructured to limit the need to perform fallback resolution unless fully required. This allows common cases to avoid unnecessary and expensive resolution attempts. This provided a roughly 40% improvement in build times for the Angular Material documentation site.
> perf(@angular-devkit/build-angular): enhance Sass package resolution in esbuild builder

- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
- packages/angular_devkit/build_angular/src/utils/normalize-asset-patterns.ts
- yarn.lock
Previously when using the esbuild-based browser application builder with the new dev server, resource files referenced via stylesheets may not have been served by the development server. The development server has now been adjusted to properly prioritize and serve files that were generated during the build process.
Global stylesheets are also currently considered resource files as well to workaround issues with development sourcemaps within the development server itself. Global stylesheets are already fully processed by the build system prior to being passed to the development server.
> fix(@angular-devkit/build-angular): ensure all build resources are served in esbuild dev server

- CHANGELOG.md
> docs: release notes for the v15.2.6 release

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/jit-plugin-callbacks.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/load-result-cache.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sass-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets.ts
To improve rebuild performance when using Sass stylesheets with the esbuild-based browser application builder in watch mode, Sass stylesheets that are not affected by any file changes will now be cached and directly reused. This avoids performing potentially expensive Sass preprocessing on stylesheets that will not change within a rebuild.
> perf(@angular-devkit/build-angular): cache Sass in memory with esbuild watch mode

- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/utility/latest-versions.ts
- packages/schematics/angular/utility/latest-versions/package.json
This reverts commit 290e06018d3934cf27a5734a60947dcd7b45fa58.
Release checks don't like being in an RC state and it's not strictly necessary since installing a `-next` package will install `-rc` because it alphabetically follows. This means generating applications with `-next` in the `package.json` will still pull the latest RC releases of Angular packages.
> Revert "ci: bump Angular dependencies to `16.0.0-rc.0`"

- .circleci/bazel.common.rc
A number of small changes with comments here. The main one is that removing `--noshow_progress` will make Bazel print progress updates which tells Circle CI that test execution is still ongoing and avoids test failures due to lack of output.
The other notable trade-offs being made here are:
1. [`--keep_going`](https://bazel.build/docs/user-manual#keep-going) means `bazel test` will run all tests report all failures, which could be slower and noisier than reporting just the first failure but is more complete.
2. [`--build_tests_only`](https://bazel.build/docs/user-manual#build-tests-only) means only tests and binaries will be built, so any library targets not tested could have build errors hidden. Any such important targets should either be tested or use Skylib's `build_test()`.
The UI …
> ci: update CI `.bazelrc` to better support CI systems.

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/esbuild.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
When using the esbuild-based browser application builder, only actual initial files will be displayed in the initial files section. Previously, certain dynamically imported files could unintentionally be displayed in the stats output table as initial files. This was a display only error and had no effect on the files added to the index HTML file.
> fix(@angular-devkit/build-angular): correctly show initial files in stat table with esbuild builder

- packages/angular/cli/src/commands/command-config.ts
The mistake was introduced in a previous commit that introduced registration of lazy loading of commands.
> refactor(@angular/cli): update E2E command alias

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer-worker.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/sourcemap_spec.ts
When using the esbuild-based browser application builder, third-party sourcemaps will now be fully removed when the `sourcemap` option's `vendor` sub-option is disabled. The `vendor` sub-option is disabled by default and is only enabled if explicitly enabled within the project's configuration. Sourcemaps are considered third-party if their referencing code is contained within a `node_modules` directory. Previously, sourcemap URL comments may have been unintentionally left intact when processing third-party code via the Babel-based JavaScript transformer. These sourcemap URL comments are now removed correctly when code is both transformed and return directly when no transformation is required.
> fix(@angular-devkit/build-angular): fully remove third-party sourcemaps when disabled in esbuild builder

- tests/legacy-cli/e2e.bzl
- tests/legacy-cli/e2e/tests/basic/rebuild.ts
- tests/legacy-cli/e2e/tests/basic/scripts-array.ts
- tests/legacy-cli/e2e/tests/basic/styles-array.ts
- tests/legacy-cli/e2e/utils/project.ts
With the increased feature parity of the esbuild-based browser application builder, all the basic E2E tests can now be executed against the builder. Several of the output checks were required to be updated to reflect the differences in console output, lazy chunk file naming, and less required initial files in the index HTML.
> test(@angular-devkit/build-angular): execute all basic E2E tests with esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/angular-compilation.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/aot-compilation.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/jit-compilation.ts
The TypeScript and Angular configuration reading (`tsconfig.json`) has now been moved into the Angular compilation classes (AOT/JIT) directly. This removes compilation specific functionality from the esbuild plugin and allows the plugin to focus primarily on integration with esbuild.
> refactor(@angular-devkit/build-angular): move TS/NG configuration reading into compiler classes

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
- packages/angular_devkit/build_angular/src/utils/tailwind.ts
- packages/angular_devkit/build_angular/src/webpack/configs/styles.ts
With this change we added `tailwind.config.mjs` and `tailwind.config.ts` to known tailwind config files.
Closes #24943
> fix(@angular-devkit/build-angular): update list of known tailwind configuration files

- packages/angular/cli/src/analytics/analytics-collector.ts
In newer Node.js versions ng commands do not terminate properly when analytics are enabled.
This is because the request is never closed unless a `data` event listener is attached.
Closes #25034 and closes #25008
> fix(@angular/cli): process keeps running when analytics are enabled

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/esbuild.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
The code to execute the individual bundling elements of the esbuild-based browser application builder has been consolidated within a bundler context helper method. This moves the execution and result merging code into a single location and allows for more flexibility in control which elements should be executed per build. The global styles and global scripts bundling is now fully skipped if the options are not present in the build configuration.
> refactor(@angular-devkit/build-angular): use helper to bundle all elements of esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
Due to a typo in a conditional for the filtering of lazily defined global styles, global styles were unintentionally always initial if no global scripts were present in the application. This typo was causing the recently enabled styles E2E tests to fail.
> fix(@angular-devkit/build-angular): correctly filter lazy global styles in esbuild builder

- packages/angular_devkit/build_angular/src/builders/server/index.ts
- packages/angular_devkit/build_angular/src/builders/server/tests/behavior/preserve_whitespaces_check_spec.ts
This commits add a check to display a warning when `preserveWhitespaces` is configured in `tsconfig.server.json`, as potentially this could cause issue with hydration.
> fix(@angular-devkit/build-angular): display warning when `preserveWhitespaces` in set in the tsconfig provided to the server builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
When using the esbuild-based browser application builder, the tsconfig path will now be properly converted to the realpath when the `preserveSymlinks` option is disabled (the default). This ensures that TypeScript source files will be properly matched with the bundler's resolved paths when symlinks are used and the `preserveSymlinks` option is not enabled. This is needed to properly support the use of bazel with rules_js.
> fix(@angular-devkit/build-angular): use preserveSymlinks option for tsconfigs in esbuild builder

- packages/schematics/angular/workspace/files/__dot__vscode/launch.json.template
> fix(@schematics/angular): replace vscode launch type from `pwa-chrome` to `chrome`

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- tests/legacy-cli/e2e/tests/basic/rebuild.ts
- tests/legacy-cli/e2e/utils/project.ts
The complete log has been updated to match the RegExp in https://github.com/angular/angular-cli/blob/c045c99667cec8a5986302d59eef3d326e3a53d2/packages/schematics/angular/workspace/files/__dot__vscode/tasks.json.template#L18 as otherwise vscode debugged will not work correctly when using vscode launcher to launch the dev-server.
> fix(@angular-devkit/build-angular): update esbuild builder complete log

- packages/schematics/angular/library/files/src/__entryFile__.ts.template
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/index_spec.ts
- packages/schematics/angular/library/schema.json
- tests/legacy-cli/e2e/tests/generate/library/library-basic.ts
- tests/legacy-cli/e2e/tests/generate/library/library-standalone.ts
This commit fixes an issue were libraries could not be created with standalone APIs.
Standalone libraries do not have an an NgModule. When consumed users need to import the needed components, pipes, and directives.
It is also recommended not to avoid grouping exports as this typically indicates bad architecture and may also hinder tree-shaking.
**Don't**
```ts
export const COMPONENTS = [
FooComponent,
BarComponent,
]
```
**Do**
```ts
export { FooComponent } from './foo/foo.component';
export { BarComponent } from './bar/bar.component';
```
> fix(@schematics/angular): add standalone option to library library

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/global-scripts.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/sourcemap-ignorelist-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/sourcemap_spec.ts
When using the esbuild-based browser application builder with source maps enabled, the Chrome DevTools `x_google_ignoreList` extension will be added to JavaScript source maps. This extension supports an improved developer experience with Chrome DevTools. For more information, please see https://developer.chrome.com/articles/x-google-ignore-list/
> fix(@angular-devkit/build-angular): add sourcemap `x_google_ignoreList` support for esbuild builder

- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
When using the esbuild-based browser application builder with the dev-server builder, sourcemap URL comments were unintentionally doubled due to vite adding an additional inline sourcemap comment when processing the JavaScript files for the application. To avoid this, JavaScript files now have any sourcemap URL comments removed prior to being processed by vite. The sourcemap content is already passed directly to vite and allows the sourcemaps to be processed and provided to the browser as needed without the previously existing sourcemap URL comment. The removal is done without modifying the esbuild-based builder's options to avoid assuming the builder used with the dev-server has sourcemap options that allow hidden sourcemap generation.
> fix(@angular-devkit/build-angular): avoid double sourcemap comments with esbuild dev-server

- CHANGELOG.md
> docs: release notes for the v15.2.7 release

- goldens/public-api/angular_devkit/build_angular/index.md
- packages/angular_devkit/build_angular/src/builders/server/index.ts
- packages/angular_devkit/build_angular/src/builders/server/schema.json
- packages/schematics/angular/universal/index.ts
- tests/legacy-cli/e2e/tests/build/server/platform-server-build-optimizer.ts
This commit adds the option to run build-optimizer on the server bundles.
This is needed as in some cases, there can be restrictions on the size of server bundles that can be executed. One of these cases is CloudFlare workers
which by default does not work with an `ng-new` application due to the size of the
bundle mainly due to the retention of the `@angular/compiler`.
//cc @AndrewKushnir
> fix(@angular-devkit/build-angular): provide option to run build-optimizer on server bundles

- packages/angular/cli/BUILD.bazel
- packages/angular/cli/lib/config/workspace-schema.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/builders.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/builders/jest/index.ts
- packages/angular_devkit/build_angular/src/builders/jest/init-test-bed.mjs
- packages/angular_devkit/build_angular/src/builders/jest/jest-global.mjs
- packages/angular_devkit/build_angular/src/builders/jest/options.ts
- packages/angular_devkit/build_angular/src/builders/jest/schema.json
- packages/angular_devkit/build_angular/src/builders/jest/test-files.ts
- packages/angular_devkit/build_angular/src/builders/jest/tests/options.ts
- packages/angular_devkit/build_angular/src/builders/jest/tests/test-files_spec.ts
- tests/legacy-cli/e2e/tests/jest/basic.ts
- tests/legacy-cli/e2e/utils/jest.ts
This PR adds initial experimental [Jest](https://jestjs.io/) support. This is _experimental_ and not ready for production use yet. For now, it it sufficient to pass the tests generated by the `ng new` application and we will continue to expand on this design going forward.
Enable the Jest runner by updating the `test` builder in your `angular.json` to be:
```jsonc
{
"projects": {
"my-app": {
"architect": {
// ...
"test": {
"builder": "@angular-devkit/build-angular:jest"
}
}
}
}
}
```
The current approach is to pre-build application tests with the `browser-esbuild` Angular builder under the hood, and then run Jest on the JavaScript outputs. We'll continue to experiment with this …
> Initial experimental Jest support

- CHANGELOG.md
> docs: release notes for the v16.0.0-rc.2 release

- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-16/update-server-builder-config.ts
- packages/schematics/angular/migrations/update-16/update-server-builder-config_spec.ts
In https://github.com/angular/angular-cli/pull/25070 we turned on `buildOptimizer` by default for server builds. This causes existing projects development builds to always run build-optimizer. This migration will set `buildOptimizer` to false, when `optimization` is disabled.
> fix(@schematics/angular): provide migration that disables build optimizer on dev server builds

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
`@angular/platform-server/init` entry-point is side-effectful and thus it's not safe to perform advanced optimizations.
> fix(@angular-devkit/build-angular): exclude `@angular/platform-server/init` from unsafe optimizations

- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Vite inlines the source map as part of content (https://github.com/vitejs/vite/blob/ba62be40b4f46c98872fb10990b559fee88f4a29/packages/vite/src/node/server/send.ts#L59-L63) with no option to disable this behaviour. While this is improves performances when Vite is used without prebundling. When using prebundling this is causes an overhead as the response can grow drastically, in some cases over 50mb.
Closes #25012
> perf(@angular-devkit/build-angular): do not inline sourcemap when using vite dev-server

- packages/angular_devkit/build_angular/src/builders/jest/index.ts
This is ensure that the same node executable is used to spawn Jest
> refactor: replace `node` with `process.execPath`

- packages/angular_devkit/build_angular/src/babel/plugins/adjust-typescript-enums.ts
- packages/angular_devkit/build_angular/src/babel/plugins/adjust-typescript-enums_spec.ts
- packages/angular_devkit/build_angular/src/babel/presets/application.ts
- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/javascript-transformer-worker.ts
With this change TypeScript enums are always processing in "loose" mode. Previously, this was only done for `@angular/` packages.
> fix(@angular-devkit/build-angular): always enable `looseEnums` build optimizer rule

- CHANGELOG.md
> docs: release notes for the v16.0.0-rc.3 release

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
The status of the esbuild-based browser application builder has been changed to developer preview. Warning messages for unsupported options are now updated to reflect this change.
> refactor(@angular-devkit/build-angular): update esbuild builder option status messages

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
- tests/legacy-cli/e2e/tests/build/jit-standalone.ts
This commit fixes and issue were standalone applications would fail during runtime because the `@angular/compiler` is not available.
We now add the `@angular/compiler` as part of the bundle when JIT mode is enabled.
> fix(@angular-devkit/build-angular): JIT support for standalone applications

- CHANGELOG.md
> docs: release notes for the v16.0.0-rc.4 release

- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/utility/latest-versions.ts
- packages/schematics/angular/utility/latest-versions/package.json
Prep PR for v16 following [instructions](https://github.com/angular/angular-cli/blob/main/docs/process/release.md#release).
> refactor: bump peer dependencies for v16 release

- packages/angular/pwa/package.json
Missed the `@angular/pwa` dep in a previous PR, need to bump this as well.
> refactor: bump `@angular/pwa` peer dependency version for v16

- docs/process/release.md
There is a peer dep in `@angular/pwa` which needs to be updated for major releases. This got missed initially because it was not listed in the documentation, so hopefully this will catch it next time.
> docs: add `@angular/pwa` to version bump list in release documentation

- packages/angular/pwa/package.json
- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/utility/latest-versions/package.json
Post-release task to update peer dependencies now that we'll release `16.1.0-next` from the `main` branch.
> refactor: widen peer dependencies to `^16.0.0 || ^16.1.0-next.0`

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/global-scripts.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/global-styles.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
When using the esbuild-based browser application builder, non-injected global styles and scripts were unintentionally being output with filenames that contain a hash. This can prevent the filenames from being discoverable and therefore usable at runtime. The output filenames will now no longer contain a hash component which matches the behavior of the Webpack-based builder.
> fix(@angular-devkit/build-angular): avoid hash filenames for non-injected global styles/scripts

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets/less-plugin.ts
- tests/legacy-cli/e2e.bzl
All the tests within the `build/library` and `build/styles` test directories will now be run for the esbuild-based builder E2E CI.
Also fixes an issue with relative Less imports.
> test(@angular-devkit/build-angular): enable additional build E2E tests for esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
esbuild currently has a defect involving self-referencing a class within a static code block or static field initializer. This is not an issue for projects that use the default browserslist as these elements are an ES2022 feature which is not support by all browsers in the default list. However, if a custom browserslist is used that only has newer browsers than the static code elements may be present. This issue is compounded by the default usage of the tsconfig `"useDefineForClassFields": false` option present in generated CLI projects which causes static code blocks to be used instead of static fields. esbuild currently unconditionally downlevels all static fields in top-level classes so to workaround the Angular issue only static code blocks are disabled here.
Fixes #25127
> fix(@angular-devkit/build-angular): workaround for esbuild static block AOT generated code

- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
When using the esbuild-based browser application builder with the development server, the `baseHref` build option will now be properly propagated to the underlying Vite server.
Closes #25128
> fix(@angular-devkit/build-angular): properly set base dev-server path with esbuild

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
The `index` option of the `browser-esbuild` builder is defined to accept one of a `string`, an `object`, or a const `"false"`. Note the const value it's not `false` but a string value. Because of that, there's no way to disable the index generation:
- If we set the option to `"false"` we get an error because it matches both the `string` and the const:
```
Error: Schema validation failed with the following errors:
Data path "/index" must be object.
Data path "/index" must match exactly one schema in oneOf.
```
- If we set the option to `false` we get an error because it doesn't match any of the possible definitions:
```
Error: Schema validation failed with the following errors: …
```
> fix(@angular-devkit/build-angular): fix index option const value for browser-esbuild

- packages/angular_devkit/build_angular/src/webpack/configs/dev-server.ts
By default now webpack-dev-server adds runtime errors in an overlay. See: https://github.com/webpack/webpack-dev-server/commit/aab01b3c4e4fb9ca9ae1c1bbc860a52a06026de6 this commit disables this functionality.
Closes #25151
> fix(@angular-devkit/build-angular): disable runtime errors from being displayed in overlay

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
This reverts commit 04274afc15084ead2916e11055aa8f1d2f61951d.
Closes: #25161
> Revert "fix(@angular-devkit/build-angular): set public class fields as properties (#24849)"

- docs/process/release.md
I mainly rewrote the section about modifying dependencies after a major/minor release, however I also refactored the other sections to more clearly specify the timing of each action and share a single list of all files which need to be updated so duplicates don't fall out of date.
> docs: update release doc to be more clear about peer dependency updates and timing

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets/css-resource-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/behavior/stylesheet-url-resolution_spec.ts
When using the esbuild-based browser application builder with a `url()` in a stylesheet that uses that Webpack-specific tilde prefix, a note will be added to the resolution error providing additional information regarding the removal of the tilde.
Closes #25089
> fix(@angular-devkit/build-angular): show error note for CSS url() tilde usage in esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/commonjs-checker.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/allowed-common-js-dependencies_spec.ts
When using the esbuild-based browser application builder, CommonJS file warnings were incorrectly being issued for relative file imports. The CommonJS warnings are only intended to be generated for node module imports.
> fix(@angular-devkit/build-angular): avoid CommonJS warnings for relative imports with esbuild builders

- goldens/public-api/angular_devkit/schematics/index.md
- packages/angular/pwa/pwa/index.ts
- packages/angular_devkit/schematics/src/sink/dryrun.ts
- packages/angular_devkit/schematics/src/sink/host.ts
- packages/angular_devkit/schematics/src/tree/recorder.ts
- packages/angular_devkit/schematics/src/utility/update-buffer.ts
`UpdateBuffer` only supports UTF-8 encoded files, which causes schematics to emit corrupted binary like files such as images.
This commit also introduce an errors when the `UpdateRecorder` is used for non UTF-8 files.
Closes #25174
>     fix(@angular-devkit/schematics): do not generate an UpdateBuffer for created and overridden files

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/angular-compilation.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/aot-compilation.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/jit-compilation.ts
The internal emit strategy for the TypeScript/Angular compiler has been adjusted to prefill the memory cache during the initial phase of the build. Previously each file was emitted during the bundling process as requested by the bundler. This change has no immediate effect on the build process but enables future build performance improvements.
> refactor(@angular-devkit/build-angular): emit affected files as a group in esbuild builder

- goldens/public-api/angular_devkit/core/index.md
- packages/angular_devkit/core/src/virtual-fs/host/buffer.ts
- packages/angular_devkit/core/src/virtual-fs/host/record_spec.ts
`TextDecoder` and `TextEncoder` can now be used on Node.js
> refactor(@angular-devkit/core): update `stringToFileBuffer` and `fileBufferToString` to use `TextDecoder` and `TextEncoder`

- goldens/public-api/angular_devkit/build_angular/index.md
- packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/options.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
To allow lower overhead trial of the developer preview of the esbuild-based builder system, the development server now has an option to force the usage of the esbuild-based build system while still retaining the default Webpack-based build system for the `build` command. The `forceEsbuild`/`--force-esbuild` option can be added to the `angular.json` options for the `serve` target or used on the command line, respectively. The `browser-esbuild` builder will be used to build the application using the options specified by the server configuration's `browserTarget` option. Unsupported build options will be ignored. If using a third-party builder, a warning will be issued but the build will still be attempted. Third-party builder usage in this context is considered unsupported and may result in …
> feat(@angular-devkit/build-angular): allow forcing esbuild builder with dev-server

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/aot-compilation.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/jit-compilation.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
When using the esbuild-based browser application builder with CLI caching enabled, TypeScript's `incremental`
option will also be enabled by default. A TypeScript build information file will be written after each build and
an attempt to load and use the file will be made during compilation setup. Caching is enabled by default within
the CLI and can be controlled via the `ng cache` command. This is the first use of persistent caching for the
esbuild-based builder. If the TypeScript `incremental` option is manually set to `false`, the build system will
not alter the value. This can be used to disable the behavior, if preferred, by setting the option to `false` in
the application's configured `tsconfig` file.
NOTE: The build information only contains information regarding the TypeScript …
> feat(@angular-devkit/build-angular): support incremental TypeScript semantic diagnostics in esbuild builder

- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
When using the esbuild-based browser application builder with the Vite-based development server on Windows, source asset paths were previously not normalized prior to being included in request URLs. This could result in invalid asset request URLs due to invalid path segment separators.
> fix(@angular-devkit/build-angular): normalize Vite dev-server Windows asset paths

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/global-scripts.ts
When using a global script (`scripts` option) with the esbuild-based browser application builder, an attempt to read the script as a relative path from the workspace root will be performed first. This avoids the need to perform a potentially expensive module resolution attempt for files that are directly available and also ensures the relative paths are given priority over any potential modules with the same name. This matches prior behavior that also preferred relative paths.
Closes #25198
> fix(@angular-devkit/build-angular): attempt relative global script read first in esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- tests/legacy-cli/e2e/tests/basic/build.ts
- tests/legacy-cli/e2e/tests/build/progress-and-stats.ts
When using the esbuild-based browser application builder, the console build stats output will now show the estimated transfer size of JavaScript and CSS files when optimizations are enabled. This provides similar behavior to the default Webpack-based builder.
> feat(@angular-devkit/build-angular): show estimated transfer size with esbuild builder

- package.json
- yarn.lock
The package resolutions for `ajv` and `parse5` are no longer needed with the latest package versions.
> build: remove unneeded package resolutions

- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
When using the esbuild-based browser application builder with the development server, configured application assets are served directly from disk. The URLs passed to Vite are now percent encoded to properly handle asset paths that may contain unsupported URL characters. This aligns with the static middleware within Vite: https://github.com/vitejs/vite/blob/3609e79dc1416073dc4775bb2fcf6a7398f169b3/packages/vite/src/node/server/middlewares/static.ts#L162
Closes #25238
> fix(@angular-devkit/build-angular): percent encode asset URLs in development server for esbuild

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/global-scripts.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/load-result-cache.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets/bundle-options.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets/css-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets/css-resource-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets/less-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/stylesheets/sass-plugin.ts
Within the esbuild-based browser application builder, a helper function has been introduced
to streamline the use of the load result cache within the internal plugins. This removes
repeat code that would otherwise be needed.
> refactor(@angular-devkit/build-angular): use helper to setup esbuild plugin load caching

- .bazelignore
- packages/angular/cli/BUILD.bazel
- packages/angular/create/BUILD.bazel
- packages/angular/pwa/BUILD.bazel
- packages/angular_devkit/benchmark/BUILD.bazel
- packages/angular_devkit/core/BUILD.bazel
- packages/angular_devkit/core/node/BUILD.bazel
- packages/angular_devkit/core/node/testing/BUILD.bazel
- packages/angular_devkit/schematics/BUILD.bazel
- packages/angular_devkit/schematics/tasks/BUILD.bazel
- packages/angular_devkit/schematics/tasks/node/BUILD.bazel
- packages/angular_devkit/schematics/tools/BUILD.bazel
- packages/ngtools/webpack/BUILD.bazel
- packages/schematics/angular/BUILD.bazel
BUILD files for each package have had outdated glob excludes removed. Additionally, some src args have been reduced to a single file where possible. The root bazel ignore file has also been expanded to include all node module directories in each package. The ignore file does not appear to currently support globs so each path has been individually specified.
> build: minor cleanup of bazel build rules

- packages/angular_devkit/build_angular/src/webpack/configs/common.ts
Webpack enabled top level await by default in version 5.83.0. (See: https://github.com/webpack/webpack/releases/tag/v5.83.0)
This commit restores the previous behaviour, as top level await is not supported due to Zone.js issues.
> refactor: disable Webpack `topLevelAwait`

- .circleci/dynamic_config.yml
- .github/workflows/lint.yml
The eslint CI action has now been moved to a Github Action.
The check also now adds annotations to the PR code when eslint generates an error
or warning. Additionally, the eslint cache is saved and reused which provides improved
runtimes for the CI action.
> ci: add initial Github Action lint workflow

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/angular-compilation.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/aot-compilation.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/jit-compilation.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/watcher.ts
When using the esbuild-based browser application builder in watch mode, all files referenced by the TypeScript program are now watched in additional to files within the project root. This allows for more extensive monorepo setups to take advantage of watch mode as TypeScript files may exist in other library projects within the repository.
> fix(@angular-devkit/build-angular): watch all TypeScript referenced files in esbuild builder

- CHANGELOG.md
> docs: release notes for the v16.0.3 release

- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/test/hello-world-app/tsconfig.json
- packages/angular_devkit/build_angular/test/hello-world-lib/tsconfig.json
- packages/angular_devkit/build_webpack/test/angular-app/tsconfig.json
- packages/angular_devkit/build_webpack/test/basic-app/tsconfig.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
- packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
- yarn.lock
Bumps up the dev dependencies to TypeScript 5.1-beta and expands the allowed version ranges to prepare for the final release.
> build: update to TypeScript 5.1

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/angular/aot-compilation.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/behavior/stylesheet_autoprefixer_spec.ts
The Angular compiler generates two types of metadata calls when it generates AOT code. This metadata is not used in fully AOT compiled applications and can contain direct references to components, services, etc. that may affect the output chunk layout of the application. While this currently has not lead to any problems, it could in the future and the Webpack bundler already performs a transform that preemptively removes these calls. To remain consistent, the esbuild-based build system will now also perform this transform.
This also updates the autoprefixer behavior tests to check the actual runtime style text
instead of the style text within the metadata calls.
> fix(@angular-devkit/build-angular): preemptively remove AOT metadata in esbuild builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/options.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
When using the development server with the esbuild-based browser application builder, the underlying
Vite server will now prebundle packages present in an application. During the prebundling process,
the Angular linker will also be invoked to ensure that APF packages are processed for AOT usage.
The Vite prebundling also provides automatic persistent caching of processed packages. This allows
reuse of processed packages across `ng serve` invocations. To support the use of prebundling at the
development server level, all packages are considered external from the build level. The first time
a package is used within an application there may be a short delay upon accessing the page as the
package is processed. Due to the persistent nature of the prebundling, the `ng cache` command is used
to …
> feat(@angular-devkit/build-angular): support dev-server package prebundling with esbuild builder

- CHANGELOG.md
> docs: release notes for the v16.0.4 release

- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html_spec.ts
- packages/angular_devkit/build_angular/src/utils/index-file/index-html-generator.ts
The index HTML generation functionality for both the Webpack-based and esbuild-based browser application builder now supports adding link hint elements to the generated output. This includes `prefetch`, `preload`, `modulepreload`, `preconnect`, and `dns-prefetch` hint modes. This functionality is not yet used by builds and will be integrated within future changes.
> refactor(@angular-devkit/build-angular): add internal support for index HTML link hints

- packages/schematics/angular/private/standalone.ts
- packages/schematics/angular/utility/ast-utils.ts
- packages/schematics/angular/utility/ast-utils_spec.ts
- packages/schematics/angular/utility/index.ts
- packages/schematics/angular/utility/standalone/app_config.ts
- packages/schematics/angular/utility/standalone/code_block.ts
- packages/schematics/angular/utility/standalone/index.ts
- packages/schematics/angular/utility/standalone/rules.ts
- packages/schematics/angular/utility/standalone/rules_spec.ts
- packages/schematics/angular/utility/standalone/util.ts
These changes add the necessary APIs that library authors can use to create `ng add` schematics that don't need to account for whether a project is NgModule-based or standalone. They're split up across a few commits to make reviewing easier. High-level description of the commits:
1. `refactor(@schematics/angular): allow for imports to be inserted under an alias` - Expands the `insertImport` utility to allow for aliases to be specified. This is necessary to avoid naming conflicts when automatically adding imports. I've also added some tests for `insertImport` since it didn't have any test coverage.
2. `refactor(@schematics/angular): add utility to find top-level identifiers` - Adds a utility that can be used to find whether a file has a top-level identifier with a specific name. Useful …
> APIs for authoring bootstrap-agnostic ng add schematics

- CHANGELOG.md
> docs: release notes for the v16.0.5 release

- README.md
- scripts/templates/readme.ejs
> docs: updated the i tag to the em tag in the html and docs

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/behavior/index-preload-hints_spec.ts
When using the esbuild-based browser application builder, the pre-existing initial file analysis is now used to generate preload hints for any transitive initial files required by the application. These hints are generated for both the initial JavaScript chunks and any initial global stylesheets that may be present. These hints provide additional information to the browser so that it can start and better prioritize fetching of files needed to start the application.
> feat(@angular-devkit/build-angular): add preload hints based on transitive initial files

- packages/angular_devkit/build_angular/src/babel/webpack-loader.ts
- packages/angular_devkit/build_angular/src/utils/normalize-asset-patterns.ts
- packages/angular_devkit/build_angular/src/utils/normalize-file-replacements.ts
> refactor: replaced the String wrapper object with primitive type string

- packages/angular_devkit/build_angular/src/builders/dev-server/load-proxy-config.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/proxy-config_spec.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
When using the Webpack-based browser application builder with the development server, the proxy configuration can be in an array form when using the `proxyConfig` option. This is unfortunately not natively supported by the Vite development server used when building with the esbuild-based browser application builder. However, the array form can be transformed into the object form. This transformation allows for the array form of the proxy configuration to be used by both development server implementations.
> fix(@angular-devkit/build-angular): support proxy configuration array-form in esbuild builder

- CHANGELOG.md
> docs: release notes for the v16.0.6 release

- packages/angular/pwa/package.json
- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/utility/latest-versions.ts
- packages/schematics/angular/utility/latest-versions/package.json
(cherry picked from commit d4a2849010f5151bf7ad2bd390d1ec0a8b26a0f5)
Manual cherry pick of https://github.com/angular/angular-cli/pull/25373 because I accidentally targeted `minor` instead of `rc`.
> build: bump versions for minor release

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
This is in an effort to reduce errors like `"Unknown version 114 of edge (While processing: "base$0$0")"` which are caused by mismatching versions.
Closes #25377
> fix(@angular-devkit/build-angular): unpin and downgrade `browserslist`

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/behavior/stylesheet_autoprefixer_spec.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/aot-compilation.ts
These changes are causing imported types to be incorrectly retained.
This reverts commit https://github.com/angular/angular-cli/commit/c462d9cb90377342980384c6bccb3ddfef533282.
> Revert "fix(@angular-devkit/build-angular): preemptively remove AOT metadata in esbuild builder"

- packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
esbuild 0.18.2 contains a fix that removes the need for the workaround of disabling support for static class blocks.
Related issue: https://github.com/evanw/esbuild/issues/2950
> refactor(@angular-devkit/build-angular): remove unneeded static block workaround

- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
Currently, for RxJS v6, no conditions are available, and the ESBuild pipeline will select the
ES5 distribution based on the `module` main field. This is fine in most cases, but applications
could benefit from better optimization with the use of the ES2015 output + there are certain
code differences that currently would cause runtime breakages when e.g. `rxjs/testing` is used.
See: https://github.com/angular/angular-cli/issues/25405 for more details.
Fixes #25405.
> fix(@angular-devkit/build-angular): experimental esbuild pipeline, add `es2015` to main fields for RxJS v6 compatibility

- packages/angular_devkit/build_angular/src/tools/esbuild/angular/aot-compilation.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/watcher.ts
When using the esbuild-based browser application builder in watch mode (including `ng serve`), all input files provided by the bundler via the internal metafile information will now be watched and will trigger rebuilds if changed. This allows for files outside of the TypeScript compilation that are also outside of the project source root to be watched. This situation can be encountered in monorepo setups where library code is directly referenced within an application.
> fix(@angular-devkit/build-angular): watch all bundler provided inputs with esbuild builder

- CHANGELOG.md
> docs: release notes for the v16.1.1 release

- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
When using prebundling with the Vite-based development server, the angular linker will now correctly emit JIT module scope information. This information is required in JIT mode for NgModules to successfully be used in an application.
> fix(@angular-devkit/build-angular): allow linker JIT support with prebundling with esbuild builder

- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
The development `NG_BUILD_MANGLE` environment variable is now supported when using the esbuild-based browser application builder. This environment variable is intended only for Angular CLI development and test purposes.
Closes: #25412
> refactor(@angular-devkit/build-angular): allow NG_BUILD_MANGLE variable with esbuild builder

- renovate.json
Webpack 5.88.0+ currently causes failures during i18n builds and prevents CI from passing. This is causing a block on renovate from updating all minor dependencies. While an investigation into the problem is in progress, the Webpack version is now added to the Renovate ignore list to allow other dependencies updates to occur.
> build: temporarily block Webpack version updates

- renovate.json
The issue appears to be related to esbuild/terser optimization and not webpack.
This reverts commit 78d1010967b21949688fa269f8a9ee7ae5fcd348.
> Revert "build: temporarily block Webpack version updates"

- packages/angular_devkit/build_angular/src/builders/application/tests/behavior/index-preload-hints_spec.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts
- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html_spec.ts
- packages/angular_devkit/build_angular/src/utils/index-file/index-html-generator.ts
When a preload hint is added for a stylesheet that is referenced via an `@import` that has an URL that does not contain a file extension, an `as` attribute is now correctly added to the hint to ensure that the stylesheet is loaded properly. This case can happen when a font service URL is imported within a initial stylesheet.
> fix(@angular-devkit/build-angular): ensure preload hints for external stylesheets are marked as styles

- packages/angular_devkit/build_angular/src/tools/webpack/configs/common.ts
- packages/angular_devkit/build_angular/src/tools/webpack/plugins/javascript-optimizer-plugin.ts
- packages/angular_devkit/build_angular/src/tools/webpack/plugins/javascript-optimizer-worker.ts
This option is no longer needed due to the changes done in the forked version of Domino.
> refactor: remove `keepNames` esbuild option for server builds

- packages/angular_devkit/build_angular/src/builders/application/tests/behavior/angular-aot-metadata_spec.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/angular-compilation.ts
The esbuild plugin used within the esbuild-based browser application builder will not use the newly introduced internal `supportTestBed` AOT compiler option to disable the emit of class metadata functions within the output code. This removes the need to perform an additional transformation of the AOT compiler generated code to immediately remove the class metadata. The class metadata is only needed when using TestBed with AOT generated code but testing infrastructure within the CLI only performs unit-testing in JIT mode. In the future event that AOT enabled unit-testing is supported, this compiler option can be enabled for test related builds.
> refactor(@angular-devkit/build-angular): configure AOT compiler to skip class metadata in esbuild

- packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer-worker.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
As of esbuild v0.18.8, async generators can be downleveled when not supported. This improvement allows for the removal of the babel plugins to perform the async generator downleveling that were previously used. This can provide a performance benefit for cases of async generator usage in application and third-party library code.
> refactor(@angular-devkit/build-angular): use built-in async generator downleveling in esbuild

- .circleci/dynamic_config.yml
- package.json
- packages/angular/cli/package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
All direct usages of the `semver` package have been updated to address https://github.com/advisories/GHSA-c2qf-rxjj-qqgw. The `semver` package is only used as a development dependency and not included in built application code within generated projects. This update does not affect any transitive usages of `semver` and any such usages would need to be handled by relevant upstream packages.
> [14.2.x] fix(@angular/cli): update direct semver dependencies to 7.5.3

- CHANGELOG.md
> docs: release notes for the v14.2.12 release

- packages/angular/pwa/package.json
- packages/angular_devkit/build_angular/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/utility/latest-versions/package.json
This is needed as the release check are failing due to incorrect peer deps.
> build: update Angular peer dependencies to `^16.0.0`

- package.json
- packages/angular/cli/package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
All direct usages of the `semver` package have been updated to address https://github.com/advisories/GHSA-c2qf-rxjj-qqgw. The `semver` package is only used as a development dependency and not included in built application code within generated projects. This update does not affect any transitive usages of `semver` and any such usages would need to be handled by relevant upstream packages.
> [15.2.x] fix(@angular/cli): update direct semver dependencies to 7.5.3

- packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts
Postcss's directory dependency message can use a glob pattern to reflect that multiple files within a given directory should be watched. When calculated the complete file set, the paths must be absolute to ensure that the watch system correctly invalidates the stylesheet being processed.
> fix(@angular-devkit/build-angular): use absolute watch paths for postcss dependency messages

- CHANGELOG.md
> docs: release notes for the v16.1.3 release

- packages/angular_devkit/build_angular/src/tools/esbuild/global-scripts.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/load-result-cache.ts
When using the esbuild-based application builder, some plugins may return watch file lists that contain POSIX paths on Windows systems. This can cause the file watcher to not correctly invalidate files that need to be processed during a rebuild. All watch files are now normalized prior to being added to the in-memory cache to avoid this problem.
> fix(@angular-devkit/build-angular): normalize paths in loader cache with esbuild

- packages/angular_devkit/build_angular/src/builders/application/options.ts
- packages/angular_devkit/build_angular/src/builders/application/schema.json
- packages/angular_devkit/build_angular/src/builders/application/tests/options/output-hashing_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/bundle-options.ts
This `resourcesOutputPath` option is removed from the application builder. Instead the CSS resources will always be emitted in a directory named `media`. This is preparation to output server and browser bundles in different directories.
> refactor(@angular-devkit/build-angular): remove `resourcesOutputPath` option from application builder.

- tests/legacy-cli/e2e_runner.ts
Previously, the ignore was as a string, but this breaks with the last `fast-glob` update.
See: https://app.circleci.com/pipelines/github/angular/angular-cli/31919/workflows/7d68deac-000e-46ef-80f8-4dc259ef61fa/jobs/428958
> test: convert e2e_runner `ignore` to array

- CHANGELOG.md
> docs: release notes for the v16.1.4 release

- WORKSPACE
- package.json
- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/builders/app-shell/render-worker.ts
- packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
- packages/angular_devkit/build_angular/src/builders/application/options.ts
- packages/angular_devkit/build_angular/src/builders/application/schema.json
- packages/angular_devkit/build_angular/src/builders/application/tests/options/app-shell_spec.ts
- packages/angular_devkit/build_angular/src/builders/application/tests/options/server_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
- packages/angular_devkit/build_angular/src/builders/jest/index.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts
- packages/angular_devkit/build_angular/src/utils/ssg/esm-in-memory-file-loader.ts
- packages/angular_devkit/build_angular/src/utils/ssg/render-worker.ts
- packages/angular_devkit/build_angular/src/utils/ssg/render.ts
- packages/angular_devkit/build_angular/test/hello-world-app/src/main.server.ts
- yarn.lock
This commit introduces experimental support to pre-render (SSG) and app-shell generation to the new application builder.
- `appShell`: option which can have a value of `true` or `false` has been added to support generating an app-shell.
- `prerender`: option which can have a value of `true`, `false` or an object with the below listed properties can be used to static render pages;
- `routes`: Array of routes to render.
- `discoverRoutes`: Whether the builder should statically discover routes.
- `routesFile`: The path to a file containing routes separated by newlines.
> feat(@angular-devkit/build-angular): add pre-rendering (SSG) and App-shell support generation to application builder     

- packages/angular/cli/bin/ng.js
There is a separate, internal version of the Angular CLI which should be used instead. Running this version can lead to unintuitive and unexpected behavior. This commit intentionally does not include an opt-out because there is no supported use case for running the external CLI inside google3. If someone is broken by this and presents a compelling use case, we can reconsider and add an opt-out for this check.
> fix(@angular/cli): throw an error when executed in a google3-context

- .prettierrc
- package.json
- packages/angular_devkit/build_angular/src/tools/babel/plugins/adjust-static-class-members_spec.ts
- packages/angular_devkit/build_angular/src/tools/babel/plugins/adjust-typescript-enums_spec.ts
- packages/angular_devkit/build_angular/src/tools/babel/plugins/elide-angular-metadata_spec.ts
- packages/angular_devkit/build_angular/src/tools/babel/plugins/pure-toplevel-functions_spec.ts
- yarn.lock
Tests that used prettier for assertions were updated to reflect the new prettier promise-based API.
> build: update prettier to v3.0.0

- packages/angular_devkit/build_angular/src/tools/babel/presets/application.ts
The `browserslist` package is only needed in the custom Babel application preset if the `supportedBrowsers` option is specified. This option is not used within the esbuild-based browser application builder. The `browserslist` is now lazily imported only when needed and avoids the overhead of loading browser support data when not needed by the build.
> perf(@angular-devkit/build-angular): only load browserslist in babel preset if needed

- packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
- packages/angular_devkit/build_angular/src/builders/application/options.ts
- packages/angular_devkit/build_angular/src/builders/application/schema.json
- packages/angular_devkit/build_angular/src/builders/application/tests/options/server_spec.ts
- packages/angular_devkit/build_angular/src/builders/application/tests/options/ssr_spec.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
- packages/angular_devkit/build_angular/src/utils/ssg/render-worker.ts
- tests/legacy-cli/e2e_runner.ts
This commit adds an `ssr` option to the application builder, this can be either a `boolean` or an `object` with an `entryPoint` property.
In the future, server bundles will only be emitted when the ssr option is truthy, as unlike SSR, SSG and AppShell do not require the server bundles to be written to disk.
>  feat(@angular-devkit/build-angular): add `ssr` option in application builder

- packages/angular_devkit/build_angular/src/tools/esbuild/angular/angular-host.ts
When overriding module resolution on a TypeScript Host object, TypeScript will not automatically create a resolution cache for the Host. Within the application build system the TypeScript resolution is only overrided if file replacements are used. A resolution cache is now manually created and added to the TypeScript Host when file replacements are present.
> refactor(@angular-devkit/build-angular): ensure TS resolution cache with file replacements

- packages/angular/cli/src/commands/version/cli.ts
This commit add `zone.js` to the `ng version` command output.
> fix(@angular/cli): add `zone.js` to `ng version` output

- renovate.json
This reverts commit 5651d4056644134e5373ebed5c4e252db3087027 as quicktype issue has been resolved.
See: https://github.com/quicktype/quicktype/issues/2325
> Revert "ci: disable update of `quicktype-core`"

- packages/angular_devkit/build_angular/src/builders/application/tests/behavior/angular-aot-metadata_spec.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/angular-compilation.ts
The esbuild plugin used within the esbuild-based browser application builder will now use the newly introduced internal `supportJitMode` AOT compiler option to disable the emit of NgModule scope metadata functions within the output code. This removes the need to perform an additional transformation of the AOT compiler generated code to immediately remove the metadata. The Angular CLI neither previously nor currently supports hybrid AOT/JIT mode. In the future if this support situation changes, additional behavior may be added control the internal `supportJitMode` option.
> refactor(@angular-devkit/build-angular): configure AOT compiler to skip NgModule scope metadata emit in esbuild

- packages/angular_devkit/build_angular/src/tools/babel/plugins/adjust-typescript-enums.ts
- packages/angular_devkit/build_angular/src/tools/babel/plugins/adjust-typescript-enums_spec.ts
When optimizing a CommonJS exported enum, the build optimizer enum wrapping pass was previously dropping the `exports` object assignment from the enum wrapper function call expression. This would not occur with application code but is possible with library code that was built with TypeScript and shipped as CommonJS.
Assuming the following TypeScript enum:
```
export enum ChangeDetectionStrategy {
OnPush = 0,
Default = 1,
}
```
TypeScript 5.1 will emit an exported enum for CommonJS as follows:
```
exports.ChangeDetectionStrategy = void 0;
var ChangeDetectionStrategy;
(function (ChangeDetectionStrategy) {
ChangeDetectionStrategy[ChangeDetectionStrategy["OnPush"] = 0] = "OnPush";
ChangeDetectionStrategy[ChangeDetectionStrategy["Default"] = 1] = "Default";
})(ChangeDetectionStrategy || …
```
> fix(@angular-devkit/build-angular): correctly wrap CommonJS exported enums when optimizing

- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
- tests/legacy-cli/e2e/tests/basic/rebuild.ts
Currently, chunk names are determined by ESBuild. Some libraries may resolve to a name that is not in a format of `chunk.hash.mjs`. This causes Jest to run over the lib files and fail as it contains no test suite.
Fixes: #25189
The change sets chunk name pattern explicitly so that all `chunk`s are exluded by pattern from running tests over.
I didn't figure out how this could be covered by tests. I did run a local build & installation and verified on a sample project that `@azure/msal-angular` no longer creates a "StandardController" file. Instead, it's named as `chunk...` and hence is excluded from tests.
> fix(@angular-devkit/build-angular): Set chunk names explicitly

- packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/sass-language.ts
- packages/angular_devkit/build_angular/src/tools/sass/lexer.ts
- packages/angular_devkit/build_angular/src/tools/sass/rebasing-importer.ts
- packages/angular_devkit/build_angular/src/tools/sass/sass-service.ts
To correctly resolve a package based import reference in a Sass file with pnpm or Yarn PnP, the importer file path must be known. Unfortunately, the Sass compiler does not provided the importer file to import plugins. Previously to workaround this issue, all previously resolved stylesheets were tried as the importer path. This allowed the stylesheets to be resolved but it also could cause a potentially large increase in build time due to the amount of previous stylesheets that would need to be tried. To avoid the performance impact and to also provide more accurate information regarding the importer file, a lexer is now used to extract import information for a stylesheet and inject the importer file path into the specifier. This information is then extracted from the import specifier …
> perf(@angular-devkit/build-angular): inject Sass import/use directive importer information when resolving

- CHANGELOG.md
> docs: release notes for the v16.1.5 release

- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
- tests/legacy-cli/e2e/tests/basic/serve.ts
The underlying development server (Vite) for the application build system updated
its static file serving dependencies which resulted in the `@fs` special file URLs
supported by Vite to have a different format.  Previously, the paths were encoded
using `encodeURIComponent` but are now use `encodeURI`. The development server
integration with Vite will now use the matching encoding to allow build defined
assets to be correctly served.
> fix(@angular-devkit/build-angular): correctly load dev server assets with vite 4.4.0+

- packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css_spec.ts
These changes revert the performance improvement from https://github.com/angular/angular-cli/pull/24925/commits/e88aea65bdb66fa4e9c6ad580ff733642e1fb24c and add a test. The problem with the previous approach is that it assumes that a `link` tag processed by Critters will be preceded by a `style` tag that was inserted by Critters. This assumption might not necessarily be true if Critters is unable to resolve the content of the linked styles. Furthermore, I'm not sure if we need to optimize this code path to begin with, because it only does a shallow traversal of the `head` tag which is generally fast and is unlikely to have many direct descendants.
Fixes #25419.
> fix(@angular-devkit/build-angular): error during critical CSS inlining for external stylesheets

- CHANGELOG.md
> docs: release notes for the v16.1.6 release

- .github/workflows/ci.yml
CI was failing for the Node.js v18 test job when using the dev-infra setup task. To unblock PRs, the GHA checkout and node setup is now done directly.
> ci: temporarily use direct GHA checkout and setup node actions in test job

- .circleci/dynamic_config.yml
- .github/workflows/ci.yml
The newly introduce GHA CI build job has been augmented to build the release packages and, when run within a PR, upload the release packages at an artifact within the PR.
> ci: transfer PR package artifact storage to GHA

- CHANGELOG.md
> docs: release notes for the v16.1.7 release

- packages/angular_devkit/build_angular/BUILD.bazel
- tests/legacy-cli/e2e/tests/build/ts-standard-decorators.ts
Reduce the number of test shards for the browser builder from 50 to 10. 50 is more than needed and can cause excessive resource usage.
This fixes the OOM errors on CI for the test job.
> ci: reduce bazel test shards for browser builder test

- packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/sass-language.ts
Multiple calls to the `SassStylesheetLanguage`'s process function can lead to setting up multiple sass worker pools, only one of which is cleaned up after the esbuild application build.
The result is `ng build` hanging forever waiting for the workers to exit.
Prevent the race condition, thus setting up only one worker pool and allowing the process to exit gracefully.
> fix(@angular-devkit/build-angular): prevent race condition in setting up sass worker pool

- CHANGELOG.md
> docs: release notes for the v16.2.0-rc.1 release

- CHANGELOG.md
> docs: release notes for the v16.1.8 release

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
`resourcesOutputPath` option is not supported when using the esbuild based builder.
Closes #25658
> fix(@angular-devkit/build-angular): display warning when using `resourcesOutputPath` with esbuild builder

- packages/schematics/angular/app-shell/schema.json
- packages/schematics/angular/universal/schema.json
Remove deprecated unused options from schematics.
BREAKING CHANGE: App-shell and Universal schematics deprecated unused `appId` option has been removed.
> refactor(@schematics/angular): remove deprecated appId option

- .circleci/dynamic_config.yml
- .github/workflows/ci.yml
All E2E test runs are moved to Github Actions except:
* Windows E2E
* Snapshot E2E
> ci: partially move E2E tests to GHA

- tests/legacy-cli/e2e/tests/commands/builder-not-found.ts
- tests/legacy-cli/e2e/tests/generate/module/module-import.ts
Several of the older E2E tests that use regular expression based checks have been cleaned up by using string include checks where possible. Several regular expressions have also been simplified where possible.
> test: cleanup E2E test regular expressions

- packages/angular_devkit/build_angular/src/tools/sass/rebasing-importer.ts
- tests/legacy-cli/e2e/tests/build/styles/scss-partial-resolution.ts
When using the new developer preview application build system, Sass import/use usage that specifies a package is adjusted to contain the resolve directory to workaround Sass import plugin limitations. This resolve directory is now encoded to prevent the new specifier from looking like a URL with a scheme to the Sass compiler. This can occur on Windows when a drive letter is present (`C:\`).
> fix(@angular-devkit/build-angular): encode Sass package resolve directories in importer URLs

- packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
- packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-file-loader.ts
- packages/angular_devkit/build_angular/src/utils/server-rendering/prerender.ts
This commits, update the application builder and vite dev-server to be able to serve the app-shell and prerendered pages.
> fix(@angular-devkit/build-angular): update vite to be able to serve app-shell and SSG pages

- packages/angular_devkit/build_angular/src/builders/extract-i18n/application-extraction.ts
- packages/angular_devkit/build_angular/src/builders/extract-i18n/builder.ts
- tests/legacy-cli/e2e.bzl
- tests/legacy-cli/e2e/tests/i18n/extract-ivy-disk-cache.ts
- tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts
The `ng extract-i18n` command now supports using either the developer preview esbuild-based browser or application builders. Support for the existing Webpack-based build system has been maintained. The extraction process will now build the application based on the build target defined builder in the case of either `@angular-devkit/build-angular:browser-esbuild` and `@angular-devkit/build-angular:application`. In the case of the application builder, SSR output code generation is disabled to prevent duplicate messages for the same underlying source code.
> feat(@angular-devkit/build-angular): initial i18n extraction support for application builder

- packages/angular_devkit/build_angular/src/utils/package-chunk-sort.ts
- [] Refactoring (no functional changes, no api changes)
The type is incorrect
The type is correct
> fix(@angular-devkit/build-angular): use correct type for `extraEntryPoints`

- packages/angular_devkit/core/BUILD.bazel
- packages/angular_devkit/core/package.json
- packages/angular_devkit/core/src/virtual-fs/host/pattern.ts
The glob support in the `PatternMatchingHost` class now uses the capabilities of the `picomatch` package to convert glob strings into regular expressions. This removes custom string replacement code that previously was used. The `picomatch` package is already used by `@angular-devkit/build-angular` and is present in the repository but is a new dependency for the `@angular-devkit/core` package specifically.
Addresses https://github.com/angular/angular-cli/security/code-scanning/20 
Partially corrects #25731
> refactor(@angular-devkit/core): use picomatch for PatternMatchingHost glob support

- packages/angular/ssr/src/common-engine.ts
- packages/angular/ssr/src/inline-css-processor.ts
- packages/angular_devkit/build_angular/src/builders/prerender/render-worker.ts
- packages/angular_devkit/build_angular/src/builders/prerender/works_spec.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
This change updates the critical css processor to remove the need for a Polynomial regular expression.
Addresses: https://github.com/angular/angular-cli/security/code-scanning/51
Closes #25742
> refactor: remove polynomial regular expression

- packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts
Disabling certificate validation is strongly discouraged and is not required for inling of fonts.
Addresses https://github.com/angular/angular-cli/security/code-scanning/29
Closes #25731
> refactor(@angular-devkit/build-angular): remove disabling certificate validation when inlining fonts

- CHANGELOG.md
> docs: release notes for the v16.2.1 release

- scripts/release-checks/dependency-ranges/peer-deps-check.mts
Prior, to this change when a new major prerelease the check did not allow `^17.0.0 || ^17.0.0-next.0`.
> build: update peer deps check to support stable versions when cutting a major prerelease

- packages/angular_devkit/build_angular/src/builders/application/options.ts
The esbuild-based application builder will now access the project level i18n configuration as well as the builder `localize`, `duplicateTranslationBehavior`, and `missingTranslationBehavior` options to construct a full, normalized i18n option structure. These options are not yet used by the builder but they are now available to access as future work incrementally adds i18n support.
> refactor(@angular-devkit/build-angular): normalize i18n options for application builder

- goldens/public-api/angular_devkit/schematics/testing/index.md
- packages/angular_devkit/schematics/testing/schematic-test-runner.ts
BREAKING CHANGE: deprecated `runExternalSchematicAsync` and `runSchematicAsync` methods have been removed in favor of `runExternalSchematic` and `runSchematic`.
> refactor(@angular-devkit/schematics): remove deprecated `runExternalSchematicAsync` and `runSchematicAsync`

- packages/angular/cli/src/commands/build/long-description.md
The Angular CLI does not accept camelCase args.
> docs(@angular/cli): update outdated statement about CLI accepting camelCase

- packages/angular_devkit/build_angular/src/tools/babel/plugins/elide-angular-metadata.ts
- packages/angular_devkit/build_angular/src/tools/babel/plugins/elide-angular-metadata_spec.ts
- packages/angular_devkit/build_angular/src/tools/babel/plugins/pure-toplevel-functions.ts
- packages/angular_devkit/build_angular/src/tools/babel/plugins/pure-toplevel-functions_spec.ts
- packages/ngtools/webpack/src/transformers/remove-ivy-jit-support-calls.ts
- packages/ngtools/webpack/src/transformers/remove-ivy-jit-support-calls_spec.ts
There's some new output coming from the Angular compiler. These changes update the various custom transformers to account for it. It includes:
1. Emitting calls to `setClassMetadataAsync` instead of `setClassMetadata` for components that use the new `defer` block syntax.
2. Using arrow functions instead of function expressions for IIFEs. This isn't merged yet, but is being explored in https://github.com/angular/angular/pull/51637.
> Account for new compiler output in custom tranformers

- .circleci/dynamic_config.yml
- .github/workflows/ci.yml
The E2E snapshot tests have now been migrated to use Github Actions instead
of CircleCI. The CircleCI jobs and workflow configuration for the test execution
have also been removed. The CircleCI dynamic configuration aspects are still
present to minimize the changeset complexity and will be removed in a future
change.
The snapshot tests are guarded by a new analyze job which checks for a change
to the `tests/legacy-cli/e2e/ng-snapshot/package.json` file which is used to
store the snapshot commit SHAs for the relevant Angular packages used in tests.
This job based guard approach allows the entire set of snapshot E2E jobs to be
skipped when not required. Additionally, a single skipped PR status entry is
created.
> ci: move snapshot E2E tests to GHA

- tests/legacy-cli/e2e/tests/misc/npm-7.ts
To avoid project installation errors when running the `npm-7` E2E test, the previous semver range of `>7.5.6` has been instead set to a fixed `8.0.0`. This ensures consistency within the test as now a known version of npm will be used.
This E2E test started failing recently due to the release of npm 10 which some packages do not support via the `engines` field. This situation in turn caused project install failures when the new version of npm was attempted to be installed in the test.
> test: install specific npm version in npm version E2E test

- packages/angular_devkit/build_angular/src/builders/application/schema.json
- packages/angular_devkit/build_angular/src/builders/application/tests/options/output-hashing_spec.ts
- packages/angular_devkit/build_angular/src/builders/application/tests/options/polyfills_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/jest/schema.json
This commit updates the polyfills options in application builder to support only an array of string as value.
> refactor(@angular-devkit/build-angular): update polyfills option in application builder to be only an array.

- packages/angular/ssr/package.json
This is necessary for Wombat publishing. Normally most packages have this generated at build time through `pkg_npm`, however we need to use `ng_package` in this case which does not do this by default.
> build: add `repository` field to `@angular/ssr` package

- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
By setting up a single instance of the `JavaTransformer`, the Vite-based development server will now have a fixed and controllable number of worker threads available to process prebundling requests. This avoids a potentially large number of initial worker threads when a new application with a large number of dependencies is first used with the development server. This is particularly beneficial for web container setups which may not be able to efficiently handle the number of workers.
> perf(@angular-devkit/build-angular): use single JS transformer instance during dev-server prebundling

- packages/angular/ssr/src/inline-css-processor.ts
- packages/angular_devkit/build_angular/src/builders/prerender/utils.ts
- packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
- tools/defaults.bzl
- tsconfig.json
The JavaScript generated for the published packages is now using ES2022. This removes additional downleveling of code that was previously necessary to use newer features.
The minimum Node.js version of 18.13 provides support for the needed features. While this change does require a patch to `@bazel/concatjs` to allow the target to be set to `ES2022`, this patch is now already required by the migration of the universal repository into the CLI repository.
> build: update package output to use ES2022

- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
When using the Vite-based development server and a custom `index` build option (not `index.html`), the custom index path will now be used as the root of the development server. This mimics the behavior of the Webpack-based development server.
Fixes: #25806
> fix(@angular-devkit/build-angular): support custom index option paths in Vite-based dev server

- packages/angular/pwa/README.md
Issue Number: #25490 
Readme for @angular/pwa package is outdated and has typos
Closes #25490 
Updated readme for @angular/pwa package
> docs: update @angular/pwa readme

- packages/angular/cli/src/commands/e2e/cli.ts
Running `ng e2e` suggests `Cypress`, `Nightwatch`, `WebdriverIO`. 
Running `ng e2e` suggests Puppeteer as an option to for e2e testing. 
Ref package: [@puppeteer/ng-schematics](https://www.npmjs.com/package/@puppeteer/ng-schematics)
Ref docs: [pptr.dev](https://pptr.dev/ng-schematics)
> docs(@angular/cli): Add Puppeteer schematics to e2e command

- tests/legacy-cli/verdaccio.yaml
- tests/legacy-cli/verdaccio_auth.yaml
`logs` has been deprecated in favor of `log`
> refactor: replace deprecated `logs` verdaccio setting

- packages/angular_devkit/build_angular/src/builders/browser/index.ts
- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts
- packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html_spec.ts
- packages/angular_devkit/build_angular/src/utils/index-file/index-html-generator.ts
- packages/ngtools/webpack/src/index.ts
- packages/ngtools/webpack/src/ivy/index.ts
- packages/ngtools/webpack/src/ivy/plugin.ts
- packages/ngtools/webpack/src/ivy/transformation.ts
- packages/ngtools/webpack/src/transformers/find_image_domains.ts
- packages/ngtools/webpack/src/transformers/find_image_domains_spec.ts
This PR adds new functionality to identify image domains used in [NgOptimizedImage](https://angular.io/api/common/NgOptimizedImage) loaders, and automatically add `link rel="preload"` tags to the index.html file for those domains, if the end-user isn't already managing their own preconnects. I designed this change with some substantial help from @alan-agius4 and @clydin. ATTN: @kara @AndrewKushnir 
How domains are identified:
Image domains are identified during the Typescript transformation process, where application Typescript files are already being traversed as an AST multiple times. This PR adds a new, non-modifying transformer, which conducts a narrow traversal of the AST to find image domains in the code. The traversal looks like this:
1) Starting at the root of the file, do a …
> feat(@ngtools/webpack): add automated preconnects for image domains

- packages/angular_devkit/build_angular/src/tools/esbuild/angular/jit-resource-transformer.ts
- packages/ngtools/webpack/src/transformers/replace_resources.ts
- packages/ngtools/webpack/src/transformers/replace_resources_spec.ts
Updates the JIT transformers to account for the upcoming changes from https://github.com/angular/angular/pull/51715.
> Account for string literals in styles and the new styleUrls

- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
This is no longer needed as `zone.js` now has proper package exports.
> refactor(@angular-devkit/build-angular): remove deep import of `zone.js/node`

- CHANGELOG.md
> docs: release notes for the v16.2.2 release

- CHANGELOG.md
- package.json
(cherry picked from commit 6a89dbea26e50eb6f1d2e09e4fb7dbe1b923b802)
> release: cut the v17.0.0-next.4 release

- packages/angular_devkit/build_angular/src/tools/esbuild/rxjs-esm-resolution-plugin.ts
Previously, the path matching and replacement did not consider non posix file systems like windows.
> fix(@angular-devkit/build-angular): correctly re-point RXJS to ESM on Windows

- tests/legacy-cli/e2e.bzl
This commits adds the entire `tests/commands/add` directory to be tested with esbuild.
> test(@angular/cli): test all `ng add` in the esbuild pipeline

- packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-file-loader.ts
- packages/angular_devkit/build_angular/src/utils/server-rendering/prerender.ts
This commit fixes several Windows issues in the prerendering pipeline. Primarily due to path normalization and other Windows only constraints.
> fix(@angular-devkit/build-angular): several windows fixes to application builder prerendering

- .github/workflows/ci.yml
Use the head_ref value for the concurrency group on `ci` rather than the ref, so that the main ref is not used and cancelling across pull requests and the main branch
Backport https://github.com/angular/angular/pull/51784 to the CLI.
> ci: use `head_ref` for concurrency group

- .github/workflows/ci.yml
Reverts angular/angular-cli#25847
> Revert "ci: use `head_ref` for concurrency group"

- packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
The terser build time constant import from the `@angular/compiler-cli` package is no longer used in the esbuild-based builder. The constants present are already defined and conditionally added within the build configuration itself. This not only provides more flexibility but also removes the need to import the package early in the process. The import is also an expensive import due to it needing TypeScript and being ESM that needs to be dynamically imported via a function helper to work around current ESM/TypeScript/CommonJS limitations.
> refactor(@angular-devkit/build-angular): remove usage of terser constants in esbuild

- packages/schematics/angular/application/files/standalone-files/src/app/app.config.ts.template
There's empty space after provideRouter();
No empty space
> refactor(@schematics/angular): remove empty space in app.config.ts.template

- packages/ngtools/webpack/src/paths-plugin.ts
fix a recursion in webpack resolve when resolving absolute paths on windows
When using wildcard in tsconfiig.json paths on windows webpack-dev-server fail with the following error
```
./node_modules/webpack-dev-server/client/socket.js:10:7-36 - Error: Module not found: Error: Recursion in resolving
Stack:
resolve: (C:\Users\athor\OneDrive\Bureau\stackblitz-starters-6juerj\node_modules\webpack-dev-server\client) C:\Users\athor\OneDrive\Bureau\stackblitz-starters-6juerj\node_modules\webpack-dev-server\client\clients\WebSocketClient.js
parsedResolve: (C:\Users\athor\OneDrive\Bureau\stackblitz-starters-6juerj\node_modules\webpack-dev-server\client) …
```
> fix(@ngtools/webpack): fix recursion in webpack resolve

- packages/angular/ssr/schematics/ng-add/index.ts
- packages/angular_devkit/build_angular/src/builders/application/options.ts
- packages/angular_devkit/build_angular/src/builders/application/schema.json
- packages/angular_devkit/build_angular/src/builders/application/tests/options/ssr_spec.ts
This is to align with the `serviceWorker` option.
> refactor(@angular-devkit/build-angular): accept boolean and string in `ssr` option

- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
This commit changes the way that global style updates are applied when using `vite`.  When either live-reload or hmr are enabled the styles are replaced in placed (HMR style) without a live-reload.
> feat(@angular-devkit/build-angular): apply global CSS updates without a live-reload when using `vite`

- CHANGELOG.md
> docs: release notes for the v16.2.3 release

- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
- packages/angular_devkit/build_angular/src/utils/routes-extractor/extractor.ts
This commit updates the routes extractor to use the newly exported private `ɵloadChildren` method from the router to executes a `route.loadChildren` callback and return an array of child routes.
See: https://github.com/angular/angular/pull/51818
> refactor(@angular-devkit/build-angular): use `ɵloadChildren` helper from router package

- packages/angular_devkit/build_angular/src/tools/esbuild/angular/angular-host.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/aot-compilation.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/jit-compilation.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/web-worker-transformer.ts
When using the esbuild-based builders (`application`/`browser-esbuild`), Web Workers following the previously
supported syntax as used in the Webpack-based builder will now be discovered. The worker entry points are not
yet bundled or otherwise processed. Currently, a warning will be issued to notify that the worker will not
be present in the built output.
Additional upcoming changes will add the processing and bundling support for the workers.
Web Worker syntax example: `new Worker(new URL('./my-worker-file', import.meta.url), { type: 'module' });`
> feat(@angular-devkit/build-angular): initial support for application Web Worker discovery with esbuild

- tests/legacy-cli/e2e/tests/i18n/ivy-localize-hashes.ts
This update the regexp to account for the change in https://github.com/angular/angular-cli/pull/25877. A filename that has the hash included will be `main.[hash]` in Webpack and `main-[hash]` when using esbuild.
> test: update output regexp in i18n tests to account for change in filename

- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
When using the devserver, instead of prerendering every page for every incremental change, we now perform a server rendering on the page during request time. This ensures that incremental build times are faster when prerending is enabled as we avoid rendering of pages that are never viewed.
> perf(@angular-devkit/build-angular): disable ahead of time prerendering in vite dev-server

- packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/web-worker-transformer.ts
- tests/legacy-cli/e2e.bzl
- tests/legacy-cli/e2e/tests/build/worker.ts
When using the esbuild-based builders (`application`/`browser`), Web Workers that use the supported syntax will now be bundled. The bundling process currently uses an additional synchronous internal esbuild execution. The execution must be synchronous due to the usage within a TypeScript transformer. TypeScript's compilation process is fully synchronous. The bundling itself currently does not provide all the features of the Webpack-based builder. 
The following limitations are present in the current implementation but will be addressed in upcoming changes:
- Worker code is not type-checked
- Nested workers are not supported
> feat(@angular-devkit/build-angular): support basic web worker bundling with esbuild builders

- packages/angular/ssr/schematics/ng-add/index.ts
- packages/angular/ssr/schematics/utility/utils.ts
- packages/schematics/angular/server/index.ts
- packages/schematics/angular/server/index_spec.ts
This commits updates the internal server schematic that is used by SSR and AppShell schematics to include `provideClientHydration` in the list of providers, which causes hydration to be enabled for application.
For more information about `provideClientHydration`, see: https://angular.io/api/platform-browser/provideClientHydration
FYI @AndrewKushnir
>  feat(@schematics/angular): enable hydration when adding SSR, SSG or AppShell     

- packages/schematics/angular/workspace/files/package.json.template
This is to match all other Angular framework and Angular devkit dependencies
> fix(@schematics/angular): update `@angular/cli` version specifier to use `^`

- packages/angular/cli/package.json
This ensures that when the CLI is updates so is `@angular/ssr`
>     fix(@angular/cli): add `@angular/ssr` as part of the ng update `packageGroup`

- packages/schematics/angular/interceptor/schema.json
This commit updates the interceptor schematic to generate function intererceptors by default.
BREAKING CHANGE: `ng g interceptor` now generate a functional interceptor by default. or guard by default. To generate a class-based interceptor the `--no-functional` command flag should be used.
> feat(@schematics/angular): generate functional interceptors by default

- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
This commit disables logging `Angular is running in development mode.` when using SSR with vite dev-server. This to avoid polluting the server console with `Angular is running in development mode.` logs for each page load and reload.
Example:
```
ng s
Initial Chunk Files | Names         | Raw Size
main.js             | main          | 34.31 kB | 
polyfills.js        | polyfills     | 95 bytes | 
styles.css          | styles        | 95 bytes | 
| Initial Total | 34.49 kB
Application bundle generation complete. [5.205 seconds]
➜  Local:   http://localhost:4200/
Watch mode enabled. Watching for file changes...
Angular is running in development mode.
Angular is running in development mode.
Angular is running in development mode.
Angular is running in development mode.
Angular is running in …
```
> fix(@angular-devkit/build-angular): do not print `Angular is running in development mode.` in the server console when using dev-server

- packages/angular_devkit/build_angular/src/utils/routes-extractor/BUILD.bazel
- packages/angular_devkit/build_angular/src/utils/routes-extractor/extractor.ts
This commit refactors the route extractor to use the newly `whenStable` API.
> refactor(@angular-devkit/build-angular): use `whenStable` private API in route extractor

- tests/legacy-cli/e2e/tests/misc/safari-15-class-properties.ts
Safari v15 is longer included in the default browserlist configuration of CLI apps.
> test(@angular/cli): remove Safari 15 test

- packages/angular_devkit/schematics_cli/blank/project-files/package.json
- packages/angular_devkit/schematics_cli/schematic/files/package.json
- packages/schematics/angular/utility/latest-versions/package.json
Currently, running a schematics that adds `@types/node` to a project, like `ng add @angular/ssr`, will add the v16 types. 
As nodejs v16 is now EOL, this PR updates the types to v18.
> fix(@schematics/angular): use @types/node v18

- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
- packages/angular_devkit/build_angular/src/utils/server-rendering/main-bundle-exports.ts
- packages/angular_devkit/build_angular/src/utils/server-rendering/render-page.ts
This commit clean ups the compiled components state when the build is being executed in watch mode. This is required as otherwise during development `Component ID generation collision detected` are displayed on the server.
Closes: #25924
> fix(@angular-devkit/build-angular): clean up internal Angular state during rendering SSR

- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/index_spec.ts
- packages/schematics/angular/workspace/files/tsconfig.json.template
- tests/legacy-cli/e2e/tests/build/library-with-demo-app.ts
The `baseUrl` is no longer needed since NGCC has been removed. This also enables better auto-import suggestions.
Closes #18834
> fix(@schematics/angular): remove `baseUrl` from `tsconfig.json`

- packages/schematics/angular/application/files/common-files/src/app/app.component.html.template
Fixes that the starter template would've generated a compilation error in v17 after https://github.com/angular/angular/pull/51994 is released.
> fix(@schematics/angular): account for new block syntax in starter template

- packages/angular_devkit/build_angular/src/builders/application/build-action.ts
- packages/angular_devkit/build_angular/src/builders/application/index.ts
- packages/angular_devkit/build_angular/src/builders/application/tests/options/inline-style-language_spec.ts
- packages/angular_devkit/build_angular/src/builders/application/tests/setup.ts
- packages/angular_devkit/build_angular/src/testing/builder-harness.ts
To better capture file changes after the initial build for the esbuild-based builders in a programmatic usage, the file watching initialization has been moved to before the first build results are yielded. This allows tests that execute code to change files with improved accuracy of the watch mode triggering. The application builder now also supports aborting the watch mode programmatically. This allows tests to gracefully stop the watch mode and more fully cleanup the test at completion.
> refactor(@angular-devkit/build-angular): improve accuracy of programmatic watch mode usage for esbuild builders

- packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/aot-compilation.ts
To prevent stale Angular template diagnostics from persisting in watch mode (including `ng serve`), the template diagnostic cache will now be invalidated based on the set of changed external template files. This ensures that the Angular AOT compiler will analyze the template again during the rebuild and clear any fixed errors.
> fix(@angular-devkit/build-angular): clear diagnostic cache when external templates change with esbuild builders

- packages/schematics/angular/application/files/module-files/src/app/app.component.spec.ts.template
- packages/schematics/angular/application/files/standalone-files/src/app/app.component.spec.ts.template
- packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.spec.ts.template
- packages/schematics/angular/component/index_spec.ts
The defer block support introduces a new asynchronous form of the set class metadata Angular function. This form is needed to allow for providing metadata for dynamically imported deferred components. The asynchronous compileComponents call within TestBed is now used to initialize this metadata during unit tests. Unit tests that contain defer blocks must use this call prior to executing a test to allow templates containing defer to properly render. Existing tests that do not use the new defer block do not require modification unless the defer block is introduced into components used in the unit test.
> fix(@angular-devkit/build-angular): re-add TestBed compileComponents in schematics to support defer block testing

- packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
- packages/angular_devkit/build_angular/src/builders/application/i18n.ts
- packages/angular_devkit/build_angular/src/builders/application/index.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/i18n-inliner.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-app-shell-service-worker.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-app-shell.ts
When using the esbuild-based application build system through the `application` builder, the `localize` option will now allow inlining project defined localizations when using the app shell, prerendering, and service worker features. Previously a warning was issued and these features were disabled when the `localize` option was enabled.
> feat(@angular-devkit/build-angular): support i18n with service worker and app-shell with esbuild builders

- packages/angular_devkit/build_angular/src/builders/application/options.ts
- packages/angular_devkit/build_angular/src/builders/application/schema.json
- packages/angular_devkit/build_angular/src/builders/application/tests/options/named-chunks_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
The `application` builder does not support `namedChunks` yet.
This adds the support of `namedChunks` for the new `application` builder.
It generates output like the following:
```
Initial Chunk Files         | Names         |  Raw Size | Estimated Transfer Size
chunk-ACXUMF56.js           | -             |  94.14 kB |                28.25 kB
main-3WP5KDHR.js            | main          |  71.95 kB |                18.31 kB
polyfills-4UVFGIFL.js       | polyfills     |  32.85 kB |                10.68 kB
chunk-2XJVAMHT.js           | -             | 449 bytes |               449 bytes
styles-5INURTSO.css         | styles        |   0 bytes |                 0 bytes
| Initial …
```
> feat(@angular-devkit/build-angular): support namedChunks option in application builder

- renovate.json
Updates to `aspect_bazel_lib` currently breaks the build.
> ci: disable auto updates for `aspect_bazel_lib`

- package.json
- packages/angular_devkit/build_angular/package.json
- yarn.lock
Addresses npm audit report of https://github.com/advisories/GHSA-7fh5-64p2-3v2j
> fix(@angular-devkit/build-angular): update dependency postcss to v8.4.31

- CHANGELOG.md
> docs: release notes for the v16.2.5 release

- CHANGELOG.md
> docs: release notes for the v14.2.13 release

- CHANGELOG.md
> docs: release notes for the v15.2.10 release

- packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
This commit removed the hard coded Node.js version in application builder server config and instead passes the Angular CLI supported Node.js versions that are currently stamped using Bazel.
> refactor(@angular-devkit/build-angular): remove hardcoded Node.js version in application builder

- packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
- tests/legacy-cli/e2e/tests/build/worker.ts
The previous Web Worker bundling code for the esbuild-based builders assumed that the first output file was the JavaScript code for the worker. While this is typically the case, when sourcemaps are enabled it may not be. To ensure the code file is used as the replacement path for the Worker constructor, the output files are now searched for the code file.
> fix(@angular-devkit/build-angular): ensure Web Worker code file is replaced in esbuild builders

- packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
- packages/angular_devkit/build_angular/src/builders/application/options.ts
- packages/angular_devkit/build_angular/src/builders/application/tests/options/bundle-budgets_spec.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/budget-stats.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
- packages/angular_devkit/build_angular/src/utils/bundle-calculator.ts
The bundle budget functionality (`budgets` option) is not available when using the esbuild-based builders (`browser-esbuild`/`application`). The existing option format from the Webpack-based builder can continue to be used. All budget types except `anyComponentStyle` are implemented. Any usage of the `anyComponentStyle` type will be ignored when calculating budget failures. This type will be implemented in a future change.
> feat(@angular-devkit/build-angular): add initial support for bundle budgets to esbuild builders

- packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
- packages/angular_devkit/build_angular/src/builders/application/options.ts
- packages/angular_devkit/build_angular/src/builders/application/tests/options/bundle-budgets_spec.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/budget-stats.ts
- packages/angular_devkit/build_angular/src/utils/bundle-calculator.ts
The `anyComponentStyle` budget type is now supported when using bundle budgets in the esbuild-based builders (`browser-esbuild`/`application`). The configuration and behavior are intended to match that of the Webpack-based  builder (`browser`). With this addition, the bundle budget feature is now at feature parity with the Webpack-based builder. The implementation of this budget type requires less code than the Webpack implementation due to the component stylesheet information being present in the application's output metadata. This removes the need for a custom budget plugin to extract the stylesheet size information during the build.
> feat(@angular-devkit/build-angular): support component style budgets in esbuild builders

- packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/component-stylesheets.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/jit-plugin-callbacks.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/bundle-options.ts
When using the esbuild-based builders (`esbuild-browser`/`application`) in watch mode (including `ng serve`), component stylesheets will now be incrementally rebuilt when needed. This avoids a full build of each affected component's styles during an application rebuild. Both JIT and AOT mode are supported as well as both inline and external styles.
> perf(@angular-devkit/build-angular): use incremental bundling for component styles in esbuild builders

- packages/angular_devkit/build_angular/src/builders/application/index.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-ssr.ts
With the output path directory structure updates in place, the localize support for SSR has now been enabled. This allows for the `application` builder to produce both browser and server output that is localized based on the i18n configuration for the project.
> feat(@angular-devkit/build-angular): enable localize support for SSR with application builder

- tests/legacy-cli/e2e/tests/build/material.ts
- tests/legacy-cli/e2e/tests/commands/add/add-material.ts
- tests/legacy-cli/e2e/tests/misc/invalid-schematic-dependencies.ts
Re-enables Material tests that had to be disabled during the TS 5.2 update.
> build: re-enable Material tests

- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
Prior to this change, async/await in external packages were not being correctly downlevelled when using vite dev-server with cache enabled.
Closes #25985
> fix(@angular-devkit/build-angular): fully downlevel async/await when using vite dev-server with caching enabled

- packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
- packages/angular_devkit/build_angular/src/builders/application/tests/options/server_spec.ts
Prior to this change, a server build was performed when all the "server" features were disabled but the `server` fields was specified.
> perf(@angular-devkit/build-angular): only perform a server build when either prerendering, app-shell or ssr is enabled

- packages/angular_devkit/build_angular/src/builders/application/tests/behavior/typescript-rebuild-lazy_spec.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation-state.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
This commit improves the logic to block and share a TypeScript results across multiple esbuild instances (browser and server builds) which fixes an issue that previously during rebuilds in some cases did not block the build correctly.
> fix(@angular-devkit/build-angular): improve sharing of TypeScript compilation state between various esbuild instances during rebuilds

- packages/angular_devkit/build_angular/src/builders/dev-server/load-proxy-config.ts
When normalizing the proxy configuration for the Vite-based development server, the `pathRewrite` logic will now be skipped if the proxy entry is not an object and therefore invalid. This situation can occur if the proxy configuration JSON contains invalid properties.
Closes #25978
> fix(@angular-devkit/build-angular): avoid dev-server proxy rewrite normalization when invalid value

- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
When using the esbuild-based builders (`application`/`browser-esbuild`), the localize polyfill and the locale specifier for the configured source locale will now be injected into the application when available and the application is not configured to inline translations (`localize` option disabled or otherwise not used). This is useful for when developing a localized application with the development server or when the application is not translated but has a customized source locale.
> fix(@angular-devkit/build-angular): ensure localize polyfill and locale specifier are injected when not inlining

- packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-loader/loader-hooks.ts
- packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-loader/node-18-utils.ts
- packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-loader/register-hooks.ts
- packages/angular_devkit/build_angular/src/utils/server-rendering/prerender.ts
- packages/angular_devkit/build_angular/src/utils/server-rendering/render-worker.ts
- packages/angular_devkit/build_angular/src/utils/server-rendering/routes-extractor-worker.ts
This commit refactors the ESM Node.js in memory loader to work with Node.js 20+
> refactor(@angular-devkit/build-angular): update ESM in memory file loader to work with Node.js 20

- packages/angular_devkit/build_angular/src/builders/application/options.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/deploy-url_spec.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/compiler-plugin-options.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/global-styles.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/bundle-options.ts
The `browser-esbuild` builder now provides support for using the `deployUrl` option when building applications.  This option is still considered deprecated which is the same status as with the Webpack-based `browser` application builder. This option is only available with the `browser-esbuild` builder and not other esbuild-based builders. The `browser-esbuild` builder is primarily intended to be used as a compatibility builder with the `browser` builder that requires only minimal changes to use.
> feat(@angular-devkit/build-angular): support deploy URL option for `browser-esbuild` builder

- goldens/public-api/angular_devkit/build_angular/index.md
- packages/angular_devkit/build_angular/src/builders/application/tests/behavior/typescript-rebuild-lazy_spec.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/options.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
- packages/angular_devkit/build_angular/src/builders/dev-server/tests/setup.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/webpack-server.ts
- packages/angular_devkit/build_angular/src/builders/extract-i18n/application-extraction.ts
- packages/angular_devkit/build_angular/src/builders/extract-i18n/builder.ts
- packages/angular_devkit/build_angular/src/builders/extract-i18n/options.ts
- packages/angular_devkit/build_angular/src/builders/extract-i18n/schema.json
- packages/angular_devkit/build_angular/src/builders/extract-i18n/webpack-extraction.ts
- packages/angular_devkit/build_angular/src/utils/build-options.ts
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-17/update-workspace-config.ts
- packages/schematics/angular/migrations/update-17/update-workspace-config_spec.ts
This is to better match the nature of the application builder where the target can be both browser and server.
DEPRECATED: The `browserTarget` in the dev-server and extract-i18n builders have been deprecated in favor of `buildTarget`.
> feat(@angular-devkit/build-angular): add `buildTarget` option to dev-server and `extract-i18n` builders

- packages/angular_devkit/build_angular/src/builders/protractor/index.ts
Protractor is no longer deprecated, it's already end-of-life. I didn't commit to a specific version because plans always fluctuate, but it is eligible to be removed in any future Angular major version.
Targeting `patch` so we can include this in the latest v16 release as well to increase visibility.
> refactor: strengthen language around Protractor support status

- CHANGELOG.md
> docs: release notes for the v16.2.6 release

- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-17/replace-nguniversal-engines.ts
- packages/schematics/angular/migrations/update-17/replace-nguniversal-engines_spec.ts
This commit adds a migration to migrate usages of `@nguniversal` to `@angular/ssr`.
> feat(@schematics/angular): add migration to migrate from `@nguniversal` to `@angular/ssr`

- packages/angular_devkit/build_angular/src/builders/application/schema.json
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
- packages/angular_devkit/build_angular/src/builders/browser/schema.json
By default output path does not default to dist.
> docs(@angular/cli): remove incorrect statement about outputPath

- goldens/public-api/angular_devkit/build_angular/index.md
- packages/angular_devkit/build_angular/src/builders/application/index.ts
- packages/angular_devkit/build_angular/src/builders/application/options.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
- packages/angular_devkit/build_angular/src/index.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
Similar to the existing Webpack-based `browser` builder, the new `application` builder is also exported from the `@angular-devkit/build-angular` package for use programmatically. As is the case for the existing builder JavaScript exports from the package, the new export (`buildApplication`) is also considered experimental and does not provide the support nor semver guarantees that the builders have when used via `angular.json` configuration. The usage of the `plugins` parameter of the `buildApplication` allows adding esbuild compatible plugins to the end of the plugin list for the main application code bundling. However, usage of the parameter may result in unexpected application output and/or build failures. Stable and supported methods for build process extension are being evaluated for …
> refactor(@angular-devkit/build-angular): export application builder for experimental programmatic usage

- packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/bundle-options.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/less-language.ts
When a Less stylesheet is detected to require the deprecated `javascriptEnabled` Less option, the option is enabled for the stylesheet and a warning is issued to inform the user of the behavior change. The Less `javascriptEnabled` option has been deprecated and disabled by default since Less v3 (https://github.com/less/less.js/releases/tag/v3.0.0). When enabled, the `javascriptEnabled` option allows JavaScript within Less stylesheets to be executed at build time.
Less option reference: https://lesscss.org/usage/#less-options
This provides similar behavior to the default Webpack-based build system. However, the Webpack-based build system currently unconditionally enables the option.
Closes #25572
> fix(@angular-devkit/build-angular): conditionally enable deprecated Less stylesheet JavaScript support

- packages/angular_devkit/build_angular/src/tools/esbuild/angular/component-stylesheets.ts
Within the application builder's template stylesheet processing, internal identifiers are used to track the incremental bundling status of each inline stylesheet. This identifier now consists of the stylesheet language, data, and containing file. This ensures that a tracking entry is maintained for each inline stylesheet and allows for the full cleanup and any incremental bundling resources at the end of the build.
> fix(@angular-devkit/build-angular): ensure unique internal identifiers for inline stylesheet bundling

- packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
- packages/angular_devkit/build_angular/src/builders/application/execute-post-bundle.ts
- packages/angular_devkit/build_angular/src/builders/application/i18n.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
- packages/angular_devkit/build_angular/src/utils/service-worker.ts
With this change common steps that are executed when running an i18n build and not are moved into a shared file.
> refactor(@angular-devkit/build-angular): move common steps in a shared function

- packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
When using localization with the application builder for a large amount of locales, the number of files that may need to be written to disk can become large. This may be problematic on certain operating systems depending on the open file process limits. To avoid approaching the limit, the number of concurrent writes is now limited to 64.
> fix(@angular-devkit/build-angular): limit concurrent output file writes with application builder

- packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts
- packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
This commits add a warning when using the browser-esbuild builder which eventually will be removed in favor of the `application` builder.
> refactor: add warning when using `browser-esbuild`

- packages/schematics/angular/migrations/update-17/replace-nguniversal-engines.ts
- packages/schematics/angular/ssr/index.ts
- packages/schematics/angular/utility/latest-versions.ts
This commit fixes an issue that causes update tests to fail when we are in feature freeze
> test: ensure to use the correct version for `@angular/ssr` packages

- goldens/circular-deps/packages.json
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
- packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/assets_spec.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
This commit ports https://github.com/angular/angular-cli/pull/26016 to the esbuilder and also fixes an issue where assets were being outputted in the wrong directory.
Closes #26021
> fix(@angular-devkit/build-angular): several fixes to assets and files writes in browser-esbuild builder

- packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
- tests/legacy-cli/e2e/tests/i18n/ivy-localize-ssr.ts
When using the application builder to create server builds for SSR and/or prerendering with localization enabled, the locale data for each enabled locale is now properly included in the server output files. While browser builds contain this data in the polyfills output file, the server builds do not contain a polyfill output file, as a result, the locale data is added to the main server code instead. This is also the case for other polyfill-like code including zone.js.
> fix(@angular-devkit/build-angular): ensure i18n locale data is included in SSR application builds

- packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-web-workers_spec.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/file-reference-tracker.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/jit-plugin-callbacks.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/source-file-cache.ts
When using the application builder with a Web Worker in watch mode, A change to the Web Worker code will now invalidate the referencing source file to ensure that all changes are captured and the new output file for the Web Worker is correctly injected into the referencing output file. Previously, the Web Worker output file may have changed but the reference may not have been updated causing an old instance of the Web worker code to be used in watch mode.
> fix(@angular-devkit/build-angular): fully track Web Worker file changes in watch mode

- packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts
- tests/legacy-cli/e2e/tests/build/styles/tailwind-v3.ts
When using the application builder with Tailwind directives not in a directly referenced Sass stylesheet, the Tailwind process was previously skipped. To avoid this problem, the Tailwind keyword checks are now performed on the result of any stylesheet language processing which will contain all the used stylesheet content.
Closes #26044
> fix(@angular-devkit/build-angular): process nested tailwind usage in application builder

- packages/angular_devkit/build_angular/BUILD.bazel
- packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-errors_spec.ts
- packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/aot-compilation.ts
Previously, the application builder relied on TypeScript to detect affected component files via changes to the internal template type check code. However, not all AOT compiler generated template errors will cause the template type check code to be changed. Block syntax errors are one example. To ensure that component diagnostics are recalculated when required, the component file will now always be considered affected when a used template file is changed.
> fix(@angular-devkit/build-angular): ensure recalculation of component diagnostics when template changes
