angular/angular-cli

packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
packages/angular_devkit/build_angular/src/builders/prerender/render-worker.ts
packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts
packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
packages/angular_devkit/build_angular/src/utils/server-rendering/render-page.ts

Critters has a number of large deps like postcss which slow down the Angular CLI loading times.

perf(@angular-devkit/build-angular): reduce CLI loading times by removing critters from critical path

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts

When using an esbuild-based builder (`application` or `browser-esbuild`) with the development server, a build that fails due to an TypeScript, Angular, or bundling error will now skip all output file result processing. This avoids unnecessary work since an update of the client code will not take place. This also allows for an error overlay to be displayed showing the first error available. The full list of errors will still be shown in the console used to execute the `ng serve` command. Fixing the error will automatically clear the error overlay but if there were multiple errors the next unfixed error will be shown instead.

fix(@angular-devkit/build-angular): avoid dev server update analysis when build fails with vite

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/application/execute-post-bundle.ts
packages/angular_devkit/build_angular/src/builders/application/i18n.ts
packages/angular_devkit/build_angular/src/utils/server-rendering/prerender.ts
tests/legacy-cli/e2e/tests/build/prerender/discover-routes-standalone.ts

With this change when SSG is enabled a `prerendered-routes.json` file is emitted that contains all the prerendered routes.
This is useful for Cloud providers and other server engines to have server rules to serve these files as static.
//cc @petebacondarwin

fix(@angular-devkit/build-angular): generate a file containing a list of prerendered routes

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/angular-compilation.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/factory.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/index.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/parallel-compilation.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/parallel-worker.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/diagnostics.ts
packages/angular_devkit/build_angular/src/utils/environment-options.ts

By default Angular compilations will now use a Node.js Worker thread to load and execute the
TypeScript and Angular compilers when using esbuild-based builders (`application`/`browser-esbuild`).
This allows for longer synchronous actions such as semantic and template diagnostics to be calculated
in parallel to the other aspects of the application bundling process. The worker thread also has
a separate memory pool which significantly reduces the need for adjusting the main Node.js CLI process
memory settings with large application code sizes. This can be disabled via the `NG_BUILD_PARALLEL_TS`
environment variable currently to support performance benchmarking. However, this is an unsupported
environment variable option and may be removed in a future version.

refactor(@angular-devkit/build-angular): add initial support for parallel TS/NG compilation

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/parallel-worker.ts

Due to the Windows Bazel directory structure, TypeScript can not safely infer the return type of the `diagnose` function in the parallel worker module. The return type should ideally be explicit regardless and so a return type is now provided for the function.

build: add diagnose return type annotation for windows bazel builds

---

packages/angular_devkit/build_angular/src/utils/server-rendering/prerender.ts

This should solve the Windows failures

fix(@angular-devkit/build-angular): address a path concatenation on Windows

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

In the Vite-based development server, an error overlay is requested if a build encounters an error. This error is then cleared when the error is corrected. However, the flag indicating that the error was cleared was not previously reset. This resulted in additional empty update commands being sent to the Vite client. While this has no visual effect, it is unneeded additional processing.

fix(@angular-devkit/build-angular): avoid repeat error clear in vite development server

---

packages/angular_devkit/build_angular/src/builders/application/schema.json
packages/angular_devkit/build_angular/src/builders/application/tests/options/allowed-common-js-dependencies_spec.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
packages/angular_devkit/build_angular/src/builders/browser/schema.json
packages/angular_devkit/build_angular/src/builders/browser/tests/options/allowed-common-js-dependencies_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/commonjs-checker.ts
packages/angular_devkit/build_angular/src/tools/webpack/plugins/common-js-usage-warn-plugin.ts

The `allowedCommonJsDependencies` property suppresses warnings if CJS/AMD modules are used.
The developer can then search for alternative dependencies or expand this list. 
If there are many affected dependencies that the developer needs to use without alternatives, it’s a lot of effort to constantly maintain this list. It would be helpful if there is an option to allow all dependencies…
Closes #25784
The current behavior remains unchanged, but gives developers the option to allow all CJS/AMD dependencies by using asterisk (`*`) as entry in `allowedCommonJsDependencies` .

feat(@angular-devkit/build-angular): add wildcard option for `allowedCommonJsDependencies`

---

goldens/public-api/angular_devkit/build_angular/index.md
packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/builders/application/schema.json
packages/angular_devkit/build_angular/src/builders/application/tests/options/ssr_spec.ts
packages/schematics/angular/ssr/index.ts

This commits updates the `ssr` application builder option definition. The main change is that now the option does not accept the entry-point as a value. Instead it should be passed in the `entry` suboption.
Example
```json
"ssr": {
"entry": "server.ts"
}
```
This change in this option is important to allow us in the future to add additional sub options. Like potentially a `platform` or `target`.

fix(@angular-devkit/build-angular): update `ssr` option definition

---

packages/schematics/angular/migrations/update-17/update-workspace-config.ts
packages/schematics/angular/migrations/update-17/update-workspace-config_spec.ts

Prior to this change there was a missing check that causes the migration to remove valid config when it was executed multiple times or on configs that do not contain the deprecated option.
Closes #26063

fix(@schematics/angular): noop workspace config migration when already executed

---

CHANGELOG.md

docs: release notes for the v17.0.0-rc.0 release

---

CHANGELOG.md

docs: release notes for the v16.2.7 release

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

In the devserver we do not perform ahead of time prerendering, instead we perform it during request time.

refactor(@angular-devkit/build-angular): remove redundant prerendering content from vite devserver

---

packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
packages/angular_devkit/build_angular/src/tools/esbuild/virtual-module-plugin.ts

This commit adds caching to the polyfills virtual modules to avoid module resolutions on rebuilds which can take up to 3 seconds in some cases. Whilst these are done async, these can still slow down the build slightly due to IO limits.

     perf(@angular-devkit/build-angular): cache polyfills virtual module result

---

packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
packages/angular_devkit/build_angular/src/builders/prerender/index.ts
packages/angular_devkit/build_angular/src/tools/esbuild/i18n-inliner.ts
packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer.ts
packages/angular_devkit/build_angular/src/tools/webpack/plugins/javascript-optimizer-plugin.ts
packages/angular_devkit/build_angular/src/utils/action-executor.ts
packages/angular_devkit/build_angular/src/utils/server-rendering/prerender.ts

When destroying a `piscina` package worker pool, the minimum workers must be set to 0 first to prevent the recreation of the minimum number of workers. These workers would then be cleaned up once the worker pool goes out of scope but the recreation and initialization of each worker is unneeded processing that should be avoided.

refactor(@angular-devkit/build-angular): workaround for piscina worker destroy recreation

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/angular-compilation.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/noop-compilation.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/diagnostics.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/source-file-cache.ts

To improve initialization type for the application builder, loading of the typescript package as been removed from the main thread. The parallel TS/NG compilation will instead load typescript during its worker thread startup. The typescript package is currently large and can take several hundred milliseconds to load.

refactor(@angular-devkit/build-angular): isolate typescript usage to compilation worker thread in application builder

---

packages/angular/cli/src/commands/update/cli.ts

This commit updates the behaviour of `ng update --migrate-only` to remove the need for `--migrate-only` option to be specified. `--migrate-only` will be set internally.
Before
```
ng update @angular/cli --migrate-only --name=migration-name
```
Now
```
ng update @angular/cli --name=migration-name
```

fix(@angular/cli): remove the need to specify `--migrate-only` when `--name` is used during `ng update`

---

packages/schematics/angular/migrations/update-17/replace-nguniversal-engines.ts
packages/schematics/angular/migrations/update-17/replace-nguniversal-engines_spec.ts

Prior to this change the Universal migration ran and added `@angular/ssr` even the workspace did not depend on `@nguniversal/` packages.
Closes #26083

fix(@schematics/angular): do not add unnecessary dependency on `@angular/ssr` during migration

---

packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-component_styles_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/component-stylesheets.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
packages/angular_devkit/build_angular/src/tools/esbuild/load-result-cache.ts

When using the esbuild-based builders (`application`/`browser-esbuild`) in watch mode including `ng serve`, component stylesheets that used Sass and imported other stylesheets were previously no properly tracked. As a result, changes to the imported stylesheets would not invalidate the component and the rebuild would not contain the updated styles. The files used by the Sass (and Less) stylesheet processing are now correctly tracked in these cases.

fix(@angular-devkit/build-angular): use component style load result caching information for file watching

---

packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts

When using the esbuild-based builders (`application`/`browser-esbuild`), the Angular compiler plugin is now only added to the polyfills bundler configuration if TypeScript files are found in the `polyfills` build option. This is not the case for a default project. The Angular compiler plugin is used to provide type-checking diagnostics for any TypeScript files present within the build. However, if there are no TypeScript files to process, there is no need to use it for the polyfills processing.

perf(@angular-devkit/build-angular): conditionally add Angular compiler plugin to polyfills bundling

---

packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/sass-language.ts
packages/angular_devkit/build_angular/src/tools/sass/rebasing-importer.ts
packages/angular_devkit/build_angular/src/tools/sass/sass-service.ts
packages/angular_devkit/build_angular/src/tools/sass/worker.ts
packages/angular_devkit/build_angular/src/tools/webpack/configs/styles.ts

The recent version of the Sass compiler (`dart-sass@1.68.0`) now provides additional information within an importer that allows more accurate resolution of node modules packages without several existing workarounds. Previously, the Sass files needed to be pre-processed to extract all `@import` and `@use` paths so that information regarding the containing Sass file could be used to fully resolve the paths. The Sass compiler now provides this information directly.

refactor(@angular-devkit/build-angular): remove Sass module resolve workarounds

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/application/index.ts

The build time is now shown when bundling fails. Previously only the errors were shown. This provides additional information that the build did indeed fail and how long it took to fail.

refactor(@angular-devkit/build-angular): show build time on failures with application builder

---

packages/angular_devkit/build_angular/BUILD.bazel
packages/angular_devkit/build_angular/src/builders/application/tests/behavior/stylesheet-url-resolution_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/css-resource-plugin.ts
packages/angular_devkit/build_angular/src/tools/sass/rebasing-importer.ts

The stylesheet url() resource plugin will now correctly issue warnings for the usage of Webpack specific prefixes such as the tilde when used in an imported Sass file. Previously, these URLs would be rebased by the Sass processing step which would cause the tilde prefix to no longer be a prefix. This would then no longer be considered a warning due to the tilde no longer being the first character of the URL value. Additionally, a warning is also now issued for the previously unsupported but available caret prefix. Removing the caret prefix and adding the path to the `externalDependencies` build option should provide equivalent behavior.

fix(@angular-devkit/build-angular): ensure css url() prefix warnings support Sass rebasing

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts

The Angular compiler's partial compilation mode is only intended for use when building libraries. If attempting to use the mode while building an application, the application would fail. A warning is now issued if partial mode is configured for the application and the mode is switched to full compilation mode to prevent the build from failing due to the option value.

fix(@angular-devkit/build-angular): warn if using partial mode with application builder

---

packages/angular/ssr/src/common-engine.ts
packages/schematics/angular/migrations/update-17/replace-nguniversal-engines.ts
packages/schematics/angular/ssr/files/application-builder/server.ts.template
packages/schematics/angular/ssr/files/server-builder/server.ts.template

When calling `renderApplication` or `renderModule` the URL would be overridden to undefined as the `url` option was not provided as an option.

fix(@angular/ssr): correctly set config URL

---

packages/angular_devkit/build_angular/src/tools/esbuild/commonjs-checker.ts

This is used inernally by '@angular/platform-server' and is in a seperate chunk that is unused when using `provideHttpClient(withFetch())`.

fix(@angular-devkit/build-angular): silence xhr2 not ESM module warning

---

packages/angular/cli/src/commands/version/cli.ts

Node.js support was removed, but it appears that this got through the cracks.

fix(@angular/cli): remove Node.js 16 from supported checks

---

packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer.ts

The idle timeout for threads in the JavaScript transformer worker pool for the esbuild-based builders (`application`/`browser-esbuild`) is now set at 1 second. This prevents the default of immediate shutdown of an idle worker from occurring. The immediate shutdown causes additional worker threads to be created due to the variable time between bundler requests for node module JavaScript files. The shutdown and subsequent recreation of the threads during the build causes unneeded extra processing that can now be avoided.

refactor(@angular-devkit/build-angular): increase JS transformer worker pool idle timeout to 1 second

---

tools/postinstall/patches/@bazel+concatjs+5.8.1.patch

The built packages that will be published on npm previously contained inlined sourcemaps for every JavaScript file. This caused a significant increase in the overall package size of over two times larger. This has a negative effect on developer experience especially the new project experience due to the increased time to download and setup a new project. The sourcemaps are also rarely used as debugging the CLI code itself is typically done with development builds. The generated code is also very close to the original source due to it being emitted as ES2022 code and with the eventual switch to ESM output this will become even closer.
As an example of the size difference, the `@angular/cli` compressed package size was reduced from ~352Kb to ~115Kb with this change.

build: disable inline sourcemap generation

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/component-stylesheets.ts
tests/legacy-cli/e2e/tests/basic/rebuild.ts

To avoid incorrectly invalidating the stylesheet bundler within the application builder on Windows, the paths of changed files are now first normalized. This ensures that any changed files properly cause affected component stylesheets to be reprocessed.

fix(@angular-devkit/build-angular): normalize paths when invalidating stylesheet bundler

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts

When using the Vite-based development server, the application build step already contains the list of known packages that would need to be prebundled. This information can be passed to Vite directly to avoid Vite needing to perform discovery on every output file that will be requested. This also avoids the Vite server behavior where Vite forces a reload of the page when it discovers a new dependency. This behavior can result in lost state during lazy loading of a route.

fix(@angular-devkit/build-angular): automatically include known packages in vite prebundling

---

CHANGELOG.md

docs: release notes for the v16.2.8 release

---

CHANGELOG.md

docs: release notes for the v17.0.0-rc.1 release

---

packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer-worker.ts

This entry-points are side effectual.

fix(@angular-devkit/build-angular): do not perform advanced optimizations on `@angular/common/locales/global`

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts

The builder system (architect) currently attempts to treat all results as JSON and attempts to validate the object with a JSON schema validator. This can lead to slow build completion (even after the actual build is fully complete) or crashes if the size and/or quantity of output files is large. Architect only requires a `success` property so that is all that will be passed here if the infrastructure settings have not been explicitly set to avoid writes. Writing is only disabled when used directly by the dev server which bypasses the architect behavior.

fix(@angular-devkit/build-angular): avoid binary content in architect results with browser-esbuild

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

When using the Vite-based development server combined with the `externalDependencies` option, Vite will no longer attempt to resolve the explicitly marked externals. This is still not ideal since it Vite will still transform the import specifier to `/@id/${source}` but is currently closer to a raw external than a resolved file path. Further investigation with a possible feature request for Vite may be needed to achieve the desired outcome of an unresolved and untransformed external import specifier.

refactor(@angular-devkit/build-angular): prevent vite from resolving explicit external dependencies

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
packages/angular_devkit/build_angular/src/tools/esbuild/global-scripts.ts
packages/angular_devkit/build_angular/src/tools/esbuild/global-styles.ts
packages/angular_devkit/build_angular/src/tools/esbuild/watcher.ts

The newly introduced incremental bundler result caching is now used for both global styles (`styles` option) and global scripts (`scripts` option). This allows the bundling steps to be skipped in watch mode when no related files for either have been modified. This can be especially beneficial for applications with large global stylesheets.

perf(@angular-devkit/build-angular): only rebundle global scripts/styles on explicit changes

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

This commit fixes an issue were during SSG/SSR in the dev-server http requests to assets causes the page rendering to fail.

fix(@angular-devkit/build-angular): handle HTTP requests to assets during SSG in dev-server

---

packages/schematics/angular/component/index_spec.ts
packages/schematics/angular/utility/validation.ts

Closes #25164
Does not allow dash in selector before a number. Which means, following command would throw error: -
`ng g c TodoItemTask-123`
Issue Number: https://github.com/angular/angular-cli/issues/25164
Command like this will work: -
`ng g c TodoItemTask-123`

fix(@schematics/angular): allow dash in selector before a number

---

CHANGELOG.md

docs: release notes for the v17.0.0-rc.2 release

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts
packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts

Similar to how the Webpack-based `browser` builder only shows the output files that have changed during watch mode (including `ng serve`), the esbuild-based builders will now also only show changed files. For large applications, this can greatly reduce the amount of text shown in the console when actively developing in watch mode.

fix(@angular-devkit/build-angular): only show changed output files in watch mode with esbuild

---

packages/schematics/angular/workspace/files/tsconfig.json.template
tests/legacy-cli/e2e/initialize/500-create-project.ts

The `esModuleInterop` TypeScript option is a TypeScript recommended option that ensures that TypeScript emits compliant ESM code when transforming namespace and default imports. This is important for new projects because they now use the `application` builder which emits full ESM code. Not using this option with certain third-party packages can result in build warnings and the potential for runtime failure. For existing applications that are considering migrating, information pertaining to this situation will be available within the documentation.
Since the `allowSyntheticDefaultImports` is implied and automatically enabled when `esModuleInterop` is enabled, the previous option has been replaced with this one.
Reference: https://www.typescriptlang.org/tsconfig#esModuleInterop

fix(@schematics/angular): enable TypeScript `esModuleInterop` by default for ESM compliance

---

packages/ngtools/webpack/src/transformers/replace_resources.ts
packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
packages/schematics/angular/component/index_spec.ts

An array is no longer required in v17 and we always generate a single style or style URL anyways, so we may as well drop the array.
This actually revealed a bug in the Webpack compilation where an empty `styles: ''` string would break PostCSS / the Webpack loader. Fixed this by just skipping resource inlining for an empty string, since there's no work to do anyways.

Fix empty `styles` string and update component schematic to use single `styles` or `styleUrl` property

---

packages/angular_devkit/build_angular/src/tools/esbuild/commonjs-checker.ts

When CommonJS module checking is enabled in the esbuild-based builders (`application`/`browser-esbuild`), the checker will now skip all descendants of a CommonJS module. Previously it would only skip them if the module was not allowed. This change now provides the same module checking behavior as the Webpack-based check. This makes the build behavior more consistent when migrating to the new build system.

fix(@angular-devkit/build-angular): skip checking CommonJS module descendants

---

packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-web-workers_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts

When using the application builder with the development server, Web Worker URLs previously may have been incorrectly resolved. This caused Vite to consider the Web Worker URLs as outside the project root and generate a special file system URL. While this worked on Mac/Linux, it would fail on Windows. Since Vite does not appear to support resolve plugins for Web Workers, the virtual project root for the in-memory build has now been adjusted to allow the referencing file to have a path that resolves the Web Worker URL to a project relative location.

fix(@angular-devkit/build-angular): ensure correct web worker URL resolution in Vite dev server

---

packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts

The newly introduced incremental bundler result caching is now used for browser polyfills (`polyfills` option). This allows the bundling steps to be skipped in watch mode when no related files have been modified.

perf(@angular-devkit/build-angular): only rebundle browser polyfills on explicit changes

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/extract-i18n/application-extraction.ts
tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts

Any errors or warnings generated from post-bundling steps of the build will now be formatted and displayed in a similar manner to the bundling errors and warnings. This should be most noticeable with bundle budgets.

refactor(@angular-devkit/build-angular): format post-bundle diagnostic messages for esbuild builders

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

The Vite-based development server that is used with the esbuild-based builders (`application`/`browser-esbuild`)
will show an error overlay when the application build encounters an error. This overlay previously provided a
suggestion to edit the `vite.config.js` configuration file to disable the error overlay. Since Vite usage is
encapsulated within the Angular CLI, this suggestion is unactionable and may lead to user confusion due to
no Vite configuration file being present within the project nor would creating one have an effect on the build
process.
Blocked on #26162

fix(@angular-devkit/build-angular): remove unactionable error overlay suggestion from Vite-based dev server

---

.github/workflows/ci.yml
WORKSPACE
constants.bzl
package.json
packages/angular/cli/src/commands/version/cli.ts
tools/toolchain_info.bzl

Closes https://github.com/angular/angular-cli/issues/26114

Node.js 20

---

packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts

The newly introduced incremental bundler result caching is now used for server polyfills. This allows the bundling steps to be skipped in watch mode when no related files have been modified.

perf(@angular-devkit/build-angular): only rebundle server polyfills on explicit changes

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts

This changes add a log to the console to prints the total number of prerendered routes.

fix(@angular-devkit/build-angular): log number of prerendered routes in console

---

packages/angular/cli/BUILD.bazel
packages/angular/pwa/BUILD.bazel
packages/angular/ssr/schematics/BUILD.bazel
packages/angular_devkit/architect/BUILD.bazel
packages/angular_devkit/architect/node/BUILD.bazel
packages/angular_devkit/build_angular/BUILD.bazel
packages/angular_devkit/build_webpack/BUILD.bazel
packages/angular_devkit/core/BUILD.bazel
packages/angular_devkit/core/node/BUILD.bazel
packages/angular_devkit/schematics/BUILD.bazel
packages/angular_devkit/schematics/tools/BUILD.bazel
packages/angular_devkit/schematics_cli/BUILD.bazel
packages/ngtools/webpack/BUILD.bazel
packages/schematics/angular/BUILD.bazel

E2E tests are used to run tests on multiple platforms and node.js versions.

build: use single Node.js toolchain to run unit tests

---

packages/schematics/angular/migrations/update-17/replace-nguniversal-engines.ts
packages/schematics/angular/migrations/update-17/replace-nguniversal-engines_spec.ts

This commit updates the nguniversal migration to add `REQUEST` and `RESPONSE` tokens.
Closes #26110

fix(@schematics/angular): add missing express `REQUEST` and `RESPONSE` tokens

---

packages/angular_devkit/schematics/tools/node-module-engine-host.ts

This change addresses an issue encountered when running external schematics from a yarn pnp workspace.  The function used to resolve a collection json using node used recursion in a way that it effectively walked itself into an exception. Then if the exception is the type it expected, it would keep going.  This was flawed in that yarn with pnp throws a different type of error when it failed to load the mis-constructed collection path (e.g. `/node_modules/@schematics/angular/collection.json/package.json`).  `ENOTDIR` instead of `MODULE_NOT_FOUND`.
This process of intentionally / knowingly walking into an exception seems problematic in
general.  So, I addressed it by first checking if the `schematics` entry in the package
is a relative path.  If it is, then don't construct the collection …

fix(@angular-devkit/schematics): running external schematics with yarn pnp

---

goldens/public-api/ngtools/webpack/index.md
packages/angular_devkit/build_angular/src/tools/babel/plugins/elide-angular-metadata.ts
packages/angular_devkit/build_angular/src/tools/babel/plugins/elide-angular-metadata_spec.ts
packages/ngtools/webpack/src/ivy/plugin.ts
packages/ngtools/webpack/src/ivy/transformation.ts
packages/ngtools/webpack/src/transformers/remove-ivy-jit-support-calls.ts
packages/ngtools/webpack/src/transformers/remove-ivy-jit-support-calls_spec.ts

Includes a couple of commits that update the Babel and Webpack plugins to drop calls to the new `ɵsetClassDebugInfo` function which is only used in development mode.

Remove setClassDebugInfo calls

---

packages/angular_devkit/build_angular/src/builders/application/build-action.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts
packages/angular_devkit/build_angular/src/utils/environment-options.ts

When using the application builder in watch mode (including `ng serve`), the file watching will now only watch files used or relevant to the used files. Previously, all files within the project root were watched. This previous behavior could result in unneeded rebuilds when unrelated files were changed. An environment variable named `NG_BUILD_WATCH_ROOT` is also now available to enable the previous behavior in cases where it is still preferred as well as for testing and debugging purposes.

fix(@angular-devkit/build-angular): only watch used files with application builder

---

packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-loader/loader-hooks.ts

On Node.js 20 prerendering failed on Windows with `An unhandled exception occurred: No handler function exported` error. This appears to be caused by transforming Piscina CJS bundles using the `JavaScriptTransformer`. interestingly, this does not effect other OS like Linux and Mac.

fix(@angular-devkit/build-angular): Windows Node.js 20 prerendering failure

---

CHANGELOG.md

docs: release notes for the v17.0.0-rc.3 release

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/application/tests/options/bundle-budgets_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts
tests/legacy-cli/e2e/tests/build/bundle-budgets.ts

This change fixes an issue were non bundling related errors that happen during prerendering, index generation and bundle budget failures did not cause the build to terminate with an error.

fix(@angular-devkit/build-angular): fail build on non bundling error when using the esbuild based builders

---

packages/angular_devkit/build_angular/src/utils/bundle-calculator.ts

The extra whitespace matching can be removed via a trim call prior to matching and casing can be handled by the `i` flag.

refactor(@angular-devkit/build-angular): reduce complexity of bundle budget threshold regex

---

goldens/public-api/angular_devkit/build_angular/index.md
packages/angular_devkit/build_angular/src/builders/ssr-dev-server/index.ts
packages/angular_devkit/build_angular/src/index.ts

The `ssr-dev-server` builder function is not exposed in the public API.
The `ssr-dev-server` builder function is exposed in the public API.

fix(@angular-devkit/build-angular): expose ssr-dev-server builder in the public api

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

The commit introduces dependencies prebundling and optimisation for SSR dependencies. This is primarily needed for Angular linking and async/await downlevelling. To enable this, we need to use the undocumented `optimizeDeps` setting under the `ssr` option. This is because, the top level `optimizeDeps` vite config option  only controls browser dependencies.
For the above mentioned option to take effect and transform node packages, we also need to use `noExternal` and use a catch all `RegExp`. Note: setting this option to `true` has a different effect from a catch all `RegExp`, as the former will cause the `external` option to be ignored.
Additionally together with `externalMetadata.explicit` we add Node.js build-ins as `external`.
Closes: #26192

fix(@angular-devkit/build-angular): prebundle dependencies for SSR when using Vite

---

tests/legacy-cli/e2e/tests/basic/rebuild.ts

It appears that the changes where being done to quicky to be picked up by the watcher.

test(@angular/cli): delay changes to reduce `tests/legacy-cli/e2e/tests/basic/rebuild.ts` flakiness

---

goldens/public-api/angular/ssr/index.md
packages/angular/ssr/src/common-engine.ts

The option `enablePeformanceProfiler` has a typo
The option is now properly named `enablePerformanceProfiler`

fix(@angular/ssr): enable performance profiler option name

---

packages/angular/cli/src/utilities/load-esm.ts
packages/angular_devkit/architect/node/node-modules-architect-host.ts
packages/angular_devkit/build_angular/src/utils/load-esm.ts
packages/angular_devkit/schematics_cli/bin/schematics.ts

The dynamically compiled ESM import helper is now cached to prevent the need to recompile the helper function everytime a load ESM helper call is made. This helper is currently used to workaround dynamic import limitations with the TypeScript compilation output. Once the build process is updated, it will no longer be required.

refactor(@angular-devkit/build-angular): cache compiled load ESM file helper

---

packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts

This is now done by default in zone.js versions greater than  `0.14.1`
See https://github.com/angular/angular/pull/52492

refactor(@angular-devkit/build-angular): remove `__zone_symbol__DISABLE_WRAPPING_UNCAUGHT_PROMISE_REJECTION` code

---

packages/ngtools/webpack/src/transformers/find_image_domains.ts
packages/ngtools/webpack/src/transformers/find_image_domains_spec.ts

Currently, the static scanning done by the image domain scanner catches domains provided in files following the AppModule pattern, but misses domains when using the standalone component module. This PR adjusts the scan path to fix that. The actual logic governing the detection of domains and inserting them into the index.html file is unchanged, this fix simply tells the scanner to also look in one additional place in files.
Specifically, the new scanning route looks for the `static ɵinj = /*@__PURE__*/ i0.ɵɵdefineInjector(...)` invocation, which exists in post-transform standalone component files, and contains the providers.
As with the existing scanning, this new code path is very specific, looking at a constant number of nodes, and should not effect build time. CC: @clydin …

fix(ngtools/webpack): let static scan to find image domains in standlone components

---

goldens/public-api/angular_devkit/build_angular/index.md
packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

When using the experimental programmatic API for the development server with an esbuild-based builder (`application`/`browser-esbuild`), express compatible middleware can now be added. Also, the index HTML transformer that previously only worked with the Webpack-based development server is also now enabled.
However, usage of these options may result in unexpected application output and/or build failures. They are also not officially supported and SemVer guarantees are not present. Stable and supported methods for build process extension are being evaluated for a future release.

refactor(@angular-devkit/build-angular): add experimental extension points to Vite-based dev server

---

packages/angular/ssr/src/common-engine.ts

With this change we replace `resolve` with `join` to avoid potential path traversal vulnerability.
More context about the reasoning behind this change can be found in https://buganizer.corp.google.com/issues/299878755#comment26
//cc @securityMB, @AndrewKushnir

refactor(@angular/ssr): use `join` instead of `resolve`

---

packages/angular_devkit/build_angular/src/tools/esbuild/commonjs-checker.ts
packages/angular_devkit/build_angular/src/utils/server-rendering/render-worker.ts

This commit add `critters` and `express` to the CJS allowed deps.

fix(@angular-devkit/build-angular): remove CJS usage warnings for inactionable packages

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

Do not try to SSR a request that has extensions.
Closes #26199

fix(@angular-devkit/build-angular): in vite skip SSR middleware for path with extensions

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts

This commit splits the retrieval of external dependencies into two. Server imports and browser imports. This is so that we avoid vite from optimizing server or browser only dependencies twice.
This also fixes an issue were in some cases Vite would issue a warning like `Cannot optimize dependency: path, present in 'optimizeDeps.include'`. This was caused because of server only dependencies ended up trying to be optimized for a browser build.

perf(@angular-devkit/build-angular): optimize server or browser only dependencies once

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

Unlike assets, output file were not prefixed with a `/`. This change alings these and now files are always prefixed with a slash.
Closes #26215

fix(@angular-devkit/build-angular): media files download files in vite

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts

When using the esbuild-based builders (`application`/`browser-esbuild`), the secondary Angular compilations will wait for the primary compilation to finish prior to bundling. This can potentially occur for polyfills that contain TypeScript files and the server code if enabled. However, if the Angular compilation throws an error during the start of the bundling process, the secondary compilations were never notified and instead would wait indefinitely. To avoid this situation, the compilations will now always be notified at the end of the compilation which will occur regardless. The build error that will be generated in these situations is currently not ideal and more verbose than needed but will provide information pertaining to the root cause.
Closes #26213

fix(@angular-devkit/build-angular): ensure secondary Angular compilations are unblocked on start errors

---

packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-loader/loader-hooks.ts
packages/angular_devkit/build_angular/src/utils/server-rendering/render-worker.ts
packages/angular_devkit/build_angular/src/utils/server-rendering/routes-extractor-worker.ts

The in-memory ESM loader hooks have been adjusted to avoid potential errors when
resolving and loading the bundled server code during prerendering. These errors
could result in hard to diagnose build failures. E2E testing via the deprecated
protractor builder, would silently exit, for instance. To ensure on disk files
including node modules are resolved from the workspace root, a virtual file root
is used for all in memory files. This path does not actually exist but is used to
overlay the in memory files with the actual filesystem for resolution purposes.
A custom URL schema (such as `memory://`) cannot be used for the resolve output
because the in-memory files may use `import.meta.url` in ways that assume a file
URL. `createRequire` from the Node.js `module` builtin is one example of …

fix(@angular-devkit/build-angular): avoid in-memory prerendering ESM loader errors

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

Vite will only start dependency optimization of SSR modules when the first request comes in.
In some cases, this causes a long waiting time. To mitigate this, we call `ssrLoadModule` to initiate this process before the first request.

perf(@angular-devkit/build-angular): start SSR dependencies optimization before the first request

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer.ts

The `JavaScriptTransformer` class that is responsible for Angular linking and several build optimization transformations can now be configured to track and reuse previous and pending transformation requests. This allows for cases where multiple consumers of the class will not cause repeat transformation actions. Pending results will be stored if the constructor option `reuseResults` is enabled. If two transformation requests are issued for the same file, the same underlying result will be provided to each. This behavior currently only applies to file transformation requests.

refactor(@angular-devkit/build-angular): allow JS transformer result reuse for application dev-server builder

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

It appears that Vite currently, has a number of limitation/bugs when using `optimizeDeps` for SSR bundles.
Currently this causes a number of issues:
- Deps are re-optimized everytime the server is started.
- Added deps after a rebuild are not optimized.
- Breaks RxJs (Unless it is added as external). See: #26235
We should follow up with Vite and try to get this solved as this would be a nice feature to use.
Closes #26235 and #26234

fix(@angular-devkit/build-angular): disable dependency optimization for SSR

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

Prior to this commit, the pre-bundling of dependencies was being invalidated for each build. This is because vite uses parts of the config among other things to generate a hash. In our case the config was not always consistent for the same project between different builds.
The main 2 problems areas were:
- Random `root` path
- `include` and `exclude` arrays were not always in the same order.

fix(@angular-devkit/build-angular): keep dependencies pre-bundling validate between builds

---

packages/angular_devkit/build_angular/src/utils/environment-options.ts

When using the `application` or `browser-esbuild` builders, a parallel TS/NG compilation will be used by default via a Node.js Worker. However, when used inside a Web Container, the build will fail to initialize the compilation instance due to what appears to be a defect within Web containers involving the transfer/serialization of a MessageChannel's MessagePort objects. To avoid this problem, the parallel compilation is disabled by default when the build system detects it is being executed from within a Web Container. A parallel compilation can still be forced by using the `NG_BUILD_PARALLEL_TS=1` environment variable.

fix(@angular-devkit/build-angular): disable parallel TS/NG compilation inside WebContainers

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts

When using the `application` builder, exceptions thrown by the AOT compiler will now be converted into error diagnostics. This allows for more actionable information to be displayed in the build output. It also prevents the typically incorrect "missing file" error from occurring in these cases which previously occurred due to TypeScript files not being emitted as a result of the compiler failure.

fix(@angular-devkit/build-angular): convert AOT compiler exceptions into diagnostics

---

packages/schematics/angular/application/files/common-files/src/app/app.component.html.template
packages/schematics/angular/application/files/module-files/src/app/app.component.spec.ts.template
packages/schematics/angular/application/files/module-files/src/app/app.component.ts.template
packages/schematics/angular/application/files/standalone-files/src/app/app.component.spec.ts.template
packages/schematics/angular/application/files/standalone-files/src/app/app.component.ts.template
packages/schematics/angular/e2e/files/src/app.e2e-spec.ts.template
packages/schematics/angular/e2e/files/src/app.po.ts.template
packages/schematics/angular/e2e/index_spec.ts
tests/legacy-cli/e2e/tests/basic/standalone.ts
tests/legacy-cli/e2e/tests/build/ssr/express-engine-csp-nonce.ts
tests/legacy-cli/e2e/tests/build/ssr/express-engine-ngmodule.ts
tests/legacy-cli/e2e/tests/build/ssr/express-engine-standalone.ts
tests/legacy-cli/e2e/tests/update/update.ts

angular.dev
Read more at goo.gle/angular-dot-dev

feat(@schematics/angular): update ng new generated application

---

CHANGELOG.md

docs: release notes for the v17.0.0-rc.4 release

---

tests/legacy-cli/e2e.bzl
tests/legacy-cli/e2e/tests/vite/reuse-dep-optimization-cache.ts

This commit adds a test to verify that vite uses the dep optimization cache

test(@angular-devkit/build-angular): add test to validate vite cache re-usage

---

packages/angular_devkit/build_angular/src/builders/karma/find-tests-plugin.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/exclude_spec.ts

The issue arises from passing `exclude` paths directly to the glob method, which can confuse users when they provide relative project roots or backslashes. This problem doesn't occur with `include` paths because those are automatically normalized. 
Issue Number: #26239
The `exclude` paths are now normalized for common user errors, such as the use of backslashes or relative project roots. This also unifies, to a certain extent, how `include` and `exclude` paths are transformed internally by the builder.
The remaining normalization steps for `include` are already informed to the developer, so now all the normalization for `include` & `exclude` are either unified or documented.

fix(@angular-devkit/build-angular): normalize exclude path

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts

When using the `application` builder with SSR enabled and the `allowJs` TypeScript option, the build would previously generate warnings about undefined imports. This was caused by the recently introduced initialization error handling that was not accounting for the early exit of the SSR compiler plugin's `onStart` hook. This early exit prevent the error status checking from completing which resulted in the SSR plugin load hook assuming an error had occurred. This in turn caused JavaScript files that were not imported into TypeScript files to be returned as empty content to avoid the not found error message. To remedy this situation, the error status is now also set during the SSR early exit.

fix(@angular-devkit/build-angular): allow SSR compilation to work with TS allowJs option

---

CHANGELOG.md

docs: release notes for the v17.0.0-rc.5 release

---

CHANGELOG.md

docs: release notes for the v16.2.10 release

---

CHANGELOG.md

docs: release notes for the v17.0.0 release

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/parallel-compilation.ts
packages/angular_devkit/build_angular/src/utils/environment-options.ts

When using the `application` builder, a parallel TS/NG compilation is used that is run inside a Node.js Worker.
This Worker by default uses an Atomics-based wait loop to improve performance while waiting for messages. This
loop relies on the synchronous API `receiveMessageOnPort`. While this works well in Node.js, the web container
execution environment does not currently support passing transferable objects via `receiveMessageOnPort`. Attempting
to do so will cause a serialization error and a failed application build. To avoid this problem, the wait loop
optimization is disabled when the web container execution environment is detected. This change is only needed
for the TS/NG compilation as no other parallel operation within the build system currently uses `receiveMessageOnPort`
with …

fix(@angular-devkit/build-angular): disable Worker wait loop for TS/NG parallel compilation in web containers

---

packages/schematics/angular/application/files/common-files/src/app/app.component.html.template

The default template uses interpolation instead of a property binding to set the the href value.
Use `[href]="item.title"`

fix(@schematics/angular): use href property binding for links

---

.bazelrc

By default Bazel, a single test attempt will be made for regular tests and three for tests marked explicitly as flaky by their rule (flaky=1 attribute)
This configures e2e tests to retry the test when it fails.

build: set `flaky_test_attempts` to `2` for E2E tests

---

packages/schematics/angular/application/files/module-files/src/app/app.component.ts.template
packages/schematics/angular/application/files/standalone-files/src/app/app.component.ts.template
tests/legacy-cli/e2e/tests/build/styles/include-paths.ts

The `ng g c` schematic is already using `styleUrl`, but `app.component.ts` was still using `styleUrls`.
`app.component.ts` now uses `styleUrl` by default.

fix(@schematics/angular): use styleUrl

---

packages/angular_devkit/build_angular/src/builders/browser/specs/output-path_spec.ts
packages/angular_devkit/build_angular/src/utils/delete-output-dir.ts

When the `deleteOutputPath` option is enabled (default is enabled), the configured `outputPath` for the project was previously removed directly. This was problematic for cases such as when the path was mounted via a Docker setup. To alleviate these issues, the contents of the output path will now be removed instead. This maintains the existing output path directory itself but ensures an empty location to place the new build output.
Closes #26223

fix(@angular-devkit/build-angular): empty output directory instead of removing

---

packages/schematics/angular/ssr/index.ts
packages/schematics/angular/ssr/index_spec.ts

This commit adds a helper script in the `package.json` when running `ng add @angular/ssr` or `ng new --ssr` that can be used to spawn the SSR server.
Example of script:
```json
{
"scripts": {
"serve:ssr:my-app": "node dist/my-app/server/server.mjs"
}
}
```
Closes #26315

fix(@schematics/angular): add helper script to spawn SSR server from `dist`

---

packages/angular_devkit/build_angular/src/utils/routes-extractor/extractor.ts

Prior to the commit, when no routes were defined the default view was not prerendering.
Closes #26317

fix(@angular-devkit/build-angular): prerender default view when no routes are defined

---

packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts

RxJs is not imported in the server polyfills and thus we can safely remove this plugin.

refactor(@angular-devkit/build-angular): remove unused plugin from server polyfills

---

packages/schematics/angular/workspace/files/tsconfig.json.template

We no longer need `downlevelIteration` as ES5 is output is no longer supported by the CLI.

fix(@schematics/angular): remove `downlevelIteration` from `tsconfig.json` for new workspaces

---

packages/angular_devkit/build_angular/src/builders/application/build-action.ts
packages/angular_devkit/build_angular/src/builders/application/tests/options/delete-output-path_spec.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/delete-output-path_spec.ts
packages/angular_devkit/build_angular/src/builders/browser/index.ts
packages/angular_devkit/build_angular/src/builders/server/index.ts
packages/angular_devkit/build_angular/src/utils/delete-output-dir.ts

Prior to this change the `deleteOutputPath` was not being used in the esbuild-builder.
Closes #26308

fix(@angular-devkit/build-angular): `deleteOutputPath` when using `esbuild-builder`

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
tests/legacy-cli/e2e.bzl
tests/legacy-cli/e2e/tests/vite/reuse-dep-optimization-cache.ts
tests/legacy-cli/e2e/tests/vite/ssr-error-stack.ts

Prior to this change, when a error occurs when using the SSR dev-server the stacktraces pointed back to the virtual root path.

 fix(@angular-devkit/build-angular): rewire sourcemap back to original source root

---

packages/angular_devkit/build_angular/src/builders/application/build-action.ts
packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-global_styles_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
packages/angular_devkit/build_angular/src/tools/esbuild/load-result-cache.ts
packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/less-language.ts
packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/sass-language.ts

When using the `application` and/or `browser-esbuild` builders, the current watch files
will be maintained in the event of a build error. This better ensures that files used
in the last build/rebuild that may have caused an error will continue to be watched and
refreshed when later changed. Only when a successful rebuild has occurred will any stale
watch files be removed from the watch list.

fix(@angular-devkit/build-angular): maintain current watch files after build errors

---

packages/angular/cli/src/utilities/package-metadata.ts

In some cases pacote will return undefined as `version` which resulted in `Cannot convert undefined or null to object`.
Closes #26337

fix(@angular/cli): handle packages with no version

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

Prior to this change the vendor sourcemaps were never generated when using vite prebundling.

fix(@angular-devkit/build-angular): add support for vendor sourcemaps when using the dev-server

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

The server entry-point is not used by vite.

fix(@angular-devkit/build-angular): do not process server entry-point when running `ng serve`

---

packages/angular_devkit/build_angular/src/builders/application/options.ts

This commits adds an actionable error when the file to replace with is missing.
Closes #26333

fix(@angular-devkit/build-angular): add actionable error when file replacement is missing

---

CHANGELOG.md

docs: release notes for the v17.0.1 release

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

Path normalization that fixes a tests on windows

fix(@angular-devkit/build-angular): normalize paths in ssr sourcemaps to posix when using vite

---

goldens/public-api/angular_devkit/build_angular/index.md
packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/builders/application/schema.json
packages/angular_devkit/build_angular/src/builders/application/tests/options/loader_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts

When using the `application` builder, a new `loader` option is now available for use. The option allows a project to define the type of loader to use with a specified file extension. A file with the defined extension can then used within the application code via an import statement or dynamic import expression, for instance.
The available loaders that can be used are:
* `text` - inlines the content as a string
* `binary` - inlines the content as a Uint8Array
* `file` - emits the file and provides the runtime location of the file
* `empty` - considers the content to be empty and will not include it in bundles
The loader option is an object-based option with the keys used to define the file extension and the values used to define the loader type.
An example to inline the content of SVG …

feat(@angular-devkit/build-angular): allow configuring loaders for custom file extensions in application builder

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/source-file-cache.ts
packages/angular_devkit/build_angular/src/tools/esbuild/load-result-cache.ts

The path comparisons for the TypeScript emit file lookups now use the native path normalization functions. This removes the special handling previously used and better ensures that cache checks are valid. The separate babel cache Map has also been combined with the already present memory load cache within the Angular plugin. This removes the need for extra handling of another Map and allows it to use the common logic of the load cache. To support this usage, the load cache will also now automatically include the request path in the file dependencies if the request is from the `file` namespace. This removes the need to manually specify the request path file for each load result return value.

refactor(@angular-devkit/build-angular): use native path normalization for angular compiler caching

---

packages/angular_devkit/build_angular/src/builders/application/i18n.ts
packages/angular_devkit/build_angular/src/builders/application/tests/options/extract-licenses_spec.ts

This commit adds back the root files to the `outputFiles` when localize is enabled.
Closes #26386

fix(@angular-devkit/build-angular): emit root files when `localize` is enabled when using the esbuild based builders

---

packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts

The TypeScript compiler converts all paths to use POSIX path separators. When on Windows, this can cause problems when comparing paths from other parts of the build system including the file watching provided by `chokidar`. The referenced files returned from the TypeScript compiler are now normalized to the native path format to mitigate this problem. This also avoids an issue where the same files but with differing path separators were included in the watch files list on Windows due to the bundler using native paths and TypeScript using converted paths.

fix(@angular-devkit/build-angular): ensure watch file paths from TypeScript are normalized

---

tests/legacy-cli/e2e/tests/vite/reuse-dep-optimization-cache.ts

The test is changed to now wait for Vite to output that it has optimized the dependencies
after a request to the main application chunk. This removes the need to wait a specific
amount of time between steps. The `vite:deps` part of the console text check was also
removed to avoid any potential comparison problems with ansi color codes.
The final `killAllProcesses` is also removed since the test runner will always run that
function at the end of every test.

test: attempt to reduce flakiness of Vite cache reuse test

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts

To avoid potential confusion when updating to v17, the usage warning as been removed from the `browser-esbuild` builder. The `browser-esbuild` builder is considered stable and fully supported. This is in addition to the other stable builders: `browser` and `application`. The `browser-esbuild` builder provides similar behavior to the `browser` builder but with the performance improvements of the `application` builder. However, `browser-esbuild` does not have integrated SSR support and will not receive new/future `application` builder options and features.
For more details on these builders, please see: https://angular.io/guide/esbuild

fix(@angular-devkit/build-angular): remove browser-esbuild usage warning

---

tests/legacy-cli/e2e.bzl

Prior to this change, all snapshot tests were being executed using webpack

build: add missing args concat in snapshots e2e tests

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

With the Vite-based development server, the build pipeline itself watches for files and rebuilds the relevant parts of the application as needed. The Vite file watching is unneeded and was previously setup to ignore all files. This worked but was not ideal as chokidar was still initialized inside Vite. However, Vite now supports fully disabling the file watching by passing `null` for the Vite watch option value.

refactor(@angular-devkit/build-angular): fully disable Vite internal file watching

---

tests/legacy-cli/e2e/tests/basic/serve.ts
tests/legacy-cli/e2e/tests/build/poll.ts
tests/legacy-cli/e2e/tests/build/rebuild-deps-type-check.ts
tests/legacy-cli/e2e/tests/build/rebuild-replacements.ts
tests/legacy-cli/e2e/tests/build/rebuild-types.ts
tests/legacy-cli/e2e/tests/build/ssr/express-engine-csp-nonce.ts
tests/legacy-cli/e2e/tests/build/ssr/express-engine-ngmodule.ts
tests/legacy-cli/e2e/tests/build/ssr/express-engine-standalone.ts
tests/legacy-cli/e2e/tests/commands/e2e/e2e-and-serve.ts
tests/legacy-cli/e2e/tests/commands/serve/reload-shims.ts
tests/legacy-cli/e2e/tests/commands/serve/serve-path.ts
tests/legacy-cli/e2e/tests/misc/fallback.ts
tests/legacy-cli/e2e/tests/misc/proxy-config.ts
tests/legacy-cli/e2e/tests/vite/ssr-error-stack.ts

The E2E test runner will always perform the call after the completion of each E2E test. This removes the need to manually execute the helper function at the end of a test. All tests that did so have had the call removed from the end of the test. Some tests use the helper within the test and those calls have not been altered and remain.
REVIEW NOTE: Consider enabling "Hide whitespace"

test: remove unneeded kill-all-processes calls in E2E tests

---

CHANGELOG.md

docs: release notes for the v17.0.2 release

---

packages/angular_devkit/build_angular/src/builders/application/execute-post-bundle.ts

The generated HTML files for the application were previously not included in the hash calculations for the service worker. This has now been corrected and the index file for an application will not be included when service worker support is enabled via the `serviceWorker` option.

fix(@angular-devkit/build-angular): ensure service worker hashes index HTML file for application builder

---

packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts

Prior to this change a postcss instance was created for every component style. This can cause a performance overhead when using tailwindcss, since each tailwind instance would do multiple IO calls to get the list of files specified in the `content` field.

perf(@angular-devkit/build-angular): only create one instance of postcss when needed

---

packages/angular_devkit/build_angular/src/utils/environment-options.ts

When using the `application` or `browser-esbuild` builder in watch mode on Windows, the project root will now be watched by default. This provides a workaround for users of Visual Studio which uses a file save mechanism that causes the watch mode to not correctly trigger. By watching the entire project root, this problem is avoided. However, this may result in additional rebuilds due to changes of unrelated files in the project root.
This behavior can be disabled using the environment variable `NG_BUILD_WATCH_ROOT=0`. On non-Windows platforms, disabled is the default.

fix(@angular-devkit/build-angular): default to watching project root on Windows with application builder

---

CHANGELOG.md

docs: release notes for the v17.0.3 release

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

The Vite-based development server restricts filesystem access by default. However, assets configured by the build option `assets` are intended to be accessible by the application at runtime. To ensure that these files are accessible, the allow list will now explicitly include all configured assets found during the build.
Closes https://github.com/angular/angular-cli/issues/26384

fix(@angular-devkit/build-angular): ensure all configured assets can be served by dev server

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer-worker.ts
packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer.ts
tests/legacy-cli/e2e/tests/build/library/lib-unused-decorated-class-treeshake.ts

This changes enables wrapping classes in side-effect free modules that make use of custom decorators when using the esbuild based builders so that when such classes are unused they can be treeshaken.

fix(@angular-devkit/build-angular): treeshake unused class that use custom decorators

---

goldens/public-api/angular_devkit/build_angular/index.md
goldens/public-api/angular_devkit/core/node/index.md
goldens/public-api/angular_devkit/core/node/testing/index.md
goldens/public-api/angular_devkit/schematics/index.md
goldens/public-api/angular_devkit/schematics/tasks/index.md
goldens/public-api/angular_devkit/schematics/testing/index.md
goldens/public-api/angular_devkit/schematics/tools/index.md
package.json
packages/angular_devkit/build_angular/package.json
packages/ngtools/webpack/package.json
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
yarn.lock

Updates the repo to TypeScript 5.3.

build: update to TypeScript 5.3

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

To minimize ambiguity, the update related log messages for the development server now consistently indicate that the page reload, HMR update, or otherwise has actually been sent to any connected clients.

refactor(@angular-devkit/build-angular): adjust wording of dev server client status messages

---

packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts

When the `preserveSymlinks` option is false (the default), the tsconfig path was passed through realpath to ensure that the TypeScript source files were resolved correctly. However, the promise version of the Node.js API was previously used. This version used `realpath.native` internally but the native version has numerous behavior problems on Windows systems. This includes potential case conversion which can result in differing cases for files within the build system and in turn failed path comparison checks. The synchronous version is now used which has a JavaScript implementation that does not suffer from these problems.

fix(@angular-devkit/build-angular): avoid native realpath in application builder

---

packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
packages/schematics/angular/component/index_spec.ts

`ng g c` no longer generates a component with the `CommonModule` import. This import is not useful if developers adopt the control flow syntax in their templates. Instead, developers are encouraged to import the individual directives/pipes if needed.

fix(@schematics/angular): remove CommonModule import from standalone components

---

packages/angular_devkit/build_angular/src/tools/esbuild/watcher.ts
packages/angular_devkit/build_angular/src/utils/environment-options.ts

This commit, fixes a file watching issue where file changes events are not triggered when using IDEs like Visual Studio (not VS Code).
The main changes to solve the issue are;
Using `watcher.on('all')` does not capture some of events fired when using Visual studio and this does not happen all the time, but only after a file has been changed 3 or more times.
```
watcher.on('raw')
Change 1
rename | 'C:/../src/app/app.component.css'
rename | 'C:/../src/app/app.component.css'
change | 'C:/../src/app/app.component.css'
Change 2
rename | 'C:/../src/app/app.component.css'
rename | 'C:/../src/app/app.component.css'
change | 'C:/../src/app/app.component.css'
Change 3
rename | 'C:/../src/app/app.component.css'
rename | 'C:/../src/app/app.component.css'
change | 'C:/../src/app/app.component.css' …
```

fix(@angular-devkit/build-angular): improve file watching on Windows when using certain IDEs

---

packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
packages/angular_devkit/build_angular/src/builders/prerender/index.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/parallel-compilation.ts
packages/angular_devkit/build_angular/src/tools/esbuild/i18n-inliner.ts
packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer.ts
packages/angular_devkit/build_angular/src/tools/webpack/plugins/javascript-optimizer-plugin.ts
packages/angular_devkit/build_angular/src/utils/action-executor.ts
packages/angular_devkit/build_angular/src/utils/server-rendering/prerender.ts

This is no longer needed since 4.2.0

refactor(@angular-devkit/build-angular): remove piscina minThreads workaround

---

packages/angular_devkit/build_angular/src/builders/application/build-action.ts
tests/legacy-cli/e2e/tests/build/poll.ts
tests/legacy-cli/e2e/tests/build/rebuild-dot-dirname.ts
tests/legacy-cli/e2e/utils/utils.ts

This commit fixes an issue were previously, application files in a directory that starts with a dot were being ignored from watching.
Closes #26441

fix(@angular-devkit/build-angular): correctly watch files when app is in a directory that starts with a dot

---

packages/angular_devkit/build_angular/src/builders/application/build-action.ts
tests/legacy-cli/e2e/tests/build/poll.ts
tests/legacy-cli/e2e/tests/build/rebuild-dot-dirname.ts
tests/legacy-cli/e2e/utils/utils.ts

Cherry-pick of https://github.com/angular/angular-cli/pull/26473

[patch ]fix(@angular-devkit/build-angular): correctly watch files when app is in a directory that starts with a dot

---

packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts

In some cases the `$localize.locale` was being set prior to `$localize` being set through `@angular/localize`. This caused `$localize.locale` to be reset to `en-US`.
This change moves the order in which `$localize.locale` is set.
Partially addresses: #26350
Fixes: https://github.com/angular/angular-cli/issues/26409

fix(@angular-devkit/build-angular): correct set locale when using esbuild based builders

---

packages/angular_devkit/build_angular/src/builders/application/i18n.ts
packages/angular_devkit/build_angular/src/builders/application/tests/options/i18n-missing-translation_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/i18n-inliner-worker.ts
packages/angular_devkit/build_angular/src/tools/esbuild/i18n-inliner.ts

When using the `application` or `browser-esbuild` builders, localization errors were previously not being propagated to the final build result. In the event that the `i18nMissingTranslation` option was changed to error from the default of warning, the final build result would previously indicate a success if there were any missing translations present within the build. This has now been corrected and the build will now fully fail including a non-zero exit code in this case.
Closes #26499

fix(@angular-devkit/build-angular): propagate localize errors to full build result

---

packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/serve-path_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

When the `serve-path` option is used assets are now correctly servered from this location.
Closes #26509

fix(@angular-devkit/build-angular): serve assets from the provided `serve-path`

---

packages/angular_devkit/build_angular/src/builders/app-shell/index.ts

This option is not available in webpack based builders.

refactor: remove `removeSpecialComments` from webpack based builder app-shell builder

---

CHANGELOG.md

docs: release notes for the v17.0.4 release

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

When using the `application` or `browser-esbuild` builders with the `dev-server`, interactive key shortcuts are now available to use while the server is active. Once the build has successfully completed and the development server has initialized, typing a single letter key followed by enter will execute the associated action. These actions include forcing a browser full reload, clearing the console, or quitting. More actions may be added in the future.
The following actions are currently available:
```
press r + enter to force reload browser
press u + enter to show server url
press o + enter to open in browser
press c + enter to clear console
press q + enter to quit
```
The `h` action is also available which will display the above list at runtime.

feat(@angular-devkit/build-angular): support keyboard command shortcuts in application dev server

---

packages/angular/pwa/package.json

Missed this peer dependency and it's blocking next releases.

refactor: bump `@angular/pwa` peer dep for `17.0.0-next`

---

packages/angular_devkit/build_angular/src/tools/esbuild/watcher.ts
packages/angular_devkit/build_angular/src/utils/environment-options.ts

This reverts commit bbbe13d6782ba9d1b80473a98ea95bc301c48597.
Switching to `raw` event changes the event names such that some events are getting dropped and breaking watch mode rebuilds on Mac.

Revert "fix(@angular-devkit/build-angular): improve file watching on Windows when using certain IDEs"

---

CHANGELOG.md

docs: release notes for the v17.0.5 release

---

packages/angular_devkit/build_angular/src/utils/spinner.ts

When using the `application` builder with progress enabled (the default), the spinner text will now automatically contain a trailing newline. This ensures that any diagnostic messages are not awkwardly printed on the same line as the spinner.

fix(@angular-devkit/build-angular): correctly align error/warning messages when spinner is active

---

packages/angular_devkit/build_angular/src/builders/application/index.ts
packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-component_styles_spec.ts
packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-errors_spec.ts
packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-global_styles_spec.ts
packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-web-workers_spec.ts
packages/angular_devkit/build_angular/src/builders/application/tests/behavior/typescript-rebuild-lazy_spec.ts
packages/angular_devkit/build_angular/src/builders/application/tests/options/inline-style-language_spec.ts

An AbortController is now automatically linked to the `application` builder's teardown context if one has not been provided. This supports reduced overhead in the unit tests by eliminating the need to manually create and use an AbortController/AbortSignal in each test that uses watch mode. Relevant tests that were previously doing this have also been updated.

refactor(@angular-devkit/build-angular): add watch builder teardown to application builder

---

packages/schematics/angular/workspace/files/tsconfig.json.template

This commit enables `skipLibCheck` in new workspaces which is now recommended by TypeScript.  When enabled, type checking of declaration files is skipped as rather than doing a full check of all `d.ts` files, TypeScript will type check the code you specifically refer to in your app’s source code.
See: https://www.typescriptlang.org/tsconfig#skipLibCheck
Note: this option is also enabled by default when running `tsc --init`
```
npx tsc --init               
Created a new tsconfig.json with: TS 
target: es2016
module: commonjs
strict: true
esModuleInterop: true
skipLibCheck: true
forceConsistentCasingInFileNames: true
```
Some more context: https://github.com/microsoft/TypeScript-Website/pull/970

fix(@schematics/angular): enable TypeScript `skipLibCheck` in new workspace

---

packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/builders/application/tests/behavior/angular-aot-metadata_spec.ts
tests/legacy-cli/e2e/tests/build/prerender/error-with-sourcemaps.ts

When using the `application` or `browser-esbuild` builders, the internal advanced optimizations can only be applied when in AOT mode. However, they were previously only checking the AOT mode and not whether the project was configured to use script optimizations. The advanced optimizations are now conditional on both AOT mode and the `optimization.scripts` option. This can greatly improve the performance of builds in development since the Babel related processing can be skipped for all TypeScript application code.

perf(@angular-devkit/build-angular): only enable advanced optimizations with script optimizations

---

tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js

The browser compatibility CI job contains a hardcoded set of browsers and platform combinations that should be updated for each major release. This update adjusts the versions for the Angular v17 release based on the support matrix at the time of release. Based on the release cadence of chrome-based browsers, the range was increased by 2 last versions to test a larger segment of the browser usage space.

test: update browser compatibility test versions for v17

---

.eslintrc.json

The latest major (v6) of the typescript eslint plugin contains several new rule defaults that currently cause errors in the repository code while linting. To facilitate an upgrade, these rules are now preemptively disabled. Once the update is complete, these rules can be evaluated for inclusion.
The rules are as follows:
* @typescript-eslint/no-unsafe-enum-comparison
* @typescript-eslint/no-redundant-type-constituents
* @typescript-eslint/no-base-to-string
Unblocks #25522

test: disable new failing default typescript eslint rules to allow upgrading

---

tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js

Using Linux in certain combinations on Saucelabs can lead to unsupported errors when initializing Saucelab environments prior to any actual testing.

test: correct misconfigured saucelabs platform/OS combination

---

packages/angular_devkit/build_angular/src/builders/application/build-action.ts
packages/angular_devkit/build_angular/src/builders/application/index.ts
packages/angular_devkit/build_angular/src/tools/esbuild/watcher.ts

When using the esbuild based builder symlinks are not watched when `preserveSymlinks` is enabled.
Closes #26585

fix(@angular-devkit/build-angular): watch symlink when using `preserveSymlinks` option

---

CHANGELOG.md

docs: release notes for the v17.0.6 release

---

goldens/public-api/angular_devkit/build_angular/index.md
packages/angular_devkit/build_angular/src/builders/karma/index.ts
packages/angular_devkit/build_angular/src/builders/karma/schema.json

This commit enables users to disable runnings tests against a browsers. This can be done by using the `--no-browsers` command line flag or setting `browsers` to `false` in the `angular.json`
Closes #26537

feat(@angular-devkit/build-angular): add support for `--no-browsers` in karma builder

---

packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/port_spec.ts
packages/angular_devkit/build_angular/src/utils/check-port.ts

Vite appears to consider a port value of `0` as a falsy value and use the default Vite port of `5173` when zero is used as a value for the development server port option. To workaround this issue, the port checker code now explicitly handles the zero value case and determines a random port as would be done automatically by the Webpack-based development server.

fix(@angular-devkit/build-angular): ensure port 0 uses random port with Vite development server

---

packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/force-esbuild_spec.ts

To ensure that the `forceEsbuild` development server option chooses the correct underlying build implementation when the project contains the `browser` builder within the build target, an explicit check and conversion of the builder name is now performed during the initialization phase of the development server builder.

fix(@angular-devkit/build-angular): ensure browser-esbuild is used in dev server with browser builder and forceEsbuild

---

packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build-base-href_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

This commit fixes an issue were when using a `baseHref` with trailing slash, vite dev-server would have been only accessible via a URL with a trailing slash. As vite would redirect to an error page similar to the below;
```
The server is configured with a public base URL of /myapp/ - did you mean to visit [/myapp/](http://localhost:4200/myapp/) instead?
```
Closes: #26618

fix(@angular-devkit/build-angular): `baseHref` with trailing slash causes server not to be accessible without trailing slash

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/angular-host.ts

TypeScript 5.3 provides a new programmatically accessible option on the compiler host object to control the amount of JSDoc parsing that the TypeScript parser will perform. The `tsc` command line tool now uses the `ParseForTypeErrors` value which only parses JSDoc comments that may affect type checking and is considered a good default for tools such as the Angular CLI. The Angular CLI will now attempt to use the `ParseForTypeErrors` value as well when available. Projects will need to use TypeScript 5.3+ for this option to be available. No behavior changes will occur on TypeScript 5.2 projects. This should not only provide a small improvement to build times but also a reduction in overall memory usage.

perf(@angular-devkit/build-angular): reduce TypeScript JSDoc parsing in application builder

---

packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts

We now replace the user agent string used to perform font inlining with a Windows one. This is because Google fonts will including hinting in fonts for Windows. Hinting is a technique used with Windows files to improve appearance however results in 20-50% larger file sizes, however this will make the fonts display correctly on all platforms.
More information about this can be found in:
- https://fonts.google.com/knowledge/glossary/hinting
- https://glyphsapp.com/learn/hinting-manual-truetype-hinting
- http://google3/java/com/google/fonts/css/OpenSansWebFontsCssBuilder.java?l=22
Note: this has been discussed with Katie Hempenius from the Chrome Aurora team.
Closes #22248

fix(@angular-devkit/build-angular): inlining of fonts results in jagged fonts for Windows users

---

packages/angular_devkit/build_angular/src/builders/application/tests/options/optimization-fonts-inline_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/component-stylesheets.ts
packages/angular_devkit/build_angular/src/tools/esbuild/compiler-plugin-options.ts
packages/angular_devkit/build_angular/src/tools/esbuild/global-styles.ts
packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/bundle-options.ts
packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/css-inline-fonts-plugin.ts
packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts

`@import url()` to Google and Adobe fonts that are located in global and component CSS will now be inlined when using the esbuild based builders.
Input
```css
@import url(https://fonts.googleapis.com/css?family=Roboto:300,400,500);
```
Output
```css
/* latin */
@font-face {
font-family: 'Roboto';
font-style: normal;
font-weight: 500;
src: url(https://fonts.gstatic.com/s/roboto/v30/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2) format('woff2');
unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```
Closes #23054

feat(@angular-devkit/build-angular): inline Google and Adobe fonts located in stylesheets

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/builder-status-warnings.ts

The logBuilderStatusWarnings function of browser-esbuild builder checks if unsupportedOption is "deployUrl". However, deployUrl is not in the UNSUPPORTED_OPTIONS array.
The logBuilderStatusWarnings function of browser-esbuild builder does not check if unsupportedOption is "deployUrl".

refactor(@angular-devkit/build-angular): remove deployUrl from browser-esbuild builder-status-warnings

---

packages/angular_devkit/build_angular/src/builders/application/build-action.ts
packages/angular_devkit/build_angular/src/builders/application/tests/options/delete-output-path_spec.ts
packages/angular_devkit/build_angular/src/testing/builder-harness.ts
packages/angular_devkit/build_angular/src/testing/jasmine-helpers.ts
packages/angular_devkit/build_angular/src/utils/delete-output-dir.ts

The `deleteOutputPath` option will now empty specific build artifact directories instead of
removing them completely. This allows for symlinking or mounting the directories via Docker.
This is similar to the current behavior of emptying the root output path to allow similar
actions. All previous files will still be removed when the `deleteOutputPath` option is enabled.
This is useful in situations were the browser output files may be symlinked onto another
location on disk that is setup as a development server, or a Docker configuration mounts the browser
and server output to different locations on the host machine.

fix(@angular-devkit/build-angular): retain symlinks to output platform directories on builds

---

packages/angular_devkit/build_angular/src/builders/application/build-action.ts

Prior to this change, watching of an `npm link` of a library in another workspace when `preserveSymlinks` was set to `true` was not being picked up as `node_modules` files were always ignored.
Closes #25753

fix(@angular-devkit/build-angular): handle updates of an `npm link` library from another workspace when `preserveSymlinks` is `true`

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

Vite's fs.allow was being populated incorrectly.
Closes #26624

fix(@angular-devkit/build-angular): the request url "..." is outside of Vite serving allow list for all assets

---

packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-component_styles_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/jit-plugin-callbacks.ts

The load result caching capabilities of the Angular compiler plugin used within the `application` and `browser-esbuild` builders is now used for both stylesheet and template component resources when building in JIT mode. This limits the amount of file system access required during a rebuild in JIT mode and also more accurately captures the full set of watched files.

fix(@angular-devkit/build-angular): cache loading of component resources in JIT mode

---

packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-component_styles_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/jit-plugin-callbacks.ts

The load result caching capabilities of the Angular compiler plugin used within the `application` and `browser-esbuild` builders is now used for both stylesheet and template component resources when building in JIT mode. This limits the amount of file system access required during a rebuild in JIT mode and also more accurately captures the full set of watched files.
17.0.x variant of https://github.com/angular/angular-cli/pull/26636

[17.0.x] fix(@angular-devkit/build-angular): cache loading of component resources in JIT mode

---

packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build-assets_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

This commit fixes an issue which caused vite to transform JavaScript and TypeScript assets.
Closes #26641

fix(@angular-devkit/build-angular): allow vite to serve JavaScript and TypeScript assets

---

packages/angular_devkit/build_angular/src/utils/server-rendering/esm-in-memory-loader/node-18-utils.ts

In Node.js 18.19 ESM loaders works the same way as Node.js 20.9+
Closes #26648

fix(@angular-devkit/build-angular): update ESM loader to work with Node.js 18.19.0

---

packages/angular_devkit/build_angular/src/builders/application/tests/behavior/typescript-rebuild-touch-file_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/source-file-cache.ts

Before this update, removing the modified file entry from `typeScriptFileCache` when a file was saved but unmodified created an issue. The TypeScript compiler didn't re-emit the file using `emitNextAffectedFile` because the file hashes remained unchanged. Consequently, this led to missing files in the esbuild compilation process.
In the current update, we no longer delete entries from typeScriptFileCache. This adjustment resolves the problem by ensuring the proper handling of file recompilation and prevents files from going missing during the esbuild compilation.
Closes #26635

fix(@angular-devkit/build-angular): file is missing from the TypeScript compilation with JIT

---

tests/legacy-cli/e2e/tests/basic/serve.ts

This was causing `Error: The service was stopped: write EPIPE` which caused the test to fail on Node.js 18.

Fix MAIN CI

---

CHANGELOG.md

docs: release notes for the v17.0.7 release

---

packages/angular_devkit/build_angular/src/builders/application/tests/behavior/component-stylesheets_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/angular-host.ts

When an optimized Sass stylesheet becomes an empty string the AOT Angular host adapter was previously treating this as a falsy value and using the original content of the stylesheet. Empty strings are now considered valid values and will be passed to the AOT compiler as such.
Closes: #26653

fix(@angular-devkit/build-angular): ensure empty optimized Sass stylesheets stay empty

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
tests/legacy-cli/e2e.bzl
tests/legacy-cli/e2e/tests/commands/serve/ssr-http-requests-assets.ts

With vite `header.host` is undefined when SSL is enabled. This resulted in an invalid URL to be constructed.
Closes #26652

fix(@angular-devkit/build-angular): construct SSR request URL using server resolvedUrls

---

tests/legacy-cli/e2e/utils/test_process.ts

This fixes an issue on Linux CI that `ng serve` sub-process is not terminated properly when using tree-kill which causes the tests test process not to exit.

refactor: update test runner to use proxess.exit instead of treekill

---

goldens/public-api/angular_devkit/build_angular/index.md
packages/angular_devkit/build_angular/src/builders/application/index.ts
packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts

Similar to the `dev-server` builder, the `application` builder's programmatic usage can now transform the index HTML that is generated during a build. As is the case for the existing builder JavaScript exports from the package, the new export (`buildApplication`) is also considered experimental and does not provide the support nor semver guarantees that the builders have when used via `angular.json` configuration.
The third parameter of the `buildApplication` function can now be an extensions object with one of the fields being `indexHtmlTransformer`. This newly introduced field allows adjusting the index HTML content.
Closes #26299

refactor(@angular-devkit/build-angular): add index HTML transformer to application programmatic usage

---

goldens/public-api/angular_devkit/build_angular/index.md
packages/angular_devkit/build_angular/src/builders/application/build-action.ts
packages/angular_devkit/build_angular/src/builders/application/index.ts
packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/builders/application/schema.json
packages/angular_devkit/build_angular/src/builders/application/tests/options/output-path_spec.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts

This update introduces the ability for users to define the locations for storing `media`, `browser`, and `server` files.
You can achieve this by utilizing the extended `outputPath` option.
```json
{
"projects": {
"my-app": {
"architect": {
"build": {
"builder": "@angular-devkit/build-angular:application",
"options": {
"outputPath": {
"base": "dist/my-app",
"browser": "",
"server": "node-server",
"media": "resources"
}
}
}
}
}
}
}
```
While not recommended, choosing to set the `browser` option empty will result in files being output directly under the specified `base` path. It's important to note that this action will generate certain files like `stats.json` and `prerendered-routes.json` that aren't intended for deployment in this directory.
**Validation rules:**
- `browser` and `server` …

feat(@angular-devkit/build-angular): allow customization of output locations

---

packages/angular/cli/src/commands/version/cli.ts

Bazel and NgUniversal packages information is not needed in version 17.

refactor(@angular/cli): remove no longer relevant regexps from `ng version` checks

---

packages/angular/cli/src/command-builder/schematics-command-module.ts

This got accidentally deleted during the transition to yargs.
Closes #26496

fix(@angular/cli): re-add `-d` alias for `--dry-run`

---

packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/builders/application/schema.json
packages/angular_devkit/build_angular/src/builders/application/tests/options/index_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/index-html-generator.ts

The long-form variant of the `index` option for the `application` builder now supports an addition sub-option named `preloadInitial`. This new option is a boolean option that controls the generation of initial preload related link elements in the generated index HTML file for the application. Preload related link elements include `preload`, `modulepreload`, and `preconnect` link rels for initial JavaScript and stylesheet application files.
Closes #26330

feat(@angular-devkit/build-angular): allowing control of index HTML initial preload generation

---

packages/angular_devkit/schematics_cli/bin/schematics.ts

This helper is only used in one location and can be replicated by adjusting the whitespace of the string within the code. This reduces the number of value imports from `@angular-devkit/core` to only one remaining.

refactor(@angular-devkit/schematics-cli): remove usage of devkit core tags helper

---

packages/angular/pwa/pwa/index.ts

The index HTML augmentation within the PWA schematic now uses the Node.js promise-based pipeline helper to reduce the complexity of the code when using the parse5 streaming rewriter. This removes a noticeable amount of code as well as removing the need to manually wrap the result in a Promise.

refactor(@angular/pwa): use stream pipeline operator with HTML rewriter

---

packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts

The promise creation overhead when calculating the estimated transfer size of the output files during an optimized build has been reduced by directly using the `brotliCompress` Node.js function instead of using a promisified variant. Node.js only provides a callback-based async variant for brotli compression. This change allows for a single promise to be used.

refactor(@angular-devkit/build-angular): reduce promise creation during estimated transfer size calculation

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts

The metadata used by the development server to determine the prebundling and externalization behavior is now created using the external configurations of each bundling operation context directly instead of the higher level `externalDependencies` build option. This better captures the explicitly defined external values as each bundling operation configuration could contain additional values based on the needs and/or customization of each. This will have no current noticeable behavior change as the default behavior currently does not differ from the higher level option.

refactor(@angular-devkit/build-angular): use direct explicit external configuration for metadata

---

packages/angular_devkit/build_angular/src/builders/application/tests/options/external-dependencies_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts

When processing a Web Worker reference in application code, the Web Worker entry point is bundled in a separate action. The external dependencies configuration was previously not passed on to this action which caused the Web Worker bundling to attempt to bundle any configured external dependencies. This could lead to build errors if the dependency does not exist within the project.

fix(@angular-devkit/build-angular): ensure external dependencies are used by Web Worker bundling

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts

This is no longer needed since the path provided is already passed through `realpathSync`. https://github.com/angular/angular-cli/blob/9d7d136b32a8bb0e0d70a502071418c9e4beaa05/packages/angular_devkit/build_angular/src/builders/application/options.ts#L104-L109

refactor(@angular-devkit/build-angular): remove no longer needed `realpathSync`

---

tests/legacy-cli/e2e/tests/commands/add/version-specifier.ts

The goal of the `commands/add/version-specifier` test is to check the behavior of the `ng add` command itself and not that of the package manager. To do so requires adding a package using a variety of different version specifiers. Some of which a package manager may consider incompatible with the hosting project. However, this is not relevant to the selection logic of the `ng add` command which should select the version as designed. To verify it does so within the Angular CLI, the installed version needs to be checked. As a result the package manager must install the package.

test: always use package manager force option in version add command E2E

---

packages/angular_devkit/build_angular/src/builders/application/tests/options/sourcemap_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/component-stylesheets.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/jit-plugin-callbacks.ts
packages/angular_devkit/build_angular/src/tools/esbuild/compiler-plugin-options.ts
packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/bundle-options.ts

This commits, changes the behaviour in the esbuild based builders by emitting component sourcemaps in external files instead of inlining them.
Closes #24049 and closes #26676

feat(@angular-devkit/build-angular): emit external sourcemaps for component styles

---

packages/angular/cli/src/command-builder/architect-base-command-module.ts
packages/angular/cli/src/commands/add/cli.ts

This fixes an issue where prompts in nested child processes on Windows require multiple keystrokes to proceed.
Closes #26724

fix(@angular/cli): `ng e2e` and `ng lint` prompt requires to hit Enter twice to proceed on Windows

---

packages/angular/cli/src/command-builder/architect-base-command-module.ts

Instead of checking for existence of PNP config files we now use `process.versions.pnp`. See https://yarnpkg.com/advanced/pnpapi#processversionspnp

refactor(@angular/cli): use `process.versions.pnp` to determine if PNP is used in `warnOnMissingNodeModules`

---

packages/schematics/angular/utility/workspace-models.ts

The interface `ServeBuilderOptions` from `@schematics/angular/utility/workspace-model` is missing the property `buildTarget`
Issue Number: https://github.com/angular/angular-cli/issues/26693
The interface `ServeBuilderOptions` from `@schematics/angular/utility/workspace-model` now has the the property `buildTarget`. It's optional to avoid a breaking change, until the next major.
Note: I've left the obsolete `browserTarget` required property to avoid a breaking change. IMHO it's should be removed in the next major. But I marked the `browserTarget` property as `@deprecated`.

fix(@schematics/angular): add missing property "buildTarget" to interface "ServeBuilderOptions"

---

CHANGELOG.md

docs: release notes for the v16.2.11 release

---

CHANGELOG.md

GitHub encountered a 502 error when `ng-dev` attempted to create the changelog cherry pick PR, so doing this one manually.

docs: changelog cherry pick for 17.0.8 release

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts

To ensure that Vite does not unintentionally attempt to prebundle a module that was explicitly marked as external (typically via the `externalDependencies` build option), the full list of externalized imports is now filtered by the dependencies specified within the external configuration. Vite currently will include a module for prebundling if it is present in the include list even though it may also be present in the exclude list.
Closes #26730

fix(@angular-devkit/build-angular): filter explicit external dependencies for Vite prebundling

---

packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
packages/angular_devkit/build_angular/src/builders/prerender/index.ts

The application builder has built-in prerendering and app-shell generation capabilities which makes using these builders redundant.

fix(@angular-devkit/build-angular): emit error when using prerender and app-shell builders with application builder

---

packages/schematics/angular/application/index.ts
packages/schematics/angular/application/index_spec.ts
packages/schematics/angular/ssr/index.ts

The `skipInstall` option was never passed to the ssr schematic, which caused NPM install to also be invoked when running `ng new --ssr`.
Closes #26727

fix(@schematics/angular): do not trigger NPM install when using `---skip-install` and `--ssr`

---

packages/schematics/angular/utility/ast-utils.ts

There is typo in `expresssion` variable name that is part of the `addSymbolToNgModuleMetadata` function from AST utils.
Variable name has been changed to `expression`

refactor(@schematics/angular): fix typo in "expression" variable name inside "addSymbolToNgModuleMetadata" function

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

Reverts angular/angular-cli#26750
The original change breaks Windows bazel build. 
```
ERROR: D:/a/angular-cli/angular-cli/packages/angular_devkit/build_angular/BUILD.bazel:80:11: Compiling TypeScript (devmode) //packages/angular_devkit/build_angular:build_angular failed: missing input file 'external/npm/node_modules/json-joy/es2020/json-crdt/nodes/con/ConNode.d.ts', owner: '@npm//:node_modules/json-joy/es2020/json-crdt/nodes/con/ConNode.d.ts'
ERROR: D:/a/angular-cli/angular-cli/packages/angular_devkit/build_angular/BUILD.bazel:80:11: Compiling TypeScript (devmode) //packages/angular_devkit/build_angular:build_angular failed: missing input file 'external/npm/node_modules/json-joy/es6/json-crdt/nodes/con/ConNode.d.ts', owner: '@npm//:node_modules/json-joy/es6/json-crdt/nodes/con/ConNode.d.t …
```

Revert "build: update dependency webpack-dev-middleware to v7"

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/component-stylesheets.ts
packages/angular_devkit/build_angular/src/tools/esbuild/cache.ts
packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer-worker.ts
packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer.ts
packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/sass-language.ts

Several parts of application builder use slightly different variants of an in-memory cache. To avoid duplication of code, unified cache infrastructure is now available for use internally. This also allows for expanded use in other areas of the build system including the future potential for adding additional backing cache stores.

refactor(@angular-devkit/build-angular): create reusable internal cache infrastructure

---

packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer-worker.ts

Due to the file structure of Bazel Windows builds, type annotations are required in certain locations to successfully build the project. Function return type annotations are generally recommended anyway within the code.

build: add function type annotation for bazel win32 build support

---

packages/angular_devkit/schematics/src/rules/template.ts

Currently, when using `ng new` on Windows, users will get a number of `LF will be replaced by CRLF the next time Git touches it` warnings.
This commit, replaces the line endings in templates to be platform specific.
Closes #26764

fix(@angular-devkit/schematics): replace template line endings with platform specific

---

CHANGELOG.md

docs: release notes for the v17.0.9 release

---

package.json
packages/angular/cli/BUILD.bazel
packages/angular/cli/lib/config/workspace-schema.json
packages/angular_devkit/build_angular/BUILD.bazel
packages/angular_devkit/build_angular/builders.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/builders/jest/index.ts
packages/angular_devkit/build_angular/src/builders/web-test-runner/builder-status-warnings.ts
packages/angular_devkit/build_angular/src/builders/web-test-runner/index.ts
packages/angular_devkit/build_angular/src/builders/web-test-runner/jasmine_runner.js
packages/angular_devkit/build_angular/src/builders/web-test-runner/options.ts
packages/angular_devkit/build_angular/src/builders/web-test-runner/options_spec.ts
packages/angular_devkit/build_angular/src/builders/web-test-runner/schema.json
packages/angular_devkit/build_angular/src/builders/web-test-runner/test_page.html
packages/angular_devkit/build_angular/src/utils/test-files.ts
packages/angular_devkit/build_angular/src/utils/test-files_spec.ts
tests/legacy-cli/e2e/tests/web-test-runner/basic.ts
tests/legacy-cli/e2e/utils/web-test-runner.ts
yarn.lock

This adds a new `@angular-devkit/build-angular:web-test-runner` builder which invokes Web Test Runner to execute tests. The initial implementation is still experimental and lacks a lot of features, but it is sufficient to run tests generated by `ng new`.
There's no docs or setup instructions yet, however the main path to trying this out is to replace `@angular-devkit/build-angular:karma` with `@angular-devkit/build-angular:web-test-runner` in `angular.json`. Since Web Test Runner is intended to be a drop-in replacement for Karma, options should mostly align. Currently only a couple options are actually supported right now, but more will be added over time.
The commit messages go more in detail on the implementation. In particular, Web Test Runner integration is done via a custom HTML page …

Initial Web Test Runner Implementation

---

CHANGELOG.md
package.json

Also this PR cherry-picks the changelog for v17.1.0-rc.0 into the main branch so that the changelog is up to date.

Update next branch to reflect new release-train "v17.2.0-next.0".

---

tests/legacy-cli/e2e/utils/web-test-runner.ts

It doesn't appear to be finding the Chrome binary from Bazel correctly. Likely a Bazel-specific issue. This should get the build green immediately, will need to spend more time looking into the issue.

ci: disable WTR e2e test on Windows

---

.github/workflows/ci.yml

This automatically runs full CI for any branch prefixed with `ci-`. This makes it easier to manually run CI prior to opening a pull request without having to update any files and make sure they aren't accidentally included in the final PR.

ci: add `ci-*` to GitHub actions config

---

packages/angular_devkit/build_angular/src/builders/web-test-runner/index.ts

Turns out this isn't needed for `application` builder to correctly resolve inputs. Not using `process.cwd` should make this builder a little less brittle for monorepo use cases or when running `ng test` inside a subdirectory.

refactor: remove `process.cwd` from Web Test Runner builder

---

yarn.lock

Somehow the requested and resolved versions of `sauce-connect-proxy` got desynced and downgraded to 4.8.1 in 68dae539adfa12d6088f96ac5c9f224d9bb52e17. This reverts that change and bumps it back up to 4.9.1 which appears to fix Saucelabs CI.

ci: fix `sauce-connect-proxy` version

---

tests/legacy-cli/e2e.bzl
tests/legacy-cli/e2e/utils/process.ts
tests/legacy-cli/e2e/utils/web-test-runner.ts
tests/legacy-cli/e2e_runner.ts

Needed to set `$CHROME_PATH` correctly for Web Test Runner / Chrome launcher to correctly find the the Chrome binary provided by Bazel.

Fix Web Test Runner e2e test on Windows

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts

To improve the readability and discoverability of any warnings or errors present during build, the diagnostic messages will be shown after the build stats are displayed. For large projects the amount of generated files previously could cause warnings to scroll off the screen and potentially be missed.
Closes #26514

fix(@angular-devkit/build-angular): show diagnostic messages after build stats

---

packages/angular_devkit/build_angular/src/builders/application/index.ts

The `buildApplication` function normalizes the provided extensions incorrectly. When an object of the`ApplicationBuilderExtensions` type is provided with the esbuild plugin and/or the index HTML transformer function, the value is lost and the `buildApplicationInternal` function is invoked with `undefined`.
The `buildApplication` function normalizes the provided extensions correctly. If an object of `ApplicationBuilderExtensions` type is provided, it is used as is.

fix(@angular-devkit/build-angular): fix normalization of the application builder extensions

---

packages/angular_devkit/build_angular/src/builders/application/build-action.ts
packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/application/setup-bundling.ts
packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts

To reduce the amount of code within the main `application` builder execution function, the bundler context setup has been moved into a separate file. This also reduces the amount of imports within the main execution function's module.

refactor(@angular-devkit/build-angular): move bundler context setup into separate file

---

goldens/public-api/angular_devkit/build_angular/index.md
packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts

When using the experimental programmatic API for the development server, the choice of builder used to execute the actual underlying build can now be chosen via a selector function extension option. The returned string value must be one of the first-party esbuild-based builders for the Vite-based development server to be used. All other returned values will cause the Webpack-based development server to be used. The Vite-based development server currently requires one of those builders to be used (either `@angular-devkit/build-angular:application` or `@angular-devkit/build-angular:browser-esbuild`).

refactor(@angular-devkit/build-angular): add experimental builder selector extension for dev-server

---

.circleci/dynamic_config.yml

ci: remove daily CI run for v14.x

---

CHANGELOG.md

docs: release notes for the v17.0.10 release

---

CHANGELOG.md

Cherry-picks the changelog from the "17.1.x" branch to the next branch (main).

docs: release notes for the v17.1.0-rc.1 release

---

goldens/public-api/angular_devkit/architect/index.md
packages/angular_devkit/architect/src/api.ts
packages/angular_devkit/build_angular/src/builders/dev-server/options.ts
packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
packages/angular_devkit/build_angular/src/builders/extract-i18n/options.ts
packages/angular_devkit/build_angular/src/builders/extract-i18n/schema.json

The `buildTarget` options for both the `dev-server` and `extract-i8n` builders now have default values that reflect the recommended and new project generated values. The defaults are as follows where `<current-project>` is the name of the project where the `dev-server` or `extract-i18n` builder target is located:
* `dev-server` --> `<current-project>:build:development`
* `extract-i18n` --> `<current-project>:build`
Additionally, abbreviated target specifiers are now supported for these options. This allows target specifiers such as `::production` which would expand to `<current-project>:build:production` for either builder. Abbreviated target specifiers are only supported for the `buildTarget` option in the `dev-server` and `extract-i18n` builders.

feat(@angular-devkit/build-angular): provide default and abbreviated build target support for dev-server and extract-i18n

---

packages/angular_devkit/build_angular/src/builders/jest/index.ts
packages/angular_devkit/build_angular/src/builders/jest/jest.config.mjs
tests/legacy-cli/e2e/tests/jest/custom-config.ts

Refs #25434.
Currently with Jest we're experimenting with whether or not Angular CLI can meet user needs without exposing the underlying configuration file. See https://github.com/angular/angular-cli/issues/25434#issuecomment-1610298235 for more context.
If hiding the Jest configuration is a challenge for you, please consider if an alternative approach _without_ hooking into the Jest config is reasonable. Otherwise please post your use case to https://github.com/angular/angular-cli/issues/25434 so we can evaluate the best path forward for this feature.
Jest was incorrectly picking up custom configurations, even though they exist outside Jest's root directory. This commit fixes that behavior so Jest does not see user configurations and does not apply them. Ideally we would throw an error …

fix: ignore custom Jest configuration file and warn if one is found

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/angular-compilation.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/aot-compilation.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/index.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/jit-compilation.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/parallel-compilation.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/parallel-worker.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular_devkit/build_angular/src/utils/environment-options.ts

To support generate diagnostics in varying ways, the internal compilation classes now support a `modes` argument when diagnosing files during a build using the `application` builder. This is not exposed as an option at this time but can be experimented with a build using the `NG_BUILD_TYPE_CHECK` environment variable. This environment variable is not considered part of the public API and may be removed or altered in the future. Its current purpose is to allow profiling of the type checking diagnostics functionality of the build system.

refactor(@angular-devkit/build-angular): allow internal Angular compilation control of diagnostic modes

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

This commit fixes an issue were `OPTIONS` requests were not being proxied when using Vite dev-server
Closes #26782

fix(@angular-devkit/build-angular): alllow `OPTIONS` requests to be proxied when using `vite`

---

CHANGELOG.md

Cherry-picks the changelog from the "17.1.x" branch to the next branch (main).

docs: release notes for the v17.1.0 release

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts

To reduce the amount of code within the main Vite development server file, the Vite plugin that handles the in-memory output file integration for the Angular build system is now within a separate file.

refactor(@angular-devkit/build-angular): move Angular memory Vite plugin into separate file

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

This commit updates vite to address https://github.com/advisories/GHSA-c24v-8rfc-w8vw
Closes #26916

fix(@angular-devkit/build-angular): update dependency vite to v4.5.2

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/component-stylesheets.ts

Previously, we `joined` the workspace root with the `outputFile.path`, in windows this caused a problem as during the 2nd rebuild it caused the workspace root to be prepended again which causes a `ENOENT` error. To avoid this problem, now we `clone` the output file.
Closes #26900

fix(@angular-devkit/build-angular): `ENOENT: no such file or directory` on Windows during component rebuild

---

packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/css-resource-plugin.ts

This change fixes an issue which caused internal virtual inputs to be added to the watch, this cases watchpack to emit a removed event as this file does not exist on disk.
We fix this issue, by prefixing `css-resouces` namespace with `angular:` which the input to be filtered out, see: https://github.com/angular/angular-cli/blob/4539961968e90c8c40ed683afe1cf491630a0048/packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts#L251
Closes #26918

fix(@angular-devkit/build-angular): do not add internal CSS resources files in watch

---

packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts

This commit fixes a regression which causes a pre-transform error when using vite with ssr. The `request.url` is now passed to the index transformer instead of `request.originalUrl`. This is because the `request.url` will have a value of the `index.html`.
Closes #26897

fix(@angular-devkit/build-angular): pre-transform error when using vite with SSR

---

packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
packages/angular_devkit/build_angular/src/tools/esbuild/external-packages-plugin.ts

Previously, the `application` builder would consider all imports originating from a package to be considered external when caching was enabled. This allows Vite's prebundling to function and optimize the build/rebuild experience for the development server. However, when using the newly introduced `loader` option, this also inadvertently caused files that should be affected by the option that originate from a package to also be considered external. This behavior would then prevent the loader customization from being performed. To rectify this situation, all files that would be affected by a loader customization will not be marked as external for the purposes of prebundling unless explicitly configured by the `externalDependencies` option.
Closes #26866

fix(@angular-devkit/build-angular): allow package file loader option with Vite prebundling

---

packages/angular/cli/lib/config/workspace-schema.json

fix(@angular/cli): update regex to validate the project-name
Ensure that the regex used for validating the project-name is updated to address any issues and enhance accuracy.
the existing regex for project-name validation was not validating the name with the dot(.) in application name.
Fixes #25704 
Issue Number: #25704  
Project name can include the dot(.) in the name while creating the project but while validating the dot(.) was missing. I updated the pattern to accept dot(.) in projectName.

fix(@angular/cli): update regex to validate the project-name

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

This commit updates vite to address https://github.com/advisories/GHSA-c24v-8rfc-w8vw
Closes https://github.com/angular/angular-cli/issues/26916

fix(@angular-devkit/build-angular): update dependency vite to v5.0.12

---

packages/schematics/angular/utility/standalone/rules.ts
packages/schematics/angular/utility/standalone/rules_spec.ts

This fixes an issue which caused the new provider to be added in the position of the trailing comma. With this change the trailing comma is retained.
Closes #26911

fix(@schematics/angular): retain trailing comma when adding providers to app config

---

packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts

Vite v5 updated the client code's error dialog text. This requires that the text replacement code also be updated to remove unactionable information from the error dialog.

refactor(@angular-devkit/build-angular): update Vite client code loading for v5

---

CHANGELOG.md

docs: release notes for the v16.2.12 release

---

packages/angular/ssr/src/inline-css-processor.ts
packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
tests/legacy-cli/e2e/tests/build/ssr/express-engine-csp-nonce.ts

The `load` event for each stylesheet may not always be triggered by Google Chrome's handling. Refer to: https://crbug.com/1521256
This results in the media attribute persistently being set to print, leading to distorted styles in the UI. To address this issue, we substitute the onload logic by replacing `link.addEventListener('load', ...` with `document.documentElement.addEventListener('load', ...` and filtering for link tags.
Closes #26932

fix(@angular-devkit/build-angular): handle handle load event for multiple stylesheets and CSP nonces

---

packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build-assets_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts

This commit updates the vite dev-server to return 404 for assets and files that are not found.
Closes #26917

fix(@angular-devkit/build-angular): return 404 for assets that are not found

---

packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts

Prior to this change any module which was used using `require` was not listed as an external.
Closes #26833

fix(@angular-devkit/build-angular): add `required` modules as externals imports

---

packages/angular_devkit/build_angular/src/builders/extract-i18n/application-extraction.ts

This commit disables index and service worker generation when using the i18n extraction together with the esbuild builders.

refactor(@angular-devkit/build-angular): disable SW and index generation during i18n extraction

---

packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts

Currently the `result` variable will be set to `any` which caused a large part of this file not to be safely typed.

refactor(@angular-devkit/build-angular): increase type safety in bundle-context

---

goldens/public-api/angular_devkit/core/index.md
packages/angular_devkit/core/src/virtual-fs/host/interface.ts

const enums complicate the potential use of the TypeScript isolatedModules option.

refactor(@angular-devkit/core): remove single usage of const enum

---

goldens/public-api/angular_devkit/architect/index.md
goldens/public-api/angular_devkit/core/index.md
packages/angular_devkit/architect/src/jobs/index.ts
packages/angular_devkit/architect/src/jobs/strategy.ts
packages/angular_devkit/architect/src/jobs/strategy_spec.ts
packages/angular_devkit/core/src/virtual-fs/host/index.ts
packages/angular_devkit/core/src/virtual-fs/host/record_spec.ts
packages/angular_devkit/core/src/virtual-fs/host/test.ts
packages/angular_devkit/core/src/virtual-fs/host/test_spec.ts
packages/angular_devkit/schematics/src/tree/interface.ts

The `namespace` TypeScript usage within the CLI has been removed. This syntax is not recommended outside of type definition files.
Recommended to review with hide whitespace enabled.

refactor: remove outdated namespace syntax usage

---

packages/angular_devkit/build_angular/src/builders/application/options.ts

Prior to this change using an absolute path as a `output-path` resulted in the path to be combined with the workspace root instead of resolved which caused the output to be emitted in the incorrect directory or error in Windows.
Closes #26935

fix(@angular-devkit/build-angular): resolve absolute `output-path` when using esbuild based builders

---

packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/proxy-config_spec.ts
packages/angular_devkit/build_angular/src/utils/load-proxy-config.ts

This commit fixes an issue were negated globs in proxy config were not process correctly when using vite.
Closes #26970

fix(@angular-devkit/build-angular): correctly handle glob negation in proxy config when using vite

---

packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/proxy-config_spec.ts
packages/angular_devkit/build_angular/src/utils/load-proxy-config.ts

This commit enables proxies to have a RegExp as context when using Vite. See: https://vitejs.dev/config/server-options#server-proxy
Closes #26970

fix(@angular-devkit/build-angular): handle regular expressions in proxy config when using Vite

---

packages/angular_devkit/build_angular/src/tools/babel/plugins/pure-toplevel-functions.ts

The `pure-toplevel-functions` build optimization pass have been cleaned up and restructured to remove the need for a direct runtime dependency on `@babel/core`.

refactor(@angular-devkit/build-angular): remove babel core runtime imports from `pure-toplevel-functions` build optimizer pass

---

packages/angular_devkit/build_angular/src/tools/babel/plugins/elide-angular-metadata.ts

The `elide-angular-metadata` build optimization pass have been cleaned up and restructured to remove the need for a direct runtime dependency on `@babel/core`.

refactor(@angular-devkit/build-angular): remove babel core runtime imports from `elide-angular-metadata` build optimizer pass

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/application/setup-bundling.ts
packages/angular_devkit/build_angular/src/builders/browser/specs/scripts-array_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/budget-stats.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts
packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
packages/angular_devkit/build_angular/src/tools/webpack/utils/stats.ts
tests/legacy-cli/e2e/tests/basic/build.ts
tests/legacy-cli/e2e/tests/basic/styles-array.ts
tests/legacy-cli/e2e/tests/build/progress-and-stats.ts

This commit adds server bundle information to the build logs.
Closes #25855

fix(@angular-devkit/build-angular): display server bundles in build stats

---

packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/tools/esbuild/compiler-plugin-options.ts
packages/angular_devkit/build_angular/src/tools/esbuild/global-styles.ts
packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/bundle-options.ts
packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts
packages/angular_devkit/build_angular/src/utils/postcss-configuration.ts

When using the `application` builder, the usage of a custom postcss configuration is now supported. The builder will automatically detect and use specific postcss configuration files if present in either the project root directory or the workspace root. Files present in the project root will have priority over a workspace root file. If using a custom postcss configuration file, the automatic tailwind integration will be disabled. To use both a custom postcss configuration and tailwind, the tailwind setup must be included in the custom postcss configuration file.
The configuration files must be JSON and named one of the following:
* `postcss.config.json`
* `.postcssrc.json`
A configuration file can use either an array form or an object form to setup plugins. An example of the array form: …

feat(@angular-devkit/build-angular): support using custom postcss configuration with application builder

---

packages/angular_devkit/build_angular/src/builders/application/build-action.ts
packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/application/index.ts
packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts
packages/angular_devkit/build_angular/src/tools/esbuild/global-scripts.ts
packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
packages/angular_devkit/build_angular/src/utils/environment-options.ts

This change implements the capability to display JSON build logs in the terminal instead of a format readable by humans. This is particularly useful for hosting providers, as it allows them to effortlessly access the necessary information without having to parse the JSON configuration.
To enable this output, set the `NG_BUILD_LOGS_JSON=1` environment variable. Additionally, warnings, errors, and logs are automatically colorized when the standard output is a WritableStream. You can disable the colors by using the `FORCE_COLOR=0` environment variable.
```
FORCE_COLOR=0 NG_BUILD_LOGS_JSON=1 ng b
{
"errors": [],
"warnings": [],
"outputPaths": {
"base": "file:///usr/local/test/home//test-project/dist/test-project",
"browser": "file:///usr/local/test/home//test-project/dist/test-project/browser" …
```

feat(@angular-devkit/build-angular): add JSON build logs when using the application builder

---

CHANGELOG.md

Cherry-picks the changelog from the "17.1.x" branch to the next branch (main).

docs: release notes for the v17.1.2 release

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

Since this change https://github.com/angular/angular-cli/commit/4b3a965429bfaa6559693b2a3b69565455a75866 A warning is displayed when using `./` as a base href
```
(!) invalid "base" option: ".". The value can only be an absolute URL, "./", or an empty string.
```

fix(@angular-devkit/build-angular): allow `./` baseHref when using vite based server

---

packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
packages/angular_devkit/build_angular/src/tools/esbuild/external-packages-plugin.ts

To support future use cases, the internal `externalPackages` application builder option now also accepts an object form with an `exclude` array field in addition to the existing boolean value. The `exclude` capability allows for specifying individual packages that should always be bundled when using the external packages functionality. Currently the external packages functionality is only used by the Vite-based development server.

refactor(@angular-devkit/build-angular): allow internal externalPackages option to exclude packages

---

goldens/public-api/angular_devkit/build_angular/index.md
packages/angular_devkit/build_angular/src/builders/application/build-action.ts
packages/angular_devkit/build_angular/src/builders/application/index.ts
packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/builders/application/schema.json

When setting `"clearScreen": true` to the appliction builder during rebuilds the terminimal screen will be cleaned.
```json
{
"projects": {
"my-app": {
"projectType": "application",
"root": "",
"sourceRoot": "src",
"architect": {
"build": {
"builder": "@angular-devkit/build-angular:application",
"options": {
"clearScreen": true
}
}
}
}
}
}
```
Closes #25699

feat(@angular-devkit/build-angular): provide option to allow automatically cleaning the terminal screen during rebuilds

---

goldens/public-api/angular_devkit/build_angular/index.md
packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
packages/angular_devkit/build_angular/src/builders/dev-server/options.ts
packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
packages/angular_devkit/build_angular/src/builders/dev-server/tests/execute-fetch.ts
packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/prebundle_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

Previously, the Vite-based development server that is automatically used with the `application` and `browser-esbuild` builders would always use prebundling if the Angular CLI caching was enabled. The development server now has a specific `prebundle` option to allow more control over prebundling while still allowing other forms of caching within the Angular CLI. The `prebundle` option can be a boolean value of `true` or `false` that will enable or disable prebundling, respectively. Additionally, the option also has an object long-form. This long-form enables prebundling and currently contains one property named `exclude`. The `exclude` property supports cases where a package should not be prebundled and rather should be bundled directly into the application code. These cases are not common …

feat(@angular-devkit/build-angular): allow control of Vite-based development server prebundling

---

packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build-assets_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts

Prior to this commit, the Vite html fallback middleware failed to handle the in-memory assets generated by Angular CLI, resulting in incorrect fallback behavior. For instance, when an `index.html` existed as an asset under a specific path, the generated `index.html` would be served instead.
This fix addresses the issue, ensuring that the appropriate `.html` is served when using the Vite dev-server.
Closes #27044

fix(@angular-devkit/build-angular): ensure correct `.html` served with Vite dev-server

---

goldens/public-api/angular_devkit/build_angular/index.md
packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/builders/application/schema.json
packages/angular_devkit/build_angular/src/builders/application/tests/options/define_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts

The `application` builder now supports a new option named `define`. This option allows global identifiers present in the code to be replaced with another value at build time. This is similar to the behavior of Webpack's `DefinePlugin` which was previously used with some custom Webpack configurations that used third-party builders. The option has similar capabilities to the `esbuild` option of the same name. The documentation for that option can be found here: https://esbuild.github.io/api/#define 
The command line capabilities of the Angular CLI option are not yet implemented and will added in a future change.
The option within the `angular.json` configuration file is of the form of an object. The keys of the object represent the global identifier to replace and the values of the object …

feat(@angular-devkit/build-angular): add define build option to application builder

---

CHANGELOG.md

Cherry-picks the changelog from the "17.1.x" branch to the next branch (main).

docs: release notes for the v17.1.3 release

---

CHANGELOG.md
package.json

Also this PR cherry-picks the changelog for v17.2.0-rc.0 into the main branch so that the changelog is up to date.

Update next branch to reflect new release-train "v17.3.0-next.0".

---

packages/angular_devkit/schematics/tasks/package-manager/executor.ts

Fixes an issue that causes `Unknown package manager "bun".` is thrown when running `NodePackageTask` executor

fix(@angular-devkit/schematics): add `bun` to known package managers

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

To avoid the Vite-based development server's prebundling system from attempting to prebundle import statements containing absolute URLs, the set of external specifiers will now be pre-filtered before being passed onto Vite. Currently, the check for an absolute URL is any specifier starting with `http://`, `https://`, or `//`.
Closes #27068

fix(@angular-devkit/build-angular): bypass Vite prebundling for absolute URL imports

---

packages/schematics/angular/private/standalone.ts
packages/schematics/angular/utility/standalone/code_block.ts

There were several typos in the comments for the Angular schematics utilities.

refactor(@schematics/angular): correct several comment typos

---

packages/angular_devkit/build_angular/package.json
renovate.json
yarn.lock

The `copy-webpack-plugin@12` package has a dependency on the `globby@14` package. The recently released `globby@14.0.1` uses the `merge-streams@2.1.0` package which requires a minimum Node.js version higher than the officially supported 18.13 for the Angular CLI. Due to both `globby` and `merge-streams` being transitive dependencies in end-user projects, the Angular CLI cannot directly control the package versions. However, `copy-webpack-plugin@11` uses `globby@13` which is not affected by the Node.js version problem. To workaround the Node.js compatibility problem, `copy-webpack-plugin` has been downgraded to version 11.0.0 which is the latest version in the 11 major for the package. The `copy-webpack-plugin` is only used with the Webpack-based builders when in watch mode. From a review …

fix(@angular-devkit/build-angular): downgrade copy-webpack-plugin to workaround Node.js support issue

---

packages/angular_devkit/build_angular/src/utils/postcss-configuration.ts

In certain cases, the plugin option may be a string value, as shown in the example below:
```json
{
"plugins": {
"tailwindcss/nesting": "postcss-nesting"
}
}
```
See: https://tailwindcss.com/docs/using-with-preprocessors#nesting

fix(@angular-devkit/build-angular): support string as plugin option in custom postcss plugin config

---

CHANGELOG.md

Cherry-picks the changelog from the "17.2.x" branch to the next branch (main).

docs: release notes for the v17.2.0 release

---

packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts

The sourcemap for the Vite client code was previously not being loaded along with the actual code. This could lead to browser 404 console messages when debugging applications.
closes #27136

fix(@angular-devkit/build-angular): provide Vite client code source map when loading

---

CHANGELOG.md

Cherry-picks the changelog from the "17.2.x" branch to the next branch (main).

docs: release notes for the v17.2.1 release

---

packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-global_styles_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/load-result-cache.ts

This fixes a logic error wherein some stylesheets could potentially not be rebuilt if a shared import was edited and triggered an application rebuild.
Closes #27148

fix(@angular-devkit/build-angular): ensure all related stylesheets are rebuilt when an import changes

---

tests/legacy-cli/e2e/tests/misc/safari-15-class-properties.ts

Recent babel downlevelling changes for private properties require adjustments to the test expectations for the `misc/safari-15-class-properties` E2E test. This E2E test ensured that private class properties are downlevelled when Safari 15 is present in the supported browsers list to workaround Safari bugs that were present in these older versions of the browser.

test: update Safari 15 private property E2E for babel changes

---

CHANGELOG.md

Cherry-picks the changelog from the "17.2.x" branch to the next branch (main).

docs: release notes for the v17.2.2 release

---

packages/angular_devkit/build_angular/src/builders/app-shell/index.ts
packages/angular_devkit/build_angular/src/builders/prerender/index.ts
packages/angular_devkit/build_angular/src/tools/esbuild/angular/compilation/parallel-compilation.ts
packages/angular_devkit/build_angular/src/tools/esbuild/i18n-inliner.ts
packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer.ts
packages/angular_devkit/build_angular/src/tools/webpack/plugins/javascript-optimizer-plugin.ts
packages/angular_devkit/build_angular/src/utils/action-executor.ts
packages/angular_devkit/build_angular/src/utils/server-rendering/prerender.ts

The latest version of the worker pool package used by the build system (`Piscina`) now has an option to disable performance timing information. Since the build system does not currently use that information, disabling it avoids the extra overhead of histogram creation and usage. This information collection could potentially be enabled conditionally in the future if needed.

refactor(@angular-devkit/build-angular): disable Piscina timing information recording

---

packages/angular_devkit/build_angular/src/builders/application/tests/options/output-path_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts

The logic to detect media output files was previously predicated on the presence of a media subdirectory being defined. Prior to the ability to customize output path subcomponents there was a guaranteed media subdirectory. However, now that customization is possible, there is the potential for media files to not have a distinct subdirectory in the output. To facilitate output media detection in this scenario a file extension based method is now employed. This avoids a dependence on output directory structure.
Closes #27166

fix(@angular-devkit/build-angular): avoid marking component styles as media with no output media directory

---

goldens/public-api/angular_devkit/build_angular/index.md
packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/builders/application/schema.json
packages/angular_devkit/build_angular/src/builders/application/tests/options/deploy-url_spec.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/schema.json
packages/angular_devkit/build_angular/src/builders/browser/schema.json
packages/angular_devkit/build_angular/src/builders/server/schema.json
packages/schematics/angular/migrations/update-17/use-application-builder.ts

This commit adds the deployUrl option ot the application builder.
Closes #26411

feat(@angular-devkit/build-angular): add `deployUrl` to application builder

---

packages/angular_devkit/build_angular/src/tools/webpack/utils/stats.ts
packages/angular_devkit/build_angular/src/utils/color.ts

The Node.js `node:util` builtin contains a helper (`stripVTControlCharacters`) that can be used to remove ANSI color characters from a string. Usage removes the need for a custom helper within the package.

refactor(@angular-devkit/build-angular): use Node.js builtin instead of custom removeColor helper

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

`optimizeDeps.disabled` has been deprecated in favor of `optimizeDeps.noDiscovery` to `true` and `optimizeDeps.include` to `undefined`
```
(!) Experimental ssr.optimizeDeps.disabled and deps pre-bundling during build were removed in Vite 5.1.
To disable the deps optimizer, set ssr.optimizeDeps.noDiscovery to true and ssr.optimizeDeps.include as undefined or empty.
Please remove ssr.optimizeDeps.disabled from your config.
```

refactor(@angular-devkit/build-angular): remove vite deprecation warning

---

packages/schematics/angular/migrations/update-17/css-import-lexer.ts
packages/schematics/angular/migrations/update-17/use-application-builder.ts
packages/schematics/angular/migrations/update-17/use-application-builder_spec.ts

When using the newly introduced migration to convert an application to use the new
esbuild-based `application` builder, CSS and Sass stylesheet will now have any import
and/or use specifiers adjusted to remove any Webpack builder specific prefixes. This includes
both the tilde and caret. Tilde usage is fully removed as package resolution is natively
supported. The caret is also removed and for each such specifier an external dependencies
entry is added to maintain existing behavior of keep the specifier unchanged.
Further, if any Sass imports are detected that assumed a workspace root path as a relative import
location then an entry is added to the `includePaths` array within the `stylePreprocessorOptions`
build option. This allows these import specifiers to continue to function.

Update CSS/Sass import/use specifiers in application migration

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

Prior to this commit, the deployUrl was incorrectly being set when using vite dev-server.

fix(@angular-devkit/build-angular): disable `deployUrl` when using vite dev-server

---

packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
packages/angular_devkit/build_angular/src/tools/esbuild/global-styles.ts

Only the injected index HTML file references and component stylesheets require the modification of relative URLs with a public path when specified. Other usages are already resolved relative to their containing file location with the `application` builder.

refactor(@angular-devkit/build-angular): remove unneeded relative URL modification for public path

---

packages/angular/pwa/package.json
packages/angular/ssr/package.json
packages/angular_devkit/build_angular/package.json
packages/ngtools/webpack/package.json
packages/schematics/angular/utility/latest-versions.ts
packages/schematics/angular/utility/latest-versions/package.json

The prerelease checks are failing due to incorrect dependencies
```
Discovered errors when validating dependency ranges.
- @angular/pwa: Unexpected peer dependency range for "@angular/cli". Expected: ^17.0.0 || ^17.3.0-next.0
- @angular/ssr: Unexpected peer dependency range for "@angular/common". Expected: ^17.0.0 || ^17.3.0-next.0
- @angular/ssr: Unexpected peer dependency range for "@angular/core". Expected: ^17.0.0 || ^17.3.0-next.0
- @angular-devkit/build-angular: Unexpected peer dependency range for "@angular/compiler-cli". Expected: ^17.0.0 || ^17.3.0-next.0
- @angular-devkit/build-angular: Unexpected peer dependency range for "@angular/localize". Expected: ^17.0.0 || ^17.3.0-next.0
- @angular-devkit/build-angular: Unexpected peer dependency range for "@angular/platform-server". …
```

build: update dependencies for version 17.3.0

---

CHANGELOG.md
package.json

Also this PR cherry-picks the changelog for v17.3.0-rc.0 into the main branch so that the changelog is up to date.

Update next branch to reflect new release-train "v17.4.0-next.0".

---

scripts/build.ts

Previously, the `@angular/core` package which was being built was used during the build process. This package was only used for logging and has now been replaced with the Console instead. This prevents potential logging issues if there are bugs or errors within the package being built.

build: remove usage of built package from build script

---

tsconfig.json

The use of wildcard entries with the tsconfig `paths` allows the root import of the `@angular-devkit/` packages to be reduced to a single entry.

build: reduce amount of dev tsconfig paths entries

---

packages/angular_devkit/build_angular/src/builders/application/build-action.ts
packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/builders/application/index.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-execution-result.ts
packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts

Previously, a race condition could occur due to the spinner, resulting in the deletion of the last printed log when warnings or errors were present. With this update, we ensure that logs are printed after the spinner has stopped.
Fixes #27233

fix(@angular-devkit/build-angular): ensure proper display of build logs in the presence of warnings or errors

---

packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/disable-host-check_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/public-host_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

This commit adds warnings when using unsupported dev-server options with vite.

refactor(@angular-devkit/build-angular): add warnings for unsupported vite options

---

packages/angular_devkit/build_angular/src/utils/i18n-options.ts

The `i18n` project field is used to configure i18n behavior for a project. The validation code has been reorganized to use two helper functions to centralize the type validation and exception throwing. This reduces the complexity of the analysis code as well as removing the need to rely on `@angular-devkit/core`.

refactor(@angular-devkit/build-angular): improve i18n project option validation

---

packages/angular_devkit/build_angular/src/builders/application/build-action.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts
packages/angular_devkit/build_angular/src/utils/normalize-asset-patterns.ts
packages/angular_devkit/build_angular/src/utils/normalize-file-replacements.ts
packages/angular_devkit/build_angular/src/utils/supported-browsers.ts
packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts

Logging types are now based on the BuilderContext's type instead of the `@angular-devkit/core` type. This reduces the need to directly depend on this package while also allowing the builder logging type to diverge if needed.

refactor(@angular-devkit/build-angular): reduce usage of @angular-devkit/core types

---

packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel

In an earlier commit TypeScript was updated to stable, but not the vendored version.

build: update vendored TypeScript to final

---

package.json
packages/angular_devkit/build_angular/package.json
renovate.json
yarn.lock

Also removes `less-loader` from the renovate update ignore list. The transitive dependency licensing issue has been resolved upstream.

build: update less-loader to v12.2.0

---

packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts

This improves the error message when the server entry-point is required but missing
Closes #27251

fix(@angular-devkit/build-angular): provide better error message when server option is required but missing

---

packages/angular_devkit/build_angular/src/utils/server-rendering/load-esm-from-memory.ts
packages/angular_devkit/build_angular/src/utils/server-rendering/render-page.ts
packages/angular_devkit/build_angular/src/utils/server-rendering/render-worker.ts
packages/angular_devkit/build_angular/src/utils/server-rendering/routes-extractor-worker.ts

Currently, errors occurring in ESM loader hooks while using `--import` are not correctly displayed, as they cannot be transferred from the worker to the main thread. Although the error is an instance of Error, it contains non-transferable properties and cannot be transmitted from a worker when --import is used. Consequently, when read outside of the worker, the error object displays as `[Object object]`. To address this issue, we reconstruct the error message.
See: https://github.com/angular/angular-cli/issues/27251

refactor(@angular-devkit/build-angular): properly display errors originating in ESM loader hooks

---

scripts/build-packages-dist.mts

The main release build script now has the infrastructure needed to build using the `local` bazel configuration. This is not yet used within the build process but provides the base infrastructure to support local builds of the packages in the future. `local` builds are package builds that contain file path dependencies to the other built package archives in the workspace and are used for local development and testing purposes only.

build: add infrastructure to build local-variant package outputs to main build script

---

scripts/validate-build-files.ts
scripts/validate.ts

The helpers are unneeded and behavior can be reproduced with direct string usage.  Also, this removes a runtime dependency on the packages being validated.

build: remove template string helpers from validation scripts

---

packages/schematics/angular/workspace/files/tsconfig.json.template

The `bundler` TypeScript resolution mode is now the default for all newly created Angular CLI projects. This mode allows TypeScript to read and use any package.json `exports` and `imports` fields found within packages including the Angular workspace. Unlike the `node16` option value, this value does not require the use of file extensions for each import and does not require modification of all existing application code to use. The TypeScript language service also benefits from this option by allowing import auto-discovery to leverage any `exports` defined for a package. This is particularly useful for packages such as `@angular/material` which makes extensive use of secondary package exports.
Additional information regarding this resolution mode can be found here: …

feat(@schematics/angular): use TypeScript bundler module resolution for new projects

---

docs/process/release.md
packages/angular/ssr/package.json

Missed this in the previous PR.

build: bump `@angular/ssr` framework versions

---

CHANGELOG.md

docs: release notes for the v17.3.0 release

---

packages/schematics/angular/workspace/files/tsconfig.json.template
tests/legacy-cli/e2e/assets/15.0-project/tsconfig.json
tests/legacy-cli/e2e/assets/17-ssr-project-webpack/tsconfig.json

This option is enabled by default and hence it does not need to be specified.
See: https://www.typescriptlang.org/tsconfig#forceConsistentCasingInFileNames

refactor: remove `forceConsistentCasingInFileNames` from tsconfig files

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts

In this commit, we've optimized the build performance for applications containing a large number of components when using the esbuild-based builder. This optimization entails replacing the spread operator with `Object.assign` when appending to the result metadata in the Angular compiler plugin to avoid creating multiple copies of the object.
See: https://bugs.chromium.org/p/v8/issues/detail?id=11536
**Previous Performance**:
- Initial compilation: 37 seconds
- First incremental build: 20 seconds
- Second incremental build: 16 seconds
**Updated Performance**:
- Initial compilation: 24 seconds
- First incremental build: 6 seconds
- Second incremental build: 2 seconds
Closes #27280

perf(@angular-devkit/build-angular): reduce build times for apps with  a large number of components when utilizing esbuild-based builders

---

goldens/public-api/angular_devkit/schematics/tasks/index.md
packages/angular_devkit/schematics/tasks/package-manager/link-task.ts
packages/schematics/angular/ng-new/index.ts
packages/schematics/angular/ng-new/schema.json

`yarn ng-dev misc build-and-link <path-to-local-project-root>` should be used instead.

refactor(@schematics/angular): remove internal `linkCli` ng-new option

---

scripts/snapshots.mts

This should fix the snpashot publishing which are currently being skipped.
```
Skipping @angular/cli.
Skipping @angular/create.
Skipping @angular/pwa.
Skipping @angular/ssr.
Skipping @angular-devkit/architect.
Skipping @angular-devkit/architect-cli.
Skipping @angular-devkit/build-angular.
Skipping @angular-devkit/build-webpack.
Skipping @angular-devkit/core.
Skipping @angular-devkit/schematics.
Skipping @angular-devkit/schematics-cli.
Skipping @ngtools/webpack.
Skipping @schematics/angular.
```

build: address issue with snapshot publishing due to non existing property

---

scripts/snapshots.mts

This should fix the snpashot publishing which are currently being skipped.
```
Skipping @angular/cli.
Skipping @angular/create.
Skipping @angular/pwa.
Skipping @angular/ssr.
Skipping @angular-devkit/architect.
Skipping @angular-devkit/architect-cli.
Skipping @angular-devkit/build-angular.
Skipping @angular-devkit/build-webpack.
Skipping @angular-devkit/core.
Skipping @angular-devkit/schematics.
Skipping @angular-devkit/schematics-cli.
Skipping @ngtools/webpack.
Skipping @schematics/angular.
```

build: address issue with snapshot publishing due incorrect property access

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/angular-host.ts

A stylesheet for a component that is empty or contains only whitespace will no longer be transformed and bundled during a build. Transforming the stylesheet was unnecessary work as an empty string would be returned as a result. While this may not be common in applications, it is a possibility. Both file and inline component stylesheets are affected by this change.

perf(@angular-devkit/build-angular): avoid transforming empty component stylesheets

---

packages/angular/cli/src/command-builder/utilities/schematic-workflow.ts
packages/angular/cli/src/commands/add/cli.ts
packages/angular/cli/src/commands/update/schematic/index.ts

Direct string usage can be leveraged to remove the need for the helpers and reduce imports of `@angular-devkit/core`.

refactor(@angular/cli): remove unneeded devkit core tag helper usage

---

packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts

The warning mentions `allowedHost` instead of `allowedHosts`.
Warning is fixed

fix(@angular-devkit/build-angular): typo in allowedHosts warning for unsupported vite options

---

packages/angular_devkit/build_angular/src/builders/application/build-action.ts
packages/angular_devkit/build_angular/src/builders/application/tests/options/ssr_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts

Previously, the `server` directory was erroneously generated even in instances where SSG was enabled but SSR remained inactive.

fix(@angular-devkit/build-angular): only generate `server` directory when SSR is  enabled

---

packages/schematics/angular/application/schema.json

The labels of the Sass preprocessor stylesheet option values have been updated for the `application` schematic's `style` option. The labels now provide greater clarity regarding the preprocessor tool used for both the SCSS (more common) and indented Sass syntaxes.
The new list selection prompt is now as follows:
```
? Which stylesheet format would you like to use? (Use arrow keys)
❯ CSS             [ https://developer.mozilla.org/docs/Web/CSS                     ]
Sass (SCSS)     [ https://sass-lang.com/documentation/syntax#scss                ]
Sass (Indented) [ https://sass-lang.com/documentation/syntax#the-indented-syntax ]
Less            [ http://lesscss.org                                             ]
```

fix(@schematics/angular): improve Sass format clarity for application style option

---

CHANGELOG.md

docs: release notes for the v17.3.1 release

---

scripts/build.mts
scripts/create.mts
scripts/devkit-admin.mts

This update addresses an issue where an older version of the CLI tarball was mistakenly employed in creating a new application via `yarn admin create`.
Additionally, `yarn admin create` now accommodates extra options that can be utilized with `ng new`.
Example:
```
yarn admin create my-app --ssr
```

build: a couple of tweaks and fixes to `yarn admin create`.

---

packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts

When using a non-localhost IP, Vite will correctly populate the `network` property of the `server.resolvedUrls` instead of `local`.
Example:
```
ng server --host=127.0.0.2
{ local: [], network: [ 'http://127.0.0.2:4200/' ] }
```
Closes #27327

fix(@angular-devkit/build-angular): `Internal server error: Invalid URL` when using a non localhost IP

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

Addressed in this commit is an update to `webpack-dev-middleware` to version `6.1.2`, resolving a security concern identified at https://github.com/advisories/GHSA-wr3j-pwj9-hqq6.
Closes #27334

fix(@angular-devkit/build-angular): update `webpack-dev-middleware` to `6.1.2`

---

packages/angular_devkit/build_angular/src/builders/ssr-dev-server/index.ts
packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/proxy_spec.ts
packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/ssl_spec.ts
packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/works_spec.ts
packages/schematics/angular/migrations/update-17/replace-nguniversal-engines.ts
packages/schematics/angular/migrations/update-17/replace-nguniversal-engines_spec.ts
packages/schematics/angular/ssr/files/application-builder/server.ts.template
packages/schematics/angular/ssr/files/server-builder/server.ts.template
tests/legacy-cli/e2e/assets/18-ssr-project-webpack/server.ts

Rename SSR port env variable to SSR_PORT.
Rename the SSR port env variable to SSR_PORT.
It could help to resolve this firebase issue: https://github.com/firebase/firebase-tools/issues/6651#issuecomment-1881647322, cause PORT is reserved environment variable: https://firebase.google.com/docs/functions/config-env?gen=2nd#reserved-names.

fix(@schematics/angular): rename SSR port env variable

---

packages/angular_devkit/build_angular/src/tools/babel/plugins/index.ts
packages/angular_devkit/build_angular/src/tools/esbuild/javascript-transformer-worker.ts

The linker and build optimizer related babel plugins are now directly imported when needed within the JavaScript transformer worker code. This lowers the number of transitive modules that must be loaded for each worker instance. It also removes the use of `require` from the initialization code which provides support for full ESM output in the future.

refactor(@angular-devkit/build-angular): directly configure internal babel plugins for application builder

---

packages/angular_devkit/build_angular/src/builders/application/execute-post-bundle.ts
packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/builders/application/tests/options/service-worker_spec.ts
packages/angular_devkit/build_angular/src/utils/service-worker.ts

This commit addresses an issue where the service worker incorrectly referenced a non-existent `index.html` when utilizing the output index option. Additionally, it ensures proper resolution of the service worker configuration when the option value is set to `true`.

fix(@angular-devkit/build-angular): service-worker references non-existent named index output

---

packages/angular_devkit/build_angular/src/tools/sass/rebasing-importer.ts

This commit addresses a bug where SCSS files within linked directories were not being resolved correctly by the Angular CLI. By implementing the necessary adjustments, linked SCSS files are now properly resolved.
Closes #27353

fix(@angular-devkit/build-angular): ensure proper resolution of linked SCSS files

---

CHANGELOG.md

docs: release notes for the v15.2.11 release

---

CHANGELOG.md

docs: release notes for the v16.2.13 release

---

packages/schematics/angular/utility/latest-versions.ts
packages/schematics/angular/utility/latest-versions/package.json
scripts/release-checks/dependency-ranges/latest-versions-check.mts

Previously, the release process encountered an error due to ts-node's inability to transform `packages/schematics/angular/utility/latest-versions.ts`, resulting in the following error:
```
export const latestVersions: Record<string, string> & {
^^^^^^
SyntaxError: Unexpected token 'export'
at internalCompileFunction (node:internal/vm:73:18)
at wrapSafe (node:internal/modules/cjs/loader:1274:20)
at Module._compile (node:internal/modules/cjs/loader:1320:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
at Module.load (node:internal/modules/cjs/loader:1197:32)
at Module._load (node:internal/modules/cjs/loader:1013:12)
at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:202:29)
at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
at async …
```

build: address pre-release validation failure

---

packages/angular_devkit/build_angular/src/tools/babel/presets/application.ts

The babel application preset that is used with the Webpack-based build system now also uses the updated location for the build optimizer plugins. This also reduces the amount of require statements in the setup function for the preset.

refactor(@angular-devkit/build-angular): update babel application preset with new plugin import location

---

packages/angular_devkit/build_angular/package.json
packages/ngtools/webpack/package.json
tests/legacy-cli/e2e/assets/18-ssr-project-webpack/package.json

In https://github.com/angular/angular/pull/54961 the Angular compiler stopped supporting TypeScript versions older than 5.4. These changes narrow down the range for Tooling.

build: narrow down supported TypeScript versions

---

packages/angular_devkit/build_angular/src/utils/normalize-cache.ts

The build process will automatically perform package version placeholder replacement within source files. This allows for the package version to be injected into the build cache path creation process as a constant. As the version is now a constant, there is no need to attempt runtime loading of the package metadata to retrieve the package version.

refactor(@angular-devkit/build-angular): use build version stamping for build cache path creation

---

packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts

Since the calculated cache path already contains the `@angular-devkit/build-angular` package version, the version is not needed within the cache key for each font URL. This removes the need to import the loaded version from the `package.json` in the font inline logic.

refactor(@angular-devkit/build-angular): remove unneeded package version from inline font cache key

---

packages/schematics/angular/application/files/module-files/src/main.ts.template
packages/schematics/angular/application/files/standalone-files/src/app/app.config.ts.template
packages/schematics/angular/application/index_spec.ts
packages/schematics/angular/server/index_spec.ts
packages/schematics/angular/service-worker/index_spec.ts
packages/schematics/angular/utility/standalone/rules_spec.ts

This commit enables eventCoalescing by default for standalone applications.

feat(@schematics/angular): use zone eventCoalescing by default

---

packages/schematics/angular/application/files/standalone-files/src/app/app.config.ts.template
packages/schematics/angular/application/index_spec.ts
packages/schematics/angular/utility/standalone/rules_spec.ts

The usual coding style in the generated application is to have spaces in objects (see `server.ts.template` for example).
The new introduced `eventCoaslecing` option doesn't.

fix(@schematics/angular): add spaces around eventCoalescing option

---

packages/angular_devkit/build_angular/src/builders/ssr-dev-server/index.ts
packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/proxy_spec.ts
packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/ssl_spec.ts
packages/angular_devkit/build_angular/src/builders/ssr-dev-server/specs/works_spec.ts
packages/schematics/angular/migrations/update-17/replace-nguniversal-engines.ts
packages/schematics/angular/migrations/update-17/replace-nguniversal-engines_spec.ts
packages/schematics/angular/ssr/files/application-builder/server.ts.template
packages/schematics/angular/ssr/files/server-builder/server.ts.template
tests/legacy-cli/e2e/assets/18-ssr-project-webpack/server.ts

Reverts angular/angular-cli#27333 following a recommendation by firebase. We will work on an alternate solution.

Revert "fix(@schematics/angular): rename SSR port env variable"

---

CHANGELOG.md

docs: release notes for the v17.3.3 release

---

renovate.json

This commit disabled auto updating of `build_bazel_rules_nodejs` since this requires the new version of rulesjs

ci: disable updating `build_bazel_rules_nodejs`

---

packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts

Previously, there were instances where the ESbuilder might incorrectly generate CJS code, leading to runtime errors.
Fixes #27421

fix(@angular-devkit/build-angular): ensure esbuild-based builders exclusively produce ESM output

---

packages/angular_devkit/architect/node/node-modules-architect-host.ts
packages/angular_devkit/architect/src/builders-schema.json

A builder's manifest definition within a package (typically `builders.json`) can now contain a string value that will be used as a builder specifier when loading the named builder. This allows a builder name to be aliased to another builder. The other builder may also be in another package.
The build resolution logic has also been updated to remove use of the global `require` to support eventual direct ESM usage.

refactor(@angular-devkit/architect): allow aliasing builder names in package builder manifest

---

packages/angular/cli/src/commands/completion/long-description.md

Working url: https://angular.dev/assets/images/guide/cli/completion.gif

docs: fix image url for completion command

---

packages/angular_devkit/build_angular/src/builders/application/options.ts
packages/angular_devkit/build_angular/src/builders/application/tests/behavior/index-preload-hints_spec.ts
packages/angular_devkit/build_angular/src/builders/application/tests/behavior/rebuild-errors_spec.ts
packages/angular_devkit/build_angular/src/builders/application/tests/options/index_spec.ts
packages/schematics/angular/ssr/files/application-builder/server.ts.template

BREAKING CHANGE: By default, the index.html file is no longer emitted in the browser directory when using the application builder with SSR. Instead, an index.csr.html file is emitted. This change is implemented because in many cases server and cloud providers incorrectly treat the index.html file as a statically generated page. If you still require the old behavior, you can use the `index` option to specify the `output` file name.
```json
"architect": {
"build": {
"builder": "@angular-devkit/build-angular:application",
"options": {
"outputPath": "dist/my-app",
"index": {
"input": "src/index.html",
"output": "index.html"
}
}
}
}
```

fix(@angular-devkit/build-angular): do not generate an `index.html` file in the browser directory when using SSR.

---

packages/angular_devkit/build_angular/src/builders/application/execute-build.ts
packages/angular_devkit/build_angular/src/utils/resolve-assets.ts

Instead of previously attempting to reuse the Webpack-based copy assets helper function, the application builder will now only resolve all potential configured assets. This avoids depending on non-obvious parameter behavior to prevent the actual copying of the asset files.

refactor(@angular-devkit/build-angular): directly resolve asset files in application builder

---

CHANGELOG.md

docs: release notes for the v16.2.14 release

---

CHANGELOG.md

docs: release notes for the v17.3.4 release

---

packages/angular_devkit/build_angular/src/builders/browser/index.ts
packages/angular_devkit/build_angular/src/builders/dev-server/webpack-server.ts
packages/angular_devkit/build_angular/src/builders/server/index.ts
packages/angular_devkit/build_angular/src/utils/action-executor.ts
packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts
packages/angular_devkit/build_angular/src/utils/i18n-options.ts
packages/angular_devkit/build_angular/src/utils/i18n-webpack.ts
packages/angular_devkit/build_angular/src/utils/output-paths.ts
packages/angular_devkit/build_angular/src/utils/process-bundle.ts
packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts

The i18n option creation for a project, which is a combination of the `i18n` project field and the `localize` build option, is now in a separate file from the Webpack specific i18n configuration setup. This allows the i18n option creation to be used without loading anything Webpack specific.

refactor(@angular-devkit/build-angular): split Webpack-specific functionality from i18n option creation

---

packages/angular_devkit/build_angular/src/builders/application/tests/behavior/stylesheet-url-resolution_spec.ts
packages/angular_devkit/build_angular/src/tools/esbuild/stylesheets/css-resource-plugin.ts
packages/angular_devkit/build_angular/src/tools/sass/rebasing-importer.ts

This commit introduces enhancements to the Sass rebasing importer, enabling it to resolve resources whose paths are stored in variables or namespaced variables. Also this addresses an issue where URL paths in Sass and SCSS files, flagged as external, were incorrectly rebased, leading to resolution errors.
Closes #27445 and closes #27007

feat(@angular-devkit/build-angular): enhance Sass rebasing importer for resources URL defined in variables and handling of external paths

---

packages/angular_devkit/build_angular/src/tools/webpack/plugins/any-component-style-budget-checker.ts
packages/angular_devkit/build_angular/src/utils/bundle-calculator.ts
packages/angular_devkit/build_angular/src/utils/bundle-calculator_spec.ts

Webpack-specific types and imports have been reduced within the logic and test code for the bundle budget calculator. This reduces the amount of unused code that needs to be loaded when not using a Webpack-based bundler. The Webpack component style budget plugin was also updated to use only the `checkBudgets` function instead of the previous two function setup which limits the needed amount of runtime exports for the plugin.

refactor(@angular-devkit/build-angular): reduce Webpack specific overlap in bundle budget calculator

---

packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

The above mentioned API is deprecated.

refactor: replace vite `server.ws.send` usages

---

packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts

`type="text/css"` is deprecated, for more info see: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#deprecated_attributes
Closes: #27471

fix(@angular-devkit/build-angular): remove `type="text/css"` from `style` tag

---

CHANGELOG.md

docs: release notes for the v17.3.5 release

---

packages/angular_devkit/build_angular/src/builders/application/tests/behavior/browser-support_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts
packages/angular_devkit/build_angular/src/tools/esbuild/utils.ts

This commit updates the esbuild based builders to emit native async/await when `zone.js` is not added as a polyfill.
Closes #22191

feat(@angular-devkit/build-angular): support native async/await when app is zoneless

---

scripts/create.mts

The admin create script previously only updated the package.json dependencies for direct dependencies. This did not ensure that all built packages were used due to some built packages being used as transitive dependencies. The npm `overrides` field is now also used to ensure that these dependencies are also properly redirected to the built packages.

build: adjust create project script to ensure all built packages are used

---

goldens/public-api/angular_devkit/build_angular/index.md
packages/angular_devkit/build_angular/BUILD.bazel
packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
packages/angular_devkit/build_angular/src/builders/dev-server/index.ts
packages/angular_devkit/build_angular/src/builders/dev-server/internal.ts
packages/angular_devkit/build_angular/src/builders/dev-server/output.ts
packages/angular_devkit/build_angular/src/builders/dev-server/specs/works_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts

**refactor(@angular-devkit/build-angular): move Vite dev-server @angular/build imports into separate file**
To reduce the complexity of the move of the Vite-based dev-server builder
into the `@angular/build` package. The soon to be self-referencing imports
are now located in a separate file. Self-referencing imports are not well
supported inside the repository currently so this move allows the imports
to be adjusted in one location.
**refactor(@angular-devkit/build-angular): remove Webpack-specific index option helper from Vite-based dev-server**
The index output option helper from within the Webpack-based build system has been removed
from the Vite-based development server code to support separation of the builder. This
information will eventually be passed via the build system results …

Several Vite-based development server internal refactoring changes

---

goldens/public-api/angular/build/index.md
packages/angular/build/BUILD.bazel
packages/angular/build/builders.json
packages/angular/build/src/builders/extract-i18n/application-extraction.ts
packages/angular/build/src/builders/extract-i18n/builder.ts
packages/angular/build/src/builders/extract-i18n/index.ts
packages/angular/build/src/builders/extract-i18n/options.ts
packages/angular/build/src/builders/extract-i18n/schema.json
packages/angular/build/src/index.ts
packages/angular/cli/BUILD.bazel
packages/angular/cli/lib/config/workspace-schema.json

With the `application` builder already within the new `@angular/build` package, the `extract-i18n` builder with application builder support is now also contained within this package. Only the application builder aspects of `extract-i18n` have been moved. The compatibility builder `browser-esbuild` is not supported with `@angular/build:extract-i18n`. The existing `extract-i18n` builder found within `@angular-devkit/build-angular` should continue to be used for both the Webpack-based `browser` builder and the esbuild-based compatibility `browser-esbuild` builder. To maintain backwards compatibility, the existing `@angular-devkit/build-angular:extract-i18n` builder continues to support builders it has previously.
No change to existing applications is required.

feat(@angular-devkit/build-angular): move i18n extraction for application builder to new build system package

---

packages/schematics/angular/migrations/use-application-builder/migration.ts

When using the optional application build system migration, the newly
introduced `@angular/build` package which contains only the new build
system and no Webpack-related dependencies will be directly used when
possible. The migration will check for usage of any other builders from
the `@angular-devkit/build-angular` package. if none are present in the
`angular.json` file (excluding `dev-server` and `extract-i18n`), the
`@angular/build` package will be added as a dependency and used in the
`angular.json` file. The `@angular-devkit/build-angular` package will
then be removed as a dependency. Project usage of karma and/or protractor
will be the most common reasons this part of the migration will not be
performed.
Also includes a fix to the migration to no longer remove the now support …

feat(@schematics/angular): allow application migration to use new build package in projects where possible

---

packages/angular/build/package.json
packages/angular/build/src/tools/esbuild/stylesheets/less-language.ts

The Less stylesheet preprocessor is now an optional peer dependency of the newly introduced `@angular/build` build system package. Less stylesheet usage is currently estimated at less than 10% of projects with analytics enabled. Less stylesheets are still fully supported but usage will now require installing the `less` package within the Angular workspace. An error with instructions to install the package will be generated during a build if the package is not present. This change only affects direct usage of the new `@angular/build` package. The `@angular-devkit/build-angular` package which is currently used for all existing projects will continue to contain and directly depend on the `less` package.
No changes are required for existing applications.

refactor(@angular/build): move less stylesheet preprocessor to an optional peer dependency

---

packages/angular/build/src/utils/index-file/augment-index-html.ts
packages/angular/build/src/utils/index-file/augment-index-html_spec.ts

When an invalid self-closing HTML element is used in the index.html file, the build proceeds without raising an error, potentially leading to runtime issues.
Now, when an invalid self-closing element is encountered in the index.html file, the build process issues an error, providing developers with immediate feedback to correct the issue.
Closes: #27528

fix(@angular/build): emit error for invalid self-closing element in index HTML

---

tests/legacy-cli/e2e/tests/vite/ssr-error-stack.ts

With Node.js 22 on Windows the stack traces may contain paths that have double backslash path segment separators.

test: update regexp in ssr-error-stack E2E test for Node.js 22 on Windows

---

docs/process/release.md

Refs https://github.com/angular/dev-infra/issues/744
CC @josephperrott

docs: add explanation of how to set up a new NPM package in Wombat

---

CHANGELOG.md

docs: release notes for the v17.3.6 release

---

packages/angular/build/src/utils/version.ts

The compatible Angular version check now supports getting the SemVer range of a compatible `@angular/compiler-cli` package from both this package and `@angular-devkit/build-angular` if present. This prevents a potential build error condition if `@angular-devkit/build-angular` is not present.

fix(@angular/build): check both potential build packages in Angular version check

---

constants.bzl
tests/legacy-cli/e2e/utils/project.ts

Currently this is not being set correctly. Ex: https://github.com/angular/angular-devkit-build-angular-builds/blob/2760127ec678d422d352d8d02ebb85e16512a478/package.json#L10

build: correctly set `@angular/build` version in snapshots

---

goldens/circular-deps/packages.json
packages/angular/build/src/builders/dev-server/options.ts
packages/angular/build/src/builders/dev-server/schema.json
packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
packages/angular_devkit/build_angular/src/builders/dev-server/options.ts

This change ensures that `ngDevMode` is replaced in node packages, aligning the behavior of the Vite server more closely with a production environment.

fix(@angular/build): disable Vite prebundling when script optimizations are enabled

---

CHANGELOG.md
package.json

The previous "next" release-train has moved into the feature-freeze phase. This PR updates the next branch to the subsequent release-train.
Also this PR cherry-picks the changelog for v18.0.0-next.5 into the main branch so that the changelog is up to date.

Update next branch to reflect new release-train "v18.1.0-next.0".

---

packages/angular/build/src/private.ts

Add several additional APIs to the private export of the package. Note that these are not considered part of the public API and are intended for use only with the `@angular-devkit/build-angular` package.

refactor(@angular/build): update private exports for additional usage

---

goldens/public-api/angular/build/index.md
packages/angular/build/src/builders/extract-i18n/schema.json
packages/angular_devkit/build_angular/src/builders/extract-i18n/schema.json
packages/schematics/angular/application/index.ts

The `extract-i18n` option schema has been updated to reflect that the
`buildTarget` option is not required. The option value will default
to the `build` target of the containing project. This removes the need
for an additional option and character count within the `angular.json`
file for the project.

I18n extract default build target

---

packages/schematics/angular/migrations/use-application-builder/migration.ts
packages/schematics/angular/migrations/use-application-builder/migration_spec.ts
packages/schematics/angular/utility/latest-versions/package.json

The application migration schematic will now attempt to detect the usage of Less stylesheets within a workspace and install the `less` dependency if required. This will only occur if the migration analysis allows for the conversion to use the `@angular/build` package instead of the `@angular-devkit/build-angular` package. The Less usage detection may not detect Less stylesheets within Node.js packages and currently does not handle the case where a project only has inline Less stylesheets. More complex analysis may be added in the future. However, a build time error message will be presented with instructions to install `less` in these cases if the stylesheet preprocessor is required and not present.

fix(@schematics/angular): add less dependency in application migration if needed

---

packages/angular/build/package.json
packages/angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts

The Postcss stylesheet processor is now an optional peer dependency of the newly introduced `@angular/build` build system package. This change removes the need for the package to have a direct dependency on the `postcss` package and allows some version customization of the optional `postcss` package if needed. Postcss plugins (including Tailwind) are still fully supported but usage will now require installing the `postcss` package within the Angular workspace. An error with instructions to install the package will be generated during a build if the package is not present. This change only affects direct usage of the new `@angular/build` package. The `@angular-devkit/build-angular` package which is currently used for all existing projects will continue to contain and directly depend on the …

refactor(@angular/build): move postcss stylesheet processor to an optional peer dependency

---

packages/angular/cli/package.json

The ng update package group list now contains the newly introduced `@angular/build` package which contains the esbuild/Vite-based build system. The group list ensures that all relevant direct project dependencies are update as group when `@angular/cli` itself is updated.

fix(@angular/cli): add `@angular/build` package to update group

---

CHANGELOG.md

docs: release notes for the v18.0.0-rc.0 release

---

packages/angular_devkit/build_angular/BUILD.bazel

When creating a local development build of the repository via `yarn build --local`, the package version for `@angular/build` within `@angular-devkit/build-angular` will now correctly be replaced with the path to the locally built archive of `@angular/build`.

build: replace `@angular/build` version with archive in local builds

---

packages/schematics/angular/migrations/use-application-builder/migration.ts
packages/schematics/angular/migrations/use-application-builder/migration_spec.ts
packages/schematics/angular/utility/latest-versions/package.json

The application migration schematic will now attempt to detect the usage of custom postcss plugins within a workspace and install the `postcss` dependency if required. This will only occur if the migration analysis allows for the conversion to use the `@angular/build` package instead of the `@angular-devkit/build-angular` package. Custom postcss configurations will be detected within the same locations as the build system itself which includes the workspace root and any project root for the `postcss.config.json` and `.postcssrc.json` files.

fix(@schematics/angular): add postcss dependency in application migration if needed

---

packages/angular_devkit/architect/node/node-modules-architect-host.ts

When resolving a builder alias, the base path for the resolution will now use the containing package. This prevents potential resolution failure due to varying package manager installation strategies.

fix(@angular-devkit/architect): resolve builder aliases from containing package

---

packages/angular/build/src/utils/server-rendering/render-page.ts
packages/angular_devkit/build_angular/src/builders/app-shell/render-worker.ts

There might be cases were currently, the render application promise does not resolve because the application never becomes stable in most cases this is due to errors, this causes the worker to never exit and the build to keep running until it's manually terminated.
With this change, we add a maximum rendering timeout of 30seconds for each page.
Closes #27565

fix(@angular/build): add a maximum rendering timeout for SSG

---

packages/angular/build/src/tools/esbuild/bundler-context.ts
packages/angular/build/src/tools/esbuild/index-html-generator.ts

To remove the potential for a large amount of modulepreload link elements being added to the generating `index.html` for an application, the number of elements is now limited to five. Also, only first-level initial scripts will be added. Previously all initial scripts regardless of depth were eligible for preloading. The preload generation can still be fully disabled via the `index.preloadInitial` option within the build options.

fix(@angular/build): only generate shallow preload links for initial files

---

CHANGELOG.md

docs: release notes for the v18.0.0-rc.1 release

---

packages/angular/build/src/utils/server-rendering/fetch-patch.ts
tests/legacy-cli/e2e/tests/build/prerender/http-requests-assets.ts

Previously, missing URL decoding led to assets not being located correctly.
Closes: #27590

fix(@angular/build): decode URL pathname decoding during SSG fetch

---

packages/angular_devkit/build_angular/src/utils/server-rendering/fetch-patch.ts
tests/legacy-cli/e2e/tests/build/prerender/http-requests-assets.ts

Previously, missing URL decoding led to assets not being located correctly.
Closes: #27590

fix(@angular-devkit/build-angular): decode URL pathname decoding during SSG fetch

---

packages/schematics/angular/workspace/files/__dot__gitignore.template

updates the broken link for `.gitignore` file
upon generating a new Angular project `.gitignore` file refers to an outdated link for docs on ignoring files.
should generate `.gitignore` file with updated link for ignoring files.

refactor(@schematics/angular): link for ignoring files

---

packages/angular/build/src/utils/bundle-calculator_spec.ts
packages/angular/build/src/utils/format-bytes.ts
packages/angular/build/src/utils/format-bytes_spec.ts
packages/schematics/angular/application/index.ts

Ensure that file sizes are consistently formatted using decimal byte units, adhering to the International System of Units (SI) convention. This aligns with clarity and standardization across the project.
- Kilobyte (kB): 10^3 bytes (1000 bytes)
- Megabyte (MB): 10^6 bytes (1,000,000 bytes)
- Gigabyte (GB): 10^9 bytes (1,000,000,000 bytes)
Closes: #27580

fix(@angular/build): format sizes using decimal byte units consistently

---

renovate.json

This commit addresses a warning in Renovate regarding a deprecated behavior that will be phased out in the future.
```
WARNING: To prevent future issues, replace the usage of matchPackagePatterns with matchDepPatterns (repository=angular/angular-cli, baseBranch=main)
"packageRule": {
"matchPackagePatterns": ["^@bazel/.*", "^build_bazel.*"],
"groupName": "bazel",
"schedule": ["at any time"]
},
"packageName": "bazelbuild/rules_nodejs",
"depName": "build_bazel_rules_nodejs"
```

ci: update Renovate configuration: replace `matchPackagePatterns` with `matchDepPatterns`

---

packages/angular/build/src/tools/sass/rebasing-importer.ts
packages/angular/build/src/tools/sass/worker.ts

When attempting to resolve a Sass import, failure to read the contents of a directory that is not caused by a non-existent directory will now cause an exception to be thrown. This prevents abnormal situations from being hidden during the build.
A deprecated Sass interface was also replaced and was a type only change.

refactor(@angular/build): show unexpected Sass import resolution errors

---

CHANGELOG.md

docs: release notes for the v17.3.7 release

---

CHANGELOG.md

docs: release notes for the v18.0.0-rc.2 release

---

packages/angular/build/src/builders/application/build-action.ts
packages/angular/build/src/builders/application/tests/behavior/rebuild-general_spec.ts

When deleting a file and then recreating a file that is again referenced in the application, the watch state will now be correctly synchronized. Previously the application builder would consider the previously deleted file as still watched which would prevent it from being watched again. This situation can happen when switching source control branches while a build is active watching.
Fixes: #27619

fix(@angular/build): ensure recreated files are watched

---

packages/angular/build/src/builders/application/tests/behavior/stylesheet-url-resolution_spec.ts
packages/angular/build/src/tools/sass/rebasing-importer.ts

Previously, the Sass url() rebasing logic was skipping values that contained leading Sass interpolations. This was because an interpolation starts with the `#` character which in CSS indicates a fragment identifier and not a path. However, Sass special cases this scenario by checking if the next character is the `{` character and considers it an interpolation if present. The Angular rebasing logic will now match this behavior.
Fixes: #27621

fix(@angular/build): properly rebase Sass url() values with leading interpolations

---

packages/angular/cli/src/commands/update/cli.ts

The instructions for when optional migrations are present within an updated package have been adjusted. A sentence has been added to mention that optional migrations can be executed after the update process if preferred and can be skipped for now.

fix(@angular/cli): clarify optional migration instructions during ng update

---

packages/angular/build/src/tools/esbuild/commonjs-checker.ts
packages/angular_devkit/build_angular/src/tools/webpack/plugins/common-js-usage-warn-plugin.ts

This replaces https://angular.io/guide/build#configuring-commonjs-dependencies with https://angular.dev/tools/cli/build#configuring-commonjs-dependencies

refactor: replace angular.io link with angular.dev

---

package.json
packages/angular/build/BUILD.bazel
packages/angular/build/package.json
packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular/build/src/tools/esbuild/lmdb-cache-store.ts
packages/angular/build/src/tools/esbuild/stylesheets/sass-language.ts
packages/angular_devkit/build_angular/src/tools/webpack/configs/styles.ts
tests/legacy-cli/e2e/tests/misc/check-postinstalls.ts
yarn.lock

When caching is enabled for the Angular CLI, the JavaScript transformer within the application build system will now perform persistent caching of its output. This allows for improved warm build times by removing the need to run the Angular linker and build optimizer steps against unchanged third-party code within each build. This does not affect hot rebuilds that would take place during watch mode since the outputs are already cached within memory. The on-disk storage of the cached data is handled by the `lmdb` package which provides fast key/value storage and built-in off-thread compression. This package is currently used by such projects as Gatsby and parcel for their respective caching subsystems.
Warm production build of a new 18.0.0-rc.2 project with disabled caching:
``` …
```

perf(@angular/build): add persistent caching of JavaScript transformations

---

packages/angular/build/src/tools/esbuild/stylesheets/css-inline-fonts-plugin.ts

This commit adds the error as part of the notes when an error occurs during font inlining.

refactor(@angular/build): add error as part of error notes

---

packages/angular/build/src/builders/dev-server/vite-server.ts
packages/angular/build/src/tools/esbuild/external-packages-plugin.ts

Rebuilds can now use the optimized external package execute path when using the `application` builder's `loader` option if only `file` type loaders are used. The Vite-based development server will now process any `file` type loader usage for third-party file references which removes the need for the build itself to handle the loader processing. This change only optimizes the case where only the `file` loader type is used. If any other loader types are present, the optimized execution path will not be used. Future further improvements may allow for all cases to use the optimized rebuild execution path.

perf(@angular/build): improve rebuild time for file loader usage with prebundling

---

packages/angular_devkit/schematics/src/rules/template.ts
packages/angular_devkit/schematics/src/tree/host-tree.ts

When using Jest `instanceof` does not work correctly. See: https://github.com/jestjs/jest/issues/2549
Closes: #27643

fix(@angular-devkit/schematics): `SchematicTestRunner.runExternalSchematic` fails with "The encoded data was not valid for encoding utf-8"

---

packages/angular_devkit/schematics/src/tree/host-tree.ts

All direct usage of rxjs has been removed from the FilterHostTree implementation. This removes the need to import rxjs within the containing file. The recursive logic has also been replaced with an iterative approach.

refactor(@angular-devkit/schematics): reduce direct rxjs usage in filter host tree

---

packages/angular/build/src/builders/dev-server/vite-server.ts

An informational note will now be shown upon development server startup to indicate that the raw file sizes shown in the console do not reflect any of the per-request transformations that may occur within the Vite-based development server. The raw file size and the size shown within the browser may differ as a result of these development workflow based transformations.

fix(@angular/build): add console note about development server raw file size

---

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts

Close and allow the persistent JS transformer cache to cleanup open lock files when the Angular compiler plugin is disposed. While this is not strictly necessary, it does help prevent extra cache lock files from being retained after build completion.

refactor(@angular/build): cleanup persistent JS transformer cache on plugin dispose

---

README.md
packages/angular/build/src/utils/version.ts
packages/angular/cli/src/commands/update/cli.ts
packages/angular/cli/src/commands/update/long-description.md
scripts/templates/readme.ejs

References to the Angular update guide now use the new angular.dev site.

fix(@angular/cli): change update guide link to angular.dev

---

packages/angular/cli/src/analytics/analytics.ts
packages/angular/cli/src/utilities/completion.ts

Instead of manually invoking an underlying prompt library, the analytics and completion commands now use the helper utility functions present to handle console prompts.

refactor(@angular/cli): use prompt helper functions in analytics and completion commands

---

packages/angular/build/src/tools/babel/plugins/adjust-static-class-members.ts
packages/angular/build/src/tools/babel/plugins/adjust-static-class-members_spec.ts

Prior to this commit, class expressions emitted by esbuild that have static blocks or properties were not being properly wrapped. This caused the class to become non-treeshakable.
Closes #27662

fix(@angular/build): correctly wrap class expressions with static properties or blocks emitted by esbuild

---

packages/angular/cli/src/command-builder/command-module.ts
packages/angular/cli/src/command-builder/command-runner.ts
packages/angular/cli/src/utilities/completion.ts
tests/legacy-cli/e2e/tests/commands/analytics/ask-analytics-command.ts
tests/legacy-cli/e2e/tests/commands/completion/completion-prompt.ts
tests/legacy-cli/e2e/tests/commands/help/help-json.ts

**fix(@angular/cli): add `--version` option**
This commit introduces the `--version` option, which will display the Angular CLI version when using `ng --version`.
Closes #27668
**fix(@angular/cli): eliminate prompts during `ng version` command**
This update removes the analytics and completion prompts that appear when executing the `ng version` command, ensuring a smoother and uninterrupted user experience.
Closes #27668

ng version updates

---

CHANGELOG.md

docs: release notes for the v18.0.0-rc.3 release

---

packages/angular/cli/src/command-builder/command-runner.ts
tests/legacy-cli/e2e/tests/commands/help/help-json.ts

The newly added `--version` option was previously added to all subcommands which can result in a warning being shown if the subcommand was a builder or schematics that also happened to have a `version` option. To support the default `--version` option that displays the actual CLI version, the option is now only added when no subcommand is present. This prevents potential version option overlap.

fix(@angular/cli): only add --version option on default command

---

CHANGELOG.md

docs: release notes for the v17.3.8 release

---

CHANGELOG.md

docs: release notes for the v18.0.0 release

---

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts

To avoid loading and initializing the underlying persistent cache store when caching is disabled, the lmdb-based cache will now only be imported when caching is enabled.

fix(@angular/build): only import persistent cache store with active caching

---

packages/angular/build/src/tools/sass/rebasing-importer.ts
tests/legacy-cli/e2e/tests/build/styles/bootstrap.ts

Function calls can alter the URL path, leading to issues during URL parsing.
Closes: #27688

fix(@angular/build): avoid rebasing URLs with function calls

---

packages/angular/build/src/builders/dev-server/vite-server.ts

With `esbuild-browser` the `polyfills` option can be a string which was not handled properly.
Closes #27693

fix(@angular/build): handle esbuild-browser `polyfills` option as `string` during `ng serve`

---

packages/angular/build/src/utils/normalize-cache.ts

When using the build system within a Web container, persistent disk caching is now disabled by default. Persistent disk caching does not provide a benefit for typical use cases and can cause increased browser memory usage when enabled.

fix(@angular/build): disable persistent disk caching inside webcontainers by default

---

CHANGELOG.md

docs: release notes for the v18.0.1 release

---

packages/schematics/angular/ssr/index.ts
packages/schematics/angular/utility/standalone/util.ts
packages/schematics/angular/utility/workspace-models.ts

The SSR schematic was previously only checking for the application build found within the `@angular-devkit/build-angular` package which is only an alias to the actual builder found in the `@angular/build` package. Both aliased and direct usages are now checked when executing the schematic.

fix(@schematics/angular): check both application builder packages in SSR schematic

---

packages/angular/build/src/tools/sass/sass-service.ts

The Sass Worker by default uses an Atomics-based wait loop to improve performance while waiting for messages. This loop relies on the synchronous API `receiveMessageOnPort`. While this works well in Node.js, the web container execution environment does not currently support passing transferable objects via `receiveMessageOnPort`.
Closes: #27723

fix(@angular/build): disable Worker wait loop for Sass compilations in web containers

---

packages/angular/build/src/tools/esbuild/stylesheets/sass-language.ts

When using the `@warn` directive, the `span` entry in the warning object is often undefined. Instead, the `stack` property is populated.
```js
{
"warnings": [
{
"deprecation": false,
"deprecationType": null,
"span": undefined,
"stack": "projects/foo/src/app/app.component.scss 1:1  root stylesheet\n",
"message": "some message"
}
]
}
```
```
▲ [WARNING] some message [plugin angular-sass]
```
```
▲ [WARNING] some message [plugin angular-sass]
projects/foo/src/app/app.component.scss 1:1  root stylesheet
```
Closes: #27726

fix(@angular/build): print Sass `@warn` location

---

packages/angular/build/src/builders/application/tests/behavior/stylesheet-url-resolution_spec.ts
packages/angular/build/src/tools/sass/lexer.ts
packages/angular/build/src/tools/sass/rebasing-importer.ts

Sass url rebasing correctness improvements

---

packages/angular/build/src/builders/application/setup-bundling.ts
packages/angular/build/src/builders/dev-server/vite-server.ts

With this commit, we introduce Vite dependencies prebundling for server bundles.
**Before:**
```
ng s
Browser bundles
Initial chunk files     | Names               |  Raw size
polyfills.js            | polyfills           |  90.87 kB
main.js                 | main                |  22.71 kB
styles.css              | styles              |  95 bytes
| Initial total       | 113.67 kB
Server bundles
Initial chunk files     | Names               |  Raw size
chunk-4EGJGG5L.mjs      | -                   |   1.80 MB
polyfills.server.mjs    | polyfills.server    | 573.58 kB
main.server.mjs         | main.server         | 224.03 kB
chunk-QDHZVCWX.mjs      | -                   |   2.57 kB
render-utils.server.mjs | render-utils.server | 423 bytes
Lazy chunk files        | Names               |  Raw …
```

perf(@angular/build): enable dependency prebundling for server dependencies

---

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts

The backing store for the persistent caching of the JavaScript transformers is not currently supported on web containers. To allow other potential forms of caching, the JavaScript transformer caching is now selectively disabled when executed on a web container. This allows for development server prebundling to be used on web containers if needed.

fix(@angular/build): disable JS transformer persistent cache on web containers

---

modules/testing/builder/projects/hello-world-app/tsconfig.json
packages/angular_devkit/build_angular/src/builders/browser/specs/lazy-module_spec.ts
packages/schematics/angular/workspace/files/tsconfig.json.template
tests/legacy-cli/e2e/tests/misc/safari-15-class-properties.ts
tests/legacy-cli/e2e/tests/misc/third-party-decorators.ts

Newly generated projects will now use ECMAScript standard class field behavior by default. If the legacy TypeScript behavior is required for a new project the `useDefineForClassFields` TypeScript option can be set to `false` within the application's `tsconfig`. This should be uncommon, and if needed, it is recommended to adjust code to match standard behavior where possible.

fix(@schematics/angular): generate new projects with ECMAScript standard class field behavior

---

packages/angular/cli/src/commands/add/cli.ts

This commit fixes the method `AddCommandModule.getCollectionName()`, so it now returns only the package name, but remove the specified version (if present).
Previously, a `@<version>` specified in the const `collectionName` was causing a (silenced) error during the invocation of `workflow.engine.createCollection(collectionName)`, which lead to skipping eventually the invocation of the method `this.addSchemaOptionsToCommand()` in the try/catch block.
fixes https://github.com/angular/angular-cli/issues/27766
Issue Number: https://github.com/angular/angular-cli/issues/27766

fix(@angular/cli): add `schema.json` options to parsed command, also when a version is passed to `ng add <package>@<version>`

---

goldens/public-api/angular/build/index.api.md
goldens/public-api/angular_devkit/build_angular/index.api.md
packages/angular/build/src/builders/dev-server/options.ts
packages/angular/build/src/builders/dev-server/schema.json
packages/angular/build/src/builders/dev-server/vite-server.ts
packages/angular_devkit/build_angular/src/builders/dev-server/options.ts
packages/angular_devkit/build_angular/src/builders/dev-server/schema.json

This commit introduces an `--inspect` option to the dev-server, enabling debugging of server-side code when using SSR or SSG. This option is equivalent to `node --inspect=[[host:]port]`.
Usage examples:
```
$ ng serve --inspect
$ ng serve --inspect 9999
$ ng serve --inspect localhost:9999
```
Closes: #27773

feat(@angular/build): add `--inspect` option to the dev-server

---

packages/angular/build/src/builders/application/tests/behavior/typescript-isolated-modules_spec.ts
packages/angular/build/src/tools/esbuild/angular/compilation/aot-compilation.ts
packages/angular/build/src/tools/esbuild/angular/compilation/parallel-worker.ts
packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts

When using the application builder and the TypeScript `isolatedModules` option is enabled and script sourcemaps are disabled, TypeScript code will be transpiled via the bundler instead of the current behavior of using TypeScript. The use of the `isolatedModules` option ensures that TypeScript code can be safely transpiled without the need for the type-checker. This mode of operation has several advantages. The bundler (esbuild in this case) will know have knowledge of the TypeScript code constructs, such as enums, and can optimize the output code based on that knowledge including inlining both const and regular enums where possible. Additionally, this allows for the removal of the babel-based optimization passes for all TypeScript code. These passes are still present for all JavaScript …

perf(@angular/build): use direct transpilation with isolated modules

---

CHANGELOG.md

docs: release notes for the v18.0.3 release

---

packages/angular/build/src/tools/esbuild/application-code-bundle.ts
tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts

This commit introduces a warning for when the application builders automatically add the @angular/localize/init polyfill. The current approach has a drawback: the localize polyfill will always be included if it is found in a monorepo, even if an application does not use i18n.
To address this, we will issue a warning to inform users about this behavior and encourage them to explicitly add the polyfill to their polyfills configuration.
Additionally, this commit fixes an issue where the polyfill was not removed when using the build-time Angular i18n.

fix(@angular/build): issue warning when auto adding `@angular/localize/init`

---

packages/angular/build/src/utils/index-file/augment-index-html.ts
packages/angular/build/src/utils/index-file/augment-index-html_spec.ts

The `modulepreload` link elements for initial scripts are now generated next to the actual script elements that require the referenced preloaded scripts. This better represents the fetch priorities to the browser and also allows easier visual discovery of the relevant script related elements inside the index HTML.

fix(@angular/build): generate module preloads next to script elements in index HTML

---

packages/angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts

Previously, PostCSS was initialized three times (once for each preprocessor), resulting in plugins being applied multiple times to each instance. This issue occured due to a race condition triggered by multiple esbuild plugins.
Fixes #27804

fix(@angular/build): Initiate PostCSS only once

---

package.json
scripts/saucelabs/start-tunnel.sh
yarn.lock

The saucelabs connect tunnel utility is now only downloaded when a saucelabs related test is executed. Previously it was part of the root `package.json` and downloaded whenever a package install was executed. The utility archive was also not an actual package which incidentally worked with npm but does not work with newer versions of yarn. A SHA256 check is also now performed prior to executing the utility to verify the expected file is present.

ci: only download saucelabs connect utility when running tests

---

scripts/build-schema.mts

`--silent` is not a valid option for Yarn 4. This causes the build-schema script to fail.

build: remove `--silent` from `yarn` command

---

packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/code-coverage_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage-exclude_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage_spec.ts

In this commit, the custom implementation of a promise-based setTimeout function has been replaced with the native Node.js setTimeout function, which now returns a promise.

refactor: replace custom promise-based setTimeout with native Node.js setTimeout

---

packages/angular/cli/lib/cli/index.ts
packages/angular/cli/src/utilities/color.ts

Node.js contains a helper function within the `util` builtin that will remove any ANSI escape codes from a string. This removes the need for a custom utility function.

refactor(@angular/cli): use Node.js builtin ANSI escape removal helper

---

renovate.json

Since the yarn version is specified in the Bazel setup, automatically updating the dependency is not feasible.

ci: disable `yarn` auto update

---

.yarnrc.yml
package.json
yarn.lock

Package installation will now disable postinstall scripts by default for the repository dependencies. The yarn `enableScripts` option is now set to `false`. This still allows workspace postinstall scripts to execute and the required dependency postinstall scripts are explicitly allowed (currently: esbuild & puppeteer).

build: disable package install scripts by default

---

docs/DEVELOPER.md

The E2E config allows stamping, not using it can cause certain e2e tests to fail locally.

docs: update e2e test commands

---

.github/dependency-review-config.yml
package.json
tests/legacy-cli/e2e/setup/010-local-publish.ts
tests/legacy-cli/e2e/utils/registry.ts
yarn.lock

This commit updates the e2e setup to use the latest version of NPM to publish packages.

build: update E2E setup to use NPM 10 to publish packages

---

.github/workflows/ci.yml
.github/workflows/pr.yml
packages/angular/cli/src/commands/update/cli.ts
tests/legacy-cli/e2e.bzl
tests/legacy-cli/e2e/initialize/300-log-environment.ts
tests/legacy-cli/e2e/setup/100-global-cli.ts
tests/legacy-cli/e2e/tests/misc/create-angular.ts
tests/legacy-cli/e2e/tests/update/update.ts
tests/legacy-cli/e2e/utils/packages.ts
tests/legacy-cli/e2e/utils/process.ts
tests/legacy-cli/e2e_runner.ts

This commit adds PNPM and Bun package managers as subsets. However, Bun tests are currently disabled due to an issue where packages from the local registry are only partially extracted.

test: add bun and pnpm subsets

---

.github/workflows/ci.yml

These subsets are for validation and are typically not affected by Node.js versions.

ci: disable running pnpm and yarn subsets on Node.js 20 and 18

---

tests/legacy-cli/e2e/tests/web-test-runner/basic.ts

This was disabled due to an issue with Puppeteer and Bazel which has been resolved by a simple version update.

test: re-enable WTR test

---

packages/angular/build/src/builders/application/tests/options/sourcemap_spec.ts
packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular/build/src/tools/esbuild/compiler-plugin-options.ts
packages/angular/build/src/tools/esbuild/global-styles.ts

This commit addresses an issue where sourcemaps in web workers and global stylesheets were referenced despite the hidden setting being enabled.
Closes: #27833

fix(@angular/build): do not reference sourcemaps in web workers and global stylesheet bundles when hidden setting is enabled

---

CHANGELOG.md

docs: release notes for the v18.0.4 release

---

packages/angular/build/src/builders/dev-server/vite-server.ts
packages/angular/build/src/tools/esbuild/application-code-bundle.ts
packages/angular/build/src/tools/esbuild/global-scripts.ts

Previously, ESM file resolution without extensions failed when using Vite, causing issues in module loading. This commit addresses the problem by automatically resolving `.mjs` files, aligning the behavior with the application builder and ensuring consistent module resolution across different build tools.
**NB**:  This is a workaround as valid ESM imports should always have an extension.
Closes #27841

fix(@angular/build): automatically resolve `.mjs` files when using Vite

---

packages/schematics/angular/application/files/module-files/src/app/app.component.spec.ts.template
tests/legacy-cli/e2e/assets/15.0-project/src/app/app.component.spec.ts
tests/legacy-cli/e2e/assets/18-ssr-project-webpack/src/app/app.component.spec.ts

update schematics to use RouterModule instead of RouterTestingModule when generating a new project with the --routing flag
Fixes #27691
Running `ng new --inline-style false --inline-template false --package-manager bun --routing --skip-git --standalone false --strict true --ssr false --style scss my-test-app` generates a new project with the `RouterTestingModule` which is deprecated
Issue Number: #27691 
Running `ng new --inline-style false --inline-template false --package-manager bun --routing --skip-git --standalone false --strict true --ssr false --style scss my-test-app` generates a new projects with the `RouterModule`
NA

fix(@angular/cli): update schematics to use RouterModule when --routing flag is present

---

packages/angular/cli/BUILD.bazel
packages/angular/cli/lib/cli/index.ts
packages/angular/cli/package.json
packages/angular/cli/src/commands/update/cli.ts
packages/angular/cli/src/utilities/color.ts
yarn.lock

The newly introduced `listr2` dependency used for the updated `ng add` console UI provides color support. This removes the need to retain a direct dependency on a color package within the `@angular/cli`.

refactor(@angular/cli): remove direct use of ansi-colors package

---

packages/angular/build/src/utils/index-file/nonce.ts
packages/angular/build/src/utils/index-file/nonce_spec.ts

Prior to this change, script tags with the `src` attribute were not being assigned a CSP nonce during the build process. This is useful strict-dynamic is a Content Security Policy (CSP) directive that simplifies the management of dynamically loaded scripts while maintaining a high level of security. It allows scripts that are initially trusted (through a nonce or hash) to load other scripts without additional restrictions.
Closes #27874

fix(@angular/build): add CSP nonce to script with src tags

---

packages/angular/build/src/utils/environment-options.ts
packages/angular_devkit/build_angular/src/utils/environment-options.ts

The Node.js `os.availableParallelism` API now provides more accurate values when used within containers such as many CI environments. This provides a better default when using resource limited CI setups. The value is still set to a maximum default of four. However, the `NG_BUILD_MAX_WORKERS` environment variable can be used to set the value to an explicit value if required.

fix(@angular/build): use Node.js available parallelism for default worker count

---

tests/legacy-cli/e2e/tests/misc/create-angular.ts

Previously, this test did not include package installation.

test: update create-angular test to install packages

---

CHANGELOG.md

docs: release notes for the v18.0.5 release

---

package.json
packages/ngtools/webpack/package.json
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
yarn.lock

Updates the repo to the stable version of TypeScript 5.5. I'm holding off on updating the new projects to it due to https://github.com/angular/angular/pull/56358.

build: update to TypeScript 5.5 stable

---

packages/angular/build/src/private.ts

Add `createCompilerPlugin` function to the private export of the package. Note that these are not considered part of the public API and are intended for use only with the `@angular-devkit/build-angular` package.

refactor(@angular/build): include Angular compiler plugin in private API

---

packages/angular/cli/src/utilities/color.ts
packages/angular/cli/src/utilities/tty.ts

The `isTTY` and `supportColor` helpers can now accept a stream to check instead of assuming stdout. This is useful if stderr needs to be checked, for instance. Also, color checking now uses Node.js `hasColors` where possible which has been available since Node.js v10.

refactor(@angular/cli): allow tty and color helpers to use a stream

---

packages/angular/build/src/tools/esbuild/bundler-context.ts

The bundler context class now has a static helper method to support merging bundler results outside of a specific bundle action. This will be used in the future to support more complex bundling hierarchies.

refactor(@angular/build): support directly merging bundler results

---

tests/legacy-cli/e2e/tests/basic/aot.ts
tests/legacy-cli/e2e/tests/basic/build.ts
tests/legacy-cli/e2e/tests/basic/command-scope.ts
tests/legacy-cli/e2e/tests/basic/e2e.ts
tests/legacy-cli/e2e/tests/basic/run.ts

The aot, build, and command-scope E2E tests now use assertions from the Node.js `assert` builtin module. This reduces the amount of code within each test and improves the overall readability.

test: add proper assertions to several E2E tests

---

packages/angular/build/src/builders/dev-server/vite-server.ts

Replacing the paths to ESM in Vite can cause prebundling to fail in some cases, resulting in errors similar to the following:
```
12:55:12 PM [vite] Error when evaluating SSR module /chunk-CHB4JJIP.mjs:
|- TypeError: Cannot read properties of undefined (reading 'Subject')
at eval (//src/app/shared/snackbar/snackbar.service.ts:2:25)
at async instantiateModule (file:////node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53408:5)
12:55:12 PM [vite] Error when evaluating SSR module /chunk-GQZ5BKXC.mjs:
|- TypeError: Cannot read properties of undefined (reading 'Subject')
at eval (//src/app/shared/snackbar/snackbar.service.ts:2:25)
at async instantiateModule (file:////node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53408:5)
```
Closes: #27907

fix(@angular/build): address rxjs undefined issues during SSR prebundling

---

packages/angular/cli/src/commands/config/cli.ts
packages/angular/cli/src/commands/update/cli.ts
packages/angular/cli/src/utilities/package-tree.ts
packages/angular/cli/src/utilities/project.ts
tsconfig.json

To remove the tsetse rule exclusions, several usages of `JSON.parse` that did not have type casting where adjusted to add types. This removed the need for the manual configuration within the tsconfig.

build: remove tsetse rule exclusions

---

packages/angular_devkit/core/src/json/schema/registry.ts
packages/angular_devkit/core/src/utils/object.ts

Add type casting to several additional `JSON.parse` usages to avoid implicit any usage in the code.

refactor(@angular-devkit/core): additional JSON parse type casting

---

packages/angular/cli/src/utilities/memoize.ts
tsconfig.json

With standard decorator support now available for use, the memoize decorator has been updated to be a standard decorator instead of the TypeScript experimental decorator. This change also removes the only usage of decorators within the Angular CLI code itself. This change does not affect application code.

refactor(@angular/cli): use non-experimental decorators for internal memoize

---

package.json
packages/angular/build/BUILD.bazel
packages/angular_devkit/build_angular/BUILD.bazel
yarn.lock

`browserslist` now ships it's own typings

build: remove `@types/browserslist`

---

package.json
packages/angular_devkit/schematics_cli/blank/project-files/package.json
packages/angular_devkit/schematics_cli/schematic/files/package.json
packages/schematics/angular/utility/latest-versions/package.json
tests/legacy-cli/e2e/assets/18-ssr-project-webpack/package.json
yarn.lock

Now that https://github.com/angular/angular/pull/56358 is on track for 18.1, we can use TypeScript 5.5 for newly-created projects and in tests.

build: use TypeScript 5.5 for new projects and tests

---

packages/angular_devkit/schematics/tools/file-system-utility.ts

The file system engine hosts for schematics were using a helper method to read JSON files that was performing both an exist and read call. Besides causing two file system calls, this also has a potential race condition where the file may not exist by the time the read call is made. To avoid this, a try/catch is used with the read call to handle the not existing case.

refactor(@angular-devkit/schematics): avoid double file access reading JSON files

---

CHANGELOG.md

docs: release notes for the v18.0.6 release

---

CHANGELOG.md
package.json

Also this PR cherry-picks the changelog for v18.1.0-rc.0 into the main branch so that the changelog is up to date.

Update next branch to reflect new release-train "v18.2.0-next.0".

---

goldens/public-api/angular/build/index.api.md
packages/angular/build/src/builders/application/execute-post-bundle.ts
packages/angular/build/src/tools/esbuild/bundler-context.ts
packages/angular/build/src/tools/esbuild/bundler-execution-result.ts
packages/angular/build/src/tools/esbuild/i18n-inliner.ts
packages/angular/build/src/tools/esbuild/utils.ts

The `BuildOutputFile` type's helper functions have been adjusted to cache commonly accessed property values to avoid potentially expensive repeat processing. This includes encoding/decoding UTF-8 content and calculating hash values for the output file content. A size property has also been added to allow consumers to more directly determine the byte size of the output file. The size property is currently unused but will be leveraged in forthcoming updates to bundle budgets and console info logging.

refactor(@angular/build): improve BuildOutputFile property access

---

packages/angular/build/src/tools/vite/angular-memory-plugin.ts

Before this update, the importer path was not normalized, causing mismatches during SSR on Windows.

fix(@angular/build): normalize paths during module resolution in Vite

---

packages/angular/build/src/builders/application/tests/options/bundle-budgets_spec.ts
packages/angular/build/src/tools/esbuild/budget-stats.ts
packages/angular/build/src/tools/esbuild/utils.ts

This commit addresses an issue where some lazy entry points were not name correctly to align with specified budgets.
Closes: #27936

fix(@angular/build): correctly name entry points to match budgets

---

packages/angular/build/src/builders/application/execute-build.ts
packages/angular/build/src/tools/esbuild/budget-stats.ts
packages/angular/build/src/tools/esbuild/utils.ts

The bundle budget calculators and the console build stats output are now calculated directly from the build output file information instead of the esbuild metafile where possible. This provides a more generic method of accessing the information and can more accurately account for post-processing steps that may alter the output files. The metafile is still used for component style budgets and lazy chunk name information.

refactor(@angular/build): use build output files directly in stats and budgets

---

packages/angular/cli/src/commands/update/schematic/index.ts
packages/angular/cli/src/commands/update/schematic/index_spec.ts

As stated in https://github.com/angular/angular-cli/issues/11744, `ng update` command removed the newline at the end of the package.json file. This commit makes `ng update` to preserve newline, if it was present before running the command.
Fixes #11744
Issue Number: #11744
`ng update` preserves the newline at the end of the package.json file

fix(@angular/cli): make `ng update` to keep newline at the end of package.json

---

packages/angular_devkit/schematics/src/rules/template.ts

An explicit cast was removed in https://github.com/angular/angular-cli/commit/fa9bce0e9ae5f28ae1d5c826bd218145a343c731#diff-29e41c6172a2d68db9886be9e933ed2b477732095313e104c52a725f887276cf which relies on [control flow narrowing](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#control-flow-narrowing-for-constant-indexed-accesses) in TS 5.5. However, google3 is still on TS 5.4, so we can't fully depend on that feature. Using an intermediate variable makes the type narrowing work correctly even in TS 5.4.

refactor: fix pipe type

---

package.json
packages/angular/build/BUILD.bazel
packages/angular/build/package.json
packages/angular/build/src/builders/application/chunk-optimizer.ts
packages/angular/build/src/builders/application/execute-build.ts
packages/angular/build/src/utils/environment-options.ts
tests/legacy-cli/e2e/tests/build/chunk-optimizer.ts
tests/legacy-cli/e2e/tests/build/material.ts
yarn.lock

An experimental chunk optimizer is now available for initial usage. To enable the optimization, script optimization must be enabled as well as an environment variable `NG_BUILD_OPTIMIZE_CHUNKS=1`. This build step uses `rollup` internally to process the build files directly in memory. The main bundling performs all resolution, bundling, and tree-shaking of the application. The chunk optimizer step then only needs to access the in-memory built files and does not need to perform any disk access or module resolution. This allows the step to be performed fairly quickly but it does add time to the overall production build. The `NG_BUILD_DEBUG_PERF=1` environment variable can be used to view how long the step takes within a build via the `OPTIMIZE_CHUNKS` entry. In the future, this optimization …

refactor(@angular/build): add experimental chunk optimizer for production application builds

---

packages/angular/build/src/builders/dev-server/tests/behavior/build-assets_spec.ts
packages/angular/build/src/tools/vite/angular-memory-plugin.ts

Prior to this commit, accessing a static asset directory without a trailing slash resulted in a 404 error. With this change, we now redirect to the path with a trailing slash, aligning with the behavior of express static.
Closes #27949

fix(@angular/build): redirect to path with trailing slash for asset directories

---

packages/angular/build/src/builders/dev-server/vite-server.ts
packages/angular/build/src/tools/vite/angular-memory-plugin.ts
packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts
packages/angular/build/src/tools/vite/middlewares/html-fallback-middleware.ts
packages/angular/build/src/tools/vite/middlewares/index-html-middleware.ts
packages/angular/build/src/tools/vite/middlewares/index.ts
packages/angular/build/src/tools/vite/middlewares/ssr-middleware.ts
packages/angular/build/src/tools/vite/utils.ts

As the number of middlewares has increased over time, this commit enhances code health by relocating them into individual files.

refactor(@angular/build): move Vite middlewares into separate files

---

packages/angular/build/src/utils/environment-options.ts
packages/angular_devkit/build_angular/src/utils/environment-options.ts

This commit reduces the maximum number of workers to the available CPUs minus 1. This adjustment ensures that some resources are left for the main thread, preventing it from being starved of CPU cycles.
For more context see: https://github.com/angular/angular-cli/issues/27167#issuecomment-2199987874

fix(@angular/build): reduce the number of max workers to available CPUs minus one

---

packages/angular/build/src/tools/esbuild/utils.ts

With the potential future introduction of features such as WASM/ES module integration and the experimental chunk optimizer, the need to restrict top-level await usage is no longer needed and a blocker for new features. As such, top-level await will now be available if an application has been configured to be zoneless.
Zoneless Angular is currently experimental and more details can be found here: https://angular.dev/guide/experimental/zoneless

fix(@angular/build): allow top-level await in zoneless applications

---

tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts

It can be re-enabled now that https://github.com/angular/angular/pull/56300 have been released in v18.1.0-next.2

test: re-enable localize warning check

---

package.json
packages/angular_devkit/build_angular/package.json
renovate.json
yarn.lock

More information in https://github.com/terser/terser/issues/1539
Closes #27866

fix(@angular-devkit/build-angular): rollback terser to `5.29.2`

---

package.json
packages/angular/build/BUILD.bazel
packages/angular/build/package.json
packages/angular/build/src/tools/esbuild/javascript-transformer-worker.ts
yarn.lock

The babel-based JavaScript transformer currently requires a syntax plugin to support import attributes. Import attributes are otherwise supported in application code. However, in production builds the JavaScript transformations such as the build optimizer passes would fail on code that contain any import attributes. The inclusion of the babel syntax plugin removes this problem. Once babel provides built-in support for this syntax feature, the plugin can be removed.
(cherry picked from commit 2dc51d5c9cd1c40dbd97a714e3bb4d17e51c27ae)

fix(@angular/build): support import attributes in JavaScript transformer

---

packages/angular/build/src/builders/application/tests/behavior/wasm-esm_spec.ts
packages/angular/build/src/tools/esbuild/application-code-bundle.ts
packages/angular/build/src/tools/esbuild/wasm-plugin.ts
packages/angular/build/src/tools/esbuild/wasm.d.ts
tests/legacy-cli/e2e.bzl
tests/legacy-cli/e2e/tests/build/wasm-esm.ts

Application builds will now support the direct import of WASM files. The behavior follows the WebAssembly/ES module integration proposal. The usage of this feature requires the ability to use native async/await and top-level await. Due to this requirement, applications must be zoneless to use this new feature. Applications that use Zone.js are currently incompatible and an error will be generated if the feature is used in a Zone.js application. Manual setup of a WASM file is, however, possible in a Zone.js application if WASM usage is required. Further details for manual setup can be found here: https://developer.mozilla.org/en-US/docs/WebAssembly/Loading_and_running
The following is a brief example of using a WASM file in the new feature with the integration proposal behavior:
```
import …
```

feat(@angular/build): support WASM/ES Module integration proposal

---

CHANGELOG.md

docs: release notes for the v18.0.7 release

---

CHANGELOG.md

docs: release notes for the v18.1.0-rc.1 release

---

packages/angular/build/src/tools/angular/compilation/aot-compilation.ts
packages/angular/build/src/tools/angular/compilation/parallel-worker.ts
packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts

The isolated modules transpilation option that was recently introduced is currently disabled when source maps are enabled. TypeScript has two mutually exclusive options that can be used to check for source map usage. Both of these options (`sourceMap` and `inlineSourceMap`) are now checked to determine if the direct transpilation optimization can be used.

fix(@angular/build): check inlineSourceMap option with isolated modules optimization

---

scripts/devkit-admin.mts

Implicit coercion to number was removed in node 20, see https://nodejs.org/api/deprecations.html#DEP0164

refactor: use explicit coercion of exitCode to number.

---

package.json
tools/defaults.bzl
yarn.lock

This commit removes unused bazel rules.

build: remove unused bazel rules

---

packages/schematics/angular/workspace/files/tsconfig.json.template

As 3acb7768317bb05a9cd73fa64e081b5ca0326189 introduced an optimization for projects that use `isolatedModules`, this commit makes projects generated with `ng new` use this option by default.

feat(@schematics/angular): use isolatedModules in generated project

---

packages/angular/build/src/tools/esbuild/wasm-plugin.ts
tests/legacy-cli/e2e/tests/build/wasm-esm.ts

When using a WASM file on Node.js via SSR/SSG/etc. the path for the `readFile` call will now be based on the location of the script using the WASM file instead of the current working directory.
This change also adds a general Node.js WASM E2E test via prerendering.

fix(@angular/build): read WASM file from script location on Node.js

---

renovate.json

Issue https://github.com/terser/terser/issues/1539 has been fixed and released as part of `5.31.2`

ci: allow terser to be updated by renovate

---

CHANGELOG.md

docs: release notes for the v18.1.0 release

---

.eslintrc.json
packages/angular/build/src/builders/extract-i18n/builder.ts
packages/angular/build/src/builders/extract-i18n/options.ts
packages/angular/build/src/tools/angular/transformers/jit-bootstrap-transformer.ts
packages/angular/build/src/tools/angular/transformers/jit-resource-transformer.ts
packages/angular/build/src/utils/index-file/inline-fonts.ts
packages/angular/cli/src/command-builder/schematics-command-module.ts
packages/angular/cli/src/command-builder/utilities/schematic-workflow.ts
packages/angular_devkit/build_angular/src/builders/extract-i18n/builder.ts
packages/angular_devkit/build_angular/src/builders/extract-i18n/options.ts
packages/angular_devkit/build_angular/src/tools/babel/webpack-loader.ts
packages/angular_devkit/core/src/workspace/json/reader.ts
packages/angular_devkit/core/src/workspace/json/writer.ts
packages/angular_devkit/schematics/src/engine/engine.ts
packages/angular_devkit/schematics/src/tree/action.ts
packages/angular_devkit/schematics_cli/bin/schematics.ts
packages/ngtools/webpack/src/transformers/elide_imports.ts
packages/ngtools/webpack/src/transformers/replace_resources.ts

Each rule is enabled in a separate commit with relevant fixes when needed.

Enable several previously disabled lint rules 

---

tests/legacy-cli/BUILD.bazel
tests/legacy-cli/e2e.bzl
tests/legacy-cli/e2e/initialize/500-create-project.ts
tests/legacy-cli/e2e/initialize/BUILD.bazel
tests/legacy-cli/e2e/utils/BUILD.bazel
tests/legacy-cli/e2e/utils/project.ts
tests/legacy-cli/e2e_runner.ts

The `node:util` builtin provides an argument parser that
can be leveraged for the E2E test runner that avoids the
need for additional third-party packages.

test: use Node.js argument parser for E2E test runner

---

packages/angular/build/src/builders/application/tests/behavior/loader-import-attribute_spec.ts
packages/angular/build/src/tools/esbuild/application-code-bundle.ts
packages/angular/build/src/tools/esbuild/loader-import-attribute-plugin.ts

When using the `application` builder, a `loader` import attribute is now available for use with import statements and expressions. The presence of the import attribute takes precedence over all other loading behavior including JS/TS and any `loader` build option values. This allows per file control over loading behavior. For general loading for all files of an otherwise unsupported file type, the `loader` build option is recommended.
For the import attribute, the following loader values are supported:
* `text` - inlines the content as a string
* `binary` - inlines the content as a Uint8Array
* `file` - emits the file and provides the runtime location of the file
Unfortunately, at this time, TypeScript does not support type definitions that are based on import attribute values. The use of …

feat(@angular/build): support import attribute based loader configuration

---

packages/angular/build/src/builders/dev-server/tests/behavior/build-external-dependencies_spec.ts
packages/angular/build/src/builders/dev-server/vite-server.ts
packages/angular/build/src/tools/vite/id-prefix-plugin.ts

This PR adds a Vite plugin to remove the `/@id/` prefix (which gets inserted by Vite during import-analysis) for explicit externalDependencies.
Issue Number: #28028
The `/@id/` prefix gets removed from a new Vite plugin.

fix(@angular/build): remove Vite "/@id/" prefix for explicit external dependencies

---

CHANGELOG.md

docs: release notes for the v18.1.1 release

---

packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts

Added handling to ensure trailing slashes on static files do not disregard query strings.
Closes #28071

fix(@angular/build): prevent redirection loop

---

packages/angular/build/src/builders/dev-server/tests/behavior/build-external-dependencies_spec.ts
packages/angular/build/src/tools/vite/id-prefix-plugin.ts

When adjusting URLs to support explicit external dependencies when using Vite, the workaround will now account for the presence of a base HREF value within the specifier. Vite will automatically add the base HREF as a prefix to the path when specified. This previously resulted in invalid specifiers due to the partial removal of the full Vite specific `@id` path prefix.
Closes #28077

fix(@angular/build): account for HTML base HREF for dev-server externals

---

packages/angular/build/src/builders/application/build-action.ts
packages/angular/build/src/builders/application/execute-build.ts
packages/angular/build/src/builders/application/index.ts
packages/angular/build/src/builders/application/results.ts
packages/angular/build/src/builders/application/tests/options/output-path_spec.ts
packages/angular/build/src/builders/dev-server/vite-server.ts
packages/angular/build/src/builders/extract-i18n/application-extraction.ts
packages/angular/build/src/builders/extract-i18n/builder.ts
packages/angular/build/src/private.ts
packages/angular/build/src/tools/esbuild/bundler-execution-result.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/assets_spec.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/delete-output-path_spec.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/deploy-url_spec.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/main_spec.ts
packages/angular_devkit/build_angular/src/builders/extract-i18n/application-extraction.ts
packages/angular_devkit/build_angular/src/builders/extract-i18n/builder.ts
packages/angular_devkit/build_angular/src/builders/web-test-runner/index.ts

The application builder now provides structured output types to its internal consumers. The architect builders themselves and the programmatic API is not changed. These output result types allow for the development server to receive additional information regarding the build and update the active browser appropriately. This functionality is not yet implemented but the additional result types provide the base infrastructure to enable future features. The result types also allow for reduced complexity inside other builders such as i18n extraction and the browser compatibility builder. The usage is not yet fully optimized and will be refined in future changes.

refactor(@angular/build): provide structured application builder result types

---

packages/angular/build/src/tools/sass/lexer.ts
packages/angular/build/src/tools/sass/lexer_spec.ts

The Sass rebasing lexer was incorrectly checking for a comma in certain cases previously. This has now been corrected and url usage that immediately follows a comma within a rule will now be extracted as expected.
Closes #28084

fix(@angular/build): correctly detect comma in Sass URL lexer

---

CHANGELOG.md

docs: release notes for the v18.1.2 release

---

packages/angular/build/src/builders/extract-i18n/builder.ts
packages/angular_devkit/build_angular/src/builders/extract-i18n/builder.ts

The `extract-i18n` builder is only intended to be used with application projects.
Closes #28109

fix(@angular/build): resolve error with `extract-i18n` builder for libraries

---

packages/angular/build/src/builders/application/tests/behavior/csp-nonce_spec.ts
packages/angular/build/src/utils/index-file/index-html-generator.ts

Prior to this change when inline critical CSS is disabled CSP `nonce` was not added to script tags.
Closes #28102

fix(@angular/build): add CSP `nonce` attribute to script tags when inline critical CSS is disabled

---

renovate.json

Dev-infra recently upgraded to Renovate version 38. This update causes `matchDepPatterns` to only accept RegExp. Since we require a glob pattern, we will now use `matchPackageNames`, which supports glob patterns and is already used in the configuration.

ci: replace `matchDepPatterns` with `matchPackageNames`

---

packages/angular/build/src/tools/esbuild/stylesheets/bundle-options.ts
packages/angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts
tests/legacy-cli/e2e/tests/build/styles/tailwind-v3.ts

This addresses a bug where `@import url()` statements with remote CSS files (ending in .css) caused build errors when Tailwind was present. The issue arised from incorrect handling of remote URLs by the stylesheet plugin, which treated them as local files. This fix ensures proper handling of remote CSS imports.
Closes #28113

fix(@angular/build): prevent build failures with remote CSS imports when Tailwind is configured

---

CHANGELOG.md

docs: release notes for the v18.1.3 release

---

packages/angular_devkit/build_angular/src/builders/jest/index.ts
packages/angular_devkit/build_angular/src/builders/web-test-runner/index.ts
packages/angular_devkit/build_angular/src/builders/web-test-runner/write-test-files.ts

With the structured build results available, the WTR builder can now more easily write only the needed files to a temporary location. This reduces the need to assume build directory output structure and reduces the amount of potential filesystem calls. The temporary files are also now written into a UUID subdirectory within the existing `dist/test-out` location. This allows for multiple projects to be tested concurrently without overwriting each other.
The Jest builder has also been updated with similar changes.

refactor(@angular-devkit/build-angular): only write test related files in WTR builder

---

packages/angular/build/src/builders/application/tests/behavior/typescript-incremental_spec.ts
packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts

If the TypeScript `incremental` option is explicitly set to `false`, the `application` builder will no longer attempt to enable and use incremental compilation mode via stored TypeScript build file information. This prevents an potential build time error that would otherwise occur due to the `tsBuildInfoFile` option being set without the `incremental` option. Behavior remains the same if the option is not present or set to `true`.

fix(@angular/build): allow explicitly disabling TypeScript incremental mode

---

.eslintrc.json
package.json
packages/angular_devkit/core/src/json/schema/interface.ts
packages/ngtools/webpack/src/transformers/find_image_domains.ts
scripts/validate-user-analytics.mts
yarn.lock

The `@typescript-eslint/eslint-plugin` package has been updated to v8.0.1. With new major versions of the package, additional rules are added to the default recommended list. Several such new rules have been disabled to minimize the code changes to update the package. Several minor type only fixes were however included to reduce the number of disabled rules.

test: update @typescript-eslint/eslint-plugin to v8.0.1

---

packages/angular/build/src/builders/dev-server/vite-server.ts

The Node.js inspector will now only be imported if SSR is enabled and the `inspect` option is used. This prevents potential failures when a custom Node.js binary build is used that has not enabled inspector usage. While this is not common, loading the inspector on demand is a minimal change that also avoids loading code that will not be used for the majority of development server usage.
Closes #28172

fix(@angular/build): lazy load Node.js inspector for dev server

---

CHANGELOG.md

docs: release notes for the v18.1.4 release

---

CHANGELOG.md
package.json

Also this PR cherry-picks the changelog for v18.2.0-rc.0 into the main branch so that the changelog is up to date.

Update next branch to reflect new release-train "v18.3.0-next.0".

---

packages/angular/cli/src/command-builder/schematics-command-module.ts
packages/angular_devkit/schematics_cli/bin/schematics.ts

Previously, when a select or checkbox prompt failed validation, it was bypassed, preventing users from correcting their input. This commit ensures that when validation fails, the prompts are re-displayed, allowing users to make the necessary corrections. This improves the user experience and helps avoid unintended selections.
Closes #28189

fix(@angular/cli): prevent bypassing select/checkbox prompts on validation failure

---

packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/assets_spec.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/delete-output-path_spec.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/deploy-url_spec.ts
packages/angular_devkit/build_angular/src/builders/browser-esbuild/tests/options/main_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
packages/angular_devkit/build_angular/src/builders/extract-i18n/application-extraction.ts

The implementation of the `browser-esbuild` builder is now a small wrapper around the `application` builder. The custom file writing code is no longer required with the availability of the additional output path options for `application` builder. This also allows the internal `browser-esbuild` programmatic interface to retain its architect-based signature.

refactor(@angular-devkit/build-angular): reduce custom code in browser-esbuild implementation

---

packages/angular_devkit/schematics_cli/bin/schematics.ts
packages/angular_devkit/schematics_cli/blank/factory.ts
packages/angular_devkit/schematics_cli/blank/schema.json
packages/angular_devkit/schematics_cli/schematic/factory.ts
packages/angular_devkit/schematics_cli/schematic/schema.json
tests/legacy-cli/e2e/tests/schematics_cli/basic.ts
tests/legacy-cli/e2e/tests/schematics_cli/blank-test.ts
tests/legacy-cli/e2e/tests/schematics_cli/schematic-test.ts

Allows users to specify the package manager (npm, yarn, etc.) when creating a new project using the `schematics blank` command. Resolves #27571.

feat(@angular-devkit/schematics-cli): add package manager option to blank schematic

---

goldens/circular-deps/packages.json
packages/angular/ssr/BUILD.bazel
packages/angular/ssr/package.json
packages/angular/ssr/src/app-engine.ts
packages/angular/ssr/src/app.ts
packages/angular/ssr/src/assets.ts
packages/angular/ssr/src/manifest.ts
packages/angular/ssr/src/render.ts
packages/angular/ssr/src/routes/ng-routes.ts
packages/angular/ssr/src/routes/route-tree.ts
packages/angular/ssr/src/routes/router.ts
packages/angular/ssr/src/utils/ng.ts
packages/angular/ssr/src/utils/url.ts
packages/angular/ssr/test/BUILD.bazel
packages/angular/ssr/test/app-engine_spec.ts
packages/angular/ssr/test/app_spec.ts
packages/angular/ssr/test/assets_spec.ts
packages/angular/ssr/test/routes/route-tree_spec.ts
packages/angular/ssr/test/routes/router_spec.ts
packages/angular/ssr/test/testing-utils.ts
packages/angular/ssr/test/utils/url_spec.ts
yarn.lock

This enhancement eliminates the dependency on file extensions for server-side rendering (SSR) route handling, leveraging Angular's router configuration for more dynamic and flexible route determination. Additionally, configured redirectTo routes now correctly respond with a 302 redirect status.
The new router uses a radix tree for storing routes. This data structure allows for efficient prefix-based lookups and insertions, which is particularly crucial when dealing with nested and parameterized routes.
This change also lays the groundwork for potential future server-side routing configurations, further enhancing the capabilities of Angular's SSR functionality.

feat(@angular/ssr): dynamic route resolution using Angular router

---

packages/angular/create/BUILD.bazel

Included missing `@angular/cli` in `pkg_deps`.

build: add missing `pkg_deps` for `@angular/create`

---

CHANGELOG.md

docs: release notes for the v18.2.0 release

---

packages/angular/build/src/utils/server-rendering/prerender.ts
packages/angular_devkit/build_angular/src/builders/server/tests/behavior/build-errors_spec.ts

This change enhances the error messaging when an unhandled exception occurs during the prerendering process. The updated error message provides more context and clarity.
**Previous Behavior**
```
ng b
An unhandled exception occurred: Some error!!!
See "/tmp/ng-S2ABKF/angular-errors.log" for further details.
```
**Updated Behavior:**
```
ng b
Browser bundles
Initial chunk files     | Names               |  Raw size | Estimated transfer size
main-AFPIPGGK.js        | main                | 218.00 kB |                59.48 kB
polyfills-Z2GOM3BN.js   | polyfills           |  35.82 kB |                11.80 kB
styles-5INURTSO.css     | styles              |   0 bytes |                 0 bytes
| Initial total       | 253.82 kB |                71.28 kB
Server bundles
Initial chunk files     | …
```

fix(@angular/build): improve error message when an unhandled exception occurs during prerendering

---

tools/link_package_json_to_tarballs.bzl

Fixes the paths to npm_package_archive.tgz on local builds
I have followed the documentation steps mentioned in [Developer.md](https://github.com/angular/angular-cli/blob/main/docs/DEVELOPER.md). After running `yarn build --local` the package.json file for every scope(i.e. cli, build, pwa, etc..) have incorrect paths to npm_package_archive.tgz
Steps to reproduce
1. Clone the [angular cli repository](https://github.com/angular/angular-cli). 
2. Run `yarn build --local`
3. Open the dist folder and extract _angular_cli.tgz (Using this as an example you can look for any other tgz file in dist)
4. Open the `package.json` file
5. Look for `@angular-devkit/architect` (Using this as an …

BUILD: Changes to local repo's build system(path to npm_package_archive.tgz files)

---

package.json
packages/angular/build/package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

In 18.2 the Sass version was updated to 1.77.7 which causes a lot of deprecation warnings for Material users (see https://github.com/angular/components/issues/29591). Resolving these warnings can break some apps so we want to delay it until v19.
These changes downgrade to a version that doesn't check for the deprecation.

build: downgrade sass version

---

tools/link_package_json_to_tarballs.bzl

This reverts commit eedeee2f4fc4f0cd3124611aa733d320847f5bd3.
Causes snapshot publishing failures: https://github.com/angular/angular-cli/actions/runs/10471282117/job/29006137399

Revert "build: change to local repo's build system(path to npm_package_archive.tgz files)"

---

packages/angular/build/src/builders/extract-i18n/application-extraction.ts
packages/angular_devkit/build_angular/src/builders/extract-i18n/application-extraction.ts

If an application has JavaScript files that are sourced directly from disk, the extraction would previously fail due to the i18n extractor only able to access the in-memory generated JavaScript files. The extractor can now access both memory and disk-based JavaScript files.

fix(@angular/build): support reading on-disk files during i18n extraction

---

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts

Now that style elements within templates are processed as inline component styles, the style contents should only be considered CSS. This ensures consistent behavior prior to when style elements were processed. It also ensures that the styles will function as expected in JIT mode where template styles cannot be preprocessed and must be written in a browser supported language.

refactor(@angular/build): template style elements should always be CSS

---

packages/schematics/angular/workspace/files/tsconfig.json.template

The `declaration` TypeScript option has been removed from the default generated `tsconfig` for new projects. This option was explicitly set to `false`. However, the default value for the option is already `false`. Also, the `sourceMap` option has been removed. Source map generation is controlled by the build options and not the TypeScript configuration.

fix(@schematics/angular): remove `declaration` and `sourceMap` from default tsconfig

---

packages/angular/ssr/private_export.ts
packages/angular/ssr/src/app-engine.ts
packages/angular/ssr/src/app.ts
packages/angular/ssr/src/assets.ts
packages/angular/ssr/src/global.d.ts
packages/angular/ssr/src/manifest.ts
packages/angular/ssr/src/render.ts
packages/angular/ssr/src/routes/ng-routes.ts
packages/angular/ssr/test/app-engine_spec.ts
packages/angular/ssr/test/app_spec.ts
packages/angular/ssr/test/assets_spec.ts
packages/angular/ssr/test/testing-utils.ts

- Exposed several utility functions as private APIs to support the integration with the build system.
- Removed `isDevMode` and caching logic from `AngularAppEngine`. This was necessary to better handle updates when using Vite. Instead, `AngularServerApp` is now treated as a singleton to simplify management.
- Switched asset storage from an `Object` to a `Map` in the manifest for improved efficiency and consistency.
This refactor sets the groundwork for seamless wiring with the build system.

refactor(@angular/ssr): expose private APIs for build system integration and refactor app management

---

CHANGELOG.md

docs: release notes for the v18.2.1 release

---

goldens/public-api/angular_devkit/core/index.api.md
packages/angular_devkit/core/src/virtual-fs/host/buffer.ts

BREAKING CHANGE: The deprecated `fileBuffer` function is no longer available. Update your code to use `stringToFileBuffer` instead to maintain compatibility.
**Note:** that this change does not affect application developers.

refactor(@angular-devkit/core): remove deprecated `fileBuffer` function in favor of `stringToFileBuffer`

---

packages/angular_devkit/build_angular/BUILD.bazel

These server tests frequently fail due to timeouts. Despite efforts, the root cause has not yet been identified, so they are being marked as flaky to prevent blocking the pipeline while further investigation continues.

build: mark server tests as flaky

---

packages/angular/ssr/src/app.ts

The `resetAngularServerApp` method was identical to `destroyAngularServerApp` and was mistakenly retained due to an incorrect merge. This commit removes the redundant method.

refactor(@angular/ssr): remove duplicate `resetAngularServerApp` method

---

packages/angular/build/src/tools/esbuild/application-code-bundle.ts
packages/schematics/angular/migrations/migration-collection.json
packages/schematics/angular/migrations/update-workspace-config/migration.ts
packages/schematics/angular/migrations/update-workspace-config/migration_spec.ts

The logic that automatically added the `@angular/localize/init` polyfill has been removed.
BREAKING CHANGE: The `@angular/localize/init` polyfill will no longer be added automatically to projects. To prevent runtime issues, ensure that this polyfill is manually included in the "polyfills" section of your "angular.json" file if your application relies on Angular localization features.

refactor(@angular/build): remove automatic addition of `@angular/localize/init` polyfill and related warnings

---

goldens/public-api/angular_devkit/build_angular/index.api.md
modules/testing/builder/projects/hello-world-app/angular.json
packages/angular/build/src/builders/dev-server/tests/behavior/build-inline-critical-css_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/options.ts
packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/build-inline-critical-css_spec.ts
packages/angular_devkit/build_angular/src/builders/dev-server/tests/behavior/serve-live-reload-proxies_spec.ts
packages/angular_devkit/build_angular/src/builders/extract-i18n/options.ts
packages/angular_devkit/build_angular/src/builders/extract-i18n/schema.json
packages/schematics/angular/migrations/update-workspace-config/migration.ts
packages/schematics/angular/utility/workspace-models.ts
tests/legacy-cli/e2e/tests/i18n/setup.ts

The `browserTarget` option has been removed as part of the refactoring process. This option was part of a private API and is no longer used. Projects relying on this option should migrate to using the `buildTarget` option.
BREAKING CHANGE: The `browserTarget` option has been removed from the DevServer and ExtractI18n builders. `buildTarget` is to be used instead.

refactor(@angular-devkit/build-angular): remove deprecated `browserTarget`

---

packages/schematics/angular/application/index.ts

The 2kB/4kB warning/error thresholds for any component style within an application has now been increased to 4kB/8kB for warnings/errors respectively. This allows for more complex styles within a component while also reducing the likelihood of the budget rule being disabled or removed. The new limits still provide diagnostics for extreme size cases such as accidentally importing all Bootstrap or Material styles into an individual component. Such instances are a primary use case for the budget.

refactor(@schematics/angular): increase new application anyComponentSyle budget thresholds

---

tsconfig-build.json

The exclude field has been removed from `tsconfig-build.json` as it is redundant. This configuration is used by Bazel, which already specifies the input files explicitly, making the exclude field unnecessary. This change simplifies the configuration without impacting the build process.

build: clean up redundant `exclude` field from `tsconfig-build.json`

---

packages/angular/ssr/package.json
yarn.lock

This is a required peer dependency which was not listed.

fix(@angular/ssr): add missing peer dependency on `@angular/platform-server`

---

packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template
packages/schematics/angular/component/index_spec.ts
packages/schematics/angular/component/schema.json

added option for export class in default mode
Closes #25023
Issue Number: #25023
added option for export class in default mode. Example `ng g c foo --export-default=true`. This option will generate a component with default keyword: ... export default class ...

feat(@schematics/angular): add option to export component as default

---

packages/angular_devkit/build_angular/BUILD.bazel
packages/angular_devkit/build_angular/src/builders/server/tests/setup.ts

Attempting to reduce flaky tests.

test: disable `buildOptimizer` for server tests

---

packages/schematics/angular/server/index.ts
packages/schematics/angular/ssr/index.ts

This change is necessary as the `@angular/ssr` package is now required for all types of server-side rendering, including SSG and app-shell.
Context: https://github.com/angular/angular-cli/pull/28283

refactor(@schematics/angular): move `@angular/ssr` dependency to server schematic

---

packages/angular/ssr/BUILD.bazel

This update addresses an issue on Windows where rollup attempts to bundle the `@angular/ssr`as part of the `@angular/ssr/node` FESM. Additionally, `tslib` is removed from externals as it is already configured internally within `ng_package`. See: https://github.com/angular/angular/blob/76b9e2b836d050e9196253ae56d45a65466d9f57/packages/bazel/src/ng_package/ng_package.bzl#L106

build: prevent rollup from bundling `@angular/ssr` in `@angular/ssr/node`

---

goldens/circular-deps/packages.json
goldens/public-api/angular/ssr/index.api.md
packages/angular/ssr/private_export.ts
packages/angular/ssr/public_api.ts
packages/angular/ssr/src/app-engine.ts
packages/angular/ssr/src/manifest.ts

Added `AngularAppEngine` to the public API of `@angular/ssr`, allowing users to access it directly for enhanced server-side rendering functionality.

feat(@angular/ssr): export `AngularAppEngine` as public API

---

packages/angular/ssr/private_export.ts
packages/angular/ssr/src/routes/ng-routes.ts
packages/angular/ssr/src/routes/router.ts

This commit introduces a new utility function designed to extract routes and creating a corresponding route tree.
Context: https://github.com/angular/angular-cli/pull/28283

refactor(@angular/ssr): Add Utility Function for route extraction and tree creation

---

.prettierignore
goldens/public-api/angular_devkit/core/index.api.md
package.json
packages/angular/build/package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/core/src/utils/partially-ordered-set.ts
packages/angular_devkit/schematics/src/tree/action.ts
packages/ngtools/webpack/package.json
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts
yarn.lock

Updates the repo to the TypeScript 5.6 RC and narrows down the version to drop support for 5.4, in line with the compiler.

build: update to TypeScript 5.6 RC

---

.circleci/dynamic_config.yml
package.json
packages/angular_devkit/build_angular/package.json
packages/angular_devkit/build_angular/src/builders/browser/tests/options/named-chunks_spec.ts
packages/angular_devkit/build_angular/src/builders/browser/tests/options/stats-json_spec.ts
packages/angular_devkit/build_angular/src/tools/webpack/plugins/builder-watch-plugin.ts
packages/angular_devkit/build_angular/src/tools/webpack/plugins/common-js-usage-warn-plugin.ts
packages/angular_devkit/build_angular/src/tools/webpack/plugins/styles-webpack-plugin.ts
packages/ngtools/webpack/src/ivy/plugin.ts
packages/ngtools/webpack/src/ivy/system.ts
yarn.lock

Addresses security vulnerability detailed in https://github.com/advisories/GHSA-4vvj-4cpr-p986.
Closes #28292

fix(@angular-devkit/build-angular): upgrade webpack to `5.94.0`

---

CHANGELOG.md

docs: release notes for the v18.2.2 release

---

packages/angular_devkit/build_angular/src/builders/karma/index.ts
packages/schematics/angular/config/files/karma.conf.js.template

This works around https://github.com/angular/angular-cli/issues/28271.
(cherry picked from commit 3ee21631f481b2e72be2390b5a2cac74824efbb5)
This is an LTS patch of #28315 to v16.

fix(@angular-devkit/build-angular): clear context in Karma by default for single run executions

---

CHANGELOG.md

docs: release notes for the v16.2.15 release

---

CHANGELOG.md

docs: release notes for the v17.3.9 release

---

packages/schematics/angular/workspace/files/tsconfig.json.template

Newly generated projects will now no longer have an explicit `lib` option defined within the TypeScript configuration for the workspace (`tsconfig.json`). This option will default to the `target` option value plus `DOM`. This combination is the same as the explicit value set in a new project. Removing the explicit option value will result in equivalent behavior without the need to duplicate the ES version in two places.

refactor(@schematics/angular): remove explicit TypeScript lib option for new projects

---

packages/angular/ssr/package.json
packages/angular/ssr/test/BUILD.bazel
packages/angular/ssr/test/app-engine_spec.ts
packages/angular/ssr/test/app_spec.ts
packages/angular/ssr/test/assets_spec.ts
packages/angular/ssr/test/testing-utils.ts
yarn.lock

This commit updates the UT tests to zoneless.

test: update ssr UT to zoneless

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

This update contains a fix for `Error: Cannot set headers after they are sent to the client`. See: https://github.com/webpack/webpack-dev-middleware/blob/master/CHANGELOG.md#742-2024-08-21
Closes #28331

fix(@angular-devkit/build-angular): update `webpack-dev-middleware` to `7.4.2`

---

CHANGELOG.md

docs: release notes for the v18.2.3 release

---

packages/angular/build/src/tools/angular/compilation/parallel-compilation.ts
packages/angular/build/src/tools/esbuild/javascript-transformer.ts
packages/angular/build/src/tools/sass/sass-service.ts
packages/angular/build/src/typings.d.ts
packages/angular/cli/bin/bootstrap.js

The Angular CLI will now enable the Node.js compile cache when available for use. Node.js v22.8 and higher currently provide support for this feature. The compile cache stores the v8 intermediate forms of JavaScript code for the Angular CLI itself. This provides a speed up to initialization on subsequent uses the Angular CLI. The Node.js cache is stored in a temporary directory in a globally accessible location so that all Node.js instances of a compatible version can share the cache. The code cache can be disabled if preferred via `NODE_DISABLE_COMPILE_CACHE=1`.
Based on initial profiling, this change provides an ~6% production build time improvement for a newly generated project once the cache is available.
```
Benchmark 1: NODE_DISABLE_COMPILE_CACHE=1 node ./node_modules/.bin/ng build …
```

perf(@angular/cli): enable Node.js compile code cache when available

---

goldens/public-api/angular/ssr/index.api.md
goldens/public-api/angular/ssr/node/index.api.md
packages/angular/ssr/node/public_api.ts
packages/angular/ssr/node/src/app-engine.ts
packages/angular/ssr/private_export.ts
packages/angular/ssr/public_api.ts
packages/angular/ssr/src/app-engine.ts
packages/angular/ssr/src/manifest.ts
packages/angular/ssr/src/routes/route-config.ts
packages/angular/ssr/test/app-engine_spec.ts

**feat(@angular/ssr): Add `getHeaders` Method to `AngularAppEngine` and `AngularNodeAppEngine` for handling pages static headers**
This commit introduces a new `getHeaders` method to the `AngularAppEngine` and `AngularNodeAppEngine` classes, designed to facilitate the retrieval of HTTP headers based on URL pathnames for statically generated (SSG) pages.
```typescript
const angularAppEngine = new AngularNodeAppEngine();
app.use(express.static('dist/browser', {
setHeaders: (res, path) => {
// Retrieve headers for the current request
const headers = angularAppEngine.getHeaders(res.req);
// Apply the retrieved headers to the response
for (const { key, value } of headers) {
res.setHeader(key, value);
}
}
}));
```
In this example, the `getHeaders` method is used within an Express application to …

feat(@angular/ssr): add `getHeaders` method to `AngularAppEngine` and `AngularNodeAppEngine` for handling pages static headers

---

packages/angular/build/src/utils/server-rendering/manifest.ts
packages/angular/ssr/src/app.ts
packages/angular/ssr/src/manifest.ts
packages/angular/ssr/src/routes/ng-routes.ts
packages/angular/ssr/test/testing-utils.ts
tests/legacy-cli/e2e/tests/build/ssr/express-engine-csp-nonce.ts
tests/legacy-cli/e2e/tests/build/ssr/express-engine-ngmodule.ts
tests/legacy-cli/e2e/tests/build/ssr/express-engine-standalone.ts

The issue was addressed by changing the top-level import to a dynamic import.
Closes #28358

fix(@angular/ssr): resolve circular dependency issue from main.server.js reference in manifest

---

packages/angular/cli/BUILD.bazel
packages/angular/cli/src/command-builder/command-module.ts
packages/angular/cli/src/command-builder/utilities/json-schema.ts
packages/angular/cli/src/command-builder/utilities/json-schema_spec.ts

The values of `define` can only be updated by changing the Angular config file.
Issue Number: https://github.com/angular/angular-cli/issues/4318 (arguably)
Defines can now be introduced or changed by passing them to the CLI, e.g.:
```
ng build --define "BUILD_TIME=$(date)"
```
The PR also moves `addSchemaOptionsToCommand` to be colocated with `parseJsonSchemaToOptions`. The two functions are tightly coupled and it makes unit testing the schema-to-yargs flow a lot easier.

feat(@angular/cli): handle string key/value pairs, e.g. --define

---

packages/angular_devkit/schematics_cli/blank/project-files/package.json
packages/angular_devkit/schematics_cli/schematic/files/package.json
packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel
packages/schematics/angular/utility/latest-versions/package.json

Updates a few leftover places to the TypeScript 5.6 final version.

build: update all remaining places to TypeScript 5.6

---

packages/angular/build/src/tools/sass/worker.ts

This refactor resolves an issue where the inferred type of `renderSassStylesheet` required an external reference, which could affect portability.
Fixes the following error:
```
packages/angular/build/src/tools/sass/worker.ts:59:31 - error TS2742: The inferred type of 'renderSassStylesheet' cannot be named without a reference to '../../../../../../external/npm/node_modules/source-map-js/source-map'. This is likely not portable. A type annotation is necessary.
```
Explicit type annotation added to `renderSassStylesheet` function to prevent reliance on inferred types.
**Note:** Ensure compatibility with Windows Bazel builds.

refactor(@angular/build): add explicit type annotations to avoid inferred types

---

.eslintrc.json
package.json
packages/angular/build/src/builders/dev-server/vite-server.ts
packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular/build/src/tools/esbuild/i18n-inliner-worker.ts
packages/angular/build/src/tools/esbuild/stylesheets/css-inline-fonts-plugin.ts
packages/angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts
packages/angular/build/src/tools/esbuild/virtual-module-plugin.ts
packages/angular/build/src/tools/esbuild/wasm-plugin.ts
packages/angular/build/src/tools/sass/sass-service.ts
packages/angular/build/src/tools/sass/worker.ts
packages/angular/build/src/utils/index-file/augment-index-html.ts
packages/angular/build/src/utils/index-file/valid-self-closing-tags.ts
packages/angular/build/src/utils/normalize-cache.ts
packages/angular/cli/src/command-builder/command-module.ts
packages/angular/cli/src/commands/update/cli.ts
packages/angular/ssr/node/src/common-engine/common-engine.ts
packages/angular/ssr/src/routes/ng-routes.ts
packages/angular/ssr/src/routes/route-config.ts
packages/angular_devkit/architect/src/jobs/api.ts
packages/angular_devkit/build_angular/src/builders/app-shell/render-worker.ts
packages/angular_devkit/build_angular/src/tools/webpack/plugins/javascript-optimizer-worker.ts
packages/angular_devkit/build_angular/src/tools/webpack/plugins/postcss-cli-resources.ts
packages/angular_devkit/build_angular/src/utils/normalize-cache.ts
packages/schematics/angular/utility/dependency.ts
packages/schematics/angular/utility/workspace-models.ts
scripts/build-packages-dist.mts
yarn.lock

I often struggle with spacing around block comments, so I've decided to add the `lines-around-comment` lint rule to help manage this.
For more details, see the https://eslint.style/rules/js/lines-around-comment

refactor: Add `lines-around-comment` rule

---

packages/angular/build/src/builders/dev-server/vite-server.ts

This commit excludes Node.js module imports from being processed by Vite when prebundling is enabled.
Closes #28390

fix(@angular/build): prevent transformation of Node.js internal dependencies by Vite

---

packages/angular_devkit/architect/src/architect.ts
packages/angular_devkit/architect/src/options.ts
packages/angular_devkit/architect/src/options_spec.ts

We recently introduced the ability to pass object values from the command line (#28362). @clydin noticed that the initial behavior didn't work well for `--define`: It completely replaced all values even if just one of multiple defines is specified.
This updates the architect to support merging of object options. If both the base option (e.g. from `angular.json`) and the override (e.g. from a CLI `--flag`) are objects, the objects are merged.
See: https://github.com/angular/angular-cli/pull/28362
With multiple `define`s in `angular.json`, passing any define via the `--define` flag will ignore all existing defines.
Only defines specified via the `--define` flag …

feat(@angular-devkit/architect): merge object options from CLI

---

packages/angular/build/BUILD.bazel
packages/angular/build/package.json
packages/angular/build/src/builders/dev-server/vite-server.ts
packages/angular/build/src/tools/vite/angular-memory-plugin.ts
packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts
yarn.lock

The Vite-based development server now provides support for serving individual component stylesheets both with and without emulated view encapsulation. This capability is not yet used by the Angular runtime code. The ability to use external stylesheets instead of bundling the style content is an enabling capability primarily for automatic component style HMR features. Additionally, it has potential future benefits for development mode deferred style processing which may reduce the initial build time when using the development server. The application build itself also does not yet generate external stylesheets.

refactor(@angular/build): support dev server direct component style serving

---

goldens/public-api/angular/ssr/index.api.md
goldens/public-api/angular/ssr/node/index.api.md
packages/angular/ssr/node/src/app-engine.ts
packages/angular/ssr/src/app-engine.ts
packages/angular/ssr/src/manifest.ts

The `Readonly` mapped type only introduces the `readonly` modifier for each property, but `Map` has mutating methods like `clear`, `delete` and `set` that would still remain usable. This commit switches those usages over to the `ReadonlyMap` type which doesn't have any of the mutating methods.

refactor(ssr): use `ReadonlyMap` instead of `Readonly` mapped type

---

packages/angular/ssr/src/routes/ng-routes.ts

In cases where the application is not zoneless and async/await is downleveled, an issue occurred where `await` was not being downleveled correctly. This led to the `bootstrap is not a function` error.
See: https://github.com/angular/angular/actions/runs/10817795242/job/30014914340?pr=57776

fix(@angular/ssr): resolve `bootstrap is not a function` error

---

packages/angular/build/src/tools/angular/compilation/parallel-compilation.ts
packages/angular/build/src/tools/esbuild/javascript-transformer.ts
packages/angular/build/src/tools/sass/sass-service.ts
packages/angular/build/src/typings.d.ts
packages/angular/cli/bin/bootstrap.js

This reverts commit `ecc107d83bfdfd9d5dd1087e264892d60361625c`.
Passing a custom `process.env` to Piscina causes Bazel to fail, leading to path leaks and sandbox escapes.
As a result, `adev` builds encounter errors such as:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@angular/compiler-cli' imported from /home/runner/work/angular/angular/node_modules/@angular/build/src/utils/load-esm.js
```
Further investigation is needed to determine if this is a bug in Piscina or another underlying issue. For now, the change has been reverted to allow the FW repo to update to the latest version of the CLI packages.

Revert "perf(@angular/cli): enable Node.js compile code cache when available

---

packages/angular/build/src/tools/vite/angular-memory-plugin.ts
packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts
packages/angular/build/src/tools/vite/middlewares/headers-middleware.ts
packages/angular/build/src/tools/vite/middlewares/html-fallback-middleware.ts
packages/angular/build/src/tools/vite/middlewares/index-html-middleware.ts
packages/angular/build/src/tools/vite/middlewares/index.ts
packages/angular/build/src/tools/vite/middlewares/ssr-middleware.ts
packages/angular/build/src/tools/vite/utils.ts

Replaced multiple `appendServerConfiguredHeaders` calls with a single custom middleware to append headers to all responses, simplifying the code and ensuring consistency.

refactor(@angular/build): implement custom middleware for header appending

---

packages/angular/build/src/utils/server-rendering/prerender.ts
packages/angular/build/src/utils/server-rendering/routes-extractor-worker.ts
packages/angular/ssr/node/src/app-engine.ts
packages/angular/ssr/src/routes/ng-routes.ts
packages/angular/ssr/src/routes/route-tree.ts
packages/angular/ssr/src/routes/router.ts
packages/angular/ssr/src/utils/url.ts
packages/angular/ssr/test/app-engine_spec.ts
packages/angular/ssr/test/app_spec.ts
packages/angular/ssr/test/routes/ng-routes_spec.ts
packages/angular/ssr/test/routes/router_spec.ts
packages/angular/ssr/test/utils/url_spec.ts

This commit introduces the following changes:
- Disallows paths starting with a slash to match Angular router behavior.
- Errors are now stored and displayed at a later stage, improving UX by avoiding unnecessary stack traces that are not useful in this context.

fix(@angular/ssr): correct route extraction and error handling

---

goldens/public-api/angular/ssr/node/index.api.md
packages/angular/ssr/node/public_api.ts
packages/angular/ssr/node/src/module.ts

Adds a new function `isMainModule` that checks if the current module is the main entry point of the application.
This is useful to ensure that server listener handlers are only registered when the module is executed directly and not when it's imported as a dependency such as the dev-server. This prevents potential issues with multiple listeners being registered unintentionally.

feat(@angular/ssr): add `isMainModule` function

---

package.json
packages/angular/build/package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

Includes a fix for CVE-2024-45812 / CVE-2024-45811
Closes #28435

fix(@angular/build): update vite to `5.4.6`

---

packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts
tests/legacy-cli/e2e/tests/commands/serve/head-request.ts
tests/legacy-cli/e2e/tests/i18n/extract-ivy.ts

When using the development server, HTTP HEAD requests will now correctly respond for the virtual output files generated from the Angular build system.  Previously Vite only handled GET requests for the files. While HEAD requests are not common in development workflows, it can be needed in more complex cases with additional servers/proxies/etc. during development.

fix(@angular/build): support HTTP HEAD requests for virtual output files

---

package.json
packages/angular_devkit/build_angular/package.json
yarn.lock

Includes a fix for CVE-2024-45812 / CVE-2024-45811
Closes angular#28435

fix(@angular-devkit/build-angular): update vite to 4.5.5

---

CHANGELOG.md

docs: release notes for the v16.2.16 release

---

CHANGELOG.md

docs: release notes for the v18.2.5 release

---

packages/angular/build/src/tools/vite/middlewares/html-fallback-middleware.ts

If a HTTP request is made to the development server that explicitly requests an HTML file (i.e., `/abc.html`), the development server will now attempt to fallback to the root `index.html` file if the requested HTML file does not exist. Since this may indicate a defect or other application misconfiguration such as a missing asset, a warning will also be issued in the console during development to notify the developer that something may be wrong.

fix(@angular/build): allow missing HTML file request to fallback to index

---

packages/schematics/angular/server/index.ts
packages/schematics/angular/server/index_spec.ts

Event Replay is now stable (see https://github.com/angular/angular/pull/57895). This commit adds `withEventReplay()` to the `provideClientHydration()` call in newly created Angular applications with SSR.

feat(@schematics/angular): integrate `withEventReplay()` in `provideClientHydration` for new SSR apps

---

tests/legacy-cli/e2e/tests/commands/add/base.ts

Instead of attempting to delete all files within the directory, the created symlink can instead be removed on its own. This should prevent odd Windows failures in CI.

test: unlink symlink in ng add base E2E test

---

packages/angular/build/src/utils/server-rendering/prerender.ts
tests/legacy-cli/e2e/tests/server-rendering/server-routes-output-mode-static.ts

Updated the build process to exclude catch-all routes from being prerendered.

fix(@angular/build): prevent prerendering of catch-all routes

---

packages/angular/build/src/builders/application/options.ts
packages/angular/build/src/builders/dev-server/vite-server.ts
packages/angular/build/src/tools/angular/angular-host.ts
packages/angular/build/src/tools/angular/compilation/angular-compilation.ts
packages/angular/build/src/tools/angular/compilation/aot-compilation.ts
packages/angular/build/src/tools/angular/compilation/parallel-compilation.ts
packages/angular/build/src/tools/angular/compilation/parallel-worker.ts
packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular/build/src/tools/esbuild/angular/component-stylesheets.ts
packages/angular/build/src/tools/esbuild/cache.ts
packages/angular/build/src/tools/esbuild/compiler-plugin-options.ts
packages/angular/build/src/utils/environment-options.ts

To support automatic component style HMR, `application` builder in development mode now provides support for generating external runtime component stylesheets. This capability leverages the upcoming support within the AOT -compiler to emit components that generate `link` elements instead of embedding the stylesheet contents for file-based styles (e.g., `styleUrl`). In combination with support within the development server to handle requests for component stylesheets, file-based component stylesheets will be able to be replaced without a full page reload.
The implementation leverages the AOT compiler option `externalRuntimeStyles` which uses the result of the resource handler's resolution and emits new external stylesheet metadata within the component output code. This new metadata works …

refactor(@angular/build): support external runtime component stylesheets in application builder

---

CHANGELOG.md

docs: release notes for the v17.3.10 release

---

goldens/public-api/angular/ssr/index.api.md
packages/angular/ssr/public_api.ts
packages/angular/ssr/src/tokens.ts

This commit exports that the `RESPONSE_INIT`, `REQUEST`, and `REQUEST_CONTEXT` tokens.

fix(@angular/ssr): export `RESPONSE_INIT`, `REQUEST`, and `REQUEST_CONTEXT` tokens

---

packages/angular_devkit/build_angular/BUILD.bazel
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/code-coverage_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/errors_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/module-cjs_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/rebuilds_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/assets_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage-exclude_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/exclude_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/include_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/styles_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/web-worker-tsconfig_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/setup.ts

Runs all existing karma tests twice: Once in an environment that uses the application builder and once in one that uses the browser builder. The general approach is taken from the dev server tests.
This is in preparation for supporting the application builder for karma tests.
All karma builder-related tests are run twice: Once in a harness that includes a "browser" development builder and once with a "application" development builder.

test(@angular-devkit/build-angular): add application/browser test runs

---

CHANGELOG.md

docs: release notes for the v18.2.6 release

---

packages/angular/build/src/utils/index-file/valid-self-closing-tags.ts

The `<animate>` tag, used for SVG animations, was incorrectly treated as a non-self-closing tag by the Angular build process. This resulted in errors during the build, as the parser expected a closing `</animate>` tag even when unnecessary.
Closes #28502

fix(@angular/build): add `animate` to valid self-closing elements

---

packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts

The `@angular/compiler` package now has an updated `encapsulateStyle` helper
that allows directly providing the component identifier as an argument.
This avoids needing to perform an additional regular expression replace
with the internal marker text.

refactor(@angular/build): use new encapsulate style helper for HMR

---

packages/angular/build/src/utils/server-rendering/manifest.ts

See: https://github.com/angular/angular-cli/security/code-scanning/74

refactor(@angular/build): improve HTML Code Sanitization in Manifest

---

packages/angular/ssr/src/app-engine.ts

If multiple concurrent requests hit `getEntryPointExports`, all of
them would previously see the cache miss for entry point. With this
change, only the first request will and the others can leverage the
cache.
This can be important when instances are added to a pool under high
traffic.

perf(@angular/ssr): prevent potential stampede in entry-points cache

---

packages/schematics/angular/workspace/files/__dot__editorconfig.template

The editorConfig generated by `ng new` specified `quote_type = single` for ts files. This is not a valid configuration option within editorConfig, instead editor could use it, but AFAIK no one utilizes this (https://github.com/editorconfig/editorconfig-vscode/issues/95). JetBrains IDEs have the option with the `ij_` prefix to set custom settings, and `ij_use_double_quote=false` will lead to autogenerated code (e.g. autoimports) to use single quotes
JetBrains IDEs will use single quotes by default

feat(editorconfig): support single quote setting in JetBrains IDEs

---

goldens/public-api/angular_devkit/build_angular/index.api.md
modules/testing/builder/projects/hello-world-app/karma.conf.js
packages/angular_devkit/build_angular/BUILD.bazel
packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts
packages/angular_devkit/build_angular/src/builders/karma/browser_builder.ts
packages/angular_devkit/build_angular/src/builders/karma/find-tests-plugin.ts
packages/angular_devkit/build_angular/src/builders/karma/find-tests.ts
packages/angular_devkit/build_angular/src/builders/karma/index.ts
packages/angular_devkit/build_angular/src/builders/karma/init_test_bed.js
packages/angular_devkit/build_angular/src/builders/karma/schema.json
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/code-coverage_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/rebuilds_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/builder-mode_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage-exclude_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/styles_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/web-worker-tsconfig_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/setup.ts
packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/karma.conf.js

`ng test` for projects that are using Karma has a hard dependency on the webpack builder. Apps can't use application builder features in any files loaded in the tests, really.
Apps can opt into using the application builder by setting the `builderMode` for the karma builder to either "application" or "detect". The latter only works if they switched the app to the new builder for their development/production builds. Once they do, we will use the new application builder toolchain to build their tests before running them in Karma.
This PR builds on top of https://github.com/angular/angular-cli/pull/28479. The "meat" is in the [last …

feat(@angular-devkit/build-angular): support karma with application builder

---

packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/code-coverage_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/errors_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/module-cjs_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/rebuilds_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/assets_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/builder-mode_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage-exclude_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/exclude_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/include_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/styles_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/web-worker-tsconfig_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/setup.ts

In the v19 application builder, the localize polyfill should not be added implicitly.
See: https://github.com/angular/angular-cli/commit/d6a34034d7489c09753090642ade4c606cd98ece
1. Test: Reference `./src/polyfills.ts` in the base options so we have an easy way to inject the polyfill based on which builder is used.
2. Test: Make the `setupTarget` function async so we can write to the polyfills file as part of the setup.
3. Builder: Remove the code in the application-builder based Karma support to inject localize.

refactor(@angular-devkit/build-angular): remove implicit localize polyfill

---

packages/angular/ssr/src/routes/ng-routes.ts
packages/angular/ssr/src/routes/route-tree.ts
packages/angular/ssr/test/routes/ng-routes_spec.ts

fix(@angular/ssr): show error when multiple routes are set with `RenderMode.AppShell`**
This change introduces error handling to ensure that when multiple routes are configured with `RenderMode.AppShell`, an error message is displayed. This prevents misconfiguration and enhances clarity in route management.
---
**fix(@angular/ssr): improve handling of route mismatches between Angular server routes and Angular router**
This commit resolves an issue where routes defined in the Angular server routing configuration did not match those in the Angular router. Previously, discrepancies between these routes went unnoticed by users. With this update, appropriate error messages are now displayed when mismatches occur, enhancing the developer experience and facilitating easier troubleshooting.

fix(@angular/ssr): improve handling of route mismatches between Angular server routes and Angular router

---

packages/angular/build/package.json
packages/angular/build/src/builders/application/options.ts
packages/angular/build/src/tools/babel/plugins/add-code-coverage.ts
packages/angular/build/src/tools/babel/plugins/types.d.ts
packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular/build/src/tools/esbuild/compiler-plugin-options.ts
packages/angular/build/src/tools/esbuild/javascript-transformer-worker.ts
packages/angular/build/src/tools/esbuild/javascript-transformer.ts
packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/code-coverage_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage-exclude_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/code-coverage_spec.ts
yarn.lock

* The additions in `packages/angular/build/src/tools/babel/plugins/*` are 1:1 copies of files already present in `packages/angular_devkit/build_angular/src/tools/babel/plugins/*`. I couldn't find a clean way to prevent that. Either @angular/build have to expose the plugin in `package.json#exports` or it would have to depend on @angular-devkit/build-angular. Both seemed undesirable.
* The logic for excluding files from coverage is lifted from the [equivalent webpack config](https://github.com/angular/angular-cli/blob/ecfb2b261356946d5f4a653f90c0b78db4ef519c/packages/angular_devkit/build_angular/src/tools/webpack/configs/common.ts#L424-L429). Given the state of Karma, I didn't make an effort to refactor the code to share the logic - I assume we don't expect many changes here. That would …

feat(@angular-devkit/build-angular): karma-coverage w/ app builder

---

packages/angular/build/src/utils/server-rendering/manifest.ts

See: https://github.com/angular/angular-cli/security/code-scanning/76

fix(@angular/build): incomplete string escaping or encoding

---

packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/fake-async_spec.ts

Previously, the testing module was split into its own entrypoint but then never loaded. Now it's just left in the overall polyfill bundle.
The bug wasn't caught by the existing test coverage, so this adds a new test that ensures that fakeAsync works.
Cleaning up the Karma `files` list also removes the noisy "no file matched the pattern worker-*.js" warnings that were previously generated for test suites that don't include web worker sources.

fix(@angular-devkit/build-angular): zone.js/testing + karma + esbuild

---

packages/angular/ssr/src/app.ts
packages/angular/ssr/src/utils/crypto.ts
packages/angular/ssr/src/utils/lru-cache.ts
packages/angular/ssr/test/utils/lru_cache_spec.ts
tests/legacy-cli/e2e/tests/server-rendering/server-routes-output-mode-server-i18n-base-href.ts
tests/legacy-cli/e2e/tests/server-rendering/server-routes-output-mode-server-i18n.ts
tests/legacy-cli/e2e/tests/server-rendering/server-routes-output-mode-server.ts

Implement LRU cache for inlined CSS in server-side rendered HTML. 
This optimization significantly improves server-side rendering performance by reusing previously inlined styles and reducing the overhead of repeated CSS inlining.
Performance improvements observed:
* **Latency:** Reduced by ~18.1% (from 1.01s to 827.47ms)
* **Requests per Second:** Increased by ~24.1% (from 381.16 to 472.85)
* **Transfer per Second:** Increased by ~24.1% (from 0.87MB to 1.08MB) 
These gains demonstrate the effectiveness of caching inlined CSS for frequently accessed pages, resulting in a faster and more efficient user experience.
___
**Edit**:  Previously the numbers were calculated not using the Average but the Max.

perf(@angular/ssr): cache generated inline CSS for HTML

---

packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/rebuilds_spec.ts

This introduces support for `--watch` when using the application builder. It's tested as far as the relevant test case is concerned. But I wouldn't be surprised if there's still some rough corners.
~~**NOTE:** Currently includes the commit from https://github.com/angular/angular-cli/pull/28518 because the two touch some of the same code.~~ Rebased.

feat(@angular-devkit/build-angular): karma+esbuild+watch

---

packages/angular/build/src/tools/vite/middlewares/ssr-middleware.ts
packages/angular/build/src/utils/server-rendering/fetch-patch.ts
packages/angular/build/src/utils/server-rendering/launch-server.ts
packages/angular/build/src/utils/server-rendering/load-esm-from-memory.ts
packages/angular/build/src/utils/server-rendering/prerender.ts
packages/angular/build/src/utils/server-rendering/render-worker.ts
packages/angular/build/src/utils/server-rendering/routes-extractor-worker.ts
packages/angular/build/src/utils/server-rendering/utils.ts
tests/legacy-cli/e2e/tests/server-rendering/server-routes-output-mode-static-http-calls.ts

The server.ts file is now utilized during prerendering, allowing access to locally defined API routes for improved data fetching and rendering.

 feat(@angular/build): utilize `ssr.entry` during prerendering to enable access to local API routes     

---

packages/angular/build/src/builders/dev-server/vite-server.ts

The `ViteServer` instance's `hot` field is deprecated and will eventually be removed. The `ws` field can be used in its place.

refactor(@angular/build): remove deprecated Vite node server hot field usage

---

packages/angular/build/src/builders/dev-server/vite-server.ts

Previously, Vite prebundled dependencies were stored in a shared directory across all projects, which caused the `_metadata.json` files to be overwritten. This resulted in undefined behavior, such as re-optimizing dependencies on each run when multiple projects were present in the workspace. Additionally, it introduced conflicts when running multiple `ng serve` processes simultaneously.
Closes #28536

fix(@angular/build): separate Vite cache by project

---

CHANGELOG.md

docs: release notes for the v18.2.7 release

---

packages/angular/build/src/builders/dev-server/vite-server.ts
packages/angular/build/src/tools/vite/middlewares/ssr-middleware.ts

This commit activates ssr in the Vite when prerendering is disabled internally.
Closes #28523

refactor(@angular/build): enable SSR when disabling Prerendering in Vite

---

packages/angular/build/src/utils/index-file/index-html-generator.ts
packages/angular/build/src/utils/index-file/ngcm-attribute.ts
packages/angular/build/src/utils/index-file/ngcm-attribute_spec.ts

With the introduction of the `RenderMode` configuration for routes, some routes may be set to `RenderMode.Client` while still including the `provideClientHydration()` function in the provider list during bootstrap. This led to a false-positive warning in the console, incorrectly suggesting a hydration misconfiguration.
This commit introduces a DOM marker that allows the framework to bypass these unnecessary checks, preventing the misleading warnings.
See: https://github.com/angular/angular/pull/58004

refactor(@angular/build): avoid hydration warnings when `RenderMode.Client` is set

---

packages/angular_devkit/build_angular/src/utils/tailwind.ts
packages/angular_devkit/schematics/src/rules/base.ts

The upcoming version of typescript Eslint rules will fail the `await-thenable`
rule for cases of for await...of that use promise arrays. This change
removes the usage to avoid lint failures during the version update.
Ref: https://typescript-eslint.io/rules/await-thenable/#async-iteration-for-awaitof-loops
Unblocks: #28534

Avoid `for await...of` with promise arrays

---

packages/angular/ssr/src/app.ts
packages/angular/ssr/src/utils/crypto.ts

This update changes the handling of the crypto unavailable error in the Angular SSR environment. Instead of throwing a hard error, which could interrupt the application flow, the error is now treated as a soft error

refactor(@angular/ssr): Convert crypto unavailable error to a soft error

---

modules/testing/builder/src/jasmine-helpers.ts
packages/angular/build/src/builders/dev-server/tests/options/watch_spec.ts

To reduce duplicate code within tests for rebuild/watch scenarios, a new helper has been added to the builder test harness.  This helper allows passing in an array of test case functions that are executed in order per rebuild. The development server's watch option tests have been updated to use the new helper.

test(@angular/build): add test harness rebuild case helper function

---

packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/fake-async_spec.ts
packages/angular_devkit/build_angular/src/builders/karma/tests/options/main_spec.ts

1. Move `init_test_bed.js` to the end of polyfills to ensure it always runs before any of the test chunks.
2. Add source maps to served files and only add `worker-*` and `chunk-*` files if there are any. This is meant to reduce the number of warnings Karma logs. In practice any non-trivial app should have _some_ `chunk-*` files for their test suite.
3. If `options.main` is provided, use that file instead of the default `init_test_bed.js`.
4. Add a new test that prevent future regressions with handling of the `main` option.

fix(@angular-devkit/build-angular): handle main field

---

packages/angular/build/src/builders/application/chunk-optimizer.ts

Rollup chunk optimizer preserves file name hashes from esbuild and doesn't add a new hash for these files 
Issue Number: [28569](https://github.com/angular/angular-cli/issues/28569)
Rollup chunk optimizer always adds a new hash to the filename. Hash from esbuild is removed

fix(@angular/build): always generate a new hash for optimized chunk

---

packages/angular/build/src/builders/application/build-action.ts

The application builder performs fine-grained file watching now which removes the need to watch the project root by default as it did in early implementations. As a result, the need to ignore the `node_modules` directory is not longer necessary by default and is only needed when the `NG_BUILD_WATCH_ROOT` environment variable is enabled.

refactor(@angular/build): only ignore watching node modules when watching root

---

packages/angular/build/src/utils/server-rendering/prerender.ts

Handle cases where the error stack is missing by displaying a relevant message.
Closes #28590

fix(@angular/build): show error message when error stack is undefined

---

packages/angular/build/src/builders/application/options.ts
tests/legacy-cli/e2e/tests/build/prerender/discover-routes-ngmodule.ts

This commit addresses an issue where `index.csr.html` was not being generated when SSR was disabled and prerendering was enabled.
Closes #28580

fix(@angular/build): ensure `index.csr.html` is always generated when prerendering or SSR are enabled

---

packages/angular/build/src/builders/dev-server/vite-server.ts

This commit provides a workaround for https://github.com/angular/angular-cli/issues/28336, which occurs due to the interaction between `zone.js` and `listr2`. The issue prevents proper termination of the development server using Ctrl + C when dev-server.
Closes: #28336

fix(@angular/build): `Ctrl + C` not terminating dev-server with SSR

---

packages/angular/build/src/builders/dev-server/vite-server.ts

Patch version of https://github.com/angular/angular-cli/pull/28604

[backport] fix(@angular/build): `Ctrl + C` not terminating dev-server with SSR

---

packages/angular/build/package.json
yarn.lock

A warning mechanism has been implemented to notify users when lmdb is unavailable. On Windows ARM64 systems, however, installing this package with pnpm appears to cause installation failures.
See: https://github.com/angular/angular-cli/issues/27882#issuecomment-2395029997
Closes #27882

fix(@angular/build): move lmdb to optionalDependencies

---

CHANGELOG.md

docs: release notes for the v18.2.8 release

---

modules/testing/builder/src/dev_prod_mode.ts
packages/angular/build/src/builders/application/tests/behavior/build-conditions_spec.ts
packages/angular/build/src/builders/dev-server/tests/behavior/build-conditions_spec.ts
packages/angular/build/src/tools/esbuild/application-code-bundle.ts
packages/angular/build/src/tools/esbuild/global-scripts.ts
packages/angular/build/src/tools/esbuild/stylesheets/bundle-options.ts

Ensures that conditional exports/imports work as intended in `ng serve` and `ng build`:
1. For optimized builds, the "production" condition is enabled.
2. For non-optimized builds, the "development" condition is enabled.
This allows quick conditional logic like the following to work as expected:
```ts
import {verboseLogging} from '#logger';
```
The file can be switched in the `imports` field in `package.json`:
```js
// ...
"imports": {
"#logger": {
"development": "./src/logging/debug.ts",
"default": "./src/logging/noop.ts"
}
},
```
Something similar already (and continues to) work for SSR vs browser code.
The difference can be expressed using the "browser" condition:
```js
// ...
"imports": {
"#crashReporter": {
"browser": "./src/crash/sendBeacon.ts",
"default": …
```

feat(@angular/build): set development/production condition

---

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular/build/src/tools/esbuild/angular/component-stylesheets.ts
packages/angular/build/src/tools/esbuild/angular/jit-plugin-callbacks.ts

The configured inline style language for Angular components is now set during the construction of the component stylesheet bundler. This avoids needing to repeatedly pass the value into each inline bundling call. The ability to customize the language per call is retained to allow individual style control if needed.

refactor(@angular/build): reduce inline style language value per call usage

---

packages/angular/build/src/tools/vite/middlewares/ssr-middleware.ts
packages/angular/build/src/utils/server-rendering/launch-server.ts
packages/angular/build/src/utils/server-rendering/load-esm-from-memory.ts
packages/schematics/angular/ssr/files/application-builder/server.ts.template
tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-server-platform-neutral.ts
tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-static-http-calls.ts
tests/legacy-cli/e2e/tests/vite/ssr-entry-express.ts
tests/legacy-cli/e2e/tests/vite/ssr-entry-fastify.ts
tests/legacy-cli/e2e/tests/vite/ssr-entry-h3.ts
tests/legacy-cli/e2e/tests/vite/ssr-entry-hono.ts

Some cloud providers, such as Cloudflare, expect the default export to follow a specific structure (e.g., an object with a `fetch` property). To prevent the need for creating a separate `server.ts` file for production builds, the request handler is now exported as `reqHandler` instead of a default export.

fix(@angular/build): use named export `reqHandler` for server.ts request handling

---

modules/testing/builder/projects/hello-world-app/README.md
packages/schematics/angular/workspace/files/README.md.template
tests/legacy-cli/e2e/assets/15.0-project/README.md
tests/legacy-cli/e2e/assets/18-ssr-project-webpack/README.md
tests/legacy-cli/e2e/assets/19-ssr-project-webpack/README.md

Improve the Code scaffolding section.
Code scaffolding section is updated a while ago and new commands associated with `ng generate` is not included. Only a subset of available schematics is documented in this section.
Issue Number: #28059 
This PR updates the code scaffolding section to inform users about the various commands available with `ng generate`, such as `ng generate component`.
Since the list of commands may evolve in the future, it's best to guide developers to use the `--help` option with `generate`. The documentation is now rewritten to highlight the use of `ng generate --help` for accessing the most up-to-date list of commands.

docs(@schematics/angular): update code scaffolding doc to with `ng generate --help`

---

renovate.json

Express version 5 is still in beta, but the types are incorrectly marked as the latest version.

ci: disable auto-updates for `@types/express`

---

packages/angular/build/src/utils/supported-browsers.ts
packages/schematics/angular/config/files/.browserslistrc.template

Adding a small change to the default browserslist
The command `ng g config browserslist` is not showing `last 2 Android major versions` in the `.browserslistrc` file. 
Issue Number: #26834 
The command `ng g config browserslist` will start to show `last 2 Android major versions` in the `.browserslistrc` file.

fix:@schematics/angular update browserslist config to include last 2 Android major versions

---

packages/angular/build/src/builders/application/results.ts
packages/angular/build/src/builders/dev-server/tests/behavior/component-updates_spec.ts
packages/angular/build/src/builders/dev-server/vite-server.ts
packages/angular/build/src/tools/vite/middlewares/component-middleware.ts
packages/angular/build/src/tools/vite/middlewares/index.ts
packages/angular/build/src/tools/vite/plugins/setup-middlewares-plugin.ts

An additional development server middleware has been added that responds to client `/@ng/component` requests from the Angular framework for hot component template updates. These client requests are made by the framework after being triggered by the development server sending a `angular:component-update` WebSocket event. The Angular compiler's new internal `_enableHmr` option will emit template replacement and reloading code that uses this new development server update middleware. Within the development server, the component update build result will be used to indicate that an event should be sent to active clients. The build system does not yet generate component update results.

refactor(@angular/build): add component update middleware to development server

---

packages/angular/build/src/tools/sass/worker.ts

Issue Number: #27167
Builds under load sometimes fail with "Can't find stylesheet to import" errors.
I was able to reproduce this error in my CI pipeline consistently, by running 4 `npx ng build` builds in parallel on an 8 core VPS. It also occurs sometimes during regular builds/`ng test`, especially when other concurrent jobs put load on the system.
By adding lots and lots of logging, I found the root cause, which is a race condition when the sass worker manages to call `findFileUrl` again in between `Atomics.store(..., 0, 1)` and `Atomics.notify(..., 0)` invocations - I left more details as a comment.
The race no longer causes failing builds. After being notified, the worker …

fix(@angular/build): avoid race condition in sass importer

---

modules/testing/builder/src/dev_prod_mode.ts
packages/angular/build/src/builders/application/tests/behavior/build-conditions_spec.ts
packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts

To improve type-checking and reduce hard to diagnose errors when using the new `production`/`development` conditions, the set of conditions used by the bundler are now also synchronized with those used by TypeScript. This helps ensure that type mismatches are avoided by type-checking against the actual file that will be bundled into the output.

fix(@angular/build): synchronize import/export conditions between bundler and TypeScript

---

packages/angular/build/src/builders/application/schema.json
packages/angular/build/src/builders/application/tests/options/style-preprocessor-options-sass_spec.ts
packages/angular/build/src/tools/esbuild/compiler-plugin-options.ts
packages/angular/build/src/tools/esbuild/global-styles.ts
packages/angular/build/src/tools/esbuild/stylesheets/bundle-options.ts
packages/angular/build/src/tools/esbuild/stylesheets/sass-language.ts
packages/angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts

This commit introduces the functionality to configure a limited number of options for Sass processing in the Angular application builder. The following options have been added to enhance the Sass integration:
- **futureDeprecations**: Specifies features that are scheduled for deprecation. The compiler will treat these as active and emit warnings as necessary.
- **fatalDeprecations**: Identifies Sass features that are already deprecated and will cause build failures if used.
- **silenceDeprecations**: This option suppresses deprecation warnings for specified versions.
Usage example:
```json
"architect": {
"build": {
"builder": "@angular-devkit/build-angular:application",
"options": {
"outputHashing": "none",
"namedChunks": true,
"stylePreprocessorOptions": {
"sass": {
"futureDeprecations": …
```

feat(@angular/build): add `sass` to `stylePreprocessorOptions` in application builder

---

packages/angular/build/src/builders/application/tests/behavior/typescript-isolated-modules_spec.ts
packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts

When using the application builder with `isolatedModules`, the bundler will directly handle TypeScript transpilation and bundling. Previously, any input TSX files were loaded by the bundler as TS files. This difference caused errors when attempting to process the files since the syntax differs between TSX and TS. The appropriate loader will now be used if the input file is TSX in this situation.
Closes #28640

fix(@angular/build): allow direct bundling of TSX files with application builder

---

packages/angular/build/package.json
packages/angular/build/src/builders/dev-server/vite-server.ts
packages/angular/build/src/tools/angular/angular-host.ts
packages/angular/build/src/tools/angular/compilation/parallel-compilation.ts
packages/angular/build/src/tools/angular/compilation/parallel-worker.ts
packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular/build/src/tools/esbuild/utils.ts
packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts
packages/angular/build/src/tools/vite/plugins/setup-middlewares-plugin.ts
packages/angular/build/src/utils/environment-options.ts
tests/legacy-cli/e2e/assets/19-ssr-project-webpack/src/app/app.component.ts
tests/legacy-cli/e2e/tests/basic/rebuild.ts
yarn.lock

When using the `application` builder (default for new projects) with the development server, component style only changes will now automatically replace the styles within the running application without a full reload of the page. No application code changes are necessary and both file-based (`styleUrl`/`styleUrls`) and inline (`styles`) component styles are supported. Within a component template, `<style>` elements and `<link rel="stylesheet">` elements with relative `href` attributes are also supported.
If any issues are encountered or it is preferred to not hot replace component styles, the `NG_HMR_CSTYLES=0` environment variable can be used to disable the feature. Setting the `liveReload` option to false will also disable all updates.

feat(@angular/build): enable component stylesheet hot replacement by default

---

CHANGELOG.md

docs: release notes for the v18.2.9 release

---

packages/schematics/angular/application/files/module-files/src/app/app.component.spec.ts.template
packages/schematics/angular/application/files/standalone-files/src/app/app.component.spec.ts.template
packages/schematics/angular/application/files/standalone-files/src/app/app.config.ts.template

The experimental zoneless feature introduces some spacing issues in the generated code: see https://github.com/cexbrayat/angular-cli-diff/compare/19.0.0-next.10...19.0.0-next.11
THis hopefully fixes these issues

refactor(@schematics/angular): spacing fixes after experimental zoneless introduction

---

packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts

The number of digits in the component identifier that is generated at runtime can vary. The check for a valid identifier now accounts for this case.
Closes: #28656

fix(@angular/build): relax constraints on external stylesheet component id

---

packages/angular/build/src/utils/index-file/html-rewriting-stream.ts

The `StartTag` and `EndTag` types are now also exported along with the `htmlRewritingStream` factory. These types are commonly used with the rewriter and by exporting them reduces the need to manually extract them from the underlying methods.

refactor(@angular/build): add helper types to internal HTML rewriter

---

packages/angular/ssr/src/app-engine.ts
tsconfig-build-ng.json

This removes `useDefineForClassFields` to leave static field instead of using static blocks.

refactor(@angular/ssr): remove `useDefineForClassFields`

---

goldens/circular-deps/packages.json
packages/angular/build/src/builders/application/execute-build.ts
packages/angular/build/src/builders/application/setup-bundling.ts
packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
packages/angular/build/src/tools/esbuild/application-code-bundle.ts
packages/angular/build/src/tools/esbuild/bundler-execution-result.ts
packages/angular/build/src/tools/esbuild/compiler-plugin-options.ts
packages/angular/build/src/utils/server-rendering/manifest.ts

**refactor(@angular/build): move component stylesheet bundler out of compiler plugin**
The component stylesheet bundler is now created during the setup of the Angular
compiler plugin options. This is an initial step to support more fine-grained
rebuild actions with the new component stylesheet development server support.
**refactor(@angular/build): create component stylesheet bundler at start of build**
The component stylesheet bundler is now created at the start of the build
and accessible prior to the bundling actions. This will provide support for
generating updated component styles and bypassing all code bundling when using
the development server and only component styles have been modified.

refactor(@angular/build): create component stylesheet bundler at start of build

---

modules/testing/builder/projects/hello-world-app/angular.json
packages/angular/cli/lib/config/workspace-schema.json
packages/angular_devkit/build_angular/builders.json
packages/angular_devkit/core/src/workspace/json/test/angular.json
packages/angular_devkit/core/src/workspace/json/test/cases/AddProject2.json
packages/angular_devkit/core/src/workspace/json/test/cases/AddProject3.json
packages/angular_devkit/core/src/workspace/json/test/cases/ProjectAddTarget.json
packages/angular_devkit/core/src/workspace/json/test/cases/ProjectDeleteTarget.json
packages/angular_devkit/core/src/workspace/json/test/cases/ProjectModifyProperties.json
packages/angular_devkit/core/src/workspace/json/test/cases/ProjectSetProperties.json
packages/schematics/angular/collection.json
packages/schematics/angular/e2e/index_spec.ts
packages/schematics/angular/utility/workspace-models.ts
tests/legacy-cli/e2e/tests/build/jit-ngmodule.ts
tests/legacy-cli/e2e/tests/build/server-rendering/express-engine-ngmodule.ts
tests/legacy-cli/e2e/tests/update/update.ts
tests/legacy-cli/e2e/utils/project.ts

This renames the Protractor builder and its `e2e` generator schematic to mark them private and remove them from Angular's public API. This will give us an opportunity to clean up internal usages and then remove the builder altogether in a future release. Since this rename makes Protractor non-public API, it may be completely deleted in a future patch release.
Protractor was [marked end-of-life in August 2023](https://protractortest.org/). Projects still relying on Protractor should consider migrating to another E2E testing framework, several support solid migration paths from Protractor.
Additional resources:
* https://angular.dev/tools/cli/end-to-end
* https://blog.angular.dev/the-state-of-end-to-end-testing-with-angular-d175f751cb9c

Remove Protractor Builder
