angular/angular-cli

packages/angular/build/src/tools/angular/compilation/angular-compilation.ts, packages/angular/build/src/tools/angular/compilation/aot-compilation.ts, packages/angular/build/src/tools/angular/compilation/parallel-worker.ts
The internal AOT Angular compilation processing can now generate the newly introduced template update functions during development server rebuilds of template only file changes. These template update functions are not yet used but provide the infrastructure to enable template hot replacement in a future change.
=> refactor(@angular/build): add internal support for generating template update functions

packages/angular/build/src/utils/index-file/auto-csp.ts, packages/angular/build/src/utils/index-file/auto-csp_spec.ts
Auto-CSP is a feature to rewrite the `<script>` tags in a index.html file to either hash their contents or rewrite them as a dynamic loader script that can be hashed. These hashes will be placed in a CSP inside a `<meta>` tag inside the `<head>` of the document to ensure that the scripts running on the page are those known during the compile-time of the client-side rendered application.
This is an application of the recommended [Strict CSP](https://web.dev/articles/strict-csp#choose-hash) approach that is also recommended by the [OWASP CSP Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html#strict-csp) and inspired by https://github.com/google/strict-csp. The approach of having build tooling auto-generate a hash-based CSP addresses the main …
=> refactor(@angular/build): Auto-CSP support as an index file transformation.

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/application/execute-build.ts, packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/builders/application/schema.json, packages/angular/build/src/tools/esbuild/index-html-generator.ts, packages/angular/build/src/utils/index-file/auto-csp.ts, packages/angular/build/src/utils/index-file/index-html-generator.ts
There are no angular.json configurations to add the auto-csp to the index.html transformation.
There are angular.json configurations to add the auto-csp to the index.html transformation.
This PR also contains content from https://github.com/angular/angular-cli/pull/28639. Please ignore the files changed in that previous PR and instead on
- packages/angular/build/src/utils/index-file/index-html-generator.ts
- packages/angular/build/src/tools/esbuild/index-html-generator.ts
- packages/angular/build/src/builders/application/schema.json
- packages/angular/build/src/builders/application/options.ts
=> feat(@angular/build): Auto-CSP support as a part of angular.json schema

packages/angular/build/src/tools/esbuild/javascript-transformer.ts
In Node.js 20, changes to ESM loader hooks result in the `--import` execArgv being passed from the parent to child workers.
This commit resolves the issue by setting an empty `execArgv` in the JavaScript transformer, preventing unintended propagation.
Closes #28683
=> fix(@angular/build): Address build issue in Node.js LTS versions with prerendering or SSR

package.json, packages/angular_devkit/build_angular/package.json, yarn.lock
Address CVE-2024-21536
Closes #28680
=> fix(@angular-devkit/build-angular): update `http-proxy-middleware` to `3.0.3`

package.json, packages/angular_devkit/build_angular/package.json, yarn.lock
Address CVE-2024-21536
Closes #28680
=> fix(@angular-devkit/build-angular): update `http-proxy-middleware` to `2.0.7`

CHANGELOG.md
=> docs: release notes for the v17.3.11 release

CHANGELOG.md
=> docs: release notes for the v18.2.10 release

CHANGELOG.md, package.json
The previous "next" release-train has moved into the feature-freeze phase. This PR updates the next branch to the subsequent release-train.
Also this PR cherry-picks the changelog for v19.0.0-next.13 into the main branch so that the changelog is up to date.
=> Update next branch to reflect new release-train "v19.1.0-next.0".

packages/angular/build/src/tools/esbuild/angular/component-stylesheets.ts
When using the development server with a production configuration or with bundle hashing enabled, the external stylesheet files used by the development server for hot replacement of component styles are no longer hashed. This ensures that the requests from the runtime served by the development server match the available generated component stylesheet files.
=> fix(@angular/build): avoid hashing development external component stylesheets

packages/schematics/angular/application/files/standalone-files/src/app/app.component.ts.template, packages/schematics/angular/application/index_spec.ts, packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.ts.template, packages/schematics/angular/component/index_spec.ts, packages/schematics/angular/directive/files/__name@dasherize@if-flat__/__name@dasherize__.directive.ts.template, packages/schematics/angular/directive/index_spec.ts, packages/schematics/angular/library/index_spec.ts, packages/schematics/angular/pipe/files/__name@dasherize@if-flat__/__name@dasherize__.pipe.ts.template, packages/schematics/angular/pipe/index_spec.ts
=> refactor(@schematics/angular): remove redundant `standalone: true` from templates

packages/ngtools/webpack/src/ivy/host.ts
=> refactor(@ngtools/webpack): remove unused `augmentHostWithVersioning` method

packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts, packages/angular/build/src/tools/vite/utils.ts
When using the development server, Angular component stylesheet requests that use hot replacement (default for v19) will now use the `ETag` header to remove the need to reprocess and resend encapsulated component styles if the styles have not changed since last usage. The ETag value used is a combination of the style content and the encapsulation component identifier.
=> refactor(@angular/build): use ETag headers for development external component styles

packages/angular/ssr/src/routes/ng-routes.ts
Replaced the custom logic for creating the platform server with the standard `platformServer` method.
=> refactor(@angular/ssr): remove custom Platform Server creation Logic

packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts
When using the development server with the application build system, resource files managed by the build system will now using ETag headers to avoid resending content that has not changed since the last request. This includes such content as global stylesheet files, image/font files referenced in stylesheets, and other files managed by the bundler.
=> refactor(@angular/build): use ETags for dev-server resource requests

.yarn/patches/rollup-license-plugin-npm-3.0.0-038e5f6edc.patch, package.json, yarn.lock
Upstream PR: https://github.com/codepunkt/rollup-license-plugin/pull/178
=> build: patch rollup-license-plugin to fix on windows

packages/angular/build/src/tools/esbuild/application-code-bundle.ts, packages/angular_devkit/build_angular/src/tools/webpack/configs/common.ts
Configure esbuild to add `ngServerMode` as define.
=> refactor(@angular/build): add handling for `ngServerMode`

packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts
When using the development server with the application builder, external component stylesheet usage must always be record to ensure that any hot replacement actions correctly reference the relevant components. Previously, browser cached styles from a past dev server execution would return a 304 status prior to recording the usage. This resulted in the development server not knowing that the component needed a potential update in the future.
=> fix(@angular/build): always record component style usage for HMR updates

packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts
Outside of single-run mode, the karma test provider was expected to watch for changes. In the application builder branch, we only handled the case of an explicit `--watch` though. This meant that the karma runner was kept running but didn't see any file changes.
Fixes https://github.com/angular/angular-cli/issues/28730
=> fix(@angular-devkit/build-angular): fix --watch regression in karma

packages/angular/build/src/builders/dev-server/vite-server.ts
This commit sets the `ngServerMode` in the prebundled deps.
=> fix(@angular/build): set `ngServerMode` during vite prebundling

packages/angular/build/src/tools/esbuild/bundler-context.ts
A bundle call for a `BundlerContext` can now force a rebundling in cases where the cached version should not be used. This is currently not leveraged within the code but will be used for improvements to typescript based context rebuilds in the future.
=> refactor(@angular/build): allow forcing bundler context rebundle

CHANGELOG.md
=> docs: release notes for the v18.2.11 release

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/application/index.ts, packages/angular/build/src/index.ts
An experimental overload of `buildApplication` has been removed.
=> refactor(@angular/build): remove experimental `buildApplication` overload

CHANGELOG.md
=> docs: release notes for the v19.0.0-rc.0 release

packages/angular/build/src/tools/esbuild/javascript-transformer.ts, packages/angular/build/src/utils/server-rendering/esm-in-memory-loader/utils.ts, packages/angular/build/src/utils/server-rendering/prerender.ts
This change prevents Bazel compilation issues in the ADEV build process.
=> fix(@angular/build): Exclude known `--import` from execArgv when spawning workers

goldens/public-api/angular/ssr/index.api.md, goldens/public-api/angular/ssr/node/index.api.md, packages/angular/build/src/builders/application/execute-post-bundle.ts, packages/angular/build/src/tools/vite/middlewares/ssr-middleware.ts, packages/angular/build/src/utils/server-rendering/manifest.ts, packages/angular/ssr/node/src/app-engine.ts, packages/angular/ssr/node/src/request.ts, packages/angular/ssr/src/app-engine.ts, packages/angular/ssr/src/app.ts, packages/angular/ssr/src/assets.ts, packages/angular/ssr/src/manifest.ts, packages/angular/ssr/test/app-engine_spec.ts, packages/angular/ssr/test/app_spec.ts, packages/angular/ssr/test/testing-utils.ts, packages/schematics/angular/ssr/files/application-builder/server.ts.template, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-server-platform-neutral.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-static-http-calls.ts, tests/legacy-cli/e2e/tests/vite/ssr-entry-express.ts, tests/legacy-cli/e2e/tests/vite/ssr-entry-fastify.ts, tests/legacy-cli/e2e/tests/vite/ssr-entry-h3.ts, tests/legacy-cli/e2e/tests/vite/ssr-entry-hono.ts, tests/legacy-cli/e2e/utils/packages.ts
This commit implements the capability for the App Engine to serve prerendered pages directly. Previously, we relied on frameworks like Express for this functionality, which resulted in inconsistent redirects for directories where in some cases a trailing slash was added to the route.
**Note:** This change applies only when using the new SSR APIs. When using the `CommonEngine`, a 3rd party static serve middleware is still required.
=> fix(@angular/ssr): enable serving of prerendered pages in the App Engine

packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts, packages/angular/build/src/tools/esbuild/compiler-plugin-options.ts, packages/angular/build/src/utils/environment-options.ts
The experimental Angular component template hot replacement capabilities will be initially controlled via an environment variable. Setting `NG_HMR_TEMPLATES=1` with the development server that is using the application builder will generate the runtime event code to support hot replacement of an individual component template. The build system itself does not yet generate the component update build results needed to trigger the runtime events. The environment variable is currently intended to support integration of the remaining code to fully implement the feature.
=> refactor(@angular/build): allow experimental template update generation via environment variable

packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.spec.ts.template, packages/schematics/angular/component/index_spec.ts
The generated spec was using the same import when it should be adapted if `exportDefault` is used:
```ts
import { UserComponent } from './user.component.ts`
```
It now produces:
```ts
import UserComponent from './user.component.ts`
```
=> fix(@schematics/angular): component spec with export default

packages/angular/build/src/builders/application/execute-build.ts, packages/angular/build/src/builders/application/setup-bundling.ts, packages/angular/build/src/tools/esbuild/angular/component-stylesheets.ts, packages/angular/build/src/tools/esbuild/angular/source-file-cache.ts, packages/angular/build/src/tools/esbuild/application-code-bundle.ts, packages/angular/build/src/tools/esbuild/bundler-execution-result.ts
The TypeScript-based bundling contexts have now been separated from the other bundling contexts that may be present in an application build. The later of which include global styles, scripts, and non-TypeScript polyfills. This allows for the TypeScript bundling contexts to perform additional checks during a rebuild to determine if they actually need to be rebundled. The bundling context caching for the TypeScript contexts has not yet been enabled but these changes prepare for the switch to allow conditional rebundling on file changes.
=> refactor(@angular/build): improve typescript bundling context rebuild checking

packages/angular/build/src/tools/angular/angular-host.ts
When using the development server with the application builder (default for new projects), the external stylesheet functionality for component style hot replacement was incorrectly considering SVG files as stylesheet resources. This resulted in a build error when using SVG files as a template source. The file extension based checks have now been improved to account for this usage.
=> fix(@angular/build): ensure SVG template URLs are considered templates with external stylesheets

packages/angular/build/src/builders/application/setup-bundling.ts, packages/angular/build/src/tools/esbuild/application-code-bundle.ts, packages/angular/build/src/tools/esbuild/bundler-execution-result.ts, packages/angular/build/src/tools/esbuild/compiler-plugin-options.ts
Now that the TypeScript bundler contexts perform additional checks for validity, they can now be cached in memory during watch modes. This allows the TypeScript bundler contexts to skip rebundling when not affected by a file changed. This is particularly beneficial for style related file changes where no code processing is otherwise required.
=> refactor(@angular/build): allow caching of TypeScript build contexts for rebuilds

packages/angular/cli/src/commands/update/cli.ts, packages/angular/cli/src/utilities/prompt.ts, packages/schematics/angular/migrations/migration-collection.json
The optional application builder migration will now default to enabled and recommended during the update process (`ng update`) for v19. The migration is still optional and can be unselected if preferred when updating.
=> fix(@angular/cli): recommend optional application update migration during v19 update

packages/angular/build/src/builders/application/execute-build.ts, packages/angular/build/src/utils/server-rendering/manifest.ts, packages/angular/ssr/src/app.ts, packages/angular/ssr/src/assets.ts, packages/angular/ssr/src/manifest.ts, packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/test/app_spec.ts, packages/angular/ssr/test/assets_spec.ts, packages/angular/ssr/test/testing-utils.ts
When using the new developer preview API to serve prerendered pages, ETags are added automatically, enabling efficient caching and content validation for improved performance.
=> perf(@angular/ssr): integrate ETags for prerendered pages

packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts, packages/angular/build/src/tools/vite/plugins/setup-middlewares-plugin.ts
If an invalid component identifier is provided to the development server for an external stylesheet requiring encapsulation, both a console message and a 400 status response will now be sent. This removes the potential for invalid styles to be sent to the browser.
=> refactor(@angular/build): send error status code on invalid external style component ID

tests/legacy-cli/e2e/tests/misc/check-postinstalls.ts
Included `@parcel/watcher` in the list of packages allowed in the postinstall checks test.
=> test: add `@parcel/watcher` to allowed postinstall checks

goldens/circular-deps/packages.json, packages/angular/build/src/builders/application/execute-post-bundle.ts, packages/angular/build/src/tools/vite/plugins/angular-memory-plugin.ts, packages/angular/build/src/utils/server-rendering/manifest.ts
This commit refactors the build process for server-side rendering (SSR) by dividing server assets into separate, importable chunks rather than bundling them into a single output file
=> refactor(@angular/build): split SSR server assets into separate chunks

packages/angular/build/src/builders/dev-server/vite-server.ts
Now that additional result object types can be returned from the build system, the error overlay must be cleared on all non-error results. The introduction of component update results and eventual incremental results will now properly clear the error overlay after a successful build.
=> fix(@angular/build): always clear dev-server error overlay on non-error result

packages/angular/build/src/builders/application/build-action.ts, packages/angular/build/src/builders/application/execute-build.ts, packages/angular/build/src/builders/application/setup-bundling.ts, packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts, packages/angular/build/src/tools/esbuild/application-code-bundle.ts, packages/angular/build/src/tools/esbuild/bundler-execution-result.ts, packages/angular/build/src/tools/esbuild/compiler-plugin-options.ts, packages/angular/build/src/tools/vite/middlewares/component-middleware.ts
When using the development server with the application builder (default for new projects), experimental support for component template hot replacement is now available for use. To enable support, the `NG_HMR_TEMPLATES=1` environment variable must present when executing the development server (for example, `NG_HMR_TEMPLATES=1 ng serve`). Once support has become stable, template hot replacement will be enabled by default.
=> refactor(@angular/build): integrate template update function generation with builder results

packages/angular/build/src/tools/esbuild/server-bundle-metadata-plugin.ts, packages/angular/cli/src/analytics/analytics-parameters.mts, packages/angular/cli/src/analytics/analytics-parameters.ts, packages/angular/ssr/node/src/app-engine.ts, packages/angular/ssr/src/app-engine.ts, packages/angular/ssr/src/app.ts, packages/angular/ssr/src/manifest.ts
Updated TSDoc comments by replacing @note with @remarks across the codebase. This aligns with TSDoc's preferred conventions, where @remarks is used for supplementary explanations and additional context.
=> docs: replace `@note` with `@remarks`

packages/angular/build/src/utils/server-rendering/prerender.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-static-i18n_APP_BASE_HREF.ts
This commit resolves path stripping issues when `APP_BASE_HREF` does not align with the expected value.
Closes #28775
=> fix(@angular/build): handle `APP_BASE_HREF` correctly in prerendered routes

packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts
When using the development server with the application builder (default for new projects), Angular components using ShadowDOM view encapsulation will now cause a full page reload. This ensures that these components styles are correctly updated during watch mode. Vite's CSS hot replacement client code currently does not support searching and replacing `<link>` elements inside shadow roots. When support is available within Vite, an HMR based update for ShadowDOM components can be supported as other view encapsulation modes are now.
=> fix(@angular/build): workaround Vite CSS ShadowDOM hot replacement

packages/angular/ssr/src/global.d.ts, packages/angular/ssr/src/routes/route-config.ts
Introduced an error check to ensure that 'provideServerRoutesConfig' is not utilized in the browser part of the application. This helps avoid unintended behavior.
=> fix(@angular/ssr): add validation to prevent use of `provideServerRoutesConfig` in browser context

goldens/public-api/angular/ssr/index.api.md, goldens/public-api/angular/ssr/node/index.api.md, packages/angular/ssr/node/public_api.ts, packages/angular/ssr/node/src/handler.ts, packages/angular/ssr/public_api.ts, packages/angular/ssr/src/handler.ts
These additions are necessary to ensure their inclusion in adev.
=> refactor(@angular/ssr): Add `RequestHandlerFunction` and `NodeRequestHandlerFunction` to public API

packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts, packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/rebuilds_spec.ts
The Karma file watching was racing with the file writes done by the application builder. Since we already tell Karma when to reun via `.refeshFiles()`, disabling Karma's own file watcher should make things more reliable.
This allows removing a weird special-case in the test case and removes the noisy "File chaned" logs generated by Karma.
Fixes https://github.com/angular/angular-cli/issues/28755
=> fix(@angular-devkit/build-angular): remove double-watch in karma

packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts, packages/angular_devkit/build_angular/src/builders/karma/tests/options/assets_spec.ts
Turns out the test for asset serving didn't actually test asset serving because of a missing `whenStable()` - it always succeeded, even with random filenames. This change adds a custom middleware to serve our static files since it seemed easier (and more predictable) than to try to map the `assets` concept to Karma's `files`+`proxy` logic.
One side effect of adding the middleware is that we don't actually need the Karma `files` anymore with the exception of any files that we'd want to include on page load. I don't touch that part here because it will be cleaner to change it when also addressing the naming collisions between spec files.
Fixes https://github.com/angular/angular-cli/issues/28754
~~P.S.: Currently the first commit is from a different PR …
=> fix(@angular-devkit/build-angular): serve assets

goldens/public-api/angular/ssr/index.api.md, packages/angular/build/src/tools/vite/middlewares/ssr-middleware.ts, packages/angular/build/src/utils/server-rendering/prerender.ts, packages/angular/build/src/utils/server-rendering/render-worker.ts, packages/angular/ssr/src/app-engine.ts, packages/angular/ssr/src/app.ts, packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/src/routes/route-tree.ts, packages/angular/ssr/test/BUILD.bazel, packages/angular/ssr/test/app_spec.ts, packages/angular/ssr/test/routes/route-tree_spec.ts
This commit cleans up duplicate code left from the previous implementations of process, serve, and render. Additionally, prerender serve now exclusively handles HEAD and GET requests, aligning with updated handling requirements. The private `renderStatic` method has been removed in favor of the `handle` method for improved maintainability.
=> refactor(@angular/ssr): remove duplicate code and streamline functionality

packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts, packages/angular/build/src/tools/vite/middlewares/index.ts, packages/angular/build/src/tools/vite/plugins/setup-middlewares-plugin.ts
When using the development server with the application builder, the internal state of any external component stylesheets is now more comprehensively tracked. This allows for more flexibility in both debugging potential problems as well as supporting additional stylesheet preprocessing steps including deferred component stylesheet processing.
=> refactor(@angular/build): use structured component stylesheet tracking for hot replacement

packages/angular/build/src/builders/application/execute-post-bundle.ts
This fix ensures that the wildcard routes are not included in the prerendered list, improving the accuracy of prerendered route generation.
=> fix(@angular/build): skip wildcard routes from being listed as prerendered routes

packages/angular/build/src/builders/application/options.ts, packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts, packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/specs_spec.ts
Generates unique names for each test entry point and also creates a nice & consistent name for the main ("init test bed") chunk. All specs are now `spec-*.js` files.
Fixes https://github.com/angular/angular-cli/issues/28756
~~P.S.: Current based on https://github.com/angular/angular-cli/pull/28795, will rebase post-merge.~~
=> fix(@angular-devkit/build-angular): handle basename collisions

goldens/public-api/angular/ssr/tokens/index.api.md, packages/angular/ssr/tokens/src/tokens.ts
This commit initializes the `REQUEST`, `RESPONSE_INIT`, and `REQUEST_CONTEXT` DI tokens with `null` values by default.
Previously, these tokens lacked default values, which meant that developers had to explicitly mark them as optional when injecting them in constructors. This was necessary to avoid errors when these tokens were not provided, particularly in scenarios like client-side rendering or during development.
By initializing these tokens with `null`, we eliminate the need for developers to mark them as optional, simplifying the code and improving the developer experience.
=> fix(@angular/ssr): initialize the DI tokens with `null` to avoid requiring them to be set to optional

CHANGELOG.md
=> docs: release notes for the v19.0.0-rc.1 release

goldens/public-api/angular/ssr/node/index.api.md, packages/angular/ssr/node/src/app-engine.ts, packages/angular/ssr/node/src/request.ts, packages/angular/ssr/node/src/response.ts, packages/angular/ssr/node/test/request_http1_spec.ts, packages/angular/ssr/node/test/request_http2_spec.ts, packages/angular/ssr/node/test/response_http1_spec.ts, packages/angular/ssr/node/test/response_http2_spec.ts, tests/legacy-cli/e2e/tests/vite/ssr-entry-express.ts, tests/legacy-cli/e2e/tests/vite/ssr-entry-fastify.ts, tests/legacy-cli/e2e/tests/vite/ssr-entry-h3.ts, tests/legacy-cli/e2e/tests/vite/ssr-entry-hono.ts, tests/legacy-cli/e2e/tests/vite/ssr-with-ssl.ts
This commit introduces support for handling HTTP/2 requests and responses in the `@angular/ssr` package.
Closes #28807
=> fix(@angular/ssr): support for HTTP/2 request/response handling

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
A component may contain multiple inline styles that will originate from the same containing file. The content of the processed style is sent directly to the Angular compiler. However, any additional result files are collected and emitted in the application output. In most cases, this worked as expected as inline styles rarely had resource references that would overwrite each other. However, the potential is present for later inline styles for a component to overwrite these output files. To avoid this potential problem, the internal identifier now accounts for both the class name and order of the inline styles. This ensures that each inline style retains a unique additional results entry.
=> fix(@angular/build): avoid overwriting inline style bundling additional results

packages/angular/build/src/builders/application/execute-post-bundle.ts, packages/angular/ssr/src/app.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-server.ts
Corrected an issue where a redirect was not properly included in the SSR (Server-Side Rendering) manifest. This fix ensures that all necessary redirects are accounted for during the build process.
=> fix(@angular/build): add missing redirect in SSR manifest

goldens/public-api/angular/ssr/index.api.md, packages/angular/build/src/builders/application/tests/options/app-shell_spec.ts, packages/angular/build/src/utils/server-rendering/models.ts, packages/angular/build/src/utils/server-rendering/prerender.ts, packages/angular/build/src/utils/server-rendering/routes-extractor-worker.ts, packages/angular/ssr/public_api.ts, packages/angular/ssr/src/app.ts, packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/src/routes/route-config.ts, packages/angular/ssr/test/routes/ng-routes_spec.ts, packages/angular_devkit/build_angular/src/builders/app-shell/app-shell_spec.ts, packages/schematics/angular/app-shell/index.ts, packages/schematics/angular/app-shell/index_spec.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-server.ts
This commit removes the `RenderMode.AppShell` option. Instead, a new configuration parameter, `{ appShellRoute: 'shell' }`, is introduced to the `provideServerRoutesConfig` method.
```ts
provideServerRoutesConfig(serverRoutes, { appShellRoute: 'shell' })
```
=> refactor(ssr): remove `RenderMode.AppShell` in favor of new configuration option

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
Previously the `fileReplacements` option within the `application` builder would only replace `.js` files if the TypeScript `allowJs` option was enabled. This differs from the `browser` builder which did not require the option. To minimize friction when migrating to the new build system, the `allowJs` option is no longer required for this file replacement case.
=> fix(@angular/build): allow `.js` file replacements in all configuration cases

packages/angular/cli/src/command-builder/schematics-command-module.ts
Issue Number: #28843
This PR provides support for default options for multiselect list x-prompt after switching to `@inquirer/prompts` library.
=> fix(@angular/cli): support default options for multiselect list x-prompt

packages/angular/build/src/builders/application/tests/behavior/stylesheet-url-resolution_spec.ts, packages/angular/build/src/tools/sass/rebasing-importer.ts
Sass variable namespaces can contain either a hyphen or underscore in the namespace identifier. The URL rebasing support within the Angular CLI will now account for these type of namespaces and rebase the evaluated URL as expected.
=> fix(@angular/build): improve URL rebasing for hyphenated Sass namespaced variables

CHANGELOG.md
=> docs: release notes for the v19.0.0-rc.2 release

packages/angular/ssr/public_api.ts
Importing `PrerenderFallback` in a project throws at build time in rc.2 with:
```ts
✘ [ERROR] No matching export in "node_modules/@angular/ssr/fesm2022/ssr.mjs" for import "PrerenderFallback"
src/app/app.routes.server.ts:1:9:
1 │ import { PrerenderFallback, RenderMode, ServerRoute } from '@angula...
```
This exports `PrerenderFallback` the same way `RenderMode` is exported to fix the issue.
=> fix(@angular/ssr): export PrerenderFallback

package.json, packages/angular/cli/package.json, yarn.lock
The previous version specified `@inquirer/prompts < 7` which caused a warning about invalid peer deps. The only difference between 2.0.17 and 2.0.18 is that this range was expanded to `< 8`.
See: https://github.com/listr2/listr2/issues/730
Fixes: https://github.com/angular/angular-cli/issues/28870
Commit history: https://github.com/listr2/listr2/commits/@listr2%2fprompt-adapter-inquirer@2.0.18/packages/prompt-adapter-inquirer
=> build: fix peer dep warning for listr2

packages/angular_devkit/build_angular/src/builders/server/index.ts
This was missed in the original addition of `ngServerMode` and incorrectly caused `withEventReplay` to run browser-specific code on the server and crash.
=> refactor: add `ngServerMode` to Webpack SSR dev server

packages/schematics/angular/ssr/files/server-builder/server.ts.template
Now that we're using `esModuleInterop`, a default import is required.
=> fix: use default import for `express`

packages/angular_devkit/build_angular/src/builders/ssr-dev-server/index.ts
Running the SSR dev server when `browser-sync` is not installed would print the error, but then build the browser and server targets, then hang and never return control to the user until they manually Ctrl+C. This change skips building at all if `browser-sync` is not installed, immediately returning control to the user.
This is a simple workaround, but there are two deeper bugs which would benefit from investigation:
1.  Figure out why NPM sometimes doesn't install `browser-sync`. It was happening inconsistently for me when running `ng add @angular/ssr`.
2.  Figure out why Architect does not cancel/await targets still executing when a builder completes.
I'm not sure if this fix should be backported to older versions, but we can worry about that after the v19 launch.
=> fix(@angular-devkit/build-angular): fix hanging terminal when `browser-sync` is not installed

packages/angular/ssr/schematics/ng-add/index_spec.ts, packages/schematics/angular/BUILD.bazel, packages/schematics/angular/application/index_spec.ts, packages/schematics/angular/ssr/index.ts, packages/schematics/angular/ssr/index_spec.ts, packages/schematics/angular/ssr/schema.json, packages/schematics/angular/ssr/tty.ts, tests/legacy-cli/e2e/tests/build/prerender/discover-routes-ngmodule.ts, tests/legacy-cli/e2e/tests/build/server-rendering/express-engine-csp-nonce.ts, tests/legacy-cli/e2e/tests/build/server-rendering/express-engine-standalone.ts, tests/legacy-cli/e2e/tests/commands/serve/ssr-http-requests-assets.ts, tests/legacy-cli/e2e/tests/vite/ssr-error-stack.ts
The new routing APIs don't support `browser` builder, but calling `ng add @angular/ssr` with a `browser` builder would still prompt the user to add them. If the user said "Yes", it would actually ignore that answer and not enable the new APIs.
With this change, `ng add @angular/ssr` when using `browser` builder does not show the prompt and assumes the answer is "No". It also throws an error if the user runs `ng add @angular/ssr --server-routing`.
I'm not aware of a built-in prompting mechanism in schematics beyond `x-prompt`, which can't be used here, so instead I just called Inquirer directly. Unfortunately testing the prompt is a little awkward, as Inquirier does not provide useful APIs in this space. I evaluated `@inquirer/testing`, but ultimately decided that was more intended for …
=> fix(@schematics/angular): don't show server routing prompt when using `browser` builder

CHANGELOG.md
=> docs: release notes for the v19.0.0-rc.3 release

CHANGELOG.md
=> docs: release notes for the v19.0.0 release

packages/angular/build/src/utils/server-rendering/manifest.ts
Adjusts the server assets to use the original content length
Closes #28832
=> fix(@angular/build): ensure accurate content length for server assets

packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/test/app-engine_spec.ts, packages/angular/ssr/test/routes/ng-routes_spec.ts, packages/angular/ssr/test/testing-utils.ts
Updated function to support handling `baseHref` starting with './' path correctly.
=> fix(@angular/ssr): handle baseHref that start with `./`

packages/angular/build/src/utils/server-rendering/routes-extractor-worker.ts
Ensure that errors occurring during initialization are properly propagated, as Piscina currently swallows errors during worker initialization. For more details, see:
https://github.com/piscinajs/piscina/blob/b64747233446ca4271e6aed744a740f637e278a5/src/worker.ts#L57
=> refactor(@angular/build): adjust code to propagate errors from Piscina

tests/legacy-cli/e2e/tests/vite/ssr-default.ts
This commit introduces end-to-end (e2e) tests to validate the server-side rendering (SSR) setup.
=> test: add end-to-end tests for SSR setup

packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts
The `stylePreprocessorOptions` were ignored, meaning that `silenceDeprecations`, for example, was not used when building tests.
The options is now passed to the builder
=> fix(@angular-devkit/build-angular): use stylePreprocessorOptions

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts, packages/angular/build/src/tools/esbuild/wasm-plugin.ts
Stackblitz appears to fail when attempting to use `crypto.createHash` with an algorithm value of `sha-256`. Since Node.js supports both the hyphenated and unhyphenated values, the later is now used to avoid issues when running on Stackblitz.
=> fix(@angular/build): use `sha256` instead of `sha-256` as hash algorithm name

CHANGELOG.md
=> docs: release notes for the v19.0.1 release

packages/angular/ssr/src/app.ts, packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/src/utils/url.ts, packages/angular/ssr/test/app_spec.ts, packages/angular/ssr/test/routes/ng-routes_spec.ts, packages/angular/ssr/test/routes/router_spec.ts, packages/angular/ssr/test/utils/url_spec.ts
This commit ensures proper handling of nested redirects that are implicitly structured but not explicitly defined in the router configuration.
Closes #28903
=> fix(@angular/ssr): handle nested redirects not explicitly defined in router config

.github/workflows/perf.yml, .ng-dev/dx-perf-workflows.yml, package.json, yarn.lock
Set up the initial workflow to build upon.
=> ci: set up perf workflow job and create initial workflow

packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/src/routes/route-tree.ts, packages/angular/ssr/test/routes/route-tree_spec.ts
The SSR router relies on wildcard matching rather than params. This commit refactors the stored routes by removing the `:params`.
=> refactor(@angular/ssr): replace `:params` with `*`

packages/angular/build/src/tools/esbuild/application-code-bundle.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-server-platform-neutral.ts
Resolved an issue where the use of `esbuild`'s `inject` feature caused incorrect reordering of class structures during bundling. This reordering affected extended classes, as illustrated below:
```js
class e extends Ur {
constructor(n, r, i) {
super(n, r, i);
}
ngOnDestroy() {
this.flush();
}
static ɵfac = function (r) {
return new (r || e)(pe(Xe), pe(Ti), pe(Di));
};
static ɵprov = oe({ token: e, factory: e.ɵfac });
}
var Ur = class {
// Class properties and methods omitted for brevity
};
```
By reducing the reliance on `inject`, we ensure that the ordering of class properties and methods remains consistent, preserving the expected behavior.
Closes #28941
=> fix(@angular/build): minimize reliance on esbuild `inject` to prevent code reordering

packages/schematics/angular/ssr/index.ts, packages/schematics/angular/ssr/index_spec.ts
Apparently `inquirer` requires `async_hooks` which isn't supported in webcontainers, therefore prompting the user fails. Instead we always fall back to the default option.
See: https://github.com/SBoudrias/Inquirer.js/issues/1426
=> fix(@schematics/angular): skip SSR routing prompt in webcontainer

packages/angular/build/src/private.ts
To minimize downstream breakage for consumers of the private API, the `createCompilerPlugin` function signature has been adjusted to maintain compatibility with v18.
=> refactor(@angular/build): maintain previous compiler plugin factory signature

packages/angular/build/src/utils/server-rendering/routes-extractor-worker.ts, tests/legacy-cli/e2e/tests/build/prerender/discover-routes-standalone.ts
Ensure that parameterized routes do not cause errors when the `getPrerenderParams` function is undefined, specifically in cases where the routing API is not utilized.
Closes #28948
=> fix(@angular/build): prevent errors with parameterized routes when `getPrerenderParams` is undefined

CHANGELOG.md
=> docs: release notes for the v19.0.2 release

packages/angular/build/src/builders/application/tests/options/file-replacements_spec.ts, packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
When using the `application` builder, the `fileReplacements` option will now work as it previous did with the `browser` builder when replacing JSON files.
Closes #28949
=> fix(@angular/build): allow .json file replacements with application builds

package.json, packages/angular/build/package.json, packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/build/src/tools/vite/plugins/ssr-transform-plugin.ts, tests/legacy-cli/e2e/tests/vite/reuse-dep-optimization-cache.ts, tests/legacy-cli/e2e/tests/vite/ssr-new-dep-optimization.ts, yarn.lock
This commit updates vite to version 6
=> build: update to vite version 6

goldens/public-api/angular/ssr/node/index.api.md, packages/angular/ssr/node/src/response.ts, packages/angular/ssr/node/test/request_http2_spec.ts
Updated the `Http2ServerResponse` interface to eliminate dependency on generics, ensuring compatibility across multiple versions of `@types/node`.
Closes #28965
=> fix(@angular/ssr): ensure compatibility for `Http2ServerResponse` type

packages/angular/cli/src/commands/add/cli.ts
When using the `ng add` command, the package version selection logic was not correctly selected based on the available versions in desc order. This could lead to selecting an unintended version of the package.
Closes: #28985
=> fix(@angular/cli): correctly select package versions in descending order during `ng add`

README.md, scripts/templates/readme.ejs
Made some corrections in the documentation
=> docs: readme

packages/angular/build/src/utils/server-rendering/routes-extractor-worker.ts, packages/angular/ssr/src/app.ts, packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/src/routes/router.ts, packages/angular/ssr/src/utils/promise.ts, packages/angular/ssr/test/app_spec.ts, packages/angular/ssr/test/routes/ng-routes_spec.ts, packages/angular/ssr/test/utils/promise_spec.ts
This commit introduces a 30-second timeout for route extraction.
=> fix(@angular/build): add timeout to route extraction

packages/schematics/angular/guard/type-files/__name@dasherize__.guard.spec.ts.template
=> refactor(@schematics/angular): add required type to CanDeactivate guard

packages/angular/build/src/builders/application/execute-post-bundle.ts, packages/angular/build/src/utils/server-rendering/manifest.ts, packages/angular/build/src/utils/server-rendering/prerender.ts, packages/angular/ssr/src/app.ts, packages/angular/ssr/src/manifest.ts, packages/angular/ssr/test/app-engine_spec.ts, packages/angular/ssr/test/assets_spec.ts, packages/angular/ssr/test/testing-utils.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-server-i18n-base-href.ts
Ensures proper handling of internationalized (i18n) pages during the  serving of prerendered content.
=> fix(@angular/ssr): correctly handle serving of prerendered i18n pages

packages/angular/build/src/builders/application/tests/options/define_spec.ts, packages/angular/build/src/tools/esbuild/global-scripts.ts
The `define` option will now apply to JavaScript that is included in the output via the `scripts` option.  This allows the replacement of identifiers within any included scripts in addition to the already supported replacement within application code.
Closes #29002
=> fix(@angular/build): apply define option to JavaScript from scripts option

.github/workflows/perf.yml, .ng-dev/dx-perf-workflows.yml, package.json, yarn.lock
=> ci: run workflows for all releasable branches

packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/builders/application/tests/behavior/index-csr_spec.ts, packages/angular/build/src/builders/application/tests/options/index_spec.ts
Previously, the index file was not being renamed correctly when using server-side rendering (SSR).
Closes: #29012
=> fix(@angular/build): ensure correct handling of `index.output` for SSR

packages/angular/build/src/utils/index-file/augment-index-html.ts, packages/angular/build/src/utils/index-file/augment-index-html_spec.ts
The `deployUrl` option was unintentionally being prepended to preload links with absolute URLs within the generated index HTML for an appplication. This has now been corrected and absolute URLs will not be altered when a deploy URL is configured.
Closes: #29029
=> fix(@angular/build): avoid deploy URL usage on absolute preload links

packages/angular/build/src/utils/server-rendering/manifest.ts, packages/angular/ssr/src/app-engine.ts, packages/angular/ssr/src/assets.ts, packages/angular/ssr/src/manifest.ts, packages/angular/ssr/test/app-engine_spec.ts, packages/angular/ssr/test/assets_spec.ts, packages/angular/ssr/test/testing-utils.ts
Replaced `Map` with `Record` in SSR manifest to simplify structure and improve testing/setup.
=> refactor(@angular/ssr): replace `Map` with `Record` in SSR manifest

packages/angular/ssr/src/app.ts
Before this commit, HTML transformations were not applied to CSR responses, leading to the omission of the Vite client code.
Closes angular/angular-cli#29033
=> fix(@angular/ssr): apply HTML transformation to CSR responses

CHANGELOG.md
=> docs: release notes for the v19.0.3 release

tests/legacy-cli/e2e/tests/vite/reuse-dep-optimization-cache.ts, tests/legacy-cli/e2e/tests/vite/ssr-new-dep-optimization.ts
This forcefully removes the colors.
=> test: disable colors in vite tests

packages/angular/build/src/tools/angular/angular-host.ts, packages/angular/build/src/tools/angular/compilation/aot-compilation.ts, packages/angular/build/src/tools/angular/compilation/jit-compilation.ts
TypeScript 5.6 and higher added functionality that will search for a `package.json` file for source files that are part of the program (e.g., `.d.ts`) and within a node modules directory. This can be an expensive task especially considering the large amount of `.d.ts` files within packages. TypeScript supports using a cache of known `package.json` files to improve the performance of this task. The Angular CLI will now provide and reuse this cache across rebuilds during watch mode. This includes the use of `ng serve`.
The performance difference is most apparent for the Angular template diagnostic step of the build. Internally the Angular compiler creates a new template typechecking program which causes the `package.json` search process to occur. By leveraging the cache, this process …
=> perf(@angular/build): reuse TS package.json cache when rebuilding

.github/workflows/assistant-to-the-branch-manager.yml, .github/workflows/ci.yml, .github/workflows/dev-infra.yml, .github/workflows/feature-requests.yml, .github/workflows/pr.yml
This commit consumes the latest version of dev-infra to fix CI.
See: angular/dev-infra@40b2cbd
=> ci: update dev-infra sha to use latest Bazel keys

packages/angular/ssr/src/routes/route-config.ts
Remove duplicate `@return` tsdoc comment.
=> docs(@angular/ssr): remove duplicate `@return` comment

packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts, packages/angular_devkit/build_angular/src/builders/karma/find-tests.ts, packages/angular_devkit/build_angular/src/builders/karma/find-tests_spec.ts, packages/angular_devkit/build_angular/src/builders/karma/tests/behavior/specs_spec.ts
The previous logic didn't quite work when interacting with windows path. This PR does three things:
1. Move the logic to generate unique spec entrypoint names into its own function. This prepares for reusing it elsewhere (e.g. in WTR).
2. Add a more direct unit test for that logic.
3. Fix the logic so it works with Windows paths as well as unix paths.
As a drive-by fix, this also cleans up the deduped filenames so we get "foo-2.spec.js" instead of "foo.spec-2.js". The latter looked a bit confusing and it was just a tiiiiny regex to fix those names up. The index append shouldn't really come up in real code very often, so this is very much a tiny niche case.
Fixes https://github.com/angular/angular-cli/issues/28915
=> fix(@angular-devkit/build-angular): handle windows spec collisions

packages/angular/build/src/builders/dev-server/vite-server.ts, tests/legacy-cli/e2e/tests/vite/browser-node-module-dep-error.ts, tests/legacy-cli/e2e/tests/vite/reuse-dep-optimization-cache.ts
This commit ensures consistent behavior between `ng build` and `ng serve`. Previously, `ng serve` did not display an error message when Node.js built-in modules were included in browser bundles. By default, Vite replaces Node.js built-ins with empty modules, which can lead to unexpected runtime issues. This update addresses the problem by surfacing clear error messages, providing better developer feedback and alignment between the two commands.
Closes: #27425
(cherry picked from commit 06f478bc18d3e0daa8902d0fef94e55a5d052348)
=> fix(@angular/build): show error when Node.js built-ins are used during `ng serve`

CHANGELOG.md
=> docs: release notes for the v19.0.4 release

modules/testing/builder/src/builder-harness.ts, packages/angular_devkit/build_angular/BUILD.bazel, packages/angular_devkit/build_angular/src/builders/karma/browser_builder.ts, packages/angular_devkit/build_angular/src/builders/karma/tests/options/custom-loader_spec.ts
This PR is 10% passing an argument that got dropped during refactoring and 90% finding a way to test the behavior.
I'm making up a new concept for the harness (`additionalExecuteArguments`) which is pretty ugly but I couldn't think of a cleaner way of doing it. There might be a way to capture rest arguments of the `execute` function signature inside of the harness to make the cast go away. But I'm not 100% convinced that the more complicated types leaking throughout the harness code would really be worth it for this edge case.
See: https://github.com/angular/angular-cli/issues/29003
=> fix(@angular-devkit/build-angular): webpack config transform for karma

packages/angular/ssr/test/app-engine_spec.ts, packages/angular/ssr/test/app_spec.ts, packages/angular/ssr/test/testing-utils.ts
This update addresses excessive log noise caused by the following warning: `NG0912: Component ID generation collision detected. Components 'AppComponent' and 'AppComponent' with selector 'app-root' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.dev/errors/NG0912`.
=> test(@angular/ssr): refine spec setup to resolve component ID collision warnings

packages/angular/ssr/src/app.ts, packages/angular/ssr/test/app-engine_spec.ts, packages/angular/ssr/test/testing-utils.ts
The server now includes the `Content-Language` HTTP header in responses whenever a locale is explicitly set.
=> fix(@angular/ssr):  include `Content-Language` header when locale is set

packages/angular/build/src/builders/application/i18n.ts, packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/builders/extract-i18n/options.ts, packages/angular/build/src/utils/i18n-options.ts, packages/angular/build/src/utils/server-rendering/manifest.ts, packages/angular/build/src/utils/server-rendering/prerender.ts, packages/angular/cli/lib/config/workspace-schema.json, packages/angular/ssr/src/app-engine.ts, packages/angular_devkit/build_angular/src/builders/browser/index.ts, packages/angular_devkit/build_angular/src/builders/extract-i18n/options.ts, packages/angular_devkit/build_angular/src/utils/i18n-webpack.ts, packages/angular_devkit/build_angular/src/utils/output-paths.ts, packages/schematics/angular/guard/index.ts, packages/schematics/angular/guard/index_spec.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-server-i18n-sub-path.ts
Previously, the `baseHref` option under each locale allowed for generating a unique base href for specific locales. However, users were still required to handle file organization manually, and `baseHref` appeared to be primarily designed for this purpose.
This commit introduces a new `subPath` option, which simplifies the i18n process, particularly in static site generation (SSG) and server-side rendering (SSR). When the `subPath` option is used, the `baseHref` is ignored. Instead, the `subPath` serves as both the base href and the name of the directory containing the localized version of the app.
Below is an example configuration showcasing the use of `subPath`:
```json
"i18n": {
"sourceLocale": {
"code": "en-US",
"subPath": ""
},
"locales": {
"fr-BE": {
"subPath": "fr",
"translation": …
```
=> feat(@angular/build): add support for customizing URL segments with i18n

packages/angular/build/src/tools/esbuild/application-code-bundle.ts, packages/angular/build/src/utils/server-rendering/esm-in-memory-loader/loader-hooks.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-server-external-dependencies.ts
This commit introduces `ngServerMode` to ensure proper handling of external `@angular/` packages when they are used as externals during server-side rendering (SSR).
Closes: #29092
=> fix(@angular/build): handle external `@angular/` packages during SSR

packages/angular/build/BUILD.bazel, packages/angular/build/src/builders/application/execute-build.ts, packages/angular/build/src/builders/application/execute-post-bundle.ts, packages/angular/build/src/builders/application/i18n.ts, packages/angular/build/src/tools/angular/compilation/aot-compilation.ts, packages/angular/build/src/tools/angular/compilation/factory.ts, packages/angular/build/src/tools/angular/compilation/jit-compilation.ts, packages/angular/build/src/tools/angular/compilation/parallel-compilation.ts, packages/angular/build/src/tools/angular/compilation/parallel-worker.ts, packages/angular/build/src/tools/angular/transformers/lazy-routes-transformer.ts, packages/angular/build/src/tools/angular/transformers/lazy-routes-transformer_spec.ts, packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts, packages/angular/build/src/tools/esbuild/compiler-plugin-options.ts, packages/angular/build/src/utils/server-rendering/manifest.ts, packages/angular/ssr/src/app.ts, packages/angular/ssr/src/manifest.ts, packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/src/routes/route-tree.ts, packages/angular/ssr/test/testing-utils.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-preload-links.ts
Enhance performance when using SSR by adding `modulepreload` links to lazy-loaded routes. This ensures that the required modules are preloaded in the background, improving the user experience and reducing the time to interactive.
Closes #26484
=> feat(@angular/ssr): add `modulepreload` for lazy-loaded routes

packages/angular/build/src/utils/server-rendering/manifest.ts, packages/angular/ssr/src/app-engine.ts, packages/angular/ssr/src/i18n.ts, packages/angular/ssr/src/manifest.ts, packages/angular/ssr/test/app-engine_spec.ts, packages/angular/ssr/test/i18n_spec.ts
When users access the root route `/` without providing a locale, the application now redirects them to their preferred locale based on the `Accept-Language` header.
This enhancement leverages the user's browser preferences to determine the most appropriate locale, providing a seamless and personalized experience without requiring manual locale selection.
=> feat(@angular/ssr): redirect to preferred locale when accessing root route without a specified locale

packages/angular/build/src/tools/angular/compilation/aot-compilation.ts
To ensure that component HMR identifiers match correctly during an update, the path element of the identifier generated by the build system will now convert all windows path separators into POSIX separators. This provides matching behavior to the AOT compiler's identifier generation process.
=> fix(@angular/build): use consistent path separators for template HMR identifiers

packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/test/routes/ng-routes_spec.ts, packages/angular/ssr/test/testing-utils.ts
This commit disables component bootstrapping during route extraction to prevent invoking the AppComponent and its lifecycle hooks.
Closes #29085
=> fix(@angular/ssr): disable component bootstrapping during route extraction

packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/build/src/tools/vite/plugins/angular-memory-plugin.ts
When using component HMR and SSR with the development server, the component update modules will now be available to the Vite server rendering.  This prevents console errors due to missing component update paths. Additionally, it allows the server rendering to use the latest component templates if those have been changed before a new rebuild has occurred.
=> fix(@angular/build): provide component HMR update modules to dev-server SSR

packages/angular_devkit/architect/node/node-modules-architect-host.ts
Currently, when you create a custom builder for Angular CLI, the builder `schema` can only be a reference to a *local file* in the manifest directory. This is cumbersome, for example when you want to reference an external schema from a module instead.
This is now working:
```json
"schema": "./src/builders/browser-esbuild/schema.json"
```
This is not working:
```json
"schema": "@angular-devkit/build-angular/src/builders/browser-esbuild/schema.json"
```
It is now possible to require a builder schema from a module.
This is now working:
```json
"schema": "./src/builders/browser-esbuild/schema.json"
```
and this too:
```json
"schema": …
```
=> feat(@angular-devkit/architect): require build schemas from modules

CHANGELOG.md
=> docs: release notes for the v19.0.5 release

packages/angular/build/src/builders/application/execute-build.ts
The experimental chunk optimizer is now only imported if it is enabled via its environment variable (`NG_BUILD_OPTIMIZE_CHUNKS=1`). This prevents the loading of the rollup package as well as any transitive dependencies when these packages will not be used by the build.
=> refactor(@angular/build): only load chunk optimizer if enabled

tests/legacy-cli/e2e.bzl, tests/legacy-cli/e2e/tests/build/auto-csp.ts
No e2e tests for https://github.com/angular/angular-cli/pull/28663
e2e tests for https://github.com/angular/angular-cli/pull/28663
=> test: e2e tests for autoCsp

packages/angular/build/src/tools/vite/plugins/angular-memory-plugin.ts, tests/legacy-cli/e2e/tests/vite/ssr-no-server-entry-sub-path.ts
Ensure proper resolution of pre-transform resources when using SSR in Vite without relying on AppEngine.
Closes #29132
=> fix(@angular/ssr): correctly resolve pre-transform resources in Vite SSR without AppEngine

renovate.json
This is needed as otherwise the `npm_translate_lock` file will be out of sync
=> ci: sync package locks information for aspect with renovate

renovate.json
There is an unidentified issue causing the Yarn binary to be altered, resulting in packages not installing correctly and leading to failures in the process.
=> ci: ignore changes to `.yarn/releases`

renovate.json
This commit tries to display `pnpm-lock.yaml` update using renovate and instead it uses `yarn bazel run @npm2//:sync`.
=> ci: disable `pnpm-lock.yaml` update via renovate

renovate.json
These files are updated by our tooling
=> ci: ignore pnpm lock file update from renovate

packages/angular/build/src/builders/dev-server/vite-server.ts
When server-side rendering (SSR) is enabled with SSL and Express, Vite must use HTTP/1.1 because Express does not support HTTP/2. This is achieved by setting an empty proxy configuration.
Reference: https://github.com/vitejs/vite/blob/c4b532cc900bf988073583511f57bd581755d5e3/packages/vite/src/node/http.ts#L106
Closes #29142
=> fix(@angular/build): force HTTP/1.1 in dev-server SSR with SSL

packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/build/src/tools/esbuild/application-code-bundle.ts, packages/angular/build/src/tools/vite/plugins/angular-memory-plugin.ts, packages/angular/build/src/utils/environment-options.ts, tests/legacy-cli/e2e/tests/basic/rebuild.ts, tests/legacy-cli/e2e/tests/vite/ssr-entry-express.ts, tests/legacy-cli/e2e/tests/vite/ssr-entry-fastify.ts, tests/legacy-cli/e2e/tests/vite/ssr-entry-h3.ts, tests/legacy-cli/e2e/tests/vite/ssr-entry-hono.ts
When using the `application` builder (default for new projects) with the development server, component template only changes will now automatically replace the template within the running application without a full reload of the page. No application code changes are necessary and both file-based (`templateUrl`) and inline (`template`) component templates are supported. Additionally, changing a components styles in combination with a template change is also supported for hot replacement. This includes both inline and file-based changes.
If any issues are encountered or it is preferred to not hot replace component templates, the `NG_HMR_TEMPLATES=0` environment variable can be used to disable the feature. Setting the `liveReload` option or `hmr` option to false will also disable all …
=> feat(@angular/build): enable component template hot replacement by default

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, package.json, pnpm-lock.yaml, renovate.json
**ci: remove `ignorePaths` paths for `pnpm-lock.yaml`**
This does not work as expected because the paths are expected to be package files.
**build: update `engines` field in `package.json`**
This commit removes the `yarn` engine field. The `packageManager` version was previously removed, causing Renovate to pick up an outdated Yarn version. Additionally, Yarn Berry does not use this field, rendering it unnecessary.
**build: workaround for `ERROR: An error occurred during the fetch of repository 'npm2'`**
In some cases `yarn bazel run @npm2//:sync` will fail in the first run see: https://github.com/aspect-build/rules_js/issues/1445 as a workaround we run a build before.
```
ERROR: An error occurred during the fetch of repository 'npm2':
Traceback (most recent call last):
File …
```
=> Renovate fixes

renovate.json
Frce this fill to be generated by the tooling
=> ci: restore `pnpm-lock.yaml` that was updated by renovate

packages/angular/ssr/src/utils/inline-critical-css.ts
=> refactor(@angular/ssr): mark `LINK_LOAD_SCRIPT_CONTENT` as `@PURE`

packages/angular/ssr/node/src/request.ts, packages/angular/ssr/src/app.ts, packages/angular/ssr/test/app_spec.ts
Previously, when the application was served behind a proxy, server-side redirects generated an incorrect Location header, causing navigation issues. This fix updates `createRequestUrl` to use the port from the Host header, ensuring accurate in proxy environments. Additionally, the Location header now only contains the pathname, improving compliance with redirect handling in such setups.
Closes #29151
=> fix(@angular/ssr): ensure correct `Location` header for redirects behind a proxy

packages/angular_devkit/architect/node/node-modules-architect-host.ts
To avoid the need to perform Node.js resolution for the typical case of a relative builder schema, a check is now performed to determine if a schema path within the build manifest appears to be relative.
=> fix(@angular-devkit/architect): avoid Node.js resolution for relative builder schema

CHANGELOG.md
=> docs: release notes for the v19.0.6 release

tests/legacy-cli/e2e/tests/web-test-runner/basic.ts
Temporary disable this test due to
```
Failed to launch local browser installed at /home/runner/.cache/bazel/_bazel_runner/f47b8283cc0f5922f9455b06771398a1/sandbox/processwrapper-sandbox/410/execroot/angular_cli/bazel-out/k8-fastbuild/bin/tests/legacy-cli/e2e.npm_node22.sh.runfiles/org_chromium_chromium_linux_x64/chrome-linux/chrome.
This could be because of a mismatch between the version of puppeteer and Chrome or Chromium.
Try updating either of them, or adjust the executablePath option to point to another browser installation. Use the --puppeteer flag to run tests with bundled compatible version of Chromium.
dist/test-out/c48222bb-ca34-455e-bc1b-122521e1e71e/app.component.spec.js:
```
=> test: disable WTR e2e test

modules/testing/builder/projects/hello-world-app/protractor.conf.js
This fixes an issue where protractor integration tests are failing with
```
[07:38:37] I/direct - Using ChromeDriver directly...
[07:38:39] E/launcher - unknown error: Chrome failed to start: crashed.
(unknown error: DevToolsActivePort file doesn't exist)
```
=> test: add `--disable-dev-shm-usage` to address `WebDriverError: unknown error: Chrome failed to start: crashed`

tests/legacy-cli/e2e/tests/misc/check-postinstalls.ts
Added `resolve/test/list-exports/packages/tests/fixtures/resolve-1/project/test/resolver/multirepo/package.json as a false positive`
See: https://github.com/angular/angular-cli/actions/runs/12402554909/job/34638018185?pr=29134
=> test: add `resolve/test/list-exports` to false positive in postinstall scripts check

packages/angular/ssr/src/routes/ng-routes.ts
This commit fixes an issue where the components where still being bootstrapping when using `provideAppInitializer`
Closes #29131
=> fix(@angular/ssr): disable component boostrapping when running route extraction

packages/angular/build/src/tools/esbuild/javascript-transformer.ts
Node.js workers will currently fail to initialize if the `execArgv` option is used and it contains v8 specific options. This is currently problematic for the JS transformer worker because it contains a workaround to remove the SSR `--import` argument that is used to add a loader hook for SSR purposes. The filtering of the argument and subsequent use of the `execArgv` array had the potential to pass custom Node.js options to the worker and cause it to fail. These options can be passed by developers on the command line when invoking the Angular CLI.
To mitigate this problem, the `execArgv` option is now only filtered and used if the SSR import argument is present in the array. Otherwise, no value is passed which allows the default Node.js behavior to be used. While this does not fully solve …
=> fix(@angular/build): mitigate JS transformer worker `execArgv` errors

.bazelrc
Set the mnemonic to determine if it allows us to reduce the number of RBE queries executed
=> build: set a mnemonic for template expand and file write

packages/angular_devkit/build_angular/src/builders/karma/application_builder.ts
We should only force the type for files that we know are JavaScript. Otherwise we risk breaking the magic type detection done by Karma.
The previous code broke for `jasmine.css`.
Fixes https://github.com/angular/angular-cli/issues/29190
=> fix(@angular-devkit/build-angular): preserve css type for jasmine.css

packages/ngtools/webpack/BUILD.bazel, packages/ngtools/webpack/index.ts, tsconfig.json
The `@ngtools/webpack` package has been migrated to the `rules_js` ts_project rule.
Other than the `index.ts` addition, no code changes were needed.
=> build: migrate `@ngtools/webpack` to `ts_project`

packages/angular_devkit/build_webpack/BUILD.bazel
The `@angular-devkit/build-webpack` package has been migrated to the `rules_js` ts_project rule.
=> build: migrate `@angular-devkit/build-webpack` to `ts_project`

packages/angular_devkit/core/BUILD.bazel, packages/angular_devkit/core/index.ts, packages/angular_devkit/core/node/BUILD.bazel, packages/angular_devkit/core/node/testing/BUILD.bazel
Migrates `@angular-devkit/core` to `ts_project`.
=> build: migrate `angular_devkit/core` to `ts_project`

packages/angular/create/BUILD.bazel
The `@angular/create` package has been migrated to the `rules_js` ts_project rule.
=> build: migrate `@angular/create` to `ts_project`

modules/testing/builder/BUILD.bazel
The `modules/testing/builder` target used for builder integration testing has been migrated to the `rules_js` ts_project rule.
=> build: migrate modules/testing to ts_project

packages/schematics/angular/BUILD.bazel, packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel, tsconfig.json
The `@schematics/angular` package has been migrated to the `rules_js` ts_project rule.
=> build: migrate `@schematics/angular` to `ts_project`

packages/angular_devkit/schematics_cli/BUILD.bazel
The `@angular-devkit/schematics-cli` package has been migrated to the `rules_js` ts_project rule.
=> build: migrate `@angular-devkit/schematics-cli` to `ts_project`

packages/angular/cli/BUILD.bazel
The `@angular/cli` package has been migrated to the `rules_js` ts_project rule.
=> build: migrate `@angular/cli` to `ts_project`

packages/angular/pwa/BUILD.bazel
The `@angular/pwa` package has been migrated to the `rules_js` ts_project rule.
=> build: migrate `@angular/pwa` to `ts_project`

packages/angular/build/BUILD.bazel, packages/angular/build/index.ts, packages/angular/build/private/BUILD.bazel, packages/angular/build/private/index.ts, packages/angular_devkit/build_angular/BUILD.bazel, tsconfig.json
This commit migrates `@angular/build` to `ts_project`.
=> [Patch of #29224] build: migrate `@angular/build` to `ts_project`

tests/legacy-cli/BUILD.bazel, tests/legacy-cli/e2e/initialize/BUILD.bazel, tests/legacy-cli/e2e/setup/BUILD.bazel, tests/legacy-cli/e2e/tests/BUILD.bazel, tests/legacy-cli/e2e/utils/BUILD.bazel, tsconfig.json
The E2E tests have been migrated to the `rules_js` ts_project rule.
=> build: migrate E2E tests to `ts_project`

packages/angular/ssr/src/routes/route-config.ts
The double JSDoc start sequence was visible in the docs (https://angular.dev/api/ssr/provideServerRoutesConfig). This commit fixes it.
=> refactor(@angular/ssr): clean up comment.

packages/angular/build/src/tools/babel/plugins/pure-toplevel-functions.ts, packages/angular/build/src/tools/babel/plugins/pure-toplevel-functions_spec.ts
Fixes #29145
_defineProperty is marked as pure and then tree shaken when targeting Safari < 15 or Chrome < 84 which breaks the application.
Issue Number: #29145
_defineProperty is not marked as pure
=> fix(@angular/build): do not mark Babel _defineProperty helper function as pure

packages/angular/build/src/utils/server-rendering/fetch-patch.ts
Ensures proper handling of relative URLs to prevent errors in server-side fetch operations.
Closes #29236
=> fix(@angular/build): handle relative URLs when constructing new URLs during server fetch

packages/angular_devkit/architect/node/node-modules-architect-host.ts
When a builder is not defined a more actionable error message is now displayed.
Closes #29226
=> fix(@angular-devkit/architect): provide better error when builder is not defined

packages/angular/build/src/tools/vite/plugins/angular-memory-plugin.ts
This update resolves an issue that prevents SSR from functioning correctly on Windows when using the latest Vite.
=> refactor(@angular/build): normalize source path for windows compatibility

packages/angular/build/src/builders/dev-server/vite-server.ts
The dev-server will now leverage the incremental build result data from the application
builder. This removes the need to directly analyze all the newly built files within the
dev-server to determine what type of update is needed. Incremental build results also
only contain the files that are new and/or modified and removes the need to pass a potentially
large amount of file content between the application build and the dev-server.
=> refactor(@angular/build): support application incremental build result in dev-server

packages/angular_devkit/schematics/BUILD.bazel, packages/angular_devkit/schematics/index.ts, packages/angular_devkit/schematics/tasks/BUILD.bazel, packages/angular_devkit/schematics/tasks/node/BUILD.bazel, packages/angular_devkit/schematics/testing/BUILD.bazel, packages/angular_devkit/schematics/tools/BUILD.bazel, tsconfig.json
The `@angular-devkit/schematics` package has been migrated to the `rules_js` ts_project rule. The tsconfig path mappings for the `@angular-devkit` scope have also been cleaned up now that all the packages within this scope have been migrated.
=> build: migrate `@angular-devkit/schematics` to `ts_project`

.bazelrc
Use less jobs per bazel run to reduce the rate at which we perform API calls for RBE
=> ci: run less jobs per executor for RBE

packages/angular/build/BUILD.bazel
The integration tests for the application and dev-server targets within `@angular/build` have been separated into two bazel targets. This allows more fine-grained control of test options for each builder as well as reducing the overall size of each target.
=> test(@angular/build): separate application and dev-server integration test targets

.ng-dev/release.mjs
This ensures that the Bazel lock files are automatically updated.
See: https://github.com/angular/dev-infra/commit/289aa644e65a557bcb21adcf75ad60605a9c9859
=> ci: enable `rules_js` interop mode for ng-dev release tool

packages/angular/build/BUILD.bazel
Reference: https://github.com/angular/angular-build-builds/commit/3735297d21181b5885cf9a3625cb554c46efb8b3
=> build: resolve issue with uncompiled `@angular/build/private` being included

tools/interop.bzl
`rules_js` includes `tsconfig.json` files in the `DeclarationInfo` provider. This ends up causing these files to be part of the npm archives.
=> build: do not include tsconfig files in npm archives

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, package.json, pnpm-lock.yaml, yarn.lock
The current version does not support `rulesJsInteropMode` which causes the build to fail.
=> build: update `@angular/ng-dev` to support `rulesJsInteropMode`

packages/angular/build/src/builders/application/build-action.ts
The `application` builder may now return more than one build result per rebuild action. This will typically occur when using the development server with HMR enabled. In this scenario, component template update results may be sent to the development server in addition to incremental updates for global styles. TailwindCSS, for instance, may update the global stylesheet for an application based on the usage of styles within a given template.
Closes #29096
=> refactor(@angular/build): support multiple results per application build action

packages/angular/build/src/builders/dev-server/vite-server.ts
This change addresses recent updates in Vite that trigger pre-transform errors when SSR files (`/server.mjs`, `/main.server.mjs`) are missing. Skipping the configuration prevents unnecessary errors during the build process.
=> fix(@angular/build): skip vite SSR warmup file configuration when SSR is disabled

packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/build/src/tools/vite/utils.ts
This update ensures that the `define` option is correctly passed to Vite during the prebundling phase of the application builder, improving compatibility and optimization of the build process.
Closes #29278
=> fix(@angular/build): pass `define` option defined in application builder to Vite prebundling

packages/angular/ssr/src/routes/ng-routes.ts
Route matchers are not currently supported in Angular SSR. This commit ensures an error is issued when a route matcher is detected.
=> fix(@angular/ssr): throw error when using route matchers

packages/angular/build/src/utils/bundle-calculator.ts, packages/angular/build/src/utils/bundle-calculator_spec.ts
Fixes #29040
Issue Number: #29040
It uses kb value from packages/angular/build/src/utils/bundle-calculator.ts so there is no difference in value when running tests
=> fix(@angular/build) : fix incorrect budget calculation

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, BUILD.bazel, WORKSPACE, package.json, packages/angular/ssr/BUILD.bazel, packages/angular/ssr/node/BUILD.bazel, packages/angular/ssr/node/test/BUILD.bazel, packages/angular/ssr/schematics/BUILD.bazel, packages/angular/ssr/test/BUILD.bazel, packages/angular/ssr/test/npm_package/BUILD.bazel, packages/angular/ssr/third_party/beasties/BUILD.bazel, patches/@angular+bazel+19.1.0-next.4.patch, pnpm-lock.yaml, tools/interop.bzl, tsconfig-build-ng.json, yarn.lock
Migrates `@angular/ssr` to `ts_project`. Possible after various upstream fixes for `ng_package` and interop changes.
=> build: migrate `@angular/ssr` to `ts_project`

.bazelrc
Placing all of the node_modules files into remote cache is too much
=> ci: prevent `NpmPackageExtract` results from being placed remote cache

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, BUILD.bazel, WORKSPACE, package.json, packages/angular/ssr/BUILD.bazel, packages/angular/ssr/node/BUILD.bazel, packages/angular/ssr/node/test/BUILD.bazel, packages/angular/ssr/schematics/BUILD.bazel, packages/angular/ssr/test/BUILD.bazel, packages/angular/ssr/test/npm_package/BUILD.bazel, packages/angular/ssr/third_party/beasties/BUILD.bazel, patches/@angular+bazel+19.1.0-next.4.patch, pnpm-lock.yaml, tools/interop.bzl, tsconfig-build-ng.json, yarn.lock
Migrates `@angular/ssr` to `ts_project`. Possible after various upstream fixes for `ng_package` and interop changes.
Patch of #29272
=> [19.0.x] build: migrate `@angular/ssr` to `ts_project`

packages/angular/build/src/tools/esbuild/angular-localize-init-warning-plugin.ts, packages/angular/build/src/tools/esbuild/application-code-bundle.ts
Importing `@angular/localize/init` directly can cause unpredictable behavior, as highlighted in multiple reports:
- https://github.com/angular/angular/issues/59422
- https://github.com/angular/angular/issues/48545
- https://github.com/angular/angular/issues/59405
=> fix(@angular/build): warn when `@angular/localize/init` is imported directly

goldens/public-api/angular/build/index.api.md, packages/angular/build/BUILD.bazel, packages/angular/build/builders.json, packages/angular/build/package.json, packages/angular/build/src/builders/ng-packagr/builder.ts, packages/angular/build/src/builders/ng-packagr/index.ts, packages/angular/build/src/builders/ng-packagr/schema.json, packages/angular/build/src/index.ts, packages/angular/cli/BUILD.bazel, packages/angular/cli/lib/config/workspace-schema.json, packages/schematics/angular/library/index.ts, packages/schematics/angular/library/index_spec.ts, packages/schematics/angular/migrations/use-application-builder/migration.ts, packages/schematics/angular/utility/latest-versions.ts, packages/schematics/angular/utility/workspace-models.ts
To support migration to the `@angular/build` package which contains the
`application` builder that is used by all new projects, the `ng-packagr`
builder used to build Angular libraries is also now available within this
package. This removes the need for projects that are using the application
builder but also would like to build a library from having to install the
Webpack related `@angular-devkit/build-angular` package.  This can result
in a significant reduction in overall Node.js packages installed within the
project.
=> feat(@angular/build): add ng-packagr builder to the package 

CHANGELOG.md
=> docs: release notes for the v19.0.7 release

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, CHANGELOG.md, package.json
Also this PR cherry-picks the changelog for v19.1.0-rc.0 into the main branch so that the changelog is up to date.
=> Update next branch to reflect new release-train "v19.2.0-next.0".

packages/angular/build/src/tools/esbuild/application-code-bundle.ts
This update ensures proper handling of loaders in SSR bundles when packages are marked as external dependencies.
Closes #29235
=> fix(@angular/build): handle loaders correctly in SSR bundles for external packages

packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/build/src/utils/environment-options.ts
The newly stable template HMR support has also been improved to support hot replacement of component stylesheets. While this is not as fast during a rebuild as external stylesheet based HMR, it does currently avoid some edge cases with the current implementation. Once these cases are resolved, the default may be reverted to the previous setup.
If the previous behavior is preferred, the `NG_HMR_CSTYLES=1` environment variable can be used.
=> fix(@angular/build): use component updates for component style HMR

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, .ng-dev/commit-message.mjs, package.json, pnpm-lock.yaml, yarn.lock
Fixup commit messages are not permitted in this repository. This update modifies the `ng-dev` commit message validator configuration to prevent such commits.
(cherry picked from commit 55f7d87a5806359a7e7711cd2a5435568bd7aa50)
=> ci: disable fixup commit messages

tests/legacy-cli/e2e/utils/process.ts
Previously, if `waitForMatch` failed to find a match, the CI process could hang indefinitely. This commit updates the method to ensure it fails after a 60-second timeout, preventing such blocks.
Example: https://github.com/angular/angular-cli/actions/runs/12709516529/job/35428835418?pr=29318
=> build: update `_exec` to handle timeouts gracefully when `waitForMatch` does not match within 60 seconds.

packages/angular/build/src/builders/application/build-action.ts, packages/angular/build/src/builders/application/tests/behavior/rebuild-assets_spec.ts, packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/build/src/tools/esbuild/bundler-execution-result.ts, packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts, packages/angular/build/src/tools/vite/plugins/setup-middlewares-plugin.ts, packages/angular/build/src/tools/vite/utils.ts
**fix(@angular/build): trigger browser reload on asset changes with Vite dev server**
Ensures the Vite-based development server automatically reloads the browser when asset files are modified.
Closes #26141
**fix(@angular/build): remove deleted assets from output during watch mode**
This commit ensures that assets deleted from the source are also removed from the output directory while in watch mode. Previously, deleted assets could persist in the output folder, potentially causing inconsistencies or outdated files to be served. This fix improves the accuracy of the build output by maintaining synchronization between the source and the output directory during development.
=> Multiple asset fixes for Vite and the application builder in watch mode

packages/angular/build/src/utils/i18n-options.ts
The `subPath` validation function was not being called.
=> fix(@angular/build): correctly validate locales `subPath`

packages/angular/build/BUILD.bazel, packages/angular/cli/BUILD.bazel, tools/bazel/npm_package.bzl
=> Update more packages to `npm_package`

packages/angular/cli/src/utilities/version.ts
Previously, the version was retrieved from the `package.json`. With this update, the version is now sourced using Bazel stamping.
=> refactor(@angular/cli): replace `VERSION` with Bazel-stamped version

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, package.json, pnpm-lock.yaml, scripts/diff-release-package.mts
This script will be very useful for the `rules_js` migration, as it allows us to quickly spot differences between the local `npm_package` target and the valid golden (based on the snapshot repository).
=> [19.1.x] build: add script to diff local npm package with snapshot repository

packages/ngtools/webpack/BUILD.bazel
This allows us to use the package in the RJS pnpm workspace.
=> build: migrate @ngtools/webpack to npm_package

goldens/public-api/angular_devkit/schematics/index.api.md, packages/angular_devkit/schematics/src/engine/interface.ts, packages/angular_devkit/schematics/src/rules/base_spec.ts
The `Rule` type has been updated to align with its intended functionality, allowing it to return a `Promise<Tree>`. Previously, this behavior was supported but not properly typed.
Closes #22783
=> fix(@angular-devkit/schematics): update `Rule` type to support returning a `Promise` of `Tree`

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
If both the `isolatedModules` and `emitDecoratorMetadata` Typescript options are enabled within a project, a warning will now be issued explaining that not all metadata may be emitting for each decorator. Isolated modules may not have access to non-local type information that would otherwise be needed for complete metadata emit.
The `emitDecoratorMetadata` option is not required by Angular and can cause runtime errors due to its underlying implementation when used with ES2015+ output. The option is only compatible with the experimental decorators and cannot be used with standard decorators. New Angular projects also do not enable this option. Removing the `emitDecoratorMetadata` option will remove the warning.  The majority of projects do not require the option and it may cease to …
=> fix(@angular/build): warn when using both `isolatedModules` and `emitDecoratorMetadata`

packages/ngtools/webpack/src/benchmark.ts, packages/ngtools/webpack/src/ivy/host.ts, packages/ngtools/webpack/src/ivy/loader.ts, packages/ngtools/webpack/src/loaders/inline-resource.ts, packages/ngtools/webpack/src/resource_loader.ts, packages/ngtools/webpack/src/transformers/spec_helpers.ts
Functions that are exported from files within the `@ngtools/webpack` package now contain return types. This improves code readability as well as being a requirement for eventual isolated declarations usage.
=> refactor(@ngtools/webpack): add return types to functions

packages/angular/build/src/builders/application/execute-build.ts, packages/angular/build/src/builders/application/setup-bundling.ts, packages/angular/build/src/private.ts, packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts, packages/angular/build/src/tools/esbuild/application-code-bundle.ts, packages/angular/build/src/tools/esbuild/compiler-plugin-options.ts
The creation of the internal Angular compilation used by the internal esbuild plugin is now created within the main execution phase of the build process. This is causes no behavior changes but provides the infrastructure for several addition refactoring improvements including performance improvements of the HMR process. The private API for the `createCompilerPlugin` has kept its function signature and currently is not affected by this change.
=> refactor(@angular/build): move Angular compilation creation to build execution

packages/schematics/angular/BUILD.bazel
This allows us to use the package in the RJS pnpm workspace.
=> build: migrate @schematics/angular to npm_package

packages/ngtools/webpack/src/ivy/index.ts, packages/ngtools/webpack/src/ivy/paths.ts, packages/ngtools/webpack/src/ivy/plugin.ts, packages/ngtools/webpack/src/ivy/symbol.ts, packages/ngtools/webpack/src/loaders/inline-resource.ts
Adding explicit type information for a module's exported variables allows the `@ngtools/webpack` package to be built with the `isolatedDeclarations` option.
=> refactor(@ngtools/webpack): add types to exported module variables

packages/angular_devkit/schematics_cli/BUILD.bazel
This allows us to use the package in the RJS pnpm workspace.
=> build: migrate @angular-devkit/schematics-cli to npm_package

CHANGELOG.md
=> docs: release notes for the v19.1.0 release

packages/angular/build/src/tools/vite/plugins/angular-memory-plugin.ts
Improved handling of Angular prefixed files when using Vite dev-server with SSR. Updated logic ensures proper resolution of `file://` files paths with query strings.
Closes #29364
=> fix(@angular/build): resolve HMR-prefixed files in SSR with Vite

CHANGELOG.md
=> docs: release notes for the v19.1.1 release

tools/package_json_release_filter.jq
Currently, the `pnpm` and `dependenciesMeta` fields from the root `package.json` are inadvertently copied to the `package.json` of published packages.
For example, see: https://github.com/angular/angular-devkit-schematics-builds/blob/dc4d5e0d523e3449963fa8e6efa32aee3e194e0f/package.json#L42-L52
=> build: exclude `pnpm` and `dependenciesMeta` fields from published NPM packages

packages/angular/build/src/builders/application/build-action.ts, packages/angular/build/src/builders/application/results.ts, packages/angular/build/src/builders/dev-server/vite-server.ts
When HMR is enabled, a change to a lazy route component template may alter the names of lazy chunks. These lazy chunks must be updated within the development server so that any later non-HMR based update will have access to these chunks. To support this, the incremental results from the build process can now emit background file updates that will provide output file changes without triggering client updates.
=> fix(@angular/build): perform incremental background file updates with component updates

constants.bzl, docs/process/release.md, packages/angular/build/package.json, packages/angular/pwa/package.json, packages/angular/ssr/package.json, packages/angular_devkit/build_angular/package.json, packages/ngtools/webpack/package.json, packages/schematics/angular/library/index.ts, packages/schematics/angular/library/index_spec.ts, packages/schematics/angular/utility/latest-versions.ts, packages/schematics/angular/utility/latest-versions/package.json, tools/substitutions.bzl
Refactor the build configuration to use Bazel stamping for Angular and ng-packagr dependencies, eliminating the need for hardcoded peer dependencies.
=> build: replace hardcoded Angular and ng-packagr peer dependencies with Bazel stamping

renovate.json
This will prevent updates to any version matching the pattern `/0\.0\.0-/`.
=> ci: disable Renovate updates for all stamped versions

packages/angular/build/src/builders/application/build-action.ts, packages/angular/build/src/builders/dev-server/vite-server.ts
This commit resolves an issue where HMR would incorrectly trigger a full page reload when used with SSR.
Closes #29372
=> fix(@angular/build): prevent full page reload on HMR updates with SSR enabled

packages/angular/build/src/builders/dev-server/vite-server.ts
An informational message has been added to the development server to ensure that users are aware that component HMR has been enabled and provide actionable steps in the event that an application reload may not behave as expected.
=> refactor(@angular/build): add console message to dev server when component HMR is enabled

CHANGELOG.md
=> docs: release notes for the v19.1.2 release

packages/angular/build/src/tools/vite/middlewares/component-middleware.ts, packages/angular/build/src/tools/vite/plugins/angular-memory-plugin.ts, packages/angular/build/src/tools/vite/plugins/setup-middlewares-plugin.ts
This update serves as a preparatory step to address #29248. The change involves modifying the line 'urlPartial'  in [r3_hmr_compiler.ts](https://github.com/angular/angular/blob/4e6017a9f5cda389c5fbf4f2c1519ce1bba23e11/packages/compiler/src/render3/r3_hmr_compiler.ts#L57) to start with `./` instead of `/`.
=> fix(@angular/build): handle relative `@ng/components`

packages/angular/build/src/builders/dev-server/tests/options/hmr_spec.ts
Tests of the development server's console message output for the `hmr` option including enabled, disabled, and default cases.
=> test(@angular/build): add dev-server HMR enabled console message tests

packages/angular/build/src/builders/application/build-action.ts
Changes to asset files were previously not considered when determining if an incremental build result could be background update and not cause a page reload. Asset modifications will not cause a page reload in incremental update cases.
Additionally, a superfluous component update result will no longer be emitted in this case. The required page reload will account for the component updates.
Review Note: Enable hide whitespace for a more readable diff
=> fix(@angular/build): allow asset changes to reload page on incremental updates

packages/angular/build/src/tools/angular/compilation/aot-compilation.ts
Component template updates that contain `$localize` usage currently may result in incorrect updates at runtime. To avoid this problem, any template update module that contains `$localize` will now perform a full rebuild. Support for component updates of these templates will be added in a future release.
=> fix(@angular/build): perform full reload for templates with `$localize` usage

packages/angular/build/src/builders/dev-server/tests/behavior/build_localize_replaced_watch_spec.ts
The existing test for i18n `$localize` replacement during watch mode has been re-enabled.
=> test(@angular/build): enable i18n localize watch test for dev-server

CHANGELOG.md
=> docs: release notes for the v19.1.3 release

packages/angular/ssr/src/routes/ng-routes.ts
Although route matchers are not supported with the SSR Routing API, they still function with the legacy `CommonEngine`. Therefore, no error should be issued in this case.
Closes #29420
=> fix(@angular/ssr): prevent route matcher error when SSR routing is not used

packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/test/routes/ng-routes_spec.ts, packages/angular/ssr/test/testing-utils.ts
This fix ensures that route extraction is not blocked when `withEnabledBlockingInitialNavigation` is used.
Closes #29400
=> fix(@angular/ssr): unblock route extraction with `withEnabledBlockingInitialNavigation`

packages/angular/build/src/tools/vite/plugins/angular-memory-plugin.ts
The `virtualProjectRoot` is normalized, but `sourcePath` is not, leading to mismatched path slashes and related issues.
Closes #29424
=>  fix(@angular/build): correct path for `/@ng/components` on Windows

goldens/public-api/angular/build/index.api.md, goldens/public-api/angular_devkit/build_angular/index.api.md, packages/angular/build/src/builders/application/index.ts, packages/angular/build/src/builders/dev-server/index.ts, packages/angular/build/src/builders/extract-i18n/index.ts, packages/angular/build/src/builders/ng-packagr/index.ts, packages/angular_devkit/build_angular/src/builders/dev-server/tests/jasmine-helpers.ts, packages/angular_devkit/build_angular/src/builders/protractor/index.ts, packages/angular_devkit/build_angular/src/builders/ssr-dev-server/index.ts, packages/angular_devkit/build_webpack/BUILD.bazel, packages/angular_devkit/build_webpack/src/builders/webpack-dev-server/index.ts, packages/angular_devkit/build_webpack/src/builders/webpack/index.ts, tools/quicktype_runner.js
By converting schemas from TypeScript `interfaces` to `types`, we can minimize the reliance on `json.JsonObject`. This approach avoids the error "Type 'Schema' does not satisfy the constraint 'JsonObject'" caused by the missing index signature for type 'string' in 'Schema'.
=> refactor: reduce dependencies on `@angular-devkit/core`

packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/utils/i18n-options.ts, packages/angular/cli/lib/config/workspace-schema.json
In certain scenarios, users build applications with the same `baseHref` when using i18n, primarily for deploying localized applications across multiple domains. To address this, we are removing the deprecation of `i18n.baseHref` and will revisit potential options as part of https://github.com/angular/angular-cli/issues/29111
Instead of deprecating `i18n.baseHref`, we now issue a warning when it is used with SSR, as this may lead to undefined behavior.
Closes #29396
=> fix(@angular/build): replace deprecation of `i18n.baseHref` with a warning

tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js
For some reason it seems all Linux tests are failing
```
[15:25:13] I/testLogger - [chrome 132 Linux #01] PID: 17353
[chrome 132 Linux #01] Specs: /tmp/angular-cli-e2e-HZAJ55/e2e-test/test-project/e2e/src/app.e2e-spec.ts
[chrome 132 Linux #01]
[chrome 132 Linux #01] [15:24:49] I/sauce - Using SauceLabs selenium server at https://ondemand.saucelabs.com:443/wd/hub
[chrome 132 Linux #01] Jasmine started
[chrome 132 Linux #01] [15:25:10] E/protractor - Could not find Angular on page http://localhost:2000/ : retries looking for angular exceeded
```
https://github.com/angular/angular-cli/actions/runs/12890037755/job/35938861009
=> ci: replace platform linux with windows 11

packages/angular/build/src/utils/i18n-options.ts
The i18n configuration validation was incorrectly flagging errors for identical `subPaths` when both locales were not inlined within the same build. This was due to the validation not properly accounting for the inlining of locales.
This commit fixes this issue by ensuring that the validation only checks for duplicate `subPaths` when the locales are inlined.
Closes #29398
=> fix(@angular/build): only issue invalid i18n config error for duplicate `subPaths` with inlined locales

packages/angular/build/src/builders/application/execute-post-bundle.ts, packages/angular/build/src/utils/server-rendering/prerender.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-static.ts
This commit ensures that extracted routes are added to the manifest during prerendering. This guarantees a correct ng-server-context value for parameterized routes and provides a performance benefit by preventing route extraction from being repeated for every rendering worker.
Closes #29426
=> fix(@angular/build): include extracted routes in the manifest during prerendering

packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/src/routes/route-tree.ts, packages/angular/ssr/test/routes/route-tree_spec.ts
This fix ensures that catch-all routes (e.g., wildcard routes like `**`) are handled correctly when a base href is configured in an Angular SSR application.
Closes #29397
=> fix(@angular/ssr): properly manage catch-all routes with base href

packages/angular/ssr/src/routes/route-tree.ts
This change modifies the `getPathSegments` function to use `stripTrailingSlash`, providing a more consistent and reliable way to handle trailing slashes in paths. This update also resolves issues causing CI failures.
=> refactor(@angular/ssr): update `getPathSegments` to use `stripTrailingSlash` instead of `filter(Boolean)`

CHANGELOG.md
=> docs: release notes for the v19.1.4 release

packages/angular/ssr/src/routes/route-tree.ts
The `segment` property within the route-tree metadata is redundant and serves no functional purpose. Therefore, it has been removed.
=> refactor(@angular/ssr): remove unused `segment` property from metadata

packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/build/src/tools/vite/middlewares/ssr-middleware.ts
Ensure that accessing the module after invalidation doesn't result in an empty module, which causes a `TypeError: ɵgetOrCreateAngularServerApp is not a function`.
Closes #29458 and closes #29443
=> fix(@angular/build): handle empty module case to avoid TypeError

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/dev-server/options.ts, packages/angular/build/src/builders/dev-server/schema.json, packages/angular/build/src/builders/dev-server/tests/execute-fetch.ts, packages/angular/build/src/builders/dev-server/tests/options/allowed-hosts_spec.ts, packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts, packages/angular_devkit/build_angular/src/builders/dev-server/schema.json
Vite version 6.0.9+, which is now used by the Angular CLI, contains a potentially breaking change for some development setups. Examples of such setups include those that use reverse proxies or custom host names during development. The change within a patch release was made by Vite to address a security vulnerability. For projects that directly access the development server via `localhost`, no changes should be needed. However, some development setups may now need to adjust the newly introduced `allowedHosts` development server option. This option can include an array of host names that are allowed to communicate with the development server. The option sets the corresponding Vite option within the Angular CLI. For more information on the option and its specific behavior, please see the …
=> fix(@angular/build): support Vite `allowedHosts` option for development server

packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/src/routes/route-tree.ts, packages/angular/ssr/test/routes/ng-routes_spec.ts, packages/angular/ssr/test/routes/route-tree_spec.ts
Updated route matching logic to prioritize closest matches, improving the accuracy of dynamic route resolution. Also we optimized performance by eliminating unnecessary recursive checks, reducing overhead during route matching.
Closes #29452
=> fix(@angular/ssr): enhance dynamic route matching for better performance and accuracy

packages/angular/build/src/tools/angular/compilation/angular-compilation.ts, packages/angular_devkit/build_angular/src/tools/webpack/plugins/typescript.ts
Disables TypeScript's `removeComments` option to ensure important annotations like `/* @__PURE__ */` and `/* vite-ignore */` are preserved. TypeScript's comment removal can be too aggressive, potentially stripping out critical information needed by bundlers for dead code elimination. Non-essential comments will be handled by the bundler, so removing them in TypeScript isn't necessary and could lead to an increase in the final bundle size.
Closes #29470
=> fix(@angular/build): disable TypeScript `removeComments` option

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, goldens/public-api/angular/build/index.api.md, package.json, packages/angular/build/package.json, packages/angular/build/src/builders/dev-server/options.ts, packages/angular/build/src/builders/dev-server/schema.json, packages/angular/build/src/builders/dev-server/tests/execute-fetch.ts, packages/angular/build/src/builders/dev-server/tests/options/allowed-hosts_spec.ts, packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts, packages/angular_devkit/build_angular/src/builders/dev-server/schema.json, pnpm-lock.yaml, yarn.lock
Version update from 6.0.7 to address advisory https://github.com/vitejs/vite/security/advisories/GHSA-vg6x-rcgg-rjx6
Vite version 6.0.9+, which is now used by the Angular CLI with the `application`/`browser-esbuild` builders, contains a potentially breaking change for some development setups. Examples of such setups include those that use reverse proxies or custom host names during development. The change within a patch release was made by Vite to address a security vulnerability. For projects that directly access the development server via `localhost`, no changes should be needed. However, some development setups may now need to adjust the `allowedHosts` development server option. This option can include an array of host names that are allowed to communicate with the development server. …
=> fix(@angular/build): update vite to version 6.0.11

packages/angular/build/src/builders/application/build-action.ts, packages/angular/build/src/builders/dev-server/vite-server.ts
In some cases a change to a component template may cause changes to other aspects of the application. Tailwind, for instance, may cause changes to the global stylesheets when class usage is changed in a template. To support hot module replacement of the component template in these cases, stylesheet changes are now analyzed and separated during the update process. This allows both a hot update of the template and the global stylesheet during the rebuild instead of the previously required full page reload.
Closes #29440
=> fix(@angular/build): support template updates that also trigger global stylesheet changes

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, packages/angular/build/package.json, packages/angular_devkit/build_angular/package.json
To support usage of the newly released Tailwind CSS 4.0.0, the peer dependency range has been update to include `^4.0.0`. This prevents potential installation warnings/error when using various package managers. Use of Tailwind CSS 4+ requires either the `application` (new project default) or `browser-esbuild` builder. Both of which support custom postcss configuration via a `.postcssrc.json` file.
For instructions on the setup of Tailwind CSS with Angular, please see the Tailwind CSS documentation here: https://tailwindcss.com/docs/installation/framework-guides/angular
=> fix(@angular/build): allow tailwindcss 4.x as a peer dependency

goldens/public-api/angular/build/index.api.md, modules/testing/builder/projects/hello-world-app/protractor.conf.js, package.json, packages/angular/build/package.json, packages/angular/build/src/builders/dev-server/options.ts, packages/angular/build/src/builders/dev-server/schema.json, packages/angular/build/src/builders/dev-server/tests/execute-fetch.ts, packages/angular/build/src/builders/dev-server/tests/options/allowed-hosts_spec.ts, packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/cli/src/commands/add/cli.ts, packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts, packages/angular_devkit/build_angular/src/builders/dev-server/schema.json, tests/legacy-cli/e2e/tests/web-test-runner/basic.ts, yarn.lock
Version update from 5.4.6 to address advisory https://github.com/vitejs/vite/security/advisories/GHSA-vg6x-rcgg-rjx6
Vite version 5.4.12+, which is now used by the Angular CLI with the `application`/`browser-esbuild` builders, contains a potentially breaking change for some development setups. Examples of such setups include those that use reverse proxies or custom host names during development. The change within a patch release was made by Vite to address a security vulnerability. For projects that directly access the development server via `localhost`, no changes should be needed. However, some development setups may now need to adjust the `allowedHosts` development server option. This option can include an array of host names that are allowed to communicate with the development server. …
=> fix(@angular/build): update vite to version 5.4.14

packages/angular/build/README.md, packages/angular/cli/README.md
The link to the README was relative, which caused it to break when viewed on the npm repository. The link has been updated to an absolute URL to ensure it works properly.
Closes #29489
- [ x] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ x] Docs have been added / updated (for bug fixes / features)
- [x ] Documentation content changes
- [ x] No
=> fix(@angular/cli): fix relative link to README not working on npm repo

goldens/public-api/angular/ssr/index.api.md, packages/angular/ssr/public_api.ts, packages/angular/ssr/src/routes/route-config.ts, packages/angular/ssr/test/testing-utils.ts, packages/schematics/angular/app-shell/index.ts, packages/schematics/angular/app-shell/index_spec.ts, packages/schematics/angular/server/files/application-builder/ngmodule-src/app/app.module.server.ts.template, packages/schematics/angular/server/files/application-builder/standalone-src/app/app.config.server.ts.template
This commit renames `provideServerRoutesConfig` to `provideServerRouting` and updates the second parameter to use the `ServerRoutes` features.
This change improves alignment with the framework's API conventions and the way features are integrated.
Before:
```typescript
provideServerRoutesConfig(serverRoutes, { appShellRoute: 'shell' })
```
After:
```typescript
provideServerRouting(serverRoutes, withAppShell(AppShellComponent))
```
=> fix(@angular/ssr): rename `provideServerRoutesConfig` to `provideServerRouting`

packages/angular/build/BUILD.bazel, packages/angular/build/src/utils/version.ts
This update replaces the resolution of peer dependency versions with the use of the Bazel stamp for improved consistency and reliability.
Closes #29504
=> fix(@angular/build): utilize bazel stamp instead of resolving peer dependency versions

packages/angular/build/src/builders/dev-server/vite-server.ts
The development server now supports a WebSocket event named `angular:log`. This event allows the browser client to send log messages back to the development server. Currently this is unused by the client and Angular runtime. But is intended to be used in the future for such cases as propagating error messages back to the development server console. This event is considered internal and should not be relied upon by external code.
=> refactor(@angular/build): allow browser client to log console message with dev-server

packages/angular/build/src/utils/version.ts
Cleaned up legacy version-checking logic.
=> refactor(@angular/build): remove outdated version checks

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, packages/angular/build/package.json, pnpm-lock.yaml
The `@angular-devkit/core` package is not needed at runtime within the `@angular/build` package.
=> refactor(@angular/build): move `@angular-devkit/core` to a development dependency

packages/schematics/angular/library/index.ts, packages/schematics/angular/library/index_spec.ts
The library schematic currently relies on Karma, which requires `@angular-devkit/build-angular` to be installed. To address this, we now use the `ng-packagr` builder provided in this package.
Closes #29494
=> fix(@schematics/angular): update library schematic to use `@angular-devkit/build-angular:ng-packagr`

packages/angular/build/src/builders/application/build-action.ts
When HMR is enabled and a component update is sent to the development server, the following background incremental update will no longer remove the previous JavaScript chunk files for lazy routes. This allows the active and running application code within the browser to still access the lazy chunks referenced in the code. This is important for cases such as when a component in a lazy route (that has not yet been accessed) is modified. In this case, the component update is still processed if/when the lazy route is eventually accessed via the module-time evaluation of the component update code.
Closes #29507
=> fix(@angular/build): keep background referenced HMR update chunks

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, WORKSPACE, modules/testing/builder/package.json, modules/testing/builder/projects/hello-world-app/src/tsconfig.server.json, modules/testing/builder/src/test-utils.ts, package.json, packages/angular/build/src/utils/service-worker.ts, packages/angular_devkit/build_angular/BUILD.bazel, packages/angular_devkit/build_angular/package.json, packages/angular_devkit/build_angular/src/builders/browser/specs/cross-origin_spec.ts, packages/angular_devkit/build_angular/src/builders/browser/specs/lazy-module_spec.ts, packages/angular_devkit/build_angular/src/builders/browser/specs/source-map_spec.ts, packages/angular_devkit/build_angular/src/builders/browser/tests/options/named-chunks_spec.ts, packages/angular_devkit/build_angular/src/builders/browser/tests/options/styles_spec.ts, packages/angular_devkit/build_angular/test/hello-world-lib/BUILD.bazel, pnpm-lock.yaml, pnpm-workspace.yaml
Migrates the `@angular-devkit/build-angular` tests to `rules_js`. This was a rather larger undertaking as the tests were very reliant on e.g. the directory structure or specific node module layout; so some changes were needed.
- the Sass files include a much larger file header now. That is because the npm Sass files have much larger paths, given being inside a symlinked pnpm store directory. E.g.
```
/*!**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************!*\
!*** css …
```
=> build: migrate `@angular-devkit/build-angular` tests to `rules_js`

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, WORKSPACE, modules/testing/builder/package.json, modules/testing/builder/projects/hello-world-app/src/tsconfig.server.json, modules/testing/builder/src/test-utils.ts, package.json, packages/angular/build/src/utils/service-worker.ts, packages/angular_devkit/build_angular/BUILD.bazel, packages/angular_devkit/build_angular/package.json, packages/angular_devkit/build_angular/src/builders/browser/specs/cross-origin_spec.ts, packages/angular_devkit/build_angular/src/builders/browser/specs/lazy-module_spec.ts, packages/angular_devkit/build_angular/src/builders/browser/specs/source-map_spec.ts, packages/angular_devkit/build_angular/src/builders/browser/tests/options/named-chunks_spec.ts, packages/angular_devkit/build_angular/src/builders/browser/tests/options/styles_spec.ts, packages/angular_devkit/build_angular/test/hello-world-lib/BUILD.bazel, pnpm-lock.yaml, pnpm-workspace.yaml
=> [19.1.x]: build: migrate `@angular-devkit/build-angular` tests to `rules_js`

CHANGELOG.md
=> docs: release notes for the v18.2.13 release

packages/angular_devkit/build_angular/package.json, yarn.lock
This resolves advisory GHSA-vg6x-rcgg-rjx6
Fixes #29464
=> fix(@angular-devkit/build-angular): remove unused vite dependency 

CHANGELOG.md
=> docs: release notes for the v18.2.14 release

packages/angular/ssr/src/app-engine.ts, packages/angular/ssr/test/app-engine_spec.ts
When redirecting to the preferred locale, the previous implementation used the full URL for the 302 redirect to i18n subpaths based on the user's preferred locale. This update ensures that the redirect now uses the locale-specific pathname instead of the full URL.
Closes #29514
=> fix(@angular/ssr): redirect to locale pathname instead of full URL

constants.bzl
```
Discovered errors when validating dependency ranges.
- latest-versions: Invalid dependency range for "ng-packagr". Expected: ^19.2.0-next.0
- latest-versions: Invalid dependency range for "@angular/core". Expected: ^19.2.0-next.0
Please fix these failures before publishing a new release.
These checks can be forcibly ignored by setting: SKIP_DEPENDENCY_RANGE_PRECHECK=1
```
=> build: update framework and ng-packagr peer-deps

packages/angular_devkit/core/src/json/schema/registry.ts, packages/angular_devkit/core/src/json/schema/visitor.ts, packages/angular_devkit/core/src/logger/logger.ts, packages/angular_devkit/core/src/utils/priority-queue.ts, packages/angular_devkit/core/src/virtual-fs/host/alias.ts, packages/angular_devkit/core/src/virtual-fs/path.ts, packages/angular_devkit/core/src/workspace/json/metadata.ts
Adding explicit type information for function return types is needed to allow the `@angular-devkit/core` package to eventually be built with the `isolatedDeclarations` option.
=> refactor(@angular-devkit/core): add missing function return types

packages/angular/build/src/utils/version.ts
In the FW integration tests the packages version is `0.0.0`. This commit update the compatibility version check to account for this.
=> refactor(@angular/build) update version check to account for unreleased FW packages 

scripts/release-checks/dependency-ranges/index.mts, scripts/release-checks/dependency-ranges/latest-versions-check.mts, scripts/release-checks/dependency-ranges/peer-deps-check.mts
This commit restores the latest version checks, which are now fixed by using the stamped versions.
=> build: re-enable latest version checks during release

packages/angular/build/src/builders/application/execute-post-bundle.ts
This change ensures that the server manifest is not generated if none of the server-related features are enabled.
Closes #29443
=> fix(@angular/build): prevent server manifest generation when no server features are enabled

packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/test/routes/ng-routes_spec.ts
This commit adds support for custom route matchers in Angular SSR, allowing fine-grained control over the `renderMode` (Server, Client) for individual routes, including those defined with matchers.
Routes with custom matchers are **not** supported during prerendering and must explicitly define a `renderMode` of either server or client.
The following configuration demonstrates how to use glob patterns (including recursive `**`) to define server-side rendering (SSR) or client-side rendering (CSR) for specific parts of the 'product' route and its child routes.
```typescript
// app.routes.ts
import { Routes } from '@angular/router';
export const routes: Routes = [
{
path: '',
component: DummyComponent,
},
{
path: 'product',
component: DummyComponent,
children: [
{
path: '',
component: …
```
=> feat(@angular/ssr): Add support for route matchers with fine-grained render mode control

.github/codeql/config.yml, .github/workflows/codeql.yml
Moving to the configuration being in the repo allows us to specify which specific rules are run in analysis.
=> ci: configure codeql locally within the repo to allow for customization

packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/test/routes/ng-routes_spec.ts
Ensures that the SSR router gives precedence to the first matching route, addressing the issue where later conflicting routes.
This change prevents the incorrect prioritization of routes and ensures the intended route is matched first, aligning routing behavior.
Closes: #29539
=> fix(@angular/ssr): prioritize the first matching route over subsequent ones

scripts/build-schema.mts
If the chunk happens to end in a new line or other meaningful whitespace, stripping it can lead to two words (e.g. targets) being squished together and broken.
=> build: Preserve newlines when gathering stdout

packages/schematics/angular/migrations/update-ssr-imports/migration.ts, packages/schematics/angular/migrations/update-ssr-imports/migration_spec.ts
This commit updates the `update-ssr-imports` migration to not run when the @angular/ssr` package is not listed as a dependency.
Closes #29560
=> fix(@schematics/angular): skip ssr migration when `@angular/ssr` is not a dependency

packages/angular/ssr/src/routes/ng-routes.ts
Replace `filter` and `map` with a `for...of` loop to improve readability in the preload append logic within metadata.
=> refactor(@angular/ssr): simplify preload append logic in metadata

packages/angular/build/src/builders/dev-server/vite-server.ts
If HMR is enabled, a component update has the potential to be unsupported at runtime or may cause an exception. While build time analysis attempts to verify that an update is possible, there could be cases that are as of yet unknown. For those cases, the runtime can now signal this information back to the development server which will clear the errant component update and trigger a full page reload. This action will be logged to the development server console along with an optional message from the client.
=> refactor(@angular/build): allow component update invalidation from client

packages/angular_devkit/build_angular/src/builders/jest/index.ts, packages/angular_devkit/build_angular/src/builders/jest/schema.json, tests/legacy-cli/e2e/tests/jest/aot.ts
Tests run in JIT only.
Tests can run in AOT, using the new `aot` option.
=> feat: add aot option to jest

packages/angular/build/src/builders/dev-server/tests/behavior/build-external-dependencies_spec.ts, packages/angular/build/src/builders/dev-server/vite-server.ts
Vite 6.0 change the option location of the `preTransformRequests` to the `dev` section of the Vite configuration. While the previous `server` section option of the same name is still present, it currently does not change behavior when configured.
=> fix(@angular/build): avoid pre-transform errors with Vite pre-bundling

packages/angular/build/src/builders/application/build-action.ts, packages/angular/build/src/builders/dev-server/tests/behavior/build-errors_spec.ts, packages/angular/build/src/builders/dev-server/vite-server.ts, tests/legacy-cli/e2e/tests/build/jit-ngmodule.ts
If an initial build of an application results in an error during watch mode (including `ng serve`), the following non-error rebuild will now always be a full build result. This ensures that all new files are available for later incremental build result updates.
Closes #29566
=> fix(@angular/build): ensure full rebuild after initial error build in watch mode

CHANGELOG.md
=> docs: release notes for the v19.1.6 release

packages/angular/build/src/utils/server-rendering/manifest.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-server.ts
JS engines convert `\r\n` to `\n` in template literals, potentially leading to incorrect byte length calculations. This fix ensures the correct content length is determined.
Closes #29567
=> fix(@angular/ssr): accurately calculate content length for static pages with `\r\n`

packages/angular/build/src/builders/dev-server/vite-server.ts
https://github.com/angular/angular-cli/commit/5c1360179cec2f0fad6b2adb4a8e4d6930738976 moved `preTransformRequests` from the `server` to `dev` section. But vite, still uses the `server` section in such cases https://github.com/vitejs/vite/blob/bcdb51a1ac082f4e8ed6f820787d6745dfaa972d/packages/vite/src/node/server/index.ts#L673 and https://github.com/vitejs/vite/blob/bcdb51a1ac082f4e8ed6f820787d6745dfaa972d/packages/vite/src/node/server/middlewares/indexHtml.ts#L475
=> refactor(@angular/build): also add `server.preTransformRequests`

packages/angular/build/src/builders/application/i18n.ts
Ensure proper handling of unlocalizable files during localized prerendering to prevent errors.
Closes #29587
=> fix(@angular/build): handle unlocalizable files correctly in localized prerender

packages/angular/build/src/utils/server-rendering/prerender.ts, packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/test/routes/ng-routes_spec.ts
Enhances handling of `baseHref` when it includes a full URL with a protocol.
Closes #29590
=> fix(@angular/ssr): properly handle baseHref with protocol

packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts
The warning is no longer accurate, as `allowedHosts` is now used in Vite.
=> refactor(@angular/build): remove outdated `allowedHosts` warning

packages/angular/build/src/builders/application/i18n.ts, packages/angular/build/src/tools/esbuild/i18n-inliner.ts
When disk caching is enabled, translated i18n bundles are stored on disk, improving performance and speeding up both incremental and non-incremental builds.
=> perf(@angular/build): cache translated i18n bundles for faster builds

packages/angular/build/src/builders/dev-server/schema.json, packages/angular/build/src/builders/dev-server/vite-server.ts
Vite's `allowedHosts` option does not enable CORS; instead, it allows the dev server to respond to requests with a matching hostname (e.g., http://example.com/main.js). It only verifies that the request’s hostname is on the allowed list. However, this does not consider the `origin` in the case of a CORS request.
This commit updates Vite's configuration to enable CORS.
Closes #29549
=> fix(@angular/build): configure Vite CORS option

renovate.json
Versions 0.25.0 breaks sourcemaps, this requires further investigation and if it's possible to mitigate from our end.
=> ci: temporary disable updating esbuild

package.json, packages/angular_devkit/build_angular/package.json, packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts, packages/angular_devkit/build_angular/src/builders/dev-server/schema.json, packages/angular_devkit/build_angular/src/builders/dev-server/tests/execute-fetch.ts, packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/allowed-hosts_spec.ts, packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts, packages/angular_devkit/build_angular/src/tools/vite/angular-memory-plugin.ts, packages/angular_devkit/build_angular/test/hello-world-app/protractor.conf.js, yarn.lock
Version update from 5.1.8 to address advisory GHSA-vg6x-rcgg-rjx6
Vite version 5.4.12+, which is now used by the Angular CLI with the `application`/`browser-esbuild` builders, contains a potentially breaking change for some development setups. Examples of such setups include those that use reverse proxies or custom host names during development. The change within a patch release was made by Vite to address a security vulnerability. For projects that directly access the development server via `localhost`, no changes should be needed. However, some development setups may now need to adjust the `allowedHosts` development server option. This option can include an array of host names that are allowed to communicate with the development server. The option sets the corresponding Vite option …
=> fix(@angular-devkit/build-angular): update vite to version 5.4.14

packages/angular/build/src/tools/angular/compilation/hmr-candidates.ts
The HMR component update candidate analysis has been improved to now perform more fine-grained checks for cases where more than one component is present in a single TypeScript file. Previously it was possible for all components present in a TypeScript file to be considered update candidates when only one of the components had relevant changes to its template and/or styles.
=> fix(@angular/build): support per component updates of multi-component files

tests/legacy-cli/e2e/tests/build/material.ts
The latest version of Angular material no longer adds `@angular/animations` to application code when using `ng add`.
=> test: remove animations check from material build E2E test

CHANGELOG.md
=> docs: release notes for the v17.3.12 release

CHANGELOG.md
=> docs: release notes for the v19.1.7 release

packages/angular/cli/src/command-builder/schematics-command-module.ts
Previously, the logic incorrectly extracted the drive letter as the collection name when the schematic collection was specified as relative on Windows. This fix ensures that relative paths are parsed and resolved correctly, preventing the drive letter from being mistakenly treated as the collection name.
Closes #29559
=> fix(@angular/cli): correctly parse and resolve relative schematic collection names on Windows

packages/schematics/angular/workspace/files/package.json.template, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-server-platform-neutral.ts
Previously the animations module was added to the `ng new` app, because `platform-server` was using it. That's no longer the case as of https://github.com/angular/angular/pull/59762 so these changes remove the dependency.
=> fix(@schematics/angular): remove animations module from ng new app

packages/angular_devkit/build_angular/src/builders/karma/browser_builder.ts, packages/angular_devkit/build_angular/src/builders/karma/tests/options/aot_spec.ts
`aot: true` is supported by the karma builder, but only with the application builder, as the option is ignored with the browser builder.
The option is also used by the browser builder
=> fix(@angular-devkit/build-angular): support aot option for karma browser builder

renovate.json
In certain scenarios, running `bazel run @npm2//:sync` does not reliably update the aspect lock files. For example:
```
$ yarn bazel run @npm2//:sync  # Lock file is updated
$ git restore .aspect
$ yarn bazel run @npm2//:sync  # Lock file is NOT updated
```
Switching to `bazel sync --only=repo` guarantees that the lock file is consistently updated.
More context: https://angular-team.slack.com/archives/C042EU9T5/p1739398554132249
=> ci: replace `bazel run @npm2//:sync` with `bazel sync --only=repo`

renovate.json
When the pnpm lock file is updated this command exits with a non zero error code.
=> ci: handle error when running `bazel sync --only=repo`

packages/angular/cli/src/commands/add/cli.ts
Fixes an issue where JSON help extraction fails if the `ng add` collection name is undefined.
=> refactor(@angular/cli): handle undefined `ng add` collection name

packages/angular/cli/src/commands/update/schematic/index.ts
Previously, the package group name defaulted to the first item in the list. This update prioritizes an installed package as the fallback instead.
Closes #29627
=> fix(@angular/cli): prefer installed package as fallback when listing package groups

tests/legacy-cli/e2e/tests/vite/reuse-dep-optimization-cache.ts
This commit reduces test flakiness by modifying the logic to perform the fetch only after the app is bundled.
=> test: reduce flakiness of `reuse-dep-optimization-cache` e2e test

packages/angular/build/src/builders/application/execute-build.ts, packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/builders/dev-server/vite-server.ts, packages/angular/build/src/tools/esbuild/index-html-generator.ts, packages/angular/build/src/utils/index-file/auto-csp.ts, packages/angular/build/src/utils/index-file/index-html-generator.ts, packages/angular/build/src/utils/index-file/inline-critical-css.ts, packages/angular/build/src/utils/index-file/inline-critical-css_spec.ts, tests/legacy-cli/e2e/tests/build/auto-csp.ts
This update improves the handling of inlined critical CSS to align with `autoCsp`, ensuring compliance with Content Security Policy (CSP) directives. Previously, inlined styles could trigger CSP violations in certain configurations. With this fix, critical CSS is inlined in a way that maintains security while supporting `autoCsp`.  
Closes #29603
//cc @aaronshim
=> fix(@angular/build): update critical CSS inlining to support `autoCsp`

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, packages/angular/build/BUILD.bazel, packages/angular/build/package.json, packages/angular/build/src/builders/karma/application_builder.ts, packages/angular/build/src/builders/karma/polyfills/init_sourcemaps.js, pnpm-lock.yaml, tests/legacy-cli/e2e/tests/test/test-sourcemap.ts
When executing unit tests with `karma`, the stack traces within errors will now use any sourcemaps that were generated during the build process to provide source-based locations for the errors. Script sourcemaps must be enabled for this functionality.
Closes: #29129
=> fix(@angular/build): provide karma stack trace sourcemap support

packages/angular_devkit/build_angular/src/builders/web-test-runner/index.ts, packages/angular_devkit/build_angular/src/builders/web-test-runner/schema.json
For consistency, adds an `aot` option to WTR as well. This should mean that all test builders have the same option now.
=> feat(@angular-devkit/build-angular): add aot to WTR schema

WORKSPACE, packages/angular/build/BUILD.bazel, packages/angular/cli/BUILD.bazel, packages/angular/pwa/BUILD.bazel, packages/angular/ssr/node/BUILD.bazel, packages/angular/ssr/schematics/BUILD.bazel, packages/angular_devkit/architect/testing/BUILD.bazel, packages/angular_devkit/build_angular/BUILD.bazel, packages/angular_devkit/schematics/BUILD.bazel, packages/angular_devkit/schematics/tasks/BUILD.bazel, packages/angular_devkit/schematics/testing/BUILD.bazel, packages/schematics/angular/BUILD.bazel, tests/angular_devkit/schematics/tools/file-system-engine-host/BUILD.bazel, tools/interop.bzl
Setup requirement for strict_deps throughout repository to ensure that the only dependencies which are imported
are directly provided as dependencies within bazel.
=> [Patch Version] build: add strict_deps requirement for ts_project

CHANGELOG.md
=> docs: release notes for the v19.1.8 release

WORKSPACE, packages/angular/build/BUILD.bazel, packages/angular/cli/BUILD.bazel, packages/angular/pwa/BUILD.bazel, packages/angular/ssr/node/BUILD.bazel, packages/angular_devkit/architect/testing/BUILD.bazel, packages/angular_devkit/build_angular/BUILD.bazel, packages/angular_devkit/schematics/BUILD.bazel, packages/angular_devkit/schematics/tasks/BUILD.bazel, packages/angular_devkit/schematics/testing/BUILD.bazel, packages/schematics/angular/BUILD.bazel, tests/angular_devkit/schematics/tools/file-system-engine-host/BUILD.bazel, tools/interop.bzl
Setup requirement for `strict_deps` throughout repository to ensure that the only dependencies which are imported
are directly provided as dependencies within bazel.
=> build: add `strict_deps` requirement for `ts_project`

renovate.json
The latest version of the DevInfra internal `@angular/build-tooling` package contains breaking changes that need to be addressed separately before the version can be updated.
=> build: temporarily ignore renovate updates for @angular/build-tooling

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, CHANGELOG.md, package.json
Also this PR cherry-picks the changelog for v19.2.0-rc.0 into the main branch so that the changelog is up to date.
=> Update next branch to reflect new release-train "v19.3.0-next.0".

tests/legacy-cli/e2e/initialize/500-create-project.ts, tests/legacy-cli/e2e/tests/build/jit-ngmodule.ts, tests/legacy-cli/e2e/tests/build/rebuild-dot-dirname.ts, tests/legacy-cli/e2e/tests/commands/add/version-specifier.ts, tests/legacy-cli/e2e/tests/test/test-environment.ts
The E2E test setup and several of the individual E2E tests have been updated to be more robust for when the `@angular/build` package is used as the new default. The main changes involve ensuring that the Webpack- based `browser` builder testing uses the correct builders instead of the new `@angular/build` variants. This change also improves the reliability of some tests (e.g., `commands/add/version-specifier`) by not relying on outdated versions of Angular packages.
=> test: prepare E2E tests for `@angular/build` project default

.aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx, package.json, packages/angular_devkit/build_angular/package.json, packages/angular_devkit/build_angular/src/builders/browser/specs/vendor-source-map_spec.ts, packages/schematics/angular/utility/latest-versions/package.json, pnpm-lock.yaml, yarn.lock
A test for the browser builder needed to be updated to reflect a different order in the sources array within the generated source map.
=> build: update postcss to v8.5.3

packages/angular/build/src/builders/dev-server/vite-server.ts
When using the development server, the `statsJson` option will now unconditionally be disabled. The output JSON file is not accessible with the server and the analysis/generation of the JSON file may increase the rebuild time. Additionally, the JSON file changes during a rebuild may unexpectedly cause component HMR fallback to a full reload due to non-component file changes in the build output.
=> fix(@angular/build): always disable JSON stats with dev-server

CHANGELOG.md
=> docs: release notes for the v19.1.9 release

packages/angular/build/src/tools/esbuild/stylesheets/less-language.ts
There can be cases where the `less` stylesheet preprocessor will return an undefined value for a sourcemap even though sourcemaps have been enabled. A check is now performed to handle these cases to prevent potential crashes when processing `less` styles.
=> fix(@angular/build): handle undefined `less` stylesheet sourcemap values

packages/schematics/angular/migrations/use-application-builder/migration.ts
In certain cases, misconfiguration of the server builder could cause the migration process to incorrectly delete `main.ts`. 
Closes: #29661
=> fix(@schematics/angular): prevent accidental deletion of `main.ts` during application builder migration

goldens/public-api/angular/ssr/index.api.md, packages/angular/ssr/public_api.ts, packages/angular/ssr/src/routes/route-config.ts
`provideServerRouting` should be used instead.
=> refactor(@angular/ssr): remove deprecated `provideServerRoutesConfig` dev-preview API

packages/angular/build/src/tools/esbuild/angular/jit-plugin-callbacks.ts
Previously, JIT component resource URLs in sourcemaps included a `file:` prefix (e.g., `file:src/app/app.component.html`). This change removes the `file:` prefix to ensure cleaner source mappings.
=> refactor(@angular/build): remove `file:` prefix from JIT component resource URLs in sourcemaps

packages/angular/build/src/builders/application/build-action.ts
When the service worker option is enabled, each code update will cause the `ngsw.json` configuration file to change due to the different hashes of the updated output. This is problematic for component HMR usage with the development server since the full reload fallback logic would be triggered due to the changed `ngsw.json` file.  To avoid this problem, the `ngsw.json` configuration file is now special cased within the fallback logic.
=> fix(@angular/build): allow component HMR with a service worker

packages/angular/build/src/utils/bundle-calculator.ts
Previously, component styles were included in the 'any' and 'all' budgets, which could lead to incorrect budget violations. This update ensures that component styles are excluded from these budget calculations.
Closes #29609
=> fix(@angular/build): exclude component styles from 'any' and 'all' budget calculations

packages/schematics/angular/migrations/use-application-builder/migration.ts
If the root tsconfig.json is missing we should not error.
Closes #29754
=> fix(@schematics/angular): prevent error when tsconfig file is missing in application builder migration

packages/angular/build/src/builders/extract-i18n/application-extraction.ts, packages/schematics/angular/application/index.ts, packages/schematics/angular/application/index_spec.ts, packages/schematics/angular/config/index_spec.ts, packages/schematics/angular/library/index.ts, packages/schematics/angular/library/index_spec.ts, tests/legacy-cli/e2e/initialize/500-create-project.ts, tests/legacy-cli/e2e/utils/project.ts
The `@angular/build` package is now used directly within all newly created projects and replaces the previous usage of the `@angular-devkit/build-angular` package. This has the advantage of removing the need to install all of the Webpack related transitive dependencies contained within `@angular-devkit/build-angular` that are used to support the `browser` builder. This results in a significant reduction in both total dependency count and disk install size for new projects. New projects that would prefer to use the Webpack-based `browser` builder can still install the `@angular-devkit/build-angular` package within the workspace.
The `@angular/build@19.2.0-next.2` package currently has a total unpacked size of ~115 MB.
The `@angular-devkit/build-angular@19.2.0-next.2` package currently has …
=> feat(@schematics/angular): directly use `@angular/build` in new projects

CHANGELOG.md
=> docs: release notes for the v19.2.1 release

packages/angular/build/src/builders/extract-i18n/builder.ts, packages/angular/build/src/utils/i18n-options.ts
Current behaviour is described inside this issue - https://github.com/angular/angular-cli/issues/23635
Issue Number: #23635
Now we can add different values according to the `i18nDuplicateTranslation` option https://github.com/angular/angular-cli/blob/d99e4ed49359632657cd170524673dd9f4e88b82/goldens/public-api/angular/build/index.api.md?plain=1#L40 and have corresponding output, not hardcoded `warning`
=> bugfix: provide i18nDuplicateTranslation config value to checkDuplicateMessages function

packages/angular/build/src/builders/application/execute-build.ts, packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/builders/application/schema.json, packages/angular/build/src/builders/dev-server/schema.json, packages/angular/build/src/builders/dev-server/tests/behavior/build-external-dependencies_spec.ts, packages/angular/build/src/tools/esbuild/bundler-context.ts, packages/angular/build/src/tools/esbuild/bundler-execution-result.ts, packages/angular/build/src/tools/esbuild/external-packages-plugin.ts, packages/angular/build/src/tools/vite/plugins/id-prefix-plugin.ts
The configuration now ensures that when a package is listed for exclusion, all paths within that package including sub-paths like `@foo/bar/baz`  are marked as external and not prebundled by the development server.
For example, specifying `@foo/bar` in the exclude list will prevent the development server from bundling any files from the `@foo/bar` package, including its sub-paths such as `@foo/bar/baz`.
This aligns with esbuild external option behaviour https://esbuild.github.io/api/#external
Closes #29170
=> fix(@angular/build): exclude all entrypoints of a library from prebundling

packages/angular/build/src/builders/dev-server/builder.ts
This warning is already displayed during the normalization of options. See: https://github.com/angular/angular-cli/blob/b5a86709b7c035c129f5a9d8f1f684169432195e/packages/angular/build/src/builders/dev-server/options.ts#L56
=> fix(@angular/build): remove duplicate prebundling warning

packages/angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts
Improves error handling in the PostCSS compilation process to prevent crashes and allow recovery.
Closes #29789
=> fix(@angular/build): handle postcss compilation errors gracefully

packages/angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts
Cherry-pick of https://github.com/angular/angular-cli/pull/29792
=>  [Patch] fix(@angular/build): handle postcss compilation errors gracefully

packages/angular/cli/src/command-builder/schematics-command-module.ts
Prior to this commit, analytics were not recorded for nested schematics. This caused certain data to be incomplete. For example, when running `ng new` and selecting "yes" for SSR in the prompt, this choice was not recorded because the prompt exists within the `application` schematic.
=> fix(@angular/cli): record analytics for nested schematics

packages/angular/ssr/node/src/response.ts
Implements a workaround for https://github.com/CodeGenieApp/serverless-express/issues/683
Closes #29801
=> fix(@angular/ssr): prevent stream draining if `write` does not return a boolean

package.json, pnpm-lock.yaml, renovate.json
With the migration to use `rules_js` with Bazel, this package should no longer be needed.
=> build: remove dev-infra `@angular/build-tooling` package

docs/DEVELOPER.md
Improves the developer guide for pnpm and Windows.
See for the Windows change:
https://github.com/angular/angular-cli/pull/29705.
=> docs: improve developer guide for pnpm and windows

package.json, pnpm-lock.yaml
The release tool did check for a `yarn.lock` file. This check was updated to also work with pnpm.
=> build: update `ng-dev` to include latest pnpm release tool fixes

package.json, pnpm-lock.yaml
Updates `ng-dev` again as we made another release-tool fix for pnpm. See: https://github.com/angular/dev-infra-private-ng-dev-builds/commit/9fd3adb2e8b9a0fef1ba5bc905a900e018445e05
=> build: update ng-dev

renovate.json
The previous regexp also matches `20.0.0-next` which causes Angular FW packages not to be updated.
=> ci: update `matchCurrentVersion` RegExp

CHANGELOG.md
=> docs: release notes for the v19.2.2 release

scripts/windows-testing/convert-symlinks.mjs
For our native Windows tests (verifying `ng` CLI outside WSL), we currently build the test binaries inside WSL, leveraging bazel remote execution.
The scripts involved in moving the built binaries to outside WSL rarely flake due to a WSL interop bug when we invoke Windows commands from inside WSL (which is an untypical thing to do; but a needed trick given some WSL limitation).
This commit tries to stabilize/avoid this flake by retrying if we recognize this
=> build: avoid WSL interop flake when preparing Windows CI environment

CHANGELOG.md
=> docs: release notes for the v18.2.15 release

CHANGELOG.md
=> docs: release notes for the v19.2.3 release

.bazelignore
Although the `build` package is not present in this branch, the `node_modules` directory may persist when switching branches during a release, potentially causing the build to fail.
=> build: configure Bazel to ignore `packages/angular/build/node_modules`

packages/angular/build/src/builders/karma/application_builder.ts, tests/legacy-cli/e2e/tests/test/test-sourcemap.ts
The karma configuration will now automatically set the `basePath` option to the temporary output path when using the application build system's karma testing. This ensures that only the relative path of the test files is represented in the stack traces of test failures.
Closes #29766
=> fix(@angular/build): ensure relative karma stack traces for test failures

packages/angular/build/src/builders/dev-server/tests/behavior/component-updates_spec.ts, packages/angular/build/src/tools/esbuild/application-code-bundle.ts
An `ngHmrMode` boolean value will now be defined within application bundles. The value is based on the development server's `hmr` option with `true` when HMR is enabled and `false` when disabled. For all application builds, the value will be `false`. `ngHmrMode` is similar in behavior to `ngServeMode` or `ngDevMode`. It will not be present in the output code unless referenced and in those cases only the final boolean value will be present if not optimized out of the final code.
The value is not considered part of the public API and may change in the future.
=> refactor(@angular/build): define an internal ngHmrMode value

docs/DEVELOPER.md
These command are outdated and no longer work
=> docs: correct bazel e2e commands

packages/angular/build/src/tools/esbuild/stylesheets/sass-language.ts, tests/legacy-cli/e2e.bzl, tests/legacy-cli/e2e/tests/build/styles/sass-pkg-importer.ts
Enhanced Sass integration by adding support for package importers.
See: https://sass-lang.com/blog/announcing-pkg-importers/
Closes: #29854
=> feat(@angular/build): Support Sass package importers

packages/angular/cli/lib/init.ts, packages/angular/cli/src/commands/cache/clean/cli.ts, packages/angular/cli/src/commands/cache/info/cli.ts, packages/angular/cli/src/utilities/completion.ts
Several usages of `import { promises as fs } from 'node:fs'` have been adjusted to import directly from `node:fs/promises`. This is consistent with the rest of the source code usage.
=> refactor(@angular/cli): import from `node:fs/promises` where appropriate

tests/legacy-cli/e2e_runner.ts
Currently the `while` loop may either be causing the process to be really stuck/hanging, or it somehow causes Node to exit.
This change makes the logic more robust and less CPU consuming.
=> build: improve debugging mode of e2e test runner

packages/schematics/angular/migrations/replace-provide-server-rendering-import/migration.ts, packages/schematics/angular/migrations/replace-provide-server-rendering-import/migration_spec.ts
Prior to this commit, the dependency was always added.
=> fix(@schematics/angular): add `@angular/ssr` dependency only when `provideServerRendering` import has been updated

packages/schematics/angular/application/files/module-files/src/main.ts.template
The Angular CLI explicitly adds `@angular/compiler` as a polyfill when JIT mode is enabled which makes using  `@angular/platform-browser-dynamic` redundant and causes the compiler to be imported twice.
=> fix(@schematics/angular): replace `@angular/platform-browser-dynamic` with `@angular/platform-browser`

packages/schematics/angular/app-shell/index.ts, packages/schematics/angular/server/index.ts
Previously, Webpack-based builders did not utilize this option.
=> fix(@angular/schematics): ensure app-shell schematic consistently uses `withAppShell`

packages/angular/build/src/builders/application/tests/behavior/component-stylesheets_spec.ts, packages/angular/build/src/builders/application/tests/behavior/component-templates_spec.ts, packages/angular/build/src/tools/angular/angular-host.ts
Compile time errors will now always be generated when an HTML template and/or CSS component stylesheet are not present on disk. The Angular compiler expects a return value of `null` from the `resourceNameToFileName` function to indicate that a resource path does not exist. JIT mode previously and continues to generate errors as expected.
Closes #29887
=> fix(@angular/build): ensure errors for missing component resources

CHANGELOG.md
=> docs: release notes for the v19.2.4 release

packages/angular/build/src/builders/application/tests/behavior/component-stylesheets_spec.ts, packages/angular/build/src/builders/application/tests/behavior/component-templates_spec.ts
Correct several small test description typos for the application builder.
=> test: correct test description typos

tsconfig.json
With Node.js v20 now the minimum supported version for Angular v20, the ECMAScript version used with TypeScript can be increased to ES2023.
=> build: update tsconfig ECMAScript version to ES2023

packages/schematics/angular/directive/files/__name@dasherize@if-flat__/__name@dasherize__.directive.spec.ts.template, packages/schematics/angular/directive/files/__name@dasherize__.__type@dasherize__.spec.ts.template, packages/schematics/angular/directive/files/__name@dasherize__.__type@dasherize__.ts.template, packages/schematics/angular/directive/index.ts, packages/schematics/angular/directive/index_spec.ts, packages/schematics/angular/directive/schema.json, tests/legacy-cli/e2e/tests/generate/directive/directive-basic.ts, tests/legacy-cli/e2e/tests/generate/directive/directive-prefix.ts
To align with the updated style guide, Angular v20 will generate services without a `.directive` file extension type for all directive related files by default. Projects will automatically use this naming convention. Projects can however opt-out by setting the `type` option to `Directive` for the directive schematic. This can be done as a default in the `angular.json` or directly on the commandline via `--type=Directive` when executing `ng generate`. As an example, `example.directive.ts` will now be named `example.ts`. Additionally, the TypeScript class name will be `Example` instead of the previous `ExampleDirective`.
=> fix(@schematics/angular): generate directives without a .directive extension/type

packages/schematics/angular/application/index.ts
The `scripts` option with an empty array value has been removed from newly generated applications including with `ng new`. This option is less commonly used and can be added if needed by a project. The removal reduces the total size of the generated `angular.json`.
=> fix(@schematics/angular): remove empty `scripts` option value from new applications

packages/angular/ssr/src/routes/route-config.ts
=> docs(@angular/ssr): remove extra pipe from link in tsdocs

packages/angular/build/src/utils/server-rendering/launch-server.ts, packages/angular/build/src/utils/server-rendering/prerender.ts
Prior to this change, request errors were not handled correctly.
Closes #29884
=> fix(@angular/build): correct handling of response/request errors

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/builders/application/schema.json
The application builder will now use a default output path when the `outputPath` option is not specified either in the `angular.json` configuration or via the command line.  The default used will be `dist/<project_name>` and be relative to the workspace root. This value is the typical default for new projects. Projects may continue to customize the output path via the option if needed. Existing project behavior and configuration will not be changed.
=> feat(@angular/build): support a default outputPath option for applications

packages/angular/ssr/src/app.ts, packages/angular/ssr/src/utils/ng.ts
This change ensures that HTTP headers are flushed to the client before the server begins rendering the Angular application HTML. By flushing headers early, the server can inform the client of response metadata (e.g., status code, content type) immediately, improving performance and user experience.
=> perf(@angular/ssr): flush headers prior to start rendering the HTML

packages/schematics/angular/ssr/files/application-builder/server.ts.template, packages/schematics/angular/ssr/index_spec.ts, scripts/build-packages-dist.mts, scripts/build-schema.mts, scripts/build.mts, scripts/create.mts, scripts/devkit-admin.mts, scripts/json-help.mts, scripts/snapshots.mts, scripts/templates.mts, scripts/validate-user-analytics.mts, tests/legacy-cli/e2e/assets/ssr-project-webpack/package.json, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-static-http-calls.ts, tests/legacy-cli/e2e/tests/vite/ssr-entry-express.ts, tests/legacy-cli/e2e/utils/project.ts
This change is possible because we no longer support Node.js versions earlier than 20.11.0
=> refactor: replace `dirname(fileURLToPath(import.meta.url))` with `import.meta.dirname`

packages/schematics/angular/workspace/files/tsconfig.json.template
Adds the `typeCheckHostBindings` flag when the user has opted into strict type checking.
=> fix(@schematics/angular): add type checking of host bindings to strict config

packages/angular/build/src/tools/vite/middlewares/ssr-middleware.ts
Enhanced error handling to account for cases where `getOrCreateAngularServerApp` is undefined during the compilation process. This prevents unexpected crashes and improves build stability.
Closes #29907
=> fix(@angular/build): handle undefined `getOrCreateAngularServerApp` during error compilation

packages/schematics/angular/application/index.ts, packages/schematics/angular/ssr/index.ts, packages/schematics/angular/ssr/index_spec.ts, tests/legacy-cli/e2e/tests/build/jit-ngmodule.ts, tests/legacy-cli/e2e/tests/build/rebuild-dot-dirname.ts, tests/legacy-cli/e2e/tests/build/relative-sourcemap.ts
The `outputPath` option now defaults to `dist/<project_name>` for applications. This removes the need to explicitly set the option within a newly generated project. The value removal also reduces the overall size of the `angular.json` configuration for new projects. Existing projects are not modified by this change.
=> fix(@schematics/angular): remove explicit `outputPath` option value from generated applications

WORKSPACE, constants.bzl, package.json
For more details, see: https://github.com/angular/angular-cli/issues/27674
**BREAKING CHANGE:** Node.js versions from 22.0 to 22.10 are no longer supported
=> fix(@angular/cli): update minimum supported Node.js 22 version to 22.11.0

packages/angular/build/src/builders/karma/application_builder.ts
When handling a request for a configured asset with the application- based karma unit testing, the asset URL is now normalized to the executing platform's path format before looking up the asset. This is required due to the build file paths being based on the underlying operating system's paths which may not align with a URL's path separator such as when using Windows.
=> fix(@angular/build): normalize karma asset paths before lookup

packages/angular/build/src/builders/application/schema.json, packages/angular/build/src/builders/application/setup-bundling.ts, packages/angular/build/src/builders/application/tests/options/sourcemap_spec.ts, packages/angular/build/src/tools/esbuild/application-code-bundle.ts, packages/angular/build/src/tools/esbuild/global-styles.ts, packages/angular/build/src/tools/esbuild/stylesheets/bundle-options.ts, packages/angular/build/src/utils/normalize-source-maps.ts
The `sourceMap` option now contains an additional sub-option named `sourcesContent` that allows the exclusion of original file content from generated source maps. This option affects both JavaScript and stylesheet source maps. The value of the `sourcesContent` option defaults to `true`.
Example usage to disable sources content:
```
"sourceMap": {
"scripts": true,
"styles": true,
"sourcesContent": false
}
```
Closes #29551
=> feat(@angular/build): allow control of source map sources content for application builds

packages/angular/build/src/builders/application/index.ts, tests/legacy-cli/e2e/tests/build/assets.ts
When using Node.js v22 (minimum of v22.11 for v22 with Angular v20), the application build system will now use the Node.js `cp` filesystem API instead of the `copyFile` API. This newer API provides equivalent functionality while also preserving timestamps for copied assets.  Additionally, it supports potential future internal refactorings to support full direct directory copying. Projects built with Node.js v20 will continue to use the `copyFile` API.
=> refactor(@angular/build): use newer Node.js `cp` API for asset copying

tests/legacy-cli/e2e/tests/build/assets.ts
The test now uses an asset that is already on disk.
Using an asset that was just written within the test
may cause timestamps to not yet be synced to disk.
=> test: improve resilience of asset timestamp E2E test

package.json, packages/angular_devkit/build_angular/package.json, yarn.lock
This fixes https://github.com/vitejs/vite/security/advisories/GHSA-x574-m823-4x7w
Closes #29936
=> fix(@angular-devkit/build-angular): update vite to 5.4.15

package.json, packages/angular/build/package.json, yarn.lock
This fixes https://github.com/vitejs/vite/security/advisories/GHSA-x574-m823-4x7w
Closes #29936
=> fix(@angular/build): update vite to 5.4.15

tests/legacy-cli/e2e/tests/build/assets.ts
Node.js handles time precision differently, which may cause mtime-based tests to fail.
This update ensures that atime and mtime values are rounded to the same precision,  preventing inconsistencies in file timestamp comparisons.
=> test: ensure atime and mtime are rounded consistently in tests

CHANGELOG.md
=> docs: release notes for the v17.3.14 release

CHANGELOG.md
=> docs: release notes for the v18.2.16 release

CHANGELOG.md
=> docs: release notes for the v19.2.5 release

packages/angular/build/src/builders/karma/application_builder.ts, packages/angular/build/src/builders/karma/index.ts, packages/angular/build/src/builders/karma/tests/options/browsers_spec.ts
The jsdom package does not currently support execution of ESM scripts. Attempting to use the karma jsdom launcher will cause test failures with potentially unclear error messages after the tests have been built and have started to execute. The karma application builder test runner will now issue a warning describing the problem and remove the jsdom launcher from the `browsers` option. The warning will be shown while analyzing the options and prior to the actual start of the test process.
=> fix(@angular/build): warn and remove jsdom launcher when used with karma

packages/angular/build/src/builders/karma/polyfills/init_test_bed.js, packages/angular_devkit/build_angular/src/builders/jest/init-test-bed.mjs, packages/angular_devkit/build_angular/src/builders/karma/browser_builder.ts, packages/angular_devkit/build_angular/src/builders/web-test-runner/jasmine_runner.js
This reverts commit e5e51a22abe4c5c421ff984542fcc808b440b0fa.
This can now be reverted as `platformBrowserTesting` has been fixed.
=> Revert "refactor: use `platformBrowser` instead of `platformBrowserTesting`

.bazelrc, .github/shared-actions/windows-bazel-test/action.yml, .github/workflows/assistant-to-the-branch-manager.yml, .github/workflows/ci.yml, .github/workflows/dev-infra.yml, .github/workflows/feature-requests.yml, .github/workflows/perf.yml, .github/workflows/pr.yml
Update to use the latest bazel/configure-remote action from dev-infra and set up trusted builds for CI runs from upstream branches.
=> ci: update bazel RBE setup on CI and use trusted build configuration for upstream CI runs

goldens/public-api/angular_devkit/core/index.api.md, modules/testing/builder/src/builder-harness.ts, packages/angular/build/src/builders/application/tests/setup.ts, packages/angular/cli/src/command-builder/architect-base-command-module.ts, packages/angular_devkit/core/src/json/schema/transforms.ts
Previously, all builder options that were of type array were set to a default empty array even if there was no explicit default defined within the schema. This can be problematic for options that have differing behavior based on their presence such as runtime calculated defaults. The implicit defaulting behavior was also not aligned with the generated schema types which resulted in additional type safety and initialization regardless. As a result, the implicit behavior was effectively redundant in most cases. Since this change could be breaking for third-party builders, the removal of this behavior is currently limited to the `@angular/build` package.
=> refactor(@angular/cli): avoid implicit undefined array defaults for `@angular/build` builders

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/builders/application/schema.json
The schema included a top-level `type`, preventing this option from functioning correctly.
Closes: #29969
=> fix(@angular/build): correctly handle  `false` value in server option

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/builders/application/schema.json, packages/angular/build/src/builders/application/tests/options/conditions_spec.ts, packages/angular/build/src/builders/dev-server/tests/setup.ts, packages/angular/build/src/tools/esbuild/application-code-bundle.ts
When using the application build system, a new `conditions` option is now available that allows adding custom package resolution conditions that can adjust the resolution for conditional exports and imports. By default the `module` and `production`/`development` conditions will be present with the later dependent on the `optimization` option. If any custom conditions value is present including an empty array, none of these defaults will be present and must be manually included if needed. The following special conditions will always be present if their respective requirements are satisfied:
* es2015 (required by rxjs)
* es2020 (APF backwards compatibility)
* default
* import
* require
* node
* browser
For additional information regarding conditional exports/imports: …
=> feat(@angular/build): support custom resolution conditions with applications

packages/angular/build/BUILD.bazel, packages/angular/build/package.json, packages/angular/build/src/tools/esbuild/javascript-transformer-worker.ts, pnpm-lock.yaml
As of babel v7.26.0, the separate `@babel/plugin-syntax-import-attributes` package is no longer needed. The ability to parse import attributes is included by default.
=> refactor(@angular/build): remove unneeded babel import attributes syntax plugin

packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/tools/esbuild/application-code-bundle.ts
To support future APF changes that may include pre-linked code specific to the Angular version used to create the package, an additional package resolution condition will now be automatically added to the build process for applications. A condition in the form of `angular:linked-<version>`, where `<version>` is the full package version of `@angular/core`, will now be present during application builds. This change in combination with APF changes will allow matching packages to avoid the linking step during a build. Non-version matching packages will continue to function and use the existing linking transformation process.
=> refactor(@angular/build): provide a pre-link resolution condition for APF

packages/schematics/angular/utility/generate-from-files.ts
The potential double periods within file name templates are now more completely removed in cases where there may be more than one set.
=> refactor(@schematics/angular): more comprehensive empty type file name cleanup

WORKSPACE
The shared dev-infra repository will depend on `rules_esbuild` going forward, so we need to install it.
Unblocks https://github.com/angular/angular-cli/pull/29984
=> build: setup `rules_esbuild` in preparation for `devinfra` update

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/builders/application/schema.json, packages/angular/build/src/builders/application/tests/options/index_spec.ts
The application build system's `index` option is now considered optional. If not present, the value will be an `index.html` file within the configured project source root (`sourceRoot`). The default only applies to the short-form of the option. The object-based long-form continues to require explicit configuration of the input index HTML file. This change allows the removal of the `index` option from any project that uses the default generated value.
=> refactor(@angular/build): provide a default for the application index option

package.json, packages/angular/build/package.json, yarn.lock
Addresses GHSA-4r4m-qw57-chr8
Closes #29996
=> fix(@angular/build): update vite to 5.4.16 due to a security issues

packages/schematics/angular/migrations/migration-collection.json, packages/schematics/angular/migrations/update-module-resolution/migration.ts, packages/schematics/angular/migrations/update-module-resolution/migration_spec.ts
This commit adds a migration to update the TypeScript `moduleResolution` option to `'bundler'` for improved compatibility with modern package resolution.
See: https://www.typescriptlang.org/tsconfig/#moduleResolution
=> feat(@schematics/angular): add migration to update `moduleResolution` to `bundler`

CHANGELOG.md
=> docs: release notes for the v17.3.15 release

CHANGELOG.md
=> docs: release notes for the v18.2.17 release

CHANGELOG.md
=> docs: release notes for the v19.2.6 release

packages/angular/build/src/builders/application/tests/options/optimization-scripts_spec.ts, packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts, packages/angular/build/src/tools/esbuild/compiler-plugin-options.ts
To support the usage of AOT with unit tests, development builds of applications will now include injected calls to the internal Angular `setClassMetadata` function. These calls add metadata to each component that can be leveraged by the `TestBed` to override component information.
=> fix(@angular/build): include component test metadata in development builds

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/ng-packagr/builder.ts, packages/angular/build/src/builders/ng-packagr/schema.json, packages/schematics/angular/library/index.ts, packages/schematics/angular/library/index_spec.ts
This option is now considered optional
=> refactor(@angular/build): provide a default for the ng-packagr project option

packages/schematics/angular/library/index.ts
Explicitly sets an empty `type` when the `library` calls into the `component` schematic for a few reasons:
1. The `type` for classes mostly makes sense in an application contenxt. E.g. libraries are unlikely to have guards.
2. The generated component is there primarily as an example and library authors are likely to either delete it or modify it to match their expected public API.
3. It ensures that the generated files remain correct if the `component` schematic ends up inheriting the `type` from the workspace.
=> fix(@schematics/angular): set explicit type in library schematic

packages/angular/build/src/builders/application/options.ts
In this PR https://github.com/angular/angular-cli/pull/29753 there was a regression that now prevents corrent handling of external local dependencies. In my case the configuration for the build target looks like this `"externalDependencies": ["/assets/js/*"]`. This ensures that all scripts in the given folder are marked as external. 
With the change in the PR mentioned above this no longer works. To bring back the old behavior I'm adding an extra condition to check whether provided dependency is indeed a package name or a relative/absolute path.
=> fix(@angular/build): skip normalization of relative externals

package.json, pnpm-lock.yaml
The `@angular/platform-server` package has been updated to correctly include a peer dependency on `rxjs` and no longer requires a custom package extension defined.
=> build: remove now unneeded platform-server package extension

packages/schematics/angular/migrations/migration-collection.json, packages/schematics/angular/migrations/previous-style-guide/migration.ts, packages/schematics/angular/migrations/previous-style-guide/migration_spec.ts
When updating to Angular v20 via `ng update`, a migration will be executed that will add schematic generation (`ng generate`) defaults to the workspace. These defaults will ensure that existing projects will continue to generate files as done in previous versions of the Angular CLI. All new projects (via `ng new`) or projects that do not explicitly contain these options in their workspace will use the updated style guide naming behavior.
The option values for the `schematics` field are as follows:
```
{
'@schematics/angular:component': { type: 'component' },
'@schematics/angular:directive': { type: 'directive' },
'@schematics/angular:service': { type: 'service' },
'@schematics/angular:guard': { typeSeparator: '.' },
'@schematics/angular:interceptor': { typeSeparator: '.' }, …
```
=> feat(@schematics/angular): add update migration to keep previous style guide generation behavior

tests/legacy-cli/e2e/tests/build/jit-prod.ts
Applications built with JIT will be significantly larger due to both the need to bundle the Angular compiler and the extra metadata that must be retained for each Angular construct. The initial bundle budget in new applications is specified for an AOT application and may not pass if used with JIT.
=> test: remove bundle budget from JIT production E2E test

packages/angular/build/package.json, packages/angular_devkit/build_angular/package.json, tests/legacy-cli/e2e/tests/misc/dedupe-duplicate-modules.ts
This is required  to support strict mode in pnpm.
Closes #30068
=> refactor: add missing peer depedency on `@angular/core` and `tslib`

.github/workflows/assistant-to-the-branch-manager.yml, .github/workflows/ci.yml, .github/workflows/dev-infra.yml, .github/workflows/feature-requests.yml, .github/workflows/pr.yml, package.json, packages/angular/build/package.json, yarn.lock
This fixes  GHSA-xcj6-pq6g-qj4x
Closes #30056
=> fix(@angular/build): update vite to 5.4.17

CHANGELOG.md
=> docs: release notes for the v17.3.16 release

CHANGELOG.md
=> docs: release notes for the v18.2.18 release

packages/ngtools/webpack/src/ivy/plugin.ts
The Angular compiler does not directly support the `composite` option within a referenced `tsconfig` file. If this option is enabled, the Angular compiler will crash due to the Angular compiler not leveraging the TypeScript BuilderProgram infrastructure. Since the Angular compiler is not aware of composite projects nor project references, the `composite` option is disabled when options are passed to the Angular compiler. This has no effect on non- Angular related usages of the `tsconfig`.
=> fix(@ngtools/webpack): disable TypeScript composite option with Angular compiler

CHANGELOG.md
=> docs: release notes for the v19.2.7 release

packages/angular/build/src/builders/dev-server/vite-server.ts
This fix ensures that transitive external dependencies are correctly recognized and excluded during development builds with the Vite dev server. Previously, some dependencies were mistakenly bundled.
Closes #30048
=> fix(@angular/build): properly resolve transitive external dependencies in vite-dev-server

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
Previously, when setting `module: preserve`—which internally sets `moduleResolution` to `bundler` in TypeScript—custom conditions were not applied. This change ensures that custom conditions are also added when `module` is set to `preserve`.
=> fix(@angular/build): include `module` value check when adding custom conditions

packages/schematics/angular/migrations/use-application-builder/migration.ts, packages/schematics/angular/migrations/use-application-builder/migration_spec.ts
The `use-application-builder` update migration will now attempt to migrate the `karma` builder to use the `@angular/build` package if no other `@angular-devkit/build-angular` usage is present.
=> fix(@schematics/angular): application migration should migrate karma builder package

packages/angular/build/src/tools/esbuild/angular/component-stylesheets.ts
The Angular encapsulation currently does not support CSS nesting syntax, which can lead to run-time errors or unexpected behavior when such styles are used in component stylesheets. This change ensures that nested CSS rules flattened to maintain compatibility with the compiler.
For more context, see: https://github.com/angular/angular/issues/58996
=> fix(@angular/build): prevent nested CSS in components

packages/angular/build/src/builders/dev-server/vite-server.ts
The internal `ngHmrMode` define value was previously available to application code and third-party modules that were not prebundled. To ensure that the value is propagated to all relevant code served by the development server, the `ngHmrMode` define is now used during the Vite prebundling phase. This allows any prebundled dependencies to also leverage the `ngHmrMode` value. The framework may, for instance, use the value to provide additional development time diagnostics.
=> refactor(@angular/build): use `ngHmrMode` define for Vite prebundling

packages/schematics/angular/application/files/common-files/tsconfig.app.json.template, packages/schematics/angular/application/files/common-files/tsconfig.spec.json.template, packages/schematics/angular/application/index.ts, packages/schematics/angular/application/index_spec.ts, packages/schematics/angular/server/index.ts, packages/schematics/angular/server/index_spec.ts, packages/schematics/angular/ssr/index.ts, packages/schematics/angular/ssr/index_spec.ts, packages/schematics/angular/workspace/files/tsconfig.json.template
When generating a project (either via `ng new` or `ng generate application`), the created TypeScript configuration files (`tsconfig.app.json`/`tsconfig.spec.json`) will be setup as composite projects and added as project references to in the root `tsconfig.json`.  This transforms the root `tsconfig.json` into a "solution" style configuration. This allows IDEs to more accurately discover and provide type information for the varying types of files (test, application, etc.) within each project. The Angular build process is otherwise unaffected by these changes.
=> feat(@schematics/angular): generate applications using TypeScript project references

packages/angular/build/src/builders/karma/application_builder.ts
Ensure that several previously omitted options are correctly passed to the Karma esbuild builder, improving consistency and expected behavior.
=> fix(@angular/build): pass `preserveSymlinks` option to Karma esbuild builder

packages/schematics/angular/application/index.ts, packages/schematics/angular/application/index_spec.ts
We can't quickly navigate to the referenced paths as VSCode for example thinks they are modules (Failed tor resolve tsconfig.app.json as a module)
This makes them clickable for a quick navigation in IDEs
=> fix(@schematics/angular): relative tsconfig paths in references

package.json, packages/angular_devkit/build_angular/package.json, yarn.lock
Addresses https://github.com/advisories/GHSA-4www-5p9h-95mh
=> fix(@angular-devkit/build-angular): update http-proxy-middleware to v3.0.5

packages/schematics/angular/application/files/common-files/tsconfig.app.json.template, packages/schematics/angular/application/files/common-files/tsconfig.spec.json.template
Based on this [TS discussion](https://github.com/microsoft/TypeScript/issues/60465), `composite` is in fact not necessary, the TS docs are just misleading.
This removes `composite` from the configs, as it was recently done in create-vue (see  https://github.com/vuejs/create-vue/pull/635).
=> fix(@schematics/angular): drop composite in tsconfig

.bazelignore, WORKSPACE, constants.bzl, docs/process/release.md, modules/testing/builder/projects/hello-world-app/.browserslistrc, packages/angular/build/BUILD.bazel, packages/angular/build/src/builders/application/tests/behavior/browser-support_spec.ts, packages/angular/build/src/utils/supported-browsers.ts, packages/angular_devkit/build_angular/src/builders/browser/tests/behavior/browser-support_spec.ts, packages/schematics/angular/BUILD.bazel, packages/schematics/angular/config/files/.browserslistrc.template, packages/schematics/angular/config/index.ts, packages/schematics/angular/config/index_spec.ts, pnpm-lock.yaml, pnpm-workspace.yaml, tools/baseline_browserslist/BUILD.bazel, tools/baseline_browserslist/baseline_browserslist.bzl, tools/baseline_browserslist/generate_browserslist.mts, tools/baseline_browserslist/generate_browserslist_spec.mts, tools/baseline_browserslist/index.mts, tools/baseline_browserslist/package.json, tools/baseline_browserslist/tsconfig-build.json, tools/baseline_browserslist/tsconfig-test.json, tools/baseline_browserslist/tsconfig.json
This changes the default `.browserslistrc` file to one generated from a Baseline "widely available" date using `baseline-browser-mapping`, codifying the policy change from https://github.com/angular/angular/pull/60754 into the Angular CLI.
This effectively pins the `.browserslistrc` file to a hard-coded Baseline date, preventing it from automatically updating based on `caniuse-lite` versions managed in user workspaces, which should make Angular's tooling much more stable. Prior to this, expressions like "last 2 Chrome versions" were relative to the installed `caniuse-lite` version and could update at any time. By pinning `.browserslistrc`, we're ensuring that supported browsers only change during Angular major version updates, not arbitrary `caniuse-lite` updates.
Angular CLI now warns if …
=> Update `.browserslistrc` to use Baseline

packages/angular/build/src/builders/karma/application_builder.ts
Early exits and reduce optional chaining.
=> refactor: minor code changes in karma `AngularAssetsMiddleware`

pnpm-lock.yaml, tools/baseline_browserslist/generate_browserslist_spec.mts, tools/baseline_browserslist/package.json
This fixes a bug  where the `widelyAvailableOnDate` was just returning whatever is currently Widely available.
=> build: update `baseline-browser-mapping` to `2.2.1`

packages/schematics/angular/application/files/module-files/src/app/app-module.ts.template, packages/schematics/angular/application/files/standalone-files/src/app/app.config.ts.template, packages/schematics/angular/service-worker/index_spec.ts, packages/schematics/angular/utility/standalone/rules_spec.ts, pnpm-lock.yaml
This commit adds the provider for global error listener in the browser. This is particularly useful for zoneless apps but also useful for Zone-based applications when errors happen outside the Angular zone.
=> feat(@schematics/angular): Add global error listeners to new app generation

packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/src/routes/route-config.ts, packages/angular/ssr/test/routes/ng-routes_spec.ts
Handle `getPrerenderParams` return values when used with wildcard route paths, including support for combined routes like `/product/:id/**`.
Supports returning an array of path segments (e.g., `['category', '123']`) for `**` routes and dynamic segments combined with catch-all routes.
This enables more flexible prerendering configurations in server routes, including handling specific paths such as `/product/1/laptop/123`.
Example:
```ts
{
path: '/product/:id/**',
renderMode: RenderMode.Prerender,
async getPrerenderParams() {
return [
{ id: '1', '**': 'laptop/123' },
{ id: '2', '**': 'laptop/456' }
];
}
}
```
Closes #30035
=> fix(@angular/ssr): support `getPrerenderParams` for wildcard routes

CHANGELOG.md
=> docs: release notes for the v18.2.19 release

CHANGELOG.md
=> docs: release notes for the v19.2.9 release

modules/testing/builder/BUILD.bazel, modules/testing/builder/package.json, packages/angular/build/BUILD.bazel, packages/angular/build/builders.json, packages/angular/build/package.json, packages/angular/build/src/builders/unit-test/builder.ts, packages/angular/build/src/builders/unit-test/index.ts, packages/angular/build/src/builders/unit-test/options.ts, packages/angular/build/src/builders/unit-test/schema.json, packages/angular/build/src/builders/unit-test/tests/options/exclude_spec.ts, packages/angular/build/src/builders/unit-test/tests/options/include_spec.ts, packages/angular/build/src/builders/unit-test/tests/setup.ts, packages/angular/cli/lib/config/workspace-schema.json, pnpm-lock.yaml
When using the application build system via the `@angular/build` package (default for new projects starting in v20), a new experimental unit-test builder is available that initially uses vitest. This experimental system is intended to provide support for investigation of future unit testing efforts within the Angular CLI. As this is experimental, no SemVer guarantees are provided, the API and behavior may change, and there may be unexpected behavior. Available test runners may be added or removed as well.
The setup is somewhat different than the previous unit-testing builders. It uses a similar mechanism to that of the `dev-server` and requires a `buildTarget` option. This allows the code building aspects of the unit-testing process to leverage pre-existing option values that are already …
=> feat(@angular/build): add experimental vitest unit-testing support

packages/angular/ssr/src/app.ts, packages/angular/ssr/src/routes/ng-routes.ts, packages/angular/ssr/src/utils/ng.ts, packages/angular/ssr/test/app_spec.ts, packages/angular/ssr/test/routes/ng-routes_spec.ts
Ensure the server returns a 302 status code and sets the correct 'Location' header when the redirectTo value is a function, aligning with expected HTTP redirect behavior.
=> fix(@angular/ssr): return 302 when redirectTo is a function

packages/angular/build/src/builders/unit-test/builder.ts, packages/angular/build/src/builders/unit-test/options.ts, packages/angular/build/src/builders/unit-test/schema.json
The experimental `unit-test` builder now allows for enabling the experimental vitest browser testing support. A `browsers` option is now available that can list one or more browsers to use for test execution. If the `browsers` option is not specified (the default), then `jsdom` will be used to execute the tests without a browser. To use the browser support, either `playwright` or `webdriverio` must be installed within the project. On startup, the testing process will automatically attempt to discover the browser provider. The browser names present in the `browsers` option must be specified based on the installed provider. Each may have differing names for some browsers.
=> feat(@angular/build): add experimental vitest browser support to unit-testing

packages/angular/build/src/tools/vite/middlewares/chrome-devtools-middleware.ts
Previously, `com.chrome.devtools.json` was generated and served correctly on the first run, but subsequent `ng serve` runs failed to serve the file unless the Angular cache was cleared. This change addresses the inconsistency.
=> fix(@angular/build): ensure `com.chrome.devtools.json` is consistently served after initial run

packages/angular/build/src/tools/esbuild/application-code-bundle.ts
Consolidates common ESBuild plugins and configuration options into a single utility function
=> refactor(@angular/build): merge common plugins and options into `getEsBuildCommonOptions`

packages/schematics/angular/application/index.ts, packages/schematics/angular/application/index_spec.ts
When generating a new project with `ng new` and the `minimal` option, a Typescript project reference to a `tsconfig.spec.json` should not be present since that file is not created with a minimal project.
Closes #30181
=> fix(@schematics/angular): skip spec project reference for minimal ng new

packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/builders/karma/application_builder.ts, packages/angular/build/src/builders/unit-test/options.ts, packages/angular/build/src/utils/project-metadata.ts
The `application`, `karma`, and `unit-test` builders now all use the same utility function to get the project root and project source root paths. This helps ensure consistent behavior and removes repeat code within each.
=> refactor(@angular/build): use utility helper to get project root paths

packages/angular/ssr/test/testing-utils.ts, packages/schematics/angular/application/files/module-files/src/app/app-module.ts.template, packages/schematics/angular/application/files/module-files/src/app/app.spec.ts.template, packages/schematics/angular/application/files/module-files/src/main.ts.template, packages/schematics/angular/application/files/standalone-files/src/app/app.config.ts.template, packages/schematics/angular/application/files/standalone-files/src/app/app.spec.ts.template, packages/schematics/angular/application/index.ts, packages/schematics/angular/application/index_spec.ts, packages/schematics/angular/application/schema.json, packages/schematics/angular/ng-new/index.ts, packages/schematics/angular/ng-new/schema.json, pnpm-lock.yaml, tests/legacy-cli/e2e/tests/build/wasm-esm.ts, tests/legacy-cli/e2e/tests/generate/application/application-zoneless.ts
=> Remove "experimental" from zoneless and add prompt for new apps

.github/workflows/ci.yml, .github/workflows/pr.yml
This should avoid extra downloads on every run, mitigating instabilities from e.g. GitHub downloads that are currently a bit unstable.
=> ci: setup bazel repository caching for windows jobs

packages/angular/build/src/builders/unit-test/builder.ts, packages/angular/build/src/builders/unit-test/karma-bridge.ts, packages/angular/build/src/builders/unit-test/schema.json
The `runner` option for the `unit-test` builder can now be set to `karma`. This leverages the existing `karma` builder for test execution. The `karma` build related options are derived from the provided `buildTarget` option instead of being manually specified within the `unit-test` builder. In other areas, the test execution is the same with the exceptions of specifying either a custom configuration file and/or a custom main file.
NOTE: The `unit-test` builder is considered experimental. Direct usage of the `karma` builder is currently recommended for production applications.
=> refactor(@angular/build): provide karma runner for unit-test builder

packages/schematics/angular/application/index.ts
To reduce the size of the initial `angular.json` for applications, newly generated zoneless applications will no longer contain an explicit empty `polyfills` option. The option can still be added and is available for use if needed by an application but the empty array value will no longer be present when generating a zoneless application.
This has no effect for applications using Zone.js (default).
=> fix(@schematics/angular): avoid empty polyfill option for new zoneless application

goldens/public-api/angular_devkit/core/index.api.md, packages/angular_devkit/core/src/logger/level.ts, packages/angular_devkit/core/src/utils/partially-ordered-set.ts, packages/angular_devkit/core/src/virtual-fs/host/memory.ts, packages/angular_devkit/core/src/virtual-fs/host/pattern.ts, packages/angular_devkit/core/src/virtual-fs/host/record.ts, packages/angular_devkit/core/src/virtual-fs/path.ts, packages/angular_devkit/core/src/workspace/json/metadata.ts
To eventually support the use of the TypeScript `isolatedDeclarations` option, additional type adjustments have been made to code within the `@angular-devkit/core` package. While this is not yet comprehensive, it significantly reduces the amount of build errors with the `isolatedDeclarations` option enabled.
=> refactor(@angular-devkit/core): additional isolated declarations cleanup

CHANGELOG.md
=> docs: release notes for the v19.2.10 release

WORKSPACE
This reverts commit 100571f03790bb5cf40a54b31b5f3cf902a2c46f.
The hope here is that it will address the spurious "module not found" issues we have seen.
=> Revert "build: update devinfra digest to 8ca74b8"

CHANGELOG.md, package.json
The previous "next" release-train has moved into the feature-freeze phase. This PR updates the next branch to the subsequent release-train.
Also this PR cherry-picks the changelog for v20.0.0-next.9 into the main branch so that the changelog is up to date.
=> Update next branch to reflect new release-train "v20.1.0-next.0".

packages/angular_devkit/schematics/src/engine/engine.ts, packages/angular_devkit/schematics/src/engine/schematic.ts, packages/angular_devkit/schematics/src/sink/host.ts, packages/angular_devkit/schematics/src/tree/action.ts, packages/angular_devkit/schematics/src/tree/entry.ts, packages/angular_devkit/schematics/src/tree/host-tree.ts, packages/angular_devkit/schematics/src/tree/null.ts, packages/angular_devkit/schematics/src/tree/recorder.ts, packages/angular_devkit/schematics/src/tree/scoped.ts, packages/angular_devkit/schematics/src/tree/static.ts
To support the eventual use of the TypeScript `isolatedDeclarations` option, explicit return types have been added to functions throughout the `@angular-devkit/schematics` package code.
=> refactor(@angular-devkit/schematics): add explicit return types to functions

packages/angular/build/src/builders/unit-test/builder.ts
The `unit-test` builder's `reporters` option will now pass through the values to the underlying unit-test runner. This allows customization of the reporters used when executing tests.
The `unit-test` builder is currently considered experimental.
=> fix(@angular/build): enable unit-test reporters option

goldens/public-api/angular_devkit/core/index.api.md, packages/angular_devkit/core/src/utils/partially-ordered-set.ts
`Set` isn't a stable interface, it's a concrete type that changes over time (new spec versions may add methods, older ones may lack methods). There shouldn't be a huge downside to just declaring this class as "its own thing".
Follow-up to https://github.com/angular/angular-cli/pull/30208 which breaks on google3 import because the `Set` types are subtly different because of different TS configs.
=> refactor(@angular-devkit/core): don't use concrete type as interface

packages/angular/pwa/pwa/index.ts, packages/schematics/angular/application/index.ts, packages/schematics/angular/application/index_spec.ts, tests/legacy-cli/e2e/initialize/500-create-project.ts, tests/legacy-cli/e2e/tests/build/jit-ngmodule.ts, tests/legacy-cli/e2e/tests/build/prerender/discover-routes-ngmodule.ts, tests/legacy-cli/e2e/tests/build/rebuild-dot-dirname.ts, tests/legacy-cli/e2e/tests/build/relative-sourcemap.ts, tests/legacy-cli/e2e/tests/build/server-rendering/express-engine-ngmodule.ts
With the index option now defaulting to `<project_source_root>/index.html` for the `application` build system, the explicit value present in new applications is no longer required. This removal further reduces the size of the `angular.json` file for new projects.
=> fix(@schematics/angular): remove explicit index option from new applications

packages/angular/build/src/builders/unit-test/builder.ts
Ensure proper cleanup of the Angular testing module when running tests with Vitest.
Closes: #30186
---
Blocked on https://github.com/angular/angular/pull/61017 being released on NPM
=> fix(@angular/build): perform testing module cleanup when using Vitest

packages/angular/build/src/builders/karma/application_builder.ts, packages/angular/build/src/builders/karma/tests/behavior/rebuilds_spec.ts
The internal karma common middleware that handles requests converts the to be cached data into a string when stored. This can lead to invalid data when the cached string is then sent in a followup request if the original content was not intended to be a string. To avoid this  problem, asset files are now explicitly not cached by karma's middleware.
Ref: https://github.com/karma-runner/karma/blob/84f85e7016efc2266fa6b3465f494a3fa151c85c/lib/middleware/common.js#L72
Closes #30198
=> fix(@angular/build): avoid internal karma request cache for assets

packages/angular/build/src/tools/esbuild/bundler-context.ts
When using esbuild, Angular sets up a custom file watcher using esbuilds metafile inputs. Esbuild will generate <define:KEY> entries see https://esbuild.github.io/try/#YgAwLjI1LjMALS1kZWZpbmU6Rk9PPSd7fScgLS1tZXRhZmlsZSAtLWJ1bmRsZQBlAGVudHJ5LmpzAGNvbnNvbGUubG9nKEZPTyk. After the build is finished, the file watcher will notice that the <define:KEY> entries no longer exist on the file system and trigger a rebuild even though no files have changed.
No rebuilds are triggered since the file watcher is no longer tracking changes to <define:KEY> entries.
There other conditions which may also trigger a rebuilds, because the file watcher is tracking all inputs from the …
=> perf(@angular/cli): fix unnecessary esbuild rebuilds

scripts/windows-testing/convert-symlinks.mjs
With the recent commit to rework the convert symlink script, we
addressed the high flakiness of module resolution errors due to
broken/missing symlinks. Though, this commit introduces a new source of
flakiness that we tried to avoid in the past— running too many WSL exe's
at the same time. We fix this by reducing the batch size and adding
another retry for safety.
In addition, the patch branch uses an older NodeJS version where
`fs.cp` seems to have issues when the source files are readonly— so we
fix that by just invoking the shell's `cp` command. That one works.
=> build: improve stability of windows jobs further

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/builders/application/schema.json, packages/angular/build/src/builders/application/tests/options/browser_spec.ts
The application build system's `browser` option is now considered optional. If not present, the value will be an `main.ts` file within the configured project source root (`sourceRoot`). This change allows the removal of the `browser` option from any project that uses the default generated value.
=> fix(@angular/build): allow a default application `browser` option

packages/angular/build/src/builders/application/execute-build.ts, packages/angular/build/src/builders/application/i18n.ts, packages/angular/build/src/tools/angular/compilation/aot-compilation.ts, packages/angular/build/src/tools/esbuild/i18n-inliner-worker.ts, packages/angular/build/src/tools/esbuild/i18n-inliner.ts
When using the development server with the `application` build system and HMR has been enabled (default), component templates with i18n are now eligible to be hot reloaded. If translations exist within the template, they will also be translated assuming a matching translation is available. Changing the content of an i18n block may result in a missing translation warning/error. The development server continues to only support a single enabled locale.
Closes #29457
=> fix(@angular/build) allow component HMR for templates with i18n

packages/angular/build/src/tools/esbuild/bundler-context.ts
The internal bundler (`esbuild`) may use virtual files to represent added content to the output files. This includes names such as `<define:???>` and `<runtime>` to reference object define values and runtime code, respectively. It may also use paths that end with `(disabled):<node_builtin_name>` where `<node_builtin_name>` is one of Node.js' builtin modules. All these cases are now handled by the file watching system and will not be attempted to be watched. Previously these virtual files would be considered removed by the file watching system as they do not actually exist on the file system.
Closes #30197
=> fix(@angular/build): avoid attempting to watch bundler internal files

packages/angular_devkit/build_angular/src/utils/process-bundle.ts, tests/legacy-cli/e2e/tests/i18n/ivy-localize-sub-path.ts
The `subPath` option was not being properly applied when using the webpack-based browser builder.
Closes #30247
=> fix(@angular-devkit/build-angular): correctly set i18n subPath in webpack browser builder

constants.bzl, packages/angular/cli/src/commands/version/cli.ts
Node.js 24 has been released https://nodejs.org/en/about/previous-releases
=> fix(@angular/cli): add Node.js 24 as supported version

CHANGELOG.md
=> docs: release notes for the v19.2.11 release

.github/workflows/ci.yml, WORKSPACE, tools/toolchain_info.bzl
This update configures the CI pipeline to execute e2e tests using Node.js v24.
=> ci: enable e2e test runs on Node.js 24

packages/angular/build/src/builders/unit-test/builder.ts, packages/angular/build/src/builders/unit-test/options.ts
When using the `application` build system with the experimental `unit-test` vitest support, the `watch` option will now be passed through to the underlying test runner. This allows vitest to be used for watch-based test development. Incremental test file updates from the build system are also enabled in watch mode as well to remove the need to rewrite all output files on a rebuild.
=> fix(@angular/build): allow vitest-based unit testing to use watch option

renovate.json
This change uses the dev-infra preset.
=> ci: refactor renovate config to use dev-infra preset

packages/angular/build/src/utils/load-proxy-config.ts, packages/angular_devkit/architect/node/node-modules-architect-host.ts, packages/angular_devkit/build_angular/src/tools/webpack/configs/dev-server.ts, packages/angular_devkit/build_webpack/src/utils.ts
Resolve `ERR_REQUIRE_ASYNC_MODULE` when attempting to `require()` ESM modules in a CommonJS context.
Closes #30286
=> fix(@angular/cli): properly handle Node.js `require()` errors with ESM modules

.github/workflows/ci.yml
Snapshot updates occur only on the `main` branch, so running them on patch branches provides no benefit.
=> ci: skip `e2e-snapshots` on non-main branches

packages/angular/build/src/builders/unit-test/builder.ts, packages/angular/build/src/builders/unit-test/options.ts, packages/angular/build/src/builders/unit-test/schema.json
The experimental `unit-test` builder with the `vitest` runner configured can now specify an Angular providers file via the `providersFile` option. This allows the TestBed initialization to use the providers defined in this file for all executed tests. The contents of the providers file should include a default export with an array of one or more Angular providers. As an example:
```
import { provideZonelessChangeDetection } from '@angular/core';
export default [
provideZonelessChangeDetection(),
];
```
=> fix(@angular/build): allow TestBed provider configuration with vitest unit-testing

packages/angular/build/src/builders/unit-test/builder.ts
When using the experimental `unit-test` builder with the `vitest` runner and the `browsers` option, an error will now be reported if the `@vitest/browser` package is not found. Previously, the tests would attempt to execute and produce a runtime error and stack trace. Now an explicit error with instructions to install the package will be printed to the console prior to building and executing the tests.
=> fix(@angular/build): show unit-test error for missing vitest browser package

WORKSPACE
Update `rules_ts_dependencies` to use TypeScript 5.8.3
=> build: update TypeScript integrity to 5.8.3

packages/angular/build/src/builders/unit-test/builder.ts
The experimental `unit-test` builder with the `vitest` runner now provides the test APIs also as globals. This increases the potential compatibility for existing karma/jasmine based tests. The initial unit tests within a newly generated application, for instance, now require no changes to execute with the new builder.
=> fix(@angular/build): provide vitest globals in unit-test builder

packages/angular/build/src/builders/unit-test/builder.ts
To ensure that Zone.js is fully setup and patched prior to the use of TestBed, the setup file order for the `vitest` runner of the `unit-test` builder has been swapped. This is particularly relevant for `fakeAsync` which has a module level statement that attempts to capture the `Zone` instance. If Zone.js is not setup at that point, fakeAsync will fail to function in tests.
=> fix(@angular/build): setup unit-test polyfills before TestBed init

CHANGELOG.md
=> docs: release notes for the v19.2.12 release

packages/schematics/angular/environments/index_spec.ts, packages/schematics/angular/server/index_spec.ts, packages/schematics/angular/service-worker/index.ts, packages/schematics/angular/service-worker/index_spec.ts, packages/schematics/angular/ssr/index_spec.ts, packages/schematics/angular/utility/standalone/util.ts
The Angular schematics that require knowledge of the main entry point of an application will now use the default value for the `application` builder. The default value as per the `application` build system is `<project_source_root>/main.ts`.
=> fix(@schematics/angular): support using default browser option when not present

CHANGELOG.md
=> docs: release notes for the v20.0.0-rc.1 release

packages/angular/build/src/builders/unit-test/builder.ts
The previous change caused Zone.js related test failures when using vitest as a test runner.
This reverts commit 8b2ca7ae2617d0e6a1854693dbd24408a4cbe4fb.
=> fix(@angular/build): revert setup unit-test polyfills before TestBed init

CHANGELOG.md
=> docs: release notes for the v20.0.0-rc.2 release

packages/angular/build/src/builders/unit-test/builder.ts, packages/angular/build/src/builders/unit-test/karma-bridge.ts, packages/angular/build/src/builders/unit-test/options.ts, packages/angular/build/src/builders/unit-test/schema.json
When using the experimental `unit-test` builder with the `vitest` runner, a `debug` option is now available which configures the underlying runner to setup and use the Node Inspector to debug tests. This reduces the complexity to support debugging unit tests via a command execution of `ng test --debug`. This will cause the test process to initialize and then wait for a debugger to connect prior to executing the tests.
=> fix(@angular/build): provide direct debugging support for unit test builder

packages/angular/build/src/builders/unit-test/builder.ts
To provide improved Zone.js support with the experimental `unit-test` builder using the `vitest` runner, the TestBed initialization now uses the global `beforeEach`/`afterEach` test hooks. The global hooks can be patched by Zone.js. The vitest globals are always available when using the `unit-test` builder.
=> fix(@angular/build): use global unit-test hooks during TestBed init

packages/angular/ssr/src/utils/ng.ts
This fixes SSR to ensure serialization is not broken when router is not provided.
=> fix(@angular/ssr): SSR should work without `@angular/router`

packages/angular/build/src/builders/unit-test/options.ts
When using the experimental `unit-test` builder, the `watch` option will now default to true when there is an interactive terminal and not on CI. This more closely aligns with the behavior of the existing `karma` builder and that of vitest itself. CI is determined by the presence of a "truthy" `CI` environment variable.
=> fix(@angular/build): enable unit-test builder watch outside CI

packages/angular/pwa/README.md, packages/angular/pwa/pwa/files/assets/manifest.webmanifest, packages/angular/pwa/pwa/index.ts, packages/angular/pwa/pwa/index_spec.ts
These properties are unnecessary and create additional maintenance overhead for developers.
Closes: #30336
=> fix(@angular/pwa): remove `background_color` and `theme_color` from manifest

packages/schematics/angular/application/files/module-files/src/app/app.spec.ts.template, packages/schematics/angular/application/files/module-files/src/app/app.ts.template, packages/schematics/angular/application/files/standalone-files/src/app/app.spec.ts.template, packages/schematics/angular/application/files/standalone-files/src/app/app.ts.template
This follows the updated style guide recommendations.
https://next.angular.dev/style-guide#use-protected-on-class-members-that-are-only-used-by-a-components-template
=> fix(@schematics/angular): use protected for class member

packages/angular/build/src/builders/unit-test/builder.ts
When using the experimental `unit-test` builder with the `vitest` runner and code coverage, the automatic coverage excludes are now adjust to not include the bundled test files. This previously prevent accurate coverage analysis. Vite does this as a convenience but is problematic for the bundling strategy employed by the builder's test setup. To workaround this, the excludes are adjusted here to only automatically exclude the TypeScript source test files.
Closes #30333
=> fix(@angular/build): exclude only source test files with unit-test vitest support

WORKSPACE, constants.bzl, docs/DEVELOPER.md, package.json, packages/angular/build/src/utils/load-proxy-config.ts, packages/angular/cli/lib/cli/index.ts, packages/angular_devkit/architect/node/node-modules-architect-host.ts, packages/angular_devkit/build_angular/src/tools/webpack/configs/dev-server.ts, packages/angular_devkit/build_webpack/src/utils.ts
Bumps the minimum Node.js support for `@angular/cli`. This update ensures compatibility with a growing number of upstream dependencies, such as Undici and Pacote, that are adopting newer Node.js versions. These versions where selected as `require(esm)` is enabled by default. This change also prepares us for future package releases that will likely rely on this behavior.
=> fix(@angular/cli): update min Node.js support to 20.19, 22.12, and 24.0

packages/angular/build/src/builders/unit-test/builder.ts
With the experimental `unit-test` builder with the `vitest` runner, the underlying vitest execution will no longer attempt to load external configuration files. The current internal vitest usage does not support integration of external configuration files.
=> fix(@angular/build): ensure disabled vitest config loading

CHANGELOG.md
=> docs: release notes for the v19.2.13 release

CHANGELOG.md
=> docs: release notes for the v20.0.0-rc.3 release

packages/schematics/angular/migrations/migration-collection.json, packages/schematics/angular/migrations/replace-provide-server-routing/migration.ts, packages/schematics/angular/migrations/replace-provide-server-routing/migration_spec.ts
Previously, `provideServerRoutesConfig` was not properly migrated to `provideServerRendering`. This change ensures the migration is handled correctly.
=> fix(@schematics/angular): migrate `provideServerRoutesConfig` to `provideServerRendering`

packages/angular_devkit/build_angular/package.json, packages/angular_devkit/build_angular/src/utils/spinner.ts, packages/angular_devkit/schematics/package.json, packages/angular_devkit/schematics/tasks/package-manager/executor.ts, pnpm-lock.yaml
This commit update ora to version 8.
=> build: update ora to version 8

packages/angular/build/src/builders/dev-server/vite-server.ts
This commit refactors the HMR logic within `@angular/build` to explicitly check for AOT.
=> refactor(@angular/build): check that AOT is enabled in HMR logic

packages/angular/build/src/builders/dev-server/vite-server.ts
Currently, the HMR (Hot Module Replacement) functionality in `@angular/build` requires AOT compilation to be enabled. However, when using JIT compilation, a message indicating that HMR is enabled is incorrectly displayed.
=> fix(@angular/build): HMR requires AOT do not show HMR enabled when using JIT

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
Include class metadata and JIT information in code built for development and/or test usage. All non-optimized builds will now contain this metadata (`optimization.scripts` is false). The Angular TestBed APIs require additional metadata for the Angular aspects of the application such as Components, Modules, Pipes, etc.
TestBed may also leverage JIT capabilities during testing (e.g., `overrideComponent`). To support all these TestBed usage scenarios both the underlying `setClassMetadata` and `setNgModuleScope` class augmentation functions are now emitted when test metadata inclusion is enabled.
=> fix(@angular/build): include full metadata for AOT unit-testing

packages/angular/build/src/tools/esbuild/javascript-transformer-worker.ts
To more completely avoid having to load any Angular compiler linking code when analyzing for code transformations during a build, the declaration function checks are now performed directly. This is in contrast to the previous behavior that required importing the linker code to use a helper function included in the `@angular/compiler-cli` package. Avoiding the need to load and parse a potentially large amount of code to perform the check can improve performance for the cases where no linking is required. To ensure the check stays up to date and while the list of function names rarely changes, the linker must always use the existing function name prefix (`ɵɵngDeclare`) for any declaration functions.
=> perf(@angular/build): directly check code for Angular partial linking

packages/angular/build/src/builders/dev-server/tests/options/hmr_spec.ts, packages/angular/build/src/builders/dev-server/vite-server.ts
The https://angular.dev/hmr URL is now used in the HMR enabled console message for the development server. The message text has also been shortened as the information is available at the aforementioned documentation location.
=> refactor(@angular/build): use new HMR documentation URL for console message

packages/angular/build/src/tools/esbuild/javascript-transformer.ts
The avoid unnecessary logic to be executed for every call to `transformFile`.
=> refactor(@angular/build): update `ensureWorkerPool` to do an early exit

packages/angular_devkit/architect/src/architect.ts, packages/angular_devkit/architect/src/jobs/simple-scheduler.ts
Removed JSON schema-based validation for internal job arguments, inputs, and outputs in architect builder jobs. This validation applied to internal architect values.
Builder option validation remains unaffected. Eliminating this validation reduces overhead from costly RxJS operations, improving performance, especially for builders producing large outputs that were previously delayed by this processing.
=> refactor(@angular-devkit/architect): remove redundant internal job schema validation

packages/angular/cli/bin/bootstrap.js
When using the Angular CLI within Bazel, the Node.js compile cache can be enabled by setting the `NODE_COMPILE_CACHE` environment variable to a filesystem path.
This allows opt-in usage based on the Bazel execution environment.
Compile cache documentation:
https://nodejs.org/api/module.html#module-compile-cache
=> refactor(@angular/cli): allow opt-in Node.js compile cache for Bazel

CHANGELOG.md
=> docs: release notes for the v20.0.0-rc.4 release

CHANGELOG.md
=> docs: release notes for the v19.2.14 release

packages/angular/cli/package.json, packages/angular/cli/src/command-builder/command-module.ts, packages/angular/cli/src/command-builder/command-runner.ts, packages/angular/cli/src/command-builder/utilities/command.ts, packages/angular/cli/src/command-builder/utilities/json-help.ts, packages/angular/cli/src/command-builder/utilities/normalize-options-middleware.ts, packages/angular/cli/src/commands/analytics/cli.ts, packages/angular/cli/src/commands/cache/cli.ts, packages/angular/cli/src/commands/completion/cli.ts, pnpm-lock.yaml
See associated pull request for more information.
Closes #30399 as a pr takeover
=> build: update dependency yargs to v18

packages/schematics/angular/migrations/use-application-builder/migration.ts, packages/schematics/angular/migrations/use-application-builder/migration_spec.ts
When performing an `ng update` to Angular v20, the application migration will detect the usage of the `karma` builder's `karmaConfig` option and attempt to remove usages of the no longer needed `@angular-devkit/build-angular` karma framework and plugin usage. While the karma framework usage will be specifically ignored when using the `@angular/build:karma` builder, the plugin usage leverages a direct `require` within the configuration file. Regardless of the ability of the builder to ignore, neither usage is needed with `@angular/build:karma` and removing the code aligns with what would be generated by `ng generate config karma`.
Closes #30413
=> fix(@schematics/angular): remove karma config devkit package usages during application migration

packages/angular/build/src/builders/application/options.ts, packages/angular/build/src/builders/application/schema.json, packages/angular/build/src/builders/application/tests/behavior/loader-import-attribute_spec.ts, packages/angular/build/src/builders/application/tests/options/loader_spec.ts, packages/angular/build/src/builders/karma/schema.json, packages/angular/build/src/tools/esbuild/loader-import-attribute-plugin.ts
This passes through the existing esbuild functionality to support dataurl and base64 loaders, in addition to the pre-existing text, binary, and file loaders.
Both the dataurl and base64 loaders return strings with the relevant content. There is no way to control whether the dataurl method uses base64 or plain text encoding, and no way to control the mime type it detects.
Fixes #30391
Currently only the text/binary/file esbuild loaders are usable.
Issue Number: #30391
This adds the dataurl/base64 loaders as well.
It wasn't clear to me how to cause the documentation at e.g. https://angular.dev/tools/cli/build-system-migration#file-extension-loader-customization to be updated. I …
=> feat(@angular/build): add dataurl, base64 loaders

packages/angular/cli/bin/ng.js
Enhances the Node.js version validation to include Node.js 22.12
=> fix(@angular/cli): improve Node.js version check and error messages

modules/testing/builder/BUILD.bazel, packages/angular/cli/BUILD.bazel, packages/angular/pwa/BUILD.bazel, packages/angular/ssr/schematics/BUILD.bazel, packages/angular_devkit/architect/BUILD.bazel, packages/angular_devkit/architect/node/BUILD.bazel, packages/angular_devkit/build_angular/BUILD.bazel, packages/angular_devkit/core/BUILD.bazel, packages/angular_devkit/core/node/BUILD.bazel, packages/angular_devkit/schematics/BUILD.bazel, packages/angular_devkit/schematics/tools/BUILD.bazel, packages/angular_devkit/schematics_cli/test/BUILD.bazel, packages/ngtools/webpack/BUILD.bazel, packages/schematics/angular/BUILD.bazel, tools/baseline_browserslist/BUILD.bazel
Renamed unit test targets for easier execution without needing to inspect build files.
=> build: simplify unit test target names

tools/defaults.bzl
This doesn't seem to surface here, but in the framework and in the COMP repo, the glob wasn't catching all files because it wasn't escaped— so didn't actually get picked up by Jasmine, but was expanded by Bash.
This improves the rule and makes this logic more future-proof.
=> build: improve globbing of jasmine test files

.ng-dev/dx-perf-workflows.yml
[610a36702ef3d7867bef70b0403f0847c5e3904b](https://github.com/angular/angular-cli/commit/610a36702ef3d7867bef70b0403f0847c5e3904b) renamed some test targets and broke these references.
=> build: fix perf workflows

packages/schematics/angular/application/files/common-files/src/app/app.html.template, packages/schematics/angular/application/files/module-files/src/app/app.ts.template, packages/schematics/angular/application/files/standalone-files/src/app/app.ts.template, tests/legacy-cli/e2e/tests/build/prerender/error-with-sourcemaps.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-server.ts, tests/legacy-cli/e2e/tests/misc/forwardref-es2015.ts
Now that signals are recommended, this updates the generated `AppComponent` to use a signal for the `title` field.
=> feat(@schematics/angular): use signal in app component

package.json, packages/angular_devkit/build_angular/package.json, pnpm-lock.yaml
=> build: update dependency webpack-dev-server to v5.2.2

packages/angular/build/src/tools/esbuild/bundler-context.ts
When using the `application` build system with i18n enabled, the development server may unintentionally attempt to optimize virtual internal files for the locale data. These virtual files are now excluded from the list of external imports.
Closes #30491
=> fix(@angular/build): do not consider internal Angular files as external imports

packages/angular/build/src/builders/unit-test/builder.ts
When using the experimental `unit-test` builder with the `vitest` runner,
the build option's global stylesheet file (output: `styles.css`) will now
be included in the generated `index.html` file used when browser mode is
enabled.
The global stylesheets used are currently limited to the default `styles.css`
output file. If custom named global stylesheets are configured, they will
not currently be injected into the test index HTML file used with browser
testing.
Closes #30444
=> fix(@angular/build): support injecting global styles into vitest unit-tests

CHANGELOG.md
=> docs: release notes for the v19.2.15 release

CHANGELOG.md
=> docs: release notes for the v20.0.2 release

packages/schematics/angular/server/index.ts
Add logic to automatically include `main.server.ts` in the `files` array of the tsconfig when present during schematic execution. This ensures backwards compatibility for applications generated prior to version 19.
Closes #30526
=> fix(@schematics/angular): include `main.server.ts` in `tsconfig.files` when present

packages/angular/build/src/builders/karma/application_builder.ts
When using the `karma` builder, the generated output JavaScript file was unintentionally being marked as a module type script. This prevent the output file from providing equivalent behavior to that of an actual build. The `scripts` option outputs should be considered classic scripts to the browser.
Closes #30534
=> fix(@angular/build): set scripts option output as classic script for karma

packages/angular/build/src/builders/karma/application_builder.ts
When using the `karma` builder with custom "scripts" option entries that contain the `bundleName` suboption, the output files for these scripts will now correctly be injected into the test index HTML content. Previously only the default `scripts.js` output file would be used.
=> fix(@angular/build): include custom bundle name scripts with karma

packages/angular/build/src/builders/unit-test/builder.ts
The `codeCoverageReporters` option has no effect.
The vitest coverage reporters option is `reporter` and not `reporters`, see https://vitest.dev/config/#coverage-reporter
=> fix(@angular/build): coverage reporter option

CHANGELOG.md
=> docs: release notes for the v20.0.3 release

packages/angular/build/src/utils/worker-pool.ts
This reverts commit 1d76d0ee59d54a889b564bdf85f183fd08ddc860.
This has been fixed in 5.1.1
=> Revert "fix(@angular/build): increase worker idle timeout"

tsconfig-test.json
Remove outdated `@bazel/tsetse` plugin configuration from test TS configuration. With the `rules_js` migration, `@bazel/tsetse` is no longer used.
=> test: remove unneeded bazel tsetse configuration

packages/angular/build/src/utils/server-rendering/manifest.ts, packages/angular/ssr/src/manifest.ts, packages/angular/ssr/src/routes/ng-routes.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-preload-links.ts
This change to `@angular/ssr` prevents the preloading of dynamically imported bundles that aren't directly associated with routing.
Previously, Angular SSR might preload all dynamic bundles, even those not immediately required, such as deferred chunks within components.
Closes #30541
=> fix(@angular/ssr): avoid preloading unnecessary dynamic bundles

renovate.json
`verdaccio` currently is has missing dependencies.
=> ci: disable `verdaccio` auto updates

packages/angular/ssr/node/src/request.ts, packages/angular/ssr/node/test/request_http1_spec.ts, packages/angular/ssr/node/test/request_http2_spec.ts
The `Referer` header is classified as a forbidden header name within the Web Standard Fetch API. This means it cannot be manually set directly within the `headers` option, instead it must be set when constructing a `new Request()` object.
Closes #30581
=> fix(@angular/ssr): ensure correct referer header handling in web request conversion

renovate.json
This requires some changes due to the below error:
```
ERROR: error loading package '@@devinfra//bazel/browsers/chromium': Every .bzl file must have a corresponding package, but '@@io_bazel_rules_webtesting//web:web.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
```
=> ci: disable auto updates for `io_bazel_rules_webtesting`

packages/angular_devkit/build_angular/package.json, pnpm-lock.yaml
This dependency is no longer needed.
Closes #30613
=> fix(@angular-devkit/build-angular): remove unused `@vitejs/plugin-basic-ssl` dependency

packages/angular/build/BUILD.bazel
We've added more tests (yay!) but at least when running on RBE, this seems to have made things less stable.
I've tried to run the tests a few times with `--config=remote --nocache_test_results` and this appears to make them pass consistently. There may be a more perfect integer but x2 should give us stable CI again (at least for this issue).
=> build: use more shards for application builder tests

CHANGELOG.md, package.json
CI insisted I reformat the `CHANGELOG.md` file to insert some extra newlines. I suspect the formatting tool has changed behavior slightly.
=> Bump version to "v20.0.5" with changelog.

packages/ngtools/webpack/BUILD.bazel
This seems to be timing out occasionally in CI.
=> test: raise timeout of `//packages/ngtools/webpack:test`

packages/angular/build/src/builders/karma/application_builder.ts, packages/angular/build/src/builders/karma/index.ts, packages/angular/build/src/builders/karma/tests/options/scripts_spec.ts
Remove proxy to handle `/` to `/base/` instead update the `AngularAssetsMiddleware`
Closes #30639
=> fix(@angular/build): failed to proxy error for assets

goldens/public-api/angular_devkit/schematics/index.api.md, packages/angular_devkit/schematics/src/engine/engine.ts, packages/angular_devkit/schematics/src/rules/base.ts, packages/angular_devkit/schematics/src/rules/template.ts, packages/angular_devkit/schematics/src/sink/dryrun.ts, packages/angular_devkit/schematics/src/sink/host.ts, packages/angular_devkit/schematics/src/tree/recorder.ts
Several type only changes have been made to the schematics code to support the eventual compilation of the package with TypeScript's `isolatedDeclarations` option. This is not yet comprehensive and more changes will be needed to fully support the option.
=> refactor(@angular-devkit/schematics): initial isolated declarations type adjustments

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/karma/application_builder.ts, packages/angular/build/src/builders/karma/index.ts, packages/angular/build/src/builders/karma/options.ts, packages/angular/build/src/builders/karma/schema.json, packages/angular/build/src/builders/unit-test/schema.json, packages/angular/build/src/private.ts, packages/angular_devkit/build_angular/src/builders/karma/index.ts
This issue stems from the `Some of your tests did a full page reload` error, which occurs because `karmaOptions.client.clearContext` is set to `true` when `singleRun` is `false`, even though Karma is running in watch mode. Previously, the `watch` flag was configured inconsistently across multiple locations, leading to misalignment.
Closes #30506
=> fix(@angular/build): resolve "Controller is already closed" error in Karma

modules/testing/builder/projects/hello-world-app/karma.conf.js, modules/testing/builder/src/builder-harness.ts, modules/testing/builder/src/test-utils.ts, packages/angular/build/BUILD.bazel, packages/angular/build/src/builders/application/tests/options/output-path_spec.ts, packages/angular/build/src/builders/application/tests/options/polyfills_spec.ts, packages/angular_devkit/build_angular/src/builders/app-shell/app-shell_spec.ts, packages/angular_devkit/build_angular/src/builders/ng-packagr/works_spec.ts, packages/angular_devkit/build_angular/src/builders/prerender/works_spec.ts, packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/karma.conf.js
=> Stablize CI tests

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/unit-test/builder.ts, packages/angular/build/src/builders/unit-test/karma-bridge.ts, packages/angular/build/src/builders/unit-test/options.ts, packages/angular/build/src/builders/unit-test/schema.json
When using the experimental unit-test builder with Vitest, a new `setupFiles` option is now available. This option is similar to the Vitest option in that it allows for setup and configuration prior to each test. The `setupFiles` are executed after any application polyfills as well as after the TestBed initialization. If custom TestBed initialization is needed (this is not typical), The TestBed environment can first be reset in a setupFile and then initialized as needed. Note that resetting the TestBed environment in this way will cause the `providersFile` to no longer add any providers to the tests and any custom providers would need to be manually added during initialization.
=> fix(@angular/build): support extra test setup files with unit-test vitest runner

packages/angular/build/src/utils/index-file/inline-fonts.ts, pnpm-lock.yaml
See associated pull request for more information.
Closes #30625 as a pr takeover
=> build: lock file maintenance

CHANGELOG.md
=> docs: release notes for the v20.0.6 release

packages/angular/build/src/builders/dev-server/vite-server.ts
These values are incompatible with HMR.
Closes #30697
=> fix(@angular/build): emit a warning when `outputHashing` is set to `all` or `bundles` when HMR is enabled

packages/angular/build/src/builders/application/build-action.ts, packages/angular/build/src/builders/karma/find-tests.ts, packages/angular/build/src/builders/unit-test/builder.ts, packages/angular/build/src/tools/esbuild/application-code-bundle.ts, packages/angular/build/src/tools/esbuild/global-styles.ts, packages/angular/build/src/tools/sass/rebasing-importer.ts, packages/angular/build/src/utils/path.ts, packages/angular/build/src/utils/server-rendering/prerender.ts, packages/angular/build/src/utils/service-worker.ts
Ensures that code coverage `include` patterns are converted to a POSIX-style format.
Closes #30698
=>  fix(@angular/build): normalize code coverage include paths to POSIX

packages/angular/cli/BUILD.bazel, packages/angular/cli/package.json, packages/angular/cli/src/commands/mcp/constants.ts, packages/angular/cli/src/commands/mcp/mcp-server.ts, packages/angular/cli/src/commands/mcp/tools/doc-search.ts, pnpm-lock.yaml
An additional MCP tool is now available with the `ng mcp` stdio MCP server that supports querying the `angular.dev` documentation. This uses the same algolia based search indexing that the documentation website uses. Rate limiting has been implemented with the MCP tool that may be adjusted based on feedback. The tool returns one or more URLs and titles for relevant documentation for a given query. Content of these search results are currently not fetched but rather this action is deferred to the host to determine which items are most relevant and should be retrieved from the documentation website.
=> refactor(@angular/cli): add a documentation search tool to MCP server

packages/angular/cli/src/commands/mcp/mcp-server.ts, packages/angular/cli/src/commands/mcp/tools/best-practices.ts
The Angular CLI's stdio-based MCP server now contains a tool to get an Angular best practices guide. This is in addition to a resource with the same content. The tool provides a description that strongly encourages the use of this tool and its content when performing Angular related tasks. This is useful in cases where MCP resource usage is not available or the resource would need to manually be added as context for specific use cases.
=> refactor(@angular/cli): add a get best practices guide MCP tool

WORKSPACE, goldens/public-api/angular_devkit/schematics/index.api.md, package.json, packages/angular/build/package.json, packages/angular/build/src/builders/application/tests/behavior/rebuild-errors_spec.ts, packages/angular/build/src/tools/esbuild/javascript-transformer.ts, packages/angular/cli/src/command-builder/utilities/schematic-workflow.ts, packages/angular_devkit/architect/testing/test-project-host.ts, packages/angular_devkit/build_angular/package.json, packages/angular_devkit/core/src/virtual-fs/host/buffer.ts, packages/angular_devkit/schematics/src/sink/dryrun.ts, packages/angular_devkit/schematics/src/sink/host.ts, packages/angular_devkit/schematics_cli/bin/schematics.ts, packages/ngtools/webpack/package.json, packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel, packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript.d.ts, pnpm-lock.yaml
Updates the repo to the TypeScript 5.9 beta and widens the peer dependency ranges.
=> build: update to TypeScript 5.9 beta

packages/angular/cli/src/commands/mcp/tools/doc-search.ts
The MCP tool description for the Angular CLI's documentation search tool has been expanded to include more context regarding its use and result format. When no results are found, an explicit text response is also now generated to indicate this case.
=> refactor(@angular/cli): improve description of MCP documentation search tool

packages/angular/cli/src/commands/mcp/tools/doc-search.ts
When using the documentation search MCP tool within the Angular CLI's MCP server, the top search result will now also include the main content of the documentation page. This removes the need for followup action to retrieve the content for the likely needed information. Any additional results found will continue to include the URL but no content.
=> refactor(@angular/cli): include content for top result in MCP documentation search tool

packages/angular/cli/src/commands/mcp/mcp-server.ts, packages/angular/cli/src/commands/mcp/tools/projects.ts
Move the list projects MCP tool for the Angular CLI's MCP server to a separate file within the tools subdirectory. This provides a more consistent structure that matches the other tools in the server.
=> refactor(@angular/cli): move MCP list projects tool to separate file

packages/angular/build/src/builders/unit-test/builder.ts, packages/angular/build/src/builders/unit-test/schema.json
Headless mode is currently supported only for `karma` via `browsers: [ 'ChromeHeadless', 'FirefoxHeadless' ]`. However, it is not supported for Vitest browser mode. See [Headless](https://vitest.dev/guide/browser/#headless) for more information.
I considered two solutions for Vitest:
**Solution 1 (Committed / Implemented):**
This solution is compatible with how Karma handles headless mode, allowing for migration without configuration changes:
```json
"options": {
"tsConfig": "tsconfig.spec.json",
"buildTarget": "::development",
"runner": "vitest",
"browsers": ["ChromiumHeadless"]
}
```
**Solution 2:**
Introduce a new **headless** property in the schema. This approach is not …
=> feat(@angular/build): add headless mode for vitest browser mode

packages/angular/build/package.json, packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts, pnpm-lock.yaml
This fixes an issue with sourcemaps
Closes #30731
=> fix(@angular/build): update `vite` to `7.0.6`

CHANGELOG.md
Cherry-picks the changelog from the "20.1.x" branch to the next branch (main).
=> docs: release notes for the v20.1.3 release

WORKSPACE, package.json, packages/schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel, pnpm-lock.yaml
Updates to the release candidate of TypeScript 5.9.
=> build: update to TypeScript 5.9 RC

packages/angular/build/src/builders/dev-server/tests/behavior/build-assets_spec.ts, packages/angular/build/src/tools/vite/middlewares/assets-middleware.ts
This change ensures that Vite's CSS transformation is only applied to actual stylesheets and not assets.
Closes #30792
=> fix(@angular/build): skip vite transformation of CSS-like assets

packages/angular/cli/src/commands/mcp/mcp-server.ts
When the MCP server is initialized outside of an Angular workspace, workspace-specific tools such as  `list_projects` should not be registered as they will not function correctly.
=> fix(@angular/cli): skip workspace-specific tools when outside a workspace

.github/workflows/pr.yml
Currently seems to be broken due to https://github.com/Vampire/setup-wsl/issues/76. We're only disabling for PRs right now to unblock ongoing work, `main` will continue to fail until the root cause is addressed.
=> ci: temporarily disable Windows CI for PRs

CHANGELOG.md
Cherry-picks the changelog from the "20.1.x" branch to the next branch (main).
=> docs: release notes for the v20.1.4 release

goldens/public-api/angular_devkit/build_webpack/index.api.md, packages/angular_devkit/build_angular/package.json, packages/angular_devkit/build_angular/src/tools/webpack/plugins/karma/karma.ts, packages/angular_devkit/build_webpack/package.json, packages/angular_devkit/build_webpack/src/builders/webpack-dev-server/index.ts, packages/angular_devkit/build_webpack/src/builders/webpack/index.ts, packages/ngtools/webpack/package.json, pnpm-lock.yaml
Updates Webpack to version 5.101.0.
Also adds runtime assertions to ensure that a Webpack compiler instance is always created when expected.
=> build: update Webpack to v5.101.0

packages/angular/cli/src/commands/mcp/mcp-server.ts, tests/legacy-cli/e2e/tests/mcp/registers-tools.ts
Introduces the first end-to-end test for the MCP server. The new test, `registers-tools.ts`, verifies that the MCP server correctly initializes and registers its default set of tools. This provides a foundation for more comprehensive e2e testing of the MCP server and its features.
=> test(@angular/cli): add initial e2e test for MCP server tool registration

packages/angular/cli/src/commands/mcp/tools/best-practices.ts
Caches the content of the best practices instructions to avoid redundant file reads on subsequent uses of the tool. This can provide a minor performance improvement in cases where the tool is used multiple times during a single CLI process.
Also, annotations have been added to the text to provide additional context for the assistant and allow for more tailored display of the information.
=> fix(@angular/cli): cache MCP best practices content and add tool annotations

packages/angular/cli/src/commands/version/cli.ts, packages/angular/cli/src/commands/version/version-info.ts
Refactors the `version` command's output generation for better readability and maintainability. This also allows other parts of the CLI to gather the version info programmatically, if needed.
The key changes include:
- Extracting the output formatting logic from the `run` method into a new private `formatVersionInfo` function.
- Introducing a `VersionInfo` interface to provide a clear data structure for the version details.
- Moving the ASCII art logo to a module-level constant to separate presentation from logic.
- Relocating the `gatherVersionInfo` function, `VersionInfo` interface, and related constants to a new `version-info.ts` file to better organize the code.
=> refactor(@angular/cli): separate the version command's analysis logic from logging

packages/angular/build/src/private.ts
The `ComponentStylesheetBundler` class is now available from the `private` entry point for the `@angular/build` package. All items exposed from this entry point are not subject to SemVer guarantees and may change between releases. Use with caution as breakage may occur when updating versions.
=> refactor(@angular/build): provide private component stylesheet bundling API for internal compilation infrastructure

packages/angular/cli/src/commands/mcp/mcp-server.ts, packages/angular/cli/src/commands/mcp/tools/examples.ts
The experimental MCP server now supports an additional environment variable for test purposes that allows custom markdown code examples to be used with the `find_examples` tool. This uses the `NG_MCP_EXAMPLES_DIR` environment variable.
=> refactor(@angular/cli): add MCP test support for custom code examples

packages/schematics/angular/migrations/use-application-builder/migration.ts, packages/schematics/angular/migrations/use-application-builder/stylesheet-updates.ts, packages/schematics/angular/migrations/use-application-builder/stylesheet-updates_spec.ts
Reorganizes the `use-application-builder` migration by extracting the stylesheet-related logic into a separate, more focused file.
The key changes include:
- Moving stylesheet-related functions (`hasLessStylesheets`, `hasPostcssConfiguration`, `updateStyleImports`, and their helpers) from `migration.ts` into a new `stylesheet-updates.ts` file.
- Updating the main `migration.ts` file to import these functions from the new module.
=> refactor(@schematics/angular): organize use-application-builder migration

packages/schematics/angular/application/index.ts, packages/schematics/angular/library/index.ts, packages/schematics/angular/migrations/replace-provide-server-rendering-import/migration.ts, packages/schematics/angular/migrations/use-application-builder/migration.ts, packages/schematics/angular/service-worker/index.ts, packages/schematics/angular/utility/dependency.ts, packages/schematics/angular/utility/dependency_spec.ts
Adds two new utility functions to the schematics dependency helper library:
- getDependency: Allows a schematic to query a package.json and check for the existence of a dependency, returning its version and type if found.
- removeDependency: Provides a schematic rule to safely remove a dependency from any of the dependency sections in a package.json.
Refactors several schematics (`application`, `library`, `service-worker`, and two migrations) to use the new, centralized dependency management utilities (`addDependency`, `removeDependency`, `getDependency`).
=> refactor(@schematics/angular): add getDependency and removeDependency utilities

packages/angular/cli/src/commands/mcp/resources/best-practices.md
This removes the common pitfall for if blocks in the mcp best practices, as this is no longer true in Angular v20.2, see https://github.com/angular/angular/commit/a409534d6c3d7cb4472afffd6b17df8c25e34106
=> refactor(@angular/build): remove mcp best practice for if aliases

packages/angular/cli/src/commands/mcp/tools/modernize.ts
`.ng.html` is not used unless `ngHtml` is set to true when generating a component. but the current style guide does not recommend to use `.ng.html`.
Uses `.html` instead.
=> refactor(@angular/cli): use .html as template extension for mcp modernize tool

packages/schematics/angular/library/index.ts
Prior to this the `typeSeparator` could have been inherited from the workspace setting which would cause the file references to be incorrect.
Closes #30886
=> fix(@schematics/angular): correct configure the `typeSeparator` in the library schematic

CHANGELOG.md, package.json
Also this PR cherry-picks the changelog for v20.2.0-rc.0 into the main branch so that the changelog is up to date.
=> Update next branch to reflect new release-train "v20.3.0-next.0".

packages/schematics/angular/ai-config/schema.json
With this change, we allow the AI config prompt to be skipped by pressing "ENTER" without selecting "None" and it will default to "None".
=> fix(@schematics/angular): allow AI config prompt to be skipped without selecting a value

packages/angular/cli/src/commands/mcp/tools/best-practices.ts, tests/legacy-cli/e2e/tests/mcp/best-practices.ts
The package internal path for the Angular best practices markdown file has been corrected to the new location following a previous refactoring.
=> fix(@angular/cli): use correct path for MCP get_best_practices tool

packages/angular/build/src/typings.d.ts
The manual type declaration is no longer needed with newer versions of the Node.js types (`@types/node`).
=> refactor(@angular/build): remove manual Node.js types for getCompileCacheDir

packages/angular/build/src/builders/unit-test/builder.ts, packages/angular/build/src/builders/unit-test/runners/karma/index.ts, packages/angular/build/src/builders/unit-test/runners/karma/runner.ts, packages/angular/build/src/builders/unit-test/runners/vitest/index.ts, packages/angular/build/src/builders/unit-test/runners/vitest/runner.ts, packages/angular/build/src/builders/unit-test/test-discovery.ts
The main `unit-test` builder is refactored to act as a dispatcher, delegating the core execution to runner-specific implementations. This change significantly improves the structure and maintainability of the testing infrastructure.
Key changes:
- A new `runners` directory is created within the `unit-test` builder to house runner-specific logic.
- All Vitest-related logic is extracted from the main builder and moved into `runners/vitest/`.
- The Karma bridge is moved into `runners/karma/`.
- A new `test-discovery.ts` file is introduced to centralize test finding logic, with a TODO to move the implementation there in the future.
=> refactor(@angular/build): modularize unit-test builder with runner-specific logic

.github/shared-actions/windows-bazel-test/action.yml, .github/workflows/pr.yml, WORKSPACE
This commit fixes and re-enables windows CI. 
Upstream fixes:
- https://github.com/devversion/rules_browsers/pull/18
- https://github.com/angular/dev-infra/pull/2966
=> ci: re-enable windows CI [main]

tests/legacy-cli/e2e/tests/mcp/registers-tools.ts
This is causing Windows CI to fail to the `silentNpm` being terminated.
=> refactor: await `silentNpm`

packages/angular/ssr/src/utils/ng.ts
This workaround is needed to;
- Re-enable SSG in ADEV
- Re-enable SSR tests in angular/angular main
- Make cross-repo updates green again
=> refactor(@angular/ssr): add workaround for router `lastSuccessfulNavigation` breaking changing

scripts/windows-testing/convert-symlinks.mjs
Prior to this change, there was a flaw in its handling of the retry logic, specifically within the `setTimeout` block. The function had a recursive promise resolution problem and an incorrect handling of the rejected state.
=> build: improve retry exec logic

packages/angular/cli/src/command-builder/utilities/json-schema.ts, packages/angular/cli/src/command-builder/utilities/json-schema_spec.ts
This commit enhances the command-line parser in `@angular/cli` by adding support for displaying available choices when a command option is of type `array` and has an `enum`.
=> fix(@angular/cli): add choices to command line parser when type is array and has an enum

packages/angular/cli/src/command-builder/command-module.ts, packages/angular/cli/src/command-builder/schematics-command-module.ts, packages/angular/cli/src/command-builder/utilities/json-schema.ts
This commit includes minor changes to how analytics are handled, including:
- Removing unnecessary type castings.
- Concatenating arrays into strings for Google Analytics, as it doesn't support arrays.
- Applying default values to multi-select prompts for a smoother user experience.
=> refactor(@angular/cli): improve analytics handling

packages/angular/cli/src/commands/mcp/cli.ts, packages/angular/cli/src/commands/mcp/mcp-server.ts
The recently added options to the MCP server are noteasily discoverable
The `mcp` command now lists the possible options.
The experimental tools discovery has also been improved by listing the possible options.
=> refactor(@angular/cli): improve discoverability of mcp server options

packages/angular/ssr/src/utils/ng.ts
This reverts commit 2fde130b3736d690a2bb9a56a87a549f357c7e3b.
This workaround is no longer needed since today we'll cut 21.0.0-next.0
=> Revert "refactor(@angular/ssr): add workaround for router `lastSuccessfulNavigation` breaking changing"

MODULE.bazel.lock, package.json, pnpm-lock.yaml
This contains a fix for updating the bazel lock file during the release, which otherwise would cause the build and CI to break.
See: https://github.com/angular/dev-infra/pull/2975
=> build: update `@angular/ng-dev` to `4fead3666abc9c5dfff101a8bfdc7a2d02f78982`

packages/angular/cli/src/commands/add/cli.ts
=> Several additional `ng add` improvements and cleanup

packages/angular/cli/lib/config/workspace-schema.json, packages/angular/cli/src/commands/update/schematic/schema.json, packages/angular/create/src/index.ts, packages/angular_devkit/core/src/json/schema/registry_spec.ts, packages/angular_devkit/schematics/tasks/package-manager/executor.ts, packages/angular_devkit/schematics_cli/blank/schema.json, packages/angular_devkit/schematics_cli/schematic/schema.json, packages/schematics/angular/ng-new/schema.json, packages/schematics/angular/workspace/schema.json, tests/angular_devkit/core/json/schema/serializers/schema_benchmark.json
This change removes the direct support for cnpm within the Angular CLI.
BREAKING CHANGE: The `ng` commands will no longer automatically detect and use `cnpm` as the package manager. As an alternative use the `.npmrc` file to ensure npm uses the cnpm registry.
=> feat(@angular/cli): remove direct support for `cnpm`

.github/shared-actions/windows-bazel-test/action.yml, .github/workflows/pr.yml, scripts/windows-testing/parallel-executor.mjs
On Windows 2025, `D:/` was re-introduced again this week to improve performance https://github.com/actions/runner-images/issues/12744
Also, this change reduced the shards to 1 on PR workflow, additional we also fix an issue where in each shard we split the tests into another 4 shards which on Windows causes a lot of IO operations.
Difference:  `e2e_windows (windows-2025, 22, npm, 1)` from `48m 13s` to `20m 16s`
=> ci: use `D:/` instead of `C:/` and sharding fixes

packages/angular/cli/src/command-builder/utilities/schematic-engine-host.ts, packages/schematics/angular/migrations/karma/karma-config-comparer.ts, packages/schematics/angular/migrations/migration-collection.json
To attempt to workaround Windows pathing issues in the karma configuration migration, the default karma template is now resolved via `require.resolve`.
=> fix(@schematics/angular): directly resolve karma config template in migration

packages/schematics/angular/app-shell/index.ts, packages/schematics/angular/component/index.ts, packages/schematics/angular/config/index.ts, packages/schematics/angular/directive/index.ts, packages/schematics/angular/module/index.ts, packages/schematics/angular/pipe/index.ts, packages/schematics/angular/server/index.ts, packages/schematics/angular/service-worker/index.ts, packages/schematics/angular/ssr/index.ts, packages/schematics/angular/utility/project.ts, packages/schematics/angular/web-worker/index.ts
Introduces a new `createProjectSchematic` helper to abstract the common logic of looking up a project within the workspace. This pattern was repeated across many schematics.
The following project-scoped schematics have been refactored to use the new helper:
- app-shell
- component
- config
- directive
- module
- pipe
- server
- service-worker
- ssr
- web-worker
This change simplifies the implementation of these schematics, reduces code duplication, and improves maintainability.
REVIEWER NOTE: Enable "Hide whitespace" option
=> refactor(@schematics/angular): use a project-based schematic helper to reduce boilerplate

packages/angular/cli/src/commands/mcp/tools/modernize.ts, packages/angular/cli/src/commands/mcp/tools/modernize_spec.ts
The `test-bed-get` migration is not runnable via `ng g @angular/core` and references a non-existing documentation page. `zoneless` does not exist for now (Angular v20.2.0-rc.0).
This removes the mentioned migrations
=> refactor(@angular/cli): remove non runnable migrations in mcp modernize tool

.github/workflows/ci.yml, .github/workflows/pr.yml
Disabling the PNPM cache resolves an issue where pnpm install is being run inside WSL, causing the action to fail due to missing path.
See: https://github.com/angular/dev-infra/pull/2998
=> ci: Disable PNPM cache on Windows

.github/shared-actions/windows-bazel-test/action.yml, .github/workflows/pr.yml, scripts/windows-testing/parallel-executor.mjs, tests/legacy-cli/e2e_runner.ts
This ensures that the glob is expanded by the Node.js package as otherwise not all tests will be picked up.
=> ci: do not expand glob in shell

packages/schematics/angular/app-shell/index_spec.ts, packages/schematics/angular/component/index.ts, packages/schematics/angular/pipe/index.ts, packages/schematics/angular/service-worker/index.ts, packages/schematics/angular/service-worker/index_spec.ts, packages/schematics/angular/ssr/index.ts, packages/schematics/angular/utility/ast-utils.ts, packages/schematics/angular/utility/ast-utils_spec.ts, packages/schematics/angular/utility/standalone/rules.ts, packages/schematics/angular/web-worker/index.ts
Usages of the `tags` template literal utility have been removed.
The logic has been refactored to use standard JavaScript template literals and string manipulation methods to achieve the same formatting results. This change affects multiple schematics and their tests.
=> refactor(@schematics/angular): remove tags usage from @angular-devkit/core

packages/angular/build/src/builders/karma/application_builder.ts
The factory function for the `reporter:angular--polyfills` Karma plugin did not return a value, which violates Karma's plugin contract. This could cause Karma to crash when multiple reporters were in use, particularly with tools that use Karma's multi-reporter functionality.
This change modifies the factory to return an object with an empty `adapters` array (`{ adapters: [] }`). This satisfies Karma's plugin requirements and ensures compatibility with the multi-reporter, preventing the crash.
Fixes #31039
=> fix(@angular/build): ensure karma polyfills reporter factory returns a value

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts, packages/angular/build/src/tools/esbuild/angular/rewrite-bazel-paths.ts
The compiler plugin now rewrites Bazel file paths if they were resolved outside of the execution root.
This behavior is only used if Bazel environment variables are present.
=> fix(@angular/build): correct JS/TS file paths when running under Bazel

packages/schematics/angular/tailwind/index.ts, packages/schematics/angular/tailwind/index_spec.ts
The tailwind schematic's stylesheet injection logic has been updated to support a wider range of project configurations. Previously, it assumed a `styles.css` file was always present, which could cause issues in projects using CSS preprocessors like Sass/SCSS.
Instead of unconditionally creating a new `.postcssrc.json` file, the schematic now searches for `postcss.config.json` or `.postcssrc.json` in both the workspace and project roots. If an existing configuration file is found, it is updated with the required `@tailwindcss/postcss` plugin. A new configuration file is only created if one does not already exist.
=> Improve existing project Tailwind CSS schematic integration

.github/workflows/ci.yml, .github/workflows/pr.yml, BUILD.bazel, MODULE.bazel, MODULE.bazel.lock, tools/test/expected_package.json
Within our module.bazel file when describing the version of typescript to use for rules_ts, we use ts_version instead of ts_version_from to prevent our package.json file from being part of the set of files used to calculate the sha for the lock file.  Any unrelated change to the version of the typescript file would end up causing our lockfile to be out of date. This amount of churn has proven to be too much for our current setup. We instead now test to validate the versions defined in the package.json and MODULE.bazel files match.
=> build: define typescript version via string in module.bazel file

packages/angular/cli/src/commands/add/cli.ts
Previously, `ng add` would install a package and then fail if the package did not support schematics.
This change improves the user experience by checking for `ng add` support after installation. The package is still installed, but the command now provides a clear, user-friendly message if no `ng add` actions are available, preventing an unnecessary error. If the package's manifest contains a homepage URL, it is included in the message to provide the user with a helpful next step. The dry run messaging is also updated to reflect this new behavior.
=> refactor(@angular/cli): improve logging with `ng add` for packages without schematics

packages/angular/cli/src/command-builder/utilities/json-schema.ts
This change prevents the CLI from setting a default value for array options that have a length of zero. Previously, this would result in an empty array being added  as a default, which isn't the intended behavior.
=> fix(@angular/cli): don't set a default for array options when length is 0

tests/legacy-cli/e2e/tests/commands/add/add-tailwindcss.ts
Add an explicit removal of previous `tailwindcss` at the start of the `commands/add/add-tailwindcss.ts` E2E test to workaround issues with npm not fully uninstalling the package from previous tests.
=> test: workaround npm cleanup for ng add tailwind E2E

packages/angular/cli/src/commands/mcp/tools/modernize.ts
The `modernize` MCP tool's description and schemas are rewritten to clarify its primary function: providing instructions and commands for an AI model to execute.
The new description includes detailed operational notes on how to use the tool's output, especially for the multi-step 'standalone' migration. The input and output schema descriptions are also enhanced to provide better context.
=> refactor(@angular/cli): rewrite modernize MCP tool's description and schemas for clarity

packages/angular/cli/src/commands/mcp/tools/onpush-zoneless-migration/zoneless-migration.ts
The description for the `onpush-zoneless-migration` MCP tool is rewritten to use a structured format with `<Purpose>`, `<Use Cases>`, and `<Operational Notes>` tags.
=> refactor(@angular/cli): rewrite best-practices MCP tool description for clarity

packages/angular/cli/src/commands/mcp/tools/best-practices.ts, packages/angular/cli/src/commands/mcp/tools/examples.ts
The `find_examples` MCP tool is updated to frame it as a RAG (Retrieval-Augmented Generation) source, focusing on modern and recently updated Angular features.
The tool's description is rewritten to guide the AI on when to use this tool versus the documentation search. A structured output schema is also added to make the results more reliable, and the handler is updated to return data in the new format.
=> refactor(@angular/cli): add structured output to examples MCP tool

packages/angular/cli/src/commands/mcp/tools/projects.ts, packages/angular/cli/src/commands/mcp/tools/tool-registry.ts, tests/legacy-cli/e2e/tests/mcp/registers-tools.ts
The `list_projects` MCP tool is enhanced with better monorepo support by correctly discovering all `angular.json` files in any subdirectory.
The tool's description is also rewritten to follow best practices for LLM consumption, using structured tags like `<Purpose>`, `<Use Cases>`, and `<Operational Notes>` to provide clear and actionable guidance.
Closes #30855
=> fix(@angular/cli): improve list_projects MCP tool to find all workspaces in monorepos

packages/angular/build/src/builders/dev-server/vite/index.ts
In SSR applications, an unnecessary event loop tick during server startup could lead to an incorrect platform being initialized.
This change introduces an `ngJitMode` define, which is set to `false` during AOT builds. This allows for the JIT-specific code paths to not be followed, preventing the async operations that caused the extra tick. This ensures that the server platform is correctly and synchronously initialized.
=> fix(@angular/build): avoid extra tick in SSR dev-server builds

packages/angular/cli/src/commands/mcp/tools/projects.ts
Improves the reliability of the `list_projects` MCP tool by refactoring its underlying workspace discovery function, `findAngularJsonFiles`.
The previous recursive implementation could fail in large monorepos. This new approach uses a queue-based, concurrent traversal to prevent stack overflow errors in deep repositories and file descriptor exhaustion (`EMFILE` errors) in wide ones.
Additionally, the search now excludes dot-directories and common build/cache folders to improve performance and avoid incorrect results from build artifacts.
=> refactor(@angular/cli): use iterative search for workspace discovery in MCP `list_projects` tool

packages/angular/cli/src/commands/mcp/tools/doc-search.ts
This commit enhances the `search_documentation` MCP tool by improving its error handling and the quality of the data it returns.
The key changes are:
- **Error Logging:** The content fetching logic now logs a warning if it fails to retrieve or parse the documentation page, providing better visibility for debugging without crashing the tool.
- **HTML Removal:** The fetched HTML content now has all tags removed, providing the AI with clean, plain-text content. This reduces noise, lowers the token count, and improves the quality of the input for the language model.
=> refactor(@angular/cli): add logging and HTML removal to doc search tool

packages/angular/build/src/builders/unit-test/builder.ts
To ensure that output media files do not overwrite each other if source media files use the same base file name but are contained in different directories, the output hashing option from the build target will now keep the `media` option enabled if configured.
(cherry picked from commit f806f6477af222907f1879181fb0f9839e889ea8)
=> [20.2.x] fix(@angular/build): maintain media output hashing with vitest unit-testing

packages/angular/cli/src/command-builder/architect-command-module.ts
When running an Architect command for a specific project, the process title is now updated to include the project's name. This provides better visibility in process lists, making it easier to identify which project is being built or served, especially in multi-project workspaces.
The original process title is restored after the command finishes execution.
Closes #31110
=> fix(@angular/cli): set process title when running architect commands

packages/schematics/angular/application/index.ts, packages/schematics/angular/tailwind/index.ts, packages/schematics/angular/tailwind/schema.json
When generating a new application or using the application schematic with the `tailwind` style option, the `skipInstall` option was being ignored. This resulted in dependencies being installed even when `--skip-install` was specified.
This change ensures that the `skipInstall` option is correctly passed to and handled by the Tailwind schematic, preventing automatic package installation when requested.
=> fix(@schematics/angular): respect skip-install for tailwind schematic

packages/angular/cli/src/commands/mcp/mcp-server.ts
This commit refactors the top-level `instructions` for the MCP server to provide clearer, more structured, and actionable guidance for an AI assistant.
Following the best practices for LLM-centric documentation, the new instructions:
- Use a structured tag-based format (`<General Purpose>`, `<Core Workflows>`, etc.) to improve parsability.
- Establish a mandatory "first step" workflow, instructing the AI to always use the `list_projects` tool to gather context before taking other actions.
- Provide a high-level guide to the available tools, mapping them to common user intents (e.g., answering questions, writing code).
- Define key domain concepts like "Workspace" vs. "Project" to improve the AI's operational model in a monorepo.
This change helps the AI behave more reliably and …
=> refactor(@angular/cli): add structured workflows to MCP server instructions

packages/angular/build/BUILD.bazel, packages/angular/build/src/builders/unit-test/runners/vitest/executor.ts
The `initializeVitest` method within the Vitest test executor was overly large and handled multiple distinct responsibilities, including setup file preparation and Vite plugin configuration.
This change refactors the method by extracting these responsibilities into separate private methods: `prepareSetupFiles` and `createVitestPlugins`. This improves the overall readability, testability, and maintainability of the executor by better separating concerns without changing its behavior.
=> refactor(@angular/build): improve readability of Vitest executor

packages/angular/build/BUILD.bazel, packages/angular/build/src/builders/karma/find-tests.ts, packages/angular/build/src/builders/karma/find-tests_spec.ts, packages/angular/build/src/builders/unit-test/runners/vitest/build-options.ts, packages/angular/build/src/builders/unit-test/runners/vitest/executor.ts, packages/angular/build/src/builders/unit-test/schema.json, packages/angular/build/src/builders/unit-test/tests/options/watch_spec.ts
Test coverage reporting within the Vitest runner was inaccurate because the test files themselves were being included in the coverage analysis. This was caused by how the in-memory provider directly loaded the test content.
This commit resolves the issue by introducing an intermediate virtual module for each test. The test entry point now only imports this module, which in turn contains the bundled test code. This extra layer of indirection prevents Vitest from including the test files in the coverage results, leading to an accurate analysis.
To support this change, the `getTestEntrypoints` function now removes the `.spec` or `.test` extension from bundle names, ensuring cleaner module identifiers. The Vitest runner has also been updated to better handle coverage exclusion options and …
=> fix(@angular/build): correct Vitest coverage reporting for test files

packages/angular/build/src/tools/esbuild/application-code-bundle.ts, packages/angular/build/src/tools/vite/utils.ts, tests/legacy-cli/e2e/tests/build/prerender/error-with-sourcemaps.ts
This commit introduces the `keepNames` option in esbuild configurations for both application code bundling and Vite utility functions.
By setting `keepNames` to `true` (or conditionally based on optimization settings), function and variable names are preserved during the build process. This significantly improves the debugging experience in **development mode** by ensuring that original names are retained in compiled output, leading to more readable stack traces and easier identification of code sections during development.
=> fix(@angular/build): preserve names in esbuild for improved debugging in dev mode

packages/angular/build/package.json, packages/angular_devkit/build_angular/package.json, packages/ngtools/webpack/package.json
Now that https://github.com/angular/angular/pull/63589 has landed, we can drop support for TypeScript 5.8.
* TypeScript versions older than 5.9 are no longer supported.
=> fix(@angular/build): drop support for TypeScript 5.8

packages/angular/cli/src/utilities/package-manager.ts
This commit refactors the package manager lockfile detection logic to:
- Introduce a `LOCKFILE_NAMES` constant for better maintainability and clarity.
- Enhance Bun lockfile detection by checking for both `bun.lockb` and `bun.lock`.
- Optimize lockfile checks by reading the root directory files once and passing them to the `hasLockfile` method, reducing redundant file system operations.
This addresses issues where Bun lockfiles might not have been correctly identified.
closes #31128
=> fix(@angular/cli): improve bun lockfile detection and optimize lockfile checks

packages/angular/cli/src/commands/mcp/tools/examples.ts, tools/example_db_generator.js
=> Additional MCP find examples improvements

modules/testing/builder/BUILD.bazel, modules/testing/builder/package.json, packages/angular/build/src/builders/unit-test/tests/options/code-coverage-exclude_spec.ts, packages/angular/build/src/builders/unit-test/tests/options/code-coverage-reporters_spec.ts, packages/angular/build/src/builders/unit-test/tests/options/code-coverage_spec.ts, pnpm-lock.yaml
The tests for the the `codeCoverage`, `codeCoverageExclude`, and `codeCoverageReporters` options have now been enabled.
=> test(@angular/build): enable unit-test builder coverage tests

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/unit-test/options.ts, packages/angular/build/src/builders/unit-test/runners/karma/executor.ts, packages/angular/build/src/builders/unit-test/schema.json, packages/angular/build/src/builders/unit-test/tests/options/reporters_spec.ts
This change enhances the `reporters` option in the unit-test builder to support passing an options object, similar to the existing `codeCoverageReporters` option. Users can now specify a reporter as a tuple of `[name, options]`.
- The `schema.json` is updated to allow either a string or a `[string, object]` tuple in the `reporters` array. An `enum` is provided for common reporters while still allowing custom string paths.
- The option normalization logic in `options.ts` is refactored into a shared helper function to handle both `reporters` and `codeCoverageReporters`, reducing code duplication.
- The Karma runner, which does not support reporter options, is updated to safely ignore them and warn the user.
=> feat(@angular/build): allow options for unit test reporters

modules/testing/builder/BUILD.bazel, modules/testing/builder/package.json, packages/angular/build/src/builders/unit-test/builder.ts, packages/angular/build/src/builders/unit-test/runners/api.ts, packages/angular/build/src/builders/unit-test/runners/dependency-checker.ts, packages/angular/build/src/builders/unit-test/runners/karma/index.ts, packages/angular/build/src/builders/unit-test/runners/vitest/index.ts, pnpm-lock.yaml
Previously, missing peer dependencies for test runners (e.g., `jsdom`, `karma-coverage`, `playwright`) were only discovered late in the execution process, often leading to cryptic errors. When multiple packages were missing, this resulted in a frustrating cycle of running the command, installing a package, and repeating.
This change introduces a comprehensive, upfront dependency validation system:
- A `validateDependencies` hook is added to the `TestRunner` interface, allowing each runner to declare its own requirements.
- A `DependencyChecker` class now collects all missing dependencies and reports them to the user in a single, clean error message without a stack trace.
- Both the Karma and Vitest runners implement this hook to check for all required packages based on the user's …
=> fix(@angular/build): add upfront dependency validation for unit-test runners

modules/testing/builder/src/index.ts, modules/testing/builder/src/jasmine-helpers.ts, packages/angular/build/src/builders/application/tests/behavior/rebuild-errors_spec.ts, packages/angular/build/src/builders/application/tests/behavior/rebuild-web-workers_spec.ts, packages/angular/build/src/builders/application/tests/behavior/typescript-rebuild-lazy_spec.ts, packages/angular/build/src/builders/application/tests/options/allowed-common-js-dependencies_spec.ts, packages/angular/build/src/builders/application/tests/options/bundle-budgets_spec.ts, packages/angular/build/src/builders/application/tests/options/i18n-missing-translation_spec.ts, packages/angular/build/src/builders/application/tests/options/scripts_spec.ts, packages/angular/build/src/builders/application/tests/options/style-preprocessor-options-sass_spec.ts, packages/angular/build/src/builders/application/tests/options/styles_spec.ts, packages/angular/build/src/builders/application/tests/options/subresource-integrity_spec.ts, packages/angular/build/src/builders/dev-server/tests/behavior/build-errors_spec.ts, packages/angular/build/src/builders/unit-test/tests/options/browsers_spec.ts, packages/angular/build/src/builders/unit-test/tests/options/debug_spec.ts, packages/angular/build/src/builders/unit-test/tests/options/setup-files_spec.ts
Introduces `expectLog` and `expectNoLog` jasmine helpers to simplify the assertions of logs in tests. This removes the need to use `jasmine.objectContaining` and `jasmine.stringMatching` for this purpose, making the tests more readable and less verbose.
=> test(@angular/build): use expectLog and expectNoLog helpers in tests

package.json, pnpm-workspace.yaml
This change configures pnpm's `minimumReleaseAge` setting to 1 day (1440 minutes). This is a security measure to mitigate dependency chain attacks, where malicious actors publish a new version of a dependency with malicious code and then trick users into updating to it before it can be discovered and reported.
By delaying the adoption of new releases, we reduce the window of opportunity for such attacks. The list of excluded packages contains trusted and frequently updated dependencies from the Angular team, which are considered safe to use without this delay.
=> build: enable minimumReleaseAge to mitigate dependency chain attacks

CHANGELOG.md
=> docs: release notes for the v19.2.17 release

CHANGELOG.md
Cherry-picks the changelog from the "20.3.x" branch to the next branch (main).
=> docs: release notes for the v20.3.2 release

tests/legacy-cli/e2e/tests/build/material.ts, tests/legacy-cli/e2e/tests/build/prerender/http-requests-assets.ts, tests/legacy-cli/e2e/tests/build/server-rendering/server-routes-output-mode-static-http-calls.ts, tests/legacy-cli/e2e/tests/commands/serve/ssr-http-requests-assets.ts
With the recent default flip, these tests are now unexpectedly getting a different zone behavior if they overwrite the app config.
=> test(@angular/build): preserve zone change detection provider

packages/angular/cli/src/commands/mcp/tools/onpush-zoneless-migration/zoneless-migration.ts
This commit refactors the `onpush-zoneless-migration` tool to improve its internal structure, readability, and error handling.
The file discovery and categorization logic has been extracted from the main tool function into a new, dedicated `discoverAndCategorizeFiles` helper function. This change improves separation of concerns and makes the main function's orchestration role clearer.
Additionally, focused `try...catch` blocks have been added to gracefully handle cases where the user provides an invalid or inaccessible file path. This prevents the tool from crashing and provides a clear error message to the user, while allowing other internal errors to propagate correctly.
=> refactor(@angular/cli): improve error handling and structure of zoneless tool

packages/angular/build/src/tools/angular/transformers/jit-bootstrap-transformer.ts, packages/angular/build/src/tools/angular/transformers/jit-resource-transformer.ts, packages/ngtools/webpack/src/ivy/transformation.ts, packages/ngtools/webpack/src/transformers/replace_resources.ts
Fixes usages of a deprecated signature of `createImportClause`.
=> refactor(@angular/build): remove deprecated signature usage

packages/angular/cli/src/commands/new/cli.ts, packages/angular/cli/src/utilities/package-manager.ts, packages/schematics/angular/workspace/files/package.json.template, packages/schematics/angular/workspace/index.ts, packages/schematics/angular/workspace/schema.json, tests/legacy-cli/e2e/initialize/500-create-project.ts, tests/legacy-cli/e2e/setup/100-global-cli.ts, tests/legacy-cli/e2e/tests/commands/add/file.ts
When creating a new project, the `packageManager` field in `package.json` will be automatically set to the package manager used to create the project. This helps to ensure that the same package manager is used by all developers working on the project.
The package manager is detected in the following order:
1. `packageManager` field in `package.json`
2. Angular CLI configuration (`angular.json`)
3. Lock files (`package-lock.json`, `yarn.lock`, `pnpm-lock.yaml`)
=> feat(@schematics/angular): set `packageManager` in `package.json` on new projects

CHANGELOG.md
Cherry-picks the changelog from the "20.3.x" branch to the next branch (main).
=> docs: release notes for the v20.3.3 release

packages/angular/build/src/tools/babel/plugins/pure-toplevel-functions.ts, packages/angular/build/src/tools/babel/plugins/pure-toplevel-functions_spec.ts, packages/angular/build/src/tools/esbuild/javascript-transformer-worker.ts, packages/angular_devkit/build_angular/src/tools/babel/presets/application.ts, packages/angular_devkit/build_angular/src/tools/babel/webpack-loader.ts
`new InjectionToken(...)` is not considered pure by default by build tools, which prevents it from being tree-shaken when unused. This can lead to unused services being included in production bundles if they are provided as a default value for a token.
This change marks `new InjectionToken(...)` calls as pure. The `InjectionToken` constructor is side-effect free; its only purpose is to create a token for the dependency injection system. Marking it as pure is safe and  allows build tools like esbuild to tree-shake unused tokens and their dependencies.
Closes https://github.com/angular/angular-cli/issues/31270
=> fix(@angular/build): mark InjectionToken as pure for improved treeshaking

packages/angular/build/src/builders/unit-test/schema.json, packages/angular/cli/src/command-builder/utilities/json-schema.ts, packages/angular/cli/src/command-builder/utilities/json-schema_spec.ts
The JSON schema parsing for command options has been refactored to be more robust and handle more complex schemas. This includes better support for arrays, enums within 'oneOf' and 'anyOf'.
The schema definitions in packages/angular/build/src/builders/unit-test/schema.json have been removed as these are not resolved at this stage of schema processing.
=> fix(@angular/cli): improve JSON schema parsing for command options

packages/schematics/angular/application/files/module-files/src/app/app__suffix__.spec.ts.template, packages/schematics/angular/application/files/standalone-files/src/app/app__suffix__.spec.ts.template, packages/schematics/angular/application/index_spec.ts, packages/schematics/angular/component/files/__name@dasherize@if-flat__/__name@dasherize__.__type@dasherize__.spec.ts.template, packages/schematics/angular/component/index.ts, packages/schematics/angular/component/index_spec.ts, packages/schematics/angular/utility/project-targets.ts, tests/legacy-cli/e2e/tests/jest/no-zoneless.ts
Closes #31193
Currently, when we generate the app using add or generate command, for zoneless apps it uses `fixture.detectChanges()` whereas the docs says to use `fixture.whenStable()`
Issue Number: #31193
If we now create zoneless apps, when generate or add command, `fixture.whenStable()` will be used.
See #31193
=> fix(@schematics/angular): use fixture.whenStable() instead of fixture detectChanges() for zoneless apps

packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts
Previously, any TypeScript file processed by the Angular esbuild plugin had to be part of the main TypeScript compilation defined in `tsconfig.json`. This caused errors for valid use cases, such as importing utility scripts that don't contain Angular-specific code.
This change introduces a more flexible approach:
- If a file is not found in the TS compilation, its contents are checked for Angular metadata (e.g., `@Component`, `@NgModule`).
- If Angular metadata is present, an error is correctly reported with an improved, actionable diagnostic message.
- If no Angular metadata is found, the file is passed to esbuild with a warning, allowing it to be included in the bundle without being type-checked.
This improves the developer experience by reducing build failures for non-critical files …
=> fix(@angular/build): relax requirement for files to be in TS compilation

packages/schematics/angular/ai-config/index.ts, packages/schematics/angular/ai-config/index_spec.ts, packages/schematics/angular/ai-config/schema.json, packages/schematics/angular/ng-new/schema.json
This change introduces support for generating an `AGENTS.md` file via the `ng generate ai-config` schematic. The `AGENTS.md` standard is an emerging convention for providing instructions to AI agents that operate within a codebase.
By adding this option, users can easily create a root-level `AGENTS.md` file, helping to configure AI agents with project-specific guidelines and best practices.
The implementation includes:
- Updating the schematic's `schema.json` to include `agents` as a selectable tool.
- Extending the logic in `index.ts` to handle the creation and placement of the file.
- Adding a unit test to ensure the file is generated correctly.
=> feat(@schematics/angular): add AGENTS.md support to ai-config schematic

packages/angular/build/src/builders/unit-test/runners/vitest/browser-provider.ts
The Vitest browser provider configuration is updated to be more intelligent in automated environments.
Previously, headless mode was only triggered if the browser name included headless. This change automatically enables headless mode when the `CI` environment variable is detected, which is standard practice for continuous integration pipelines.
Additionally, the `ui` property is now explicitly set to the inverse of the `headless` state, preventing the Vitest UI from attempting to render in a non-interactive environment. A `satisfies` clause has also been added to improve type safety against the Vitest configuration options.
=> refactor(@angular/build): automatically enable headless mode in CI for vitest

packages/angular/cli/src/commands/version/cli.ts, packages/angular/cli/src/commands/version/version-info.ts
This commit completely revamps the `ng version` command's output for a more modern and readable experience.
The key improvements include:
- A single, unified table for all packages, removing the separate Angular section.
- A polished table format using box-drawing characters and consistent padding.
- An improved header section with aligned, bolded, and more formal labels.
- The use of color to highlight version numbers and other key information, improving scannability.
- Version lookup errors are now highlighted in red for better visibility.
The header generation logic is also refactored to be more maintainable by removing repeated label strings.
=> feat(@angular/cli): overhaul `ng version` command output

packages/angular/cli/src/commands/cache/info/cli.ts, tests/legacy-cli/e2e/tests/commands/cache/cache-info.ts
This commit refactors the output to be more user-friendly and consistent with other commands like `ng version`. It introduces a clean, aligned, two-column layout with colors to improve readability.
- Labels are now bolded for emphasis.
- Values are colored for clarity (cyan for general info, green/red for statuses).
- The layout is padded to ensure vertical alignment, making the information easier to scan.
=> refactor(@angular/cli): improve output format for `ng cache info` command

packages/angular/build/BUILD.bazel, packages/angular/build/package.json, packages/angular/build/src/builders/application/chunk-optimizer.ts, pnpm-lock.yaml, tests/legacy-cli/e2e/tests/build/chunk-optimizer.ts
Rollup currently appears to be more effective at optimizing total output chunk count. While this is investigated further, the experimental chunk optimizer will be switched back to using rollup.
=> refactor(@angular/build): switch back to rollup for chunk optimizer

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/unit-test/options.ts, packages/angular/build/src/builders/unit-test/runners/karma/executor.ts, packages/angular/build/src/builders/unit-test/runners/karma/index.ts, packages/angular/build/src/builders/unit-test/runners/vitest/executor.ts, packages/angular/build/src/builders/unit-test/runners/vitest/index.ts, packages/angular/build/src/builders/unit-test/schema.json, packages/angular/build/src/builders/unit-test/tests/options/code-coverage-exclude_spec.ts, packages/angular/build/src/builders/unit-test/tests/options/code-coverage-reporters_spec.ts, packages/angular/build/src/builders/unit-test/tests/options/code-coverage_spec.ts
The `unit-test` builder is enhanced with several new coverage features to provide a more robust and configurable testing experience.
This change refactors the existing `codeCoverage` options to a more concise `coverage` prefix for a cleaner API. Since the builder is experimental, this is the ideal time for such an improvement.
The following new options have been added:
- `coverageAll`: Includes all files matching `coverageInclude` in the report, ensuring untested files are visible.
- `coverageInclude`: Specifies which files to include in the report, providing more accurate metrics.
- `coverageThresholds`: Allows setting minimum coverage percentages for statements, branches, functions, and lines. If thresholds are not met, the builder will exit with an error, enabling automated quality …
=> feat(@angular/build): add advanced coverage options to unit-test builder

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/unit-test/builder.ts, packages/angular/build/src/builders/unit-test/schema.json
The `buildTarget` option in the `unit-test` builder is now optional to streamline the user configuration.
If the `buildTarget` option is not provided, the builder now defaults to using the `build` target with the `development` configuration for the current project. This change significantly reduces the boilerplate configuration needed in `angular.json` for most projects, as the builder can now infer the correct build settings by convention.
The builder's schema has been updated to reflect this change by removing `buildTarget` from the required properties and updating its description to document the new default behavior.
=> refactor(@angular/build): make buildTarget optional in unit-test builder

goldens/public-api/angular/build/index.api.md, packages/angular/build/src/builders/unit-test/options.ts, packages/angular/build/src/builders/unit-test/runners/karma/executor.ts, packages/angular/build/src/builders/unit-test/runners/vitest/browser-provider.ts, packages/angular/build/src/builders/unit-test/runners/vitest/executor.ts, packages/angular/build/src/builders/unit-test/schema.json
Introduces a new option, `browserViewport`, to the unit-test builder to allow configuring the browser's viewport size during test execution.
This option accepts a string in the format `widthxheight` (e.g., `1280x720`) and is passed to the underlying browser provider when using the Vitest runner. This is particularly useful for testing responsive layouts or ensuring components render consistently at a specific size.
A warning has been added to the Karma runner to inform users that this option is not supported, preventing confusion and providing clear feedback.
Closes #31321
=> feat(@angular/build): add `browserViewport` option for vitest browser tests

packages/angular/cli/src/commands/mcp/tools/doc-search.ts, packages/angular/cli/src/commands/mcp/tools/projects.ts
The `list_projects` MCP tool is enhanced to include the major version of the Angular framework for each discovered workspace. This provides crucial context, especially in monorepos where different workspaces might use different framework versions.
A new caching mechanism efficiently finds the relevant `package.json` by searching upwards from each workspace, ensuring minimal performance impact in large repositories.
Additionally, the tool now features more robust and distinct error reporting. Failures during the version discovery process are captured and reported separately from `angular.json` parsing failures, providing clearer diagnostics.
=> refactor(@angular/cli): add framework version to `list_projects` MCP tool

packages/angular/cli/src/commands/version/cli.ts, packages/angular/cli/src/commands/version/version-info.ts
The `ng version` command output is enhanced to provide more comprehensive diagnostic information, making it easier for developers to inspect their environment.
These changes include:
- The Angular Framework version is now displayed prominently in the header section for quick reference.
- The package table now includes a "Requested Version" column, showing the version specified in the workspace `package.json`. This helps in quickly identifying any discrepancies between requested and installed versions.
- The columns in the package table have been reordered to `Package`, `Installed Version`, `Requested Version` to prioritize the most critical information and improve the logical flow.
=> feat(@angular/cli): enhance `ng version` output with more details

packages/angular/cli/src/commands/mcp/tools/projects.ts
The `list_projects` tool is enhanced to include the primary builder for each project, providing more specific metadata about its function.
The builder is extracted from the project's 'build' target and added as an optional 'builder' field to the output. This allows users and other tools to quickly determine a project's type (e.g., application, library) by inspecting its builder string.
The tool's description has also been updated to reflect this new capability.
=> feat(@angular/cli): add builder info to list_projects MCP tool 

CHANGELOG.md
Cherry-picks the changelog from the "20.3.x" branch to the next branch (main).
=> docs: release notes for the v20.3.5 release
