angular/angular-cli

- README.md
@IgorMinar can you take a look please?
> chore(README): add instructions to run unit tests

- addon/ng2/blueprints/ng2/files/src/index.html
@cironunes, @filipesilva please check this soon as master still not working.
> fix(vendor): Fix to add concatenated vendors in index.html

- package.json
> chore(build): remove typings postinstall command

- package.json
> fix(ng-serve): match brocolli version with angular

- addon/ng2/blueprints/ng2/files/package.json
Updated to angular2@2.0.0-beta.7
> feat: update to angular2@2.0.0-beta.7

- addon/ng2/commands/version.js
- addon/ng2/index.js
Closes https://github.com/angular/angular-cli/issues/174
> fix(version): outputs version of angular-cli

- addon/ng2/blueprints/ng2/files/src/app.ts
- addon/ng2/blueprints/ng2/files/src/app/__name__.ts
> fix(ng2 blueprint): register provider on root component

- addon/ng2/commands/init.js
> fix(init): set skip-bower to true

- addon/ng2/blueprints/ng2/files/package.json
- lib/cli/index.js
- package.json
- tests/acceptance/init.spec.js
Closes #315. Tested most of the commands and it works.
> chore(): update ember-cli to 2.4.2

- addon/ng2/blueprints/ng2/files/package.json
> update angular2 to beta version 13

- addon/ng2/blueprints/route/files/src/client/app/__name__/__name__-detail.component.ts
- addon/ng2/blueprints/route/files/src/client/app/__name__/__name__-root.component.ts
Probably not important for the experienced js developers but it's more readable for newcomers (at least for me!).
> fix: use explicit Number() instead of unary plus

- addon/ng2/blueprints/ng2/files/package.json
> fix(lint): fix tslint npm script arg

- tests/e2e/e2e_workflow.spec.js
@hansl @jkuri this should fix the broken test on appveyor.
> fix(tests): fix e2e workflow on appveyor

- lib/broccoli/broccoli-typescript.js
> fix: when a file has an error, recompile it next run.

- addon/ng2/tasks/doc.ts
Added the option to set `wait` to false to allow the promise to resolve
> bug: the command 'ng doc [query]' would not complete

- tests/e2e/e2e_workflow.spec.js
Late pr to address https://github.com/angular/angular-cli/pull/441#discussion_r59865435
> chore(e2e): simplify exec command

- addon/ng2/blueprints/ng2/files/karma.conf.js
> fix(tests): allow karma to load assets

- bin/ng
* removes unused `fs` variable
* removes what appears to be a duplicate `if` block
> refactor(bin): cleanup ng bin

- addon/ng2/blueprints/route/index.js
- prepend `+` only for lazy routes' import path directories
> fix(routes): remove `+` for non-lazy routes import

- addon/ng2/blueprints/route/index.js
> bug: route generation not handling the '--default' flag

- addon/ng2/blueprints/directive/index.js
- tests/acceptance/generate-directive.spec.js
> feat(generate): change directive default routing to flat

- addon/ng2/blueprints/component/files/__path__/__name__.component.spec.ts
- addon/ng2/blueprints/directive/files/__path__/__name__.directive.spec.ts
- addon/ng2/blueprints/pipe/files/__path__/__name__.pipe.spec.ts
- addon/ng2/blueprints/pipe/files/__path__/__name__.pipe.ts
- addon/ng2/blueprints/service/files/__path__/__name__.service.spec.ts
> chore: add consistent spacing in blueprints

- addon/ng2/blueprints/service/files/__path__/__name__.service.spec.ts
- addon/ng2/blueprints/service/files/__path__/__name__.service.ts
- addon/ng2/blueprints/service/files/__path__/index.ts
> chore: update class name for services to have Service suffix

- addon/ng2/blueprints/component/files/__path__/__name__.component.spec.ts
- addon/ng2/blueprints/component/files/__path__/__name__.component.ts
- addon/ng2/blueprints/directive/files/__path__/__name__.directive.spec.ts
- addon/ng2/blueprints/ng2/files/karma.conf.js
- addon/ng2/blueprints/ng2/files/package.json
- addon/ng2/blueprints/pipe/files/__path__/__name__.pipe.spec.ts
- addon/ng2/blueprints/route/index.js
- addon/ng2/blueprints/service/files/__path__/__name__.service.spec.ts
> chore: update to beta.16

- lib/broccoli/angular2-app.js
> fix(envs): update source dir

- addon/ng2/blueprints/component/files/__path__/__name__.component.ts
Clean up the inline template markup to not include a router-outlet tag
> chore: clean up component blueprint for routes

- package.json
This removes a spurious global dependency installed by `multidep`.
https://github.com/broccolijs/broccoli/commit/d00a07448624bd41c4a4065197d71dad73b68609
Fixes: https://github.com/angular/angular-cli/issues/536
> chore: update broccoli

- addon/ng2/blueprints/class/files/__path__/__name__.spec.ts
> bug: added missing semicolon in class spec file

- addon/ng2/blueprints/component/files/__path__/index.ts
> fix: add new line.

- addon/ng2/blueprints/component/files/__path__/__name__.component.spec.ts
- addon/ng2/blueprints/directive/files/__path__/__name__.directive.spec.ts
- addon/ng2/blueprints/pipe/files/__path__/__name__.pipe.spec.ts
> fix: remove extra whitespaces

- addon/ng2/blueprints/ng2/files/__path__/app/__name__.component.spec.ts
- addon/ng2/blueprints/ng2/files/__path__/app/__name__.component.ts
- addon/ng2/blueprints/ng2/files/__path__/main.ts
> bug: update app component name to have 'Component' suffix

- addon/ng2/blueprints/component/files/__path__/__name__.component.spec.ts
- addon/ng2/blueprints/component/files/__path__/__name__.component.ts
- addon/ng2/blueprints/component/files/__path__/index.ts
- addon/ng2/blueprints/directive/files/__path__/__name__.directive.spec.ts
- addon/ng2/blueprints/directive/files/__path__/__name__.directive.ts
- addon/ng2/blueprints/ng2/files/__path__/app/__name__.component.spec.ts
- addon/ng2/blueprints/ng2/files/__path__/app/__name__.component.ts
- addon/ng2/blueprints/ng2/files/__path__/main.ts
- addon/ng2/blueprints/pipe/files/__path__/__name__.pipe.spec.ts
- addon/ng2/blueprints/pipe/files/__path__/__name__.pipe.ts
- addon/ng2/blueprints/pipe/files/__path__/index.ts
- addon/ng2/blueprints/route/index.js
- addon/ng2/blueprints/service/files/__path__/__name__.service.spec.ts
- addon/ng2/blueprints/service/files/__path__/__name__.service.ts
> bug: ensure spaces appear inside braces of imports

- addon/ng2/commands/generate.ts
> bug: allow help to be displayed for the generate command

- addon/ng2/commands/get.ts
bug: fix get command message
fixes #602
> bug: fix get command message

- addon/ng2/blueprints/class/files/__path__/__name__.spec.ts
- addon/ng2/blueprints/component/files/__path__/__name__.component.spec.ts
- addon/ng2/blueprints/component/files/__path__/__name__.component.ts
- addon/ng2/blueprints/directive/files/__path__/__name__.directive.spec.ts
- addon/ng2/blueprints/directive/files/__path__/__name__.directive.ts
- addon/ng2/blueprints/ng2/files/__path__/app/__name__.component.spec.ts
- addon/ng2/blueprints/ng2/files/__path__/app/__name__.component.ts
- addon/ng2/blueprints/ng2/files/__path__/index.html
- addon/ng2/blueprints/ng2/files/__path__/main.ts
- addon/ng2/blueprints/ng2/files/__path__/system-config.ts
- addon/ng2/blueprints/ng2/files/__path__/tsconfig.json
- addon/ng2/blueprints/ng2/files/__path__/typings.d.ts
- addon/ng2/blueprints/ng2/files/angular-cli-build.js
- addon/ng2/blueprints/ng2/files/config/karma-test-shim.js
- addon/ng2/blueprints/ng2/files/config/karma.conf.js
- addon/ng2/blueprints/ng2/files/package.json
- addon/ng2/blueprints/pipe/files/__path__/__name__.pipe.spec.ts
- addon/ng2/blueprints/pipe/files/__path__/__name__.pipe.ts
- addon/ng2/blueprints/route/index.js
- addon/ng2/blueprints/service/files/__path__/__name__.service.spec.ts
- addon/ng2/blueprints/service/files/__path__/__name__.service.ts
- lib/broccoli/angular2-app.js
- lib/broccoli/broccoli-typescript.js
- package.json
- tests/acceptance/generate-route.spec.js
> chore: upgrade to new packaging

- addon/ng2/blueprints/ng2/files/__path__/index.html
> chore: move zone.js as the last loaded polyfill.

- addon/ng2/blueprints/ng2/files/__path__/main.ts
- addon/ng2/blueprints/ng2/files/__path__/system-config.ts
> chore: fix issues.

- addon/ng2/blueprints/route/index.js
> bug: provider not being added to the app component

- lib/broccoli/angular2-app.js
- lib/broccoli/broccoli-typescript.js
> fix: use options sourceDir, and fix null property access.

- README.md
I wasn't aware of the style guide. This should help others who missed it as well.
> Update README: Inline link to style guide re: lazy routes

- addon/ng2/blueprints/ng2/files/package.json
- package.json
> fix(package): temporarily remove angular2-service-worker

- addon/ng2/blueprints/ng2/files/__path__/index.html
> fix(index): fix live reload file path

- addon/ng2/blueprints/ng2/files/__path__/system-config.ts
> CLI does not lint for mobile fixed

- addon/ng2/blueprints/ng2/files/__path__/app/index.ts
> bug: have barrel export via 'export *' vs named exports

- addon/ng2/blueprints/ng2/files/package.json
Includes direct links to the styles in the style guide.
> chore(codelyzer): update to latest version

- tests/e2e/e2e_workflow.spec.js
This simplifies the link procedure in tests, see https://github.com/angular/angular-cli/pull/778.
> feat(test): use link-cli option on e2e

- README.md
Did a grammar check on README.md
> resolve syntactic pleonasm

- addon/ng2/blueprints/component/index.js
- addon/ng2/blueprints/ng2/files/angular-cli.json
- addon/ng2/blueprints/route/index.js
- lib/config/schema.json
- tests/acceptance/generate-route.spec.js
> feat: allow lazy route prefix to be configurable

- README.md
Changed server to serve in order to maintain consistency throughout.
> Consistency in commands

- README.md
> chore(readme): update unit test section

- addon/ng2/blueprints/ng2/files/angular-cli-build.js
Close #847 (see https://github.com/angular/angular-cli/issues/847#issuecomment-221285753)
> fix(mobile): add missing vendor file to build

- addon/ng2/blueprints/ng2/files/package.json
> chore(devDeps): update codelyzer

- addon/ng2/blueprints/ng2/files/package.json
> fix(mobile): lock dependency

- addon/ng2/commands/github-pages-deploy.ts
Fix #995 
Based on @JohannesHoppe comment in https://github.com/angular/angular-cli/issues/41#issuecomment-208456482
> fix(gh-deploy): fix deep links

- addon/ng2/blueprints/ng2/files/package.json
- addon/ng2/blueprints/ng2/index.js
> feat(style): automatically add deps if style is set on new projects

- addon/ng2/blueprints/class/files/__path__/__name__.spec.ts
- addon/ng2/blueprints/component/files/__path__/__name__.component.spec.ts
- addon/ng2/blueprints/directive/files/__path__/__name__.directive.spec.ts
- addon/ng2/blueprints/ng2/files/__path__/app/app.component.spec.ts
- addon/ng2/blueprints/pipe/files/__path__/__name__.pipe.spec.ts
- addon/ng2/blueprints/service/files/__path__/__name__.service.spec.ts
> chore(tests): simplify spec files for easier testing

- addon/ng2/blueprints/ng2/files/package.json
Only from the generated project.
> chore: remove all operators on dependencies.

- addon/ng2/blueprints/ng2/files/tslint.json
> fix(lint): add missing rulesDirectory

- addon/ng2/blueprints/ng2/files/package.json
> fix(deps): update router

- lib/cli/index.js
> fix(init): don't replace live reload script on diffs

- addon/ng2/blueprints/ng2/files/package.json
See https://github.com/angular/angular-cli/issues/958#issuecomment-227258879
> fix(mobile): partially fix dep problem

- addon/ng2/blueprints/ng2/files/__path__/system-config.ts
- addon/ng2/blueprints/ng2/files/package.json
Fix angular/form nor found, issue #1199
> added @angular/forms in system-config.ts  #1199

- .travis.yml
- addon/ng2/blueprints/ng2/files/package.json
- package.json
- tests/e2e/e2e_workflow.spec.js
> add mobile-specific e2e tests

- addon/ng2/models/webpack-build-mobile.ts
- addon/ng2/tasks/test.ts
See https://github.com/angular/angular-cli/issues/1356#issuecomment-233820191
> fix(test): add missing sourceDir

- addon/ng2/tasks/serve-webpack.ts
See https://github.com/angular/angular-cli/issues/1356#issuecomment-234127769
> Disable HMR

- addon/ng2/blueprints/component/files/__path__/__name__.component.ts
- addon/ng2/blueprints/ng2/files/__path__/app/app.component.ts
See https://github.com/angular/angular-cli/issues/1356
> chore(blueprints): remove module.id

- addon/ng2/blueprints/ng2/files/package.json
> bug(version): fix the version of angular-cli in package.json

- package.json
> fix: Updated webpack-karma which has proper peer deps settings

- addon/ng2/blueprints/ng2/files/__path__/test.ts
> fix: Remove `import 'rxjs/Rx'` from `test.ts`

- addon/ng2/utilities/dynamic-path-parser.js
- addon/ng2/utilities/route-utils.ts
- tests/acceptance/route-utils.spec.ts
'route-utils.ts' provides utility functions to be used in generating routes
'blueprints/routes/*' creates a 'routes.ts' file when the newroutes command is
run and 'route.ts' doesn't exit
> feat: add utility functions for route generation

- addon/ng2/blueprints/ng2/files/config/karma.conf.js
> fix(init): karma paths reflect sourceDir config

- addon/ng2/blueprints/directive/files/__path__/__name__.directive.spec.ts
- addon/ng2/blueprints/directive/files/__path__/__name__.directive.ts
- addon/ng2/blueprints/directive/index.js
- tests/acceptance/generate-directive.spec.js
> bug(directive): update directive class name to match style guide

- addon/ng2/blueprints/ng2/files/e2e/app.po.ts
- addon/ng2/blueprints/ng2/files/package.json
Close https://github.com/angular/angular-cli/issues/1676
> chore(test): update to protractor4

- addon/ng2/blueprints/directive/index.js
> bug(generate): align directive selector with the style guide

- addon/ng2/models/webpack-build-common.ts
- tests/e2e/e2e_workflow.spec.js
Kudos to @topherfangio for the suggestion!
> chore(init): use assets/.gitkeep

- package.json
> chore(webpack): update webpack deps to 2.1.0-beta.22

- lib/bootstrap-local.js
> fix(bootstrap): fix windows node_modules path

- README.md
change host name using ng server --host 0.0.0.0
> docs: update readme - add how to change hostname

- addon/ng2/commands/help.ts
- addon/ng2/index.js
> bug(help): hide ember-cli commands when running help

- addon/ng2/models/webpack-build-common.ts
add loader to support loading of gif images
Closes #1878
> fix: add loader for gif

- packages/angular-cli/models/webpack-build-common.ts
> fix(config): change css regex which causes error

- packages/angular-cli/blueprints/module/files/__path__/__name__.routing.ts
> Removed bad character in NgModule's routing file

- packages/angular-cli/models/webpack-build-common.ts
> chore(build): add otf font support

- packages/angular-cli/blueprints/ng2/files/__path__/index.html
I saw some extra spacing there, nothing fancy :)
> Trim trailing whitespace

- packages/angular-cli/tasks/build-webpack.ts
Fix source: https://github.com/webpack/webpack/issues/708
Fix #2014
> fix(build): fail ng build on error

- packages/angular-cli/commands/build.ts
- packages/angular-cli/commands/serve.ts
- packages/angular-cli/tasks/build-webpack.ts
- tests/e2e/tests/build/output-dir.ts
Fix https://github.com/angular/angular-cli/issues/2006
> fix(build): use config output path as default

- tests/e2e/tests/build/fail-build.ts
Add test for https://github.com/angular/angular-cli/pull/2360
> chore(test): add failing build test

- packages/angular-cli/blueprints/ng2/files/__path__/app/app-routing.module.ts
- packages/angular-cli/blueprints/ng2/files/__path__/app/app.module.ts
> bug(route): fix the class names for --routing in ng new

- packages/angular-cli/models/webpack-build-typescript.ts
- packages/webpack/src/compiler_host.ts
- packages/webpack/src/entry_resolver.ts
- packages/webpack/src/plugin.ts
- packages/webpack/src/resource_loader.ts
- tests/e2e/tests/build/aot.ts
- tests/e2e/tests/misc/lazy-module.ts
In addition, reading and using AST on main.ts to figure out the entry module, if not specified.
> feat(aot): creating files in a virtual fs.

- packages/angular-cli/blueprints/class/index.js
- packages/angular-cli/blueprints/directive/index.js
- packages/angular-cli/blueprints/pipe/index.js
- packages/angular-cli/blueprints/service/index.js
- tests/acceptance/generate-class.spec.js
- tests/acceptance/generate-directive.spec.js
- tests/acceptance/generate-pipe.spec.js
- tests/acceptance/generate-service.spec.js
> feature(blueprints): add spec/no-spec flags to all blueprints

- README.md
Fix https://github.com/angular/angular-cli/issues/2395
> chore(docs): elaborate node/npm prereqs

- packages/angular-cli/blueprints/component/files/__path__/__name__.component.spec.ts
Thanks to @laco0416 for pushing this issue and @wardbell for helping to come up with a concise and flexible structure.
> chore: update component spec file to use TestBed

- tests/acceptance/generate-class.spec.js
- tests/acceptance/generate-module.spec.js
- tests/e2e/tests/build/ts-paths.ts
- tests/e2e/utils/fs.ts
> chore: remove shared dir from new app blueprint

- package.json
- packages/angular-cli/package.json
> chore(build): update compression-webpack-plugin

- tests/e2e/assets/webpack/test-app/package.json
This should fix a current failure we have on Travis.
> chore(tests): update webpack app compiler-cli

- .editorconfig
- packages/angular-cli/blueprints/ng2/files/.editorconfig
> chore: fix editorconfig linefeeds on windows

- .appveyor.yml
See https://github.com/angular/webdriver-manager/issues/107 for context.
Should be reverted once issue is fixed.
> fix(appveyor): add workaround for webdriver bug

- .appveyor.yml
Reverts angular/angular-cli#2862
`webdriver-manager` seems to have fixed the problem in https://github.com/angular/webdriver-manager/pull/113.
> Revert "fix(appveyor): add workaround for webdriver bug"

- packages/angular-cli/blueprints/ng2/files/package.json
See https://github.com/angular/webdriver-manager/issues/121
> fix(e2e): fix travis e2e

- package.json
- packages/angular-cli/package.json
> chore(deps): remove unused typedoc

- package.json
- packages/angular-cli/package.json
- packages/webpack/package.json
> fix(angular-cli): add necessary dependencies.

- packages/angular-cli/blueprints/component/index.js
- packages/angular-cli/blueprints/directive/index.js
- packages/angular-cli/blueprints/pipe/index.js
> bug(generate): skip-import flag not being respected

- packages/angular-cli/blueprints/module/index.js
- packages/angular-cli/tasks/doc.ts
> chore(tasks): change apiFilter querystring to query

- .appveyor.yml
- .travis.yml
Remove OSX tests for Node 4, remove tests for Node 5. Other cleanup tasks.
> chore(travis): cleanup the tests on Travis.

- packages/angular-cli/models/webpack-build-common.ts
- packages/angular-cli/models/webpack-build-test.js
> fix(webpack): remove usage of __dirname from the config.

- packages/angular-cli/blueprints/ng2/files/__path__/typings.d.ts
> chore: remove unneeded file.

- packages/angular-cli/commands/help.ts
> Add support for `ng help <command>`

- packages/angular-cli/tasks/serve-webpack.ts
> Add support to open with ssl.

- package.json
- packages/angular-cli/commands/serve.ts
Followup to https://github.com/angular/angular-cli/pull/3465
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12995#issuecomment-265784722 for context.
> chore(deps): fix lodash import

- packages/angular-cli/models/webpack-build-common.ts
- packages/angular-cli/models/webpack-build-development.ts
- packages/angular-cli/models/webpack-build-production.ts
Mainly removes redundantly set config options.
> chore(webpack): minor config cleanup

- packages/@ngtools/webpack/src/plugin.ts
> fix(@ngtools/webpack): report errors during codegen

- packages/angular-cli/blueprints/component/index.js
- packages/angular-cli/blueprints/directive/index.js
- packages/angular-cli/blueprints/pipe/index.js
> feat(generate): Show files updated when generating

- packages/angular-cli/models/webpack-build-common.ts
> chore(typo): fix spelling of 'globalScripts`

- package.json
- packages/@ngtools/webpack/package.json
- packages/@ngtools/webpack/src/plugin.ts
- packages/angular-cli/package.json
- tests/e2e/assets/webpack/test-app-weird/package.json
- tests/e2e/assets/webpack/test-app/package.json
Need to use before-resolve until https://github.com/webpack/webpack/issues/3641 is fixed.
> chore(webpack): upgrade webpack to RC 3.

- packages/angular-cli/commands/generate.ts
> chore(generate): add abbreviation for generating interfaces

- packages/@angular-cli/ast-tools/src/change.ts
> bug(generate): prevent tracking of noop changes

- packages/@ngtools/webpack/src/loader.ts
- tests/e2e/tests/packages/webpack/test.ts
> feat(webpack): convert dashless resource urls

- scripts/publish/build.js
> chore(lint): fix lint error in build script

- packages/angular-cli/commands/init.run.ts
> feat(new): show name of created project in output

- package.json
- packages/@ngtools/webpack/package.json
- packages/angular-cli/models/webpack-build-common.ts
- packages/angular-cli/models/webpack-build-test.js
- packages/angular-cli/package.json
- tests/e2e/assets/webpack/test-app-weird/package.json
- tests/e2e/assets/webpack/test-app/package.json
Performance hint config now defaults to false as well.
> build(deps): update to webpack 2.2.0 final

- packages/angular-cli/blueprints/ng2/files/__path__/test.ts
This should solve #3370 
Let me know if that was the intention
This small PR were made with love by Itay Radotzky and Elad Bezalel #goodnessSquad :)
> add a comment in the beginning of test.ts

- packages/angular-cli/blueprints/ng2/files/gitignore
Reverts angular/angular-cli#3734. Asterisk is necessary
> Revert "fix(gitignore):the item"

- package.json
- packages/angular-cli/models/webpack-configs/styles.ts
- packages/angular-cli/package.json
> fix(build): ExtractTextWebpack 2.0.0-rc.1 and remove unsupported prop

- scripts/publish/build.js
> build: support paths with spaces on Windows

- packages/@ngtools/webpack/src/loader.ts
> fix(webpack): only diagnose each resource once

- packages/@angular/cli/commands/build.ts
> fix(build): don't override base-href if not directly specified

- tests/e2e/tests/build/rebuild-css-change.ts
- tests/e2e/tests/build/rebuild-deps-type-check.ts
- tests/e2e/tests/build/rebuild.ts
Apparently travis is still flaky with 5 seconds.
> refactor: more time given to rebuilds

- tests/e2e/setup/500-create-project.ts
- tests/e2e/utils/project.ts
When we moved to @angular/cli some testing logic wasnt updated properly.
> test: fix nightly travis tests

- packages/@angular/cli/blueprints/ng2/files/package.json
> fix(@angular/cli): update dependency to remove install warning

- .travis.yml
Followup from https://github.com/angular/angular-cli/pull/4557
> ci: split ng4 e2e into two

- packages/@angular/cli/blueprints/ng2/files/tslint.json
> fix(@angular/cli): use correct tslint rule args

- docs/documentation/stories/global-scripts.md
copy & paster error from global styles
> Correct headline

- packages/@angular/cli/lib/config/schema.json
> refactor(@angular/cli): remove version from schema.json

- packages/@angular/cli/ember-cli/lib/cli/cli.js
> fix(@angular/cli): show help on just ng command

- packages/@angular/cli/blueprints/component/index.ts
- packages/@angular/cli/blueprints/directive/index.ts
- packages/@angular/cli/blueprints/pipe/index.ts
> bug(@angular/cli): Show module file update during dry run

- package.json
- packages/@angular/cli/tsconfig.json
- packages/@ngtools/json-schema/tsconfig.json
- packages/@ngtools/logger/src/console-logger-stack.spec.ts
- packages/@ngtools/logger/src/console-logger-stack.ts
- packages/@ngtools/logger/tsconfig.json
- packages/@ngtools/webpack/src/lazy_routes.ts
- packages/@ngtools/webpack/tsconfig.json
- tsconfig.json
And use extends for its tsconfigs. Nothing of this changes whats published in npm.
> refactor: use typescript 2.1 for the CLI project itself.

- CHANGELOG.md
- Sets the actionable steps in separate lines
- Adds note about karma and CLI config file
- Adds note about action for `ng update`
> feat(docs): expand beta 32 breaking changes section

- package.json
> deps: update to typescript 2.2

- packages/@angular/cli/blueprints/class/index.ts
- packages/@angular/cli/blueprints/component/index.ts
- packages/@angular/cli/blueprints/directive/index.ts
- packages/@angular/cli/blueprints/guard/index.ts
- packages/@angular/cli/blueprints/interface/index.ts
- packages/@angular/cli/blueprints/module/index.ts
- packages/@angular/cli/blueprints/pipe/index.ts
- packages/@angular/cli/blueprints/service/index.ts
- packages/@angular/cli/commands/generate.ts
We dont have ngConfig on projects anymore.
> fix(@angular/cli): apps fixes

- tests/e2e/utils/project.ts
There was a missing one for routing.
> ci: when testing with ng4 add ng4 to all ng new calls

- packages/@angular/cli/bin/ng
- packages/@angular/cli/commands/new.ts
- packages/@angular/cli/commands/version.ts
- packages/@angular/cli/tasks/eject.ts
- tests/e2e/setup/010-build.ts
- tests/e2e/utils/assets.ts
> fix(@angular/cli): fix access to sections of package.json that dont exist

- packages/@angular/cli/commands/xi18n.ts
- packages/@angular/cli/models/webpack-configs/xi18n.ts
- packages/@angular/cli/models/webpack-xi18n-config.ts
- packages/@angular/cli/tasks/extract-i18n.ts
- packages/@ngtools/webpack/src/extract_i18n_plugin.ts
- tests/e2e/tests/i18n/extract-locale.ts
- tests/e2e/tests/i18n/extract-outfile.ts
Fixes #5145
This only works with Angular 4, I think I got the tests right, but you might want to double check because it was not obvious :)
> feat(@angular/cli): add new xi18n parameters --locale and --outFile

- packages/@angular/cli/models/webpack-configs/production.ts
- tests/e2e/tests/build/service-worker.ts
> Two service-worker fixes

- packages/@angular/cli/blueprints/ng/files/__path__/tsconfig.spec.json
- packages/@angular/cli/blueprints/ng/files/e2e/tsconfig.e2e.json
> test(@angular/cli): output test compilation to es5

- packages/@angular/cli/blueprints/component/index.ts
- packages/@angular/cli/blueprints/directive/index.ts
- packages/@angular/cli/blueprints/pipe/index.ts
- packages/@angular/cli/ember-cli/lib/ui/index.js
- packages/@angular/cli/utilities/find-parent-module.ts
- tests/e2e/tests/generate/component/component-in-existing-module-dir.ts
- tests/e2e/tests/generate/directive/directive-in-existing-module-dir.ts
- tests/e2e/tests/generate/pipe/pipe-in-existing-module-dir.ts
> fix(@angular/cli): fix issue with console prompt bailing early

- docs/documentation/home.md
> docs(@angular/cli): fixing broken ng doc link in wiki

- packages/@angular/cli/blueprints/ng/files/README.md
- packages/@angular/cli/blueprints/ng/files/gitignore
Spacing is not consistent in some blueprints. This PR rectifies this.
> Blueprint consistency

- packages/@angular/cli/models/webpack-configs/styles.ts
- tests/e2e/tests/build/css-urls.ts
> fix(@angular/cli): don't break deployUrl with scheme

- packages/@angular/cli/commands/generate.ts
Fixes: https://github.com/angular/angular-cli/issues/5335
> fix(@angular/cli): Fixing generate help command fix

- packages/@angular/cli/blueprints/class/index.ts
- packages/@angular/cli/blueprints/component/index.ts
- packages/@angular/cli/blueprints/directive/index.ts
- packages/@angular/cli/blueprints/enum/index.ts
- packages/@angular/cli/blueprints/guard/index.ts
- packages/@angular/cli/blueprints/interface/index.ts
- packages/@angular/cli/blueprints/module/index.ts
- packages/@angular/cli/blueprints/pipe/index.ts
- packages/@angular/cli/blueprints/service/index.ts
- packages/@angular/cli/ember-cli/lib/utilities/printable-properties.js
Fixes: https://github.com/angular/angular-cli/issues/5289
> fix(@angular/cli): Fixing aliases for blueprint help

- packages/@angular/cli/lib/config/schema.json
Fixes: https://github.com/angular/angular-cli/issues/5345
> fix(@angular/cli): Fixing setting enums

- .github/ISSUE_TEMPLATE.md
Issues currently get a tracking checklist by default.
> docs: don't add tracking checklist to new issues.

- packages/@angular/cli/bin/ng
> fix(@angular/cli): update warning message when @angular/cli not found in devDependencies

- packages/@angular/cli/tasks/init.ts
Fixes: https://github.com/angular/angular-cli/issues/3732
> fix(@angular/cli): fixing empty prefix issue when creating new app

- packages/@angular/cli/utilities/app-utils.ts
Fixes: https://github.com/angular/angular-cli/issues/5325
> fix(@angular/cli): fix default app index

- .github/SAVED_REPLIES.md
- CONTRIBUTING.md
- README.md
Based on the ones present in angular/angular:
- https://github.com/angular/angular/blob/master/CONTRIBUTING.md
- https://github.com/angular/angular/blob/master/docs/SAVED_REPLIES.md
We should all use these saved replies while triaging to make the process easier, more consistent and more informative for users.
/cc @IgorMinar
> Update CONTRIBUTING, add SAVED_REPLIES

- packages/@angular/cli/tasks/e2e.ts
- tests/e2e/tests/test/e2e-baseurl.ts
Fixes: https://github.com/angular/angular-cli/issues/5749
> feat(@angular/cli): fix baseUrl when running e2e with no-serve

- packages/@angular/cli/blueprints/ng/files/package.json
> feat(@angular/cli): add language service in devDependencies section

- packages/@angular/cli/blueprints/ng/files/package.json
Reverts angular/angular-cli#5899
> Revert "feat(@angular/cli): add language service in devDependencies section"

- packages/@angular/cli/blueprints/ng/files/__path__/test.ts
- packages/@angular/cli/blueprints/ng/files/package.json
Also fixes the `test.ts` file warnings.
> feat(@angular/cli): bump to tslint 5 & codelyzer 3

- packages/@ngtools/webpack/src/compiler_host.ts
Fix for path resolve in windows as listed here #5329
> fix(@ngtools/webpack): resolve path windows

- packages/@angular/cli/tasks/npm-install.ts
Fixes: https://github.com/angular/angular-cli/issues/5650
> fix(@angular/cli): use quiet flag only in case of npm

- packages/@angular/cli/models/webpack-configs/styles.ts
This adjusts the stylesheet minification settings (via `cssnano`) to remove several edge cases wherein invalid css output could occur.
> fix(@angular/cli): use safer stylesheet minification settings

- packages/@angular/cli/blueprints/ng/files/package.json
Supersedes https://github.com/angular/angular-cli/pull/5240. The latest version supports multiple browser outputs, threshold reporting and some fixes for windows users 😄
> feat(@angular/cli): upgrade the blueprint karma-coverage-istanbul-reporter version

- packages/@angular/cli/models/webpack-configs/styles.ts
This provides a small reduction in the global stylesheet pipeline for typical dev builds.
> refactor(@angular/cli): only setup CSS extraction if actually extracting

- packages/@angular/cli/blueprints/ng/files/tslint.json
Fixes https://github.com/angular/angular-cli/issues/5755
> fix(@angular/cli): removes redundant rules from tslint.json

- packages/@angular/cli/commands/completion.ts
- packages/@angular/cli/commands/destroy.ts
- packages/@angular/cli/commands/easter-egg.ts
- packages/@angular/cli/commands/help.ts
- packages/@angular/cli/commands/init.ts
- packages/@angular/cli/commands/new.ts
- packages/@angular/cli/ember-cli/lib/utilities/print-command.js
- tests/e2e/tests/commands/help/help-hidden.ts
> Use hidden flag for ignored/internal commands & options

- docs/documentation/test.md
- packages/@angular/cli/commands/test.ts
Corrects many nonsense things.
> Various fix for "ng test"

- README.md
fix(@angular/cli): Update README.md project generation text.
angular-cli/packages/@angular/cli/utilities/validate-project-name.ts looks for hypen(-) rather than the listed underscore(_).
> fix(@angular/cli): Update README.md project generation text.

- package.json
- packages/@angular/cli/package.json
> fix(@angular/cli): properly support CSS url()'s with whitespace

- packages/@angular/cli/blueprints/ng/files/__path__/polyfills.ts
It doesn't work if we just import intl.
Only put Intl here is a bit misleading. At least it got me :(
> fix: import at least one locale-data with intl

- packages/@angular/cli/blueprints/ng/files/__path__/app/app.component.html
Noticed a small typo, on the really cool new landing page. xD
> fix(@angular/cli): small typo on generated app.component.html

- packages/@angular/cli/blueprints/ng/files/__path__/index.html
Fixes: https://github.com/angular/angular-cli/issues/6260
> fix(@angular/cli): adds language to index.html for accessibility

- docs/documentation/home.md
It was wrong the name of the folder.
> docs(@angular/cli): fix sample home.md

- packages/@angular/cli/commands/generate.ts
- packages/@angular/cli/ember-cli/lib/models/blueprint.js
- tests/e2e/tests/generate/generate-name-check.ts
Fixes: https://github.com/angular/angular-cli/issues/6413
> fix(@angular/cli): fix package name fetching from package.json

- packages/@angular/cli/tasks/e2e.ts
- tests/e2e/tests/test/e2e-baseurl.ts
Fixes: https://github.com/angular/angular-cli/issues/5602
> fix(@angular/cli): allow e2e tests to run if no-serve and port 

- packages/@angular/cli/commands/generate.ts
- tests/e2e/tests/generate/generate-name-error.ts
> fix(@angular/cli): fix leading digit in file names from generate command

- packages/@angular/cli/commands/set.ts
- packages/@ngtools/json-schema/src/schema-class-factory.ts
- packages/@ngtools/json-schema/src/schema-tree.spec.ts
- packages/@ngtools/json-schema/src/schema-tree.ts
- packages/@ngtools/json-schema/tests/value2-1.json
- tests/e2e/tests/commands/set/set-enum-check.ts
Fixes: https://github.com/angular/angular-cli/issues/5874
> fix(@angular/cli): only values in enum should be allowed to update

- docs/documentation/build.md
Address concerns in #4366, #6375.
> docs(@angular/cli): document output dir deletion

- packages/@angular/cli/models/webpack-configs/browser.ts
- packages/@angular/cli/tasks/eject.ts
- tests/e2e/tests/build/vendor-chunk-symlink-node-module.ts
- tests/e2e/utils/fs.ts
> fix(@angular/cli): allow node_modules to be linked somewhere else.

- .travis.yml
- scripts/git-builds.js
Added scripts to push to build repos to github
> feat(@angular/cli): adding git builds script

- packages/@angular/cli/models/webpack-configs/typescript.ts
Fixes: https://github.com/angular/angular-cli/issues/5407
> fix(@angular/cli): fix env path

- packages/@angular/cli/blueprints/ng/files/__path__/polyfills.ts
- remove duplicate
- update browser support
> docs(@angular/cli): correct web animations polyfill description

- packages/@angular/cli/models/webpack-configs/common.ts
> feat(@angular/cli): support loading webp images

- packages/@ngtools/webpack/src/loader.ts
- tests/e2e/tests/build/styles/empty-style-urls.ts
Fixes: https://github.com/angular/angular-cli/issues/6602
> fix(@angular/cli): fix empty style urls

- tests/e2e/tests/build/rebuild.ts
Also includes some minor cleanup.
> test: attempt to reduce flakiness of rebuild e2e test

- docs/documentation/new.md
- packages/@angular/cli/blueprints/ng/files/__path__/index.html
- packages/@angular/cli/blueprints/ng/files/angular-cli.json
- packages/@angular/cli/blueprints/ng/files/package.json
- packages/@angular/cli/blueprints/ng/index.ts
- packages/@angular/cli/commands/init.ts
- packages/@angular/cli/commands/new.ts
- packages/@angular/cli/tasks/init.ts
- tests/e2e/tests/commands/new/new-minimal.ts
This feature allows users to specify `--barebones` (`-b`) to create a no-frills app.
> feat(@angular/cli): add barebones option to ng new

- packages/@angular/cli/models/config/config.ts
Also removes redundant exists check.
> fix(@angular/cli): provide file path with config parse errors

- tests/e2e/tests/build/rebuild-deps-type-check.ts
- tests/e2e/utils/process.ts
This test seems to not have been doing what it was supposed, code that wasn't supposed to have errors had one, and it was checking stdout instead of stderr for errors.
> test: fix rebuild deps test 

- packages/@angular/cli/tasks/eject.ts
> fix(@angular/cli): glob copy plugin config

- packages/@angular/cli/blueprints/ng/files/__path__/app/app.component.html
I recommend we improve the wording a little bit in this message at some point.
> fix(@angular/cli): Improve comment in sample html

- docs/documentation/test.md
- packages/@angular/cli/commands/test.ts
- packages/@angular/cli/tasks/test.ts
- tests/e2e/tests/test/test-environment.ts
> feat(@angular/cli): add flag to specify environment for ng test command

- packages/@angular/cli/blueprints/ng/files/__path__/tsconfig.app.json
- packages/@angular/cli/blueprints/ng/files/__path__/tsconfig.spec.json
- packages/@angular/cli/blueprints/ng/files/e2e/tsconfig.e2e.json
- packages/@angular/cli/blueprints/ng/files/tsconfig.json
Fix https://github.com/angular/angular-cli/issues/5875
> fix(@angular/cli): don't set baseUrl in editor tsconfig

- packages/@ngtools/webpack/src/loader.ts
Currently, having multiple @ngtools/webpack installed yields a cryptic error in typescript:
```
ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
```
This happens because a plugin is found, but it isn't an instance of the right class. This makes the loader assume it's being ran without a plugin (just transpiling TS). Then it tries to load a missing tsconfig and the error above is shown.
This PR introduced better errors for both the wrong plugin instance and missing tsconfig.
```
ERROR in ./src/main.ts
Module build failed: Error: AotPlugin was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed.You can check this with `npm ls @ngtools/webpack`, and then remove the extra …
```
> fix(@ngtools/webpack): better AoTPlugin instance error

- docs/documentation/stories.md
> docs: add multiple apps story to story list

- packages/@angular/cli/models/webpack-configs/browser.ts
- packages/@angular/cli/models/webpack-configs/common.ts
Fix #6737 
Fix #6785 
Fix #6640
> fix(@angular/cli): use inline sourcemaps in test

- .circleci/config.yml
- tests/e2e/setup/100-npm-link.ts
- tests/e2e/setup/500-create-project.ts
- tests/e2e/tests/build/poll.ts
Followup from https://github.com/angular/angular-cli/pull/6853.
> ci: add Circle CI

- .github/CODEOWNERS
Just a simple config to get started.
> ci: add github codeowners

- .github/SAVED_REPLIES.md
Update the duplicate reply to make use of https://github.com/blog/2398-better-manage-issues-and-pull-requests-with-keyword-updates.
> docs: update duplicate reply

- docs/documentation/stories.md
- docs/documentation/stories/universal-rendering.md
Add doc file for https://github.com/angular/angular-cli/wiki/stories-universal-rendering
/cc @alxhub
> docs: add universal rendering

- docs/documentation/stories/universal-rendering.md
> docs: Fixed typo in universal story

- packages/@angular/cli/tasks/build.ts
- packages/@angular/cli/tasks/serve.ts
- packages/@angular/cli/utilities/stats.ts
Errors and warnings neet to be printed separately.
Followup to #6989
Fix #7213
> Fix serve warnings, red errors

- docs/documentation/stories/universal-rendering.md
> docs: fix universal dep save flag

- packages/@angular/cli/commands/build.ts
- tests/e2e/tests/build/build-optimizer.ts
> fix(@angular/cli): remove -bo alias for --build-optimizer

- package-lock.json
- package.json
- packages/@angular/cli/package.json
> fix(@angular/cli): update build-optimizer

- docs/documentation/stories/include-angular-material.md
> docs: fix material install

- docs/documentation/build.md
> docs: add NamedChunks to dev/prod defaults table

- packages/@angular/cli/lib/base-href-webpack/base-href-webpack-plugin.spec.ts
- packages/@angular/cli/lib/base-href-webpack/base-href-webpack-plugin.ts
> fix(@angular/cli): baseHref to accept empty string via cli

- packages/@angular/cli/models/webpack-configs/production.ts
Fixes #3544
Fixes #6155 
Fixes #7243
> fix(@angular/cli): prevent unicode character compression

- docs/documentation/stories/include-angular-flex.md
*  added image snapshots, 
*  fixed links,
*  improved sample
> docs: update flex-layout story

- docs/documentation/test.md
In test command documentation, update config options description.
> docs: update test config command

- packages/@angular/cli/tasks/init.ts
> fix(@angular/cli): ensure new projects have a CLI package version

- packages/@angular/cli/tasks/init.ts
> fix(@angular/cli): only install packages once for a new project

- packages/@ngtools/logger/src/console-logger-stack.ts
- packages/@ngtools/logger/src/logger.spec.ts
- packages/@ngtools/logger/src/logger.ts
- packages/@ngtools/webpack/src/compiler_host.ts
- packages/@ngtools/webpack/src/entry_resolver.ts
- packages/@ngtools/webpack/src/extract_i18n_plugin.ts
- packages/@ngtools/webpack/src/lazy_routes.ts
- packages/@ngtools/webpack/src/loader.ts
- packages/@ngtools/webpack/src/paths-plugin.ts
- packages/@ngtools/webpack/src/plugin.ts
- packages/@ngtools/webpack/src/refactor.ts
Initial support for `@ngtools/logger` and `@ngtools/webpack`
> Partial support for strict null checks

- docs/documentation/build.md
Followup to https://github.com/angular/angular-cli/pull/7231
> docs: update build-optimizer command

- packages/@angular/cli/tasks/init.ts
- tests/e2e/tests/commands/new/new-style.ts
> fix(@angular/cli): New project now respect default styleExt

- package-lock.json
- package.json
- packages/@angular/cli/package.json
> fix(@angular/cli): Unpin version of @angular-devkit/schematics

- package-lock.json
- package.json
- packages/@angular/cli/package.json
- tests/e2e/tests/misc/public-host.ts
We dont want this in 1.3.x, so marking as a feature.
> feat(@angular/cli): update webpack to latest version

- package-lock.json
- package.json
- packages/@angular/cli/package.json
We only unlock patches, so this can be released with a patch.
> fix(@angular/cli): unlock build optimizer version

- packages/@angular/cli/plugins/insert-concat-assets-webpack-plugin.ts
- tests/e2e/tests/misc/deploy-url.ts
> fix(@angular/cli): take publicPath into account when building entry map

- packages/@angular/cli/commands/generate.ts
- tests/e2e/tests/generate/component/component-prefix.ts
> fix(@angular/cli): Make prefix work when using aliases

- README.md
It was saying angular/cli is currently at version 1.0
> Removed false information about current version

- packages/@angular/cli/commands/generate.ts
- tests/e2e/tests/generate/component/component-module-2.ts
> App root schematics

- packages/@angular/cli/tasks/lint.ts
This allows type information requiring rules to work as they do with the current version of tslint.  The use of the project and type-check options was adjusted with tslint 5.4+.  As per tslint's release notes:
> The --type-check CLI option now only enables checking for compiler errors before linting. It is no longer required to enable rules that use the type checker -- only need to supply --project now.
Unfortunately, a defect within tslint versions before 5.5 ([release notes for details](https://github.com/palantir/tslint/releases/tag/5.5.0)) prevents the `--fix` option to work properly with the `--project` option.  Therefore, existing behavior of the `--type-check` option is maintained for projects using these versions.
Note: The CLI's `--type-check` option never reported any errors and …
> feat(@angular/cli): always use lint project option if present

- packages/@ngtools/webpack/src/angular_compiler_plugin.ts
- packages/@ngtools/webpack/src/loader.ts
- packages/@ngtools/webpack/src/plugin.ts
> Improve TS compiler option handling

- packages/@angular/cli/tasks/eject.ts
> fix(@angular/cli): use relative paths within ejected config

- package-lock.json
- package.json
- packages/@angular/cli/commands/new.ts
- packages/@angular/cli/package.json
> fix(@angular/cli): Refactor skip git flag into schematics

- package-lock.json
- package.json
- packages/@angular/cli/package.json
This release addresses a Mime vulnerability: https://github.com/webpack-contrib/url-loader/releases/tag/v0.6.0
> fix(@angular/cli): update url-loader to 6.0

- README.md
Updated readme for updating Angular CLI for npm version > 5
Fixes #7894
> docs(@angular/cli): Updated instructions for cli update for npm v > 5

- package-lock.json
- package.json
- packages/@angular/cli/package.json
- This release picks up a ReDoS security patch in minimatch: https://nodesecurity.io/advisories/minimatch_regular-expression-denial-of-service
> fix(@angular/cli): update copy-webpack-plugin to 4.1.1

- packages/@angular/cli/commands/serve.ts
- tests/e2e/tests/build/eval-sourcemap.ts
Also add test to ensure it doesn't break.
Followup to #7919
> fix(@angular/cli): fix eval-sourcemap when sourcemap is undefined

- packages/@angular/cli/commands/version.ts
Group all Angular packages that have the same version as @angular/core, and
also show information for schematics, devkit and others that might not be
in the package.json but still installed. Those versions are important.
> feat(@angular/cli): show more version information

- docs/documentation/stories/universal-rendering.md
> fix(universal): add ts-loader install

- package-lock.json
- package.json
- packages/@angular/cli/package.json
This contains an important performance fix for AOT (https://github.com/webpack/webpack/pull/5778).
> fix(@angular/cli): update webpack to 3.7.1

- docs/documentation/stories/proxy.md
> docs(@angular/cli): update proxy config story

- packages/@angular/cli/models/webpack-configs/typescript.ts
- packages/@ngtools/webpack/README.md
- packages/@ngtools/webpack/src/angular_compiler_plugin.ts
- packages/@ngtools/webpack/src/compiler_host.ts
- packages/@ngtools/webpack/src/loader.ts
- packages/@ngtools/webpack/src/resource_loader.ts
- packages/@ngtools/webpack/src/transformers/replace_resources.ts
- packages/@ngtools/webpack/src/virtual_file_system_decorator.ts
- packages/@ngtools/webpack/src/webpack.ts
- tests/e2e/tests/build/rebuild-ngfactories.ts
This should improve AOT compilation times.
> fix(@ngtools/webpack): rebuild only changed ngfactories

- packages/@ngtools/webpack/src/angular_compiler_plugin.ts
- packages/@ngtools/webpack/src/ngtools_api.ts
- packages/@ngtools/webpack/src/type_checker.ts
Followup to https://github.com/angular/angular/pull/19748, https://github.com/angular/angular/pull/19804
Fix #8101
> fix(@ngtools/webpack): update formatDiagnostics call

- packages/@angular/cli/package.json
> fix(@angular/cli): update real package dep

- docs/documentation/stories/universal-rendering.md
If you run that webpack config currently it'll throw an exception
fixes #8183
> docs(@angular/cli): fix universal example webpack config

- tests/e2e/tests/build/rebuild-error.ts
The expectations for type checker errors were in a race condition with build messages (e.g. successRe  happening before the error messages).
> test: fix flake on rebuild-error

- docs/documentation/stories/universal-rendering.md
> docs(universal-stories): add ModuleMapLoaderModule import and notes

- docs/documentation/angular-cli.md
- docs/documentation/e2e.md
- docs/documentation/stories/universal-rendering.md
The fix includes changes from #6768 that looks inactive. I would use original commit out of respect for initial author, but he did not sign CLA, so as I understand, his changes cannot be merged even as part of another PR.
> docs: fix typos

- packages/@angular/cli/tasks/npm-install.ts
Displays the package installation progress for the `ng new` command by piping the output from the child process to the parent.
I've tested this on OSX and Windows for `npm`, `yarn` and `cnpm` and it works for all combinations.
Resolves #5960
> feat(@angular/cli): Show package installation progress

- packages/@angular/cli/commands/generate.ts
- packages/@angular/cli/utilities/dynamic-path-parser.ts
> fix(@angular/cli): fix generate app root in windows

- packages/@angular/cli/tasks/lint.ts
This synchronizes the return code behavior of `ng lint` and `tslint` wherein lint errors cause a non-zero return value and warnings do not affect the outcome.
> fix(@angular/cli): sync lint error code behavior with TSLint

- packages/@angular/cli/models/webpack-configs/common.ts
- tests/e2e/tests/build/assets.ts
> fix(@angular/cli): allow build output in outDir outside of project

- packages/@angular/cli/bin/ng
Fixed indentation and fixed some tslint console errors
> remove eslint errors for console

- packages/@angular/cli/tasks/serve.ts
> fix(@angular/cli): honor project's hmr warning option

- packages/@angular/cli/commands/generate.ts
- tests/e2e/tests/build/build-app-shell-with-schematic.ts
> fix(@angular/cli): Allow schematics without a name option.

- packages/@angular/cli/models/webpack-configs/styles.ts
- tests/e2e/tests/build/css-urls.ts
> fix(@angular/cli): account for root relative URLs in CSS assets

- packages/@angular/cli/lib/config/schema.json
- packages/@angular/cli/tasks/serve.ts
> feat(@angular/cli): can disable unsupported serve path warning

- docs/documentation/stories/continuous-integration.md
> docs: add addons to travis yml in CI story

- packages/@ngtools/webpack/src/angular_compiler_plugin.ts
- tests/e2e/tests/build/build-errors.ts
Related to https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325
> fix(@ngtools/webpack): improve missing TS file error message

- package-lock.json
- package.json
- packages/@angular/cli/package.json
- tests/e2e/tests/third-party/bootstrap.ts
Fix #9020, related to https://travis-ci.org/angular/angular-cli/jobs/322676874#L3792
> fix(@angular/cli): update autoprefixer

- package-lock.json
- package.json
- packages/@angular/cli/package.json
> fix(@angular/cli): update to istanbul-instrumenter-loader 3.0.0

- packages/@angular/cli/tasks/eject.ts
> fix(@angular/cli): license plugin config

- packages/@angular/cli/plugins/scripts-webpack-plugin.ts
> fix(@angular/cli): support no semicolon scripts

- packages/@angular/cli/models/webpack-configs/common.ts
> fix(@angular/cli): copy assets with special character paths

- packages/@angular/cli/tasks/serve.ts
> feat(@angular/cli): load deployUrl and baseHref from app config for ng serve

- .appveyor.yml
This will help to catch windows path related issues
> test: add additional tests on Windows

- package.json
- packages/@angular/cli/commands/generate.ts
- packages/@angular/cli/package.json
- packages/@angular/cli/tasks/schematic-run.ts
- packages/@angular/cli/utilities/schematics.ts
Followup to https://github.com/angular/devkit/pull/334
> feat(@angular/cli): use devkit core formats for schematics

- package-lock.json
- package.json
- packages/@angular/cli/package.json
- scripts/test-licenses.js
@hansl One of the packages has a malformed SPDX identifier (`true-case-path@1.0.2`).  License file is Apache-2.0.
Fixes #9164
> fix(@angular/cli): ensure webpack 3 sass-loader support

- package-lock.json
- package.json
- packages/@angular/cli/package.json
[Latest version](https://github.com/webpack/webpack-dev-server/releases/tag/v2.11.0) of `webpack-dev-server` transpiles the client code. 
Closes #8596
> fix(@angular/cli): remove ES2015 live-reload requirement

- packages/@angular/cli/models/webpack-config.ts
> fix(@angular/cli): only force CommonJS if module kind is ES2015

- packages/@angular/cli/tasks/eject.ts
- tests/e2e/utils/process.ts
And add missing dependenices when ejecting.
Fixes #9342.
> fix(@angular/cli): delete node_modules on eject e2e

- README.md
`ng g component ../newer-cmp` was throwing error
so, use `ng g component ./newer-cmp` to generate component
> docs(@angular/cli): update command to generate component

- packages/@angular/cli/plugins/scripts-webpack-plugin.ts
Maintains backwards compatibility with Webpack 3.
> feat(@angular/cli): add scripts plugin webpack 4 support

- packages/@ngtools/webpack/src/angular_compiler_plugin.ts
Required for Webpack 4 support.
> refactor(@ngtools/webpack): simplify vfs webpack integration

- packages/@angular/cli/models/webpack-configs/styles.ts
> fix(@angular/cli): favor CSS import local files over modules

- packages/@angular/cli/plugins/scripts-webpack-plugin.ts
Backwards compatible with Webpack 3.
> feat(@angular/cli): support webpack 4 hooks for scripts plugin

- package-lock.json
- package.json
- packages/@angular/cli/package.json
See https://github.com/angular/angular-cli/issues/9427#issuecomment-361383935 for context.
Supersedes #9429
> fix(@angular/cli): update uglifyjs-webpack-plugin to 1.1.8

- packages/@angular/cli/plugins/postcss-cli-resources.ts
> fix(@angular/cli): adjust postcss url promise handling

- packages/@angular/cli/models/webpack-configs/styles.ts
- tests/e2e/tests/build/styles/material-import.ts
> fix(@angular/cli): correct CSS import fallback logic

- packages/@ngtools/webpack/src/angular_compiler_plugin.ts
The forked type checker was not being disposed of when watch mode was being closed without the process exiting.
> fix(@ngtools/webpack): kill type checker on watch close

- packages/@angular/cli/tasks/schematic-get-options.ts
> fix(@angular/cli): allow usage of hidden command options

- packages/@angular/cli/plugins/postcss-cli-resources.ts
> fix(@angular/cli): prevent corruption of binary CSS resources

- packages/@angular/cli/lib/base-href-webpack/base-href-webpack-plugin.ts
- tests/e2e/tests/build/base-href.ts
> fix(@angular/cli): support empty index base href attribute

- packages/@angular/cli/commands/set.ts
plus some minor formatting fixes
Fixes #8081
> fix(@angular/cli): allow set prefix with no tslint config

- packages/@angular/cli/commands/generate.ts
> fix(@angular/cli): Fix help for generate command.

- packages/@angular/cli/plugins/postcss-cli-resources.ts
- tests/e2e/tests/build/styles/inline-urls.ts
> fix(@angular/cli): improve processing multi-line url() CSS rules

- packages/@ngtools/webpack/src/paths-plugin.ts
- tests/e2e/tests/misc/module-resolution.ts
> fix(@ngtools/webpack): directly use single path mappings

- packages/@angular/cli/commands/xi18n.ts
* Added support for xliff2
* Set xliff2 as default
> Support xliff2

- packages/@angular/cli/plugins/postcss-cli-resources.ts
- tests/e2e/tests/third-party/material-icons.ts
> fix(@angular/cli): prevent greedy CSS url function capture

- README.md
> docs: update readme cache instructions

- packages/@angular/cli/models/webpack-configs/production.ts
> fix(@angular/cli): workaround ES2015 minifier inlining defect

- docs/documentation/generate.md
- packages/@angular/cli/commands/generate.ts
- packages/@angular/cli/tasks/schematic-run.ts
BREAKING CHANGE: Removed collection and lint-fix options
> feat(@angular/cli): Clean up generate options

- packages/@ngtools/webpack/src/angular_compiler_plugin.ts
APF6 does not have fESM anymore, so we need to change our logic to include
any files in core (technically there is a faster way to do this, but for now
and for testing purposes this can go it as is).
> feat(@ngtools/webpack): support non-FESM angular core

- packages/@angular/cli/commands/generate.ts
- packages/@angular/cli/tasks/schematic-run.ts
> fix(@angular/cli): Pass logger to allow schematics to log messages

- packages/@angular/cli/models/command-runner.ts
- packages/@angular/cli/models/workspace-loader.ts
- packages/@angular/cli/utilities/find-up.ts
> fix(@angular/cli): Move update check to inProject command logic

- packages/@angular/cli/commands/update.ts
- tests/e2e/tests/misc/update-help.ts
> fix(@angular/cli): Fix update command help options

- packages/@angular/cli/models/schematic-command.ts
- tests/e2e/tests/generate/service/service-dry-run.ts
> fix(@angular/cli): Show dry run warning

- packages/@angular/cli/commands/version.ts
Refactored a lot of this too so its much easier to do in the future as well.
Fix #10257
> fix(@angular/cli): show rxjs and fix alignment

- packages/@angular/cli/bin/ng-update-message.js
- packages/@angular/cli/models/command-runner.ts
- packages/@angular/cli/package.json
> fix(@angular/cli): on postinstall show a message if using an old version of CLI

- packages/@angular/cli/models/command-runner.ts
> fix(@angular/cli): Respect the type of Option when parsing

- packages/@angular/cli/bin/ng-update-message.js
- packages/@angular/cli/models/command-runner.ts
> fix(@angular/cli): update the outdated CLI config message

- packages/@angular/cli/commands/update.ts
> fix(@angular/cli): disable ng update on 1.7 and show message

- packages/@angular/cli/commands/eject.ts
- packages/@angular/cli/lib/cli/index.ts
> fix(@angular/cli): add ng eject with a message about the disabling

- package-lock.json
- packages/@angular/cli/commands/config.ts
- tests/e2e/tests/commands/config/config-set.ts
Only supports currently known properties (CLI option properties).
Fixes #10415
> fix(@angular/cli): normalize cli config command options

- packages/@angular/cli/lib/config/schema.json
- tools/publish/src/build.ts
> CLI Schema Updates

- packages/@angular/cli/models/schematic-command.ts
> fix(@angular/cli): show schematics log at start of task phase

- packages/@angular/cli/commands/config.ts
- packages/@angular/cli/lib/config/schema.json
> fix(@angular/cli): update schema to include sourceRoot property

- packages/@angular/cli/bin/ng-update-message.js
> fix(@angular/cli): avoid errant migrate message on postinstall

- packages/@angular/cli/bin/ng-update-message.js
- packages/@angular/cli/commands/update.ts
- packages/@angular/cli/models/command-runner.ts
And use validate instead of run() ot change the options which is more correct.
> fix(@angular/cli): show a simpler command for ng update

- packages/@angular/cli/lib/config/schema.json
> fix(@angular/cli): make schema properly support configuration options

- packages/@angular/cli/lib/config/schema.json
Fixes #10517 
@hansl @Brocco @filipesilva
> fix(@angular/cli): defaultProject in right place in schema

- packages/@angular/cli/lib/config/schema.json
Follow up of angular/devkit#814
@filipesilva
> fix(@angular/cli): allow strings for assets in schema

- packages/@angular/cli/lib/config/schema.json
> fix(@angular/cli): correct malformed schema syntax

- packages/@angular/cli/utilities/project.ts
- tests/e2e/tests/basic/in-project-logic.ts
> fix(@angular/cli): Update in project logic

- docs/documentation/stories/configure-hmr.md
Address https://github.com/angular/angular-cli/issues/10438#issuecomment-385888456
> docs: fix hmr configuration properties

- package-lock.json
- package.json
- packages/@angular/cli/commands/doc.ts
- packages/@angular/cli/package.json
Fix https://github.com/angular/angular-cli/issues/10633
> fix(@angular/cli): fix ng doc not working

- packages/@angular/cli/commands/config.ts
- tests/e2e/tests/commands/config/config-set-serve-port.ts
> fix(@angular/cli): Fix config command setting number values

- packages/@angular/cli/models/schematic-command.ts
This allows additionalProperties to set appropriately on schematics for stricter validation
> fix(@angular/cli): Fix removal of non-schematic options

- packages/@angular/cli/lib/config/schema.json
See https://github.com/angular/devkit/pull/936
> feat(@angular/cli): support entry component

- packages/angular_devkit/core/src/workspace/workspace.ts
- packages/schematics/update/update/index.ts
- packages/schematics/update/update/index_spec.ts
- tests/legacy-cli/e2e/tests/build/platform-server.ts
> fix(@schematics/update): allow beta versions to be valid peer

- packages/angular/cli/commands/new.ts
> fix(@angular/cli): Fix double setting of the path options for new

- packages/angular/cli/lib/cli/index.ts
I found a minor typo in the error logging and fixed that
> fix: typo fix for error logging

- package-lock.json
- package.json
- packages/angular_devkit/build_angular/package.json
- scripts/validate-licenses.ts
Workaround for https://github.com/webpack/webpack/issues/7499
> feat(@angular-devkit/build-angular): revert to webpack 4.9.2

- packages/angular_devkit/schematics/src/engine/schematic_spec.ts
- packages/angular_devkit/schematics/src/rules/call.ts
Removes some unneeded casting; simplifies some of the logic; and fixes an issue with chaining rules that return rules.
> Schematic fixes

- packages/ngtools/webpack/src/paths-plugin.ts
- tests/legacy-cli/e2e/tests/misc/module-resolution.ts
> Improve path mapping support

- packages/schematics/schematics/blank/project-files/README.md
- packages/schematics/schematics/schematic/files/README.md
> docs(@schematics/schematics): add correct CLI package

- packages/angular/cli/lib/config/schema.json
- packages/angular_devkit/build_angular/src/tslint/schema.json
Also alphabetizes the list.
Fixes: #11067
Fixes: #11361
> Tslint output formatter fixes

- packages/angular_devkit/build_angular/src/server/schema.d.ts
- packages/angular_devkit/build_angular/src/server/schema.json
Fix https://github.com/angular/angular-cli/issues/11426
> fix(@angular-devkit/build-angular): add missing deploy-url to server

- docs/documentation/stories/continuous-integration.md
> docs: update commands in ci

- packages/angular/cli/commands/add.ts
- packages/angular/cli/commands/build.ts
- packages/angular/cli/commands/config.ts
- packages/angular/cli/commands/doc.ts
- packages/angular/cli/commands/e2e.ts
- packages/angular/cli/commands/easter-egg.ts
- packages/angular/cli/commands/eject.ts
- packages/angular/cli/commands/generate.ts
- packages/angular/cli/commands/getset.ts
- packages/angular/cli/commands/help.ts
- packages/angular/cli/commands/lint.ts
- packages/angular/cli/commands/new.ts
- packages/angular/cli/commands/run.ts
- packages/angular/cli/commands/serve.ts
- packages/angular/cli/commands/test.ts
- packages/angular/cli/commands/update.ts
- packages/angular/cli/commands/version.ts
- packages/angular/cli/commands/xi18n.ts
- packages/angular/cli/lib/cli/index.ts
- packages/angular/cli/models/command-runner.ts
- packages/angular/cli/models/command.ts
require() returns any so we were missing some typing errors.
> refactor: fix types to remove any

- packages/angular_devkit/build_angular/src/app-shell/index.ts
- packages/angular_devkit/build_angular/test/app-shell/app-shell_spec_large.ts
- tests/angular_devkit/build_angular/hello-world-app/angular.json
Fix https://github.com/angular/angular-cli/issues/8794
> Re-run ngsw after modifications in app-shell

- package-lock.json
- package.json
- packages/schematics/angular/workspace/files/package.json
- tests/angular_devkit/build_angular/hello-world-app/package.json
> fix(@schematics/angular): update protractor to 4.5 for new projects

- packages/angular/pwa/pwa/schema.d.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts
- packages/schematics/angular/service-worker/schema.d.ts
> fix(@angular-devkit/build-angular): do not break with Jasmine's mock clock

- package-lock.json
- package.json
- packages/angular_devkit/build_angular/package.json
Followup to #11232, includes fix for webpack/webpack#7499.
> feat(@angular-devkit/build-angular): update to webpack@4.15.1

- packages/angular/cli/upgrade/version.ts
Close #11665, angular/angular#25141
> fix(@angular/cli): use correct compiler version range

- packages/angular/cli/lib/init.ts
> fix(@angular/cli): properly bootstrap 1.x from global 6.x

- packages/angular/cli/models/command-runner.ts
Using the first flag is bad, but we still support --version and --help.
Fixes #11186
cf #11187
> fix(@angular/cli): if no command, properly show help

- packages/angular_devkit/core/src/json/parser.ts
- packages/angular_devkit/core/src/json/parser_spec.ts
Supports for new lines and hexa was useful for doc and descriptions (including
schematics and builder declarations). Adding the other numerical constants was
easy enough. This fully completes JSON5 support.
> feat(@angular-devkit/core): better support for JSON5

- scripts/publish-docs.ts
It got lost somewhere between 6.0 and 6.1.
> ci: add script for publishing the wiki

- docs/documentation/stories/universal-rendering.md
Webpack config and server.ts have been updated based on https://github.com/angular/universal-starter
> docs: update universal story

- .github/SAVED_REPLIES.md
It was deleted when we moved back from the devkit repo.
Also add a couple new replies contributed by Filipe.
> Restore SAVED_REPLIES

- packages/angular_devkit/build_angular/src/utils/run-module-worker.js
> fix(@angular-devkit/build-angular): fixes hash comparison for service worker

- packages/angular_devkit/build_angular/package.json
- yarn.lock
See https://github.com/sass/node-sass/issues/2355 for context.
Fix #11699
Related to #10963
> fix(@angular-devkit/build-angular): update node-sass

- packages/angular/pwa/pwa/index.ts
> fix(@angular/pwa): support ng add with CLI 6.0.x

- packages/schematics/update/migrate/index.ts
- packages/schematics/update/migrate/index_spec.ts
And add unit tests for it.
Fixes #11821
> fix(@schematics/update): fix logic to coerce the version number

- lib/packages.ts
Otherwise it will complain that some packages are not found in the monorepo description.
> Add support for yarn workspace in scripts

- packages/schematics/angular/application/files/src/polyfills.ts
- tests/angular_devkit/build_angular/hello-world-app/src/polyfills.ts
- tests/angular_devkit/build_webpack/angular-app/src/polyfills.ts
- tests/legacy-cli/e2e/assets/1.0-project/src/polyfills.ts
- tests/legacy-cli/e2e/assets/1.7-project/src/polyfills.ts
Corrects a broken link in a few places with the updated URL.
I believe I got all of the instances of the link in this repo.
> fix: broken links

- packages/angular_devkit/architect/testing/test-project-host.ts
- packages/angular_devkit/build_angular/test/utils.ts
- packages/angular_devkit/core/src/virtual-fs/host/test.ts
Closes: https://github.com/angular/angular-cli/issues/11992
> Fix typings

- docs/documentation/generate/library.md
> docs: fix generate library skip-install desc

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/bundle-budget.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator_spec.ts
Also enables and fixes linting
Fixes #12013
> fix(@angular-devkit/build-angular): improve bundle size value parsing

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Fix https://github.com/angular/angular-cli/pull/11996#issuecomment-416514015
> fix(@angular-devkit/build-angular): remove workaround for uglify-es

- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/postcss-cli-resources.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/webpack.ts
- yarn.lock
Clean up several parts of the styles config and also removed the dependency on `postcss-url`
//cc @filipesilva & @clydin
> refactor(@angular-devkit/build-angular): clean up style webpack config

- .appveyor.yml
- .circleci/config.yml
- WORKSPACE
- package.json
Blocked on https://github.com/angular/angular/pull/25812
Related to https://github.com/angular/angular/pull/25822
> ci: update CI to node 10

- docs/documentation/stories/asset-configuration.md
> docs: fix asset input path

- WORKSPACE
- package.json
Followup to the final changes in https://github.com/angular/angular/pull/25822.
> build: match engines with bazel and CI

- lib/packages.ts
- packages/angular/cli/package.json
- packages/angular_devkit/schematics_cli/package.json
- packages/ngtools/webpack/package.json
Fix https://github.com/angular/angular-cli/issues/12222
> build: use specific engines for built packages

- packages/angular_devkit/benchmark/package.json
- yarn.lock
Fixes https://github.com/angular/angular-cli/pull/12022#issuecomment-417278408
> build: update pidusage

- packages/angular_devkit/build_ng_packagr/package.json
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/index_spec.ts
- yarn.lock
This will fix issues with unmet peer dependencies for TypeScript 3 and Angular FW 7 beta packages
> Update ng packagr to v4.2.0

- packages/angular_devkit/build_angular/package.json
- yarn.lock
memory leak fix, security vulnerability package updates, hash integrity fix, and other minor defect fixes
> feat(@angular-devkit/build-angular): update webpack dependencies

- docs/documentation/generate.md
- docs/documentation/generate/app-shell.md
- docs/documentation/generate/application.md
- docs/documentation/generate/class.md
- docs/documentation/generate/component.md
- docs/documentation/generate/directive.md
- docs/documentation/generate/enum.md
- docs/documentation/generate/guard.md
- docs/documentation/generate/interface.md
- docs/documentation/generate/library.md
- docs/documentation/generate/module.md
- docs/documentation/generate/pipe.md
- docs/documentation/generate/service.md
- docs/documentation/generate/universal.md
Fixes #12200 
Added alias section to each doc for the generate commands.
Added appShell back to generate as it seemed to be missing.
> Updated generate doc to include aliases

- packages/angular_devkit/schematics/src/sink/sink.ts
- packages/angular_devkit/schematics/src/workflow/base.ts
Behaviour for NodeWorkflow should be the same.
> feat(@angular-devkit/schematics): allow workflow impl to define their own sinks

- docs/documentation/generate/library.md
Minor change in the overview part i included the command example to generate a library.
> docs: example command to generate library

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts
Fix for issue described on https://github.com/angular/angular-cli/issues/8046#issuecomment-401277380
> fix(@angular-devkit/build-angular): support of tsx files in aot mode

- packages/angular_devkit/schematics/src/tree/host-tree_spec.ts
> test: add unit test to cover `subdirs`

- packages/schematics/angular/library/index.ts
> fix(@schematics/angular): dasherize library package name

- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/dev-server/schema.json
- packages/angular_devkit/build_angular/test/dev-server/works_spec_large.ts
> fix(@angular/cli): `--verbose` is an unknown option of `serve`

- packages/angular/cli/upgrade/version.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/require-project-module.ts
> Improved monorepo support

- packages/angular/cli/lib/config/schema.json
- packages/schematics/angular/application/schema.json
- packages/schematics/angular/component/schema.json
- packages/schematics/angular/ng-new/schema.json
Native has been deprecated in favor of ShadowDom
https://angular.io/api/core/ViewEncapsulation
> Add support for ViewEncapsulation shadowDom

- CONTRIBUTING.md
- README.md
- scripts/templates.ts
- scripts/templates/contributing.ejs
- scripts/templates/readme.ejs
- scripts/validate-commits.ts
- scripts/validate.ts
Fix https://github.com/angular/angular-cli/issues/12401
Supersedes https://github.com/angular/angular-cli/pull/12412
> CONTRIBUTING.md and README.md changes

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
> style: remove unused locals and imports

- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/commands/update.json
> fix(@angular/cli): `ng update` remove duplicate `dryRun` in help

- package.json
- tools/yarn/check-yarn.js
Direct copy of the script from core.
> build: add check yarn preinstall script

- packages/schematics/angular/application/files/src/main.ts
> style(@schematics/angular): remove extra whitespace in EOF

- packages/schematics/angular/application/files/src/polyfills.ts
> Cleanup application polyfill comments

- packages/schematics/angular/migrations/update-7/index.ts
> fix(@schematics/angular): migrate existing packages for 7.0

- package.json
- packages/angular_devkit/build_optimizer/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/package.json
- yarn.lock
This lands a fix for this issue https://github.com/Microsoft/TypeScript/issues/27341
And solves the problem encountered by @FrozenPandaz 
```
ERROR in /Users/jason/projects/nx/tmp/proj/node_modules/@nrwl/nx/esm5/src/data-persistence.js
Module build failed (from /Users/jason/projects/nx/tmp/proj/node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
Error: Debug Failure.
at Object.assertDefined (/Users/jason/projects/nx/tmp/proj/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:1433:24)
at getJSDocHost (/Users/jason/projects/nx/tmp/proj/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:10071:25)
at getHostSignatureFromJSDoc (/Users/jason/projects/nx/tmp/proj/node_modules/@angular-devkit/b …
```
> update typescript to 3.1.3

- packages/angular_devkit/build_angular/src/karma/index.ts
> feat(@angular-devkit/build-angular): expose `buildWebpackConfig` method in `KarmaBuilder`

- docs/documentation/stories/budgets.md
Just fix a typo and add an example.
> Docs: fix budgets story

- docs/documentation/stories/universal-rendering.md
Closes: #9202
And also updated the docs to match https://github.com/angular/universal-starter
> docs: update universal rendering story

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/postcss-cli-resources.ts
- packages/angular_devkit/build_angular/test/browser/styles_spec_large.ts
> fix(@angular-devkit/build-angular): error when using protocol-relative url

- packages/schematics/angular/migrations/migration-collection.json
- packages/schematics/angular/migrations/update-7/index.ts
> fix(@schematics/angular): migrate build-angular for 7.0 RC users

- packages/schematics/angular/ng-new/index.ts
> fix(@schematics/angular): experimentalIvy creates project using `next` packages

- packages/schematics/angular/module/files/__name@dasherize@if-flat__/__name@dasherize__.module.ts
> fix(@schematics/angular) order of `module` properties is inconsistent

- packages/schematics/angular/library/files/__projectRoot__/tslint.json
Just indentation fix. Everywhere 2 space indentation is followed except this one.
> style: fix indentation in tslint.json

- packages/angular/cli/models/architect-command.ts
- packages/ngtools/webpack/src/angular_compiler_plugin.ts
> fix(@ngtools/webpack): print error message on new line

- package.json
- packages/angular_devkit/build_optimizer/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/angular/package.json
- packages/schematics/angular/utility/latest-versions.ts
- packages/schematics/schematics/blank/project-files/package.json
- packages/schematics/schematics/schematic/files/package.json
- yarn.lock
> Update to TypeScript 3.1.5

- packages/angular_devkit/build_angular/package.json
- yarn.lock
> fix(@angular-devkit/build-angular): allow only patch version of webpack

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/workspace/index.ts
- packages/schematics/angular/workspace/index_spec.ts
fix(@schematics/angular): minimal should be honored in workspace creation
refactor: clean up code for minimal flag
> Minimal flag

- packages/ngtools/webpack/src/angular_compiler_plugin.ts
- packages/ngtools/webpack/src/compiler_host.ts
- packages/ngtools/webpack/src/transformers/ast_helpers.ts
- packages/ngtools/webpack/src/type_checker.ts
> feat(@ngtools/webpack): disable sourcefile cache when not in watch mode

- tslint.json
tslint does support comments in json
> style: add comments in tslint.json

- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/class/index_spec.ts
- packages/schematics/angular/component/index_spec.ts
- packages/schematics/angular/directive/index_spec.ts
- packages/schematics/angular/e2e/index_spec.ts
- packages/schematics/angular/enum/index_spec.ts
- packages/schematics/angular/guard/index_spec.ts
- packages/schematics/angular/interface/index_spec.ts
- packages/schematics/angular/library/index_spec.ts
- packages/schematics/angular/module/index_spec.ts
- packages/schematics/angular/ng-new/index_spec.ts
- packages/schematics/angular/pipe/index_spec.ts
- packages/schematics/angular/service/index_spec.ts
- packages/schematics/angular/workspace/index_spec.ts
> tests: use `toContain` instead of `indexOf`

- packages/ngtools/webpack/src/resource_loader.ts
> fix(@ngtools/webpack): update error message to reference templateUrl

- .editorconfig
- packages/schematics/angular/workspace/files/__dot__editorconfig
- tests/angular_devkit/build_angular/hello-world-app/.editorconfig
- tests/legacy-cli/e2e/assets/1.0-project/.editorconfig
- tests/legacy-cli/e2e/assets/1.7-project/.editorconfig
> style: update editorconfig website url

- packages/angular/cli/commands/e2e-long.md
- packages/angular/cli/commands/lint-long.md
- packages/angular/cli/commands/test-long.md
- packages/angular/cli/commands/test.json
> docs: update long descriptions for test, e2e and lint

- packages/angular/cli/utilities/package-manager.ts
> fix(@angular/cli): silence package manager not found messages

- scripts/packages.ts
Added a --json arg for old output.
> ci: packages script should list public packages

- packages/schematics/angular/workspace/files/__dot__gitignore
> feat(@schematics/angular): add .history directory to gitignore

- packages/angular/cli/commands/update-long.md
There is an extra character at the end of the line.
> docs: remove spurious character(s) in update-long.md

- docs/documentation/stories/1.0-update.md
> docs: fix config name in update   Fixes #13028

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/cleancss-webpack-plugin.ts
Remove code that was previous required for Webpack 3
> refactor: remove webpack 3 code from cleancss plugin

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/scripts-webpack-plugin.ts
Remove code that was previous required for Webpack 3
> refactor: script webpack plugin remove webpack 3 code

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Typo introduced by af67b49342dec3159fd38cb01ac1f47b1f188775
> style(@angular-devkit/build-angular): typo in stylesSourceMap

- docs/documentation/stories.md
Autocomplete is not longer available in version 6/7
> docs: remove autocomplete link

- packages/schematics/angular/library/files/__projectRoot__/README.md
- packages/schematics/angular/library/index_spec.ts
> feat(@schematics/angular): generate a library with a README.md file

- packages/angular_devkit/build_angular/package.json
- yarn.lock
Backport https://github.com/angular/angular-cli/pull/13229 to patch
Fixes #13329
> build: update license-webpack-plugin to version 2.0.4

- packages/angular_devkit/build_angular/package.json
- yarn.lock
Backport https://github.com/angular/angular-cli/pull/13277 to patch
Fixes #13342
> build: update webpack-dev-server to version 3.1.14

- packages/schematics/angular/guard/files/__name@dasherize__.guard.ts
> feat(@schematics/angular): add UrlTree to CanActivate method signature

- packages/angular_devkit/build_angular/src/angular-cli-files/plugins/scripts-webpack-plugin.ts
- packages/angular_devkit/build_angular/test/browser/scripts-array_spec_large.ts
> fix(@angular-devkit/build-angular): script chunk in angular.json return false then calling isInitial

- .mailmap
He uses many addresses and some of his computers are not configured
properly :P
> build: add Alan to the mailmap file

- packages/angular/cli/commands/add.json
- packages/angular/cli/commands/definitions.json
- packages/angular/cli/commands/generate.json
- packages/angular/cli/commands/new.json
> fix(@angular/cli): remove unsupported `dryRun` and `force` from `ng add`

- packages/schematics/angular/package.json
Fixed inconsistency in typescript versions, in other packages it was pinned in https://github.com/angular/angular-cli/pull/13468
> fix(@schematics/angular): update typescript to 3.2.4

- packages/angular_devkit/build_angular/package.json
- yarn.lock
> fix(@angular/cli): update terser-webpack-plugin

- packages/angular_devkit/core/node/_golden-api.ts
- packages/angular_devkit/core/node/experimental/jobs/index.ts
- packages/angular_devkit/core/node/experimental/jobs/job-registry.ts
- packages/angular_devkit/core/node/experimental/jobs/job-registry_spec.ts
- packages/angular_devkit/core/node/index.ts
- packages/angular_devkit/core/src/experimental/jobs/api.ts
- packages/angular_devkit/core/src/experimental/jobs/create-job-handler.ts
- packages/angular_devkit/core/src/experimental/jobs/fallback-registry.ts
- packages/angular_devkit/core/src/experimental/jobs/index.ts
- packages/angular_devkit/core/src/experimental/jobs/simple-scheduler.ts
- packages/angular_devkit/core/src/experimental/jobs/simple-scheduler_spec.ts
- packages/angular_devkit/core/src/experimental/jobs/strategy.ts
- packages/angular_devkit/core/src/experimental/jobs/strategy_spec.ts
Each of these commits is pretty much its own thing, but in general this is improving on Jobs.
Most of these came up as I was working on Architect Proof of Concept. As the design has been approved, this is the first PR to really cleanup Jobs in preparation for a solid first Architect PR.
It's a lot of small commits, each commits are simple enough to review in a minute or two.
> Jobs yak shaving for Architect

- packages/angular/cli/lib/config/schema.json
- packages/angular/cli/tasks/npm-install.ts
- packages/angular_devkit/schematics/tasks/node-package/executor.ts
> Support pnpm as a package manager option

- packages/schematics/angular/application/files/root/karma.conf.js.template
- packages/schematics/angular/library/files/__projectRoot__/karma.conf.js.template
fix for this issue https://github.com/angular/angular-cli/issues/13542
> fix(@schematics/angular): set restartOnFileChange to true in karma.conf templates

- .circleci/config.yml
- tests/legacy-cli/e2e/setup/500-create-project.ts
- tests/legacy-cli/e2e/tests/build/build-errors.ts
- tests/legacy-cli/e2e/utils/project.ts
- tests/legacy-cli/e2e_runner.ts
Blocked on https://github.com/angular/angular/pull/28372 (merged)
Successful CI run (needed because this job is only active in master): https://circleci.com/gh/angular/angular-cli/38794?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> Ivy Snapshots e2e job

- scripts/validate-commits.ts
And remove the usage of "blacklist" while Im at it.
> build: fix invalid commits that made it through

- packages/schematics/angular/library/files/tsconfig.lib.json.template
- tests/angular_devkit/build_ng_packagr/ng-packaged/projects/lib/tsconfig.lib.json
These properties are already defined in the root tsconfig
> refactor: clean up library tsconfig

- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/bundle-calculator_spec.ts
Fixes https://github.com/angular/angular-cli/issues/13555
> fix(@angular-devkit/build-angular): minimum threshold

- packages/schematics/angular/workspace/files/__dot__vscode/extensions.json.template
> fix(@schematics/angular): fix missing semicolons in extensions.json.template

- packages/schematics/angular/workspace/files/package.json.template
Fixes #13724
This has already be done on master.
> fix(@schematics/angular): update karma to version 4

- packages/schematics/angular/application/files/root/tsconfig.app.json.template
- tests/legacy-cli/e2e/tests/experimental/ivy.ts
Blocked on https://github.com/angular/angular/pull/28616
> fix(@schematics/angular): use enableIvy as true

- package.json
- packages/angular/pwa/package.json
- packages/angular_devkit/architect/builders/all-of.ts
- packages/angular_devkit/architect/package.json
- packages/angular_devkit/architect/test/package.json
- packages/angular_devkit/architect_cli/package.json
- packages/angular_devkit/benchmark/package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/app-shell/index.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/karma/index.ts
- packages/angular_devkit/build_angular/src/tslint/index.ts
- packages/angular_devkit/build_ng_packagr/package.json
- packages/angular_devkit/build_webpack/package.json
- packages/angular_devkit/core/node/host.ts
- packages/angular_devkit/core/package.json
- packages/angular_devkit/core/src/json/schema/registry.ts
- packages/angular_devkit/core/src/virtual-fs/host/record.ts
- packages/angular_devkit/schematics/package.json
- packages/angular_devkit/schematics/src/tree/host-tree.ts
- packages/angular_devkit/schematics/src/workflow/base.ts
- packages/angular_devkit/schematics_cli/package.json
- packages/ngtools/webpack/package.json
- packages/schematics/update/package.json
- packages/schematics/update/update/npm.ts
- yarn.lock
Supersedes https://github.com/angular/angular-cli/pull/13545
> build: update to rxjs 6.4

- packages/schematics/angular/application/files/root/tsconfig.app.json.template
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/application/schema.json
- packages/schematics/angular/ng-new/index.ts
- packages/schematics/angular/ng-new/schema.json
- tests/legacy-cli/e2e/setup/500-create-project.ts
- tests/legacy-cli/e2e/tests/experimental/ivy-lazy-load.ts
- tests/legacy-cli/e2e/tests/experimental/ivy.ts
- tests/legacy-cli/e2e/utils/project.ts
Followup to https://github.com/angular/angular/pull/28569#discussion_r259558085
> feat(@schematics/angular): rename experimentalIvy to enableIvy

- .circleci/config.yml
ci: use fallback cache
Port of angular/angular#28545
ci: update circleci post checkout to v2 syntax
Port of angular/angular#28472
> Use fallback cache and correct post checkout on CI

- package.json
- yarn.lock
Also updates hook configuration to non-deprecated format.
> build: update husky to 1.3.1

- packages/angular_devkit/build_angular/test/browser/lazy-module_spec_large.ts
- packages/schematics/angular/workspace/files/tsconfig.json.template
- tests/angular_devkit/build_angular/hello-world-app/src/tsconfig.app.json
- tests/angular_devkit/build_angular/hello-world-app/src/tsconfig.spec.json
- tests/angular_devkit/build_angular/hello-world-app/tsconfig.json
- tests/legacy-cli/e2e/tests/experimental/ivy-lazy-load.ts
- tests/legacy-cli/e2e_runner.ts
Context on these usecases can be found here: https://github.com/angular/angular/pull/28685#discussion_r259891817
> test: add comprehensive tests for Ivy lazy load styles

- tests/legacy-cli/e2e/tests/experimental/ivy-lazy-load.ts
> test: fix paths for ivy lazy loading tests

- packages/schematics/angular/service-worker/files/ngsw-config.json.template
- packages/schematics/angular/service-worker/index.ts
- packages/schematics/angular/service-worker/index_spec.ts
Fixes #13324 
Depends on angular/angular#27859
> feat(@schematics/angular): JSON schema for service worker config

- packages/angular_devkit/core/src/analytics/api.ts
- packages/angular_devkit/core/src/analytics/forwarder.ts
- packages/angular_devkit/core/src/analytics/index.ts
- packages/angular_devkit/core/src/analytics/logging.ts
- packages/angular_devkit/core/src/analytics/multi.ts
- packages/angular_devkit/core/src/analytics/noop.ts
- packages/angular_devkit/core/src/index.ts
- scripts/validate-do-not-submit.ts
- scripts/validate.ts
This is a preliminary analytics interface. It is meant to be used by every
other subsystem where useful, but can be replaced by implementations.
> feat(@angular-devkit/core): analytics interfaces and basic implementations

- packages/angular_devkit/architect/src/api.ts
- packages/angular_devkit/architect/src/api_spec.ts
- packages/angular_devkit/architect/src/create-builder.ts
- packages/angular_devkit/build_angular/src/browser/index2.ts
- packages/angular_devkit/build_angular/src/dev-server/schema.json
- packages/angular_devkit/build_angular/src/index.ts
These came out when discussing with Nrwl. They should be in before the next release.
> Architect qol 2

- .monorepo.json
- docs/process/release.md
- lib/packages.ts
- packages/angular/pwa/package.json
- packages/angular_devkit/architect/package.json
- packages/angular_devkit/architect_cli/package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_ng_packagr/package.json
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/build_webpack/package.json
- packages/angular_devkit/schematics_cli/package.json
- packages/schematics/schematics/package.json
- packages/schematics/update/package.json
- scripts/publish.ts
- scripts/release.ts
- scripts/test.ts
Just got a mistake (caught in time) so decided to do a long overdue refactoring for release script(s).
> Various QoL for caretaker

- packages/angular/cli/commands/version-impl.ts
> feat(@angular/cli): add `@nguniversal/*` to ng version

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts
- packages/angular_devkit/build_angular/src/browser/index.ts
- packages/angular_devkit/build_angular/src/browser/index2.ts
- packages/angular_devkit/build_angular/src/extract-i18n/index.ts
- packages/angular_devkit/build_angular/src/karma/index.ts
- packages/angular_devkit/build_angular/src/server/index.ts
Removes several redundant and unused methods/parameters.
> Minor Webpack Configuration Cleanup

- .circleci/config.yml
- tests/legacy-cli/e2e/ng-snapshot/package.json
- tests/legacy-cli/e2e/utils/project.ts
- tests/legacy-cli/e2e_runner.ts
Next step is to set up Renovate to send PRs against this package.json file
> test: pin Angular snapshot versions

- renovate.json
Related to https://github.com/angular/angular-cli/pull/13914
> ci: add legacy cli snapshot paths to renovated paths

- packages/angular_devkit/architect/src/index2_spec.ts
See https://github.com/angular/angular-cli/commit/fe229faf784b5cfde16281e11c3470c9c0c02c32
> test: fix invalid architect tests

- tests/legacy-cli/e2e/utils/project.ts
Successful snapshot https://circleci.com/gh/angular/angular-cli/46092
> ci: remove hardcoded typescript version for snapshots

- packages/angular/cli/models/analytics.ts
> fix(@angular/cli): fix import path for TimingOptions

- packages/angular/cli/commands/config-impl.ts
- packages/angular/cli/models/analytics.ts
- packages/angular/cli/models/command-runner.ts
> Feature: Analytics sharing implementation

- packages/angular_devkit/build_ng_packagr/package.json
- packages/angular_devkit/build_ng_packagr/src/build/index.ts
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/index_spec.ts
- yarn.lock
Changelog https://github.com/ng-packagr/ng-packagr/blob/master/CHANGELOG.md#500-2019-03-27
> Update to ng-packagr version 5

- packages/angular/cli/BUILD
- packages/angular/cli/models/architect-command.ts
- packages/angular_devkit/architect/src/schedule-by-name.ts
- packages/angular_devkit/build_angular/src/server/index2.ts
- packages/angular_devkit/core/src/experimental/workspace/workspace.ts
Conversion of the CLI to use the new stable architect API.
Additional refactoring and cleanup is possible.  The goal of this PR is to get the capabilities introduced.
> feat(@angular/cli): support stable architect API

- packages/angular_devkit/build_angular/plugins/webpack/analytics.ts
This cause errors to be printed out multiple times
> refactor: remove console logs from analytics

- packages/angular/cli/models/analytics.ts
Make the language a little bit clearer.
> fix(@angular/cli): improve opt-out language

- packages/angular_devkit/build_angular/src/angular-cli-files/models/safari-nomodule.js
- packages/angular_devkit/build_angular/src/angular-cli-files/models/safari-nomodule.min.js
> add safari-nomodule snippet

- tests/legacy-cli/e2e/tests/build/script-target.ts
This has been resolved in angular/compiler-cli version 8.0.0-beta.10
> test: enable script target e2e for ivy

- package.json
- packages/angular_devkit/build_ng_packagr/package.json
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/index_spec.ts
- packages/schematics/angular/workspace/files/package.json.template
- yarn.lock
With this change we update ng-packagr, jasmine-core and tslint.
>  feat(@schematics/angular): update several workspace dependencies 

- packages/schematics/angular/application/files/browserslist.template
//cc @brandonroberts since you mentioned this a couple of days ago.
> feat(	@schematics/angular): add more information and browsers in browserlist

- etc/api/angular_devkit/core/src/_golden-api.d.ts
- packages/angular/pwa/pwa/index_spec.ts
- packages/angular_devkit/core/src/workspace/definitions.ts
- packages/angular_devkit/core/src/workspace/json/writer.ts
- packages/schematics/angular/app-shell/index_spec.ts
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/class/index_spec.ts
- packages/schematics/angular/component/index.ts
- packages/schematics/angular/component/index_spec.ts
- packages/schematics/angular/directive/index.ts
- packages/schematics/angular/directive/index_spec.ts
- packages/schematics/angular/e2e/index.ts
- packages/schematics/angular/e2e/index_spec.ts
- packages/schematics/angular/enum/index_spec.ts
- packages/schematics/angular/guard/index_spec.ts
- packages/schematics/angular/interface/index.ts
- packages/schematics/angular/interface/index_spec.ts
- packages/schematics/angular/library/index_spec.ts
- packages/schematics/angular/module/index.ts
- packages/schematics/angular/module/index_spec.ts
- packages/schematics/angular/ng-new/index_spec.ts
- packages/schematics/angular/pipe/index.ts
- packages/schematics/angular/pipe/index_spec.ts
- packages/schematics/angular/service-worker/index.ts
- packages/schematics/angular/service-worker/index_spec.ts
- packages/schematics/angular/service/index_spec.ts
- packages/schematics/angular/universal/index_spec.ts
- packages/schematics/angular/web-worker/index_spec.ts
This fixes several bugs and updates the remainder of the Angular schematics. Each schematic update is in a separate commit. Tests needed to be updated to use the async version of the test runner but are otherwise unmodified.
> Complete Angular Schematic updates to new workspace rules

- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/service-worker/index.ts
This cleans up the service worker build augmentation code that was transferred nearly verbatim from CLI 1.x.
> refactor(@angular-devkit/build-angular): cleanup service-worker augmentation

- packages/schematics/angular/application/files/browserslist.template
We want apps to be SEO friendly by default. // cc @alexeagle
> feat(@schematics/angular): enable support for Chrome 41

- packages/angular_devkit/build_angular/src/browser/index.ts
When using differential loading with targets ES5 and ES2016+, the
browser with ESM support will pick `script[type="module"]` scripts even
without supporting ES2016+ syntax.
We want to warn users in this case.
> feat(@angular-devkit/build-angular): warn when target greater es2015

- packages/schematics/angular/migrations/update-8/update-builders.ts
> fix(@schematics/angular): update zone.js version during CLI 8.0 migration

- packages/angular/cli/commands/add-impl.ts
- packages/angular/cli/commands/add.json
This PR close https://github.com/angular/angular-cli/issues/14189
> feat(@angular/cli): implement --registry for ng add

- packages/angular_devkit/build_angular/package.json
- yarn.lock
> fix(@angular-devkit/build-angular): update node-sass to 4.12.0

- packages/angular/cli/commands/update-long.md
- packages/schematics/update/update/schema.json
Remove specific reference to version 7
Add note about using "next" flag
Edit all option descriptions for style
Related Issues
https://github.com/angular/angular/issues/29742
https://github.com/angular/angular/issues/30286
> docs: edit reference doc for update command

- scripts/templates/changelog-feat.ejs
- scripts/templates/changelog-fix.ejs
> docs: fixes the changelog commits format

- packages/angular_devkit/architect/node/node-modules-architect-host.ts
- packages/angular_devkit/core/README.md
- packages/angular_devkit/core/src/workspace/core.ts
An initial overview of the capabilities.  More in-depth information will be added incrementally.
> docs(@angular-devkit/core): add preliminary overview of workspace API

- etc/api/angular_devkit/schematics/src/_golden-api.d.ts
- packages/angular_devkit/schematics/src/rules/base.ts
- packages/angular_devkit/schematics/src/rules/call.ts
rxjs has improved over time and this updates the rules to take advantage of improvements where applicable.  Also includes some general code formatting.
> refactor(@angular-devkit/schematics): update rxjs usage in rules

- packages/angular/cli/tasks/npm-install.ts
> fix(@angular/cli): print full error when package is not found

- packages/angular_devkit/core/BUILD
- packages/angular_devkit/schematics/BUILD
external code block should not include deps.
> build: fix external block in BUILD files

- packages/angular/cli/models/architect-command.ts
> fix(@angular/cli): enable analytics for safe builders

- packages/angular_devkit/build_angular/package.json
- packages/schematics/angular/utility/latest-versions.ts
- yarn.lock
Related to https://github.com/angular/angular/issues/30203
> fix(@schematics/angular): update zone.js to 0.9.1

- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/commands/update.json
- packages/angular/cli/package.json
- packages/angular/cli/tasks/npm-install.ts
- packages/angular/cli/utilities/package-metadata.ts
- packages/angular/cli/utilities/package-tree.ts
- packages/schematics/update/migrate/index.ts
- yarn.lock
This adds extensive option checking and error handling with the goal to catch user errors as early in the process as possible.  Bad option combinations and/or values will result in actionable information and stop the process before network access and processing occurs.  Executing migration packages are now also displayed to the user as well.
> Update command option checking/error reporting improvements

- packages/angular/cli/models/analytics.ts
- packages/angular/cli/models/schematic-command.ts
- packages/angular/cli/utilities/tty.ts
- tests/legacy-cli/e2e/tests/misc/ask-analytics.ts
> fix(@angular/cli): show analytics prompt when no global configuration file

- packages/angular/cli/utilities/tty.ts
Covers common CI platforms.
Fixes #14563
> fix(@angular/cli): check for CI environment variable in tty helper

- packages/angular/cli/commands/update-impl.ts
> fix(@angular/cli): avoid updating when package is already up to date

- packages/ngtools/webpack/src/compiler_host.ts
- packages/ngtools/webpack/src/resource_loader.ts
This method enables the Ivy incremental compiler to track changes to resource files and their requisites.
Related https://github.com/angular/angular/pull/30954
> fix(@ngtools/webpack): implement getModifiedResourceFiles for Ivy AOT

- packages/angular/cli/bin/postinstall/analytics-prompt.js
> fix(@angular/cli): ensure analytics prompt exceptions are caught

- packages/angular/cli/lib/cli/index.ts
Whenever an unhandled exception during command processing occurs, the message and stack trace will be saved to a debug log located in a temporary directory.  The user will be informed of the log location as well as the exception message and instructions to file a bug report at the GitHub repository.
> feat(@angular/cli): log unhandled exceptions

- packages/schematics/angular/workspace/files/tsconfig.json.template
> fix(@schematics/angular): Remove duplicate entries for module and moduleResolution

- docs/design/analytics.md
- etc/api/angular_devkit/core/src/_golden-api.d.ts
- packages/angular/cli/models/analytics.ts
- packages/angular_devkit/core/src/analytics/index.ts
Otherwise its too much noise. Some people have weird MB count probably due to
containers and VMs.
> feat(@angular/cli): report RAM in gigabytes instead of megabytes

- packages/angular/cli/models/command.ts
We might want to pass those later.
> fix(@angular/cli): pass in metrics to the pageview for commands

- .circleci/config.yml
- .lintstagedrc
- package.json
- yarn.lock
> build: stop code formatting with prettier

- scripts/publish.ts
Fixes Windows E2E CI runs on master.
> build: support publishing on windows

- tests/legacy-cli/e2e/tests/packages/webpack/test-app.ts
See https://github.com/angular/angular/issues/31404 for details.
> test: update ngtools/webpack size check

- packages/schematics/angular/ng-new/schema.json
> fix(@schematics/angular): update sass documentation links

- packages/schematics/angular/migrations/update-8/update-dependencies.ts
- packages/schematics/angular/utility/latest-versions.ts
Related to https://github.com/angular/angular-cli/issues/14589#issuecomment-508026441
> fix(@schematics/update): update `@angular/pwa` when migrating to 8

- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/test/browser/resolve-json-module_spec_large.ts
- packages/angular_devkit/build_webpack/package.json
- packages/ngtools/webpack/package.json
- yarn.lock
Supersedes https://github.com/angular/angular-cli/pull/15019
> build: update webpack to version 4.35.3

- .circleci/config.yml
- .circleci/env-helpers.inc.sh
- .circleci/env.sh
- tests/legacy-cli/e2e/setup/300-log-environment.ts
Prep work (and some cleanup) for saucelabs-based differential loading testing.
The environment shell scripts have been transferred from FW.
> CircleCI Configuration Refactor

- packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
Most of the logic that can find class statements to wrap can be used to wrap Enums, with the exception of TS 2.3+ enums which is slightly different.
This PR combines the enums and classes lookup logic and also simplifies the TS 2.3+ enum lookup logic
> refactor(@angular-devkit/build-optimizer): refactor wrap enums

- packages/angular/cli/models/analytics.ts
> feat(@angular/cli): report telemetry opt-ins

- tests/legacy-cli/e2e/assets/protractor-saucelabs.conf.js
> test: fix safari 10.1 e2e differential loading browser test

- tests/legacy-cli/e2e/tests/generate/library/library-consumption.ts
Update library-consumption e2e test to run protractor to verify that the library consumption works both during build and runtime.
//cc @vikerman
> test: add library consumption protractor test

- packages/angular_devkit/core/src/json/schema/registry_spec.ts
- packages/angular_devkit/core/src/json/schema/transforms.ts
Related to https://github.com/angular/angular-cli/pull/15207#discussion_r309175463
> fix(@angular-devkit/core): add schema defaults when value is undefined

- .circleci/config.yml
- scripts/test.ts
A jail job for known flakes.
Fix https://github.com/angular/angular-cli/pull/15204
> ci: add flake jail

- packages/schematics/angular/application/other-files/app.component.ts.template
Update the template of `app.component.ts` when using `--inlineTemplate`.
> fix(@schematics/angular): handle the inlineTemplate case for ng new

- packages/schematics/angular/application/other-files/app.component.html.template
Added twitter link icon to the toolbar of the ng new default project template
Closes #15316 
FYI @mgechev | CC: @vikerman
> fix(@schematics/angular): add twitter link icon

- packages/schematics/angular/utility/latest-versions.ts
> fix(@schematics/angular): update tsickle to 0.37.0

- packages/angular_devkit/build_angular/src/utils/process-bundle.ts
- tests/legacy-cli/e2e/tests/build/prod-build.ts
Patch version of https://github.com/angular/angular-cli/pull/15477
> Patch for #15477

- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
- packages/angular_devkit/build_angular/test/browser/aot_spec_large.ts
- yarn.lock
Full list of changes https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#800-2019-08-29
> feat(@angular-devkit/build-angular): update sass-loader to 8.0.0

- .github/workflows/lock-closed.yml
Begins process for #15532
Completes, for cli, https://github.com/angular/dev-infra/issues/16
> ci: set up angular-automatic-lock-bot for the repo

- packages/schematics/angular/migrations/migration-collection.json
> feat(@schematics/angular): run lazy loading migration for version 9

- packages/angular/cli/commands/update-impl.ts
- packages/angular/cli/utilities/package-metadata.ts
- packages/angular/cli/utilities/package-tree.ts
- packages/schematics/update/update/index.ts
> Several ng update fixes

- renovate.json
See: https://docs.renovatebot.com/configuration-options/#lockfilemaintenance
> ci: enable renovate lockFileMaintenance

- packages/angular/cli/lib/config/schema.json
> fix(@angular/cli): add browser builder index option longhand form to schema

- packages/angular_devkit/build_angular/src/browser/index.ts
> fix(@angular-devkit/build-angular): workaround Node.js copyFile defect on macOS

- packages/angular/cli/models/parser.ts
> fix(@angular/cli): do not warn on multiple array option use
